### ISSUE TITLE
zebrad will not pick up zebrad.toml from same directory 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1005]
**Version**

Introduced in  #946

**Description**
Our docker images that run zebrad nodes assume that just placing the config in the same dir will pick it up, this is no longer true. Since we use the tracing endpoint as a healthcheck endpoint, our deployments are marked as unhealthy.

**Comment by yaahc** [comment]
Worth noting that this change was intentional and requested in https://github.com/ZcashFoundation/zebra/issues/976.

**Comment by dconnolly** [comment]
Yeah it's a bug that we didn't update our docker image, not really a bug in zebrad
