### ISSUE TITLE
Make the state service return an empty block locator if the state is empty

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1024]
We want to simplify the state service block locator interface, by removing the genesis hash special case.

This special case isn't actually used by the sync service, because it downloads the genesis block without a block locator.

Original comment:
https://github.com/ZcashFoundation/zebra/pull/902#discussion_r484647276_

TODO:
- [ ]  If the state is empty, return an empty block locator

**Comment by teor2345** [comment]
Edit: let's do it like the sync service, and just store the genesis hash

**Comment by hdevalence** [comment]
Another alternative would be to return nothing at all -- do we need to include the genesis hash in the response?

**Comment by hdevalence** [comment]
Currently the sync component stores the genesis hash and uses it to pre-populate a block locator object in case the state is empty.  But if we made the state return an empty block locator when the state is empty, we could keep the existing special-case code in the sync component for downloading the genesis block, and then proceed as normal.   Then we wouldn't have to special case loading anything into the state or having hardcoded values.  WDYT?

**Comment by teor2345** [comment]
Yeah I think that's simpler, I'll update the ticket.

**Comment by teor2345** [comment]
Fixed quite a while ago, at least in the state service.
