### ISSUE TITLE
Create error enums in zebra-consensus.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1029]
**Is your feature request related to a problem? Please describe.**

`zebra-consensus` handles verification of blocks and transactions.  This means that it needs to report errors on verification failures.

**Describe the solution you'd like**

Rather than building ad-hoc errors with string descriptions, `zebra-consensus` could have `BlockError` and `TransactionError` enums, whose variants exhaustively enumerate all possible verification failures.  This would be useful because each error variant corresponds to a consensus rule, so enumerating all possible verification failures enumerates the consensus rules we implement, and ensures that we don't reject blocks or transactions for any non-enumerated reason.

```rust
use thiserror::Error;

#[derive(Error, Debug)]
pub enum TransactionError {
    // ... transaction errors ...
}

#[derive(Error, Debug)]
pub enum BlockError {
    /// The block contained an invalid transaction.
    #[error("invalid transaction")]
   Transaction(#[from] TransactionError),
    // ... other block errors ...
}
```

Zcashd also enumerates verification failures, so we can crossreference the enum variants with the Zcashd verification failure modes.

**Describe alternatives you've considered**

Currently, the consensus checks generate ad-hoc errors with string formatting.  This makes it hard to see what all the potential verification failures are.  In addition, the more consensus checks we implement, the more work it will be to enumerate errors.

**Comment by oxarbitrage** [comment]
Will try to make some progress on this one in the next day(s).
