### ISSUE TITLE
Refactor Zebrad functionality into logical components

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1030]
**Is your feature request related to a problem? Please describe.**

Zebrad's functionality is organized somewhat haphazardly.  Originally, we planned to organize things using Abscissa components, but we ran into two main problems:

1.  Abscissa's dependency injection system can't atomically inject dependencies.  If component `A` depends on components `B` and `C`, dependency injection doesn't provide `(B, C)` to `A`, it provides either `B` and then `C` or `C` and then `B`.  This is very difficult to manage, since a component has to have a bunch of intermediate states to compensate.

2.  Abscissa's component system doesn't really work well with async functionality.

**Describe the solution you'd like**

We should keep the `zebrad::components` module, but not make all of the structures it contains implement Abscissa's `Component` trait, and perform setup manually.  Then, perform rearrangement and cleanup:

- [ ] Make submodules of `component` private, and re-export their contents out of the `component` module, making the public API have, e.g., `zebrad::components::Tokio` rather than `zebrad::components::tokio::TokioComponent` (even though the `Tokio` struct is defined in the `tokio` submodule);

- [x] Create the following components:

    - [x] `Sync`: move the code from `zebrad::commands::start::sync` into a `Sync` component in `components::sync`.  The `Sync` struct should have a constructor or builder that passes in the network, verifier, and state services, and a `async run(mut self)` method that spawns the task. Done in #1040.

    - [x] `Inbound`: consume and refactor the code from the `seed` command (deleting the `seed` command when finished), along the lines of the changes in #878.  This has to have a 2-phase setup (see the current `seed` command or the code in #878) because of a cyclic dependency between the inbound and outbound network services.  In addition to the address book, the inbound service also needs handles for the network, verifier, and state services. Done in #1071.

- [x] Change the `start` command to construct the inbound and sync components (these are not abscissa components, and have to be constructed manually).

**Comment by hdevalence** [comment]
This is a prerequisite for #889.

**Comment by mpguerra** [comment]
> This is a prerequisite for #889.

How does this affect the inbound message handling tickets that are required for the First Alpha Release?

**Comment by hdevalence** [comment]
I think we can call this done, the only remaining work is some code reorganization that doesn't have to be coupled to any further work.
