### ISSUE TITLE
Reverse displayed endianness of transaction and block hashes.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1031]
**Is your feature request related to a problem? Please describe.**

Zcashd, for bad legacy reasons, displays block and transaction hashes as the hex-encoding of the *reversal* of the byte string.  This is solely a display choice.  Hashes are parsed as byte sequences as normal, but displayed differently.  Why? They are displayed as if the hex output (a byte string) were actually encoding of an integer, which can have an ordering for proof of work checks.

In Zebra, we try not to replicate bad legacy decisions from Zcashd by default, unless we have a good reason to do to (or have to, for compatibility).  So we originally didn't implement this reverse-endianness display.  However, this is a pretty bad user-experience.

**Describe the solution you'd like**

- [x] Change `Debug`, `Display`, and `FromStr` for `block::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Remove the `byte_reverse_hex` function from `zebra-utils/src/bin/zebra-checkpoints/main.rs`.
- [x] Use `zebrad revhex` to reverse all existing `block::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
  - [x] Regenerate the hard-coded `main-checkpoints.txt` and `test-checkpoints.txt’ checkpoint lists using the modified `zebra-checkpoints` binary.
- [x] Change `Debug`, `Display`, and `FromStr` for `transaction::Hash` to display the encoding of the reversed byte sequence, and to reverse a hex encoding during parsing.
- [x] Use `zebrad revhex` to reverse all existing `transaction::Hash` literals in the source code.  To find them, commenting out the `FromStr` impl should turn all `.parse()` invocations into compile errors.
  - [x] Compile using `cargo test`, so that you find hash literals in test code.
- [x] Remove the `zebrad revhex` command.
  - [x] Stop using `zebrad revhex` in the `zebrad-hash-lookup` script.

**Comment by teor2345** [comment]
I added some extra tasks:
* reverse the hard-coded checkpoint hashes
* stop using revhex in the log filter scripts
* compile in test mode, so you find hash literals in the tests

**Comment by hdevalence** [comment]
I don't think that it's necessary to reverse the hard-coded checkpoint hashes, because they can just be regenerated from `zebra-checkpoints`.
