### ISSUE TITLE
Cancel download and verify tasks if the sync service has dropped the channel

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1037]
**Version**

zebrad main branch, around 2020-09-09.

**Platform**

All.

**Description**

When the sync service encounters an error, it drops the futures for the download and verify tasks that it has spawned. But those tasks continue executing in the background.

I tried this:

Running a `zebrad sync` for 30+ minutes, on mainnet or testnet.

I expected to see this happen:

The sync service recovers from errors, and successfully downloads the next checkpoint.

Instead, this happened:

Sometimes, the sync service triggers a cascading series of errors, where each error is made more likely by the pending tasks from previous syncs.

**Proposed Solution**

The sync service drops the futures for the download and verify tasks that it has spawned. This also drops the receiving end of the channels for those futures.

We can check those channels at two different points, and cancel the task if they have been dropped:
1. When the network request is about to be sent to a peer
  - We might need to pass the channel into the download request to perform this check
2. When the block has been downloaded, before the task starts verifying the block

**Further Information**

See the original conversation at https://github.com/ZcashFoundation/zebra/pull/980#issuecomment-689131115

**Comment by teor2345** [comment]
@hdevalence did this get done as part of the download set PR?

**Comment by hdevalence** [comment]
Yes, it did.
