### ISSUE TITLE
Test translation for zebra-network::{Request, Response} protocol

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1048]
**Is your feature request related to a problem? Please describe.**

We need to complete the translation layer between Bitcoin messages and `zebra_network::{Request, Response}` pairs. 

**Describe the solution you'd like**

- [x] Each `Message` variant should generate a `zebra_network::Request`, or be explicitly ignored.  Each `zebra_network::Response` variant should generate a `Message`, or in the case of `Response::Nil`, generate no message. (Done in #1075) 

- [ ] Refactor the Zebra requests and response state into distinct request/response pairs (#1515)

- [ ] The translation should be tested by connecting two connection state machines and seeing that they translate back and forth correctly.

- [ ] The translation should be tested against `zcashd`, as much as possible

Some of this work was implemented a long time ago, and some of it was implemented in #1016. The rest is to be completed.

Prerequisite for actually handling the requests in #889.

**Comment by teor2345** [comment]
We have implemented the network protocol, and have partial tests between two zebra-network instances.

We should open more specific tickets for missing tests, or just do them as we modify the protocol.
