### ISSUE TITLE
Test out of order CommitFinalizedBlock

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1052]
> Updated with fixes to @teor2345's review comments, except for the ones about the commented-out test.  If it's OK with others, I'd prefer to merge this in advance of resolving that discussion, since most of the work we want to do next is blocked on this PR, but not on the resolution to that discussion.  (I'm still committed to resolving it, I'd just prefer to do it in a near-term followup).

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/1043#issuecomment-691288566_

TODO:
- [ ] test out of order CommitFinalizedBlock: https://github.com/ZcashFoundation/zebra/pull/1043#discussion_r486726985

We could implement this test by randomising the block order in the continuous blockchain tests.

**Comment by teor2345** [comment]
This is tested by the full sync tests, and other sync tests.
