### ISSUE TITLE
Impl `Add, Sub` for `block::Height`

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1055]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to add and subtract block heights.  However, block heights themselves are *heights*, so adding and subtracting heights doesn't give a new height, it gives a *difference* between heights: block heights are a [torsor](https://math.ucr.edu/home/baez/torsors.html).  The ops impls we add should reflect this.

**Describe the solution you'd like**

We should add the following impls for `block::Height`:

```rust
impl Sub<Height> for Height {
    type Output = i32;
    /* ... */
}

impl Add<i32> for Height {
    type Output = Option<Height> // None if over/under max/min height
    /* ... */
}

impl Sub<i32> for Height {
    type Output = Option<Height> // None if over/under max/min height
    /* ... */
}
```

**Describe alternatives you've considered**

* Implementing addition/subtraction for heights themselves -- this isn't a quite correct modeling of the problem, and trying to do this probably indicates a logic error;

* Adding a custom newtype for height differences -- this provides little type safety compared to using an `i32`, at the cost of adding and maintaining another new type, meaning additional API surface, additional impls to write, code to maintain, etc.

**Comment by oxarbitrage** [comment]
Will be working on this one.

**Comment by yaahc** [comment]
> We should add the following impls for block::Height:

I'm assuming all the `i32`'s in these signatures are meant to represent the diffs, my preference would be to create a `HeightDiff` newtype to make this more clear.
