### ISSUE TITLE
Handle `FindBlocks` in the Inbound service

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1078]
**Is your feature request related to a problem? Please describe.**

The inbound network service should handle `FindBlocks` requests correctly.

**Describe the solution you'd like**

- [ ] Compute the intersection between the chain specified in the request and the chain in the state service;
- [ ] Query the state service for up to 500 following hashes;
- [ ] Truncate those hashes at `stop`, if `stop` is `Some`;
- [ ] Return the truncated list of hashes.

**Additional context**

Part of #889. 

Response Size:
- **500 hashes** is `zcashd`'s maximum response size.
- **>= 402 hashes** is the most efficient response size for `zebrad`, see #1204. (`zebrad` uses 1 hash to verify the tip, and discards 1 hash to work around `zcashd` bugs.)

**Comment by oxarbitrage** [comment]
Blocked on https://github.com/ZcashFoundation/zebra/issues/1306
