### ISSUE TITLE
Handle `FindHeaders` in the Inbound service

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1079]
**Is your feature request related to a problem? Please describe.**

The inbound network service should handle `FindHeaders` requests correctly.

**Describe the solution you'd like**

- [x] Compute the intersection between the chain specified in the request and the chain in the state service;
- [x] Query the state service for up to 160 following hashes;
- [x] Truncate those hashes at `stop`, if `stop` is `Some`;
- [x] Query the state service for the blocks with those hashes and extract  the headers into a list;
- [x] Return the list of headers.

**Describe alternatives you've considered**

Instead of pulling the entire blocks out and throwing away everything but the headers, we could implement an additional state query to get just the headers.  But this is only helpful if (1) we can lazily load the value of the `blocks_by_height` sled tree and parse only the header, which I don't think sled supports or (2) we build a separate headers tree, potentially duplicating disk space.

Neither of these are clear wins, so I think we should not attempt to do either, and deal with the problem only if performance problems show up on a profile sometime in the future.

**Additional context**

Part of #889.

**Comment by teor2345** [comment]
Blocked by PR #1271, which implements a `chain` function on the `StateService`. The `chain` function takes a block hash, and returns an iterator which lists blocks in reverse height order, starting from that hash.

We'll want to create a similar function which returns an iterator which lists block hashes in reverse height order, starting from a hash. And then use that iterator to answer a new `State` request. (For this ticket, the request only needs to return up to 500 hashes.)

**Comment by oxarbitrage** [comment]
Blocked actually on https://github.com/ZcashFoundation/zebra/issues/1306 now.
