### ISSUE TITLE
Send inbound `AdvertiseTransactionIds` broadcasts to the mempool download & verify stream

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1081]
**Is your feature request related to a problem? Please describe.**

The inbound network service should handle `AdvertiseTransactionIds` requests correctly.

**Describe the solution you'd like**

We need to send advertised transaction IDs to the mempool download and verify service.

**Additional context**

Part of #889.

**Comment by conradoplg** [comment]
This may be the same as https://github.com/ZcashFoundation/zebra/issues/2637

**Comment by conradoplg** [comment]
> This may be the same as #2637

Pinging @mpguerra about the duplicate

**Comment by mpguerra** [comment]
Yup, it looks like it is the same @dconnolly can you confirm and we can close this one as the duplicate

**Comment by mpguerra** [comment]
@conradoplg are there any other inbound requests other than `AdvertiseTransactionIds` that are implemented in #2637 ?

**Comment by mpguerra** [comment]
closed by #2679
