### ISSUE TITLE
Handle `AdvertiseBlock` in Inbound service

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1082]
**Is your feature request related to a problem? Please describe.**

The inbound network service should handle `AdvertiseBlock` messages.

**Describe the solution you'd like**

- [ ] Clone handles for the outbound network and the chain verifier to be moved into the response future;
- [ ] Download and verify the advertised block;

**Describe alternatives you've considered**

The procedure above exposes us to a DoS risk, because we blindly download an entire block whenever anyone tells us to.  This is in contrast to the sync process, where we generally download blocks from different peers than the ones who told us about them.

**After the first alpha release**, we should:

- [ ] Download only the block header;
- [ ] Pre-verify the proof of work in the block header;
- [ ] If successful, download and verify the full block.

This is more effort because we need to have a way to pre-verify the proof of work, which requires additional verification plumbing.  So we should do this better alternative after we get something working.

**Additional context**

Part of #889.

**Comment by hdevalence** [comment]
On a little further reflection, the request processing design we use helps us a little bit with DoS resistance.

How? Well, recall that each peer connection is handled in a separate task.  This task waits for messages to arrive, tries to interpret them as a response to a previous outbound request, or otherwise tries to interpret them as a new inbound request.  It then sends that request to the inbound service and waits for the response.

In Tower's programming model, the bulk of the processing work is done while driving the response future.  Because the response futures for inbound requests are driven by the connection task and processed sequentially, work generated by a peer connection is performed as part of that peer's connection task.

This means that we are already naturally applying backpressure on a per-peer basis, so even before we implement the better DoS resistance strategy, we only risk one thread per peer connection.

**Comment by teor2345** [comment]
I just added a note that the more complex solution should be implemented after the first alpha release.

**Comment by hdevalence** [comment]
I put a note in a comment above about one way that we could structure driving the tasks in a way that gives us a little bit of stopgap defense against DoS risk.  But after talking with @oxarbitrage about another piece of complexity involved in implementing this feature, I think that it might be better to take a different approach.

When a new block is mined and spreads across the network, we're likely to get block advertisements from every single peer that we're connected to, as they each accept the block and gossip it to their peers.  This means that deduplicating requests is pretty critical, in order to avoid downloading and verifying the same block potentially hundreds of times. However, as soon as we're deduplicating requests, we're also (logically) decoupling the processing of those requests from their source.  This means that we should operationally decouple the processing, by spawning a new task.  So the strategy I sketched above doesn't really fit the problem.

Similar code to what we need already exists in the `sync` module, which contains a `Downloads<ZN, ZV>` structure that takes a network service (of type `ZN`) and a verifier service (of type `ZV`) and queues download requests.  It handles deduplication as a side effect of handling cancellation, by:

* maintaining a lookup table `cancel_handles: HashMap<block::Hash, oneshot::Sender<()>>`;
* checking the lookup table before requesting a new hash;
* cleaning up the lookup table when resolving a result as part of its `Stream` impl.

So, one option could be to try to reuse this code, making the `Downloads` set accessible from outside of the `sync` module and using it inside the `Inbound` service.  But this approach would have a number of downsides:

* there are a bunch of sync-specific metrics in the `Downloads` set that we'd have to make generic;
* we'd need to change the duplicate block behavior slightly, because in the inbound service case, a duplicate download request is expected (multiple peers gossiped the same block), but in the sync case, a duplicate download request means that we've got confused about what we're trying to download somehow;
* there's a some behavior that's needed for the sync case that we don't need in the inbound case (for instance, we don't need a stream of results).

We could try to solve each of these issues by making the `Downloads` code slightly more general, handling both cases and situations.  But this would mean that it would be harder to understand the code in each case, because the reader would have to determine, for instance, which parts were relevant to the way the `Downloads` was used in the sync case, or in the inbound service case.  And, the logic for the two settings would be coupled together, and become more difficult to change in the future.  Since we know we want to change the inbound logic later (to download headers first and then full blocks), this doesn't seem like a good idea.

Instead, we should just use the `sync::Downloads` code as a reference for a new `inbound::Downloads` structure used in the `Inbound` service, along the following lines (sketch code):

1.  Copy the `sync::downloads` module to a new `downloads` submodule of `components::inbound`, stored in `src/components/inbound/downloads.rs`;

2. Delete the `AlwaysHedge` and `impl hedge::Policy` code;

3. Change the comment on the `Downloads` struct from
    ```
    /// Represents a [`Stream`] of download and verification tasks during chain sync.
    ```
    to
    ```
    /// Manages download and verification of blocks gossiped to this peer.
    ```
    to clarify that its role is different;

4. Change
    ```
    pub async fn download_and_verify(&mut self, hash: block::Hash) -> Result<(), Report>
    ```
    to
    ```
    pub async fn download_and_verify(&mut self, hash: block::Hash) -> Result<bool, Report>
    ```
    and have the function return `Ok(false)` if the block was already queued (the first `if` condition) and `Ok(true)` if it is newly downloaded, and add a note to the method docs explaining the return value.  (This way, duplicate requests are not treated as errors, but we can still surface errors that occur if, e.g., the network service fails).

5. Change the `sync.*` metrics keys to `gossip.*` metrics keys;

6. Delete the `cancel_all` and `in_flight` methods, which aren't needed any more;

7. Add a `ZS` type parameter to the structure, with the bound
    ```
    ZS: Service<zs::Request, Response = zn::Response, Error = BoxError> + Send + 'static,
    ZS::Future: Send,
    ```
    add a `chain_state: ZS` parameter to the `Downloads` struct, and a `use zebra_state as zs;` at the top of the file next to the `zn` declaration;

8. After the first `self.cancel_handles.contains_key` check, add another check that the hash is not already contained in the chain, using the newly added `chain_state` service.  If it is, return `Ok(false)`, since we shouldn't download blocks we've already validated.

Now we can add a
```
downloads: Downloads<_, _, _>,
```
field to the `Inbound` service. To see how we should use it, we should think about the processing lifecycle of downloads tracked by the `Downloads` structure. Requests are created by `download_and_verify`, which inserts into the pending task list and cancel handle map, and removed by the `Stream::poll_next` implementation, which removes completed tasks.  In the case of the inbound service, we don't really care about whether the task succeeded or not -- we're not going to report that to the peer that advertised the block, or anyone else -- but we do need to clean up completed tasks.

This means we need to call `<Downloads as Stream>::poll_next` somewhere. This is a poll method that requires a `&mut Context`, so we have to call it from somewhere that we already have a `&mut Context`.  The only place we can put it is in `<Inbound as Service>::poll_ready`, and this also makes sense semantically, because `poll_ready` is supposed to do all the bookkeeping work required to get the service ready to receive a new request.  Each `poll_next` gives the result of a single task, so we need to call it in a loop until there are no more results:
```
// Clean up completed download tasks
while let Poll::Ready(Some(_)) = self.downloads.poll_next(cx) {}
```

We also need to figure out what layers are appropriate to apply to the services used by the download set.  For instance, in the sync code, we have a `Hedge` layer and some retry logic for block downloads, because we need to be more resilient to failures or latency.  In this case, I don't think that we need any layers to start, because it's not essential that every gossip request succeeds (if we fail to process a gossiped block for some reason, we'll catch up in the next sync iteration within a minute or two).

Then in the `<Inbound as Service>::call` implementation, we can queue downloads and output some diagnostics, maybe something like
```
if self.downloads.download_and_verify(hash).await? {
    tracing::info!(?hash, "queued download and verification of gossiped block");
} else {
    tracing::debug!(?hash, "gossiped block already queued or verified");
}
```

**Comment by oxarbitrage** [comment]
Closed by https://github.com/ZcashFoundation/zebra/pull/1328 and follow up to implement alternative solution now open at https://github.com/ZcashFoundation/zebra/issues/1393
