### ISSUE TITLE
Remove git dependencies on Hyper, Metrics, Tower

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1086]
### Is your feature request related to a problem?

We moved to a git dependency on:
* Tower in #1085
* Hyper and Metrics in #1330
* ed25519-zebra in #1952

#### Tokio 1.0 and dependencies

- [ ] upgrade to Tokio 1.0 (#2200)
    - refactor to use tokio-stream, see [teor's partial branch](https://github.com/teor2345/zebra/tree/upgrade-tokio-1.0-partial)
    - update Zebra to handle `!Unpin` sleep, by adding `tokio::pin!()`, `Box::pin()`, or `#[pin]` as needed
    - optionally, wait for `Stream` to move into std

Dependent upgrades:
- [ ] upgrade to Tower 0.4 or later and remove the patch directive, now that tower-rs/tower#431 is done
- [ ] upgrade to Hyper 0.14 or later and remove the patch directive
    - [ ] upgrade to the latest metrics-exporter-http, which depends on Hyper 0.14 or later

#### ed25519-zebra

- [x] upgrade to the latest version on crates.io
  - done in PR #2864

**Comment by teor2345** [comment]
We removed a redjubjub git dependency in #1975
