### ISSUE TITLE
Zcash-flavored Ed25519

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#109]
Parts of the Zcash specification require Ed25519 with specific, consensus-critical verification rules, for instance in [the JoinSplit signatures](https://zips.z.cash/protocol/protocol.pdf#concretejssig).  Because it is critical that we do Ed25519 verification exactly as in the spec, we may want to create a Zcash-flavored Ed25519 on top of `curve25519-dalek` that has exactly the properties we need.

**Comment by hdevalence** [comment]
Currently underway in https://github.com/ZcashFoundation/ed25519-zebra

**Comment by daira** [comment]
[Oops wrong repo; this comment was intended to be about zcashd. Moved [here](https://github.com/zcash/zcash/issues/2872#issuecomment-577432264).]

**Comment by daira** [comment]
I guess that I should clarify that we're not going to just destroy everyone's Sprout funds without plenty of warning. But as I've said before, it's not sustainable to maintain the protocol complexity of Sprout+Sapling forever.

**Comment by hdevalence** [comment]
`ed25519-zebra` `0.1.0` is now released, preparing a PR to bring it into Zebra.
