### ISSUE TITLE
Network upgrade test blocks

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1091]
It will be useful to have encoded block vectors for all the network upgrades so we can unit test the consensus changes for each. Related to https://github.com/ZcashFoundation/zebra/pull/1051

Ideally we should add 3 blocks per upgrade: NU-1, NU, and NU+1 for every network upgrade for mainnet and testnet.

This are the commands needed to be executed in a synchronized zcashd for blossom testnet(activation height: 584_000):

```
./src/zcash-cli getblock 583999 0
./src/zcash-cli getblock 584000 0
./src/zcash-cli getblock 584001 0
```

and blossom mainnet(activation height: 653_600)

```
./src/zcash-cli getblock 653599 0
./src/zcash-cli getblock 653600 0
./src/zcash-cli getblock 653601 0
```

Use https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/parameters/network_upgrade.rs#L44=L68 to get other heights.

TODO:

Networks
- [x] Mainnet
- [x] Testnet

Network Upgrades
- [x] Genesis
- [x] BeforeOverwinter
- [x] Overwinter
- [x] Sapling
- [x] Blossom
- [x] Heartwood
- [x] Canopy (Testnet only, until November)
  - [x] Open a follow-up ticket for Canopy Mainnet transition + 1 more Canopy Mainnet block (below the reorg limit) (#1099)

**Comment by teor2345** [comment]
I'd also like to have lists of Mainnet / Testnet blocks, and maybe blocks for each network upgrade, and all blocks.

**Comment by teor2345** [comment]
> I'd also like to have lists of Mainnet / Testnet blocks, and maybe blocks for each network upgrade, and all blocks.

I just went with the list of all blocks, we can make more specific lists if we need them.
