### ISSUE TITLE
Move `GENESIS_PREVIOUS_BLOCK_HASH` to `zebra-chain`

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1134]
There's actually a `GENESIS_PREVIOUS_BLOCK_HASH` constant, but we'll need to move it to `zebra_chain` to avoid a circular crate dependency:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/parameters/genesis.rs#L5

Let's do that in a separate follow-up ticket?

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/1101#discussion_r500721792_

**Comment by oxarbitrage** [comment]
I was thinking on moving the entire `genesis.rs` file from the parameters of `zebra-consensus` to the parameters of `zebra-chain`. Let me know if that is the right thing to do.

**Comment by teor2345** [comment]
Yeah, let's move the whole file.

If we're using the genesis previous block hash in `zebra-state`, then we'll probably want the genesis hashes themselves in other crates.
