### ISSUE TITLE
Panic: hashes must be unique in memory_state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1182]
**Version**

zebrad main branch, 19 October 2020.

**Platform**

`Linux ... 5.4.68 #1-NixOS SMP Sat Sep 26 16:03:16 UTC 2020 x86_64 GNU/Linux`

**Description**

While syncing mainnet blocks, `zebrad` panicked with a "hashes must be unique" error in `memory_state`, inside the span `zebra_state::service::queue_and_commit_non_finalized_blocks`.

I tried this:

Partially syncing mainnet, a sync hang (#1181), then restarting `zebrad` so sync could continue.

I expected to see this happen:

A successful sync to the tip.

Instead, this happened: [explanation]

A block timeout error, followed by a `zebra-state` panic.

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|

## Block Download Error
```
Error: 
   0: failed to verify block
   1: request timed out
```

## SpanTrace

<details>

```
SpanTrace:
   0: zebrad::components::sync::block_fetch_verify
           with hash=00000000024f9794d9cfe1d7ab6e7e23e7fa68dbc00316ea6e9a0c96358f73b4
             at zebrad/src/components/sync.rs:615
   1: zebrad::components::sync::extend_tips
             at zebrad/src/components/sync.rs:434
   2: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:169
```
</details>

## State Error
```
hashes must be unique
```

## SpanTrace

<details>

```
SpanTrace:
   0: zebra_state::service::queue_and_commit_non_finalized_blocks
             at zebra-state/src/service.rs:76
   1: zebrad::components::sync::block_fetch_verify
           with hash=000000000166f4b01559db2831189c088a99943ba2db2b40b4d068412ea16454
             at zebrad/src/components/sync.rs:615
   2: zebrad::components::sync::obtain_tips
             at zebrad/src/components/sync.rs:314
   3: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:169
```
</details>

**Comment by teor2345** [comment]
@yaahc I think you might have a better idea of what is going on with this state panic?

**Comment by yaahc** [comment]
It's implying that the same block was inserted twice into the memory state I think, looking into it. I thought we already added the duplicate block handling but I might be misremembering.

edit: looks like we didn't, what am I thinking about then X_X

edit2: Oh yea, I found it, you edited the RFC about this, back on track
