### ISSUE TITLE
Stop assuming that all transparent addresses are on mainnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1187]
Currently, `From<Script> for Address` assumes that all addresses are on mainnet.

But Zebra needs to support mainnet and testnet.

We should delete `From<Script> for Address`, and use the `From<ScriptAndNetwork> for Address` in PR #1170.

We should also check for any other places in Zebra where we've assumed Mainnet.

-----

Basically, given a script hash alone (as `lock_script`, the one we get from transaction outputs) it is not possible to know to which network it belongs, so i had to create a new type `ScriptForNetwork` and implement `impl From<ScriptForNetwork> for Address` to do the conversion.

_Originally posted by @oxarbitrage in https://github.com/ZcashFoundation/zebra/pull/1170#discussion_r508454881_

**Comment by teor2345** [comment]
Blocked on #1170 

Do we need to fix this bug in the first alpha release, or can it wait until later?

**Comment by dconnolly** [comment]
> Blocked on #1170
> 
> Do we need to fix this bug in the first alpha release, or can it wait until later?

I _think_ we can get away with not fixing this for the first alpha, but probably not any betas and certainly not the first major/stable release.

**Comment by teor2345** [comment]
It was easier than I thought, see #1191.
