### ISSUE TITLE
Add new `zebra-eyre` crate

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1197]
**Is your feature request related to a problem? Please describe.**

As part of our `zebrad` application we'd like to be able to control exactly what context we carry with our error reports and how they're formatted. Right now we've been using `color-eyre` which provides a lot of good defaults that have mostly covered our needs, but it still restricts us to working with types that are defined in common crates, and mostly with going through the error trait.

**Describe the solution you'd like**

We should export our own error reporting hooks, based initially on those defined in `color-eyre`. By having our error reporting definitions be downstream in the crate graph of the rest of our libraries we can react to concrete types in our error reporting. This will make it easier to capture context that isn't necessarily covered by the error trait, and will let us add new error reporting features that we need quickly rather than needing to iron them out well enough to merge them into a more widely used upstream crate.

**Additional context**

* based on this https://github.com/ZcashFoundation/zebra/pull/1041#discussion_r510332887

**TODO**

- [ ] Handle sled errors with nice user friendly error messages consistently in sled_state https://github.com/ZcashFoundation/zebra/pull/1198#discussion_r510531326

**Comment by teor2345** [comment]
I'm not sure if we will ever do this task.
