### ISSUE TITLE
Pipelinable Block Syncing and Lookup RFC fixes

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1218]
https://zebra.zfnd.org/dev/rfcs/0001-pipelinable-block-lookup.html

There is a huge template section on this document which is very confusing for someone trying to read it. It seems this was done before the RFC template was implemented.

We have a few options, the first one is the easiest one, unsure what we will want to do:

- Remove all template text and add a summary. This RFC will not have a standard format.
- Make the RFC fit into the format. This is more work as more stuff will have to be written.

There is maybe an already open issue for this that i am missing, if so, please close the ticket with a reference to it.

**Comment by teor2345** [comment]
I've added these fixes to #899, which is listed in the Sync Correctness tracking issue #884.
