### ISSUE TITLE
RedJubJub signatures

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#125]
In addition to #109, we also need a library for RedJubJub signatures.  One exists in `librustzcash/zcash_primitives` but it is coupled to the rest of that library, and the `zkcrypto/jubjub` implementation will soon be using `bls12_381` directly.

**Comment by hdevalence** [comment]
The library now exists: https://github.com/ZcashFoundation/redjubjub-zebra ; I could either a) update #105 to include it or b) do the update in a subsequent PR.  I have a slight preference towards a) if that's OK, since there are other refinements needed for #123 beyond just the Redjubjub changes.

**Comment by dconnolly** [comment]
> The library now exists: https://github.com/ZcashFoundation/redjubjub-zebra ; I could either a) update #105 to include it or b) do the update in a subsequent PR. I have a slight preference towards a) if that's OK, since there are other refinements needed for #123 beyond just the Redjubjub changes.

a) sounds good to me!
