### ISSUE TITLE
Implicit conversion of the minimum difficulty threshold to the compact representation 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1277]
## Issue

`zcashd` converts the `PoWLimit` to the compact representation before using it to perform the alternate difficulty check for testnet minimum difficulty blocks.

But this conversion is not explicitly specified in the Zcash Specification, ZIP-205, or ZIP-208.

This means that a strict reading of the specification might allow some block hashes that `zcashd` rejects.

## Details

zcashd implements the proof of work limit as a compact value, truncating some of its least significant bits:
```c
unsigned int GetNextWorkRequired(const CBlockIndex* pindexLast, const CBlockHeader *pblock, const Consensus::Params& params)
{
    unsigned int nProofOfWorkLimit = UintToArith256(params.powLimit).GetCompact();
```
https://github.com/zcash/zcash/blob/514d86817990a1bf9578ee5fa2d01c34c6ca6035/src/pow.cpp#L18

But the Zcash specification says:
```
PoWLimit :=
    2^243 − 1 for Mainnet
    2^251 − 1 for Testnet
```
https://zips.z.cash/protocol/protocol.pdf#constants

And ZIP-205 says:

> If the block time of a block from this height onward is at least 15 minutes after that of the preceding block, then the block is a minimum-difficulty block, and its target threshold is set to the value of PoWLimit for testnet ...
https://zips.z.cash/zip-0205#change-to-difficulty-adjustment-on-testnet

And ZIP-208 says:

> ... if the block time of a block at height height ≥ 299188 is at least 6 · PoWTargetSpacing(height) seconds after that of the preceding block, then the block is a minimum-difficulty block, and its target threshold is set to the value of PoWLimit for testnet ...

https://zips.z.cash/zip-0208#minimum-difficulty-blocks-on-the-test-network

## Suggested Resolution

@dconnolly or @daira, I'm not sure which of the following updates you'll want to make:
* update the Zcash Specification so the PoWLimit constants are always converted to the compact representation
* update the Zcash Specification so the difficulty filter specifies the precise comparison for testnet minimum difficulty blocks
* update ZIP 205 and ZIP 208 to convert the PoWLimit constant to the compact representation before comparison

**Comment by daira** [comment]
Thanks for reporting this. Please review zcash/zips#417 :-)

**Comment by daira** [comment]
Fixed in zcash/zips#417.

**Comment by mpguerra** [comment]
@teor2345 anything else to be done here?

**Comment by teor2345** [comment]
It's fixed in the ZIPs.
