### ISSUE TITLE
Implement incremental, sparse note commitment trees for Sapling and Orchard

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1287]
Implement the note commitment trees in order to compute anchors, for

- [x] Sapling
- [x] Orchard

In that order.

The follow-on to https://github.com/ZcashFoundation/zebra/issues/286

Pertains to #983 , #958 

Follow ups:
- https://github.com/ZcashFoundation/zebra/issues/2484 Implement the Sprout tree
- https://github.com/ZcashFoundation/zebra/issues/1320 write Sapling and Orchard anchors and trees in the state
- https://github.com/ZcashFoundation/zebra/issues/2485 write Sprout anchors and trees in the state
- https://github.com/ZcashFoundation/zebra/issues/2530 validate the anchors

**Comment by teor2345** [comment]
@dconnolly hey did you want to split this work into separate tickets or PRs for sprout, sapling, and orchard?

**Comment by mpguerra** [comment]
Since the sprout parts have now moved to #2484  can we consider this issue done now that #2407 has merged?

**Comment by teor2345** [comment]
> Since the sprout parts have now moved to #2484 can we consider this issue done now that #2407 has merged?

No, we still need to use these calculations in the state to finish #1287.
See https://github.com/ZcashFoundation/zebra/pull/2407#issuecomment-875182035

**Comment by conradoplg** [comment]
I've update the issue to restrict its scope to the trees themselves. We should be able to close this now.

**Comment by dconnolly** [comment]
Resolved by #2458
