### ISSUE TITLE
Add a function to `zebra_test` that returns the continuous range of blocks from genesis.

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1296]
We could add a function to `zebra_test` that returns the continuous range of blocks from genesis.

But we don't have to do that in this PR, let's open a follow-up ticket that isn't in the first alpha?

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/1281#discussion_r522614793_

**Comment by teor2345** [comment]
Closed by #1837.
