### ISSUE TITLE
Improve speed of `test_founders_address()`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1310]
**Is your feature request related to a problem? Please describe.**

The `test_founders_address()` test from https://github.com/ZcashFoundation/zebra/pull/1170 takes too much time to execute(around 3 mins 40 secs on my laptop), this ended up with the test marked as `#[ignore]`.

The root cause is that currently the test is looping all the blocks one by one for the full founders reward period collecting address changes.

**Describe the solution you'd like**

The exact address changes can be calculated, in practice before blossom address change at `founders_address_change_interval()` and after it at `founders_address_change_interval() * 2` however the first change after blossom is at block `656_866` for the mainnet and `584_794` for the testnet which are not at well known intervals. I was not able code this test right to don't use hardcoded values but it should be possible to do so.

**Describe alternatives you've considered**

We can just leave it as it is.

**Additional context**

https://github.com/ZcashFoundation/zebra/pull/1170

This is not an urgent task, the issue is created to don't block the merge of the above PR on this.

**Comment by teor2345** [comment]
I'm concerned about merging code with disabled tests right before an alpha release.

It also seems like these speed issues mean that we don't really understand what we need to be testing, and maybe the tests should be redesigned. So I'm not sure if we want to merge tests that we're just going to rewrite anyway.

**Comment by oxarbitrage** [comment]
Testing blocks one by one as we are doing now is the safest we can do to catch all the address changes. I think this is ok, the only problem is that it takes time.

**Comment by teor2345** [comment]
Disabling tests means that we can break things without realising it.

Slow tests often reveal bigger issues.

Either:
* the tests are slow because the code is slow, and we should fix the code
* the tests are generating block data we don't need, and we should fix the generator, or refactor the code to take less data
  * for example, we should be able to lookup a coinbase address given only a height and network
* the tests are doing redundant checks, and we should fix the tests

Here's one way to fix the tests:

Rather than testing every height, test the first and last height that each address is used in, with the following checks:
* the address at the first height matches the address at the last height
* the address at the last height is different to the address at the `last height + 1` (the first height for the next address)
* the addresses at the first and last heights match the expected founders reward address

That way, you don't need to test all the heights between the first and the last height, because they should all have the same address. And you know you haven't made a mistake with the heights, because you've checked that addresses only change at the end of each range you're testing.

**Comment by daira** [comment]
Yes what @teor2345 suggests is also what I suggested.

**Comment by oxarbitrage** [comment]
Let me try to explain what i am trying to test and the issue a bit further. I will be showing some numbers of the mainnet hoping to be a bit clearer.

By protocol, before Blossom, the founder address change when the integer part of the floored division `height/founders_address_change_interval()` changes. Even more, the division result is the index of the addresses array, giving the exact address the blockchain is using for rewards in the current block.

In a continuous blockchain, the first founder address from the list will be used until block `17_709` where the second address will get in, this one will be in use until `35_418,`, then `53_127`, `70_836` and so on. This is because `17_709` is `founders_address_change_interval()` and all the changes before blossom are a multiple of that number.

Up to blossom NU the index of addresses is at 36.

After Blossom(again by protocol) the calculation changes. Instead of just dividing current height by `founders_address_change_interval()` to get the address index of the array, now the height is adjusted before dividing. This is implemented at https://github.com/ZcashFoundation/zebra/blob/d2f6bc6e96c7087bc39408ae6ef7b51928d6a615/zebra-consensus/src/block/subsidy/founders_reward.rs#L72-L75 and basically it is increasing the height to be divided at half of the rate as it was in pre blossom period.

So, the last change before blossom is at block `637_524` (Blossom starts at `653_600`) and without any adjustment next change should be at `655_233`(`637_524 + 17_709`) however it is actually at `656_866`. This is because the adjusted height at `656_866` is computed as `653_600 + (656_866-653_600/2) = 655_233`. This divided by `17_709` which is exactly `37`, which is the first index change after blossom.

After this first change post blossom the next ones are just multiples of `founders_address_change_interval() * 2`. So starting from `656_866` the next change will be at `692_284`(`656_866 + (17709 * 2)`), next at `727_702`(`692_284 + 17_709 * 2`) and so on.

So, with this, we are currently testing blocks 1 by 1 for the entire founders reward period and collecting all the new addresses. Then compare the collected addresses with the hardcoded array, they should be the same. With that we make sure all the addresses were used but we don't know if they changed at the exact spots. (There is no need to increment blocks one by one, actually just by coincidence increasing by `founders_address_change_interval()` works but it could be any other value that will improve the speed of the test while collect everything at the same time).

If we want to to test the exact spots(and exact spot + or - 1) as proposed i don't see any other option than hardcode all the block heights(for the mainnet(48) and for the testnet(46)) where we are expecting the address to change into the test. I was trying to avoid that but can be done.

Open to alternatives, thanks.

**Comment by daira** [comment]
You don't need to hard-code all the heights. You just need two loops, one for pre-Blossom and one for post-Blossom.

**Comment by oxarbitrage** [comment]
> You don't need to hard-code all the heights. You just need two loops, one for pre-Blossom and one for post-Blossom.

Except for the first change after blossom where the loop can't be incremented by `founders_address_change_interval()` or by `founders_address_change_interval() * 2`. So that case i think have to be hardcoded at least, i had it like that in a previous version of the test with the 2 loops and the special case in the middle, something as https://github.com/ZcashFoundation/zebra/blob/f040a3930953e61b0a9b898c5edbb426c2dd137f/zebra-consensus/src/block/subsidy/founders_reward.rs#L184-L231

**Comment by mpguerra** [comment]
@oxarbitrage do we still need to do this now that we are checkpointing on Canopy?

**Comment by oxarbitrage** [comment]
https://github.com/ZcashFoundation/zebra/pull/1170 was never merged so neither the test the ticket refers to. This issue can be closed. Thanks @mpguerra
