### ISSUE TITLE
Make sure RocksDB debug logs don't grow too big

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1323]
By default, RocksDB logs database debug information to a textual log file:
https://github.com/facebook/rocksdb/wiki/RocksDB-Basics#database-debug-logs

We should make sure this file doesn't grow too big by:
* disabling debug logs, or
* configuring debug log rotation.

**Comment by hdevalence** [comment]
Let's disable debug logs to start, since that's the simplest thing and easiest to change going forward if we need a different behavior?

**Comment by dconnolly** [comment]
Not strictly needed for release candidate

**Comment by teor2345** [comment]
This hasn't been a problem so far, we can re-open if it becomes one.
