### ISSUE TITLE
Use recommended RocksDB configuration for new projects

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1327]
**Is your feature request related to a problem? Please describe.**

The RocksDB developers recommend a number of non-default settings for new projects.

These settings aren't enabled by default, due to concerns about upgrading existing databases. So if we decide to make this change, we should make it before the first alpha release.

**Describe the solution you'd like**

Increase the block cache size above the 8MB default:
https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ#configuration-and-tuning

Configure RocksDB with the recommended options:
```
cf_options.level_compaction_dynamic_level_bytes = true;
options.max_background_compactions = 4;
options.max_background_flushes = 2;
options.bytes_per_sync = 1048576;
options.compaction_pri = kMinOverlappingRatio;
table_options.block_size = 16 * 1024;
table_options.cache_index_and_filter_blocks = true;
table_options.pin_l0_filter_and_index_blocks_in_cache = true;
```
https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning#other-general-options

**Describe alternatives you've considered**

Do nothing, things will probably be ok.

**Comment by mpguerra** [comment]
We should probably do this one soon given the potential future cost to upgrade.

Do we know what a good block cache size should be or do we need to investigate this one further? 

Otherwise it seems like we can just take the other recommended values as given. 

If we're not planning to do this before the First Alpha Release we should just close it.

**Comment by teor2345** [comment]
We closed this issue because we want to use the default configuration for RocksDB, as much as possible.

Using the default configuration has these benefits:
* our bugs and issues are likely to be similar to most other users' issues
* the configuration we're using is well-tested in production scenarios

Changing configuration settings has these risks:
* we might introduce bugs and performance issues, particularly on configurations that we aren't using ourselves

We should only make configuration changes if they solve a specific problem we're having.
