### ISSUE TITLE
Extreme CPU usage during sync

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1350]
**Version**

tip of #1348 

**Description**

The sync proceeds normally but occasionally gets stuck, with a few cores pegged at 100% use while the rest are idle, before finally having a single core pegged at 100% until eventually making progress much, much later.  This pattern fits a scenario where some verification tasks take a very long time, and progress on tasks that depend on them can't occur until they finish (at first there are only a few cores pegged at 100% because there is still parallel work to do, but eventually there's only one left).

Profiling the overall CPU cost reveals that almost all of the time is spent in `zcash_script_verify`. Per https://github.com/ZcashFoundation/zebra/issues/1345#issuecomment-731626013 , this may be caused by accidentally quadratic behavior in `zcash_script`.

The slowdown is so extreme that this should be a blocker for our alpha release.

![profile](https://user-images.githubusercontent.com/44879/99889832-b6eb4100-2c0d-11eb-9139-0ef544f55ec8.png)

**Comment by hdevalence** [comment]
The body of `zcash_script_verify` is here: https://github.com/ZcashFoundation/zcash_script/blob/master/depend/zcash/src/script/zcash_script.cpp#L74-L104

In addition to deserializing the re-serialized transaction, it rebuilds `PrecomputedTransactionData` for every input. That constructor is here:
https://github.com/ZcashFoundation/zcash_script/blob/master/depend/zcash/src/script/interpreter.cpp#L1130-L1138

All of this work and potentially more is duplicated for every transaction input, so this would be closed by #1345

**Comment by daira** [comment]
Is this pre- or post-Overwinter in the sync?

**Comment by teor2345** [comment]
> Is this pre- or post-Overwinter in the sync?

Zebra only verifies post-Sapling scripts.

(Pre-Sapling blocks are verified using a list of block hash checkpoints.)

**Comment by mpguerra** [comment]
moving out of the First Alpha Release milestone as we have a workaround (#1360) in place for now

**Comment by hdevalence** [comment]
Yes, I think this issue should be closed entirely and we should have a new issue tracking script validation.
