### ISSUE TITLE
Add a CI job which compiles each Zebra crate individually

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1364]
## Motivation

Sometimes we add code that needs a feature to a Zebra crate, then activate that feature in `zebrad`. But we forget to activate the feature in the crate that actually contains the code.

For an example, see PR #1365, where individual crates use features in their dependencies, but don't declare those features in their `Cargo.toml`.

## Design

- [ ] Build each Zebra crate individually in a CI job, including Zebra's custom Tower crates
- [ ] Fail the PR if any build fails.

We should add a new CI job, so that we don't slow down existing jobs.

Example script:
```sh
for crate in tower* zebra*; do
    pushd "$crate"
    cargo build
    popd
done
```

## Related Work

- #4550

## Alternatives

<details>

Continue to occasionally break crates when they're used individually.

We can implement theses checks using `cargo-hack --workspace`:
- Build all targets (library, binary, example, test, and benchmark)
- Build the `--feature-powerset`

</details>

## Follow Up Tasks

<details>

- [ ] Also test if the crate is packaged succesfully (`cargo package`)
- [ ] Also test if it compiles/packages with the MSRV (and specify one if it doesn't)

</details>

**Comment by mpguerra** [comment]
Note to remove task from the release checklist once this issue is resolved

**Comment by conradoplg** [comment]
I added these two items:

- [ ] Also test if the crate is packaged succesfully (`cargo package`)
- [ ] Also test if it compiles/packages with the MSRV (and specify one if it doesn't)

**Comment by teor2345** [comment]
> I added these two items:
> * [ ]  Also test if the crate is packaged succesfully (`cargo package`)
> * [ ]  Also test if it compiles/packages with the MSRV (and specify one if it doesn't)

@conradoplg I'd prefer to add the publishing checks later, when we're working on publishing individual crates. Can we split them out into a different ticket?

**Comment by teor2345** [comment]
@gustavovalverde we might just want to start with builds (no publishing or rust version checks).

We might not be able to use the caches from the full builds, because they have different Rust features. So each crate might need its own cache.

**Comment by gustavovalverde** [comment]
Can I have a single example on how to do this? I'm not completely sure on how to this programmatically to consider all crates.

**Comment by teor2345** [comment]
> Can I have a single example on how to do this? I'm not completely sure on how to this programmatically to consider all crates.

Try
```sh
cargo tree --depth 0 --edges no-normal,no-dev,no-build,no-proc-macro | cut -d ' ' -f1
```

There is also `cargo metadata`, but it's very verbose JSON.

**Comment by teor2345** [comment]
That will give you a list of crate names, and you can build each one using:
```
cargo build --package <crate-name>
```
