### ISSUE TITLE
Timeouts for UXTO lookup in script verification

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1390]
**Is your feature request related to a problem? Please describe.**

The state service API says explicitly that `AwaitUTXO` requests should be coupled with a timeout layer.  I didn't add this when I was testing and fixing the UTXO lookup code (#1348, #1358) because causing `zebrad` to hang on a failed dependency was useful for identifying cases where the code wasn't useful (and then inspecting execution traces).

**Describe the solution you'd like**

The script verifier should apply a timeout layer to the state service it uses for UTXO requests.

This will ~close~ deal with some of the causes of #1389 as a side effect, because most far-future blocks will have their verification time out.

**Comment by teor2345** [comment]
Closed by #1391.
