### ISSUE TITLE
Add tests for Bitcoin merkle root malleability behavior

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1392]
**Is your feature request related to a problem? Please describe.**

Bitcoin's transaction Merkle trees are badly designed, and suffer from malleability.  In #1386 we address this by:

- in the checkpoint verifier, explicitly checking that there are no duplicate transaction hashes;
- in the block verifier, the double-spend prevention blocks blocks with duplicate transactions from being accepted.

That PR includes unit tests for the Merkle root computation itself, but it does not have integration tests for the verifiers.

**Describe the solution you'd like**

- For the checkpointer: check that blocks with duplicate transactions are rejected, both before and after submission of the canonical block whose hash they collide with;

- For the block verifier: take a block which otherwise passes all validation criteria, and duplicate transactions in such a way as to create a colliding block hash.  Then, check that this otherwise-valid block is rejected.

**Comment by teor2345** [comment]
This is a test we should do for security, but we're unlikely to do it any time soon.
