### ISSUE TITLE
Rewrite `find_best_chain_hashes` to use hash indexes, not blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1397]
**Is your feature request related to a problem? Please describe.**

`StateService::find_best_chain_hashes` fetches every block in the response, so it can calculate the block hash. But loading every requested block from disk could be really slow, particularly if the blocks are large, and lots of peers are sending `FindBlocks` or `FindHeaders` requests.

**Describe the solution you'd like**

1. Create a `best_ancestor_hashes` iterator that uses the non-finalized `Chain.blocks` `PreparedBlock.hash` and finalized `hash_by_height` index to return the list of hashes
2. Use `best_ancestor_hashes` to create the list of hashes in `collect_chain_hashes`

We might also want to rename `collect_chain_hashes` to something like `collect_best_descendant_hashes`.

**Describe alternatives you've considered**

Do nothing - `FindBlocks` or `FindHeaders` requests will continue to load redundant block data from disk. (The block data is eventually re-used for `FindHeaders`, because it supplies the transaction count in the header object.)

**Additional context**

We should only make this change if `FindBlocks` or `FindHeaders` turn up in profiles, or cause a lot of disk accesses.

**Comment by hdevalence** [comment]
Rather than making a second iterator, it seems like it would be better to change the existing iterator to have `Item=block::Hash` rather than `Item=Arc<Block>`.  Then there's no extra code, and users who need full blocks can just `.map` the hashes to blocks as required.

**Comment by teor2345** [comment]
This only needs to be done if it turns up in performance profiles.
