### ISSUE TITLE
Sync service/component to manage the fetching and validation of blocks.

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#140]
This will be wrapped up and made available to commands as an Abscissa component.

- [ ] make requests to network interface to get blocks from peers (#504)
- [ ] validate blocks and transactions (#428)

**Comment by hdevalence** [comment]
Edited checklist to reflect that the validation service will writeback verified blocks to the state and to link to #504

**Comment by teor2345** [comment]
Deleted the state from the checklist, because the verifiers are responsible for modifying the state after block verification.

**Comment by dconnolly** [comment]
Tracked contents elsewhere.
