### ISSUE TITLE
Test that zcashd and Zebra can sync from Zebra

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1400]
Once we've merged GetBlocks and GetHeaders support #1347 , Zebra should be able to serve blocks to other nodes.

We should test that zcashd and Zebra can sync from genesis, using a fully synced Zebra.

This is a network integration test, so its out of scope for the first alpha. But it would be nice to make sure there isn't any really bad behaviour.

**Comment by mpguerra** [comment]
@ZcashFoundation/zebra-team  has anyone tried this already?

**Comment by oxarbitrage** [comment]
I never tried this but i think is a good idea to sync zcash and zebra only with zebra seeders. We should have this done for the first beta so we should prioritize.

**Comment by teor2345** [comment]
I run tests like this all the time, and I see Zebra syncing from Zebra.

But I don't do it in an isolated environment where there are no extra `zcashd` instances.

**Comment by teor2345** [comment]
This would be a useful test, but it's partly covered by our other tests.
