### ISSUE TITLE
Sort out behaviour when the inbound service returns Err to a peer Request

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#141]
https://github.com/ZcashFoundation/zebra/pull/106/files#diff-a1699d205a2a0cec572fa943cd26f32dR366

We should decide whether an `Err` variant should signal a permanent error or an error scoped to the request, and unify behaviour with the `reject` handling below.  For instance, does it make sense to have `Response::Error` at all, or would it be better to use the `Err` variant?

**Comment by yaahc** [comment]
Is this still accurate / up to date? I'm looking at `zebra_network/src/protocol/internal/response.rs` which defines the `Response` type but it doesn't have `Ok` or `Error` variants on it as shown in the linked diff.

**Comment by hdevalence** [comment]
Looks like this is probably stale then, closing it out.
