### ISSUE TITLE
Update zebra README with Alpha Release details

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1419]
**Is your feature request related to a problem? Please describe.**

When we release alpha we want any potential users to be aware of what the zebra alpha release does and doesn't do.

We also want people to know Zebra's system requirements.

**Describe the solution you'd like**
We should update the README with these details

**Describe alternatives you've considered**

Do nothing

**Additional context**
We should probably add this note at the top of the README

**Comment by teor2345** [comment]
I think we should also add system requirements to our Go/No-Go checklist, and the readme. They don't need to be very long, we just need to give people a little bit of guidance.

**Comment by yaahc** [comment]
I created a draft PR for this based on my recent comment about the alpha in the zcash community forum as a starting point. feel free to suggest more details to add or push commits to the PR
