### ISSUE TITLE
Warn if the maximum number of peers would exceed the open file limit

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1429]
**Is your feature request related to a problem? Please describe.**

In #1850, we add a hard-coded limit on the number of open connections.

In #1426, we automatically adjust the maximum number of open files for Zebra. We use this number to limit the maximum number of files that the database opens, but we don't limit the maximum number of peers. (Which is the other major file descriptor user in Zebra.)

Limiting the maximum number of peers could also help users on slower connections, and users with routers which can't handle a large number of connections.

**Describe the solution you'd like**

- [x] Add a peer connection limit config to `zebra-network` (complete, calculated from `peerset_initial_target_size`)
- [x] Increase the maximum number of open files high enough to cover the peer limit, database, and other internal use
- [ ] Warn the user if the configured limit is too low, compared to the maximum number of open files

**Optional Changes**

We might also want to:
* add an argument to the `init` function that tells `zebra-state` the maximum number of open files it should use
* use the connection limit config value as the maximum number of open files for  `zebra-network`
* move the automatic open files increase code to `zebrad`
* decrease the connection limit and peer set target size if the open file limit is too low

**Design issues**

When and where should we increase the maximum number of open files?
* If we do it in `zebrad`, then downstream users of `zebra-state` and `zebra-network` have to resolve these issues themselves.
* If we do it in `zebra-state` and `zebra-network`, then they could interfere with each other, or with the host application.

**Comment by hdevalence** [comment]
I'm not sure that `zebra-network` or `zebra-state` should have to have anything related to tracking open files.  That seems like an application issue.  The only reason it's a problem for us at all is that we aim to support MacOS, but many server applications don't have that constraint.

**Comment by teor2345** [comment]
I've decreased the scope of this issue, and I now think it's a medium sized issue.

**Comment by teor2345** [comment]
I split the security part into #1850.

**Comment by teor2345** [comment]
Our minimum number of open files is high enough for the database and default peer limit.

We could warn users who change the default peer limit, but not the open file limit. But that seems optional.

**Comment by teor2345** [comment]
Actually, thinking about this a bit more, it's still a usability issue, but not with the default config. So we should fix it if we have time.

**Comment by teor2345** [comment]
We should re-open this issue if it ever becomes an actual problem for users.
