### ISSUE TITLE
Remove `zebra_state::Request::FindBlockHeaders`

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#1432]
**Is your feature request related to a problem? Please describe.**

The `zebra_state::Request::FindBlockHeaders` request variant duplicates functionality of `Request::FindBlockHashes`, but adds more work, blocking the state queue from processing other requests.  Once the list of block hashes has been atomically computed, there's no need to atomically fetch all of the blocks to obtain their headers, so there is no correctness problem with moving that phase of the work out of the state service.  This simplifies the state implementation.

**Describe the solution you'd like**

1. Change `FindBlockHashes` to include a `max_len: usize`, passed directly to `self.find_chain_hashes`;

2. Replace the existing use of `FindBlockHeaders` in the `Inbound` service by a `FindBlockHashes`, followed by a sequence of `Block` requests;

3. Remove `FindBlockHeaders` from the state API.

**Describe alternatives you've considered**

Leaving the code as-is.  This prevents a clean separation of concerns and prevents us from composing middleware in front of the state service.

**Comment by teor2345** [comment]
This is obsolete - with the new database and state API, we should:
- move this request to the ReadStateService
- only query the finalized state block headers column family
