### ISSUE TITLE
Add priority labels to issues

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1437]
**Is your feature request related to a problem? Please describe.**

It can sometimes be hard to decide which issues to work on as we don't currently have a way to compare relative priorities of different issues in our zebra github repo. 

**Describe the solution you'd like**

We should add priority labels to issues as they are triaged. A suggestion would be:

- **High**: issue is urgent and should be fixed as soon as possible.
- **Medium**: issue can be fixed during usual, ongoing development. 
- **Low**: issue can be fixed at a later date.

**Describe alternatives you've considered**

Alternatively we could agree to order items in our project boards and milestones accordingly to denote relative priorities but the two are not mutually exclusive. 

**Additional context**

This will be useful to plan work post-alpha release

**Comment by teor2345** [comment]
We've been trying to follow the Rust issue labels and colours. Their priority labels are:
P-critical
P-high
P-medium
P-low

https://github.com/rust-lang/rust/labels?page=11&sort=name-asc

**Comment by mpguerra** [comment]
<img width="791" alt="Screenshot 2021-01-26 at 13 54 33" src="https://user-images.githubusercontent.com/1311133/105847555-0834f980-5fde-11eb-867a-5658e218e12b.png">
