### ISSUE TITLE
Update instructions to download, build and run zebra alpha release

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1475]
**Is your feature request related to a problem? Please describe.**

We need to make sure our users can download, build and run the first zebra alpha release

**Describe the solution you'd like**

Let's update the instructions to build and run our alpha. We should have instructions for Linux, Mac and Windows.

**Describe alternatives you've considered**

Do nothing

**Additional context**

We can check our CI runners for instructions

**Comment by teor2345** [comment]
Notes:

Build time:
2-core CPU
7 GB of RAM
14 GB of SSD disk space

Runtime:
n2d-standard-4 (4 vCPUs, 16 GB memory)

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by teor2345** [comment]
30 GB to store the Mainnet blockchain

**Comment by teor2345** [comment]
`cargo install --git https://github.com/ZcashFoundation/zebra.git --tag <release-tag>`
