### ISSUE TITLE
Upload Zebra crates to crates.io

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1480]
We discussed doing this during the last zebra sync ~as well as starting all versions at 1.0.0-alpha~

**Comment by teor2345** [comment]
We changed most crate versions to 1.0.0 in #1476, and we'll fix the remaining 3.0.0 versions in #1485.

What do you mean by "make cargo versions of Zebra crates"?
I'm not sure if we want to upload to crates.io until we have a stable release.

**Comment by mpguerra** [comment]
I didn't take more notes than that unfortunately but I think it was about uploading to crates.io. 

Maybe whoever suggested it can add more details. This can definitely wait until we have a stable release

**Comment by dconnolly** [comment]
Not strictly needed for release candidate, moved to usability epic

**Comment by teor2345** [comment]
We don't know when we'll stabilise all the Zebra crates.

If we want to upload individual stable crates, we should open specific tickets for them.
