### ISSUE TITLE
Downgrade zebrad to 1.0.0

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1485]
We decided to change all the zebra crates to version 1.0.0, but we missed zebrad.

We might want to grep the whole git repository for 3.0.0, to make sure we haven't missed anything else.

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/zebrad/Cargo.toml#L5

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3329

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3314

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3292

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3263

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3250

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3246

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3218

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3187

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3183

**Comment by teor2345** [comment]
@rex4539 thanks, we'll probably just grep the whole repository for "3.0.0"

**Comment by rex4539** [comment]
https://github.com/ZcashFoundation/zebra/blob/85c7eea444a72b737dbd0920f07f01f5aa2a9b42/Cargo.lock#L3145
