### ISSUE TITLE
Tune RocksDB memory usage

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1486]
**Analysis**

We think RocksDB is the major Zebra memory user.

Here is the RocksDB memory tuning guide:
https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB

We probably want to add sprout and sapling anchors, and finish transaction validation, before we try to tune memory. Those changes will increase the database size, and change data access patterns.

Unbounded block queues can also use a lot of memory, see #1389

**Version**

v1.0.0-alpha.0

**Platform**

Unknown

**Description**

Zebra uses 4.3 GB, but zcashd uses 1.5 GB of RAM.

**Comment by rex4539** [comment]
I would argue that `zebrad` uses less memory than `zcashd`.

<img width="1116" alt="Screen Shot 2020-12-09 at 11 10 06" src="https://user-images.githubusercontent.com/227442/101609110-3d29c480-3a0f-11eb-9a85-7c9ca3e93679.png">

**Comment by teor2345** [comment]
`zebrad` and `zcashd` memory usage will depend on:
* what they are each doing at the time they are measured
* how they are each configured
* network speed
* open files limit (changes RocksDB memory usage)
* the OS
* debug/release builds
* missing checks and features in Zebra

So different users will probably get different measurements.

**Comment by mpguerra** [comment]
Do we want to investigate this further or close it out for now?

**Comment by teor2345** [comment]
> We probably want to add sprout and sapling anchors, and finish transaction validation, before we try to tune memory. Those changes will increase the database size, and change data access patterns.

I don't think we can do anything about this issue right now.

**Comment by teor2345** [comment]
PR #1523 will help us monitor Zebra's memory usage over time, in a consistent environment.
