### ISSUE TITLE
Strange version in build error: `failed to compile 'zebrad v3.0.0-alpha.0 …'`

### ISSUE THREAD

**Issue by nathan-at-least** [ZcashFoundation/zebra#1494]
**Version**

> For bugs in `zebrad`, run `zebrad version`

I have not succeeded in building `zebrad`, and I'm attempting to build the `v1.0.0-alpha.0` tag with `cargo install … --git …`.

**Platform**
> The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

```
$ uname -a
Linux myhost 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Description**

**Short Summary:** A build error refers to the crate as `zebrad v3.0.0-alpha.0 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-alpha.0#85c7eea4)` when using `cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-alpha.0 zebrad`

> I expected to see this happen:

The error message would refer to the crate as `zebrad v1.0.0-alpha.0 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-alpha.0#<some hash>)`

> Instead, this happened:

The error message included `zebrad v3.0.0-alpha.0 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-alpha.0#85c7eea4)`

Why is the version mentioned `v3.0.0-alpha.0`? I would expect it to match the tag `v1.0.0-alpha.0`.

If this is a typo or error, that makes sense to me. Another possibility is that version is a crate-specific version separate from the `zebrad` user-level application version? If that were the case, it seems confusing to me.

**Details:**

When I run `cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-alpha.0 zebrad` with a funky dev setup, the build fails. This ticket isn't about the build failing, but rather that the error message has an apparently incorrect (or at least confusing) version string.

The build output ends with:

```
error: failed to compile `zebrad v3.0.0-alpha.0 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-alpha.0#85c7eea4)`, intermediate artifacts can be found at `[redacted path]/tmp/cargo-installyd9SOB`

Caused by:
  build failed
```

**Comment by yaahc** [comment]
> Why is the version mentioned v3.0.0-alpha.0? I would expect it to match the tag v1.0.0-alpha.0.

This is a known issue, we messed up the version number during the release, where the binary itself has the higher version number than intended. I think the plan is to just decrement the version though that might cause issues for users who have already `cargo install`ed a higher version, so we need to meet up as a team on monday to discuss the trade-offs and how to move forward with fixing the version mismatch.

For now I'll go ahead and update the readme to include this as one of our known issues.

**Comment by teor2345** [comment]
Duplicate of #1485

**Comment by teor2345** [comment]
Updated tags to match #1485

**Comment by nathan-at-least** [comment]
Got it. Ok, there's no mystery left for me and I see the duplicate issue. I'll close this.

For posterity, the error message version came from the [Cargo metadata for `zebrad` in the `v1.0.0-alph.0` git tag](https://github.com/ZcashFoundation/zebra/blob/v1.0.0-alpha.0/zebrad/Cargo.toml#L5) and that was simply inconsistent with the intent for the release.
