### ISSUE TITLE
Re-enable post-Sapling testnet sync tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1530]
## Motivation

We want to re-enable the testnet post-Sapling sync tests, once their disks have synced.

## Solution

Modify the relevant GitHub actions files.

## Related Tickets

Follow-up from #1529.

**Comment by dconnolly** [comment]
Closed with https://github.com/ZcashFoundation/zebra/commit/3266265f7ffd6217e6174b8b9c8c7f89c336c51b
