### ISSUE TITLE
Change the default data directory for macOS from "Caches" to "Application Support"

### ISSUE THREAD

**Issue by rex4539** [ZcashFoundation/zebra#1549]
The defacto folder to store application data on macOS is `~/Library/Application Support/`.

`Caches` is a dangerous place to store permanent data because the `Caches` folder is sort of a temp folder. There are many macOS utilities that even periodically flush the `Caches` folder in order to save disk space.

**Comment by daira** [comment]
This would need to be implemented in a way that still finds existing data directories. Preferably it should warn if a datadir is found in the Caches directory and recommend moving it.

**Comment by teor2345** [comment]
Zebra only stores cached state in the Caches directory. This state can be re-synchronised from other nodes if it's deleted.

This is consistent with Apple's definition of "Caches":
> Contains cached data that can be regenerated as needed. Apps should never rely on the existence of cache files.

Here is Apple's definition of "Application Support":
> Contains all app-specific data and support files. These are the files that your app creates and manages on behalf of the user and can include files that contain user data.

https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html

Zebra doesn't generate any user-specific data yet.

We haven't decided where we'll store wallet state yet, but it's likely that the config and keys will go in the Preferences directory, and the wallet state will go in the Application Support (local data) directory.

Zebra configs are stored in the Preferences (config) directory.

The directory names in brackets are from the dirs crate:
https://docs.rs/dirs/2.0.2/dirs/

**Comment by teor2345** [comment]
We spoke about this change in the team meeting today, and decided to leave the default as it is.

If users don't have a lot of disk space, are on a slow network, or want to preserve the block cache, they can change Zebra's default cache directory in its config.

For example:

In `/Users/me/Library/Preferences/zebrad.toml`:
```
[state]
cache_dir = "/Users/me/Documents/zebra"
```

Then run `zebrad start`, and it will automatically read the config.

See [running zebra](https://zebra.zfnd.org/user/run.html) and [the state config reference](https://doc.zebra.zfnd.org/zebra_state/struct.Config.html) for details.
