### ISSUE TITLE
Tracking: Zebra as a Full-Node Wallet

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1556]
Tracking issue for `zebra-client` work i.e zebra as a full-node wallet as described in the `zebra-client` [RFC](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0009-zebra-client.md)

**Comment by jackgavigan** [comment]
Removed the Epic label from this to try making Zenhub tidier.

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.
