### ISSUE TITLE
Enable ZIP-215: Ed25519 Validation Rules

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1565]
## Solution

We need to upgrade our version of ed25519-zebra to use the validation rules in ZIP-215 and actually validate the Sprout Ed25519 signatures for full Sprout validation.

https://zips.z.cash/zip-0215

This involves pulling in the latest version of ed25519-zebra, checking that our async `Verifier` is well tested against the new rules, and making sure this validation is done by default on all blocks.

## Alternatives

We could just use the new rules on `blockheight >= Canopy`, but that complicates our code.

**Comment by teor2345** [comment]
We can just use the new rules for all blocks (including pre-Canopy blocks), because the new rules allow all valid old signatures.
