### ISSUE TITLE
Generic object hashing

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#159]
Currently we have a number of named hash types, e.g., `TransactionHash`, `BlockHeaderHash`, etc. Instead, we could consider having only a single type, with a generic type parameter.  (I am not sure whether this would be better, but it's worth considering).  This would require some resolution to #158.

Supposing that #158 is resolved by option (1) in that issue (make serialization infallible up to the underlying writer), this could look something like this:

```rust
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
struct Hash<T: ZcashSerialize> {
    bytes: [u8; 32],
    _marker: PhantomData<T>,
}
```

with a conversion from `&T` to `Hash<T>`, as well as (de)serialization for `Hash<T>` itself:

```rust
impl<'a, T: ZcashSerialize> From<&'a T> for Hash<T> {
    fn from(object: &'a T) -> Self {
        let mut hash_writer = Sha256dWriter::default();
        object
            .zcash_serialize(&mut hash_writer)
            .expect("The Sha256dWriter is infallible");
        Self { bytes: hash_writer.finish(), _marker: PhantomData }
    }
}

impl<T: ZcashSerialize> ZcashSerialize for Hash<T> { /* writes 32 bytes */ }
impl<T: ZcashSerialize> ZcashDeserialize for Hash<T> { /* reads 32 bytes */ }
```

This means we only have a single hash type to deal with instead of one for each object type. (We should check that this is actually the way the protocol works, i.e., that all of the object hashes are SHA256d, but I think that this is the case.)

**Comment by hdevalence** [comment]
Question: what objects do we actually have to hash? If we're just doing tx and block hashes, this may not be worthwhile.

**Comment by dconnolly** [comment]
- InventoryHash
- BlockHeaderHash
- TransactionHash
- SaplingNoteTreeRootHash
- MerkleTreeRootHash

are all currently defined

**Comment by hdevalence** [comment]
So, of those, `InventoryHash` is not itself a hash but just an enum of `TransactionHash` and `BlockHeaderHash`, and the other two hashes are not SHA256d hashes, correct? If so that seems like something that points away from trying to do something like this, because beyond the two hash types mentioned there's not any more common hashing.

**Comment by dconnolly** [comment]
Fine with me!
