### ISSUE TITLE
Run full sync tests on Mainnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1592]
## Motivation

We want to avoid merging PRs if their changes break syncing to the tip.

## Test Plan

Run a mainnet sync, and make sure they reach block `X` within `N` hours:
- `N` is the typical time on that infrastructure, plus a small margin
- `X` is the estimated block height, calculated using a recent height and the target block interval (implemented in #3543)

We should also check the logs to make sure Zebra stops syncing blocks, and activates the mempool.
(Implemented in #3543 and #3555.)

We need to run a full sync, and that takes a few hours, so we should do it on Google Cloud. (If we run a short sync, we won't catch slowness or hang issues with post-checkpoint syncs.)

## Follow Up Work

TODO: create tickets for leftover work

As a follow-up, we could show sync speeds over time. This history will help us diagnose issues more reliably.

As another follow-up, we should run these tests on testnet. To run a reliable testnet sync, we need to deploy more testnet Zebra or zcashd instances, and make sure they appear in DNS seeders (#2380, #1904). So that's out of scope for now.

**Comment by teor2345** [comment]
Given our recent experience with subtle sync hangs and slowness in #1803, I'm not sure if there is a good way to do these tests. What we really need is a test that makes sure a sync finishes within `N` hours.

I'll update the ticket.

**Comment by teor2345** [comment]
Here's one way to do the Rust part of this change:

1. Create a future that returns when the estimated height has been reached, and the mempool has been active for a few minutes, and we are at least 200<sup>*</sup> blocks above the highest checkpoint
2. Add that future to `zebrad start`'s main loop as a "continuing task", so Zebra exits when it finishes
3. Create a sync test case with a 6 hour timeout, which uses a "stop at estimated height" config

https://github.com/ZcashFoundation/zebra/blob/1a14baf8e7c6c82dba7a64e9b43d076b8f856f2a/zebrad/src/commands/start.rs#L195-L200

Here is a good follow-up task:
- Adjust the timeout so that at least 99% of syncs succeed (makes failing tests fail faster)

Here is a refactor I don't think we need to do yet:
- #3442 (simplifies similar test code that's currently in the state)

<sup>*</sup> I picked 200 because 100 non-finalized blocks are excluded from checkpoint generation, and it takes 2 hours to build and run the test. (If mainnet syncs get fast, or we're using testnet.) If we make it any higher, the first time we submit each checkpoint update PR the tests will be slow, because we'll wait to sync newly generated blocks.

**Comment by teor2345** [comment]
Here is some code that exits when the state reaches a fixed height.

But calling `exit` causes bugs like #3392, so it would be better to use the `zebrad start` loop.

https://github.com/ZcashFoundation/zebra/blob/1a14baf8e7c6c82dba7a64e9b43d076b8f856f2a/zebra-state/src/service/finalized_state.rs#L495-L507

**Comment by conradoplg** [comment]
> Here's one way to do the Rust part of this change:

Should we create a separate ticket for that? @teor2345 @jvff

**Comment by teor2345** [comment]
> > Here's one way to do the Rust part of this change:
> 
> Should we create a separate ticket for that? @teor2345 @jvff

I opened #3493 with my suggestion, but @jvff should feel free to change the design.

**Comment by teor2345** [comment]
I've been using these command-lines to test #3543 and #3555:
```sh
FULL_SYNC_MAINNET_TIMEOUT_MINUTES=600 cargo test --release --test acceptance -- --nocapture --ignored full_sync_mainnet
FULL_SYNC_TESTNET_TIMEOUT_MINUTES=600 cargo test --release --test acceptance -- --nocapture --ignored full_sync_testnet
```

https://doc.rust-lang.org/rustc/tests/index.html#--nocapture

**Comment by jvff** [comment]
I'm not sure if this should be a new job in `.github/workflows/test.yml` or if I should change the existing `test-stateful-sync` job. @gustavovalverde, what do you think?

**Comment by teor2345** [comment]
> I'm not sure if this should be a new job in `.github/workflows/test.yml` or if I should change the existing `test-stateful-sync` job.

I'd like to keep `test-stateful-sync`, and make it a required job. It's quick, and it tells us if we've broken full validation on the first thousand post-canopy blocks.

(So it catches most full validation bugs.)

**Comment by gustavovalverde** [comment]
Fixed by https://github.com/ZcashFoundation/zebra/pull/3582
