### ISSUE TITLE
Migrate to `tracing-tower`

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#160]
`tracing` now provides a `tracing-tower` crate with functionality for instrumenting tower `Service`s.  We could do a better job of instrumenting the application, by:

1. Checking every implementation of `tower::Service` to see whether it has existing instrumentation that could be replaced by `tracing-tower` functionality;

2. Ensuring that every implementation of `tower::Service` is appropriately instrumented.

This isn't critical to do at any particular time, but it will probably be a nice cleanup.

**Comment by yaahc** [comment]
it looks like `tracing-tower` hasn't been released yet and is only available via git rn, do we still want to go ahead with trying this now or do we want to wait until they make a release?

**Comment by hdevalence** [comment]
Hmm, not sure. If it's only available via git, would we have to load the rest of `tracing` from git?

**Comment by yaahc** [comment]
Yea, I had to do the same thing in my `tracing-flame` draft PR
