### ISSUE TITLE
Zebra stable release binaries should be linked from ZFND website

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1615]
**Is your feature request related to a problem? Please describe.**

Whenever we have a Zebra stable release ready, some people will expect to find it from the main ZFND website.

**Describe the solution you'd like**

We should, at the very least:

- [x] link to the Zebra dockerfile on docker hub. 

We might additionally wish to:

- [ ] Link to the Arch Linux package in the AUR
- [ ] Create and maintain a Debian package
- [x] Link to our github repo and build instructions 

**Describe alternatives you've considered**

Do nothing, people will use a search engine to find Zebra and/or will go directly to our github repository

**Additional context**

Although this did not come up as an issue during the user studies (#1501) for our first alpha release, we do know that some people prefer to click through rather than search so we would like to provide them with this option. For reference this is what is provided from [z.cash/download/](https://z.cash/download/):

- Debian package install instructions (the ECC maintains a package repo for 64-bit Debian-based distributions)
- Binary tarball
- Link to the source code, build instructions and signing keys
- A link to their dockerfile on docker hub

<img width="1160" alt="Screenshot 2023-03-24 at 11 13 38" src="https://user-images.githubusercontent.com/1311133/227493682-d1a9c99c-f95a-4381-8f0e-c96659aeccfe.png">

**Comment by mpguerra** [comment]
@winniendela when we have a stable release ready, we'll probably want to have a section in the new ZFND website where users can download the zebra binary (if we package one up instead of asking users to build from source) cc: @ZcashFoundation/zebra-team

**Comment by winniendela** [comment]
> @winniendela when we have a stable release ready, we'll probably want to have a section in the new ZFND website where users can download the zebra binary (if we package one up instead of asking users to build from source) cc: @ZcashFoundation/zebra-team

Yes for sure, just let me know what you will need. We could have on the header beside the tabs of the website - a Download Zebra Binary button - for this function. I was wondering if the User Documentation should also be moved to zfnd.org website? Or is there a good reason to keep them separate?

**Comment by oxarbitrage** [comment]
I remember creating a debian package was pretty easy https://github.com/ZcashFoundation/zebra/pull/927 but there were some concerns about this that i don't remember exactly what they were(security, privacy, ?). It was also not the time to think on that at that point, i think we might reconsider and maybe have a `.deb` package after all. I am personally not against this particular type of binary.

**Comment by teor2345** [comment]
It's a huge amount of work to package software in multiple formats, and deal with the bug reports from users of all those formats.

So I'd like us to release a single package format that's very easy for users to download and run. (For example, Docker.) Then the Foundation can commit staff time to packaging security fixes and network upgrade releases.

I'd like to find volunteers to support other package formats on a best-effort basis.
(They might or might not be on our website, depending on how secure and reliable the volunteer packages are.)

**Comment by upbqdn** [comment]
> I'd like to find volunteers to support other package formats on a best-effort basis.
(They might or might not be on our website, depending on how secure and reliable the volunteer packages are.)

I can try creating and maintaining a package for Arch Linux.

**Comment by teor2345** [comment]
> > I'd like to find volunteers to support other package formats on a best-effort basis.
> > (They might or might not be on our website, depending on how secure and reliable the volunteer packages are.)
> 
> I can try creating and maintaining a package for Arch Linux.

That would be helpful, but we might all be busy working on NU5 and zebra-client.
So I was hoping to find some volunteers who already package Zcash or other cryptocurrencies for each distribution.

Let's talk about packacing at a Zebra gardening some time soon?

**Comment by dconnolly** [comment]
Not strictly necessary for release candidate

**Comment by mpguerra** [comment]
I'm working on this one with Elise

**Comment by mpguerra** [comment]
This is done for now. Follow up tasks to add a command for running from crates.io and Debian and Arch Linux packages can be done by myself and Elise outside of github.
