### ISSUE TITLE
Move long README sections to the book, to make it easier for new users to get started with Zebra

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1617]
**Is your feature request related to a problem? Please describe.**

From our user studies we discovered that users found the README a bit long and overwhelming and that, after skimming the README, they still asked us about information that was present within.

**Describe the solution you'd like**

Some ideas/suggestions:

- [x] Remove information about First Alpha release in favour of some banner or something else that clearly shows that Zebra is currently at Alpha stage.
- [x] Move "System Requirements" and "Network Requirements" to "Getting Started" section below:
"Building zebrad requires Rust, libclang, and a C++ compiler." and above "Detailed Build and Run Instructions"
- [ ] Expand on Build and run instructions to include explicit and specific about required package managers for various operating systems and other environmental setup, binaries, etc... 
- [ ] Add hints to the "Detailed Build and Run Instructions" section about making sure cargo is in path
- [ ] Link out to Zebra book and provide high level headlines on sections such as "Architecture"

**Describe alternatives you've considered**

Leave the README as is.

**Additional context**

This was discovered during our first alpha user studies (#1501).

**Comment by teor2345** [comment]
This was on the retrospective agenda today, so I'm going to leave it open.
