### ISSUE TITLE
Provide installation scripts for common OSes and Linux distributions for Zebra 

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1619]
**Is your feature request related to a problem? Please describe.**

During our first Zebra user studies (#1501), building and installing Zebra took a while longer than we would have expected due to various different set ups on the user's machines.

**Describe the solution you'd like**

We would like to provide installation scripts for common OSes and Linux distributions for Zebra to make it quicker/easier for users to build and install Zebra.

We will probably want to link to these scripts from the README.
We might also want to run those scripts in CI.

**Describe alternatives you've considered**

We are already improving the installation instructions in #1617

**Comment by dconnolly** [comment]
Removing from the Release Candidate Epic for Q1 2022

**Comment by teor2345** [comment]
We've decided to just focus on one supported platform for now.
