### ISSUE TITLE
Run `zebrad start` by default

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1621]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) we discovered that users were confused about the exact command that they should execute in order to run `zebrad` and in light of their knowledge of how `zcashd` and `bitcoind` are run.

**Describe the solution you'd like**

In order to improve usability, we should: 

- [ ]  run the `start` command by default when a user runs `zebrad`

**Describe alternatives you've considered**

We are already reviewing instructions in the README In #1617

**Comment by oxarbitrage** [comment]
I am not sure if this is possible with abscissa : https://github.com/iqlusioninc/abscissa/issues/101

**Comment by arya2** [comment]
Not currently possible with abscissa
