### ISSUE TITLE
Zebra should tell users about disk space requirements

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1623]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) we discovered that users may be concerned about disk space requirements of a running Zebra node.

**Describe the solution you'd like**

Even though we list the disk space requirements on our README, we could be more explicit about:

1. Telling users about disk space requirements on `zebrad start`
    * our current tracing logs can't really provide this information, because the log messages scroll past really fast
2. Adding more helpful hints on panics due to running out of space

**Describe alternatives you've considered**

We already have this info in our README and are restructuring it to make this information more prominent in #1617

**Comment by teor2345** [comment]
I reworded this ticket, because "warn" has a very specific meaning in Zebra. "Warn" is a tracing a log level, and logging a warning message doesn't really do what we want here.

**Comment by teor2345** [comment]
This will probably get done as part of the README cleanup, or we can re-open it if it becomes an issue again.
