### ISSUE TITLE
`zebrad` terminal user interface improvements

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1624]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) users mentioned that the large amount of scrolling logs could be intimidating and a cause for concern with less experienced users.

**Describe the solution you'd like**

We should review other node software such as `zcashd` and `bitcoind` to see if there are any user interface improvements we can apply to `zebrad`.

We should also investigate using Tui + Termion backend.

**Describe alternatives you've considered**

Expose less verbose logs by default (#1381)

**Additional context**

Some users found the amount of logs reassuring as they could understand what was going on and that the node was working correctly

**Comment by teor2345** [comment]
We've already simplified the Zebra logs. We can re-open this ticket if we decide on a terminal for Zebra's user interface.

(We could use a web page or Grafana dashboard instead.)
