### ISSUE TITLE
Leverage prometheus and grafana to allow users to customize dashboards

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1625]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) users mentioned that the large amount of scrolling logs could be intimidating and a cause for concern with less experienced users.

**Describe the solution you'd like**

In order to allow users to better consume log info and query current and past node status we could package up pre-configured Grafana dashboards with a Dockerfile that can easily be run alongside `zebrad`.

**Describe alternatives you've considered**

We might also want to  expose a web interface to allow users to interact with zebra

**Comment by teor2345** [comment]
We've already simplified the Zebra logs. We can re-open this ticket if we decide on a dashboard for Zebra's user interface.
