### ISSUE TITLE
Investigate exposing web interface to interact with zebra

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1626]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) users mentioned that the large amount of scrolling logs could be intimidating and a cause for concern with less experienced users.

**Describe the solution you'd like**

Instead of providing lots of logs to communicate running `zebrad` status we might want to expose a web interface that users can access to check a current status snapshot for `zebrad`.

We might also want to consider exposing a web API for users to query zebra status.  

**Describe alternatives you've considered**

We are also investigating `zcashd` and `bitcoind` behaviour in #1624 and exposing a grafana dashboard in #1625

**Comment by teor2345** [comment]
We've already simplified the Zebra logs. We can re-open this ticket if we decide on a web page for Zebra's user interface.
