### ISSUE TITLE
Investigate different designs for querying a running Zebra node

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1627]
**Is your feature request related to a problem? Please describe.**

During our first alpha user studies (#1501) users mentioned that they would like to interact with `zebrad` to query specifc information, e.g about a particular transaction.

**Describe the solution you'd like**

We should investigate alternative designs for querying a running Zebra node.

For example:
* a separate command line tool using RPC
  * some RPC methods that might also be used by a wallet command line tool
* a separate command-line tool using a RocksDB secondary database object
  * https://docs.rs/rocksdb/0.16.0/rocksdb/struct.DBWithThreadMode.html#method.open_cf_as_secondary
  * https://docs.rs/rocksdb/0.16.0/rocksdb/struct.DBWithThreadMode.html
* a block explorer web interface

**Comment by teor2345** [comment]
I think this ticket is related to generic RPC, wallet, or block explorer interfaces - so I'm not sure that focusing on specific libraries is going to be helpful here.

Whatever we use as a transport, we're going to have to build our own crate.

**Comment by teor2345** [comment]
We've decided on RPC via lightwalletd to start with, so this ticket is now obsolete.
