### ISSUE TITLE
Remove isolated tracing test?

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1630]
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/ci.yml#L49-L55

Looks the acceptance `tracing_endpoint` was ignored at some point as was added isolated to the CI at https://github.com/ZcashFoundation/zebra/commit/583ec8738ba369881686eca1747f8afe7e613f83

By this comment it seems this test was an issue that then was fixed but the CI part was not updated: https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/acceptance.rs#L37-L38

I dont see any reason to keep this but maybe i am missing something so opening this ticket to confirm we should remove it.

**Comment by teor2345** [comment]
Yeah, I don't think we need to run this test twice, but @dconnolly might know more.
