### ISSUE TITLE
Handle Windows panics in acceptance test exit status checks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1632]
**Is your feature request related to a problem? Please describe.**

In the `zebrad` acceptance tests, Windows tasks that panic seem to return the same exit code as processes that are killed by the test runner.

Edit: We discovered this issue happened because we were calling `kill` on a task that had already panicked.

**Describe the solution you'd like**

Stop calling `kill` on that task.

**Describe alternatives you've considered**

We could do nothing, and our tests would be unreliable on Windows (or our test code would be hard to understand)

**Additional context**

Discovered when fixing #1535

**Comment by oxarbitrage** [comment]
I think i found the cause of this bug and fixed it at https://github.com/ZcashFoundation/zebra/pull/1535/commits/df0e38dc1ee702bc070d872aecf5425896ca165a

Our acceptance test function `check_config_conflict()` was killing both nodes but node2 is already killed by the port conflict panic. Linux seem to dont care about this, it does not fail and the status code remains as not killed. Windows in the other hand mark the program as killed. So, i removed the killing of the second node and also the windows conditional.

**Comment by teor2345** [comment]
Great, thanks for fixing this bug, it would have confused us if we copied that code around.

**Comment by teor2345** [comment]
I've edited the task description and removed the blocker.
