### ISSUE TITLE
Move to the post-Canopy ed25519 signature rules

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1667]
**Is your feature request related to a problem? Please describe.**

Zcash uses a different set of ed25519 signature verification rules after the Canopy network upgrade.

Valid signatures under the new rules are a superset of those under the old rules, so we can just use the new rules for all signatures: `all [Ed25519] signatures that validated under the old rules will validate under the new rules, and there are no new signatures, so you can just retcon all the old signatures as being under the new rules`.

**Describe the solution you'd like**

Update to ed25519-zebra 2.0 or later.

**Describe alternatives you've considered**

This is a required protocol change.

We could verify old signatures under the old rules, and new signatures under the new rules, but that complicates our dependencies.

We could checkpoint on Canopy, but that complicates our code.

**Additional context**

ed25519-zebra explanation: https://github.com/ZcashFoundation/ed25519-zebra#zip-215-and-changes-to-zcash-flavored-ed25519
ZIP-215: https://github.com/zcash/zips/blob/master/zip-0215.rst

**Comment by teor2345** [comment]
This ticket could be medium or large, depending on what we decide to do.

**Comment by str4d** [comment]
You can also decide to continue to verify pre-Canopy signatures for implementation simplicity, but using the post-Canopy rules (which are more expansive).

**Comment by teor2345** [comment]
Thanks I've edited the ticket.

**Comment by dconnolly** [comment]
Depends on https://github.com/ZcashFoundation/zebra/issues/1565
