### ISSUE TITLE
Adjust zebrad Buffer sizes, and document Buffer constraints

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1685]
**Is your feature request related to a problem? Please describe.**

`zebrad` uses a lot of `Buffer`ed services, but we haven't really checked that their bounds are high enough.

The underlying issues are:
- If lots of tasks with data dependencies use a `Buffer` or `Batch` with a small bound, Zebra can hang.
- `Buffer`s or `Batch`es with small bounds can also limit concurrency, particularly if the underlying service does a lot of work in its `call`.

**Describe the solution you'd like**

- [ ] Review `Buffer` bounds across `zebrad`
- [ ] Consider memory denial of service risks, particularly for the inbound buffer, inbound downloads buffer, and sync downloads buffer

Document the `Buffer` constraints in:
- [ ] `commands::start`
- [ ] `components::sync::ChainSync`
- [ ] `components::sync::Inbound`

See #1593 for details - ideally we should point to an RFC here.

**Describe alternatives you've considered**

Do nothing: the code might hang if future changes break the `poll_ready/call` invariants.

**Additional context**

This issue was discovered during the review in #1593. It is a routine cleanup.

**Comment by teor2345** [comment]
This task has been revised based on the fixes to the underlying `Buffer` issue, see #1593 for details.

**Comment by mpguerra** [comment]
we will create other issues as needed
