### ISSUE TITLE
Remove git dependency on tower-load

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#170]
`tower-load` wasn't published on crates.io but it seems that there is now an `0.3` version, so I think that we can drop the git dependency.

**Comment by dconnolly** [comment]
Same with tower proper?

**Comment by dconnolly** [comment]
Closed by https://github.com/ZcashFoundation/zebra/pull/172

**Comment by hdevalence** [comment]
Looks like there may still be one remnant: https://github.com/ZcashFoundation/zebra/blob/main/zebrad/Cargo.toml#L28
