### ISSUE TITLE
Bring source-based coverage job back in, name it explicitly 'nightly'

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1711]
### Tasks

- [ ] Revert the deletion of `.github/workflows/coverage.yml`
- [ ] Check that we're not exceeding the 20 concurrent jobs limit: https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits

**Comment by teor2345** [comment]
Duplicate of #1690

**Comment by teor2345** [comment]
This ticket is a duplicate, so its points do not belong in any sprint.
