### ISSUE TITLE
Fix Rust beta check warnings

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1728]
## Motivation

In #1725, we added beta Rust to CI, but didn't fix the check warnings from beta Rust.

For example: https://github.com/ZcashFoundation/zebra/pull/1709/files#diff-1a4295f873e07d9c71cc313b328d6376d9ba39423db09427dce7b6e7173d27c3

### Redundant `format!`

Remove `format!`:
```rust
        assert!(
            size < (31 + OFFSET) as _,
            format!(
                "256^size (256^{}) must fit in a u256, after the sign bit adjustment and offset",
                size
            )
        )
```

`assert!` can format arguments itself, and this change should silence the warning.

### Passing Error Types to Panic

Explain the error in the string, rather than using the error type:
```rust
            panic!(SerializationError::Parse(
                "bad sprout spending key version/type",
            )
```

An explanation is easier to read than a debug-formatted error.

**Comment by mpguerra** [comment]
reopened to link to #1731 in zenhub
