### ISSUE TITLE
Disable incremental builds for all build steps

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1743]
Should we include this for all build steps, for consistency? @teor2345 thoughts?
Not a blocker to this PR though.

_Originally posted by @dconnolly in https://github.com/ZcashFoundation/zebra/pull/1726#discussion_r576398008_

Do you think we'll ever do anything that will break incremental builds?

Maybe we can disable incremental on `build` to speed up windows and macOS, but leave `build-chain-no-features` as incremental?

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/1726#discussion_r576400348_

This change will speed up all our builds.

**Comment by teor2345** [comment]
Let's quickly do this in the next sprint, to save build time.

**Comment by dconnolly** [comment]
I'm down with this 👍 🏃‍♂️💨
