### ISSUE TITLE
Report remaining disk space as the last CI step

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1744]
It would be nice if CI reported the remaining disk space when the build finished. But that's not a blocker for this PR.

On Linux and macOS, that's `df -h`. Not sure about Windows though. There aren't any GitHub actions for it either.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/1726#issuecomment-779428007_

**Comment by teor2345** [comment]
Let's make this medium priority for now, but if #1726 happens again and we run out of disk space, let's put it as a high priority in the next sprint.

**Comment by gustavovalverde** [comment]
I haven't seen this issue while working on the pipelines, If this ever happens again then we reopen this ticket
