### ISSUE TITLE
Add impact tags on GitHub

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1745]
It's easy to confuse priority and severity, because they both use Low/Medium/High/Critical.

We've been trying to follow the Rust issue labels and colours. Instead of bug severities, they have specific labels that describe the nature of the bug.

I suggest we start with these labels which are relevant to Zebra:

I-consensus :boom:
Zebra breaks a consensus rule (the worst kind of bug)

I-crash
Zebra crashes (without a panic)

I-internal-error
Zebra panics with an internal error message

I-hang
A Zebra component stops responding to requests

I-heavy
Problems with excessive memory, disk, or CPU usage

I-slow
Problems with performance or responsiveness

I-unbounded-growth
Zebra keeps using resources, without any limit

Here is Rust's list:
https://github.com/rust-lang/rust/labels?page=9&sort=name-asc

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/1436#issuecomment-737645245_

**Comment by teor2345** [comment]
Rust also has some meta-tags, which I've left out for now:

I-needs-decision
Issues in need of decision

I-nominated
Issues nominated for discussion during a team meeting

I-prioritize
Issues that need prioritization

**Comment by teor2345** [comment]
I added this tag to categorise unbounded growth, particularly in response to bad data from peers:

I-unbounded-growth
Zebra keeps using resources, without any limit

**Comment by mpguerra** [comment]
> Rust also has some meta-tags, which I've left out for now:
> 
> I-needs-decision
> Issues in need of decision

It might be nice to tag issues that we want to make a decision on as we see them but I'm not sure I would put this under impact, also I don't know that we have a problem keeping track of these. What does everyone else think?

> I-nominated
> Issues nominated for discussion during a team meeting

Similar to my comment above, unless we see we are losing track of issues someone wants to discuss during meetings and/or asynchronously, a lot of this comes up as part of the triage process. 

> I-prioritize
> Issues that need prioritization

I don't think we need this last one as we already do prioritization as part of our triage

**Comment by mpguerra** [comment]
Done!

<img width="652" alt="Screenshot 2021-02-16 at 17 16 39" src="https://user-images.githubusercontent.com/1311133/108090291-bdf1e600-707a-11eb-9a13-d29890360fbe.png">

**Comment by teor2345** [comment]
I think the needs-triage tag works well for us right now, we don't need to duplicate it under impact.
