### ISSUE TITLE
Add config file comments on how to configure metric, tracing, rpc endpoints

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1772]
**Is your feature request related to a problem? Please describe.**
When i want to start zebrad with some custom config options i generate a config file with:

`./target/debug/zebrad generate -o myconfig` 

Then i do mods to the `myconfig` file and start the node using:

`./target/debug/zebrad -c myconfig start`

All good there but lets suppose i want to start a metrics or tracing endpoint. In the generated file i only have the section header for the metrics:

```
[metrics]
```
and for the tracing:

```
[tracing]
use_color = true
```

So if i want to open some of this services i don't know how, so i need to check in the code to realize that i need to use `endpoint_addr` in the case of the metrics and `endpoint_addr` also for the tracing. The most common mistake is to try `listen_addr` as this is the only example we have in the config.

**Describe the solution you'd like**

1- Add some comment about this into the top of the config file.

**Describe alternatives you've considered**

We can maybe add a comment of the option directly into the section, something like:

```
[metrics]
# endpoint_addr = "127.0.0.1:9999"
```

2- Do nothing, users can get confused.

This is low priority.

**Comment by mpguerra** [comment]
This is already documented in our zebra book (https://doc.zebra.zfnd.org/zebrad/config/struct.TracingSection.html and https://doc.zebra.zfnd.org/zebrad/config/struct.MetricsSection.html) but maybe we could add some details to the README so users know where to look or add these links to the config file
