### ISSUE TITLE
Skip duplicate GitHub actions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1786]
**Is your feature request related to a problem? Please describe.**

To speed up CI, we should skip duplicate GitHub actions.

**Describe the solution you'd like**

Add a skip duplicate actions step to every workflow job:
https://github.com/marketplace/actions/skip-duplicate-actions

The defaults should be fine for everything except CD, see #1785 for the CD config.

**Describe alternatives you've considered**

Do nothing: CI is a bit slower

**Comment by gustavovalverde** [comment]
We've solved most of this problem using reusable workflows
