### ISSUE TITLE
Re-enable `sync_large_checkpoints_testnet` test

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#1791]
## Motivation

In PRs #1789 and #1887 we removed the `sync_large_checkpoints_testnet` because the testnet is unreliable.

## Solution

This ticket is to bring that test back after we:
- [x] deploy more testnet nodes
- [ ] fix the DNS seeders to remove unreliable or down nodes

## Alternatives

* increase the testnet acceptance test timeouts
* decrease the number of blocks we sync on testnet
* just disable the test and leave it disabled

**Comment by teor2345** [comment]
We disabled these tests again in #1887, it looks like the `zcashd` instances from #1222 aren't turning up in the DNS seeders.

(But they seem to be interacting with the network OK, so this might be a DNS seeder issue.)

**Comment by teor2345** [comment]
We've decided not to fix some blockers for this ticket, so we can't do this ticket either.
