### ISSUE TITLE
NetworkUpgrade::NU5 and network protocol version

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1797]
**Is your feature request related to a problem? Please describe.**

We want to add a `NetworkUpgrade::NU5` network upgrade variant, and a network protocol version for `NU5`.

As part of this change, we need to write a draft NU5 ZIP.

**Describe the solution you'd like**

- [x] write a draft NU5 ZIP
  - we don't need to have a list of included ZIPs, just the branch id / numbers / etc.
  - https://github.com/zcash/zips/pull/446
- [x] add a `NetworkUpgrade::NU5` network upgrade variant
  - activation block heights will be `None` until the `NU5` ZIPs are decided and the target dates are set
  - https://github.com/ZcashFoundation/zebra/blob/128643d81e357157bfb3af3725bac653abfb402e/zebra-chain/src/parameters/network_upgrade.rs#L16
- [x] add the `NU5` consensus branch ID
  - https://github.com/ZcashFoundation/zebra/blob/128643d81e357157bfb3af3725bac653abfb402e/zebra-chain/src/parameters/network_upgrade.rs#L89
- [x] add a network protocol version for `NU5`
  - https://github.com/ZcashFoundation/zebra/blob/128643d81e357157bfb3af3725bac653abfb402e/zebra-network/src/protocol/external/types.rs#L46

For future reference, we also made this change:
- [x] add NU5 to the protocol::version_consistent test
  - https://github.com/ZcashFoundation/zebra/blob/128643d81e357157bfb3af3725bac653abfb402e/zebra-network/src/protocol/external/types.rs#L190

**Describe alternatives you've considered**

These changes are required for NU5.

**Additional context**

NU4 ZIP: https://zips.z.cash/zip-0251
NU5 ZIP: https://github.com/zcash/zips/pull/446

**Comment by teor2345** [comment]
We've talked to the `zcashd` team, and they're happy for us to write the draft NU5 ZIP.

**Comment by teor2345** [comment]
> We've talked to the `zcashd` team, and they're happy for us to write the draft NU5 ZIP.

The draft ZIP is at https://github.com/zcash/zips/pull/446 , it has passed initial review.

**Comment by oxarbitrage** [comment]
It looks like `NetworkUpgrade::NU5` should be `NetworkUpgrade::Orchard` ?

**Comment by str4d** [comment]
No. Orchard is the name of the proposed new shielded pool, not the name of the upgrade (which as proposed includes things other than Orchard). We made this mistake for Sapling (naming the upgrade after the pool), and it has caused non-trivial confusion.

**Comment by oxarbitrage** [comment]
So, to be extra clear. The name of the upgrade will be `NU5` even if previous ones had names like `Sapling`, `Blossom`, etc. Is that correct or `NU5` will actually have a name(different than `Orchard`)?

**Comment by oxarbitrage** [comment]
Forget https://github.com/ZcashFoundation/zebra/issues/1797#issuecomment-787092788, the code name is actually `NU5` according to the draft zip: https://github.com/teor2345/zips/blob/zip-252-nu5/zip-0252.rst#terminology

Thanmk you @str4d

**Comment by teor2345** [comment]
> So, to be extra clear. The name of the upgrade will be `NU5` even if previous ones had names like `Sapling`, `Blossom`, etc. Is that correct or `NU5` will actually have a name(different than `Orchard`)?

The code-name for the sixth Zcash network upgrade has not been chosen yet.

I've updated the draft ZIP to reflect that:
https://github.com/zcash/zips/pull/446/files#r584385297

There are three possible outcomes for Zebra:
* There is no code name chosen, and the enum keeps getting called `NU5`
* The community chooses a code name, the enum keeps getting called `NU5`, and everything works
* The community chooses a code name, we use `fastmod` or a similar tool to easily change `NU5` to that name

(We don't need to make that decision now.)
