### ISSUE TITLE
Implement ZIP-216: Require Canonical Point Encodings

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1798]
https://github.com/zcash/zips/issues/400
https://zips.z.cash/zip-0216
https://github.com/zkcrypto/jubjub/issues/43

Blocked on the [jubjub crate implementing this](https://github.com/zkcrypto/jubjub/issues/43), or we implement it ourselves.

**Comment by teor2345** [comment]
I moved this task to sprint 13 because the anchors are a higher priority - they are blocking the history chain contextual validation and testing.

@dconnolly should we re-estimate this task? I think it's only a dependency update?
