### ISSUE TITLE
Update tower-batch to avoid hangs on drop

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1805]
**Is your feature request related to a problem? Please describe.**

`tower-batch` is missing a semaphore fix that wakes waiting clones on close: tower-rs/tower#480

**Describe the solution you'd like**

- [x] Copy the version of `semaphore.rs` included in our pinned version of `tower`, to `tower-batch/src/`: https://github.com/tower-rs/tower/blob/d4d1c67c6a0e4213a52abcc2b9df6cc58276ee39/tower/src/semaphore.rs
- [x] Add the `Sync` bound to the semaphore future
- [x]  Update `tower_batch::Buffer`: https://github.com/tower-rs/tower/pull/480/files#diff-35398bbf39b455b121231a971e231cfc669556eda1c98705f367aa774f3da86c
  - [x] use `new_with_close` in `pair` 
  - [x] use `pair` in `new` 
 - [x] Update `tower_batch::Worker`: https://github.com/tower-rs/tower/pull/480/files#diff-868107348117bb575baa89a1a3aae31fb03e020ed6d709fe45443c4d65aefceb
   - [x] use `pin_project(PinnedDrop)` on `Worker`
   - [x] add `close` to `Worker`
   - [x] use `close` to wake waiting tasks on error
   - [x] copy `PinnedDrop`

**Describe alternatives you've considered**

Do nothing: `tower-buffer` users might hang.

**Additional context**

This issue was discovered during the review in #1593. It was partly fixed by #1671.

**Comment by mpguerra** [comment]
closed by #1908
