### ISSUE TITLE
Sprout note encryption/decryption implementation.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#181]
We need an implementation of note encryption.  This has possible overlap with `librustzcash`.

![image](https://user-images.githubusercontent.com/552961/77574006-e04da480-6ea7-11ea-94f3-34030567c6c6.png)

https://zips.z.cash/protocol/protocol.pdf#sproutencrypt
https://zips.z.cash/protocol/protocol.pdf#sproutdecrypt

**Comment by dconnolly** [comment]
Two levels of completion:

All the types to represent in the transaction 

Some types:
- [ ] sprout::Note (plaintext)
- [ ] sprout::OutCiphertext 
- [ ] sprout::EncryptedCiphertext

And implementing methods to do the note encryption
- [ ] NoteEncryptionBuilder 

But first:
- note commitment trees: https://github.com/ZcashFoundation/zebra/issues/36
- addresses
- as above, full Note implementation

Related: #266

**Comment by teor2345** [comment]
@dconnolly does this belong in the "Transaction Validation" milestone, or the "Wallet Support" milestone?

**Comment by dconnolly** [comment]
Wallet support

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
