### ISSUE TITLE
Parse Sapling data in Transaction Version 5

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1829]
## Is your feature request related to a problem?

In #1824, we parse the transaction header and transparent data for transaction version 5.

Transaction version 5 also contains Sapling data, which we need to parse:
* Design: https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0010-v5-transaction.md#sapling-changes
* Spec: https://zips.z.cash/protocol/nu5.pdf#txnencodingandconsensus

#### Spend

Implement serialization and deserialization for:
- [x] `Spend<PerSpendAnchor>` (moved from the pre-RFC `Spend`)
- [x] `SpendPrefixInTransactionV5` (new)
- [x] `redjubjub::Signature<redjubjub::SpendAuth>` (new - for v5 spend auth sig arrays)

Test `Arbitrary` `Spend` (both variants):
- [x] round-trip serialization and deserialization
- [x]  trusted vector deserialization

#### Output

Implement serialization and trusted vector deserialization for:
- [x] `OutputInTransactionV4` (moved from `Output`)
- [x] `OutputPrefixInTransactionV5` (new)

Test `Arbitrary` `Output` (both transaction versions):
- [x] round-trip serialization and deserialization
- [x]  trusted vector deserialization

#### ShieldedData

Documentation
- [x] read the relevant consensus rules in the spec
- [x] read the relevant RFC section
- [x] summarise them in each struct and function's docs

Implement serialization and deserialization for:
- [x] `Option<sapling::ShieldedData<SharedAnchor>>`
  - unlike v4 transactions, v5 sapling shielded data can be serialized into continuous bytes
  - https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0010-v5-transaction.md#changes-to-sapling-shieldeddata
  - for an example, see `Option<sprout::JoinSplitData>` at https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/transaction/serialize.rs#L34

Test`Arbitrary` `Option<sapling::ShieldedData<SharedAnchor>>`
- [x] round-trip serialization and deserialization

Test manual implementations:
- [x] Proptest the `PartialEq` impl for `ShieldedData<SharedAnchor>`
  - see the `ShieldedData<PerSpendAnchor>` tests in https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/sapling/tests/prop.rs
  - these tests should be simpler, because `ShieldedData<SharedAnchor>` has serialization impls, so it doesn't need to be wrapped in a transaction for serialization

#### Transaction

- [x] Parse the Sapling section of V5 transactions using ShieldedData
- [x] return an empty iterator for transaction version 5 in `sprout_nullifiers`
- [x] implement transaction version 5 in `sapling_nullifiers`

Test`Arbitrary` `Transaction::V5`
- [x] round-trip serialization and deserialization

#### Cleanups and Refactoring

  - Redesign data model (again)
    - [x] shared anchor only present when there are v5 spends #2021 
    - [x] simplify "at least one" constraint #2028

### Testing

Test round-trip serialization and deserialization for transaction v4 and v5 (without orchard)

#### Unit tests

  - [x] an empty transaction v5, with no Sapling or Transparent data
    - empty transaction are invalid, but Zebra only checks this rule in `zebra_consensus::transaction::Verifier`
  - [x] v5 with empty sapling spends, some outputs
    - covers the shared anchor serialization condition
  - [x] an empty transaction v4, with no Sapling, Sprout, or Transparent data
    - empty transaction are invalid, but Zebra only checks this rule in `zebra_consensus::transaction::Verifier`

#### Test vectors

  - [x] "Fake" Sapling-only and Sapling/Transparent v5 transactions based on `zebra_test::vectors::block::BLOCKS` 
    -  provides Sapling only, Transparent only, and Sapling/Transparent test vectors
    - we can write a test utility function to "convert" transactions from `V4` to `V5` format
    - some transactions won't convert because they have multiple sapling anchors
  - work out why these tests fail on blocks, but not transactions (#2023)

  - transaction v5 sapling-only test vectors from `zcashd` (or created by us and shared with `zcashd`)

## Describe alternatives you've considered

This is a required change for `NU5`.

## Follow Up Tasks

"Fake" Sapling-only and Sapling/Transparent v5 transactions based on `zebra_test::vectors::block::BLOCKS` 
  - work out why these tests fail on blocks, but not transactions (#2023)

Test vectors
  - transaction v5 sapling-only test vectors from `zcashd` (or created by us and shared with `zcashd`) - #2047

**Comment by oxarbitrage** [comment]
Blocked on https://github.com/ZcashFoundation/zebra/issues/1863

**Comment by mpguerra** [comment]
I just wanted to highlight this item from the [spec](https://zips.z.cash/protocol/nu5.pdf#saplingbalance) which may be relevant here also: 

> For a v5 transaction, vbalanceSapling is implicitly zero if the transaction has no Spend descriptions
or Output descriptions.

**Comment by teor2345** [comment]
> I just wanted to highlight this item from the [spec](https://zips.z.cash/protocol/nu5.pdf#saplingbalance) which may be relevant here also:
> 
> > For a v5 transaction, vbalanceSapling is implicitly zero if the transaction has no Spend descriptions
> > or Output descriptions.

Thanks Pili, that was a bug in the draft PR, I've added a comment at https://github.com/ZcashFoundation/zebra/pull/1860/files#r595643213

**Comment by teor2345** [comment]
> > I just wanted to highlight this item from the [spec](https://zips.z.cash/protocol/nu5.pdf#saplingbalance) which may be relevant here also:
> > > For a v5 transaction, vbalanceSapling is implicitly zero if the transaction has no Spend descriptions
> > > or Output descriptions.
> 
> Thanks Pili, that was a bug in the draft PR, I've added a comment at https://github.com/ZcashFoundation/zebra/pull/1860/files#r595643213

These was actually also a missing related Orchard spec rule as well:
<img width="840" alt="Screen Shot 2021-03-18 at 08 41 45" src="https://user-images.githubusercontent.com/8951843/111549360-c6e3ed80-87c7-11eb-84bd-df097a41d93c.png">

I've opened #1917 to implement those rules, and I'll also update the transaction RFC.

**Comment by teor2345** [comment]
I opened #2023 and #2047 for follow-up, so we can close this ticket now.
