### ISSUE TITLE
Integrate async JoinSplit Groth16 verifier with transaction verifier

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1835]
In https://github.com/ZcashFoundation/zebra/pull/1713 we integrated the Spend and Output Groth16 async verification, after loading the public Sapling verification params.

Similarly, we'll download the JoinSplit proofs in ticket #3037, and validate them in ticket #322.

Then the Sprout JoinSplit verifier needs to be integrated with the rest of the system and fully tested.

## Todo

- [ ] Integrate the JoinSplit groth16 async verifier instance with the transaction verifier using the aforementioned keys

**Comment by teor2345** [comment]
This validation isn't in our current list of exceptions for testnet NU5 activation. But we could add it if needed.
