### ISSUE TITLE
NU5 Tracking Epic

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#1841]
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/1823 we added initial support for `NU5` to zebra. Right now this support is incomplete since we have not finished drafting the zip for the next network upgrade, so we don't yet know things like the activation height or the precise consensus rule changes that will be made in NU5.
-Track all NU5 epics

## Solution

Once we've finalized the proposal for `NU5` we need to follow up on the initial support to replace various `todo`'s in the code and replace them with the specified logic.

Note: NU5 also contains other ZIPs, see #1598 and ZIP-252.

### Testnet: ZIP-252

Zebra:
- [x] #2793
- [x] #2794
- [x] #2795
- [x] #2798

DNS Seeders:
- [x] #2796
  - [x] #2808
- [x] #2797

The DNS seeders don't check the activation height. So it's ok to increase the maximum version a few weeks early.

### Mainnet: ZIP-252

Zebra mainnet:
- [x] #4115
- [x] #3948
- [x] #4117 (after activation)

Zebra testnet:
- [x] #4116 (after activation)

DNS Seeders:
- [x] Increment the maximum network protocol version accepted by the foundation's DNS seeders to `170_017`
- [x] Re-deploy the foundation's DNS seeders
  - Check that the mainnet seeder is returning new peers
  - Check that the testnet seeder continues to return new peers

**Comment by teor2345** [comment]
@yaahc I sorted the tasks by ZIP and added ticket numbers for the tickets that have already been opened.

There's a bit of overlap between this ticket and the epic ticket #1598, how do you want to resolve that?

Maybe we should make this ticket about the generic network upgrade process (ZIP-252), and move all the other tasks to #1598?

**Comment by yaahc** [comment]
> There's a bit of overlap between this ticket and the epic ticket #1598, how do you want to resolve that?
>
> Maybe we should make this ticket about the generic network upgrade process (ZIP-252), and move all the other tasks to #1598?

Not sure, I think I'll leave that up to @mpguerra to decide how to track everything.

**Comment by mpguerra** [comment]
Removed 

> ZIP-244:
> - [ ] update `RootHash::from_bytes` #881
> - [ ] update `sighash`

from issue description and moved to #1874 where this work will be done.

Tracking for ZIP-244 is done in #1854

**Comment by mpguerra** [comment]
Thinking about it some more, I've made this into ZIP 252 as suggested and added it to #1854 ZIP tracking issue

**Comment by teor2345** [comment]
We haven't chosen the testnet activation height yet, moving this ticket to sprint 13.

**Comment by mpguerra** [comment]
Blocked until we know the NU5 activation heights

**Comment by mpguerra** [comment]
Removing from Sprint 19 as this is now more of a tracking ticket containing mainnet activation tasks also

**Comment by teor2345** [comment]
We updated the DNS seeder network protocol versions as part of #2882.

**Comment by teor2345** [comment]
NU5 activated 3 days ago.
