### ISSUE TITLE
NU5 Tracking: Required ZIPs

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1854]
This epic will track the ZIPs that we will need to implement ahead of NU5 testnet activation.

A strikethrough means that we:
- have implemented that item
- are tracking that item in another Epic, or
- have otherwise resolved that item.

Our mandatory Canopy checkpoint significantly reduces the number of features that we have to implement.

- NU5 Proposed ZIPs
    - [ZIP 216: Require Canonical Jubjub Point Encodings](https://zips.z.cash/zip-0216) - #1798 
    - ~[ZIP 224: Orchard Shielded Protocol](https://zips.z.cash/zip-0224) - #1742~
    - [ZIP 225: Version 5 Transaction Format](https://zips.z.cash/zip-0225) - ~#1822~, ~#1829~, ~#1863~, #1979
    - [ZIP 244: Transaction Identifier Non-Malleability](https://zips.z.cash/zip-0244) - #1874, ~#881~
    - [ZIP 252: Deployment of the NU5 Network Upgrade](https://zips.z.cash/zip-0252) - #1841, ~#1797~
    - [ZIP 239: Relay of Version 5 Transactions](https://zips.z.cash/zip-0239) - 
    - #2681 
- NU4: Canopy
    - [ZIP 207: Funding Streams](https://github.com/zcash/zips/blob/master/zip-0207.rst) - #801 (excluding founders reward)
    - [ZIP 211: Disabling Addition of New Value to the Sprout Value Pool](https://github.com/zcash/zips/blob/master/zip-0211.rst) - #1564
    - [ZIP 212: Allow Recipient to Derive Sapling Ephemeral Secret from Note Plaintext](https://github.com/zcash/zips/blob/master/zip-0212.rst) - #785 (excluding sender)
    - [ZIP 214: Consensus rules for a Zcash Development Fund](https://github.com/zcash/zips/blob/master/zip-0214.rst) - #801 (excluding founders reward)
    - ~[ZIP 215: Explicitly Defining and Modifying Ed25519 Validation Rules](https://github.com/zcash/zips/blob/master/zip-0215.rst) - #1565~ 
    - [ZIP 251: Deployment of the Canopy Network Upgrade](https://github.com/zcash/zips/blob/master/zip-0251.rst) - #1597 
- NU3: Heartwood
    - [ZIP-221: Flyclient](https://zips.z.cash/zip-0221) - #1567 
    - [ZIP-213: Shielded Coinbase](https://zips.z.cash/zip-0213) - #608 
    - ~~[ZIP 250: Deployment of the Heartwood Network Upgrade](https://zips.z.cash/zip-0250)~~
- ~~NU2: Blossom~~
    - ~~[ZIP-208: Shorter Block Target Spacing](https://zips.z.cash/zip-0208)~~
    - ~~[ZIP-206: Deployment of the Blossom Network Upgrade](https://zips.z.cash/zip-0206)~~
- ~~NU1: Sapling~~
    - ~~[ZIP-243: Transaction Signature Validation for Sapling](https://zips.z.cash/zip-0243)~~
    - ~~[ZIP-32: Shielded Hierarchical Deterministic Wallets](https://zips.z.cash/zip-0032)~~ - #267 (wallets only, sapling and orchard only)
    - ~~[ZIP 205: Deployment of the Sapling Network Upgrade](https://zips.z.cash/zip-0205)~~
        - ~[Change to difficulty adjustment on Testnet](https://zips.z.cash/zip-0205#change-to-difficulty-adjustment-on-testnet) - #1256~ 
- NU0: Overwinter
    - ~~[ZIP-143: Transaction Signature Validation for Overwinter](https://zips.z.cash/zip-0143)~~
    - [ZIP-200: Network Upgrade Mechanism](https://zips.z.cash/zip-0200) - #337
    - [ZIP-201: Network Peer Management for Overwinter](https://zips.z.cash/zip-0201) - #706
    - ~~[ZIP-202: Version 3 Transaction Format for Overwinter](https://zips.z.cash/zip-0202)~~
    - ~~[ZIP-203: Transaction Expiry](https://zips.z.cash/zip-0203)~~
- Sprout
  - [ZIP-209: Prohibit Negative Shielded Chain Value Pool Balances](https://zips.z.cash/zip-0209) - #1895 #2381

**Comment by teor2345** [comment]
@mpguerra @dconnolly I've added some missing ZIPs (and one section that probably should have been a separate ZIP). I've also crossed out some ZIPs we've implemented already.

Our next task should be to split the tickets for the following ZIPs into essential validation work, and other work that's out of scope:
    - [ZIP 207: Funding Streams](https://github.com/zcash/zips/blob/master/zip-0207.rst) - #801 (excluding founders reward)
    - [ZIP 214: Consensus rules for a Zcash Development Fund](https://github.com/zcash/zips/blob/master/zip-0214.rst) - #801 (excluding founders reward)
    - [ZIP 212: Allow Recipient to Derive Sapling Ephemeral Secret from Note Plaintext](https://github.com/zcash/zips/blob/master/zip-0212.rst) - #785 (excluding sender)
    - [ZIP-32: Shielded Hierarchical Deterministic Wallets](https://zips.z.cash/zip-0032) - #267 (validation only)

@dconnolly do you want to take ZIP 32 and 212? And I'll take ZIPs 207 and 214?

**Comment by mpguerra** [comment]
Do we also need to explicitly create an issue for ZIP-209? Or is that work already covered in our block validation code?

**Comment by teor2345** [comment]
> Do we also need to explicitly create an issue for ZIP-209? Or is that work already covered in our block validation code?

I think it's best that we have a separate ticket, because it needs some cached state data structure changes.

**Comment by mpguerra** [comment]
Removed #1864 as this is already tracked in #1856

**Comment by mpguerra** [comment]
Removed #1334 and #1820 as these are already tracked under #1853
