### ISSUE TITLE
ZIP-209: Prohibit Negative Shielded Chain Value Pool Balances - Implementation

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1895]
## Motivation

ZIP-209 defines how the consensus rules are altered such that blocks that produce negative shielded chain value pool balances are prohibited.

#### Transparent

Note: there is no explicit rule that the remaining balance in the transparent *chain* value pool must be non-negative. But it is implicit in the other consensus rules.

#### Sprout

> As defined in [ZIP-209], the Sprout chain value pool balance for a given block chain is the sum of all vold field
values for transactions in the block chain, minus the sum of all vnew fields values for transactions in the block chain.
>
> Consensus rule: If the Sprout chain value pool balance would become negative in the block chain created as a result of accepting a block , then all nodes MUST reject the block as invalid.

https://zips.z.cash/protocol/protocol.pdf#joinsplitbalance

#### Sapling

> As defined in [ZIP-209], the Sapling chain value pool balance for a given block chain is the negation of the sum of all valueBalanceSapling field values for transactions in the block chain.
>
> Consensus rule: If the Sapling chain value pool balance would become negative in the block chain created as a result of accepting a block , then all nodes MUST reject the block as invalid.

https://zips.z.cash/protocol/protocol.pdf#saplingbalance

#### Orchard

> Similarly to the Sapling chain value pool balance defined in [ZIP-209], the Orchard chain value pool balance for a given block chain is the negation of the sum of all valueBalanceOrchard field values for transactions in the block chain.
>
> Consensus rule: If the Orchard chain value pool balance would become negative in the block chain created as a result of accepting a block , then all nodes MUST reject the block as invalid.

https://zips.z.cash/protocol/protocol.pdf#orchardbalance

## Solution

We should implement [ZIP-209](https://zips.z.cash/zip-0209) in Zebra for the Transparent, Sprout, Sapling, and Orchard pools.

**Comment by teor2345** [comment]
I explicitly listed all 3 shielded value pools in this ticket, and added the transparent pool consensus rule as well.

(We might as well implement all 4 at the same time, the data structures and code are very similar.)

**Comment by oxarbitrage** [comment]
This implementation will be done following the specs at https://github.com/ZcashFoundation/zebra/pull/2430

**Comment by mpguerra** [comment]
Are #2599 and #2610 the last 2 outstanding PRs before we can close this one or is there something else to be done?

**Comment by oxarbitrage** [comment]
This is the last PR we have to close this issue when merged: https://github.com/ZcashFoundation/zebra/pull/2652
