### ISSUE TITLE
Validate Action Proofs

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#1912]
As per the [NU5 spec](https://zips.z.cash/protocol/nu5.pdf#actionstatement) we need to validate Action Statements

**Comment by mpguerra** [comment]
@dconnolly is this the same as #2105 ?

**Comment by mpguerra** [comment]
closing as a duplicate of #2105

**Comment by teor2345** [comment]
> @dconnolly is this the same as #2105 ?

Just confirming that Action proofs are Halo2 proofs, so the tickets are duplicates.
