### ISSUE TITLE
Check Transaction cardinality at parse time, to limit memory usage

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1917]
## Motivation

Zebra can use a lot of memory when parsing malicious transactions, but we can use existing consensus rules to limit memory usage at parse time.

<img width="840" alt="Screen Shot 2021-03-18 at 08 41 45" src="https://user-images.githubusercontent.com/8951843/111548107-eb3eca80-87c5-11eb-8ffb-1b11cfb9c423.png">

We should also `Box` some of the large `Option`al data structures, so that memory isn't allocated unless they are actually used. Then we can statically assert that the `Transaction`, `Output`, and `Spend` types aren't too large.

We should make these fixes after the Orchard designs and code (#1886 and #1860) and `SafeAllocate` (#1920) are implemented.

## Solution

- [ ] Implement all the above count consensus rules when deserializing transactions (rather than during semantic verification)
  - The Sapling rules are currently implemented in `zebra_consensus::transaction::check::has_inputs_and_outputs`
- [x] Write tests that assert the `SafeAllocate` limits for `Spend`, `Output` and `Action` are all less than `2^16` (done in #3069 and #3076)

## Alternative Designs

We could `Box` data structures that are inside `Vec`s, but that increases memory fragmentation, and doesn't help if the incoming message or block has enough data to fill the `Vec`.

**Comment by teor2345** [comment]
Actually Orchard is more important than this local node security fix.

**Comment by mpguerra** [comment]
Adding this one to Sprint 24 for discussion

**Comment by teor2345** [comment]
> Adding this one to Sprint 24 for discussion

We just did the most important part of this ticket in PRs #3069 and #3076.

But I'm happy to discuss the rest.

**Comment by mpguerra** [comment]
This is done
