### ISSUE TITLE
Add signature validation telemetry metrics for all signature types at all levels

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#1966]
## Motivation 

We're starting to collect metrics for some of our batch signature and proof validation services. We should make sure we measure all the primitives we verify, so that we can see how many signatures we're verifying of each type over time.

## Solution 

Add:
`metrics::counter!("zebra.verified.signature.valid", 1, type => $TYPE, source => mempool/chain)`
`metrics::counter!("zebra.verified.signature.invalid", 1, type => $TYPE, source => mempool/chain)`

for each of $TYPE:
- [x] Orchard RedPallas signatures
- [x] Sapling RedJubjub signatures
- [ ] Sprout Ed25519 signatures
- [ ] Transparent secp256k1 script signatures (?)
  - Transparent signatures are verified using our script verifier service, so we may have to go inside zcash_script to instrument accurately

**Comment by teor2345** [comment]
I've updated the metric names to match zcash/zcash#4947, and confirmed that we use `zcash_script` to verify transparent signatures.

@str4d may also have opinions on these metric names.

**Comment by str4d** [comment]
I would suggest the prefix `zcash.chain.verified.*` to match other chain metrics, and I would also suggest making `$TYPE` a label (since signature types being verified by a full node will be low-cardinality):

- `metrics::increment_counter!("zcash.chain.verified.signature.valid", "kind" => $TYPE)`
- `metrics::increment_counter!("zcash.chain.verified.signature.invalid", "kind" => $TYPE)`

**Comment by teor2345** [comment]
> I would suggest the prefix `zcash.chain.verified.*` to match other chain metrics, and I would also suggest making `$TYPE` a label (since signature types being verified by a full node will be low-cardinality):
> 
> * `metrics::increment_counter!("zcash.chain.verified.signature.valid", "kind" => $TYPE)`
> * `metrics::increment_counter!("zcash.chain.verified.signature.invalid", "kind" => $TYPE)`

In Zebra, chain and mempool verification will go through the same batch verifiers, so those names won't quite work for us.

I guess we could tag requests with "chain" or "mempool" as part of this change?

**Comment by str4d** [comment]
Ah interesting, so mempool signature verification is bundled in with any concurrent block verification? In that case I agree that this should be outside the `zcash.chain` prefix. And if the node is caching verification success then mempool verification would displace block verification. So it might make sense to label by verification source (mempool or block), but probably is less interesting than by kind.

**Comment by teor2345** [comment]
We don't cache the results of transactions, but I guess we could if we wanted to. A cache wouldn't be much use for the initial sync, but it would help near the tip. Particularly during a chain fork.

**Comment by teor2345** [comment]
> And if the node is caching verification success then mempool verification would displace block verification.

Caching successful verifications is now #1968.

**Comment by teor2345** [comment]
This might be needed as part of benchmarking.

**Comment by dconnolly** [comment]
RedPallas and RedJubjub signature verifications are being tracked as of 1.0.0-beta.11

**Comment by teor2345** [comment]
This isn't a priority for Zebra right now.
