### ISSUE TITLE
Consider caching expensive signature and proof verification results

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1968]
**Is your feature request related to a problem? Please describe.**

When Zebra has a mempool and chain validator, it will verify most transactions twice: once in the mempool, and once in a mined block. During a chain fork, it might even verify them 3 or more times.

We could cache these verification results, so that we only have to do this work once.

**Describe the solution you'd like**

- Keep an in-memory cache of recently verified non-malleable transaction IDs, along with the corresponding authorisation tree ID
- When we see matching non-malleable and authorisation IDs in the transaction verifier, skip verification, and return the same result straight away
  - security: both the effects (actions) and authorisation (signatures/proofs) have to match for the transaction to be valid
- Caching successes and failures is useful, because both help resist denial of service attacks, and both reduce load
- We'll need to be careful of LockTime, UTXOs/nullifiers, and any other context-dependent verification outcomes
- Design this feature as a generic re-usable tower layer
  - check to see if tower already has a suitable caching layer

**Describe alternatives you've considered**

We could also cache results just above the batch layer. Caching above the batcher could take up more memory, and it would be more complex. But it would also allow us to skip more verification - for example, multiple attempts to post the same transaction, but with different expiry heights.

But transaction-level caching is a good architectural match for our existing block-level cache.

**Additional context**

We'll need to have a mempool before this feature has much benefit.

**Comment by dconnolly** [comment]
Great idea 💖

**Comment by daira** [comment]
> Keep an in-memory cache of recently verified non-malleable transaction IDs, along with the corresponding authorisation tree ID
> When we see a matching pair of IDs in the transaction verifier, skip verification, and return the same result straight away

~~This is not a correct optimization. Suppose that we saw a transaction with a given non-malleable ID in the mempool, and its signatures are correct. It's possible to see a transaction with the same ID again in a block, but with invalid signatures. (Obviously, it will be an invalid block, but block validity is what we're supposed to be checking.)~~

~~That's the point of the non-malleable ID –that it *doesn't* depend on signatures or proofs– but that also means it doesn't depend on whether signatures or proofs are valid.~~

Oh sorry, you said the authorization tree ID had to match as well. Yes that's fine, carry on :-)

**Comment by teor2345** [comment]
This is a good idea for an optimisation, but other optimisations are more valuable.
