### ISSUE TITLE
Use valuable::Enumerable to iterate through network upgrades

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1974]
**Is your feature request related to a problem? Please describe.**

Some of Zebra's tests iterate through the entire set of network upgrades. Others want to know the latest network upgrade, even if it doesn't have an activation height.

If we use the valuable crate's Enumerable derive, we won't need to change these tests every time we add a new network upgrade.

https://github.com/tokio-rs/valuable

**Describe the solution you'd like**

- [ ] Wait for `valuable` to be published to https://crates.io/crates/valuable
  - possibly outdated plans: https://tokio.rs/blog/2021-05-valuable
- [ ] Derive `Enumerable` for `NetworkUpgrade`

A list of network upgrades:
- [ ] Change the `version_consistent` test to use `Enumerable`'s `EnumDef`
- [ ] Check if any `zebra_chain::parameters` tests could also use `EnumDef`

The latest network upgrade (even if it doesn't have an activation height):
- [ ] Use `EnumDef` to find future network upgrades in `Arbitrary for LedgerState`
  - and `Default for LedgerState` and `LedgerStateOverride` if we haven't removed them in #2059
- [ ] Replace hard-coded instances of `Canopy`, `NU5`, and future network upgrades with a "latest network upgrade" function, as needed
  - [ ] Replace the `NU5` constant in `zebra-chain/src/transaction/tests/vectors.rs` with the latest network upgrade
  - [ ] Replace the list of network upgrades in the `Transaction::branch_id()` strategy with `EnumDef`, a "has branch id" filter, then a random choice

**Describe alternatives you've considered**

We could use `strum`, but we're going to have the `valuable` dependency when `tracing` hits 1.0 anyway
 https://docs.rs/strum/0.20.0/strum/

We could do nothing.

**Comment by dconnolly** [comment]
ooo this is handy

**Comment by teor2345** [comment]
This is not needed, the current code works.
