### ISSUE TITLE
Update Non-Finalized State for Transaction v5

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1982]
**Is your feature request related to a problem? Please describe.**

Transaction v5 introduces Orchard nullifiers, which we need to include in the non-finalized state. We also need to handle sapling nullifiers, transparent UTXOs, and transaction IDs for transaction v5.

**Describe the solution you'd like**

- [x] Add an `orchard_nullifiers` field to `non_finalized_state::Chain`
- [x] Implement `UpdateWith` for `Option<orchard::ShieldedData>`
- [x] Implement `UpdateWith` for `Transaction::V5`
  - handle orchard nullifiers, sapling nullifiers, transparent UTXOs, and transaction IDs
- [x] Write unit tests
  - re-enable the NU5 override in `impl Strategy for PreparedChain`
  - the current tests should cover the new nullifier code: https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/tests/prop.rs

It's hard to test this code using test vectors, because they need to be in a chain with valid previous block hashes.

**Describe alternatives you've considered**

These changes are required for NU5.

**Additional context**

Nullifier sets are validated in #958.

**Comment by oxarbitrage** [comment]
- [ ] Implement `UpdateWith` for `Transaction::V5`

    - handle orchard nullifiers, sapling nullifiers, transparent UTXOs, and transaction IDs
    - re-enable the NU5 override in `impl Strategy for PreparedChain`

This is not clear to me. 
1. There is no `UpdateWith` for `Transaction::V4`, `Transaction::V3` or any other version in https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/chain.rs (all `UpdateWith` of the project are located in that file).
2. I can't see any Nu5 override here https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/arbitrary.rs#L45-L67

**Comment by teor2345** [comment]
> * There is no `UpdateWith` for `Transaction::V4`, `Transaction::V3` or any other version in https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/chain.rs (all `UpdateWith` of the project are located in that file).

There are two `match transaction { V5 => unimplemented(), }` in the PreparedBlock UpdateWith implementation:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/chain.rs#L176
https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/chain.rs#L236

I'm not sure why we do transaction updates inside block updates. Transaction updates might be easier to understand as a separate implementation. We'd have two shorter functions, rather than one long one.

**Comment by teor2345** [comment]
> 2\. I can't see any Nu5 override here https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/arbitrary.rs#L45-L67

There is a network_upgrade_override here. It is currently disabled using None. You should replace it with NU5 after making these changes:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/arbitrary.rs#L54

**Comment by teor2345** [comment]
Blocked by #2050, which implements v5 transaction IDs

**Comment by teor2345** [comment]
> Blocked by #2050, which implements v5 transaction IDs

Thinking about this dependency again.

 We're not committing any v5 transaction IDs to state yet, so we can do these PRs in any order.

 (If we do accidentally commit v5 IDs to state because we're missing verification, we just need to update the state version and rebuild. But that shouldn't happen, because the transaction validation code is marked unimplemented!)

**Comment by mpguerra** [comment]
I see all checkbox items above are ticked, what else is outstanding here?

**Comment by teor2345** [comment]
> I see all checkbox items above are ticked, what else is outstanding here?

It's all done, we should have said `Closes #1982` on PR #2185
