### ISSUE TITLE
Store Orchard nullifiers in the finalized state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#1983]
**Is your feature request related to a problem? Please describe.**

Transaction v5 introduces Orchard nullifiers, which we need to store in the finalized state.

**Describe the solution you'd like**

- [x] Add `orchard_nullifiers` to the State RFC RocksDB column families
  - https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures
- [x] Store `orchard_nullifiers` in `commit_finalized_direct`
- [x] Implement `IntoDisk` for `orchard::Nullifier`
- [x] Update the disk state version to force a state rebuild
- [ ] Rebuild the cached state for the integration CI tests

**Describe alternatives you've considered**

These changes are required for NU5.

**Additional context**

Nullifier sets are validated in #958.

**Comment by oxarbitrage** [comment]
This is blocked by https://github.com/ZcashFoundation/zebra/pull/2116

**Comment by oxarbitrage** [comment]
I made a PR for this at https://github.com/ZcashFoundation/zebra/pull/2185, i am unsure on how to do:

- [ ] Rebuild the cached state for the integration CI tests

**Comment by teor2345** [comment]
> I made a PR for this at #2185, i am unsure on how to do:
> 
> * [ ]  Rebuild the cached state for the integration CI tests

@dconnolly can show you how to do this on the Zebra test cloud.
