### ISSUE TITLE
Decide on a re-export policy for zebra-chain

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#201]
In #199 I introduced an inconsistency; `zebra-chain` reëxports `redjubjub` but not `ed25519-zebra`.  This is a pretty minor issue (just where stuff should go in the tree and how) but it would be good to have a consistent answer to the question of "when should zebra-chain reëxport dependencies".  

One possible answer would be to do it only for crates developed by the ZF that are supposed to be part of `zebra-chain`, but are actually separate crates in order to allow reuse by `zcashd` or `librustzcash`. This would include both `redjubjub` and `ed25519-zebra` as well as a standalone crate for note encryption (#181).

Another answer would be to reëxport any crate or type which appears in public API for `zebra-chain`.

**Comment by dconnolly** [comment]
We're going to leave this open for a little while longer to see our dependencies and crates shake out.

**Comment by dconnolly** [comment]
"If it's part of your api, you should export it." So we need to export ed25519-zebra. #405
