### ISSUE TITLE
`fake_v5_round_trip` test fails on blocks but not in transactions

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2023]
In https://github.com/ZcashFoundation/zebra/pull/2020 we added support for sapling shielded data in V5 transactions and we added a good amount of test coverage for the new feature.

One of the tests is failing not working as we expect, the following piece of code can be found in `zebra-chain/src/transaction/tests/vectors.rs` where tracing was added to debug the issue.

```rust
        let fake_block2 = match fake_bytes.zcash_deserialize_into::<Block>() {
            Ok(fake_block2) => fake_block2,
            Err(err) => {
                // TODO: work out why transaction parsing succeeds,
                //       but block parsing doesn't
                tracing::info!(
                    ?err,
                    ?original_block,
                    ?fake_block,
                    hex_original_bytes = ?hex::encode(&original_bytes),
                    hex_fake_bytes = ?hex::encode(&fake_bytes),
                    original_bytes_len = %original_bytes.len(),
                    fake_bytes_len = %fake_bytes.len(),
                    %MAX_BLOCK_BYTES,
                    "unexpected structurally invalid block during deserialization"
                );

                continue;
            }
        };
```

This ticket is to research the problem and fix it but it is blocked by https://github.com/ZcashFoundation/zebra/pull/2021 that we want to try first for a possible fix.

**Comment by teor2345** [comment]
We might also want to create some hard-coded test vectors to check our implementation, see #2047.

That way we have some fixed data to test against when we're trying to fix these tests.
