### ISSUE TITLE
Orchard: derive OutgoingCipherKey ( Sapling and Orchard)

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2041]
Stub: 

```
//     From<(
//         OutgoingViewingKey,
//         ValueCommitment,
//         NoteCommitment,
//         EphemeralKey,
//     )> for OutgoingCipherKey
// {
//     type Error = &'static str;

//     fn from((): ()) -> Result<Self, Self::Error> {
//         Self(prf_ock())
//     }
// }
```

**Comment by mpguerra** [comment]
iiuc this is only for sending notes and therefore will only be relevant when we're implementing wallet support.

I'm removing from the "NU5 Tracking: The Spec"/#1856 Epic until I hear otherwise

**Comment by dconnolly** [comment]
https://github.com/ZcashFoundation/zebra/issues/2362#issuecomment-942745340

**Comment by dconnolly** [comment]
Maybe a dupe of https://github.com/ZcashFoundation/zebra/issues/2362

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
