### ISSUE TITLE
zebra-chain: Port array-wrapper types to const generics

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2042]
**Is your feature request related to a problem? Please describe.**
We created several types that wrap arrays of bytes that are longer than 32, such as the Groth16Proof and Halo2Proof types. Since they are longer, Rust did not automatically derive several common traits for them, so we had to do that manually. Now that [const generics have been stablized](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp), we can clean up some of this code. 

**Describe the solution you'd like**
Define the types in zebra-chain that wrap arrays of bytes longer than 32 as wrapping arrays with lengths defined by a const. This will allow us to `#[derive()]` common traits on the wrapper type that we could not before, and get rid of the directly implemented traits, like `Copy`, `Clone`, etc.

**Describe alternatives you've considered**
Leave the impls as they are.

**Additional context**
I _think_ this should just work? But I haven't tested it.

**Comment by teor2345** [comment]
PR #2021 already uses const generics for some of the `AtLeastOne` `From` impls. So this PR doesn't change the rust version requirement.

**Comment by teor2345** [comment]
This ticket might be obsoleted by #2331.

**Comment by teor2345** [comment]
Some of these macro-based impls were removed as part of #4004.

**Comment by teor2345** [comment]
Let's do this when we actually change those types.
