### ISSUE TITLE
Replace redpallas stub in zebra-chain with full implementation

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2044]
**Is your feature request related to a problem? Please describe.**
To suffice types in the sapling->orchard port in zebra-chain, we created [`redpallas`](https://github.com/ZcashFoundation/zebra/blob/b8fab0464695bc7ffd63f947d2a72345447c9f99/zebra-chain/src/primitives/redpallas.rs) types but they are functionally incomplete. They need to be functional to verify SpendAuth and Binding signatures for NU5. 

**Describe the solution you'd like**
@str4d has  implemented [`reddsa` as a fork of `redjubjub`](https://github.com/str4d/redjubjub/tree/orchard) to abstract the common types and traits into a dependency for the [`redpallas` types in the `orchard` crate](https://github.com/zcash/orchard/blob/4b05c20a2ddac0eee9fbf9153cb081442124aec4/src/primitives/redpallas.rs).  The reddsa orchard branch there defines the Orchard basepoints, which is not my favorite.

Should the `redjubjub` crate turn into something a more shared `reddsa`, that includes the `redjubjub` and `reddsa`? With FROST, it may be annoying to have 3 crates to juggle: `reddsa` as a dependency, `redjubjub`, `redpallas`, with boilerplate across them. 

Or should we just duplicate where necessary?

**Comment by daira** [comment]
RedDSA was designed to operate over a generic represented group. To my mind, it would be very unfortunate if we ended up duplicating effort. A small amount of boilerplate might be ok, but I think it's preferable to merge implementations as far as possible.

**Comment by str4d** [comment]
> The reddsa orchard branch there defines the Orchard basepoints, which is not my favorite.

That was the simplest path forward that made the smallest change to the existing `redjubjub` code (to make it easy for you to review). I'd be happy with a further refactor that enabled `reddsa` to be completely generic; I just don't know whether that is compatible with the strict typing that `redjubjub` has. Given that I had to use sealed traits in `redpallas` anyway though, I think it's possible to remove them from `reddsa`, but I won't commit to doing that work unless it will actually be used by Zebra.
