### ISSUE TITLE
ZIP-244: Implement transaction authorization hashes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2048]
Implement (but not validate) ZIP-244 transaction authorization hashes.

### Specifications

- clarify the auth data hash tree construction: https://github.com/zcash/zips/pull/520

## Motivation

ZIP-244 creates non-malleable transaction identifiers that commit to all transaction data except for attestations to transaction validity. (That is, signatures and proofs.)

ZIP-244 also adds a transaction authorization hash, which is hash-chained to the block commitment (#1567) and placed in the block commitment fields.

**Describe the solution you'd like**

We should implement or integrate this new transaction digest algorithm in Zebra as per:
* https://zips.z.cash/zip-0244
* https://zips.z.cash/zip-0225#modifications-to-zip-244

This will include:

Update the `block::Commitment` for NU5:
- [ ] Add the transaction authorization hash to the block header commitment field (Zebra-specific)
  - depends on #1567

Transaction authorization hashes
- [ ] implement transaction authorization hashes using librustzcash

**Alternative Implementations**

The ECC have implemented a version of this in Rust in the [librustzcash library](https://github.com/zcash/librustzcash/pull/319/files), we should be able to either port some of that code or learn from that code to implement the Zebra version.

## Follow up

Validation is done in https://github.com/zcashfoundation/zebra/issues/2562

**Comment by mpguerra** [comment]
Moved to Sprint 13

**Comment by conradoplg** [comment]
I've updated the description:

- Adding the hash to the block was moved to https://github.com/ZcashFoundation/zebra/issues/2336
- I changed the text to require only the hash computation and not validation

With this I think we can remove this blocking on #2562 and close this (implemented in https://github.com/ZcashFoundation/zebra/pull/2547). @mpguerra I'll leave this for you to confirm
