### ISSUE TITLE
Import Poseidon hash into Zebra

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2064]
As defined in NU5 spec: 
https://zips.z.cash/protocol/nu5.pdf#poseidonhash

For reference, one implementation is over in the `orchard` crate: https://github.com/zcash/orchard/blob/main/src/primitives/poseidon.rs

### Scheduling

This is only required for the wallet work, because it's used to create nullifiers.

**Comment by teor2345** [comment]
I moved this task to sprint 13 because the anchors are a higher priority - they are blocking the history chain contextual validation and testing.

**Comment by teor2345** [comment]
We decided to favour importing cryptography over re-implementing it, at least until after NU5 activation.

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
