### ISSUE TITLE
Import and test against Sinsemilla test vectors from zcash-hackworks

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2079]
**Is your feature request related to a problem? Please describe.**
We've added Sinsemilla-based commitments for Orchard, and want to make sure they are compatible with the code being used in zcashd and the https://github.com/zcash-hackworks/zcash-test-vectors/ implementation.

**Describe the solution you'd like**
Render out the test vectors in https://github.com/zcash-hackworks/zcash-test-vectors/pull/17 as Rust-compatible, import into zebra-chain, and ensure our old/new tests pass against them.

**Comment by mpguerra** [comment]
I see #2384 has merged. Are there any other test vectors that we need to import here or can we close this one?
