### ISSUE TITLE
replace`redpallas` module with `reddsa` crate

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2080]
## Motivation

There is a stub of `redpallas` in `zebra-chain::primitives` for now. There is a proposal to make `redjubjub` generic over traits to make it `reddsa`, that str4d made work over in the `orchard` crate. 

str4d published a minimal `reddsa` crate in #3070.

## Tasks

- Use the ECC's `redpallas` crate.
- Replace our stub in `zebra-chain` with `redpallas`.
- Deduplicate `redjubjub` and `redpallas`

### Scheduling

This is only required for the wallet work.

We might want to schedule this work around splitting FROST out of `redjubjub`.

**Comment by mpguerra** [comment]
Do we need to do this for NU5 activation? I'm confused as to how this fits in with #2044/#2099 and whether this is follow up/optimisation work

**Comment by teor2345** [comment]
> Do we need to do this for NU5 activation? I'm confused as to how this fits in with #2044/#2099 and whether this is follow up/optimisation work

We need to decide if we want to use this approach in Zebra. Let's add it to the decisions for the next meeting?

If we decided to use it, str4d will do most of the work here. Then we can integrate the resulting crates.

**Comment by mpguerra** [comment]
We never made a decision on this one and I'm still not clear if we need this for NU5 testnet activation.

If we do need to do this, we should take whichever approach is less work for now, even if we need to do it again some other way in future.

**Comment by dconnolly** [comment]
This is not strictly required for NU5 activation, we can save this for post-activation cleanup.

We've basically done the alternative option described in this ticket.
