### ISSUE TITLE
Remove funty pinning when halo2, bitvec update

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2082]
When https://github.com/myrrlyn/funty/issues/3 is resolved, and our direct dependencies have also updated (including `bitvec`, `halo2`), we should remove the pinning in `zebra-chain`

![image](https://user-images.githubusercontent.com/552961/116492932-8f0ea200-a86b-11eb-8daa-1f3741e3d08e.png)

**Comment by teor2345** [comment]
We've either done this, or we'll do it when they upgrade.
