### ISSUE TITLE
Add a clippy pass to CI and decide on lints to use.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#209]
Doing this for the first time will probably require making a bunch of changes to the source to make it satisfy the lints.

As indicated by the name, `clippy` is meant to err on the side of annoyance, so not all lints will be appropriate at all times.  So we need to decide as a project how we want to handle lints. One option is to allow clippy lints to fail (i.e., don't block CI on them), and another is to add annotations throughout the source to disable them where they occur.  I don't have a super strong preference, but my initial preference is to do the latter option, making clippy failures a CI failure but allowing disabling specific lints in-place with annotations.

**Comment by dconnolly** [comment]
https://github.com/actions-rs/clippy-check exists as an option
