### ISSUE TITLE
Implement Block Header FinalSaplingRoot

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2092]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

- [ ] Implement the `block::Commitment::FinalSaplingRoot` variant based on the spec
  - it's the final Sapling root hash in the block, which we're already calculating, so we might as well verify it
  - blocked on #1287 - Sapling and Orchard root calculation

The `Commitment` enum variants have already been implemented.

**Additional context**

This historical validation rule was used in the Sapling and Blossom network upgrades. But it is replaced by the `ChainHistoryRoot` in Heartwood. Since Zebra checkpoints on Canopy, we do not need to implement this rule.

But it might be useful while we're testing ZIP-221 (#1567) or ZIP-244 (#2048).

**Comment by mpguerra** [comment]
Both  ZIP-221 (#1567) or ZIP-244 (#2048) are already implemented. If we want to do this again at some point in the future we should re-open this issue.
