### ISSUE TITLE
Implement Orchard binding verification key derivation

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2102]
Similar to `ShieldedData` for Sapling, we need to derive and validate the Orchard binding verification key.

**Comment by teor2345** [comment]
I think this might be a duplicate of #1979. We have an orchard::ShieldedData and orchard::AuthorizedAction as part of the transaction v5 RFC design, they just haven't been implemented yet.

**Comment by teor2345** [comment]
> I think this might be a duplicate of #1979. We have an orchard::ShieldedData and orchard::AuthorizedAction as part of the transaction v5 RFC design, they just haven't been implemented yet.

Actually I think it might be the description that's the issue here - we don't just need to store the data, we also need to process it.

@dconnolly can you update the description to talk about binding signature verification and AuthorizedAction?
