### ISSUE TITLE
Implement a `Halo2Verifier` async service

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2104]
Similar to our other async `tower`-based verifier services, such as the [`Groth16Verifier`](https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/primitives/groth16.rs).  We should depend on the same version of the `halo2` crate as we do in `zebra-chain`. 

While we don't have batch math available yet for Halo2, the async service will decouple the verification requests from the fullfillment, allowing us to swap out the original single-verification implementation here with a more efficient batch verification implementation that is oblivious at the API level.

**Testing**:

Generate test vectors for halo2 proofs from zcash-hackworks; if they give trouble in our full validation pipeline, punt this full  integration until we get the first NU5 block with an Action in it for testnet.

**Additional context**
#1951

**Comment by teor2345** [comment]
Moving this out of NU5 because it's not strictly required for activation

**Comment by dconnolly** [comment]
It's not? Otherwise halo2 verification will block everything else in the transaction verifier

**Comment by teor2345** [comment]
> It's not? Otherwise halo2 verification will block everything else in the transaction verifier

We could just spawn a non-blocking tokio task, and await its completion.

**Comment by teor2345** [comment]
@dconnolly and I discussed this issue, and we decided that we should continue to use the same architecture as the other verifiers.

(Otherwise, we risk breaking other fragile async code.)

**Comment by daira** [comment]
> While we don't have batch math available yet for Halo2 [...]

https://github.com/zcash/halo2/issues/282 ("Document how to do simple (not aggregated) batch verification for Halo 2")

**Comment by mpguerra** [comment]
blocked on circuit from ECC
