### ISSUE TITLE
Validate Transaction::V5 Halo2 proofs

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2105]
**Is your feature request related to a problem? Please describe.**
As part of [consensus validation](https://zips.z.cash/protocol/nu5.pdf#txnencodingandconsensus), we must validate the Halo2 proofs of the Action Descriptions in Transaction::V5.

**Describe the solution you'd like**
When the async `Halo2Verifier` service is available, make async requests to validate the `proofsOrchard` aggregated proof(s)(?) for the Actions of the transaction. 

**Testing**:

Generate test vectors for halo2 proofs from zcash-hackworks; if they give trouble in our full validation pipeline, punt this full  integration until we get the first NU5 block with an Action in it for testnet.

**Additional context**
Depends on #2104

**Comment by mpguerra** [comment]
#1912 is a potential duplicate?

**Comment by dconnolly** [comment]
Yes this and #1912 describe the same work, this one has more detail

**Comment by teor2345** [comment]
I moved this task to sprint 13 because the anchors are a higher priority - they are blocking the history chain contextual validation and testing.
