### ISSUE TITLE
Fix protocol mismatch bugs between Zebra and `zcashd`

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2109]
**Is your feature request related to a problem? Please describe.**

Zebra and `zcashd` have different network protocol implementations. Sometimes, these differences cause bugs or security issues.

**Describe the solution you'd like**

- [ ] document `zcashd`'s network behaviour and the constraints it places on peers (`zcashd` team)
- [ ] identify issues with Zebra's current implementation
- [ ] make tickets for those issues and prioritise them 

**Additional context**

`zcashd`'s network protocol implementation is derived from Bitcoin, but it is not currently well documented or specified.

**Comment by mpguerra** [comment]
We should open individual tickets as we find specific bugs
