### ISSUE TITLE
Add metrics integration using the `metrics` crate.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#211]
This should initially be scoped to the `zebra-network` crate, because that's where we have the most metrics-able stuff to measure, and because that has relatively fewer in-flight changes right now.

As starting goals, we should:

- [ ] add infrastructure for metrics collection
- [ ] add appropriate metrics to the networking code (this can be reworked later, just some initial metrics)
- [ ] export this in a way that's prometheus-compatible

Stretch goals:

- [ ] add some kind of prometheus thing to a dockerfile?  I think this is not necessary to start.

**Comment by dconnolly** [comment]
Prometheus: https://prometheus.io

**Comment by hdevalence** [comment]
My experience with #240 was that it was pretty hard to tell what's going on without metrics integration, so I think that we should prioritize this before going further on networking stuff.

**Comment by hdevalence** [comment]
Notes from discussion with @dconnolly:

* We should have a config flag that enables metrics collection, off by default.  When enabled, it's the responsibility of the node operator to firewall or otherwise control access to the metrics endpoint.

* We should have a Dockerfile or something that starts a local prometheus server/collector + grafana instance, for use in development.
