### ISSUE TITLE
ZIP-221: Integrate Tree Node implementation from librustzcash

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2133]
**Is your feature request related to a problem? Please describe.**

In order to save us some time in implementing ZIP-221 in Zebra, we will integrate the Tree Node implementation from librustzcash.

**Describe the solution you'd like**

We will need to add the following enum variants:
    a. `Internal` enum variant
    b. `Leaf` enum variant

We will also need: 
- Consensus Branch Id (from block height and network)
- ~20 chain history data items as specified in ZIP-221
- we'll need both a Canopy version and an NU5 version of this code as NU5 adds more fields

**Additional context**

See https://github.com/zcashfoundation/zebra/issues/2091#issuecomment-832311598 for details

**Comment by teor2345** [comment]
This ticket is a duplicate of #2132.

We are re-using `zcash_history` from `librustzcash`, so it will handle internal details like tree nodes and fields.
