### ISSUE TITLE
Use Transaction::{V1, V2, V3} proptest strategies in finalized state tests

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2166]
**Is your feature request related to a problem? Please describe.**
In #2159, we stopped generating V1-V3 transactions in proptests for non-finalized state. We still have these proptest strategies.

**Describe the solution you'd like**
Use these strategies in proptests for finalized state, so that we exercise handling V1-V3 transactions.

**Describe alternatives you've considered**
Do not handle these cases, remove these test strategies.

**Comment by teor2345** [comment]
We have good coverage already.
