### ISSUE TITLE
Fix orchard spend auth signature regressions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2170]
**Is your feature request related to a problem? Please describe.**

#2168 contains some proptest regressions that cause the `redpallas::prop::tweak_signature` test's spend auth signature check to fail.

**Describe the solution you'd like**

- [ ] Fix these regressions
- [ ] Re-enable the tests by reverting #2169

**Describe alternatives you've considered**

Delete the tests if they are unreliable.

**Related issues**

Regression PR #2168 
Temporarily disable test PR #2169
Underlying fix ticket #2170

**Comment by dconnolly** [comment]
This is interesting, I need to check the tweaks, these failures are not related to the binding signature verification key computation failures.
