### ISSUE TITLE
Clearly identify 32-bit and 64-bit times in serialization and proptests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2171]
**Scheduling**

This risk is acceptable for the stable release, but we need to fix it before we support lightwalletd.

**Is your feature request related to a problem? Please describe.**

Zcash has two serialized time fields: 32-bit seconds, and 64-bit seconds. Zebra also keeps internal 64-bit times with additional 32-bit nanosecond precision.

In general, it's hard to identify, convert, serialize and proptest these different time types correctly.

This is a follow-up to #1849.

**Describe the solution you'd like**

Make wrapper types for serialized times:
  - [x] `DateTime32` (#2210)
  - [ ] `DateTime64`

Tasks for each wrapper type:
- [ ] make arbitrary impls
  - the arbitrary impls should replace the existing `datetime_full` and `datetime_u32` proptest strategies
  - we can use `datetime_full` for `DateTime64` by removing nanoseconds
- [ ] make serialization impls

Replace `chrono::DateTime<Utc>` with the appropriate types:
- [ ] 32-bit serialized: `DateTime32` #2211
- [ ] 64-bit serialized: `DateTime64`
- [ ] internal monotonic: `std::time::Instant`
- [ ] Remove unused dependencies on `chrono`

**Describe alternatives you've considered**

It would be nice if Zcash just used 64-bit times throughout the protocol.

**Comment by dconnolly** [comment]
> It would be nice if Zcash just used 64-bit times throughout the protocol.

💕

**Comment by teor2345** [comment]
I did `DateTime32` in #2210 so we could do #2178

**Comment by teor2345** [comment]
This is a useful validation improvement, but it's not needed right now.
