### ISSUE TITLE
Replace compactsize serialization with array serialization

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2176]
**Is your feature request related to a problem? Please describe.**

In Zebra, we manually serialize and deserialize `CompactSize`s, then separately serialize the related items.

But this is error-prone.

**Describe the solution you'd like**

Instead, we should replace:
* `read_compactsize` with `zcash_serialize(Vec)` or `zcash_serialize_bytes`
* `write_compactsize` with `zcash_deserialize(Vec)` or `Vec::zcash_deserialize_into`

These changes should only be made if the compact size is actually a length prefix.

**Describe alternatives you've considered**

We could do nothing.

**Comment by mpguerra** [comment]
We've done this already as part of address v2 work
