### ISSUE TITLE
Update user and dev instructions in the Zebra Book to deduplicate

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2191]
**Is your feature request related to a problem? Please describe.**
In the Zebra Book, the user and dev instructions duplicate each other and may get out of sync.

**Describe the solution you'd like**
Put the user/dev instructions that are common in one location and link them into both places in the Zebra Book. 

**Additional context**
This got started in https://github.com/ZcashFoundation/zebra/pull/1497

**Comment by teor2345** [comment]
We'll do this when we change the docs.
