### ISSUE TITLE
Implement `EphemeralPrivateKey`'s for Orchard, Sapling, Sprout

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2192]
**Is your feature request related to a problem? Please describe.**
To send money, we need an `EphemeralPrivateKey` to go with our `EphemeralPublicKey`s that already exist in `zebra-chain`.

**Describe the solution you'd like**
Implement the newtype wrappers around `pallas::Scalar`, `jubjub::Scalar`, and I think `x25519-dalek::SecretKey` for Orchard, Sapling, and Sprout resepectively.

**Describe alternatives you've considered**
Use those types directly, which elides the specific use and capabilities of these keys vs the other uses of those generic types other places in our codebase.

**Additional context**
This must be done to complete https://github.com/ZcashFoundation/zebra/issues/269

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope.
