### ISSUE TITLE
Redesign zebra-network so it's less sensitive to message order, timing, buffer size

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2193]
**Is your feature request related to a problem? Please describe.**

While developing #2160, we discovered that Zebra's network integration tests fail on some platforms when:
* initialization order or timing changes slightly
* message order or timing changes slightly
* buffer sizes change

This makes it hard to make network changes, and write useful tests.

**Describe the solution you'd like**

The issue could be in the code or in the tests:
- make the networking code more robust to timing and order changes
- make the tests more robust to different environments
- move to isolated network integration tests
- add more fine-grained network component tests

**Describe alternatives you've considered**

We could do nothing, but we'll spend a lot of time debugging occasional network failures.

**Comment by dconnolly** [comment]
@teor2345 so it sounds like the scope of work for this issue is 1: investigation, and 2: design informed by the results of that investigation?

**Comment by teor2345** [comment]
We should probably use `tokio-console` to do this work.

**Comment by mpguerra** [comment]
Let's open specific issues as we find specific bugs
