### ISSUE TITLE
Break out Block* components into submodules

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#220]
> Arrange the submodules of block to match transaction, splitting out into submodules, e.g., header, serialize, tests, etc, and then re-exporting components from block?

https://github.com/ZcashFoundation/zebra/pull/212#discussion_r374342673

**Comment by hdevalence** [comment]
It might be good to combine this reorg with some reorg for the `transaction` module, too.  Some things I noticed when working on #158:

- [x] there are a few `ZcashSerialize` and `ZcashDeserialize` impls for transaction components that live outside of the `serialize.rs` file, so not all the serialization code is in one place.  Instead I think it would be cleaner if the `transaction/` subtree had no `ZcashSerialize`/`ZcashDeserialize` outside of `serialize.rs`

- [ ] some of the `Arbitrary` impls for transaction components are in `transaction/tests.rs`, while others are inline but `cfg`-gated.  I think it would be cleaner if all of the `Arbitrary` impls were in some subtree of `transaction::tests`, either in `tests.rs` or in `tests/arbitrary.rs` or something.

WDYT?

**Comment by dconnolly** [comment]
> It might be good to combine this reorg with some reorg for the `transaction` module, too. Some things I noticed when working on #158:
> 
> * [x]  there are a few `ZcashSerialize` and `ZcashDeserialize` impls for transaction components that live outside of the `serialize.rs` file, so not all the serialization code is in one place.  Instead I think it would be cleaner if the `transaction/` subtree had no `ZcashSerialize`/`ZcashDeserialize` outside of `serialize.rs`
> * [ ]  some of the `Arbitrary` impls for transaction components are in `transaction/tests.rs`, while others are inline but `cfg`-gated.  I think it would be cleaner if all of the `Arbitrary` impls were in some subtree of `transaction::tests`, either in `tests.rs` or in `tests/arbitrary.rs` or something.
> 
> WDYT?

I disagree with consolidating all the `Arbitrary` impls away from the structs they are associated with, keeping test code far away from the code it tests tends to encourage drift and maintenance issues.
