### ISSUE TITLE
Accept high version numbers in non-overwinter transactions

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2207]
**Version**

`zebra-chain v1.0.0-alpha.8` commit 227757ae

**Platform**

`Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

Zebra does not accept high version numbers in pre-overwinter transactions.

I tried this:

Deserialize transaction from https://github.com/zcash/zcash/blob/master/src/test/data/sighash.json (e.g. the first one)

I expected to see this happen: the transaction to be successfully deserialized

Instead, this happened: `parse error: bad tx header`

See section 7.1 of the spec:

> Version constraints apply to the effectiveVersion, which is equal to min(2, version) when fOverwintered = 0 and
> to version otherwise.

**Solution**

- [ ] Add a u32 version field to Transaction::V2
- [ ] Serialize and deserialize it
- [ ] Add round-trip serialization tests with the test vectors that are currently failing

**Commands**

N/A

**Logs**

N/A

**Comment by teor2345** [comment]
In practice this issue never actually happened on the Mainnet or Testnet chain, so it's a low-priority fix. (Unless it's blocking other necessary work.)

**Comment by conradoplg** [comment]
We don't need this since we checkpoint on Canopy and no existing transactions has high version numbers.
