### ISSUE TITLE
Rate-limit genesis block download attempts, Credit: Equilibrium

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2213]
**Is your feature request related to a problem? Please describe.**

If nodes reply immediately with NotFound during genesis block downloads, Zebra retries immediately:
https://github.com/eqlabs/ziggurat/blob/zebra-getdata/examples/getdata.rs

This bug could be a significant issue if:
- two (or more) Zebra nodes without the genesis block are launched just pointing at each other
- a testnet node is misconfigured with mainnet peers *and* mainnet magic numbers, or the other way around (this is unlikely in practice)
- a Zebra node is seeded with non-Zcash peers, with different genesis blocks, but the same magic numbers (for example, a protocol fork)

**Describe the solution you'd like**

- [x] We should tokio::time::sleep for a short time between each genesis block attempt. This gives the crawler  time to find better peers.
- [x] Write a test that runs `0..4` genesis downloads
  - the first request should run immediately, but we can't really test for that due to VM delays
  - each subsequent request should run at least 5 seconds after the last one
  - the whole test should complete within 20 seconds (use a timeout and select)

Let's pick a limit around 5 seconds, because:
- the handshake timeout is 4 seconds (lower bound)
- the request timeout is 20 seconds (upper bound)
- other timeouts are 6 (tips) and 15 (block download) seconds
- the genesis block should be the only block that's downloading

These messages are sent by the syncer:

https://github.com/ZcashFoundation/zebra/blob/f77441d49cff09029c0191359f3223eaf6741659/zebrad/src/components/sync.rs#L609-L621

**Describe alternatives you've considered**

We could rate-limit identical messages to the same peer (#2153)

These alternatives would slow down syncing:
- rate-limit all messages to the peer set (#2153)
- rate limit all messages to individual peers (#2153)

**Comment by mpguerra** [comment]
I see #2255 is closed, is there anything else to be done here?

**Comment by oxarbitrage** [comment]
Yea, this should be closed, there are follow up tickets for remaining work.
