### ISSUE TITLE
Require minimal height encodings during deserialization

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2226]
## Motivation

Zebra accepts non-minimal height encodings when deserializing, but the spec requires minimal encodings.

The serialization should be correct. But the deserialization accepts some encodings that are longer than they need to be. So they are actually invalid.

### Consensus Rules

Here's the relevant consensus rule:

> A coinbase transaction for a block at block height greater than 0 MUST have a script that, as its first item, encodes the block height height as follows.
> 
> For height in the range {1 .. 16}, the encoding is a single byte of value 0x50 + height.
> 
> Otherwise, let heightBytes be the signed little-endian representation of height, using the minimum nonzero number of bytes such that the most significant byte is < 0x80. The length of heightBytes MUST be in the range {1 .. 5}. Then the encoding is the length of heightBytes encoded as one byte, followed by heightBytes itself.
> 
> This matches the encoding used by Bitcoin in the implementation of [BIP-34] (but the description here is to be considered normative).

https://zips.z.cash/protocol/protocol.pdf#txnconsensus

### Related Consensus Rules

Here is a related consensus rule that limits the number of bytes used by a height:

> Each block in a block chain has a block height . The block height of the genesis block is 0, and the block height of each subsequent block in the block chain increments by 1. Implementations MUST support block heights up to and including 2^31 − 1.
> 
> As of NU5, there is a consensus rule that all coinbase transactions MUST have the nExpiryHeight field set to the block height , and this limits the maximum block height to 2^32 − 1, absent future consensus changes.

https://zips.z.cash/protocol/protocol.pdf#blockchain

## Existing Code

https://github.com/ZcashFoundation/zebra/blob/24bf952e982bde28eb384b211659159d46150f63/zebra-chain/src/transparent/serialize.rs#L44-L53

## Tests

We don't have any proptests for height bytes round-trips (bytes to `Height` to bytes).

There are two different encodings we need to test:
- [ ] single byte opcodes
- [ ] 1 length byte followed by 1-5 bytes of height data

We already have height deserialization tests for every mainnet and testnet block test vector.

## Context

Comment by @daira in https://github.com/ZcashFoundation/zebra/issues/2225#issuecomment-851049413

Support the large block heights required by the spec #1113 - out of scope for NU5

**Comment by teor2345** [comment]
Oops, this was meant to go in zcash/zips.

**Comment by teor2345** [comment]
This is a consensus rule, so I've marked it as a medium priority

**Comment by daira** [comment]
> The length of heightBytes MUST be in the range {1 .. 4}.

It's { 1 .. 5 } in the current spec (which allows block heights ≥ 2<sup>31</sup>).

**Comment by teor2345** [comment]
> > The length of heightBytes MUST be in the range {1 .. 4}.
> 
> It's { 1 .. 5 } in the current spec (which allows block heights ≥ 231).

Thanks, I've updated the ticket.

**Comment by teor2345** [comment]
`parse_coinbase_height` allows multiple encodings of the same block height. But only the shortest encoding is allowed by the spec.

So it currently allows:
- `0x51` - the only valid height 1 encoding in the consensus rules
- `0x0101` - parsed as height 1, should be an error
- `0x020100` - parsed as height 1, should be an error
- `0x03010000` - parsed as height 1, should be an error
- `0x0401000000` - parsed as height 1, should be an error

**Comment by teor2345** [comment]
I just realised the height is little-endian, I've fixed the examples above.

Here is an example that don't use the special one-byte script opcodes:

`parse_coinbase_height` currently allows:
- `0x0111` - the only valid height 17 encoding in the consensus rules
- `0x021100` - parsed as height 17, should be an error
- `0x03110000` - parsed as height 17, should be an error
- `0x0411000000` - parsed as height 17, should be an error
