### ISSUE TITLE
Parse ZIP-239 Messages: Relay of Version 5 Transactions Outside Blocks

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2233]
## Motivation

ZIP-239 describes a new inv type (`MSG_WTX`), to be applied from the NU5 network upgrade onward. This message type is to be used for both `inv` messages and `getdata` requests for relaying mempool transactions.

Zebra needs to either:
- parse this new format, or
- stop closing connections on unrecognised message formats #2107

Parsing the new format is a lower risk change.

This change needs to be implemented before testnet activation, or Zebra will disconnect from all its peers and stop working.

### Specifications

> A transaction has a transaction ID that can be used to refer to it. ... Version 5 transactions also have a wtxid , which is used instead of the transaction ID when gossiping transactions in the peer-to-peer protocol

https://zips.z.cash/protocol/protocol.pdf#transactions

> The transaction ID of a version 4 or earlier transaction is the SHA-256d hash of the transaction encoding in the
pre-v5 format described above.
> 
> The transaction ID of a version 5 transaction is as defined in [ZIP-244]. A v5 transaction also has a wtxid (used for example in the peer-to-peer protocol) as defined in [ZIP-239].

https://zips.z.cash/protocol/protocol.pdf#txnidentifiers

> A new inv type MSG_WTX (0x00000005) is added, for use in both inv messages and getdata requests, indicating that the hash being referenced is the wtxid (i.e. the 64-byte value txid || auth_digest). This inv type MUST be used when announcing v5 transactions. The txid and auth_digest are as defined in 4.
> 
> An inv or getdata message MUST NOT use the MSG_WTX inv type for v4 or earlier transactions, or on peer connections that have not negotiated at least the peer protocol version specified in Deployment.
> 
> Note that MSG_WTX might also be used for future transaction versions after v5. Since such versions are not currently consensus-valid, this is left unspecified for now.
> 
> MSG_TX and MSG_WTX entries may be mixed in arbitrary order in an inv message or a getdata message. Since these entry types are of different lengths (36 bytes or 68 bytes respectively including the 4-byte type field), this implies that the size of the message is not determined by its initial count field, and has to be determined by parsing the whole message.

> it is possible for a node to receive an inv or getdata message with a MSG_WTX inv type, on a peer connection that has negotiated protocol version 170014 or later, before NU5 has activated. The node MUST handle this case in the same way that it would after NU5 activation when it has no v5 transactions to relay. Receiving a MSG_WTX inv type on a peer connection that has negotiated a protocol version before 170014, on the other hand, SHOULD be treated as a protocol error.

[ZIP-239](https://zips.z.cash/zip-0239#specification)

[Bitcoin equivalent](https://developer.bitcoin.org/reference/p2p_networking.html#inv)

## Solution

We should support the new `MSG_WTX` type in Zebra by:
- [ ] parsing `MSG_WTX` in `inv` and `getdata` messages
- [ ] converting these new `Message`s to internal `Request`s or `Response`s
- [x] ignoring these messages until Zebra has a mempool (#936)
  - Zebra currently ignores all mempool and loose transaction messages

### Testing

- [ ] Update `Arbitrary` for `inv` and `getdata` to include `MSG_WTX`
- [ ] Add or update the `inv` and `getdata` structure round-trip tests
- [x] Add a round-trip test for raw bytes, like `flags_roundtrip` in PR #2284
  - See https://github.com/ZcashFoundation/zebra/pull/2284/files#diff-61946f5da7fa4b4337dccfc09019d5e986e407c5a37bec426824ea5522699bc2R12
- [ ] Ask the `zcashd` team if they have any test vectors, and add tests for them

## Alternatives

Instead of making this change, we could stop closing connections on unrecognised message formats (#2107), but this risks bugs and errors in the logs. Parsing the new format is a lower risk change.

According to @str4d we could "use existing transaction broadcast messages with v5 transactions

But for v5 txs those have DoS risks (as the authorizing part of a transaction could potentially be malleated on the wire to make it invalid, causing full nodes to not request that txid from other nodes' inventories any more, even though the tx with valid authorizing data is still out there)"
https://discord.com/channels/676527656170160146/716086297210650634/849296485602033746

So if we decide to _NOT_ implement this then we should not support Txv5 in regular inv/getdata messages for security reasons.

**Comment by daira** [comment]
Btw I renamed `MSG_TXV5` to `MSG_WTX` in the draft. (That name makes sense now that we've defined "wtxid".)

**Comment by teor2345** [comment]
I cut down the scope of this ticket - it's now limited to parsing the new message variant in the network layer.

**Comment by daira** [comment]
[ZIP 239](https://zips.z.cash/zip-0239) has been published.

**Comment by teor2345** [comment]
This ticket needs to be implemented before testnet activation, or Zebra will disconnect from all its peers and stop working.

**Comment by teor2345** [comment]
ZIP 239 is in the NU5 ZIP, so I've updated the ticket to remove "if it is accepted".

**Comment by teor2345** [comment]
Closed by PR #2446, remaining work in tickets #2449 and #2451 in the mempool epic.
