### ISSUE TITLE
Box fields of Transaction, as appropriate

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#225]
Currently the `Transaction` enum is large, causing a clippy warning. I think that this is ultimately because the `JoinSplitData`/`ShieldedData` keep the first element out of the main vector, so replacing the `Option<T>` by `Option<Box<T>>` should work, but we should think it through first.

**Comment by dconnolly** [comment]
It doesn't seem like this is being thrown anymore on `Transaction` on main branch, closing.
