### ISSUE TITLE
Stop sending addresses of outdated peers to other peers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2261]
## Motivation

Currently, Zebra gossips all of its peer addresses to other peers, regardless of the last seen protocol version.

If we stop gossiping addresses of outdated peers, it will help network convergence.

### Specifications

Original specification: [ZIP 201: Network Peer Management for Overwinter](https://zips.z.cash/zip-0201#rejecting-pre-overwinter-connections)

Since this is a network protocol specification, Zebra is free to adopt any compatible design.

## Solution

Address Book:
- [ ] Track the most recent protocol version in `MetaAddr`, and update it every time we do a handshake

Inbound service:
- [ ] Use a watch channel from the state to get the best tip height (from #2262)
- [ ] Find the minimum acceptable network protocol version (from #2262)
- [ ] Stop sending addresses of outdated peers to other peers
  - but keep them in the address book until they expire normally (#1867 and #1865), so we can find them if they upgrade

Property testing:
- [ ] Generate some random `MetaAddr`s
- [ ] Put them in an `AddressBook`
- [ ] Create an inbound service using fake Zebra services
- [ ] Ask the inbound service for some peers
- [ ] Make sure that protocol versions are handled correctly

Manual Testing:
- [ ] Set the testnet activation height lower than specified, and check Zebra's behaviour
- [ ] Run and monitor Zebra nodes on testnet during activation
- [ ] TODO: _what other tests can we do here, without too much effort?_

### Alternatives

We don't have to make this change, but it's useful for the network.

What does `zcashd` do here?

**Comment by teor2345** [comment]
I've marked this ticket as optional - we should check if `zcashd` does this kind of check, so we know if it's necessary for Zebra.

**Comment by jvff** [comment]
We've decided to not do this, because we might not have the latest version of the peer's protocol version in the `MetaAddr` stored in the `AddressBook`.
