### ISSUE TITLE
Security: Stop panicking when the reserved bits of orchard::Flags are non-zero

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2263]
## Motivation

Zebra panics via `unwrap` when the reserved bits of `orchard::Flags` are non-zero.

Also, the consensus rules were updated to require that reserved bits of `orchard::Flags` are all zero.

### Specifications

"In a version 5 transaction, the reserved bits 2..7 of the flags Orchard field MUST be zero."
https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus

### Designs

The `orchard::Flags` design was implemented in PR #2116:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0010-v5-transaction.md#adding-orchard-flags

But the implementation had a security issue, because the design didn't cover parsing errors.

### API Reference

> pub fn from_bits(bits: u32) -> Option<Flags>
> Convert from underlying bit representation, unless that representation contains bits that do not correspond to a flag.

https://docs.rs/bitflags/1.2.1/bitflags/example_generated/struct.Flags.html#method.from_bits

## Solution

- [ ] Update the RFC to include the new consensus rule
- [ ] Return an error during deserialization when any reserved bits of `orchard::Flags` are non-zero
  - quote the consensus rule in the function docs and link to the spec
- [ ] Add a proptest that parses an arbitrary flag byte
  - when all reserved bits of `orchard::Flags` are zero, check that deserialization succeeds 
  - when any reserved bits of `orchard::Flags` are non-zero, check that deserialization fails with an error

**Comment by oxarbitrage** [comment]
I might be missing something but i think this check is enforced by the way we do the orchard flags in Zebra:

https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/orchard/shielded_data.rs#L141-L144

We can't create a `Flag` type from bits that are not 0 or 1, it will fail. Deserialization of `flagsOrchard` will also fail to parse as a `Flag` type if it is using bits from the reserved ones.

Please clarify. Thanks.

**Comment by teor2345** [comment]
> I might be missing something but i think this check is enforced by the way we do the orchard flags in Zebra:
> 
> https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/orchard/shielded_data.rs#L141-L144
> 
> We can't create a `Flag` type from bits that are not 0 or 1, it will fail. Deserialization of `flagsOrchard` will also fail to parse as a `Flag` type if it is using bits from the reserved ones.

Zebra currently panics via `unwrap` when reserved flags are non-zero:
https://github.com/ZcashFoundation/zebra/blob/fc0edb5c44730deecb486af4b16fb4b4aabaacc6/zebra-chain/src/orchard/shielded_data.rs#L158

> pub fn from_bits(bits: u32) -> Option<Flags>
> Convert from underlying bit representation, unless that representation contains bits that do not correspond to a flag.

https://docs.rs/bitflags/1.2.1/bitflags/example_generated/struct.Flags.html#method.from_bits

Panicking based on untrusted data is a security issue. So we want Zebra to return a serialization error instead.

I'm not sure how we missed this `unwrap` during code review. Maybe the original PR was too big for a detailed review?
(Unwraps in production code need explanations. A good way to provide an explanation is an `expect` or an error.)

I'll update the ticket.

**Comment by teor2345** [comment]
> I'm not sure how we missed this `unwrap` during code review. Maybe the original PR was too big for a detailed review?
> (Unwraps in production code need explanations. A good way to provide an explanation is an `expect` or an error.)

Also the design didn't cover parsing errors, so that's something we should watch out for in future designs.

**Comment by teor2345** [comment]
> > 
> 
> Also the design didn't cover parsing errors, so that's something we should watch out for in future designs.

Hmm also we're not parsing any random bytes in our proptests. So I think this is ultimately a testing gap, I opened #2282 so we remember to write those tests.
