### ISSUE TITLE
Tracking: Add tests using zcashd test vectors

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2266]
## Motivation

The zcashd repository has a [bunch of test vectors](https://github.com/zcash/zcash/tree/master/src/test/data).

We could add tests using them to increase the confidence in zebra correctness and compatibility.

### Issues

- [x] #1107
- [x] #1378
- [x] #2215
- [x] #683
- [x] #2079
- [x] #2047

## Related Work

https://github.com/ZcashFoundation/zebra/issues/2215 is a subset of this issue, regarding sighashes. It raises the issue that since some test vectors are randomly generated, we may require changing zebra to accept invalid fields, which does not seem to be worth it. But it needs further investigation.

Create Sapling-only transaction v5 test vectors (#2047)
Import and test against Sinsemilla test vectors from zcash-hackworks (#2079)
Test transaction verification on block test vectors (#1378)
Move transaction test vectors into their own files (#1107)

**Comment by teor2345** [comment]
Thanks for opening this ticket, I added a bunch of related tickets.

@mpguerra do you think this task is more like an epic? It seems like there will be a smaller task for each module or feature, with different priorities.

**Comment by mpguerra** [comment]
Converted to github tracking issue

**Comment by teor2345** [comment]
We've completed or obsoleted all these tasks.
