### ISSUE TITLE
Replace atomics with watch or oneshot channels

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2268]
## Motivation

Some atomic sizes and atomic operations [are not available on some platforms](https://doc.rust-lang.org/std/sync/atomic/#portability). Others come with a performance penalty on some platforms.

It's also easy to use a memory ordering that's too weak. Future code changes might require a stronger memory ordering. It's hard to test for memory ordering bugs. Some memory ordering bugs can only be discovered on non-x86 platforms. And when they do occur, they can be rare.

Channels take care of all these portability, maintainability, testing, and correctness issues. So in general, Zebra should avoid atomics.

Fixing this issue is a low priority, unless atomic-using code starts failing tests or causing bugs.

### Designs

The "Replacing Atomics with Channels" section of the Zebra async Rust RFC:
https://github.com/ZcashFoundation/zebra/edit/main/book/src/dev/rfcs/0011-async-rust-in-zebra.md#replacing-atomics

Tokio channels:
https://docs.rs/tokio/*/tokio/sync

## Solution

- [x] Document why we don't use atomics in Zebra (#2269)
- [ ] Upgrade to the latest tokio (#2200)
- [ ] Replace atomics in production code with `watch` or `oneshot` channels
- [ ] Replace atomics in test code with `watch` or `oneshot` channels
- [ ] Disallow atomics in Zebra using a CI check (how?)

### Alternatives

We could keep using atomics, and accept these portability, maintainability, testing, and correctness risks.

## Related Work

#1678 Design and implement graceful shutdown for Zebra

**Comment by oxarbitrage** [comment]
We need to fix https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/sync/tests/timing.rs#L72

Ill send a PR.

**Comment by teor2345** [comment]
I've marked this issue as a low priority.

**Comment by oxarbitrage** [comment]
> Ill send a PR.

https://github.com/ZcashFoundation/zebra/pull/2281 - Ended up blocked. For correctness, we need to use of a method only available in tokio 1.

**Comment by teor2345** [comment]
This general cleanup is not required.
