### ISSUE TITLE
Fuzz or property test deserialization with random bytes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2282]
## Motivation

In Zebra, we do some random struct serialization round-trip property tests (#27).

But we don't take random bytes and try to deserialize them. This means that it's harder to catch security issues like #2263.

### API Reference

`proptest` has `Arbitrary` random data implementations for fixed-size byte arrays and variable-size byte vectors:
https://docs.rs/proptest/1.0.0/proptest/arbitrary/trait.Arbitrary.html

## Solution

For each deserialized type:
- deserialize a random fixed-size byte array or variable-sized byte vector
  - if deserialization panics, fail the test
- if deserialization is successful, serialize the type back into bytes, and check that they match

Try to prioritise smaller types over larger types, because a lot of larger types are just aggregates of smaller types.

### Issues

- [x] #2298
- [x] #2299
- [x] #2300

### Alternatives

If we don't do this, we risk panic security vulnerabilities.

## Related Work

Use property testing for message struct serialization round-trips #27 - goes from random types to bytes and back

**Comment by mpguerra** [comment]
Converted to an issue

**Comment by teor2345** [comment]
This is a useful test, but it's not urgent.
