### ISSUE TITLE
Cleanup MetaAddr after security fixes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2292]
## Motivation

After the `MetaAddr` refactors in PRs #2273, #2275, and #2276, we want to clean up the code a bit.

## Solution

These changes should all be made in separate PRs.

### Refactoring

- [x] #3248
  - For details see https://github.com/ZcashFoundation/zebra/pull/2273#discussion_r649993460
- [x] #3249

#### DateTime32 and Duration32

- [x] #3250
- [x] #3251

### Optimisation

- [x] Optimise the `AddressBook` returning the next peer by using `min()` rather than `collect::<BTreeSet>().next()`
- [ ] Remove unnecessary pass-by-reference on `Copy` types, guided by the following lints:
  - [`trivially_copy_pass_by_ref`](https://rust-lang.github.io/rust-clippy/master/index.html#trivially_copy_pass_by_ref)
  - [`ref_option_ref`](https://rust-lang.github.io/rust-clippy/master/index.html#ref_option_ref)
  - [`large_types_passed_by_value(avoid-breaking-exported-api = false)`](https://rust-lang.github.io/rust-clippy/master/index.html#large_types_passed_by_value)

### Documentation

- [ ] Replace unquoted `MetaAddr` and quoted ``` `MetaAddr` ``` with rustdoc links to MetaAddr: ```[`MetaAddr`]``` using `fastmod`
  - we might want to try the [`doc_markdown`](https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown) lint here, but it might have a lot of false positives

_TODO: add other tasks here as needed_

## Alternatives

These changes are optional, but they'll make the code easier to maintain.

**Comment by teor2345** [comment]
This task doesn't contribute directly to NU5 validation or client work, so I'm removing it from the sprint.

In the meantime we should do these tasks as needed for other work.

**Comment by mpguerra** [comment]
@teor2345 or @jvff can one of you please split this up into a number of issues for re-triage?

**Comment by teor2345** [comment]
Done!
