### ISSUE TITLE
Batch MetaAddrChanges and remove identical changes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2293]
## Motivation

The `TimestampCollector` can get a lot of identical changes from the same peer, but the `AddressBook` only needs to get one of each change.

## Solution

Implementation:
- [ ] use [`futures::stream::StreamExt::ready_chunks`](https://docs.rs/futures/0.3.15/futures/stream/trait.StreamExt.html#method.ready_chunks) to get all available changes to the `AddressBook`
- [ ] before applying them to the `AddressBook`, collapse runs of equal changes into a single change
  - use [`itertools::Itertools::dedup`](https://docs.rs/itertools/0.10.1/itertools/trait.Itertools.html#method.dedup) or [`std::slice::partition_dedup`](https://doc.rust-lang.org/std/primitive.slice.html#method.partition_dedup) if it is stable
- [ ] preserve the original order of the changes

Tests:
- [ ] write a proptest that ensures that the values and order of the original changes is preserved

### Alternatives

This optimisation is a low priority.

**Comment by mpguerra** [comment]
We don't want to do this anymore
