### ISSUE TITLE
Move Block in State Checks to Downloaders

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2307]
Move the "block is in the state" checks to the downloaders:
- [ ] in the sync downloader, check if the block is in the state after downloading it
- [ ] in the inbound downloader, check if the block is in the state after downloading it
- [ ] delete the "block in state" check from the `BlockVerifier`

We probably want to keep the "block in state" check in the checkpoint verifier. There can be a delay between the downloader sending blocks, and the checkpoint verifier receiving them, due to buffers and service readiness. And I'm pretty sure the checkpoint verifier can panic on duplicate blocks.

This is part of a split of #1820

**Comment by teor2345** [comment]
This work was part of an obsolete design, we don't need to do it any more.
