### ISSUE TITLE
Tracking: `zebrad` Usability

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2310]
This epic issue tracks usability fixes we might want to make whilst working towards our first stable release:

## Issues

- [x] #1158
- [x] #1591
- [x] #1627
- [x] #1655
- [x] #1772
- [x] #2188
- [x] #2201
- [x] #2394
- [x] #2847
- [x] #3279
- [x] #3287
- [x] #3288
- [x] #3242
- [x] #1904
- [x] #3042
- [x] #1023
- [x] #1323
- [x] #1380
- [x] #1381
- [x] #692
- [x] #1480
- [x] #1326
- [x] #1615
- [ ] #1617
- [x] #1619
- [x] #1621
- [x] #1623
- [x] #1624
- [x] #1625
- [x] #1626
- [x] #1893
- [x] #1894
- [x] #656
- [x] #758
- [x] #970
- [x] #1870
- [x] #1351
- [x] #1678
- [x] #3229
- [ ] #3133
- [ ] #3114
- [ ] #3136
- [ ] #3292
- [ ] #1677
- [ ] #3294
- [ ] #3293
- [ ] #3239
- [ ] #3240
- [ ] #1421

**Comment by mpguerra** [comment]
Converted to a github tracking issue

**Comment by teor2345** [comment]
Usability priorities should be based on user reports from the release candidate, we can track this using a GitHub tag.
