### ISSUE TITLE
Tracking: Security Issues

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2311]
This epic issue tracks security fixes we might want to make at some point, as part of some of our high level goals (e.g #3096, #3134, #2814, etc... ) 

# Issues

## Stable Release

- #3096 
   - [x] #3384
   - [x] #3388
   - [x] #1143
   - [x] #3278
   - [x] #1113 
   - [x] #3234 
   - [x] #2156 
   - [x] #3429 

## Lightwalletd

- #3134
   - [x] #2028
   - [x] #3300
   - [x] #3271
   - [x] #3048
   - [ ] #3117
   - [x] #3118
   - [x] #3184 
   - [x] #3242
   - [x] #1956
   - [x] #2214
   - [x] #2171
   - [x] #3263 
   - [x] #2211 
   - [x] #2434

## NU6

- #2814 
    - [x] #2336
    - [x] #1870

## Documentation

- [x] #3187
- [x] #3186
- [x] #3188 
- [x] #3183 

## Troubleshooting 

- [ ] #2112
- [x] #2137 

## Other

- [x] #2324
- [x] #2340
- [x] #2364
- [ ] #2654 - (to be done anytime post NU5 mainnet activation)
- [x] #3288 
- [x] #3290 
- [x] #3320
- [x] #2153
- [ ] #1875
- [x] #1166

**Comment by mpguerra** [comment]
Changing this from an Epic to a tracking issue

**Comment by teor2345** [comment]
We're tracking these tasks using the Security GitHub tag.
