### ISSUE TITLE
Run benchmarks as part of Zebra CI

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2320]
## Motivation

We currently do not run our benchmarks as part of CI.

## Solution

We may want to run benchmarks as part of CI in a manner similar to our coverage jobs (informational but not blocking) to track these over time and make sure they don't break silently.

### Alternatives

Don't run benchmarks regularly as part of CI. They may continue to break silently.

## Related Work

https://github.com/ZcashFoundation/zebra/pull/2288

**Comment by conradoplg** [comment]
+1! If we don't do that then we can end up with benchmarks gettings worse for whatever reason and having no immediate idea what the cause is (been there)

**Comment by teor2345** [comment]
> +1! If we don't do that then we can end up with benchmarks gettings worse for whatever reason and having no immediate idea what the cause is (been there)

That's a slightly different change - this ticket is about making sure benchmarks compile and run successfully.

@conradoplg can you open a different ticket for showing benchmark results in CI using a bot?

**Comment by conradoplg** [comment]
> 
> That's a slightly different change - this ticket is about making sure benchmarks compile and run successfully.
> 
> @conradoplg can you open a different ticket for showing benchmark results in CI using a bot?

Sure, done in https://github.com/ZcashFoundation/zebra/issues/2348

**Comment by teor2345** [comment]
We can re-open this when we have important benchmarks we want to run in CI.
