### ISSUE TITLE
Ignore and sanitize untrusted MetaAddr peer services

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2324]
## Motivation

We have a higher level of trust in peer services that we learn directly from the peer itself.

But if we learn those services from other peers, we don't trust them very much, so we might want to:
- sanitize untrusted services
- ignore untrusted services when choosing the next peer to connect to

### Specifications

> The services the node advertised in its “version” message.

https://developer.bitcoin.org/reference/p2p_networking.html#addr

(The bitcoin reference and bitcoin wiki don't say much about services.)

### Refactor
- [x] make services optional (PR #2976)
- [ ] split peer services into optional untrusted and direct fields
- [ ] update those fields correctly with each service change
- [ ] create a "services implemented by Zebra" constant

### Security
- [ ] ignore untrusted services when choosing the next peer to connect to in `impl Ord for MetaAddr`
  - [ ] order trusted services by usefulness when selecting peers, not numeric values
    - [ ] make sure `Option<PeerServices>` ordering handles `None` and `Some` comparisons correctly
- [ ] consider sanitizing untrusted service fields to known bits (?)

### Alternatives

This change doesn't make any difference to security until Zebra supports multiple service bits.

Even then, this change might not make much difference to security.

## Related Work

The `MetaAddrChange` code in PRs #2273 and #2275 already has some untrusted service fields.

**Comment by ftm1000** [comment]
redistributing issues that can be separately worked from this epic #2311

**Comment by teor2345** [comment]
Zcash doesn't really use this field, so this change is not required.
