### ISSUE TITLE
Update librustzcash to its next release

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2353]
## Motivation

We are currently pointing to a specific commit of libruszcash. We should point to the next release after it's published.

### Specifications

N/A

### Designs

N/A

## Solution

Update librustzcash to its next release. Remove the hardcoded dependencies in the workspace Cargo.toml that are copied from the librustzcash workspace Cargo.toml.

### Alternatives

Keep pointing to the commit, but that should be avoided

## Related Work

N/A

**Comment by teor2345** [comment]
Duplicate of #2982.
