### ISSUE TITLE
Part of ZIP 212: validate Sapling and Orchard output of coinbase transactions 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2362]
## Motivation

For NU4 (Canopy), ZIP-212 introduced a new consensus rule related to the format of Sapling Output note plaintexts. While we aren't sending/receiving money yet in Zebra, as per [ZIP-213](https://zips.z.cash/zip-0213) we still need to decrypt and validate Sapling coinbase Outputs to the all-zero outgoing viewing key:

![image](https://user-images.githubusercontent.com/552961/122837128-91b4d300-d2c1-11eb-8216-b6afae2f8bb0.png)

![image](https://user-images.githubusercontent.com/552961/122837286-d476ab00-d2c1-11eb-98f7-8eb673118469.png)

![image](https://user-images.githubusercontent.com/552961/122837359-efe1b600-d2c1-11eb-8d05-4d896f79d6f5.png)

ZIP-212 is an update to the coinbase rules specified in ZIP-213.

### Specifications

![image](https://user-images.githubusercontent.com/552961/122837421-0c7dee00-d2c2-11eb-8eeb-99ab406ef238.png)

https://zips.z.cash/zip-0212

We need to implement "Decryption using a Full Viewing Key (Sapling and Orchard)":

![image](https://user-images.githubusercontent.com/552961/122838329-dc374f00-d2c3-11eb-9b2f-b46e9ce78110.png)
![image](https://user-images.githubusercontent.com/552961/122838349-e5c0b700-d2c3-11eb-929d-ab18f4cf1d31.png)

https://zips.z.cash/protocol/protocol.pdf#decryptovk

## Solution

We must move up our implementation of decrypting Sapling (and Orchard) notes for outgoing viewing keys, and use that in shielded coinbase checking, by decrypting the note ciphertexts of Sapling Outputs / Orchard Actions, and checking that the lead byte of the note plaintext resulting from decrypting to the all-zero 32 bytes outgoing viewing key is 0x02.

This relies on:

https://github.com/ZcashFoundation/zebra/issues/2041
https://github.com/ZcashFoundation/zebra/issues/269

This will require finishing / checking the Sapling and Orchard key derivation is complete according to the spec, and then use that as part of semantic transaction validation to check the shielded coinbase outputs can be decrypted under the all-zeros outgoing viewing key. The decryption implementation in zebra-chain should error / fail to represent a note plaintext with an incorrect leading byte (structural validation).

### Alternatives

Not validate this consensus rule, and not be a fully validating consensus node.

## Related Work

https://github.com/ZcashFoundation/zebra/issues/2041
https://github.com/ZcashFoundation/zebra/issues/269

**Comment by teor2345** [comment]
@dconnolly @conradoplg I think ZIP-212 is out of date here.

The consensus rules from the spec include Orchard:

> [Heartwood onward] All Sapling and Orchard outputs in coinbase transactions MUST decrypt to a note plaintext , i.e. the procedure in § 4.19.3 ‘Decryption using a Full Viewing Key (Sapling and Orchard)’ on p. 65 does not return ⊥, using a sequence of 32 zero bytes as the outgoing viewing key.
>
> [Canopy onward] Any Sapling or Orchard output of a coinbase transaction decrypted to a note plaintext according to the preceding rule MUST have note plaintext lead byte equal to 0x02. (This applies even during the “grace period” specified in [ZIP-212].)

https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus

**Comment by dconnolly** [comment]
Here's the zcash_note_encryption crate, using it for ZIP-212 coinbase note decryption compliance is as easy as calling a single function (after serializing/constructing the types), but I think for wallet/Zebra client, we'd like to port / freshly implement in zebra-chain with/against our own types:

https://github.com/zcash/librustzcash/blob/master/components/zcash_note_encryption/src/lib.rs

**Comment by mpguerra** [comment]
@dconnolly how does #2041 relate to this issue? Do we need to do it before this one? or is it already covered as part of this issue? 

We should either add #2041 to sprint 22, remove the dependency on #2041 for this issue or close #2041 altogether depending on the answer.

**Comment by dconnolly** [comment]
> @dconnolly how does #2041 relate to this issue? Do we need to do it before this one? or is it already covered as part of this issue?
> 
> We should either add #2041 to sprint 22, remove the dependency on #2041 for this issue or close #2041 altogether depending on the answer.

Per #3029, this #2041 is not strictly a blocker to #2362 because we do not need to derive the `OutgoingCipherKey`, as it is only a static value (all zeroes) to validate that consensus rule.

We need to implement #2041 for Orchard and the same for Sapling (but not Sprout) for client work, when we need to derive a non-static key to decrypt notes.

**Comment by teor2345** [comment]
> We need to implement #2041 for Orchard and the same for Sapling (but not Sprout) to client work, when we need to derive a non-static key to decrypt notes.

I've removed #2041 from the sprint and left it in the wallet epic.

**Comment by dconnolly** [comment]
I am removing https://github.com/zcashfoundation/zebra/issues/269 as a blocker to this issue alone, as we are able to validate this part of ZIP-212 using the function from `zcash_note_encryption` using the static all-zeroes `OutgoingCipherKey` alone, and moving it to the wallet epic. 

Everything else in ZIP-212 will require finishing the derivation of the `OutgoingCipherKey` and finishing the Sapling/Orchard note encryption/decryption to work natively with our types.
