### ISSUE TITLE
Unable to start zebrad (Ubuntu 20.04)

### ISSUE THREAD

**Issue by yawnbox** [ZcashFoundation/zebra#2370]
## Description

I'm not able to start zebrad (generate / start) from a new install on Ubuntu 20.04.

### Steps to Reproduce

The directions here aren’t great for outsiders:
https://zebra.zfnd.org/user/install.html

`sudo apt install clang libclang-dev llvm llvm-dev`

Installed Rust. Did not install ‘rustc’ (or cargo) from apt. At first, doing so installed rust version 1.47, where =>1.48 is necessary.

`curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh`

```
rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

`source $HOME/.cargo/env`

`git clone https://github.com/ZcashFoundation/zebra`

`cd zebra/`

`cargo build —verbose`

`zebrad generate`

```
Command 'zebrad' not found, did you mean:

  command 'zebra' from deb quagga-core (1.2.4-4build1)

Try: sudo apt install <deb name>
```

### Operating System

Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dconnolly** [comment]
Hi! Thanks for trying Zebra. To install zebrad on your path, you need to [use `cargo install`, instead of `cargo build`](https://github.com/ZcashFoundation/zebra#getting-started):

> #### Detailed Build and Run Instructions
> 1. Install [`cargo` and `rustc`](https://www.rust-lang.org/tools/install).
>      - Using `rustup` installs the stable Rust toolchain, which `zebrad` targets.
> 2. Install Zebra's build dependencies:
>      - **libclang:** the `libclang`, `libclang-dev`, `llvm`, or `llvm-dev` packages, depending on your package manager
>      - **clang** or another C++ compiler: `g++`, `Xcode`, or `MSVC`
> 3. Run `cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-alpha.11 zebrad`
> 4. Run `zebrad start`


https://github.com/ZcashFoundation/zebra#getting-started

Can you give that a try?

**Comment by yawnbox** [comment]
That did the trick, thanks so much. Sorry for the noise.

**Comment by dconnolly** [comment]
> That did the trick, thanks so much. Sorry for the noise.

Great! Let us know if you have any other trouble or questions 😁
