### ISSUE TITLE
 Update the README goals and scope for NU5 mainnet activation

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2372]
## Motivation

Update Zebra's readme with the latest release goals and scope.

## Solution

- [ ] Wait until all the NU5 validation tickets are done
- [ ] Update the goals
- [ ] Update the scope
- [ ] Check the README for other outdated info

**Comment by conradoplg** [comment]
We did as part of the beta.10 release, though we might want to review the documentation before the release candidate (I'll create a another ticket for that)
