### ISSUE TITLE
Allow different `zebra-network` apps to use different user agents

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2375]
## Motivation

1. We want `zebrad` to have a different user agent from the ECC's DNS seeder, and other apps that use `zebra-network`

2. We'd like to simplify Zebra's release process, by automatically using a `zebrad` version in the zebra-network user agent.

### Specifications

https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki

## Solution

- [ ] Add a `user_agent` argument to `zebra_network::init`, and pass it to the handshaker
- [ ] In `zebrad::commands::start`, pass `application::app_version()` to `zebra_network::init`
  - Use the BIP-14 format: "/Zebra:1.0.0-alpha.11/"
- [ ] Add the supplied user agent to the front of the `zebra-network` user agent string, using the BIP-14 syntax

https://github.com/ZcashFoundation/zebra/blob/c40cbee42f0897932b03ba9fbb53bf6219e4c5f8/zebra-network/src/isolated.rs#L43-L59

## Related Work

Make sure custom user agents conform to BIP-14 #794

**Comment by dconnolly** [comment]
Have we done this already?

**Comment by teor2345** [comment]
> Have we done this already?

Unfortunately not, we just do a manual search and replace for the version constant in the code. This seems to work ok for now.

**Comment by teor2345** [comment]
Now there are multiple apps using `zebra-network`, we might want to be able to distinguish them on the network
