### ISSUE TITLE
Deploy Zebra nodes on fixed IP addresses

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2380]
## Motivation

To test Zebra on testnet and mainnet, we should deploy Zebra nodes on fixed IP addresses.

This tests that Zebra is a full participant in the Zcash network.

### API Reference

https://cloud.google.com/sdk/gcloud/reference/compute/instance-templates/create-with-container
https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/create

> listen_addr: SocketAddr
> 
> The address on which this node should listen for connections.
>
> Can be address:port or just address. If there is no configured port, Zebra will use the default port for the configured network. address can be an IP address or a DNS name. DNS names are only resolved once, when Zebra starts up.
> 
> If a specific listener address is configured, Zebra will advertise it to other nodes. But by default, Zebra uses an unspecified address (“0.0.0.0” or “[::]”), which is not advertised to other nodes.
> 
> Zebra does not currently support:
> - Advertising a different external IP address #1890, or
> - Auto-discovering its own external IP address #1893.
> 
> However, other Zebra instances compensate for unspecified or incorrect listener addresses by adding the external IP addresses of peers to their address books.

https://doc.zebra.zfnd.org/zebra_network/struct.Config.html#structfield.listen_addr

## Solution

- [ ] Configure all deployed Zebra nodes with the Google Cloud external IP address
- [ ] Allow inbound connections to ports 8233 and 18233
- [ ] Deploy a mainnet and testnet Zebra node on fixed IP addresses, every time a release is tagged (using an action)

Optional:
- [ ] Deploy a mainnet and testnet Zebra node on fixed IP addresses, every time the main branch is updated

### Alternatives

Individual developers run their own nodes, but that's not as reliable as auto-deployment.

If the IP address changes frequently, nodes don't get included in DNS seeders.

**Comment by dconnolly** [comment]
Not strictly needed for release candidate, but we should discuss if we need to solve this before recommending it to users. // @mpguerra @ftm1000 @gustavovalverde

**Comment by teor2345** [comment]
We opened this because we thought it might be causing the DNS seeder issues, but that doesn't seem likely right now.
