### ISSUE TITLE
Check that at least one of enableSpendsOrchard or enableOutputsOrchard is set

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2433]
## Motivation

A new consensus rule for transaction V5 was added to the spec today(2021-07-01) related to the Orchard flags. We need to implement.

### Specifications

> [NU5 onward] If effectiveVersion >= 5 and nActionsOrchard > 0, then at least one of enableSpendsOrchard and enableOutputsOrchard MUST be 1.

https://zips.z.cash/protocol/protocol.pdf#txnconsensus

**Comment by teor2345** [comment]
Scheduling this for sprint 15, because it's a simple change to our existing validation.
