### ISSUE TITLE
Run Ziggurat tests as part of Zebra's CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2434]
## Motivation

We'd like our CI to test Zebra's network message handling.

Currently we don't have a lot of message tests. Our existing tests also rely on other Zebra code, which makes it easy to introduce bugs that compensate for each other. (And cause the tests to mistakenly pass.)

The Ziggurat network test framework has conformance, performance, and fuzzing tests: https://github.com/eqlabs/ziggurat

## Related Work

Any changes to Zebra's network stack.

**Comment by dconnolly** [comment]
Test specs: https://github.com/eqlabs/ziggurat/blob/master/SPEC.md

**Comment by teor2345** [comment]
I'm not sure if these tests are stable enough to run in CI.
