### ISSUE TITLE
Slim down `zebra-consensus/src/transaction.rs`

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2436]
## Motivation

`transaction.rs` is getting larger, and we should move some of the code into separate submodules.

We can probably move `AsyncChecks` into its own/another module at least. 

## Related Work

https://github.com/ZcashFoundation/zebra/pull/2432

**Comment by teor2345** [comment]
We might also want to move the transparent and shielded checks to their own modules.

**Comment by teor2345** [comment]
We should split up a bunch of large modules when we tackle technical debt.
