### ISSUE TITLE
Add retry policies to zebra-network.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#244]
The stub code in #240 always ends up crashing before it finishes downloading the chain, because it panics when one of the requests fails.  The reason it panics is because we don't have any retry mechanisms currently in place.

Tower provides a retry mechanism via `tower::retry`: https://docs.rs/tower/0.3.1/tower/retry/index.html

Retries work by wrapping a `Service` in a `Retry` wrapper, with a particular `Policy`: https://docs.rs/tower/0.3.1/tower/retry/struct.Retry.html

A `Policy` determines when to retry requests: https://docs.rs/tower/0.3.1/tower/retry/trait.Policy.html

We probably *don't* want to add any retry policy to the peer set by default, but we *do* want to hawe a library of `Policy`'s for users to layer onto their peer set handle.  To start, we could add an `AlwaysRetry` policy that retries an unlimited number of times.

**Comment by dconnolly** [comment]
Closed by #246
