### ISSUE TITLE
Look up the UTXOs in the transaction verifier, then pass them to `verify_transparent_inputs_and_outputs`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2440]
## Motivation

Currently, Zebra's script verifier looks up UTXOs. But we also need those same UTXOs to calculate mempool transaction fees.

So we should look up the UTXOs in the transaction verifier, and send them to `verify_transparent_inputs_and_outputs`,  which can send them to the script verifier as part of the request.

### Consensus Rules

> `low_fee_penalty` is 16000 if the transaction pays a fee less than the conventional fee, otherwise 0

https://zips.z.cash/zip-0401#specification

**Comment by teor2345** [comment]
This change doesn't guarantee us correct UTXOs, for details, see:
https://github.com/ZcashFoundation/zebra/pull/2486/files#r677190254

**Comment by teor2345** [comment]
Turns out we need this to calculate mempool fees.

**Comment by teor2345** [comment]
Conflicts with the NU5 block validation code freeze, moving after NU5 testnet activation.
