### ISSUE TITLE
Define a new `Amount` `Constraint` for Note values w/ [0..2^64) as `valid_range()`

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2447]
## Motivation

Orchard defines the valid range of note values to be not [0..MAX_MONEY] as defined in several places in the spec for Sapling and Sprout, but [0..2^64), which is the range of values for Orchard, Sapling, and Sprout that are actually checked _in the circuit_. The value balance, at the transaction level, is still checked to be {−MAX_MONEY .. MAX_MONEY} for Orchard/Sapling. There are already Orchard test vectors that define note values (not value balances) MAX_MONEY < v < 2^64, which is out of range of the `Amount` `Constraint`s we have defined so far.

### Specifications

https://zips.z.cash/protocol/protocol.pdf#notes

![image](https://user-images.githubusercontent.com/552961/124560406-c4ef7a00-de0a-11eb-8508-daeb3c324a87.png)

### Designs

0. Change the underlying type for `Amount`

The current underlying type is `i64`.

We could change the type based on the constraint, or use `i128`, or use `u64` and a sign bit.

1. Implement a `Constraint` that has a `value_range` of [0..u64::MAX):

```rust
pub struct NonNegativeMaxU64;

impl Constraint for NonNegativeMaxU64 {
    fn valid_range() -> RangeInclusive<u64> {
        0..=u64::MAX
    }
}
```

2. Change `Amount` additions and subtractions to use checked arithmetic, to prevent silent overflows. (Currently, only multiplications, divisions, and sums have to use checked arithmetic, because the existing constraints restrict values to less than `2^51`.)

## Related Work

https://github.com/zcash/zips/issues/533

**Comment by teor2345** [comment]
We might want to re-think this design, because some coins like ethereum use 128-bit amounts.

We could end up with a new `Amount128` type, which always comes with an asset ID, and then `Amount` would just be used for ZEC/TAZ.
