### ISSUE TITLE
Possibly implement conversion from `Vec<NoteCommitment>` into `NoteCommitmentTree`

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#2462]
## Motivation

The code contained a stub implementation of `From<Vec<NoteCommitment>> for NoteCommitmentTree`. This was initially added in commit [b93abea34](https://github.com/ZcashFoundation/zebra/commit/b93abea34f265e7cc883b16fe51b2acae89ac869), but seems like it's currently unused.

As part of the work for #2369, the code was removed to avoid being used and inadvertently leading to a panic.

A decision should be made whether the conversion should be implemented or not.

**Comment by teor2345** [comment]
This code is revised or removed in the incremental note commitment tree PR #2407 / ticket #1287, so we don't need a separate ticket for it.
