### ISSUE TITLE
Revert to the Zebra sighash implementation

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2468]
## Motivation

In #2183 we deleted our sighash implementation in order to use the librustzcash one, since we found a couple of bug in ours.

However, we may want to revert to our own implementation (and maybe implement our own ZIP-244 sighash). One possible reason for doing that would be efficiency (since we need to reserialize the transaction and deserialize it with librustzcash), but there could be others.

We must decide if we actually want to do this.

### Known Issues

The Zebra sighash implementation changes the sighash based on the current network upgrade. But the specification uses the transaction version to select the sighash. We need to fix this bug before we can re-use the Zebra implementation, because it impacts NU5, which allows both V4 and V5 transactions.

We might want to remove some `unimplemented!` placeholders in the original code after it is reverted. See for example this [previous attempt](https://github.com/jvff/zebra/compare/4a81e1d47f209f9ab2f6681cd7159ba719e1c29b..32b332d8f020c59e3f10fb5c9a073279a113c717).

### Specifications

ZIPs 143, 243, and 244.

### Related Tickets

 If we use Zebra's implementation, we might also want to [Move duplicate Transaction code into methods](#1828)

**Comment by jvff** [comment]
If this is done, it might be interesting to remove some `unimplemented!` placeholders in the original code after it is reverted. See for example this [previous attempt](https://github.com/jvff/zebra/compare/4a81e1d47f209f9ab2f6681cd7159ba719e1c29b..32b332d8f020c59e3f10fb5c9a073279a113c717).

**Comment by conradoplg** [comment]
Closing this since performance doesn't seem to be an issue. If we decide it should be done we can reopen it.
