### ISSUE TITLE
Handle a ivk == ⊥ (KA^Orchard private key) when generating an Orchard Spending Key

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2496]
## Motivation

Currently, `SpendingKey::new` does not seem to handle the case where the derived ivk is ⊥, which should trigger retrying with a new key per the spec.

### Specifications

https://zips.z.cash/protocol/protocol.pdf#orchardkeycomponents

### Designs

Note that this is not urgent (AFAIK) since it's unlikely that ivk will be ⊥ per Theorem 5.4.4, but we should eventually match the spec.

## Related Work

N/A

**Comment by dconnolly** [comment]
I think this was implemented before this check was added to the spec, and yeah we should handle this before/as we ramp up zebra-client work

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2496?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Closed by PR #5476 by deleting the spending key code.
