### ISSUE TITLE
Make Memo an enum type

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#250]
As described in 
https://github.com/ZcashFoundation/zebra/pull/249#issuecomment-585482542
https://github.com/ZcashFoundation/zebra/pull/249#issuecomment-585485102
https://github.com/zcash/librustzcash/pull/177/files

**Comment by dconnolly** [comment]
@str4d when we opened this ticket we noticed an incompatibility between the spec and I think ZIP 302 memos, a flag indicating that something is all binary or not, does this ring a bell to you?

**Comment by yaahc** [comment]
@dconnolly are you handling this issue as well as part of the note commitment work that you took over or is this issue still in my court?

**Comment by dconnolly** [comment]
I'll grab it as I'm moving that struct/impl around anyway 👍

**Comment by dconnolly** [comment]
Related: #242

**Comment by dconnolly** [comment]
Closing for now
