### ISSUE TITLE
Replace git dependency on multiset crate

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2523]
## Motivation

https://github.com/ZcashFoundation/zebra/pull/2458/ added a dependency on `multiset`, and it's not maintained anymore, which could be a liability.

`multiset` 0.0.5 contains [at least one bug](https://github.com/jmitchell/multiset/pull/21).
There is a bug fix on the `master` branch, but it has not been released (as of 7 November 2021).

## Scheduling

We need to make this change before we publish the `zebra-state` crate to crates.io, because crates.io will not accept a git dependency on `multiset`.

## Tasks

1. Use one of these maintained crates instead:
    * https://docs.rs/hashbag/0.1.4/hashbag/struct.HashBag.html
    * https://docs.rs/mset/0.0.4/mset/struct.MultiSet.html

2. Remove the exceptions for `multiset` in `deny.toml`

## Related Work

Follow up of https://github.com/ZcashFoundation/zebra/pull/2458/

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2523?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
