### ISSUE TITLE
Design: running contextual checks on mempool transactions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2534]
## Motivation

Recently, we've added a lot of contextual validation to `zebra-state`.

But some of these consensus rules also apply to mempool transactions, which are only validated by the the transaction verifier in `zebra-consensus`.

We only need this special handling for consensus rules that:
* are context-dependent - rules that depend on previous transactions or blocks,
* apply to non-coinbase transactions, or all transactions, and
* don't already have special handling.

For example, `Utxo`s already have special handling: their context-dependent information is made available to the transaction verifier.

### Current Validation

Zebra checks context-dependent transaction consensus rules in a few different places.

The `StateService`:
https://github.com/ZcashFoundation/zebra/blob/a7b0a521d51af4af7294892604c34087e0414330/zebra-state/src/service.rs#L171-L173

The `nullifier` and `utxo` check modules:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/check/

The `NonFinalizedState`:
https://github.com/ZcashFoundation/zebra/blob/a7b0a521d51af4af7294892604c34087e0414330/zebra-state/src/service/non_finalized_state.rs#L167-L174

And some context-dependent non-coinbase transaction validation that we haven't implemented yet.
See these sprints:
* https://github.com/ZcashFoundation/zebra/milestone/23
* https://github.com/ZcashFoundation/zebra/milestone/24
* https://github.com/ZcashFoundation/zebra/milestone/30

**Comment by conradoplg** [comment]
I reviewed the existing contextual validation. What seems to apply to mempool is:

- Checking for double spends (UTXOs, nullifiers)
- Checking for invalid spends (e.g. non-mature coinbase transactions)
- Checking for missing inputs (UTXOs, anchors?)
- Checking for value balance violations (it does not seem possible to validate this in the mempool, but I'm not completely sure)

I believe missing inputs are checked by the transaction verifier (which we do call before inserting into the mempool), but the rest is not currently being checked.

**Comment by teor2345** [comment]
These missing rules are all low priority, because they allow more transactions than `zcashd`'s mempool.


> * Checking for invalid spends (e.g. non-mature coinbase transactions)
> * Checking for missing inputs (anchors?)
> * Checking for value balance violations

We could validate these by checking the transaction against the best non-finalized chain.

> * Checking for double spends (UTXOs, nullifiers)
> * Checking for missing UTXOs

Here are our current checks:
* UTXO and nullifier double-spends between mempool transactions
* UTXO and nullifier double-spends within each mempool transaction (and mined transaction)
* UTXO that have already been spent (or have not been created) in the **finalized** chain can't be spent by mempool transactions (and mined transactions)

Here is the missing check:
* a mempool transaction can't reveal a nullifier that has already been revealed by the best non-finalized chain
* UTXO that have already been spent (or have not been created) in the **best non-finalized** chain can't be spent by mempool transactions (and mined transactions)
  * we could just skip this rule, and say that the finalized chain is close enough

**Comment by teor2345** [comment]
This isn't needed, we should open tickets for missing or incorrect checks instead.
