### ISSUE TITLE
Reject checkpointed blocks that would increase note commitment trees beyond their max sizes

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2544]
## Motivation

This was an implicit consensus rule, now made explicit.

### Specifications

![unknown-4.png](https://user-images.githubusercontent.com/552961/127536806-efcfe33f-3138-492a-bd2d-5691a0bcf6ca.png)

**Comment by teor2345** [comment]
Zebra already returns an error in all relevant cases:
- the non-finalized state returns an error if a note commitment tree becomes full
- the checkpoint verifier binds the transaction IDs to the block header, and returns an error if that check fails:
  - v1-v4 transactions bind all transaction data to the transaction ID
  - v5 transactions bind note commitments to the transaction ID
