### ISSUE TITLE
Test History Tree errors in finalized state

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2559]
## Motivation

https://github.com/ZcashFoundation/zebra/pull/2553/ adds the ZIP-221 History Tree to the finalized state, but there are no particular tests for it (other the running the node and checking if it syncs correctly).

Implement tests to test it, in particular the error paths. See https://github.com/ZcashFoundation/zebra/pull/2553/files#r680668957 for context:
> I think we'll need to make them cached state tests (and work out how to feed them corrupt blocks), or do significant refactoring, or wait until after NU5 testnet activation.

One quick way to do this test is:
* add the NU5 testnet activation block and a few following blocks to the Zebra test vectors
* test that the finalized state works when given those blocks
  * pre-populate the finalized state with the UTXOs deleted by those blocks, the `NU5 - 1` note commitment trees, and whatever other state is required for the tests to pass
* modify the blocks for each kind of error

### Specifications

N/A

### Designs

N/A

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2553/

**Comment by teor2345** [comment]
This seemed to work correctly on testnet before the second NU5 activation.
