### ISSUE TITLE
Test History Tree serialization

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2560]
## Motivation

https://github.com/ZcashFoundation/zebra/pull/2553/ adds History Tree serialization in the state using bincode and serde (using a helper `HistoryTreeParts` struct). However, there is no particular tests for this functionality.

Add tests for it.

See https://github.com/ZcashFoundation/zebra/pull/2553/files#r680669776 for context

### Specifications

N/A

### Designs

N/A

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2553/

Note that in #2331 we want to remove serde and change the serialization format, which will change the tests.

**Comment by teor2345** [comment]
This seems ok for now.
