### ISSUE TITLE
Remove redundant watch values once our Tokio dependency is updated

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#2573]
## Motivation

When Zebra uses `tokio::sync::watch::Sender`, we sometimes need an extra `value` field, because Tokio version 0.3.6, doesn't have a `watch::Sender::borrow` method.

That method is available on Tokio 1.0.0, so once we update to the newer version we can remove that field and replace its usage with `*self.sender.borrow()`.

Impacted types:
* `ChainTipSender`
  * #2519
  * #2676 
* `RecentSyncLengths`
  * #2602 

## Related Work

#2200 tracks updating the Tokio dependency.

**Comment by teor2345** [comment]
We can fix this when we change the related code.
