### ISSUE TITLE
Clean up History Tree fields (network, network_upgrade)

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2587]
## Motivation

Both `HistoryTree` and `zcash_history::Tree` have `network` and `network_upgrade` fields.

Clean it up to reduce data duplication - HistoryTree could probably just use the fields from Tree. We can possibly get rid of `network_upgrade` too since it can be derived from `network` and block height.

See [discussion](https://github.com/ZcashFoundation/zebra/pull/2582/files#r684951362)

### Specifications

N/A

### Designs

N/A

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2582/

**Comment by teor2345** [comment]
We can fix this if we change this code.
