### ISSUE TITLE
Refactor FinalizedState::commit_finalized_direct

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2588]
## Motivation

`FinalizedState::commit_finalized_direct` is too big and does multiple things. Refactor it to (as suggested by @teor2345  in [discussion](https://github.com/ZcashFoundation/zebra/pull/2582/files)):

1. Move the note commitment tree and history tree updates outside the database batch
1. Move any other calculations or lookups outside the database batch (such as UTXO lookups)
1. Split out the chain order assertion, the calculations, and the write batch into separate methods

If we move the calculations, the batch closure becomes infallible, because it only contains serialization and deserialization.

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2582/

**Comment by teor2345** [comment]
Closed by PR #3579, but I can't get the closing keywords to work.
