### ISSUE TITLE
Tracking: parse all message types.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#26]
This is a tracking issue for all message parsing tasks.

- [x] `version`
- [x] `verack`
- [x] `ping`
- [x] `pong`
- [x] `reject`
- [x] `addr` - #25 
- [x] `getaddr` - #25
- [x] `block` - #21 
- [x] `getblocks` - #21, #44
- [x] `headers` - #21, #44
- [x] `getheaders` - #21, #44
- [x] `inv` - #24 
- [x] `getdata` - #44
- [x] `notfound` - #44 
- [x] `tx` - #13, #44 
- [x] `mempool` - #102
- [x] `filterload` - #129 
- [x] `filteradd` - #129
- [x] `filterclear` - #129
~`merkleblock`~ - #129

**Comment by hdevalence** [comment]
`tx` should probably be unchecked until #13 is closed, correct? (unchecking, can re-check later)

**Comment by hdevalence** [comment]
Reminder that when we finish this, we should change the `peer::Server` behaviour to fail the connection on a message parse error.

**Comment by dconnolly** [comment]
I'm pretty sure zcashd doesn't implement `merkleblock` messages so I propose we don't either, since we're setting `NODE_BLOOM=false` anyway: 
https://github.com/zcash/zcash/blob/fffd5da201bf74cc832b27a1168ba4555df1524b/src/main.cpp#L6222

**Comment by hdevalence** [comment]
SGTM!
