### ISSUE TITLE
Allow LedgerState to be created with a network upgrade height

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2604]
## Motivation

The LedgerState strategy which is used for testing can be created to generate LedgerStates with a specific height or a specific network upgrade. However, there is no way to use the height of a specific network upgrade. Currently there's a workaround in `PreparedChain::new_heartwood` (computes the height for both networks and use the larger) but it would be nice to have a clearer implementation.

See [discussion](https://github.com/ZcashFoundation/zebra/pull/2583/files/fcc84dfc6a76e1d5970bd5952ef7cc54185a207b#r685572060)

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2583/

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2604?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
Optional cleanup that we can do if we touch the code again if needed.
