### ISSUE TITLE
Send `mempool` requests for mempool inventories from the network

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2605]
https://developer.bitcoin.org/reference/p2p_networking.html#mempool

**Comment by teor2345** [comment]
How is this different from #2593?

The mempool crawler sends `mempool` messages to peers.

**Comment by mpguerra** [comment]
If there is nothing else that the mempool crawler task will do, then it is not different from #2593 .

If so, we can close this as a duplicate and clarify that this is what it will do in the issue description.

**Comment by mpguerra** [comment]
Closing as duplicate of #2593
