### ISSUE TITLE
Download and verify peer `TransactionIds` responses from mempool crawler `MempoolTransactionIds` requests

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2606]
https://developer.bitcoin.org/reference/p2p_networking.html#mempool
https://developer.bitcoin.org/reference/p2p_networking.html#inv

**Comment by teor2345** [comment]
This is the download part of the download and verify stream.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2606?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
closing as a duplicate of #2650
