### ISSUE TITLE
Ignore `addrv2` and `sendaddrv2` messages

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2617]
## Motivation

Some `zcashd` developers are working on adding support for Tor V3 Onion Services. This involves a network protocol upgrade, and some new network message types: `addrv2` and `sendaddrv2`.

Currently, Zebra disconnects from peers that send unrecognised message types (#2107).

Until we fix that bug, we want to ignore these new messages instead.

### Specifications

https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki

### Current Implementation

Zebra returns an error and disconnects from the peer if the message type is unrecognised: 
https://github.com/ZcashFoundation/zebra/blob/76591ceeede5d917ad6db54ae4fce12d67cddd2d/zebra-network/src/protocol/external/codec.rs#L435

## Related Work

Eventually, we might want to add V3 onion service support in Zebra, which involves parsing and storing these addresses in our address book.

**Comment by zancas** [comment]
Ideally we'll:
0.  Implement `sendaddrv2` responses to `version` (on a feature branch)
1.  Use the dev-version of `zcashd` to test a `zebrad`
2.  Implement `sendaddrv2` message discarding in `zebrad`
3.  Merge discarding `zebrad`
4.  Merge `sendaddrv2` `zcashd`

Given the small change required of `zebrad` it seems likely that this order can be achieved.

As I am writing this, I think I am realizing that we should land `sendaddrv2` handling nodes, before we launch nodes that actually broadcast them.

**Comment by teor2345** [comment]
> As I am writing this, I think I am realizing that we should land `sendaddrv2` handling nodes, before we launch nodes that actually broadcast them.

You might not need to do anything special for `zcashd`.
I think it already ignores unknown message types and continues talking to the peer.
(This is standard Bitcoin behaviour, but it's not really documented anywhere for Zcash.)

Zebra doesn't, for a bunch of different reasons:
* we want to close connections from non-Zcash port scanners (we'll fix this in #2107)
* it's easier to test a new network protocol stack if you get errors when you get it wrong
* it's hard to find out how the Zcash network protocol should work

**Comment by zancas** [comment]
So, for forwards compatibility `zebrad` will have to either keep "message parity" with `zcashd`, or register messages from the future (e.g. `sendheaders` and `sendaddrv2`) and treat them differently from others.

So if I understand correctly this implies at least 3 categories of message:

* `valid-and-supported`
* `valid-and-unsupported`
* `invalid`

It seems unlikely that `zcashd` and `zebrad` will always support identical message sets..   or...  at least it seems plausible that there will be skew, as it has now.

**Comment by teor2345** [comment]
> So, for forwards compatibility `zebrad` will have to either keep "message parity" with `zcashd`, or register messages from the future (e.g. `sendheaders` and `sendaddrv2`) and treat them differently from others.

Or Zebra could ignore unknown messages, once we have done the required security analysis (#2107).

**Comment by daira** [comment]
See https://forum.zcashcommunity.com/t/what-to-build/39594/12?u=daira about how Zcash has handled signalling of peer protocol changes differently from Bitcoin, and why. I would prefer that we not use `sendaddv2` at all (just as we didn't use `wtxidrelay` to signal support for [ZIP 239](https://zips.z.cash/zip-0239)).

Signalling features via the peer protocol version negotiation does not require ignoring unknown messages. Zebrad would be free to keep treating unknown messages as errors if we continue with that approach.

**Comment by zancas** [comment]
I will follow @daira 's recommendation to [use the peer-to-peer protocol version value (170015)](https://github.com/zcash/zips/pull/543/commits/e77ba6bbf045421886152a3591e7279b82dbf35d#diff-cc56913137ad827bc4c3dc33fa9a9de92349f090e353555aecf37f692c4a0ec1R184) as the signal indicating node support for `addrv2` formatted messages.   This leverages `zcash`'s node-lifespan design to keep the possible feature configurations that peers must communicate small (only the current feature set needs to be handled).

As such no `sendaddrv2` message needs to be supported.

**Comment by zancas** [comment]
If I understand [this constraint](https://github.com/zcash/zips/pull/543/commits/e77ba6bbf045421886152a3591e7279b82dbf35d#diff-cc56913137ad827bc4c3dc33fa9a9de92349f090e353555aecf37f692c4a0ec1R175), it implies that well-behaved nodes will continue to send v1 `addr` messages to peers that have not negotiated a sufficient version number with the node.
I _think_ that may mean that `zebrad` nodes running lower peer protocol versions should simply ignore `addrv2` as invalid (like port scanner traffic).

**Comment by zancas** [comment]
If I understand correctly no correctly functioning peer-node should send a `addrv2` to a peer with an insufficient peer-protocol version.     Is that correct?   Does that imply we can close this issue?

**Comment by teor2345** [comment]
Yes, this issue is outdated and doesn't match the draft ZIP 155.

But Zebra will need to parse and use the IPv4 and IPv6 addresses in the new `addrv2` message before mainnet NU5 activation.
