### ISSUE TITLE
Activate the chain update task when the mempool is activated

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2623]

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2623?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@upbqdn the latest design in PR #2715 makes this ticket obsolete.

We won't need to stop the chain tip update task, because there's no task dedicated to chain tip updates.

Instead, each service/stream/task can just check the chain tip as needed.
