### ISSUE TITLE
Activate the download and verify stream when the mempool is activated

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2628]

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2628?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
Since the stream is not a service, it's just something that is called by whoever wants it, then checking if the mempool is activated must be done by the callers. This will be done for the inbound service in https://github.com/ZcashFoundation/zebra/pull/2679/ but in this ticket we can ensure the check is being done wherever it's needed (and maybe refactor it if needed)

**Comment by teor2345** [comment]
> Since the stream is not a service, it's just something that is called by whoever wants it, then checking if the mempool is activated must be done by the callers.

Streams and services get called by tasks, but they can also do their own checks when they are called.
I'd like to do most checks inside the stream/service, so different callers get consistent outcomes.

The download and verify service can call `SyncStatus::is_close_to_tip` to check if the mempool is inactive.

If the mempool is inactive, it needs to:
- cancel all downloads
- cancel all verifications
- return `None` to the caller

(If Zebra's network connection is interrupted for a long time, we'll want to deactivate the mempool while we're catching up to the new tip.)

Edit: but this is mostly ticket #2629

**Comment by teor2345** [comment]
I think you're right, there's not much to be done to activate the download and verify stream.
(Maybe we created this ticket when we thought it was going to be a task?)

**Comment by mpguerra** [comment]
I wonder if this is something that will be covered by an issue that @dconnolly has been talking about opening with the init() function?

If so, should we just close this one?

**Comment by teor2345** [comment]
Yeah let's just close this one.
