### ISSUE TITLE
Send committed spent OutPoints & nullifiers to the mempool for rejection

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2631]
## Motivation

We need to get a list of recently committed spent outpoints & nullifiers from the state service, so we can evict any mempool transactions that also spend/reveal them.

This fixes some subtle bugs:
1. Transaction `1` spends `B` and `C` - it gets in the mempool
2. Transaction `2` only spends `B` - it gets mined into the chain, but transaction `1` is not rejected from the mempool
    - this is an optional-priority bug, because we're accepting more transactions than `zcashd`
3. Transaction `3` only spends `C` - it is rejected from the mempool, but it should be accepted
    - this is a low-priority bug, because we're rejecting transactions that `zcashd` would accept

## Constraints

These rejections should persist until a chain reset, because:
* an outpoint can only be spent once in the chain, and
* a nullifier can only be revealed once in the chain.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2631?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
Should we close this one? #2694 seems to say that we're not going to follow this design

**Comment by teor2345** [comment]
> Should we close this one? #2694 seems to say that we're not going to follow this design

That ticket description is outdated - it was based on the initial mempool scope.
Zebra currently rejects spend conflicts in the mempool.

So we should implement this ticket eventually, because it fixes some bugs in our mempool implementation.

**Comment by teor2345** [comment]
I also think we should reset the estimate on this ticket, because a lot of the changes we need are already implemented.
