### ISSUE TITLE
Improve performance of authorizing data commitment

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2632]
## Motivation

https://github.com/ZcashFoundation/zebra/pull/2547/ implements the authorizing data commitment specified in ZIP-244 which is the root of a Merkle tree of the auth digest of each transaction. (`zebra-chain/src/block/merkle.rs`, `FromIterator` for `AuthDataRoot`)

This tree is padded with leaves containing all-zeroes hashes to make the tree full. However that can be expensive.

We can either optimize that by pre-computing the roots of of fully-"empty" subtrees and using that (like note commitment trees do), or by making sure this is only computed once for each block and reused where needed.

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2547/

**Comment by teor2345** [comment]
We can re-open this if it turns up in CPU profiles.
