### ISSUE TITLE
Download mempool-bound transactions, log their `transaction::Verifier` results to stdout prior to mempool storage

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2637]
We can take our block syncer and copy/paste that into a transaction downloader stream, and for a first pass, make sure that all the transcations we download pass  the `TransactionVerifier`, and log the result to stdout.

Later, those passing transactions will be inserted into our mempool via a call to the `MempoolService`

**Comment by teor2345** [comment]
We can also just verify `PushTransaction`s, but I'm not sure how common they are.

**Comment by teor2345** [comment]
We'll need to remove this `unimplemented!` panic as part of this ticket:
https://github.com/ZcashFoundation/zebra/blob/1c232ff5eaf2377376486b15d15fcc80a5622144/zebra-consensus/src/transaction.rs#L149-L152

**Comment by teor2345** [comment]
> We can also just verify `PushTransaction`s, but I'm not sure how common they are.

I just checked using Grafana (#2673), and I didn't see any `PushTransaction` messages sent by peers.
So we'll have to download transactions before we can verify them.

**Comment by teor2345** [comment]
We still need to handle `PushTransaction`, we just can't test using it, because it almost never happens.
