### ISSUE TITLE
Make sure tests are actually run when some of them are selected

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2653]
## Motivation

In some cases we select one or a group of tests to be run. For example, in the .yml files to regenerate the cached state, and in https://github.com/ZcashFoundation/zebra/pull/2633/ to run some tests with fake activation heights.

However, it's possible that renaming these tests can cause the tests to be no longer run, and we could not notice that (since `cargo test` will happily return 0 indicating success even if no tests are run).

Come up with a way to detect if that happens and fail. (For example, we could `grep` the output and check if something has actually run)

### Examples

Here are some example tickets:
- #3673 
- #2402

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2653?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We don't know how to do this easily, we should fix missing tests when they come up.

We could search for "run 0 tests" in the logs.

**Comment by teor2345** [comment]
PR #4710 fixes part of this ticket, but only for a single workflow
