### ISSUE TITLE
Sapling keys and addresses

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#266]
Start by having all the types, so that they can be parsed to and from transactions, but leave implementing the details for later as needed.

![image](https://user-images.githubusercontent.com/552961/75273820-9a7dbd80-57cf-11ea-9ebd-e753f653f887.png)

**Comment by gtank** [comment]
A reference implementation of these can be found in https://github.com/zcash-hackworks/zcash-test-vectors.

The most relevant zcashd issue is probably https://github.com/zcash/zcash/pull/3492

**Comment by dconnolly** [comment]
Related: https://github.com/ZcashFoundation/zebra/issues/267
