### ISSUE TITLE
Zebra panics when git checkout has been modified

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2662]
## Description

Sometimes when I run Zebra with a modified git checkout, it panics with a semver error.

This is probably a bug in how we convert git semver to Rust semver.

TODO <details>

### Steps to Reproduce

I tried this:

[behavior or code sample that causes the bug]

```sh
copy and paste the exact commands or code here
```

### Expected Behaviour

I expected to see this happen: [explanation]

### Actual Behaviour

Instead, this happened: [explanation]

### Zebra Logs

<details>

```
copy and paste the logs here
```

</details>

### Zebra Version

</details>

### Operating System

This behavior might have changed because the `libgit2` crate version is unpinned, or because my version of `git` stores different metadata in `.git`.

```
$ uname -a
Linux ... 5.4.122 #1-NixOS SMP Wed May 26 10:05:21 UTC 2021 x86_64 GNU/Linux`

$ git --version
git version 2.32.0

$ cargo tree | rg git2
    ├── git2 v0.13.17
    │   ├── libgit2-sys v0.12.19+1.1.0
```

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2662?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I've removed this ticket from sprint 17, because I haven't seen it recently

**Comment by teor2345** [comment]
This seems to have been fixed by a `vergen` update.
