### ISSUE TITLE
Split the mempool errors into categories

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#2668]
## Motivation

The mempool errors from #2615 need to be categorized into further enums for better maintenance and usability.

## Related Work
#2615, #2590

**Comment by teor2345** [comment]
I've added this ticket to the mempool tracking issue, and removed it from sprint 17, so we can schedule it when we have time. (And when we know most of the errors we'll have.)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2668?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
After looking at ZIP-401, it looks like we'll still be modifying the mempool errors in sprint 20.

So I've moved this out of the sprints, until we have most of our errors finished off.

**Comment by teor2345** [comment]
This was done in recent PRs, where we removed unused errors, deduplicated mempool errors with storage errors, and split storage errors by retention policy.
