### ISSUE TITLE
Implement ZIP-32 Sapling and Orchard key derivation

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#267]
In order to match what zcashd currently does.

Note: can skip Sprout key derivation, since new Sprout keys are useless, and zcashd never implemented this feature.

![image](https://user-images.githubusercontent.com/552961/78296608-07d1ec00-74fc-11ea-8006-bbab7069f9d5.png)
![image](https://user-images.githubusercontent.com/552961/78296644-18826200-74fc-11ea-9ab2-fc2f217f06be.png)
![image](https://user-images.githubusercontent.com/552961/78296657-1fa97000-74fc-11ea-88e0-cd2f006610a1.png)

https://zips.z.cash/zip-0032

**Comment by dconnolly** [comment]
This is relevant to #265 and #266 work in progress.

**Comment by str4d** [comment]
Note that we haven't actually implemented Sprout HD derivation. We defined it for completeness, but @daira and I are considering removing it, and instead deprecating Sprout address generation in zcashd.

**Comment by str4d** [comment]
That said, if you do want to be able to generate Sprout address, HD generation from the same seed as Sapling addresses makes the most sense.

**Comment by mpguerra** [comment]
What are we missing here? Because I see that both #300 and #301 are done. 

Can we close this one?

**Comment by teor2345** [comment]
Is there any verification-only work left in this ticket for NU5?

We won't need to derive addresses until we start work on zebra-client. And we might not want to generate sprout addresses anyway, because new sprout addresses can't receive any funds. (As of Canopy, transfers into the Sprout value pool are not allowed.)

**Comment by mpguerra** [comment]
Moving this out of the NU5 tracking issue for now

**Comment by mpguerra** [comment]
In #1854 we mention we need to do Orchard validation only for NU5 activation. Do we need to split this out into its own ticket? If so, I would need some help understanding what is required here.

**Comment by teor2345** [comment]
> Note that we haven't actually implemented Sprout HD derivation. We defined it for completeness, but @daira and I are considering removing it, and instead deprecating Sprout address generation in zcashd.

Just confirming we don't have to do sprout key generation.

**Comment by teor2345** [comment]
> In #1854 we mention we need to do Orchard validation only for NU5 activation.

That's not what I meant - I said that there had been a recent orchard update to ZIP-32. I've clarified that comment.

> Do we need to split this out into its own ticket? If so, I would need some help understanding what is required here.

@dconnolly does ZIP-32 require us to do any validation on sapling or orchard addresses for NU5? Or can we just leave key generation to zebra-client?

**Comment by str4d** [comment]
ZIP 32 is only relevant for wallets; it does not affect full node consensus rules.

**Comment by teor2345** [comment]
Great, I'll take it out of NU5 entirely.

**Comment by dconnolly** [comment]
> > In #1854 we mention we need to do Orchard validation only for NU5 activation.
> 
> That's not what I meant - I said that there had been a recent orchard update to ZIP-32. I've clarified that comment.
> 
> > Do we need to split this out into its own ticket? If so, I would need some help understanding what is required here.
> 
> @dconnolly does ZIP-32 require us to do any validation on sapling or orchard addresses for NU5? Or can we just leave key generation to zebra-client?

What @str4d said, not required for NU5 validation, we can leave this for later

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
