### ISSUE TITLE
Transparent keys and addresses

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#268]
We need types for representing transparent addresses and the associated keys. Related to #264.

**Comment by dconnolly** [comment]
> Transparent Private Keys...are encoded in the same way as in Bitcoin [[Bitcoin-Base58](https://en.bitcoin.it/wiki/Base58Check_encoding)], for both the production and test networks.



https://zips.z.cash/protocol/protocol.pdf#transparentkeyencoding

**Comment by dconnolly** [comment]
![image](https://user-images.githubusercontent.com/552961/75284338-98712a00-57e2-11ea-89aa-507f7a14a994.png)


https://zips.z.cash/protocol/protocol.pdf#transparentaddrencoding
