### ISSUE TITLE
ZIP-155: Parse `addrv2` in Zebra

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2681]
## Motivation

[ZIP-155](https://zips.z.cash/zip-0155) will require support for parsing inbound `addrv2` messages.
But nodes can still keep sending `addr` messages.

We'll need to implement `addrv2` parsing in both Zebra (in Rust) and the DNS Seeders (in Go).

This is the ticket for Zebra.

### Scope

Zebra only needs to parse IPv4 and IPv6 in `addrv2`.

Parsing other address types is out of scope - they can be ignored.
Sending `addrv2` is out of scope.

## Deadline

ZIP-155 activates as of the NU5 mainnet activation network protocol version.
(On both mainnet and testnet.)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2681?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
