### ISSUE TITLE
Reject duplicate UTXO spends and nullifier reveals across mempool transactions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2682]
## Motivation

Mempools typically require a consistent set of transactions, which could all be mined into a single block.

In order to support this restriction, Zebra should reject transactions that:
* spend outputs that are already spent by existing mempool transactions
* reveal nullifiers that are already revealed by existing mempool transactions

If we make this change, we should also reject transactions that duplicate spends in recently committed blocks (#2631).

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2682?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn
