### ISSUE TITLE
Sapling/Orchard note encryption implementation.

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#269]
We need an implementation of  note encryption/decryption. This has possible overlap with librustzcash.

Two levels of completion:

All the types to represent in the transaction

Some types:

 sapling::Note (plaintext)
 sapling::OutCiphertext
 sapling::EncryptedCiphertext

And implementing methods to do the note encryption

 NoteEncryptionBuilder

But first:

note commitment trees: #36
addresses
as above, full Note implementation

Related: #181 

Spec references:

https://zips.z.cash/protocol/protocol.pdf#saplingsend
https://zips.z.cash/protocol/protocol.pdf#orchardsend
https://zips.z.cash/protocol/protocol.pdf#saplingandorchardencrypt

Note that ZIP-212 is included in this ticket (it was incorporated into the spec)

**Comment by teor2345** [comment]
@dconnolly does this belong in the "Wallet Support" milestone, or the "Transaction Validation" milestone?

**Comment by dconnolly** [comment]
Wallet support, otherwise we can't send money properly

**Comment by mpguerra** [comment]
Splitting the decryption part that we need for ZIP-212 into #3002

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
