### ISSUE TITLE
Add debug configs for mempool acceptance tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2690]
### Motivation

We might want debug configs that:
* always enable the mempool, regardless of syncer status
* disable mempool transaction validation (or some parts of the validation, like UTXO lookups)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2690?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
