### ISSUE TITLE
Add `zebrad` acceptance tests for the mempool

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2691]
## Motivation

The mempool unit tests cover a lot of mempool functionality, using `MockService`s where needed.

But there are some things we can't test unless we actually run `zebrad`:
- [x] mempool startup from `zebrad`'s `start` command
    - the unit tests already check that the mempool starts disabled
- [x] mempool startup while the rest of `zebrad` is running (covered by PR #2862)
- [ ] mempool running while the rest of `zebrad` is also running
- [ ] The mempool doesn't activate really early (while we're syncing the first few checkpoints)

We've had panics and deadlocks in similar situations before. (Particularly the start command & running everything at the same time.)

So it's important that we run some tests like this.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2691?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
Related: https://github.com/ZcashFoundation/zebra/issues/2690

**Comment by teor2345** [comment]
Unblocked by merging PR #2862.
