### ISSUE TITLE
Use `Poll::map` in the download streams

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2693]
## Motivation

The block sync, inbound block, and transaction downloaders could be simplified using `Poll::map`.

### API Reference

https://doc.rust-lang.org/nightly/std/task/enum.Poll.html#method.map_ok-1

### Design

We could eventually end up with something like:
```rust
ready!(this.pending.poll_next(cx))
    .transpose()
    .map(|join_result| join_result.expect(...))
    .map_ok(|hash| { this.cancel_handles.remove(&hash); hash })
    .map_err(|(e, hash)| { this.cancel_handles.remove(&hash); e })
```

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2693?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I think this issue is actually optional, so I'm going to remove it from this sprint.

**Comment by teor2345** [comment]
This is a cleanup that already has a TODO in the code.
