### ISSUE TITLE
Use property testing for message struct serialization round-trips

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#27]
We should try to use property-based testing (probably `proptest`) for checking that message (de)serialization round-trips.  This has structured input, so in contrast to fuzzing (unstructured input), this is probably less useful for checking that we cannot be vulnerable to malformed messages, but it's probably more useful for checking that the encoding functions actually work.

**Comment by hdevalence** [comment]
@dconnolly is this already done as part of your proptest work?

**Comment by dconnolly** [comment]
> @dconnolly is this already done as part of your proptest work?

No, message roundtrips have not been fully covered by proptests yet.

**Comment by dconnolly** [comment]
The bulk of the message ser/de work is covered by the structs included in those messages, which are fully covered by proptests in zebra-chain.

**Comment by hdevalence** [comment]
@dconnolly just to clarify, this is reopened as an open-to-contributors for anyone who wants to explicitly write out proptests for the message serialization, right?

**Comment by dconnolly** [comment]
> @dconnolly just to clarify, this is reopened as an open-to-contributors for anyone who wants to explicitly write out proptests for the message serialization, right?

Correct, yes. 🙏

**Comment by teor2345** [comment]
We already have some of this, we should open a specific ticket when we change the message format.

Also the Ziggurat tests cover this.
