### ISSUE TITLE
Validate mempool-specific transaction consensus rules

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2707]
## Motivation

Transactions must be validated before being added to the mempool. In https://github.com/ZcashFoundation/zebra/pull/2679 we just call the existing transaction verifier. The only specific check added there is to make sure there aren't coinbased inputs if it's a mempool transaction.

However, there may be other mempool-specific rules that we need to enforce. We should review which of them are already being checked and implement any rules missing, if any.

### Specifications

There isn't any official specification for mempool-specific rules, but https://en.bitcoin.it/wiki/Protocol_rules#.22tx.22_messages seems to be a good reference. It may be also helpful to check what `zcashd` does.

[ZIP 401: Addressing Mempool Denial-of-Service](https://zips.z.cash/zip-0401) might have some useful rules, but it's `zcashd`-specific.

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/pull/2679

**Comment by teor2345** [comment]
I added ZIP-401 to the specs section, added this ticket to the tracking issue, and tweaked the name so it made sense in the tracking issue.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2707?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn

**Comment by mpguerra** [comment]
Quoting @teor2345 from a source external to github:

> We checked the ZIPs and specs for mempool-specific consensus rules. And we're validating the 4 we know about. (Transaction size limit, no coinbase transactions, expiry of transactions in the mempool, and clearing the mempool on network upgrades.)

Anything that we are not validating is therefore an "undocumented mempool transaction validation rule" and as such I will close this issue for now. If we do find any undocumented mempool transaction validation rules we should open a separate issue for each rule that we find.

**Comment by teor2345** [comment]
> > We checked the ZIPs and specs for mempool-specific consensus rules. And we're validating the 4 we know about. (Transaction size limit, no coinbase transactions, expiry of transactions in the mempool, and clearing the mempool on network upgrades.)
> 
> Anything that we are not validating is therefore an "undocumented mempool transaction validation rule" and as such I will close this issue for now. If we do find any undocumented mempool transaction validation rules we should open a separate issue for each rule that we find.

Just for the record, the Bitcoin and `zcashd` mempools cache transactions with missing inputs (orphans), until they can be validated.

For Zebra, we decided on an alternative implementation:
- connect to lots of nodes
- crawl other nodes' mempools periodically
- un-reject transactions with missing outputs when the chain tip block changes
