### ISSUE TITLE
Upgrade Zebra to Rust 2021 edition

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2709]
## Motivation

Rust will have a new 2021 edition in October:
https://doc.rust-lang.org/edition-guide/rust-2021/index.html

Zebra can stay on the 2018 edition, but we might miss out on new features. And some code will be harder to write.

## Tasks

- run the fix command for 2021 edition changes
- configure all crates to use the 2021 edition
    - this also upgrades the cargo dependency resolver to version 2
- ensure compatibility by adding `#[deny(clippy::rust-2021-compatibility)]` to our clippy config in each crate

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2709?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn
