### ISSUE TITLE
Cancel all mempool download and verify tasks when a network upgrade activates

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2710]
## Motivation

When a network upgrade activates, the mempool needs to redo validation with the new consensus rules.

## Design

Tasks can await network upgrade activation using `ChainTipChange::tip_change` and `TipAction::Reset`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2710?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
our approach will depend on what we do for #2374

**Comment by teor2345** [comment]
Currently Zebra:
* clears the mempool storage at network upgrade activation
* fetches transactions from peers using the mempool crawler
* validates those transactions using the new consensus rules using the mempool downloader

So I think the only thing that's missing here is clearing the download and verify queue.

The state send a `Reset` if there is a network upgrade activation.
In PR #2773, we cleared the storage on `Reset`, but not the download queue.

https://github.com/ZcashFoundation/zebra/blob/18acec6849fb09b52962365a35a374449a6364c8/zebrad/src/components/mempool.rs#L249-L254

**Comment by teor2345** [comment]
Edit: actually, it seems like we're missing clearing the download & verify stream
