### ISSUE TITLE
Send mined transaction IDs to the download and verify task for cancellation

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2711]
## Motivation

Zebra needs to remove mined transaction IDs from the mempool download and verify tasks.

## Design

Tasks can await tip changes using `ChainTipChange::tip_change` and `TipAction::Grow`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2711?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
