### ISSUE TITLE
Broadcast `AdvertiseBlock` to peers when we commit a new block

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2712]
## Motivation

Zebra needs to gossip the hashes of newly committed blocks, once it has reached the chain tip.

## Design

Tasks can wait until they are near the tip using `SyncStatus::wait_until_close_to_tip`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebrad/src/components/sync/status.rs#L31-L34

Tasks can await tip changes using `ChainTipChange::tip_change` and `TipAction`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

Both `Grow` and `Reset` variants should result in block gossips.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2712?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
