### ISSUE TITLE
Send mined transaction IDs to mempool storage for removal

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2713]
## Motivation

Zebra needs to remove mined transaction IDs from the mempool, whenever the state tip `Grow`s.

## Design

Tasks can await tip changes using `ChainTipChange::tip_change` and `TipAction::Grow`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

We currently don't have a method on `mempool::Storage` to remove members of the mempool for whatever reason, so that will have to be done to support this.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2713?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by dconnolly** [comment]
Does this conflict with https://github.com/ZcashFoundation/zebra/issues/2682 ? 
Let's close this one in favor of that one

**Comment by teor2345** [comment]
I think the conflict is with #2631 - if we do #2631, this ticket is redundant.
(And #2631 is better, and more similar to existing code like #2682.)

**Comment by teor2345** [comment]
We removed #2631 from the sprint, so we need to add this ticket back in.
