### ISSUE TITLE
Clear the mempool reject list when there is a chain rollback

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2714]
## Motivation

When the best chain fork changes (a rollback), the mempool needs to clear its rejected transaction list, so that validation is redone with the new best chain.

## Design

Tasks can await rollbacks using `ChainTipChange::tip_change` and `TipAction::Reset`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2714?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I think PR #2773 might have already closed this ticket.

The state sends a `Reset` if there is a rollback:
https://github.com/ZcashFoundation/zebra/blob/18acec6849fb09b52962365a35a374449a6364c8/zebrad/src/components/mempool.rs#L249-L254

**Comment by upbqdn** [comment]
PR https://github.com/ZcashFoundation/zebra/pull/2773 implements the behavior described in this ticket.
