### ISSUE TITLE
Upgrade aes from 0.6.0 to 0.7.5

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2717]
## Motivation

Backwards-incompatible change with the use of FF1 from the `fpe` crate to derive diversified Orchard keys:

![image](https://user-images.githubusercontent.com/552961/131559062-81a7a390-8cdd-4f89-8c22-c5b1101d51e9.png)

We should fix this up for Zebra Client support when computing keys for sending/receiving money for Orchard.

## Related Work

https://github.com/ZcashFoundation/zebra/pull/2703

**Comment by mpguerra** [comment]
This is already included in #2952 

Closing as duplicate
