### ISSUE TITLE
Sprout Key Agreement and KDF

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#272]
- [ ] Sprout key derivation test vectors w/ zcashd/librustzcash

Defined in https://zips.z.cash/protocol/protocol.pdf#concretesproutkeyagreement 
![image](https://user-images.githubusercontent.com/552961/77574266-2145b900-6ea8-11ea-93d1-3f82c9577962.png)
and 
https://zips.z.cash/protocol/protocol.pdf#sproutinband
![image](https://user-images.githubusercontent.com/552961/77574161-08d59e80-6ea8-11ea-8ba2-1910c4a67a1e.png)

**Comment by dconnolly** [comment]
Don't need for strict validation, because it's needed to create or validate Sprout transaction memo fields.

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
