### ISSUE TITLE
Clear mempool storage if the syncer starts syncing large numbers of blocks again

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2723]
## Motivation

If large numbers of blocks get synced, Zebra needs to clear the mempool storage and reject list, because:
* previously verified transactions might have become invalid
* previously invalid transactions might have become valid

## Design

Tasks can check if they are behind the tip using `SyncStatus::is_close_to_tip`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebrad/src/components/sync/status.rs#L42-L43

Tasks can await tip jumps using `ChainTipChange::tip_change` and `TipAction::Reset`:
https://github.com/ZcashFoundation/zebra/blob/44ac06775bf6bb77dea06d53a6fc5e04a79baf31/zebra-state/src/service/chain_tip.rs#L313

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2723?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn

**Comment by teor2345** [comment]
@jvff I think PRs #2773 and #2764 might have already closed this ticket:

Here's the code that clears the mempool if the syncer reports large numbers of blocks:
https://github.com/ZcashFoundation/zebra/blob/18acec6849fb09b52962365a35a374449a6364c8/zebrad/src/components/mempool.rs#L155-L167

And we also clear if the state commits more than one block at the same time:
https://github.com/ZcashFoundation/zebra/blob/18acec6849fb09b52962365a35a374449a6364c8/zebrad/src/components/mempool.rs#L249-L254
