### ISSUE TITLE
Make Zebra send `notfound`, and use received `notfound` to finish requests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2726]
## Motivation

`zcashd` and Zebra don't actually need `notfound` messages:
https://github.com/zcash/zcash/blob/e7b425298f6d9a54810cb7183f00be547e4d9415/src/main.cpp#L5632
https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/peer/connection.rs#L115

But Zebra should send `notfound` as much as possible, so that `inv` routing works efficiently.
This also helps with testing #2156.

We might also want to use them for SPV clients - does the Zcash network have any of those?

### Suggested Solution

- send `notfound` so Zebra peers know that we've replied with all the transactions/blocks we have
- make sure Zebra checks for `notfound` when it's waiting for more blocks or transactions (we might already do this)

### Rejected Alternatives

`zcashd` doesn't do this, and it isn't really supported by the protocol.

<details>

- send `notfound` to tell peers when our mempool is empty
  - make Zebra check for `notfound` when waiting for a `MempoolTransactionIds` reply, rather than timing out because there is no reply

</details>

**Comment by teor2345** [comment]
This is required for #2156 - Zebra should send `notfound` as much as possible, so that `inv` routing works efficiently.

**Comment by mpguerra** [comment]
@teor2345 can you please add your estimate to this issue when you get a chance, probably no need to do a planning poker session with the whole team since you're already working on it
