### ISSUE TITLE
Upgrade tokio-util from 0.5.1 to 0.6.9

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2735]
## Motivation

0.6.* changes trait implementations for `tokio::net::TcpStream` breaking our builds:

![image](https://user-images.githubusercontent.com/552961/132060345-7f483234-8c39-47b9-8a00-03c5c1cbaa35.png)

https://github.com/ZcashFoundation/zebra/pull/2732/checks?check_run_id=3507380221

**Comment by mpguerra** [comment]
Do we need to do this one also as part of #2200 ?

**Comment by teor2345** [comment]
> Do we need to do this one also as part of #2200 ?

Yes, tokio-util 0.6.8 depends on tokio 1:
https://crates.io/crates/tokio-util/0.6.8/dependencies

But tokio-util 0.5.8 depends on tokio 0.3.4.
