### ISSUE TITLE
`mempool::init` to kick off crawler, download & verify stream, and return `mempool::Service` and other services

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2737]
## Motivation

Want to abstract the startup work of the mempool in general away from higher layers, allow privileged access by the download+verify stream to the `mempool::Storage` instance while only allowing mediated queries to unpriviledged access via the `mempool::Service` layer.

## Related Work

See `zebra-state::init()` and `zebra-network::init()` for similar patterns.

**Comment by mpguerra** [comment]
@dconnolly do we still need to do this one? I seem to remember you mentioning that @conradoplg had done a bunch of it already elsewhere...

**Comment by dconnolly** [comment]
This may be a defunct ticket now

**Comment by teor2345** [comment]
Yeah I think `Mempool::new()` fulfills this role pretty well already.

Do you mind if we close this ticket?
