### ISSUE TITLE
Add `mempool::Storage::remove()`

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2738]
## Motivation

When a mempool transaction is mined at least, we must be able to remove an otherwise verified and healthy transaction from our mempool storage. 

![image](https://user-images.githubusercontent.com/552961/132255988-9ab9b58d-8eae-423c-ac7b-87c50de6c5b9.png)

**Comment by oxarbitrage** [comment]
Nice to see you already have the test.
