### ISSUE TITLE
Documentation: link to Zebra architecture blog posts in zebrad overview for devs in the book

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2740]
## Motivation

We have a lot of detail in our book about design RFCs and other pages for zebrad, but lack a sort of high-level overview of the design and architecture, its services, how they communicate, etc. A consolidated overview would help new developers understand zebrad it faster.

We can link to some of our existing blog posts (https://www.zfnd.org/blog/a-new-network-stack-for-zcash/) in an overview document, especially as mempool is solidifying and client makes a small addition for the trial note decryption tasks, so the major architecture of zebrad is basically set.

### Specifications

https://www.zfnd.org/blog/a-new-network-stack-for-zcash/
https://www.zfnd.org/blog/futures-batch-verification/
https://www.zfnd.org/blog/decoding-bitcoin-messages-with-tokio-codecs/

**Comment by dconnolly** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2740?planning-poker) with ZenHub @conradoplg @jvff @mpguerra @oxarbitrage @upbqdn

**Comment by conradoplg** [comment]
Here's a graph (dot file) I generated to help me understand the dependencies between services (this is how it looks like after https://github.com/ZcashFoundation/zebra/pull/2741), and that we could add to the docs. If A points to B that means A is used by B (i.e. B has a reference to A). The dotted lines are circular dependencies which are sent back using channels.

```
digraph services {
state;
latest_chain_tip;
state -> chain_verifier;
state -> tx_verifier;
mempool;
state -> inbound;
chain_verifier -> inbound;
tx_verifier -> inbound;
mempool -> inbound [style=dotted];
peer_set -> inbound [style=dotted];
address_book -> inbound [style=dotted];
inbound -> peer_set;
latest_chain_tip -> peer_set;
inbound -> address_book;
latest_chain_tip -> address_book;
peer_set -> mempool;
peer_set -> syncer;
state -> syncer;
chain_verifier -> syncer;
peer_set -> sync_status;
state -> sync_status;
chain_verifier -> sync_status;
}
```

![graphviz](https://user-images.githubusercontent.com/35766/132725921-144071b8-424a-4f9f-9ff7-30c66b451032.png)

[Render online](https://dreampuf.github.io/GraphvizOnline/#digraph%20services%20%7B%0Astate%3B%0Alatest_chain_tip%3B%0Astate%20-%3E%20chain_verifier%3B%0Astate%20-%3E%20tx_verifier%3B%0Amempool%3B%0Astate%20-%3E%20inbound%3B%0Achain_verifier%20-%3E%20inbound%3B%0Atx_verifier%20-%3E%20inbound%3B%0Amempool%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Apeer_set%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Aaddress_book%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Ainbound%20-%3E%20peer_set%3B%0Alatest_chain_tip%20-%3E%20peer_set%3B%0Ainbound%20-%3E%20address_book%3B%0Alatest_chain_tip%20-%3E%20address_book%3B%0Apeer_set%20-%3E%20mempool%3B%0Apeer_set%20-%3E%20syncer%3B%0Astate%20-%3E%20syncer%3B%0Achain_verifier%20-%3E%20syncer%3B%0Apeer_set%20-%3E%20sync_status%3B%0Astate%20-%3E%20sync_status%3B%0Achain_verifier%20-%3E%20sync_status%3B%0A%7D)

**Comment by dconnolly** [comment]
This 

> Here's a graph (dot file) I generated to help me understand the dependencies between services (this is how it looks like after #2741), and that we could add to the docs. If A points to B that means A is used by B (i.e. B has a reference to A). The dotted lines are circular dependencies which are sent back using channels.
> 
> ```
> digraph services {
> state;
> latest_chain_tip;
> state -> chain_verifier;
> state -> tx_verifier;
> mempool;
> state -> inbound;
> chain_verifier -> inbound;
> tx_verifier -> inbound;
> mempool -> inbound [style=dotted];
> peer_set -> inbound [style=dotted];
> address_book -> inbound [style=dotted];
> inbound -> peer_set;
> latest_chain_tip -> peer_set;
> inbound -> address_book;
> latest_chain_tip -> address_book;
> peer_set -> mempool;
> peer_set -> syncer;
> state -> syncer;
> chain_verifier -> syncer;
> peer_set -> sync_status;
> state -> sync_status;
> chain_verifier -> sync_status;
> }
> ```
> 
> ![graphviz](https://user-images.githubusercontent.com/35766/132725921-144071b8-424a-4f9f-9ff7-30c66b451032.png)
> 
> [Render online](https://dreampuf.github.io/GraphvizOnline/#digraph%20services%20%7B%0Astate%3B%0Alatest_chain_tip%3B%0Astate%20-%3E%20chain_verifier%3B%0Astate%20-%3E%20tx_verifier%3B%0Amempool%3B%0Astate%20-%3E%20inbound%3B%0Achain_verifier%20-%3E%20inbound%3B%0Atx_verifier%20-%3E%20inbound%3B%0Amempool%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Apeer_set%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Aaddress_book%20-%3E%20inbound%20%5Bstyle%3Ddotted%5D%3B%0Ainbound%20-%3E%20peer_set%3B%0Alatest_chain_tip%20-%3E%20peer_set%3B%0Ainbound%20-%3E%20address_book%3B%0Alatest_chain_tip%20-%3E%20address_book%3B%0Apeer_set%20-%3E%20mempool%3B%0Apeer_set%20-%3E%20syncer%3B%0Astate%20-%3E%20syncer%3B%0Achain_verifier%20-%3E%20syncer%3B%0Apeer_set%20-%3E%20sync_status%3B%0Astate%20-%3E%20sync_status%3B%0Achain_verifier%20-%3E%20sync_status%3B%0A%7D)

This is awesome! I wonder if we can do a service dependency diagram at a similar high level automatically derived from the codebase, so that we can keep it up to date automatically and embed the result in our `zebra.zfnd.org` docs / rust docs

**Comment by conradoplg** [comment]
> This is awesome! I wonder if we can do a service dependency diagram at a similar high level automatically derived from the codebase, so that we can keep it up to date automatically and embed the result in our `zebra.zfnd.org` docs / rust docs

I think it's doable with https://crates.io/crates/syn, parsing `start.rs`, but I'm not sure if it's worth the effort :thinking: Would be cool though :laughing:

**Comment by mpguerra** [comment]
> Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2740?planning-poker) with ZenHub @conradoplg @jvff @mpguerra @oxarbitrage @upbqdn

We should remove anyone who hasn't yet voted and set the final estimate here, I can't do it because I didn't start the vote... :) @dconnolly can you do the honours?

**Comment by teor2345** [comment]
I'm wondering if we could just link to the blog posts from the book instead?

**Comment by teor2345** [comment]
I'd like to do this task after we've made some more decisions about client support, because they will impact dependencies and architecture.

**Comment by mpguerra** [comment]
> I'm wondering if we could just link to the blog posts from the book instead?

if we do this we should make sure the existing blog posts are going to be migrated to the new website
