### ISSUE TITLE
Document service buffer size

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2743]
In https://github.com/ZcashFoundation/zebra/pull/2718 we created a new service with a buffer size of `20` (https://github.com/ZcashFoundation/zebra/blob/fd418b3bfea4a85cac0f0a75ea37ee52c37bcee5/zebrad/src/commands/start.rs#L73) because the state service uses the same size (https://github.com/ZcashFoundation/zebra/blob/fd418b3bfea4a85cac0f0a75ea37ee52c37bcee5/zebrad/src/commands/start.rs#L60).

We are not sure if this is the right thing to do so we should find out why `20` is a good choice and document this in the code.

**Comment by teor2345** [comment]
This seems like it's not that important.
