### ISSUE TITLE
Add tests for Inbound::Request::PushTransaction and Inbound::Request::AdvertiseTransactionIds

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2745]
In https://github.com/ZcashFoundation/zebra/pull/2727 we added code to handle this 2 mempool requests but we didn't added tests into https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/inbound/tests.rs because we have another in flight PR (https://github.com/ZcashFoundation/zebra/pull/2741) which makes some big changes to this part of the code so we don't want to refactor them after it.

This tests can be added as part of https://github.com/ZcashFoundation/zebra/pull/2741 or in a separated PR.

**Comment by oxarbitrage** [comment]
Will do this after https://github.com/ZcashFoundation/zebra/pull/2741 is merged.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2745?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @upbqdn
