### ISSUE TITLE
Make gcloud zebrad deployments from #main use persistent IPs

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2757]
## Motivation

We have at least two zebrad nodes running at any time that are auto-deployed when code is merged to #main and passes all tests and checks. By default, they get a new ephemeral IP address every time they are restarted. This means they don't stay along long enough at one IP to show up in block explorers such as BlockChair.

We currently deploy using managed groups, which keep the instances up automatically and have other nice management properties. Deploying one instance at a time supports picking a specific IP, we should investigate if we can configure our managed groups to always use persistent IPs or similar.

### Specifications

https://cloud.google.com/sdk/gcloud/reference/compute/instance-templates/create-with-container
https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/create

**Comment by mpguerra** [comment]
we also have #2380 which seems similar

**Comment by teor2345** [comment]
Duplicate of #2380.
