### ISSUE TITLE
Store valid transactions in mempool storage

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#2767]
Making this an issue so we don't forget to actually do this!

**Comment by teor2345** [comment]
@conradoplg just checking what work is remaining in this ticket?
Is it all covered by other tickets like #2650?

**Comment by conradoplg** [comment]
> @conradoplg just checking what work is remaining in this ticket?
> Is it all covered by other tickets like #2650?

Yes, this one can be considered complete after #2650 is done

**Comment by teor2345** [comment]
Since this is a duplicate now, I'm going to close it, and we can do the remaining work in #2650.
