### ISSUE TITLE
Trace mempool

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2768]

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2768?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@mpguerra we already do some tracing in the mempool, so I'm not sure if there is any work we need to do here.

I suggest that we close this ticket, and open tickets when we need specific tracing tasks, like diagnostics or status logging.

**Comment by teor2345** [comment]
I don't think this ticket is specific enough to schedule or work on, we can open specific tickets as needed.
