### ISSUE TITLE
Reject duplicate UTXO spends and nullifier reveals within the same mempool transaction

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2787]
### Motivation

Mempools typically require a consistent set of transactions, which could all be mined into a single block.

In order to support this restriction, Zebra should reject transactions that:
* spend the same output more than once
* reveal the same nullifier more than once

### Specifications

This consensus rule applies to both block and mempool transactions, so we might want to implement it in `transaction::Verifier`.

### Design

zebra-state already checks for double-spends within the same block transaction.
We can move this check to `transaction::Verifier`.

https://github.com/ZcashFoundation/zebra/blob/b714b2b3b623e1e980aac2359d1ffcca2dcfc6a4/zebra-state/src/service/check/utxo.rs#L76-L85

The mempool already checks for double-spends between transactions in `check_spend_conflicts`:
https://github.com/ZcashFoundation/zebra/blob/17f217b360e3ad93e4a53f8f0f52466d542d8b8d/zebrad/src/components/mempool/storage.rs#L159-L168

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2787?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
