### ISSUE TITLE
Implement Sapling note hashing functions

### ISSUE THREAD

**Issue by gtank** [ZcashFoundation/zebra#279]
The *Sapling note commitment tree* depends on
- [x] **5.4.1.8** Mixing Pedersen Hash Function

and Sapling note commitments, themselves, which need
- [x] **5.4.1.7** Pedersen Hash Function
- [x] **5.4.7.2** Windowed Pedersen commitments

These are unrelated to the homomorphic Pedersen commitments used for value commitments, which are described in section 5.4.7.3.

Rust implementations of these primitives should already exist somewhere inside `librustzcash`.

**Comment by dconnolly** [comment]
#334
