### ISSUE TITLE
Update the NU5 testnet Zebra version in ZIP-252

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2795]
### Tasks

- Update https://github.com/zcash/zips/blob/main/zip-0252.rst
- Regenerate the HTML using `make`

**Comment by conradoplg** [comment]
Which versions will we use? My guess is:

Support for NU5 on Testnet will be implemented in Zebra version 1.0.0-alpha.18 , which will advertise protocol version 170014. Support for NU5 on Mainnet will be implemented in Zebra version 2.0.0, which will advertise protocol version 170015.

(or 1.0.0 for Mainnet?)

**Comment by teor2345** [comment]
I think that's correct, @jvff can confirm the `Testnet` version after the release.

We might want to use `1.0.0-beta.1` for `Mainnet`, because Zebra hasn't been audited yet.
(But we don't have to make that decision yet.)

**Comment by teor2345** [comment]
@oxarbitrage or @jvff, did you want to do this task?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2795?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Updated for the latest testnet network protocol versions:

> Support for NU5 on Testnet will be implemented in Zebra version 1.0.0-alpha.18, which will advertise protocol version 170015. Support for NU5 on Mainnet will be implemented in Zebra version 2.0.0, which will advertise the specified mainnet protocol version.

Or we could just give the Zebra versions, and stop repeating network protocol details, because they are already in the spec.

**Comment by daira** [comment]
I will be updating ZIP 252 ~today~ on Friday and will include this.

**Comment by daira** [comment]
Fixed in https://github.com/zcash/zips/commit/d1909fb05a6b9a97645570c7a66f9a623875d803 (the changes were reviewed with @dconnolly).

**Comment by mpguerra** [comment]
LGTM! @ZcashFoundation/zebra-team let's make sure we include all the required changes in our next release (1.0.0-alpha.18)
