### ISSUE TITLE
Auto-deploy testnet instances  on merge to #main,  just as we do mainnet

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2799]
## Motivation

We want to test NU5 functionality in Zebra.

This is a DevOps task.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2799?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This isn't worth doing until ZF and ECC are committed to running a stable testnet.

We also need to fix #1904 first.
