### ISSUE TITLE
Add ecosystem test vectors for message parsing.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#28]
Here are some test vectors from the Zcash ecosystem:

- https://github.com/zcash-hackworks/lightwalletd/blob/master/parser/transaction_test.go

We should integrate them into the test suite.

**Comment by dconnolly** [comment]
Unblocked by #124

**Comment by dconnolly** [comment]
Poll::Pending ➡️ Poll::Ready
