### ISSUE TITLE
Add dev zones for testing DNS seeders

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2812]
## Motivation

There doesn't seem to be any way to test a newly launched ZFND seeder from Zebra.

We'd need to specify its IP address, and the canonical ZFND seeder DNS name, like:
```sh
dig @34.72.199.73 testnet.seeder.zfnd.org
```

But Zebra only uses `tokio`'s basic DNS resolver API.

### Design

We could add `dev.testnet.seeder.zfnd.org` and `dev.mainnet.seeder.zfnd.org` DNS names, so we can test development versions of the seeders before deployment.

(We'd need to change the seeder to serve the `dev.*` zones in addition to `{test,main}net.seeder.zfnd.org`. And then add those zones to our DNS records pointing at a fixed Google Cloud IP.)

## Related Work

Discovered as part of:
- #2797 
- #2804

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2812?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
