### ISSUE TITLE
Make state.finalized.committed.block.height update after checkpoint sync

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2832]
## Motivation

`state.finalized.committed.block.height` metric is not updated in regular sync, just in checkpoint sync.

Checking the code, the checkpoint verifier commits blocks using `Request::CommitFinalizedBlock`  which calls `queue_and_commit_finalized` -> `commit_finalized`  which updates the metrics (and calls `commit_finalized_direct`  to actually commit it).

During regular Sync, `Request::CommitBlock`  is called and then `queue_and_commit_non_finalized` -> `commit_finalized_direct`, i.e. the metrics are not updated.

Not sure if the proper fix is to update metrics in `commit_finalized_direct` instead or make `queue_and_commit_non_finalized`  call `commit_finalized`. I think the first makes more sense considering the parameters of the functions.

**Comment by teor2345** [comment]
> `state.finalized.committed.block.height` metric is not updated in regular sync, just in checkpoint sync.

I think there are a few issues here:
* the checkpoint-specific metrics have confusing names, they should be `state.checkpoint.*`
* the overall verified block metrics have multiple bugs
* we're missing a metric for finalized blocks, regardless of the verifier that was used

I think I fixed all these issues in #2835, but if we can do better, let me know.
