### ISSUE TITLE
Implement Sapling note commitment tree

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#286]
We need a note commitment tree implementation for both Sprout and Sapling, even when checkpointing on Sapling activation, because we need to accumulate the correct tree state up to Sapling activation in order to validate V4 Sprout-on-Groth16 proofs.

We may want to adapt the implementation in librustzcash to fit our needs.

Depends on #273

Related to #36 (Sprout note commitment tree)

**Comment by dconnolly** [comment]
https://github.com/zcash/librustzcash/blob/37270776beb10acd34bdd96dc6a4bb44117cb00a/zcash_primitives/src/merkle_tree.rs

**Comment by yaahc** [comment]
relevant discord conversation: https://discordapp.com/channels/676527656170160146/716086297210650634/728052748238585917

**Comment by dconnolly** [comment]
Depends on https://github.com/ZcashFoundation/zebra/issues/330
Depends on #279

**Comment by dconnolly** [comment]
https://docs.rs/im/15.0.0/im/

**Comment by hdevalence** [comment]
Edited title to distinguish from #289 for the nullifier set.

**Comment by hdevalence** [comment]
Edited title to distinguish from #36
