### ISSUE TITLE
Add mempool metrics related to memory usage

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2869]
## Motivation

It would be good to have metrics that report the memory usage of the mempool. One of these is `zcash.mempool.usage.bytes` that zcashd uses.

However, that's a bit tricky to measure. We can use https://github.com/str4d/memuse but we'd still need to implement a trait for every type used by the mempool, or preferably adding a derive macro to that package.

## Related Work

This is a follow-up to https://github.com/ZcashFoundation/zebra/issues/2626, and was postponed due to additional work required.

**Comment by teor2345** [comment]
We're not planning on adding more metrics soon.
