### ISSUE TITLE
Improve Zebra documentation for beta release

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2870]
## Motivation

For the beta release, we should improve the Zebra documentation (README and Zebra Book) a bit, to make it easier for an end-user to setup and run Zebra.

### Designs

Requirements:
- [ ] The first or second sentence of the README must explain what Zebra does, in terms that most people will understand
- [ ] The README should also explain how Zebra is different from `zcashd`.

Suggestions:

- [ ] The home page / README (Getting Started) and the User Documentation section have similar information, but Getting Started it's a bit more detailed. This can get confusing if the user sees the sidebar and goes directly to the (leaner) User Documentation. Not sure if we should move most of Getting Started to the User Documentation
- [ ] Describe Zebra in more detail (what it does, why does it exists, etc.) in the "About" at the beginning of the home page / README

Some suggestions moved to https://github.com/ZcashFoundation/zebra/issues/2972

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2870?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
