### ISSUE TITLE
ZIP-155: Parse received `addrv2` in the Foundation's DNS seeder

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2882]
## Motivation

[ZIP-155](https://zips.z.cash/zip-0155) will require support for parsing inbound `addrv2` messages.
But nodes can still keep sending `addr` messages.

We'll need to implement `addrv2` parsing in both Zebra (in Rust) and the DNS Seeders (in Go).

This is the ticket for the DNS Seeders.

### Scope

The DNS seeder only needs to parse received IPv4 and IPv6 in `addrv2`.

Parsing other address types is out of scope - they can be ignored.
Sending `addrv2` is out of scope.

### Current Implementation

The DNS seeders are currently using a fork of `btcsuite/btcd`:
- [ ] https://github.com/ZcashFoundation/dnsseeder/blob/master/go.mod#L14
- [ ] https://github.com/ZcashFoundation/coredns-zcash/blob/master/Dockerfile#L20

`btcsuite/btcd` currently disconnects from peers on unknown messages, including `addrv2`:
- https://github.com/btcsuite/btcd/pull/1671
- https://github.com/btcsuite/btcd/blob/master/wire/message.go#L29

Since they're Bitcoin-focused, they're unlikely to implement `addrv2`, because it's not required by Bitcoin. (But it is required in Zcash.)

So we might have to implement `addrv2` in Go ourselves.

### Edge Cases

* the spec requires 64-bit CompactSize, but some bitcoin code has a ~24-bit limit
* we need to consume the bytes for variable-length addresses, even if we ignore them

## Deadline

ZIP-155 activates as of the NU5 mainnet activation network protocol version.
(On both mainnet and testnet.)

**Comment by teor2345** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2882?planning-poker) with ZenHub @conradoplg @dconnolly @oxarbitrage @upbqdn

**Comment by mpguerra** [comment]
Is there anything left to do here? I see both ZcashFoundation/btcd#1 and ZcashFoundation/dnsseeder#14 have merged

**Comment by conradoplg** [comment]
> Is there anything left to do here? I see both [ZcashFoundation/btcd#1](https://github.com/ZcashFoundation/btcd/pull/1) and [ZcashFoundation/dnsseeder#14](https://github.com/ZcashFoundation/dnsseeder/pull/14) have merged

We just need to deploy it, @teor2345 will walk me through the procedure. Not sure if we need to consider that part of the ticket.

**Comment by teor2345** [comment]
We've deployed the new version!
