### ISSUE TITLE
Nullifier Set

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#289]
Seems like this can be generic between Sprout and Sapling?

https://zips.z.cash/protocol/protocol.pdf#nullifierset

**Comment by dconnolly** [comment]
Related to #287, #288

**Comment by yaahc** [comment]
I'm unsure how to proceed on this issue. I've read everything I could find in the spec on nullifier sets but it never really describes how they should be implemented and what properties are important.

I get that nullifiers are derived from the spending key + the p (position?) of the note, and I get that this position is where the note commitment is in the merkel tree. My assumption is that the nullifier set is just a plain ole set, like a `HashSet`, that stores all of the nullifiers. But also the spec says that each treestate has a nullifier set associated with it, which makes me think that we need a set type like https://docs.rs/im/15.0.0/im/struct.HashSet.html that lets us store a reference to the current version of the hash set for each treestate (transaction?) without having to clone the entire HashSet each time.

I have no idea if I'm entirely off base or not, let me know if this sounds right or what I should be doing instead.

**Comment by dconnolly** [comment]
This is mostly going to maintained in our state layer: #902

**Comment by dconnolly** [comment]
Basically all handled by the state layer: https://github.com/zcash/zips/issues/399
