### ISSUE TITLE
Go over all `cargo doc` warnings

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#2892]
When running `cargo doc` documentation for the zebra project is generated however there are a lot of warnings that we should go over and try to fix. Most of them are suggestions to use auto link and missing paths. This is low priority as the the documentation is currently generated with this small issues.

**Comment by oxarbitrage** [comment]
I moved this one to the stable release candidate epic. It will probably be replaced by smaller, specific issues but we should take a look at this before a stable release.

**Comment by teor2345** [comment]
> I moved this one to the stable release candidate epic. It will probably be replaced by smaller, specific issues but we should take a look at this before a stable release.

The Stable Release Candidate is only for starting the audit.

Documentation format issues don't stop us getting the code audited, and this isn't a breaking change, so I moved this to the tech debt and documentation epics.
