### ISSUE TITLE
Treestate type

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#290]
Sprout and Sapling use different hashes but we can be generic over that.

![image](https://user-images.githubusercontent.com/552961/75808622-62d5bf00-5d55-11ea-907f-ee1dbc7244a2.png)

![image](https://user-images.githubusercontent.com/552961/75808732-94e72100-5d55-11ea-8a3b-bcb9f363f05f.png)

![image](https://user-images.githubusercontent.com/552961/75808917-dd9eda00-5d55-11ea-846a-7b7e9bf066d5.png)

https://zips.z.cash/protocol/protocol.pdf#transactions

**Comment by dconnolly** [comment]
We may not want to be generic over the treestate type, since there may be different logic between different zcash versions' treestates.

**Comment by dconnolly** [comment]
This may be already resolved with https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/sapling/tree.rs and  https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/sprout/tree.rs

**Comment by mpguerra** [comment]
@dconnolly I see we have https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/orchard/tree.rs also. Can we close this issue?
