### ISSUE TITLE
Limit the initial crawler demand for outbound peers, based on seed peer connections

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2902]
## Motivation

When Zebra starts up, the crawler task tries to dial `peerset_initial_target_size` peers. This is in addition to the `peerset_initial_target_size` peers from the initial seed peer connection limit.

But we only want `peerset_initial_target_size` initial peers, not `peerset_initial_target_size * 2` initial peers. In PR #2944, this extra demand gets dropped, but it's a small waste of CPU and RAM.

### Suggested Design

Initialize the peer connection count `demand_tx` in `peer_set::initialize` based on the number of connections made in `add_initial_peers`.

### Edge Cases

The initial peer limit counts connection attempts. But the connection limit is for open connections. So we have to count the right thing here.

We should make sure the calculation doesn't underflow and panic.

## Related Work

These tickets might modify the same functions as this ticket:
- #2326

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2902?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The implementation in PR #2944 covers the security issue here.

So this is now a much smaller cleanup ticket, rather than a security ticket.
