### ISSUE TITLE
Update docs to have mini-zebra favicon

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#293]
The main Zebra logo scales poorly to small sizes because the zebra stripes are too fine, so it's hard to use in a favicon (scaling it down hits the nyquist limit). We now have a better favicon, and we should set it in the docs.

**Comment by dconnolly** [comment]
https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#html_favicon_url

**Comment by oxarbitrage** [comment]
What is the icon we should use exactly?

I made a few tests with https://github.com/ZcashFoundation/zfnd/blob/master/images/zebra-favicon-128.png and https://github.githubassets.com/images/icons/emoji/unicode/1f993.png where the latter looks better.

![zebra_favicon](https://user-images.githubusercontent.com/21685097/85067429-0cb34d00-b187-11ea-9e61-a1923e38b6d3.png)

**Comment by dconnolly** [comment]
@hdevalence is this the better favicon? 
https://github.com/ZcashFoundation/zfnd/blob/master/images/zebra-favicon-128.png

**Comment by hdevalence** [comment]
@dconnolly Yes, that's the one with the wider stripes

**Comment by oxarbitrage** [comment]
It looks pretty bad as a favicon imo, check the middle tab of the screenshot.

Do we want to go forward with it ?

**Comment by daira** [comment]
The one with the orange Rust outline (which you can't actually see is a Rust outline at favicon scale) is way too cluttered. The plain zebra head works well IMHO.

**Comment by hdevalence** [comment]
I don't think it's any worse than the Rust favicon, which seems to render fine on a retina display. My preference would be to use the logo we have, and then change it later.  Once we have a favicon working, changing it is just a search and replace.
