### ISSUE TITLE
Speed up zebra-state tests on Windows

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2930]
## Motivation

Sometimes, the zebra-state tests take a long time:

> test result: ok. 72 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 515.36s

https://github.com/ZcashFoundation/zebra/runs/3965592317?check_suite_focus=true#step:10:1949

## Suggested Fixes

We could try to speed them up by:
- reducing the number of proptest cases for slow tests
- compiling tests with optimisations (but keeping debug checks for integer overflow)

## Priority

This is a medium priority, unless it causes repeated CI failures.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2930?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I partly fixed this issue by reducing the proptest iterations to `1` on the slowest builds (macOS, Windows, coverage).

**Comment by teor2345** [comment]
Windows is a low-priority platform, so we might not ever do this.
