### ISSUE TITLE
Add unused seed peers to the AddressBook

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2931]
## Motivation

In #2900, we randomly select 50 seed peers, and drop the rest.

But those peers could be useful to connect to, if the 50 selected peers are down or slow.
(Or if the user configures `peerset_initial_target_size` very low.)

This is a potential usability or reliability issue.

## Suggested Solution

Add the unused peers from `add_initial_peers` to the `address_book`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2931?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
