### ISSUE TITLE
Upgrade tracing to the next major version

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#2953]
## Motivation

`tracing` has a medium-priority security fix:
* advisory: https://rustsec.org/advisories/RUSTSEC-2020-0159
* original issue: https://github.com/chronotope/chrono/issues/499

(Zebra uses UTC, so our direct uses of `chrono` are safe.)

`tracing-error` has a low-priority security fix, because it doesn't actually use the vulnerable API in `thread_local` 1.0:
* advisory: https://rustsec.org/advisories/RUSTSEC-2022-0006.html
* API analysis: https://github.com/tokio-rs/tracing/pull/1858#pullrequestreview-861344519

## Tasks

1. All these tracing crates need to be upgraded together:

Core tracing:
`tracing-subscriber`: https://github.com/ZcashFoundation/zebra/pull/2956
`tracing-error`: https://github.com/ZcashFoundation/zebra/pull/2948

Tracing features:
`tracing-journald`: https://github.com/ZcashFoundation/zebra/pull/2949
`tracing-flame`: https://github.com/ZcashFoundation/zebra/pull/3265
`sentry-tracing`: https://github.com/ZcashFoundation/zebra/pull/3381
`sentry`: https://github.com/ZcashFoundation/zebra/pull/3382
`color-eyre`: https://github.com/ZcashFoundation/zebra/pull/3342, #3343

Optional framework upgrades:
- `abscissa`: `zebrad` has its own `tracing` component, so upgrading `abscissa` is optional
- `gumdrop`: does not depend on `tracing`, should be replaced with `clap` in `abscissa 0.6`

**Comment by teor2345** [comment]
I added this check to the ticket:

Make sure that Zebra's dependency tree only has the upgraded tracing versions, to avoid missed log messages.
(We can use `cargo-tree` to check.)

**Comment by teor2345** [comment]
I updated the ticket for tracing-subscriber 0.3.1, which fixes some build warnings and accidental re-exports.

**Comment by jvff** [comment]
I ran into a few roadblocks trying to update `tracing`. The first issue is that `abscissa-core` hasn't been updated to use the newer version of `tracing-subscriber`, so we'll have to wait for a new release of it. The `master` branch of the [repository](https://github.com/iqlusioninc/abscissa/) has already been [updated](https://github.com/iqlusioninc/abscissa/commit/df52b4daade83c78879a08047396729ca4e2cc84) with the new version of `tracing-subscriber`, but there hasn't been a release with it yet.

The second issue is that the `sentry-tracing` dependency is in the same situation. The `master` branch has been [updated](https://github.com/getsentry/sentry-rust/commit/e0249849446db1f7ddc6e5dd1b0d8777af52b63e), but there hasn't been a release with it yet.

The third issue is that there is no `tracing-flame` release that's compatible with `tracing-subscriber` version `0.3.1`. I tried to work around this by changing the dependency to use the Git repository directly on the `tracing-subscriber-0.3.1` tag, but that split the `tracing` dependency in two, one from crates.io and one from Git. Trying to move all dependencies to the Git version leads to issues with indirect dependencies.

A think a solution to this problem might be to use dependency patching, but I'm not sure if it's worth trying this now or simply delaying this issue.

**Comment by mpguerra** [comment]
I think we should delay until we have all of the required NU5 (and prior) validation in place. Seems like too much effort when there is a lot of other work that is much higher priority than this and definitely needs to get done in the next few sprints

**Comment by jvff** [comment]
Just a note for future reference, I think there might be a simpler solution for the `tracing-flame` issue. If we fork the repository (just the `tracing-flame` sub-directory), we can change its dependencies to use the desired versions from `crates.io` instead of being `path` dependencies. This should prevent Cargo from creating separate dependency trees for the same dependencies, but it would mean we'd have a "temporary repository" until there's a new release of `tracing-flame` that supports `tracing-subscriber` version `0.3.1`.

**Comment by teor2345** [comment]
I'll reschedule this for sprint 25, we can check if the ecosystem has caught up by then.

I'll also add the checks for the crates Janito mentioned to the list of tasks in the ticket.

**Comment by dconnolly** [comment]
https://github.com/ZcashFoundation/zebra/pull/3265
