### ISSUE TITLE
Check block subsidy (miner and founder's reward) rules as part of validation

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#297]
![image](https://user-images.githubusercontent.com/552961/76341799-ea7e7900-62d3-11ea-8528-f8dd5afac025.png)

https://zips.z.cash/protocol/protocol.pdf#subsidyconcepts
https://zips.z.cash/protocol/protocol.pdf#blockchain
https://zips.z.cash/protocol/protocol.pdf#subsidies

See #338 for the specific calculations.

**Comment by teor2345** [comment]
Duplicate of #338.
