### ISSUE TITLE
Fix crawler.rs doctest

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2971]
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/2970/ we temporarily marked the `crawler.rs` doctest as `compile_fail` since it does not compile.

Fix the doctest instead.

This may simply require making the `components` module public, but that will require adding some missing documentation, see https://github.com/ZcashFoundation/zebra/pull/2893

## Related Work

May depend on https://github.com/ZcashFoundation/zebra/pull/2893

**Comment by teor2345** [comment]
It seems like we're getting along fine without this doctest.
