### ISSUE TITLE
Make it easy for users to discover how to configure Zebra

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#2972]
## Motivation

The user documentation can be made more user-friendly. Some suggestions:

- [ ] Make the free disk space requirement more explicit and describe where the state is saved
- [ ] Describe the config options, currently there's just a link to the Rust documentation of the config which is not particularly helpful for end users
- [ ] Make "Zebra Metrics" more user-friendly (i.e. instead of "Zebra has support for Prometheus...", something like "You can obtain Zebra metrics such as ... by using Prometheus which is... "

We might also want to do parts of #1772.

## Related Work

Split from https://github.com/ZcashFoundation/zebra/issues/2870

**Comment by teor2345** [comment]
We should make these changes if users ask for them, or during lightwalletd development.

**Comment by teor2345** [comment]
Duplicate of #5167
