### ISSUE TITLE
Validate that only the first transaction in a block is a coinbase transaction 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#298]
![image](https://user-images.githubusercontent.com/552961/76342227-a2138b00-62d4-11ea-99d9-4e0ad637763f.png)

https://zips.z.cash/protocol/protocol.pdf#coinbasetransactions

We'll need to check:
1. there is at least one transaction in the block
2. the first transaction in the block is a coinbase transaction
3. there are no other coinbase transactions in the block

Checks 1 and 2 are already implemented by `Block.coinbase_height().is_some()`:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/block.rs#L47

We validate blocks in the zebra-consensus `BlockValidator`:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/verify/block.rs#L97

**Comment by teor2345** [comment]
@oxarbitrage you might like to do this ticket, you can start it as soon as you have time.

**Comment by hdevalence** [comment]
Note: after NU3 activation, the consensus rules on coinbase transactions change, so we'll need to handle that.

**Comment by teor2345** [comment]
> Note: after NU3 activation, the consensus rules on coinbase transactions change, so we'll need to handle that.

This ticket is about Coinbase inputs and the "one coinbase transaction per block" rule. That rule doesn't change in Heartwood.

I opened #608 for Shielded Coinbase Outputs, which are allowed by Heartwood ZIP-213:
https://zips.z.cash/zip-0213

**Comment by teor2345** [comment]
Fixed by #593
