### ISSUE TITLE
Use the latest bindgen version in zcash_script and rocksdb

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2981]
## Motivation

Zebra currently depends on 2 different versions of the `bindgen` crate.

If we remove duplicate dependencies, Zebra will compile faster, and its binaries will be smaller.

## Tasks

1. Make `zcash_script` depend on `bindgen >= 0.58` (or `bindgen >= 0.59`)
2. Upgrade to `rocksdb = 0.17.0`
3. Remove the exceptions for these crates in `deny.toml`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2981?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
