### ISSUE TITLE
Upgrade to NU5 testnet 2 versions of librustzcash, zcash_script, orchard, halo2_proofs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2982]
## Motivation

Currently, Zebra and `zcash_script` depend on a git version of the following shared Zcash crates:
- zcash_history
- zcash_primitives
- zcash_note_encryption
- orchard
- incrementalmerkletree
- equihash
- zcash_script

And we depend on pre-NU5 versions of:
- halo2

We need to update to the NU5 testnet 2 versions of these crates.

## Tasks

1. Wait until the `zcashd` team releases 4.7.0, with the NU5 testnet 2 versions of librustzcash and orchard

### halo2_proofs

Try: 

```
halo2 = { package = "halo2_proofs", version = "=0.1.0-beta.2" }
```

"and then you only need to focus on the API changes, not renaming the imports everywhere."

See also [the changelog for `halo2_proofs 0.1.0-beta.2](https://github.com/zcash/halo2/blob/main/halo2_proofs/CHANGELOG.md#010-beta2---2022-02-14) for all of the API changes relevant to this upgrade.

(This was a separate ticket before, for reference:  #3600)

### librustzcash

If https://github.com/zcash/librustzcash/pull/459 got merged:
2. In the next steps, update zcash_script and Zebra to the latest git commit of zcash/librustzcash/master

If https://github.com/zcash/librustzcash/pull/459 is still open:
2. Merge zcash/librustzcash/master into ZcashFoundation/librustzcash/download-sprout-params
3. Tag ZcashFoundation/librustzcash/download-sprout-params as a beta release, so zcash_script and Zebra can depend on it

### zcash_script

4. Upgrade `zcash_script` to the NU5 testnet 2 orchard and librustzcash, removing the git versions in Cargo.toml
5. Revert module structure changes if needed: https://github.com/ZcashFoundation/zcash_script/pull/27
6. Remove the git patches in `zcash_script/Cargo.toml`
7. Merge the upgrade and module structure PRs to `zcash_script/master`
8. Tag a `zcash_script` beta release

### Zebra

9. Upgrade Zebra to the NU5 testnet 2 orchard and librustzcash, removing the git versions in Cargo.toml
10. Upgrade Zebra to the latest version of`zcash_script` (git tag)
11. Remove the exceptions for orchard, librustzcash, and dependencies in `deny.toml`
12. Merge the Zebra upgrade PR along with the PR for ticket #3018

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2982?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
