### ISSUE TITLE
Upgrade to criterion 0.3.5 or later

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2983]
## Motivation

Zebra currently depends on 2 different versions of the `itertools` crate, both via `criterion` 0.3.4.

If we remove duplicate dependencies, Zebra will compile faster, and its binaries will be smaller.

## Tasks

1. Upgrade to criterion 0.3.5, which resolves this duplicate dependency
2. Remove the exceptions for these crates in `deny.toml`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2983?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This will either happen as part of #3115, or it is blocked by a dependency issue.
