### ISSUE TITLE
Remove duplicate owo-colors dependency

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2984]
## Motivation

Zebra currently depends on 2 different versions of the `owo-colors` crate, via:
- zebra-test
- color-eyre

If we remove duplicate dependencies, Zebra will compile faster, and its binaries will be smaller.

## Steps

0. Check that the conflict still exists by removing the `owo-colors` exception from `deny.toml`, then running `cargo deny check bans`.

Downgrade `owo-colors`:
1. Make `zebra-test` depend on `owo-colors >= 1.3.0`

We could upgrade `color-eyre`, but that's out of scope.

**Comment by conradoplg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2984?planning-poker) with ZenHub @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Obsoleted by #3343.
