### ISSUE TITLE
Replace outdated tempdir dependency with tempfile

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#2985]
## Motivation

Zebra currently depends on 2 different versions of the `rand` crate, including an old version via `tempdir`.
The `tempdir` and `rand` dependencies are more than 3 years old.

If we remove outdated dependencies, Zebra will compile faster, its binaries will be smaller, and it will be more secure.

## Tasks

1. Replace `tempdir` with `tempfile::tempdir()`
2. Remove the exceptions for these crates in `deny.toml`

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/2985?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
