### ISSUE TITLE
Implement FromStr for hash types

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#299]
Run through the source and figure out what types it would be useful to have `FromStr` implemented for (e.g., `BlockHeaderHash`, etc), then implement it.

**Comment by hdevalence** [comment]
This is partially done in #311 (`BlockHeaderHash`). Which other hash types should we provide an impl for?

**Comment by dconnolly** [comment]
`TransactionHash`, `SaplingNoteTreeRootHash`, `MerkleTreeRootHash` also exist

**Comment by hdevalence** [comment]
@dconnolly what do you think of the following: add `FromStr` for `TransactionHash`, then whenever we add a nicer `Debug` impl for other hash types, we add a `FromStr` impl for it.

**Comment by dconnolly** [comment]
> @dconnolly what do you think of the following: add `FromStr` for `TransactionHash`, then whenever we add a nicer `Debug` impl for other hash types, we add a `FromStr` impl for it.

Sounds good to me!

**Comment by kiminuo** [comment]
@dconnolly @hdevalence Would the commit above help? 

PS: A macro would make the code shorter but current IDEs are mostly unhappy about them.
