### ISSUE TITLE
Add an address book to track peer information.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#30]
To respond to `getaddr` messages we need to maintain an address book with liveness information about network peers, to be introduced in #23 .

This address book could also be responsible for maintaining ownership of peers or routing requests to and from peers, but it's not clear that that would be the best design (compared to, e.g., handing ownership of peers to the tokio runtime and having it drive them to completion, or using tower to do load-balancing over peers, etc.), so it seems better to leave those tasks for now and have an address book solely responsible for tracking addresses and liveness information.

One idea of how to do this is to create an [async mpsc channel](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/channel/mpsc/index.html) in the addressbook and store a transmission handle to it with each peer, then [use `StreamExt::then`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.18/futures/stream/trait.StreamExt.html#method.then) to hook a timestamp message transmission step into the peer's message stream processing.

**Comment by hdevalence** [comment]
To actually respond to `getaddr` messages, we could have the `AddressBook` implement `tower::Service` (so that the request-for-address-info is handled async), and that logic could perform processing of the returned addresses, for instance truncating their timestamps to prevent clock-inspection attacks (i.e., we could encapsulate the "sensitive" exact timestamps inside the service).

**Comment by dconnolly** [comment]
This is very close to what is implemented in `TimestampCollector` in #17, @hdevalence

**Comment by hdevalence** [comment]
Yep, I think this should be closed, any future enhancements can be new issues.
