### ISSUE TITLE
Upgrade to pin-project 1.0.7 or later

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3000]
## Motivation

Zebra currently depends on 2 different versions of the `pin-project` crate, via `tower-fallback`, and via many other crates.

If we remove duplicate dependencies, Zebra will compile faster, and its binaries will be smaller.

## Tasks

0. Check that the conflict still exists by removing the `pin-project` exception from `deny.toml`, then running `cargo deny check bans`.
1. Upgrade `tower-fallback` to `pin-project` 1.0.7, which resolves this duplicate dependency
    - #2355
2. Remove the exceptions for these crates in `deny.toml`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3000?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This change isn't urgent at all.
