### ISSUE TITLE
Sapling note decryption implementation

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3002]
## Motivation

We need an implementation of sapling note decryption for ZIP-212. 

### Specifications

![image](https://user-images.githubusercontent.com/552961/77574886-10e20e00-6ea9-11ea-99ff-c9600523cf55.png)
https://zips.z.cash/protocol/protocol.pdf#saplingdecryptivk

![image](https://user-images.githubusercontent.com/552961/77574913-1c353980-6ea9-11ea-8842-bc48a1ddb2e5.png)
https://zips.z.cash/protocol/protocol.pdf#saplingdecryptovk

### Designs

We will use librustzcash to implement this for now.

## Related Work

This is related to #271, #2041 and #2362

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
