### ISSUE TITLE
Restore default target output path on Windows CI builds

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3005]
## Motivation

When Tokio was upgraded (#2994), the CI Windows builds started failing due to insufficient disk space. As a temporary workaround, the target output directory was changed to use a separate larger drive (`C:` instead of `D:`). However, it would be best to not have this workaround, and to just optimize the Zebra build to use less disk space.

## Related Work

#2994 introduced the workaround.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3005?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Let's do this after we've resolved most of our duplicate dependencies.
If we do it too soon, the build directory could get big again, and we might have to revert it.

**Comment by dconnolly** [comment]
Not strictly required for release candidate
