### ISSUE TITLE
Security: Use OSRng directly when generating proofs, commitments, and hashes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3012]
## Motivation

In rare circumstances, Rust's `rand::thread_rng()` can provide duplicate random data to different operations.

![image](https://user-images.githubusercontent.com/8951843/140196970-81b8de4d-28f5-4cf0-a7d0-1fe2974a1830.png)

https://hackmd.io/@qedit/zcash-nu5-audit

## Analysis

The OS randomness pool is out-of-scope - that's an issue that needs to be dealt with by the VM or OS software.

Eventually the VM should get enough new entropy and Rust will reseed the RNG, but that's not guaranteed to happen before the next proof. And it only works if we're using `thread_rng()`, or another `ReseedingRng`.

There's a list of other circumstances here.
But Zebra doesn't `fork()`, so we don't need to worry about them.
https://docs.rs/rand/0.8.4/rand/rngs/adapter/struct.ReseedingRng.html

## Solution

We should do what `zcashd` does here, and pay the performance cost of going direct to the `OSRng`, rather than using the caching-and-reseeding `thread_rng()`.

https://docs.rs/rand/0.8.4/rand/rngs/struct.OsRng.html

Then as soon as OSes and VMs handle this scenario correctly, we will get good-quality randomness.

This is required for:
- cryptographic operations, including key generation, signing, and proofs

But not required for:
- network operations, such as randomising peer order

## Rejected Alternatives

Here are some other options, but they have drawbacks:

<details>

A. We should also think about the scenario where the randomness was generated before the VM was cloned.

We could hash a unique identifier for the operation and data we're committing/hashing/proving with the random data. That way, if we're doing something different, we use different (but deterministic) random data for the commitment.

And if the data is the same, we get the same outcome, but that's not a security risk. (As long as we deal with identical data from different operations by prefixing an operation distinguisher.)

But this could significantly complicate some security proofs.

B. We might also want to reseed the `thread_rng()` immediately if the system clock jumps significantly. (That's the best way to detect VM suspend and clone/resume.)

This involves forking `rand`, and submitting a PR upstream.

We should also consider the performance and stability of our clock check here. And how to pick a clock jump interval.

https://docs.rs/rand/0.8.4/rand/rngs/adapter/struct.ReseedingRng.html

</details>

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3012?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is a security edge case.
