### ISSUE TITLE
Validate transparent signature operation limits in blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3015]
## Motivation

Zebra needs to check per-block limits on transparent signature operations.

## Specification

The Zcash limit is:
> `MAX_BLOCK_SIGOPS` does apply to Zcash; it's hard-coded at 20,000, matching pre-SegWit Bitcoin

This limit is applied to the sum of the sigops in lock (output) and unlock (spend) scripts.

https://github.com/zcash/zips/issues/568

Here are the corresponding Bitcoin rules:
https://en.bitcoin.it/wiki/Protocol_rules#cite_ref-4

## Design Notes

We'll need to modify `zcash_script` to return the number of sigops in lock and unlock scripts.
We'll need to validate lock scripts.

## Related Work

This ticket depends on script validation changes in:
- #2388 
- Zebra's existing unlock script implementation

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3015?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
