### ISSUE TITLE
Rollback NU5 testnet 1, and set consensus parameters for testnet 2

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3018]
## Motivation

As part of the `zcashd` mainnet support release, their developers want to change the Orchard circuit on both mainnet and testnet. So we need to rollback testnet to before NU5 activation.

### Specifications

https://zips.z.cash/zip-0252

## Tasks

Consensus parameters:
- change the NU5 testnet consensus branch ID
- change the NU5 testnet activation height

Zebra-specific:
- do a testnet rollback by incrementing Zebra's database version
- update Zebra's current network protocol version - the version scheme has changed
- #2982

Zebra-specific test changes:
- update NU5 and Orchard tests, if needed, including:
    - NU5 block test vectors from the first testnet activation
    - NU5 Orchard shielded data test vectors from the first testnet activation
    - any other tests that fail

**Comment by conradoplg** [comment]
Note that the ZIP-221 history tree, which is stored in state, commits to the consensus branch ID: https://zips.z.cash/zip-0221#tree-node-specification

I guess we'd need to regenerate the state anyway for the rollback, but maybe that warrants also bumping the database version?

**Comment by teor2345** [comment]
> Note that the ZIP-221 history tree, which is stored in state, commits to the consensus branch ID: https://zips.z.cash/zip-0221#tree-node-specification
> 
> I guess we'd need to regenerate the state anyway for the rollback, but maybe that warrants also bumping the database version?

I'll update this part of the ticket to say "database version":
> do a testnet rollback by incrementing Zebra's state version

Every v5 transaction also commits to the consensus branch ID.

**Comment by teor2345** [comment]
I just added "zebra-specific test changes" to this ticket, because the testnet fixes will break some test vectors from the first NU5 testnet activation.

Other tests might also have changed.
