### ISSUE TITLE
Remove founders reward code

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3026]
## Motivation

We have founders reward code (https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/block/subsidy/founders_reward.rs) that we are not using because we checkpoint in Canopy. This code was added to zebra before the Canopy checkpoint was done. 

Right now, we have no validation of founders reward, since Canopy the rewards are in the form of funding streams, these are being implemented in https://github.com/ZcashFoundation/zebra/pull/3017

We need to remove the founders reward code and do the needed clean up.

### Scheduling

This is a quick change that will improve the quality of the audit, because we will avoid auditing unused code.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3026?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
