### ISSUE TITLE
Pull in/wrap Curve25519 for Sprout key agreement

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#303]
![image](https://user-images.githubusercontent.com/552961/76345654-1d2b7000-62da-11ea-8d91-8464338b3d0e.png)

Probably curve25519-dalek

https://zips.z.cash/protocol/protocol.pdf#concretesproutkeyagreement

**Comment by daira** [comment]
Was this ticket intended to include note encryption? I don't see any implementation [here](https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/note_encryption/sprout.rs).

**Comment by daira** [comment]
Oh that's #181. Just pulling in x25519_dalek is sufficient for key agreement. I was confused because the above quote from the spec includes the KDF, which is not done yet.
