### ISSUE TITLE
Loading large JoinSplit parameters in released Zebra binaries

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3038]
## Motivation

The JoinSplit-on-Groth16 parameters are very large, so large that when zcashd is built, they run a [fetch script](https://github.com/zcash/zcash/blob/49ffee3f20b972dc3aa75e422c67523251cf088b/zcutil/fetch-params.sh) to download them first, before compiling them in. We should figure out how Zebra will handle this as part of our build/release process.

### Designs

https://github.com/zcash/zcash/blob/49ffee3f20b972dc3aa75e422c67523251cf088b/zcutil/fetch-params.sh

Alternatives:
- Load dynamically?
- Later in chain sync?
- Inlined in Docker image?

**Comment by teor2345** [comment]
Closed by #3085
