### ISSUE TITLE
Consider implementing `ZcashSerialize` for `PeerServices` wrappers

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3047]
## Motivation

`PeerServices` are serialized as part of other types, but it always has to be converted to the appropriate representation.

In order to centralize where the representation is defined, it would make sense to implement `ZcashSerialize` and `ZcashDeserialize` for each serialized `PeerServices` format:
* `PeerServicesU64`
* `PeerServicesCompactSize64`

Then we can use those wrapper types in types that serialize `PeerServices`.

**Comment by teor2345** [comment]
Wrapper types are required for this change, because there are multiple `PeerServices` serialization formats.
I've updated the description.

See the details here:
https://github.com/ZcashFoundation/zebra/pull/3021#discussion_r746018604
