### ISSUE TITLE
Add zebra-network test where all address book peers are outdated

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3048]
## Motivation

#3030 implemented a filter for outdated peers, so Zebra stops attempting to connect to peers that are likely unreachable. That PR added some unit tests, but it would be useful to have a separate integration test for it.

The integration test should check the following scenarios:
- What does Zebra do if all its peers are outdated?
  - Zebra should keep crawling for new peers
- What does it do if all its peers are outdated, and it has no open peer connections?
  - Zebra should wait for an inbound connection, crawl for new peers, then start connecting to peers again

### Scheduling

This isn't required for the stable release, but it is probably something we should do for lightwalletd.

We should do this test earlier if the issue actually happens on Zebra nodes.

**Comment by ftm1000** [comment]
redistributing issues that can be separately worked from Epic #2311
