### ISSUE TITLE
Tag Zebra 1.0.0-rc.0 stable release candidate

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3050]
Once all of the items in #3096 are completed we will tag our first Zebra 1.0.0 stable release to include all of the NU5 (and prior) consensus rule validation and ensure that Zebra actively contributes to the Zcash network by relaying transactions and blocks.

**Comment by mpguerra** [comment]
@conradoplg you're on the release rotation this sprint... are you ok to tag the release candidate once all outstanding issues are merged?

**Comment by conradoplg** [comment]
> @conradoplg you're on the release rotation this sprint... are you ok to tag the release candidate once all outstanding issues are merged?

Yep, should be fine

**Comment by mpguerra** [comment]
@arya2 and @teor2345 seems like we're ready here. Can you coordinate tagging and releasing today?

**Comment by teor2345** [comment]
> @arya2 and @teor2345 seems like we're ready here. Can you coordinate tagging and releasing today?

Already on it, Arya will do the versions, I will do the changelog
