### ISSUE TITLE
Switch to zcash/orchard now that upstream changes are merged

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3056]
## Motivation

We needed some changes in `orchard` to finish https://github.com/ZcashFoundation/zebra/pull/2645.

Now https://github.com/zcash/orchard/pull/223 is merged, we can switch off our fork back to https://github.com/zcash/orchard

## Related Work

https://github.com/ZcashFoundation/zebra/pull/2645

**Comment by teor2345** [comment]
We expect to have an up-to-date `orchard` for the `zcashd` mainnet support release in the next sprint.

**Comment by dconnolly** [comment]
@conradoplg I think this has been resolved?

**Comment by dconnolly** [comment]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/552961/167953502-b05cfa48-06be-4019-b837-0f7e5b59fcca.png">

**Comment by dconnolly** [comment]
`0.1.0` of orchard is now published, i think we also have to update `zcash_script` against that

**Comment by conradoplg** [comment]
@dconnolly yeah we've been using the original repo for a while (which seems to be what this issue was about) so I think we can close this. In #4335 and #3414 I'll update it to `0.1.0`
