### ISSUE TITLE
Remove duplicate `zcash_proofs` and `sentry` dependencies

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3061]
## Motivation

Zebra currently depends on 2 different versions of the `webpki-roots` crate, via the crates:
* `zcash_proofs` -> `minreq`, and
* `sentry` ->` reqwest`.

One of these versions is over 2 years old.

If we remove outdated dependencies, Zebra will compile faster, its binaries will be smaller, and it will be more secure.

## Tasks

0. Check that the conflict still exists by removing the `webpki-roots` exception from `deny.toml`, then running `cargo deny check bans`.

### Tasks

Minimise dependencies:
1. Fork `zcash_proofs` and `sentry`
2. Upgrade to the latest `webpki-roots`
3. Make Zebra depend on our forked versions
4. Submit PRs upstream
5. Remove the exceptions for these crates in `deny.toml`

**Comment by str4d** [comment]
`minreq` should only be in your dependency tree if you have the `download-params` feature flag of `zcash_proofs` enabled.

As for it being out of date, currently `zcash_proofs` specifies ` minreq 2`, so cargo should be able to select the most recent version of it (2.4.2 from five months ago).

**Comment by teor2345** [comment]
> `minreq` should only be in your dependency tree if you have the `download-params` feature flag of `zcash_proofs` enabled.

We enable `download-params` so that we can download parameters using `zcash_proofs`.

> As for it being out of date, currently `zcash_proofs` specifies ` minreq 2`, so cargo should be able to select the most recent version of it (2.4.2 from five months ago).

Thanks, I've removed the "upgrade `minreq` version" tasks.

`minreq` 2.4.2 has a really outdated `webpki-roots` dependency. But Web PKI is not required for either `zcash_proofs` or `sentry`, so we can just turn those optional dependencies off.

**Comment by teor2345** [comment]
These dependency upgrades should sort themselves out eventually.
