### ISSUE TITLE
Upgrade to the latest redjubjub

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3063]
## Motivation

Zebra currently depends on 2 different versions of the `jubjub` crate.

If we remove outdated dependencies, Zebra will compile faster, its binaries will be smaller, and it will be more secure.

## Tasks

0. Check that the conflict still exists by removing the `redjubjub` exception from `deny.toml`, then running `cargo deny check bans`.

Upgrade versions:
1. Publish a new `redjubjub` version
2. Make Zebra depend on the updated version
3. Remove the exceptions for these crates in `deny.toml`.

**Comment by conradoplg** [comment]
It seems we're only using one version now

**Comment by teor2345** [comment]
> It seems we're only using one version now

If it happens again with the Orchard upgrade, we can fix it at that point.

How does this interact with moving the checks from redjubjub to Zebra (#3154)?

**Comment by conradoplg** [comment]
> > It seems we're only using one version now
> 
> If it happens again with the Orchard upgrade, we can fix it at that point.
> 
> How does this interact with moving the checks from redjubjub to Zebra (#3154)?

Ah you're right, sorry, after that is done (i.e. we change `zebra-chain` to use `https://github.com/ZcashFoundation/reddsa`), we will have two different versions unless `orchard` updates it too (which will eventually happen).

So basically this ticket is:

- Update `redjubjub`
- Remove the exception from `deny.toml` after `orchard` updates it too

Arguably those are different things, but it's better to just wait for now and split the ticket later if needed.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3063?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> after that is done (i.e. we change `zebra-chain` to use `https://github.com/ZcashFoundation/reddsa`), we will have two different versions unless `orchard` updates it too (which will eventually happen).

The `zebrad` team have scheduled a 4.6.0 release before the end of 2021, they plan on tagging beta versions of all their crates as part of that release.

So we should be able to:
> Remove the exception from deny.toml after orchard updates it too

during the first sprint of 2022.
