### ISSUE TITLE
Change block header parsing to relax version requirements.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#308]
#307 fails because one block has a bad version field. The spec says that the only defined version for Zcash blocks is 4; apparently this does not mean that the only *allowed* version is 4.  Per https://github.com/ZcashFoundation/zebra/issues/307#issuecomment-597287298 we should check that the high bit is unset and allow any random number to be included in the `version` field.  This seems like it makes the `version` field useless for actually controlling the block version.

**Comment by str4d** [comment]
The version field does have a modicum of constraint, specifically, `nVersion >= +4`:

https://github.com/zcash/zcash/blob/2a6be9fd197bf29f92d1ada748bc2dbd19c3040c/src/main.cpp#L3767-L3770

https://github.com/zcash/zcash/blob/63c3d1ec9435b445a883028b9111595ffa9292d4/src/consensus/consensus.h#L11-L12

> This seems like it makes the version field useless for actually controlling the block version.

Correct! At best it can currently only indicate "standard interpretation".

**Comment by hdevalence** [comment]
not sure why this didn't get autoclosed
