### ISSUE TITLE
Consider refactoring transaction verifier tests to be property tests

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3083]
## Motivation

The `zebra-consensus` transaction verifier has many test vectors. They share some common boiler plate code to find a suitable transaction and to call the verifier. It would be interesting to try to refactor some of them in order to try to reduce the amount of test code and run with a larger set of inputs, by:

- collecting common behavior in helper functions
- using property tests with customized transaction generation strategies
- joining tests that have the same assertions but have different inputs into a single property test, with an `enum` or a test strategy to select between the inputs
- creating helper types to prepare valid input for the transaction verifier

### Designs

One thing I started experimenting on was a `transparent::MockTransfer` type that implements `Arbitrary`. This type could then help with the creation of a source UTXO, its output in a (mock) transaction, and an input to spend it. The idea was to use this in property tests as a replacement for test vectors that use the `mock_transparent_transfer` helper function.

## Related Work

I initially thought of this while trying to write property tests instead of test vectors for #3060.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3083?planning-poker) with ZenHub @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn @conradoplg
