### ISSUE TITLE
Upgrade blake2b and blake2s dependencies

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3094]
## Motivation

We want to update our blake2s_simd and blake2b_simd dependencies to a later version. However we want to wait until orchard, librustzcash, and bellman update their own blake2s_simd dependency to avoid creating a duplicate `blake2` dependency tree 

## Related Work

See https://github.com/ZcashFoundation/zebra/pull/3088#pullrequestreview-812819347
and https://github.com/ZcashFoundation/zebra/pull/3086#pullrequestreview-812814725

**Comment by conradoplg** [comment]
I'll close this since this should happen naturally when those dependencies are updated.
