### ISSUE TITLE
Stop panicking if a connection has multiple failures

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3109]
## Motivation

Currently, Zebra panics if a connection has multiple failures.

In #1610, we describe a complicated refactor that would stop Zebra having multiple failures on the same connection. But this refactor could introduce other bugs.

There's a much simpler solution that avoids the panics.

## Suggested Solution

- [x] if multiple errors happen, log an info-level message instead of panicking

### Rejected Solutions

- ~~close both the inbound and outbound channels in `fail_with`~~
    - ~~check how those closed channels are eventually handled (they should not panic, debug logs are ok)~~
    - closing a sink is an async operation, because it flushes, so we should just drop it
    - generic streams can't be closed

## Related Work

We'll remove some kinds of connection errors in #2107

This ticket obsoletes #1610

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3109?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
