### ISSUE TITLE
Cache unsolicited Peers responses until needed

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3110]
## Motivation

Zebra currently drops unsolicited `Peers` responses. `zcashd` sends an `Peers` response soon after the connection opens, then it ignores `Peers` requests for a long while.

This network protocol mismatch sometimes makes Zebra hang on startup, or sync really slowly.

### Specifications

This behavior is unspecified.

### Suggested Solution

- Cache the latest unsolicited `Peers` response in each connection
- When Zebra sends a `Peers` request, consume and return the cached response. If there's no cached response, send a `getaddr` message to the peer, and wait for the response.

## Related Work

#1892 has some other ideas for getting better addresses, but they're less important than this ticket

This change blocks #2325 

This change is part of #704

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3110?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
