### ISSUE TITLE
Disable circuit parameter preloads in `zebrad` acceptance tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3112]
## Motivation

Every `zebrad` instance preloads 1 GB of Sprout and Sapling parameters, so they are ready when it does full transaction validation.

But the `zebrad` acceptance tests only load checkpointed blocks, so these preloads just slow down CI.

### Suggested Fix

- [ ] Add a `debug_skip_parameter_preload` option to `zebra-consensus`
- [ ] Set it to `true` when the parameters aren't used:
    - in acceptance tests
    - when rebuilding the cached state (we don't save the downloaded parameters)
    - in any calls to `zebra_consensus::init` in unit tests
- [ ] Keep it at `false` when the parameters are used:
    - by default in `zebrad start`
    - when using the cached state to sync past `Canopy`
    - in any calls to `zebra_consensus::init` in unit tests that verify Sprout or Sapling proofs

## Related Work

Follow-up to #3085

**Comment by teor2345** [comment]
Scheduling this for sprint 25, because it contributed to a CI failure:
> test activate_mempool_mainnet ... FAILED
>     0: stdout of command did not contain any matches for the given regex
> "stopping at configured height"

https://github.com/ZcashFoundation/zebra/runs/4400724206?check_suite_focus=true#step:14:1727

**Comment by teor2345** [comment]
And another CI failure:
https://github.com/ZcashFoundation/zebra/runs/4408845461?check_suite_focus=true#step:14:1235

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3112?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
