### ISSUE TITLE
Support batch verification of JoinSplit Groth16 proofs

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3127]
## Motivation

For https://github.com/ZcashFoundation/zebra/issues/322 we added JoinSplit on Groth16 verification, but without batch support. The reason for this is that `zcash_proofs` does not return the verification key in a format suitable for batching (we need a `VerificationKey`, and not a `PreparedVerificationKey`).

Add support to batch verification, probably by submitting a PR to `zcash_proofs` to make it return the JoinSplit Groth16 verification key as required. See [discussion](https://discord.com/channels/809218587167293450/876655911790321684/913565458760892426)

## Related Work

Follow up to https://github.com/ZcashFoundation/zebra/issues/322

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3127?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
I believe this is is nice-to-have but not that important right now:

- I suspect most JoinSplits are pre-Canopy and thus don't need to be verified due to the checkpoint verifier
- The performance gain with the remaining JoinSplits won't be too great since there won't be too many of them.

I'm not 100% sure though. In any case it seems this could be moved out of the sprint if needed.

**Comment by teor2345** [comment]
> * I suspect most JoinSplits are pre-Canopy and thus don't need to be verified due to the checkpoint verifier

If we want to skip even more JoinSplits, we can increase the default checkpoint height to just before NU5 activation. (So we don't have to worry about the testnet NU5 rollback.)

**Comment by conradoplg** [comment]
Tracked in https://github.com/ZcashFoundation/zebra/issues/3153. Can be done if we detect it's a bottleneck.
