### ISSUE TITLE
`UnreadyService` ignores dropped cancel handles

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3130]
## Motivation

The `UnreadyService` allows the request in flight to be cancelled through a `oneshot` channel. However, if the cancel handle (the `oneshot::Sender` endpoint) is dropped, the request isn't cancelled. This can lead to bugs and requests being kept executing when they should have been cancelled.

## Alternatives

1. It might make sense to replace the "cancel handle" with some sort of `LiveGuard` type, that automatically signals that the request should be cancelled in its `Drop` implementation.

2. We could also check for `Err(Canceled)` in the existing code:
https://github.com/ZcashFoundation/zebra/blob/b1acdc61b4791baed5909809e860099ef6782597/zebra-network/src/peer_set/unready_service.rs#L40

## Related Work

Teor uncovered this issue while reviewing #3108.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3130?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
