### ISSUE TITLE
Epic: Zebra as a lightwalletd backend

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3134]
We want to enable Zebra to act as a lightwalletd backend. In order to do this we will need to expose the minimal subset of JSON-RPC methods required by a lightwalletd server.

This epic will be used to keep track of the items we need to implement to achieve that goal.

## Getting started

zcashd's JSON-RPC interface is mainly JSON-RPC-v1. We plan to use the `jsonrpc_core` Rust crate, because it's compatible with both v1 and v2.

### RPC listener port

We need to:
- [x] #3140
- [x] #3141
    - Example: [Zebra's metrics configuration](https://doc.zebra.zfnd.org/zebrad/config/struct.MetricsSection.html#fields)
- [x] #3165

[`zcashd`'s RPC port](https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html?highlight=rpc#json-rpc-options) has a lot of features, but they are out of scope for Zebra.

### Fixed Value RPC method

- [x] #3142
- [x] #3510

## Other Light Wallet RPC methods

The following [`zcashd` JSON-RPC calls](https://zcash.github.io/rpc/) are used by `lightwalletd`. There is a [list of RPC methods in the `lightwalletd` README](https://github.com/zcash/lightwalletd#zcashd).

We also need to create acceptance tests for each RPC method.

#### Block Chain RPC methods

- [x] #3159
    - [x] #3511 
- [x] #3143
- [x] #3144
- [x] #3156
    - [x] #3563

#### Transparent output address index RPC methods

These tickets use the database changes in #3150, but if they aren't finished, we can just return an empty list:

- [x] #3157
- [x] #3147
- [x] #3158

### State & Mempool Transaction RPC methods

- [x] #3145

### Mempool-Only RPC methods

- [x] #3160
- [x] #3146
    - [x] #3512

## Internal Zebra Changes

The current database design is:
- https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

The draft database design was merged in:
- [x] #3137

### Make transaction database more efficient

To get good `lightwalletd` performance, we need to make some changes to our database:
- [x] #3151
- [x] #3152

This is needed to:
- provide address RPC results, and
- provide good wallet performance

### Add transparent output address database index

We also need to add extra indexes for transparent output addresses:
- [x] #3148
- [x] #3149
- [x] #3950
- [x] #3951
- [x] #3952
- [x] #3953

### Add chain tip estimate calculations to zebra-state

- [x] #3161

## Infrastructure / Testing 

- [x] #3510
- [x] #3545
    - [x]  #3511

## Optional Changes

We don't know if these changes are required yet.

<details>

### Further Performance Improvements

- [x] #3138, if needed to improve performance

### Handling user-generated transactions

- [x] #3242, if needed to improve reliability (we could just put the transaction in our mempool instead)

</details>

## Out of Scope

These changes are not required, because the fields are not used by `lightwalletd`:

<details>

- store the total chain work in the database
- estimate the current verification progress
- get block and transaction data size from RocksDB
    - "rocksdb.estimate-live-data-size"
    - https://docs.rs/rocksdb/0.17.0/rocksdb/struct.DBWithThreadMode.html#method.property_int_value_cf

</details>

**Comment by teor2345** [comment]
> We plan to use [tonic](https://github.com/hyperium/tonic) as our RPC framework.

tonic supports gRPC by default, but `zcashd` uses JSON-RPC.

I updated the ticket to add [tonic-rpc](https://github.com/adamrk/tonic-rpc#encodings), which supports JSON-RPC.

The other advantage of `tonic-rpc` is that we can write our RPCs in Rust, rather than using protobuf definitions.

**Comment by teor2345** [comment]
I removed [tonic](https://github.com/hyperium/tonic) and [tonic-rpc](https://github.com/adamrk/tonic-rpc#encodings) as the preferred option, because they provide gRPC encoded as JSON, not JSON-RPC.

Other async JSON-RPC alternatives are:
- https://github.com/paritytech/jsonrpsee/blob/master/examples/http.rs
- https://docs.rs/tetsy-jsonrpc-http-server/latest/tetsy_jsonrpc_http_server/

But they are harder to use, because they declare RPC methods as closures.

**Comment by teor2345** [comment]
@ftm1000 this is the big pile of tasks that are related to `lightwalletd`.

The essential tasks are listed in the ticket, so we should create a new epic with just those tasks.

We also left some security issues until the lightwalletd work. But we should create a separate epic for them, so it's easier to see the essential tasks.

**Comment by mpguerra** [comment]
We're trying to reduce the number of Epics we have so we can just clean up this one and move the non-essential tasks to a github tracking issue instead. 

For the security issues I'm not sure that these should be an Epic unless we are planning to schedule them in the roadmap as a high level goal to complete over a number of sprints after the lightwalletd work. For anything that doesn't have a discrete start and end date we should probably just use github tracking issues instead, i.e a task list of issues as in #3125.

**Comment by teor2345** [comment]
> For the security issues I'm not sure that these should be an Epic unless we are planning to schedule them in the roadmap as a high level goal to complete over a number of sprints after the lightwalletd work. For anything that doesn't have a discrete start and end date we should probably just use github tracking issues instead, i.e a task list of issues as in #3125.

That sounds good.

We should decide which security issues represent a large risk for lightwalletd servers, and schedule them in an epic after lightwalletd is feature-complete. (I expect there might be 1-5 of these.)

And if any of the fixes will change the API or performance, we might want to put them in the lightwalletd epic itself. (I expect there might be 0-2 of these.)

**Comment by mpguerra** [comment]
Closing this one!!! Great job everyone! 👏 🎉
