### ISSUE TITLE
Add a JSON-RPC listener port and listener component

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3140]
## Motivation

`zcashd`'s JSON-RPC interface is mainly JSON-RPC-v1, but with error handling backported from JSON-RPC-v1.1.

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

It is async and uses `hyper`, which Zebra already uses.

### Example Code

Here are examples of:
* [setting up a HTTP JSON-RPC server](https://github.com/paritytech/jsonrpc#basic-usage-with-http-transport)
* [re-using an existing tokio executor](https://paritytech.github.io/jsonrpc/jsonrpc_http_server/struct.ServerBuilder.html#method.threads)
* [configuring compatibility with JSON-RPC v1 and v2](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/struct.IoHandler.html#method.with_compatibility)
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

### Tasks

- set up the listener port component
- make sure it works with `lightwalletd`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3140?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
