### ISSUE TITLE
Make the JSON-RPC listener port configurable

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3141]

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3141?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @teor2345 @upbqdn @oxarbitrage

**Comment by teor2345** [comment]
This is going to close with PR #3589, so I put it in the same sprint as ticket #3140.
