### ISSUE TITLE
getinfo JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3142]
## Motivation

`lightwalletd` uses the `getinfo` JSON-RPC method.

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getinfo.html

But only the following fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L91

Field list:
```
{
  "build": xxxxx,           (string) `zcashd`'s CLIENT_BUILD
  "subversion": xxxxx,   (string) Subversion as sent to the P2P network in `version` messages - `zcashd`'s CLIENT_NAME, CLIENT_VERSION, uacomments
}
```

### Tasks

- Implement the RPC method
    - build: `app_version()`
    - subversion: `USER_AGENT`
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)
* [testing RPC methods](https://github.com/paritytech/jsonrpc/blob/master/derive/examples/client-local.rs)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3142?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
I think it will make sense to put the `app_version()` function we need (currently in zebrad) in the new crate `zebra-node-services` of https://github.com/ZcashFoundation/zebra/pull/3626

So this is partially blocked by that, however the PR that creates the crate should be merged soon and some work can be advanced without it so i will not tag this as blocked.

**Comment by teor2345** [comment]
> I think it will make sense to put the `app_version()` function we need (currently in zebrad) in the new crate `zebra-node-services` of #3626

`app_version()` returns the version of the `zebrad` cargo package or git, so it can't be moved to another crate. (The other crate's version could be different.)

We could pass `app_version().to_string()` to `RpcServer::spawn`, and store the string in `RpcServer`?

**Comment by oxarbitrage** [comment]
Oh, I did not think on that, thanks!

> We could pass app_version().to_string() to RpcServer::spawn, and store the string in RpcServer?

Yea, i think this is doable. Thanks again.
