### ISSUE TITLE
getblockchaininfo JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3143]
## Motivation

`lightwalletd` uses the `getblockchaininfo` JSON-RPC method.

### Dependencies

- [x] #3161

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getblockchaininfo.html

But only the following fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L70

Field list:
```
{
  "chain": "xxxx",        (string) current network name as defined in BIP70 (main, test, regtest)
  "blocks": xxxxxx,         (numeric) the current number of blocks processed in the server
  "bestblockhash": "...", (string) the hash of the currently best block
  "estimatedheight": xxxx,  (numeric) if syncing, the estimated height of the chain, else the current best height
  "upgrades": {                (object) status of network upgrades
     "xxxx" : {                (string) branch ID of the upgrade, in lowercase hexadecimal
        "name": "xxxx",        (string) name of upgrade - unused by `lightwalletd`, but useful for debugging
        "activationheight": xxxxxx,  (numeric) block height of activation
        "status": "xxxx",      (string) status of upgrade: disabled/pending/active
     }, ...
  },
  "consensus": {               (object) branch IDs of the current and upcoming consensus rules
     "chaintip": "xxxxxxxx",   (string) branch ID used to validate the current chain tip, in lowercase hexadecimal
     "nextblock": "xxxxxxxx"   (string) branch ID that the next block will be validated under, in lowercase hexadecimal
  }
}
```

The `zcashd` code that generates the network upgrade JSON is here:
https://github.com/zcash/zcash/blob/6cd5b8792bbe0a3cc1064e1884914415f0c6e7d7/src/rpc/blockchain.cpp#L970

The `lightwalletd` code that parses the network upgrade JSON is here:
https://github.com/adityapk00/lightwalletd/blob/c1bab818a683e4de69cd952317000f9bb2932274/common/common.go#L195

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3143?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn @jvff

**Comment by oxarbitrage** [comment]
I am unsure about the `consensus` object data regarding what should we return there.

I tried to get info from zcashd and i get all `00000` in that fields, however it was a not in sync chain. Anyone know what is the data that goes there ?

**Comment by teor2345** [comment]
> I am unsure about the `consensus` object data regarding what should we return there.
> 
> I tried to get info from zcashd and i get all `00000` in that fields, however it was a not in sync chain. Anyone know what is the data that goes there ?

`consensus` contains the `ConsensusBranchId` of the current tip block and the next block.

Something like:
```rust
let next_block_height = (height + 1).expect("valid chain tips are a lot less than Height::MAX");

consensus.chaintip = NetworkUpgrade::current(network, height).branch_id();
consensus.nextblock = NetworkUpgrade::current(network, next_block_height).branch_id();
```
