### ISSUE TITLE
getblock JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3144]
## Motivation

`lightwalletd` uses the `getblock` JSON-RPC method.

`lightwalletd` caches all the blocks from Sapling activation, asking for them in height order.

So this RPC needs to be fast:
- #3152 

### NU5 & Orchard

`lightwalletd` implemented NU5 & Orchard changes here:
- https://github.com/zcash/lightwalletd/pull/367
- https://github.com/zcash/lightwalletd/pull/371
- https://github.com/zcash/lightwalletd/pull/372

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getblock.html

`lightwalletd` only uses `height` and `verbosity = 0` as arguments.

And only the following fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L232

Field list:
```
"data"             (string) A string that is serialized, hex-encoded data for the block.
```

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3144?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
