### ISSUE TITLE
getrawtransaction JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3145]
## Motivation

`lightwalletd` uses the `getrawtransaction` JSON-RPC method in response to wallet queries.

So this RPC needs to be fast:
- #3151
- #3152 

### Assumptions

`lightwalletd` doesn't need witnessed mempool transaction IDs for Orchard (`UnminedTxId`).
https://discord.com/channels/809218587167293450/809250822579028008/943326658042163270

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getrawtransaction.html

`lightwalletd` uses these arguments:
- `txid` and `verbosity = 0`: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L431
- `txid` and `verbosity = 1`: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L247

And only these fields are used by `lightwalletd`:
* hex, height: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L117
* unmined transaction height: https://github.com/zcash/lightwalletd/blob/83bb19918fb36a5f6d5013fba7938daf3d73db1d/walletrpc/service.proto#L39

Field list:
```
{
  "hex" : "data",       (string) The serialized, hex-encoded data for 'txid'
  "height" : n,             (numeric) The block height of the transaction in the best chain, or -1 if not in the best chain
}
```

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3145?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@ftm1000 @conradoplg this ticket doesn't depend on the transaction database indexes.

It will perform poorly until we do #3151, but it should be ok for testing.
