### ISSUE TITLE
sendrawtransaction JSON-RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3146]
## Motivation

`lightwalletd` uses the `sendrawtransaction` JSON-RPC method.

### Design Decisions

`zcashd` puts the transaction in its mempool, so Zebra should do the same thing.

What should we do if we think the transaction is invalid?
- log it at warning level
- If Zebra rejects a transaction that `zcashd` accepts, that's a bug in Zebra we need to fix

Zebra doesn't implement pending transactions in the mempool, so the transaction can't depend on another mempool transaction.

### Required Fields

The method is documented here: https://zcash.github.io/rpc/sendrawtransaction.html

`lightwalletd` only uses `hexstring` (raw transaction data) as an argument: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L302

Field list:
```
"hex"             (string) The transaction hash in hex - ignored by `lightwalletd`?
```

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd`
- Test with transactions that get split across multiple TCP packets - use a max-sized transaction

We need to test with large transactions because our JSON protocol fixes operate on each packet.

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

## Out of Scope

`lightwalletd` seems to do some weird error handling, but this is out of scope for Zebra: https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L308

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3146?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
