### ISSUE TITLE
Get addresses from transparent outputs in zcash_script

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3148]
## Motivation

`lightwalletd` uses the `getaddresstxids`, `getaddressbalance`, and `getaddressutxos` RPCs.

These RPCs return the transparent address that receives funds from a transparent output:
- #3150 

### `zcashd` Implementation

Here is how `zcashd` gets the output addresses using `out.scriptPubKey.AddressHash()`, and builds its address indexes:
- https://github.com/zcash/zcash/blob/c76b756a688bfa0a4396a45355814cdc9f9a47e3/src/main.cpp#L3232

`zcash_script` needs to return the same addresses for:
- the provided cached parsed transaction, and
- the provided transaction data.

### Example Code

The new functions are similar to the SigOps functions in:
https://github.com/zcash/zcash/commit/31bd2ba4f1f85814c34c252a198906875c8df8cb

Something like:
```c++
uint160 zcash_script_transparent_output_address(tx, nOut, ...) {
    // parse tx if needed

    if nOut >= tx.number_of_transparent_outputs {
        // set the error to "invalid output index"
        return INVALID_ADDRESS;
    }

    const CTxOut &out = tx.vout[nOut];
    CScript::ScriptType scriptType = out.scriptPubKey.GetType();
    if (scriptType == CScript::UNKNOWN) {
        // set the error to "invalid script"
        return INVALID_ADDRESS;
    }

    // set the error to "no error"
    return out.scriptPubKey.AddressHash();
}
```

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3148?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
@teor2345 could you please add more details to what is required here? What I deduced is that we need to add a new function to `zcash_script` that receives an output and returns the address from it. Is that correct?

**Comment by teor2345** [comment]
> @teor2345 could you please add more details to what is required here? What I deduced is that we need to add a new function to `zcash_script` that receives an output and returns the address from it. Is that correct?

`zcash_script` operates on transactions, so we want to pass the transaction and the transparent output index. Then we want to do the same thing `zcashd` does to build its address index.

I expanded the explanation and filled in some example code.

I'm hoping we can return a `uint160` as a Rust `[u8; 20]` without having to allocate memory. But I guess we'll see.

**Comment by conradoplg** [comment]
Those two PRs mentioned above close this issue. (The `zcashd` one won't be merged into `main` and we will keep pointing to that branch, until we create a PR upstream and it's accepted)
