### ISSUE TITLE
Get addresses from transparent outputs

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3149]

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3149?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
