### ISSUE TITLE
Store transactions in a separate database index

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3151]
## Motivation

`lightwalletd` caches all the blocks from Sapling activation, asking for them in height order. So the block RPC needs to be fast.

## Designs

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

For good performance, use the RocksDB `multi_get` methods to get all the transactions for a block.

## Tasks

1. Make the changes
2. Increment the database version
3. If you created new Rust modules, make sure the regenerate state paths are up to date in https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/test.yml

**Comment by dconnolly** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3151?planning-poker) with ZenHub @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn
