### ISSUE TITLE
getbestblockhash JSON-RPC method

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3159]
## Motivation

`lightwalletd` uses the `getbestblockhash` JSON-RPC method.

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getbestblockhash.html

These fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/common.go#L304

Response:
```
"hex"      (string) the block hash hex encoded
```

This response is not JSON-encoded:
* [jsonrpc type that holds the encoder function](https://docs.rs/jsonrpc-core/latest/jsonrpc_core/type.FutureResult.html)
* TODO: do we need to replace the encoder, or will lightwalletd just understand json encoding anyway?

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring an RPC method which returns a Rust future](https://github.com/paritytech/jsonrpc/blob/e724d087defc0af35bc1c844049d1611588d8466/derive/examples/std.rs#L39)
* [testing RPC methods](https://github.com/paritytech/jsonrpc/blob/master/derive/examples/client-local.rs)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3159?planning-poker) with ZenHub @conradoplg @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn @dconnolly

**Comment by oxarbitrage** [comment]
It seems this will need something similar to what we did at https://github.com/ZcashFoundation/zebra/pull/3706 and https://github.com/ZcashFoundation/zebra/pull/3725
