### ISSUE TITLE
getrawmempool JSON-RPC method

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3160]
## Motivation

`lightwalletd` uses the `getrawmempool` JSON-RPC method.

### Assumptions

`lightwalletd` doesn't need witnessed mempool transaction IDs for Orchard (`UnminedTxId`).
https://discord.com/channels/809218587167293450/809250822579028008/943326658042163270

### Required Fields

The method is documented here: https://zcash.github.io/rpc/getrawmempool.html

`lightwalletd` always uses the no-argument format: https://github.com/zcash/lightwalletd/blob/master/common/mempool.go#L95

And only these fields are used by `lightwalletd`: https://github.com/zcash/lightwalletd/blob/master/common/mempool.go#L106

Response:
```
[                     (json array of string)
  "transactionid"     (string) The transaction id - this is a TXID, not a WTXID
  ,...
]
```

### Tasks

- Implement the RPC method 
- Add RPC acceptance tests to CI
- Test that the RPC method works with `lightwalletd` 

## API Reference

We plan to use [jsonrpc_core](https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/) with:
* [jsonrpc_http_server](https://github.com/paritytech/jsonrpc/tree/master/http)
* [jsonrpc-derive](https://github.com/paritytech/jsonrpc/tree/master/derive)

### Example Code

Here are examples of:
* [declaring RPC methods as Rust functions](https://github.com/paritytech/jsonrpc#basic-usage-with-derive)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3160?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
