### ISSUE TITLE
Add RPC port and config acceptance tests to CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3165]
# Motivation

We want to test the RPC port like we test the Zcash, metrics, and tracing ports:
- port query success test
- port conflict test

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3165?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
