### ISSUE TITLE
Implement transaction binding signature verification key

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#318]
![image](https://user-images.githubusercontent.com/552961/77567128-16d1f200-6e9d-11ea-913c-92e45f651e9e.png)

https://zips.z.cash/protocol/protocol.pdf#saplingbalance

Resolved in https://github.com/ZcashFoundation/zebra/blob/cfc339e8ea558f0f5cd4cb117160ab3f2c542ce0/zebra-consensus/src/transaction.rs

**Comment by hdevalence** [comment]
There's an interaction to think through with the `redjubjub` API, since the procedure for creating the binding signature keypair involves manually constructing some scalars and group elements, but the `redjubjub` API doesn't expose those details.

**Comment by hdevalence** [comment]
We will not perform the recommended check for implementation faults, since it's impossible to implement without violating encapsulation of the Redjubjub interface.

**Comment by daira** [comment]
I'm surprised by that. You need to be able to compute bsk anyway; DerivePublic and checking equality of public keys are part of the intended public interface.
