### ISSUE TITLE
Add a state service request type `NoteCommitmentTree` that will fetch the deserialized tree from a chain tip

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#3182]
This issue is not strictly needed for verifying NU5 consensus.

The request could be used to get the trees to do checks in the transaction verifiers. We may eventually need that for wallet work. The idea is that a wallet can fetch the latest tree from zebrad, use that to trace a path from the root to a new note commitment when it creates a note so that zebrad doesn't have to have access to the witness Merkle path when minting a shielded transaction

**Comment by teor2345** [comment]
This got implemented for lightwalletd.
