### ISSUE TITLE
Document how we review dependency changes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3183]
## Motivation

In Zebra, we regularly:
* add new dependencies, and
* update dependencies to newer versions.

But each dependency change is a security risk, because dependency code runs in the Zebra process, and some of that code could be `unsafe`. (Or impact performance or privacy.)

So we need to carefully review dependency changes, particularly after we are audited.

### Scheduling

We should spend an hour or two creating a draft document, then iterate as needed.

### Process Changes

- Document how we identify and review dependency changes

## Related Work

- #3184

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3183?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
Since [there is no guarantee that the crates.io package matches the GitHub code](https://internals.rust-lang.org/t/making-crates-io-verify-code-against-repository/14075/11), I think we should try to use https://lib.rs/crates/cargo-crev or something similar

**Comment by teor2345** [comment]
This isn't a high priority for process documentation.
