### ISSUE TITLE
Document how we review network protocol changes after audits

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3187]
## Motivation

We have finished implementing the required parts of the Zcash network protocol, and we're going to fix some bugs over the next few weeks. After we get the network code audited, we will need to make sure Zebra keeps implementing a compatible network protocol stack.

Network protocol changes can happen due to:
- ZIP changes
- Zebra network protocol bugs
- refactors
- dependency updates

### Scheduling

We should spend an hour or two creating a draft document, then update it later as needed.

### Process Changes

We should document the requirements for new network protocol messages, and network protocol updates:
- quote the network protocol rule from the ZIP, Bitcoin docs, or `zcashd` codebase
- link to the relevant section in the ZIP, docs, or code
- explain how Zebra is compatible with the network protocol rule
- test success and failure cases for the network protocol rule
- validate test vectors from `zcashd`, if available

We should also document how we identify the code that can change network protocol behaviour:
- the function that implements the network protocol rule
- all code that it calls, including other Zebra crates, and external dependencies
- any code that changes the data that's given to the function (for example, calling the function on different messages, or in a different connection state)

## Related Work

- #3183
- #3186
- #3188

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3187?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We can probably just use the same process as:
- #3186
