### ISSUE TITLE
Stop ignoring panics in the peer receiver and heartbeat tasks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3199]
## Motivation

Zebra currently ignores panics in the peer message receiver task, and in the peer heartbeat task.

This can cause security or usability issues, because it can hide bugs, and cause hangs.

### Designs

Add the join handles for these tasks to the `Client`, and poll them for panics during `Client::poll_ready`

https://github.com/ZcashFoundation/zebra/blob/3ddb9f9e59e3c9d477c011c1feb424390eb0ac14/zebra-network/src/peer/handshake.rs#L929-L931

https://github.com/ZcashFoundation/zebra/blob/3ddb9f9e59e3c9d477c011c1feb424390eb0ac14/zebra-network/src/peer/handshake.rs#L947-L948

## Related Work

This might be the cause of peer set or Zebra hangs.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3199?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
