### ISSUE TITLE
Transaction naming scheme

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#32]
Many parts of the spec use `tx` to refer to a transaction, either standalone or in compound names (e.g., `tx_in`, `tx_out`, and more as in #13).

I think we should decide whether or not to adopt this convention, but whichever way we go, I think we should be consistent, so that if we use `tx` in some places we should use it everywhere (e.g., `Tx` rather than `Transaction`, `TxHash` rather than `TransactionHash`, etc), or else not use it and always use "transaction".

Personally I would prefer to use `tx` but I would more strongly prefer consistency.

**Comment by dconnolly** [comment]
I'm torn on this. I think I would rather use the full `Transaction` to make things explicit and clear where possible. `Tx` is not...confusable as much as poorly-scannable.

Also, terms of art such as UTxO / UTXO make a little more sense if we go with `tx`, but, we are in a compiled Rust world, and we can definitely afford 'long' names, and I don't _think_ (***knock wood***)  there are many `TransactionThingsForDifferentThings` but maybe I'm naïve.

**Comment by hdevalence** [comment]
The code in #17 (along with lots of other code in the async ecosystem) uses `tx, rx` for transmit/receive for streams and sinks (eg. in channels).  Perhaps this tilts the analysis away from `Tx` for `Transaction`?  If others agree I'm happy to close this for now (we can always revisit naming later).

**Comment by dconnolly** [comment]
I'm good with explicit `Transaction` and `tx` for transmit for now. 👍
