### ISSUE TITLE
Implement a merge queue for Zebra using the bors merge bot

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3201]
## Motivation

We want to speed up CI and at the same time ensure that code changes to zebra are merged atomically, so that we know that our main branch always contains a version of the code that has been fully tested.

### Designs

We can do this by having a merge queue for Zebra, using the bors merge bot (see https://kflansburg.com/posts/merge-queues/ for a good intro) and:

1. Adding a staging branch
2. Splitting CI jobs between staging-only and "every PR change"
3. Only running macOS and Windows tests on the staging branch
## Related Work

See #1533 also

**Comment by gustavovalverde** [comment]
I'll take this part from the proposed strategy, as this was one of the main points I considered an issue when going through the first CI test. 
![image](https://user-images.githubusercontent.com/16890942/145796818-fc8d05a6-d1e7-47ae-b816-2de85cce2f8b.png)

> "This approach works, but can become extremely tiresome for projects with many contributors and a long build process. [...] This results in multi-hour babysitting exercise to just land your one PR."

And also splitting up tests based on their duration and criticality; this way not all tests are running at the same time, and some can run at push-time, others when opening a PR, and others (like the staging CD) when the PR has been reviewed/approved to be merged.

**Comment by mpguerra** [comment]
> I'll take this part from the proposed strategy, as this was one of the main points I considered when going through the first CI test. ![image](https://user-images.githubusercontent.com/16890942/145796818-fc8d05a6-d1e7-47ae-b816-2de85cce2f8b.png)

I don't think we need to choose any strategies from the article, it just justifies other strategies that don't work as well. As I understand it we just need to configure and set up bors to implement the workflow explained in the first diagram:

![Screenshot 2021-12-13 at 12 44 14](https://user-images.githubusercontent.com/1311133/145806495-9372cd6d-e451-455e-a073-42baf247b772.png)

We can have a call to discuss the approach

**Comment by teor2345** [comment]
> And also splitting up tests based on their duration and criticality; this way not all tests are running at the same time, and some can run at push-time, others when opening a PR, and others (like the staging CD) when the PR has been reviewed/approved to be merged.

This is a big benefit of this change. There are a lot of slow tests for code we're not actively working on, so they don't need to be run that often.

But we don't need to do anything different for "push-time" and "opening a PR". For Zebra, we just have two different stages:
* opening or modifying a PR branch
* trying to merge an approved PR to the `main` branch

**Comment by teor2345** [comment]
Here's a rough plan for getting the merge bot working, split into a few stages:
1. Add the merge bot, make it run all the existing tests on PRs and the canary branch, and keep allowing manual merges
2. Add a few high-priority slow tests, if we need them urgently
3. When we're happy with the merge bot, stop allowing manual merges
4. When we have time, turn off some slow tests for PRs, and just run them using the merge bot

I'd like to use the `bors` merge bot, because it seems to work well for other Rust projects.

What do you think @gustavovalverde @dconnolly?

**Comment by gustavovalverde** [comment]
As a quick-win, `bors` merge bot seems like the way to start; I'll be testing to ensure its impact on this project. I agree with these stages @teor2345; we just have to decide which tests to prioritize (and the reasoning behind the prioritization)

**Comment by teor2345** [comment]
> we just have to decide which tests to prioritize (and the reasoning behind the prioritization)

In the past week, we merged one PR that broke syncing (see #3206), and almost merged another (#3167). So I'd like to prioritise this ticket:
- #1592

I don't see any other high-priority tickets at this stage.

**Comment by gustavovalverde** [comment]
Seems like GitHub's team is also aware of this problem (as a whole) https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/ 

We could sign here, and see if we're lucky enough, to compare it with`bors` https://github.com/features/merge-queue/signup

I don't have access to add the repo, could you help here @teor2345 @dconnolly?

**Comment by teor2345** [comment]
> Seems like GitHub's team is also aware of this problem (as a whole) https://github.blog/changelog/2021-10-27-pull-request-merge-queue-limited-beta/
> 
> We could sign here, and see if we're lucky enough, to compare it with`bors` https://github.com/features/merge-queue/signup
> 
> I don't have access to add the repo, could you help here @teor2345 @dconnolly?

Good idea! @dconnolly signed us up weeks ago, we haven't heard back.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3201?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn @gustavovalverde

**Comment by gustavovalverde** [comment]
Considering [Mergify](https://mergify.com/) as an option after going through the documentation, as it has some powerful features, and everything is well documented. Aside from the auto-merge, queue, and auto-update, the backport and the [pull request dependencies](https://docs.mergify.com/actions/merge/#defining-pull-request-dependencies) might be helpful features. And it has extra power with the premium version, allowing reviewer assignment, onboarding, prioritization, batching, parallel checks, etc.

**Comment by teor2345** [comment]
> Considering [Mergify](https://mergify.com/) as an option after going through the documentation, as it has some powerful features, and everything is well documented.

I think we should pay for premium, because we already use these features in our existing CI:
- Dependency between PRs
- Priority Queue
- Speculative Checks (Parallel Checks)

And we will probably want these features as well:
- Random Request Reviews
- Batch Merge
