### ISSUE TITLE
Bump sha2 from 0.9.8 to 0.10.0 after ECC NU5 crates

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3202]
## Motivation

There is a new version of sha2 which doesn't have anything critical that requires an update, but overall we like to keep dependencies up to date. However, since `bip0039`, `bs58`, `ed25519-zebra`, `zcash-primitives` all import `sha2 v0.9.8` we either need to wait for them to update or allow the duplicate dependency with different versions in `deny.toml`. 

Wait for the NU5 releases of the ECC crates and check if it's possible then to link to a single `sha2` version. If not, add an exception to  `deny.toml`.

## Related Work

There's a provisory bump PR in https://github.com/ZcashFoundation/zebra/pull/3195

**Comment by teor2345** [comment]
This is either fixed by:
- #2982 (we'll upgrade sha2 to remove duplicates), or
- #3115 (we'll upgrade it anyway, if it doesn't cause too many duplicates).

So we don't need a separate ticket here.
