### ISSUE TITLE
Stop panicking when attempting to run multiple Zebra instances

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#3205]
## Motivation

When a user attempts to run multiple simultaneous instances of Zebra without specifying a different database path for each, all instances except the first one panic because they try to use the same database.

These panics might be alarming to some users.

There are, in fact, five different kinds of such conflicts:
- disk state
- Zcash listener port
- metrics port
- tracing filter port
- rpc port

An error-level log message and graceful shutdown might be better for these conflicts.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3205?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
