### ISSUE TITLE
Create Output Proof

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#321]
![image](https://user-images.githubusercontent.com/552961/77572863-1d189c00-6ea6-11ea-81dc-51f1970ce14a.png)
https://zips.z.cash/protocol/protocol.pdf#outputstatement

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
