### ISSUE TITLE
Document consensus rules from Zcash spec: Section 3.7 Action Transfers and their Descriptions

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3212]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Implementation
 
This was implemented in #1864 (PR: #1885)

**Comment by conradoplg** [comment]
Already done
