### ISSUE TITLE
Document consensus rules from Zcash spec: 4.6 Action Descriptions

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3218]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rules

https://zips.z.cash/protocol/protocol.pdf#actiondesc

<img width="893" alt="Screenshot 2021-12-16 at 17 47 35" src="https://user-images.githubusercontent.com/1311133/146413471-6a88a00c-ea9d-49c2-9906-c09974492baa.png">

## Implementation
 

- #1864
    - PR: #1885

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3218?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
