### ISSUE TITLE
Document consensus rules from Zcash spec: 4.12 Balance (Sprout)

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3219]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rule
https://zips.z.cash/protocol/protocol.pdf#joinsplitbalance
<img width="871" alt="Screenshot 2021-12-16 at 17 26 48" src="https://user-images.githubusercontent.com/1311133/146410075-a259f292-e7c4-4235-9fda-f2ffd9478624.png">

See [ZIP 209: Prohibit Negative Shielded Chain Value Pool Balances](https://zips.z.cash/zip-0209) also

## Implementation
 

- #2381 
    - PR: #2566

**Comment by teor2345** [comment]
It doesn't really make sense for oxarbitrage to do two of the negative value balance rules, and me to do the other one. I'm pretty sure all 3 rules will get documented in exactly the same module. (Maybe even in the same method?)

I'm happy to pick up other tickets though.
