### ISSUE TITLE
Validate JoinSplit proofs

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#322]
![image](https://user-images.githubusercontent.com/552961/77573033-6f59bd00-6ea6-11ea-97c0-a81c05be6d98.png)

https://zips.z.cash/protocol/protocol.pdf#joinsplitstatement

Luckily we can use the Sprout JoinSplits in old transaction/block test vectors to exercise this.

**Comment by hdevalence** [comment]
xref: https://github.com/ZcashFoundation/zebra/issues/305#issuecomment-604021604
