### ISSUE TITLE
Document consensus rules from Zcash spec: 7.4 Output Description Encoding and Consensus

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3225]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rule

https://zips.z.cash/protocol/protocol.pdf#outputencodingandconsensus

<img width="911" alt="Screenshot 2021-12-16 at 15 51 23" src="https://user-images.githubusercontent.com/1311133/146394622-2c9c9100-402b-42fe-bce8-0c0c0ab3e0c8.png">

## Implementation
 
- #1864 (PR: #1885)

**Comment by conradoplg** [comment]
I ended up doing this in https://github.com/ZcashFoundation/zebra/pull/3462 since it was closely related
