### ISSUE TITLE
Document consensus rules from Zcash spec: 7.5 Action Description Encoding and Consensus

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3226]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rule

https://zips.z.cash/protocol/protocol.pdf#actionencodingandconsensus

<img width="911" alt="Screenshot 2021-12-16 at 15 48 20" src="https://user-images.githubusercontent.com/1311133/146393540-1f8c2ba5-ad33-43c6-a72c-25e9f3b4a3dc.png">

## Implementation
 
- #1864 (PR: #1885)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3226?planning-poker) with ZenHub @gustavovalverde @dconnolly @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn
