### ISSUE TITLE
Document part of consensus rules from Zcash spec: 7.6 Block Header Encoding and Consensus

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#3227]
For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rule

https://zips.z.cash/protocol/protocol.pdf#blockheader
![headerrules1](https://user-images.githubusercontent.com/21685097/147360421-3bf59ae9-e6a6-4cf2-bee4-e8d7c4f73938.png)

## Implementation
 

Implemented in:
- #477 
    - #591 (PR: #607)
    -

**Comment by teor2345** [comment]
@mpguerra @oxarbitrage there are a lot of consensus rules in this ticket, did you want to split it?

It might help to do this split:
- merkle tree root (not in the spec?) and block data root (hashLightClientRoot/hashBlockCommitments)
- everything else

**Comment by oxarbitrage** [comment]
Yes i divided the ticket. This one is now for "everything else" and https://github.com/ZcashFoundation/zebra/issues/3297 is for the root stuff. I changed the screenshot of the spec in this ticket to reflect this.
