### ISSUE TITLE
Increase `PeerSet` message and peer handling test coverage

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3229]
## Motivation

In https://github.com/ZcashFoundation/zebra/issues/2214 we will make some changes on how the `PeerSet` works. We want to have some tests beforehand to isolate other bugs that could be happening in Zebra and are not part of those changes; we also want to make sure this new coverage will keep passing after we introduce the changes.

- [ ] add PeerSet tests that make sure peer::Clients are cancellation-safe (peers become ready after drop and timeout)
- [ ] proptest that makes sure that broadcasts go to the right number of peers, and the peer set recovers from the request (with random numbers of peers)
- [ ] test broadcast error handling - some peers error, and all peers error 

### Scheduling

These tests are important, because they will help us discover the peer set bugs that are causing Zebra to hang.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3229?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> In #2214 we will make some changes on how the `PeerSet` works. We want to have some tests beforehand to isolate other bugs that could be happening in Zebra and are not part of those changes; we also want to make sure this new coverage will keep passing after we introduce the changes.
> *  add PeerSet tests that make sure peer::Clients are cancellation-safe (peers become ready after drop and timeout)

You'll want a test like this:
https://github.com/ZcashFoundation/zebra/blob/f176bb59a290f31b448f005f6018b466dfac95fc/zebra-network/src/peer_set/unready_service/tests/vectors.rs#L65

But dropping the future returned by:
https://github.com/ZcashFoundation/zebra/blob/f176bb59a290f31b448f005f6018b466dfac95fc/zebra-network/src/peer_set/set.rs#L915

It's ok to use fake `peer::Client`s, because the real Clients already have cancel-safe tests:
https://github.com/ZcashFoundation/zebra/blob/f176bb59a290f31b448f005f6018b466dfac95fc/zebra-network/src/peer/client/tests/vectors.rs#L78

> *  proptest that makes sure that broadcasts go to the right number of peers, and the peer set recovers from the request (with random numbers of peers)

Try using `MockService::expect_request` on a `PeerSet` with fake `peer::Client`s. @jvff is the best person to ask about this kind of code.

> *  test broadcast error handling - some peers error, and all peers error

Try using `MockService::expect_request`, then respond with errors when the mock service gets the request.

**Comment by oxarbitrage** [comment]
> proptest that makes sure that broadcasts go to the right number of peers, and the peer set recovers from the request (with random numbers of peers)

Here is a question for this.

Problem: 

We want to test `PeerSet::route_broadcast()` for the number of peers we send the request. 

Solution:

We can already start a peerset with the number of peers we want. We can call `Request::AdvertiseBlock`, that will trigger `route_brodcast()`.

However, there is a new problem:

`route_brodcast()` does not returns any output.

Options:

1- Return output from `route_brodcast()`, we can return for example number of successes and errors that results from sending the request to each peer (it is actually half of the peers that we will be sending to).

2- Catching the receiving peer is getting the request ? How do we make this ?

**Comment by teor2345** [comment]
> 1- Return output from `route_brodcast()`, we can return for example number of successes and errors that results from sending the request to each peer (it is actually half of the peers that we will be sending to).

This seems like a good idea, feel free to add a new `internal::Response` type. (It's like `Response::Nil`, but with extra debugging information).

We could check the other ends of the client test harness, but that seems more complicated.

**Comment by oxarbitrage** [comment]
I don't think we will do this in any near future.
