### ISSUE TITLE
Change `PeerSet` response type to enable peer set fanouts

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3230]
## Motivation

We want to handle fanouts inside the peer set.

Some peer set responses will need to contain multiple response messages, so we need to change the peer set response type. But code that deals with individual peers will keep on using single response messages.

In #2214 we will make some changes on how the `PeerSet` works. To reduce the amount of work in a single PR we are splitting in a preparation phase that should not modify any functionality.

### Scheduling

We should try to fix the underlying `PeerSet` bugs first, and then see if Zebra still has hangs.

This is a complex refactor, so we should avoid doing it unless we are sure it is needed. Instead, we should try to find easier fixes for the underlying PeerSet issues.

## Suggested Design

Add a new type:
- [ ] Rename `internal::Response` to `SinglePeerResponse`
- [ ] Change the `PeerSet`'s `Response` type to a new `PeerSetResponse`, which is an enum containing a list of successful responses:
```rust
Fanout { responses: Vec<SinglePeerResponse> }
Single(SinglePeerResponse)
```

Use `PeerSetResponse` for:
- [ ] peer set code (`zebra_network::peer_set`)
- [ ] `zebra_network::Response`, for crates that depend on `zebra_network`'s peer set

Keep on using `SinglePeerResponse` for:
- [ ] individual peer code (`zebra_network::peer`)
- [ ] isolated peer connections (`zebra_network::isolated`)

### Convenience Conversions

Implement a method on `PeerSetResponse` to get the `SinglePeerResponse`. It's ok for this method to panic if the response is not a `Single` response.

## Testing

This change should be covered by existing tests.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3230?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
@teor2345 I think we discussed this in a previous meeting but i forgot the details. I tried to do some refactor here but it became big and i think i am not understanding correctly. Do you think you can provide some more details on what exactly we are trying to achieve in this ticket specifically (for example where do we need to return the `Vect` with multiple peer set).

Any clarification will help, thanks.

**Comment by teor2345** [comment]
> I tried to do some refactor here but it became big and i think i am not understanding correctly. Do you think you can provide some more details on what exactly we are trying to achieve in this ticket specifically (for example where do we need to return the `Vect` with multiple peer set).

There were some details in #2214, but it looks like they accidentally got deleted after the design meeting. I've moved them to the description in this ticket, and added some more detail.

**Comment by teor2345** [comment]
Renaming `internal::Response` will conflict with PR #3302. If you could review that PR, that would help avoid merge conflicts.

**Comment by oxarbitrage** [comment]
IIRC we are not going to follow this design.
