### ISSUE TITLE
Add awaiting response `peer::Connection` tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3232]
## Motivation

In PR #3200, we added some `peer::Connection` tests, but we didn't test connections that are in `State::AwaitingResponse`.

## Related Work

- #3233

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3232?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Merged into #3234.
