### ISSUE TITLE
Add outbound peer message timeout

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3234]
## Motivation

Zebra doesn't impose a timeout when sending messages to the remote peer. (It only has one when receiving them.)

So at the moment, we're relying on the 2 minute disconnection timeout from the OS TCP stack, and Zebra's internal 2 minute peer service disconnection timeout.

## Suggested Design

- Wrap `peer_tx` in a timeout ~~in the handshaker~~
- Handle timeout errors using `fail_with`
- Test that the timeout works
    - Add awaiting response `peer::Connection` tests
    - Add outbound message error `peer::Connection` tests

## Related Work

- #3233

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3234?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
I was checking this earlier today and i think it can be a bit more complicated than expected. The problem is the `peer_tx` is a `Sink` which is not a future or stream. I am not sure how to timeout this and the problem is the same if we use the proposed alternative.

**Comment by teor2345** [comment]
This is blocked by PR #3295, so we can't do it in this sprint anyway.

> I was checking this earlier today and i think it can be a bit more complicated than expected. The problem is the `peer_tx` is a `Sink` which is not a future or stream. I am not sure how to timeout this

But something like this should work:

```rust
/// A wrapper that puts a timeout on the peer sender sink.
struct PeerTx<Tx> {
    inner: Tx
}

impl PeerTx<Tx>
where
    Tx: Sink<Message, Error = SerializationError> + Unpin
{
    /// Sends `msg` on `self.inner`, returning a timeout error if it takes too long.
    async fn send(msg: Message) -> Result<(), BoxError> {
        // TODO: replace with Result::flatten
        // https://github.com/rust-lang/rust/issues/70142
        tokio::time::timeout(inner.send(msg), REQUEST_TIMEOUT).await.and_then(convert::identity)
    }
}

struct Connection {
    peer_tx: PeerTx,
    ...
}
```

We should probably also change the name or docs for `REQUEST_TIMEOUT`. After this PR, it will be the remote peer send or receive timeout.
