### ISSUE TITLE
Use the env var directly for test_fake_activation_heights

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3238]
## Motivation

We implement the `test_fake_activation_heights` as a Rust feature via a build script and environmental variable. But Rust features should be additive.

This has a number of issues:
- using a build script is slow, because it has to be re-compiled every time
- using a feature means that we have to re-compile every Zebra crate, which makes the tests slow
- if we use the feature on the wrong tests, they will fail

### Designs

- only access the activation heights via `NetworkUpgrade::activation_list`
- check the env var directly in `NetworkUpgrade::activation_list` when `#[cfg(test)]`
- always use the public activation heights when `#[cfg(not(test))]`, and don't check the env var

## Related Work

- #2995

**Comment by conradoplg** [comment]
The intention was for it to not be a proper Rust feature (e.g. you can't enable it with `all-features`) precisely because it's not additive.

But I agree it's awkward and makes compiling slower, so let's do this :+1:

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3238?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn @jvff

**Comment by teor2345** [comment]
This seems to work ok as it is.
