### ISSUE TITLE
Add retries for the sapling and sprout parameter downloads

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3239]
## Motivation

A build of PR #3191 failed with:
> Dec 15 21:55:10.404  INFO {zebrad="de6b673" net="Main"}: zebra_consensus::primitives::groth16::params: downloading Zcash Sapling parameters
> Dec 15 21:56:15.162  INFO {zebrad="de6b673" net="Main"}: zebra_consensus::primitives::groth16::params: downloading Zcash Sprout parameters
> The application panicked (crashed).
> Message:  error downloading Sprout parameter files: IoError(Custom { kind: InvalidData, error: "sprout-groth16.params failed validation: expected: e9b238411bd6c0ec4791e9d04245ec350c9c5744f5610dfcce4365d5ca49dfefd5054e371842b3f88fa1b9d7e8e075249b3ebabd167fa8b0f3161292d36c180a hashing 725523612 bytes, actual: 980ecfb84bef129ff5547a5462e29c2cbff91ecf717d17aec15c6d506a12297e28a8b1c7cac9e3faddce712d02575980e8d29ee232bba3e32f438c14c256e69f hashing 609221143 bytes from \"https://download.z.cash/downloads/sprout-groth16.params.part.1 + https://download.z.cash/downloads/sprout-groth16.params.part.2\"" }). Hint: try deleting "/root/.zcash-params", then running 'zebrad download' to re-download the parameters
Location: zebra-consensus/src/primitives/groth16/params.rs:88

### Designs

- Add a retry to Zebra's parameter downloads
- Only retry the downloads that actually failed

https://github.com/ZcashFoundation/zebra/blob/ea01e305ed0205df7ac47ff757a2036fef576fd5/zebra-consensus/src/primitives/groth16/params.rs#L71

https://github.com/ZcashFoundation/zebra/blob/ea01e305ed0205df7ac47ff757a2036fef576fd5/zebra-consensus/src/primitives/groth16/params.rs#L86

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3239?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This caused another CI build to fail, so I'm moving it to this sprint.
