### ISSUE TITLE
Run async tasks that access AddressBook threaded mutexes on dedicated threads

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3240]
## Motivation

`zebra-network` keeps on having hard-to-diagnose hangs. These hangs could be happening because the `AddressBook` uses a threaded mutex, which blocks the executor, and all async tasks scheduled on the same thread.

### Designs

- launch tasks that access the `AddressBook` mutex using `spawn_blocking`, so they get their own dedicated thread
    - if needed, make the method async, or make it return a Future
    - if that's not possible, use `block_in_place` (this blocks tasks on the same thread, but not the whole executor)

## Related Work

- temporary fix for #1976

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3240?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
FYI this is implemented in PR #3244.
