### ISSUE TITLE
Fan out `PushTransaction` requests to multiple peers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3242]
## Motivation

When Zebra pushes user transactions, we want to:
- send the request to multiple distinct peers, and
- prefer peers that *don't* already have the transaction

(Zebra won't push user transactions until it has client integration.)

### Designs

- Update inventory tracker when we send blocks and transactions to peers:
    - `Request::PushTransaction`
    - `Response::Transaction`
    - `Response::Block`
- Fanout `PushTransaction` requests inside the peer set, like `AdvertiseTransaction` and `AdvertiseBlock`
- Prefer peers that *don't* already have the transaction (this is the opposite of the routing in `route_inv`)

## Related Work

- #2214

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3242?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This isn't needed at the moment, because we just use our own mempool.
