### ISSUE TITLE
Tracking: Questions for Network Audit

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3247]
## Motivation

This tracking issue contains tickets with questions we want to ask during the network audit.

It is blocked by tasks we want to complete before the network audit.

## Issues

- [x] #2167
- [x] #2274
- [x] #2282
    - [x] #2298
    - [ ]  #2299
    - [x] #2300
    - [x] #2448
- [x] #2325
- [x] #1892
- [ ] #1875
- [x] #2153
- [x] #2214
- [x] #1870
- [x] #1904
- [x] #1956 
- [ ] Should Zebra have a time limit on each peer connection, or randomly churn peers?
- [ ] Should Zebra track peer reputations, and disconnect or rate-limit bad peers?
- [ ] #3117

## To Be Confirmed

We want to re-evaluate these tickets before the network audit, to see if we want to fix them, ask questions, or close them.
- #2325

**Comment by mpguerra** [comment]
Converted to issue

**Comment by teor2345** [comment]
It seems like we've answered most of these questions between the Zebra audit and Ziggurat testing.
