### ISSUE TITLE
Block Chain Scanning 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#325]
EDIT: DO IT IN ZEBRA-CLI VERY SIMILAR TO BLAZE SYNC IN ZECWALLET LITE: https://github.com/adityapk00/zecwallet-light-cli/blob/39e59a417ccaf4ca08933166c15d5c3878599349/lib/src/blaze/trial_decryptions.rs

Maybe we'll do Sprout? Maybe say you have to build zcashd to get your balance out to transparent. But we are doing Sapling. And definitely Orchard.
Not required for validation of the whole chain.

![image](https://user-images.githubusercontent.com/552961/77575116-6cac9700-6ea9-11ea-8402-521ed2f71ad9.png)
https://zips.z.cash/protocol/protocol.pdf#sproutscan

![image](https://user-images.githubusercontent.com/552961/77575131-77672c00-6ea9-11ea-95b7-143d2b8fe378.png)
https://zips.z.cash/protocol/protocol.pdf#saplingscan

Part of the Zebra Client design https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0009-zebra-client.md

**Comment by dconnolly** [comment]
Depends on zebra-client existing.

**Comment by teor2345** [comment]
We're not planning to do full-node wallet work any time soon.

If we do, we'll need to decide if this ticket is in scope, and update its content, because the spec has changed since it was created.
