### ISSUE TITLE
Await both the heartbeat request and shutdown channel in the heartbeat task

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3254]
## Motivation

We don't detect cancellations when we're waiting for a response from a peer, so this could cause hangs.

https://github.com/ZcashFoundation/zebra/blob/852c5d63bba22ed9547722fdc9bc9b56081dd116/zebra-network/src/peer/handshake.rs#L986-L999

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3254?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
