### ISSUE TITLE
On release, upgrade to sha2=^0.8.2

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#326]
https://crates.io/crates/sha2

**Comment by hdevalence** [comment]
It looks like `0.8.1` is out already, do you mean `0.8.2` (or is that what you meant by `+`, and I'm just misunderstanding?)

https://crates.io/crates/sha2/0.8.1

**Comment by dconnolly** [comment]
Yeah 0.8.2 and above 😅

**Comment by tarcieri** [comment]
Prepping a v0.8.2 release here:

https://github.com/RustCrypto/hashes/pull/110

**Comment by tarcieri** [comment]
It's out: https://crates.io/crates/sha2/0.8.2
