### ISSUE TITLE
Document Zcash network protocol ZIPs in Zebra codebase

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3277]
## Motivation

We want to ensure that Zebra is compatible with the Zcash network protocol. In order to help us do this, we should document where the Zcash network protocol is implemented in the Zebra codebase.

This will also help when auditing Zebra.

### ZIP Rules

Tasks for each network protocol rule in a ZIP:
- check that the rule is implemented in Zebra (or explain why it's not needed)
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

### Unspecified Rules

If the rule isn't documented in a ZIP or the Zcash Specification, then it is unspecified. Zebra already has a best-effort implementation of all the unspecified Zcash network rules. We should fix and document any bugs as they come up, but we don't need to do anything as part of this ticket.

### Summary Documentation

- [x] Summarise the `zebra-network` tasks and services, and how they work together - done in #3317

We can split up and prioritise the rest of the network documentation based on the sections in the summary documentation.

### Network Protocol ZIPs

- NU5:
    - TODO: list ZIPs
- NU4: Canopy
    - TODO: list ZIPs
- NU3: Heartwood
    - TODO: list ZIPs
- NU2: Blossom
    - TODO: list ZIPs
- NU1: Sapling
    - TODO: list ZIPs
- NU0: Overwinter
    - TODO: list ZIPs
- Sprout
    - TODO: list ZIPs

**Comment by teor2345** [comment]
We could split up and prioritise the rest of the network documentation based on the sections in the summary documentation in PR #3317.

**Comment by teor2345** [comment]
I removed these sections from the ticket, because the Bitcoin documentation might be wrong for Zcash, `zcashd` might change before we match its network implementation, and we only need a compatible implementation anyway.

<details>

### Network Protocol Rules based on the `zcashd` implementation

- TODO: search `zebra-network` for references to `zcashd`, and make sure they are up to date

### Network Protocol Rules based on the [Bitcoin Reference](https://developer.bitcoin.org/reference/p2p_networking.html)

- TODO: search `zebra-network` and `zebrad` for references to the Bitcoin Reference, [Developer Guide](https://developer.bitcoin.org/devguide/p2p_network.html), or [Bitcoin Wiki](https://en.bitcoin.it/wiki/Protocol_documentation)
    - Prefer the Bitcoin Reference and Developer Guide where possible

There may also be useful information in the non-P2P parts of the Bitcoin documentation.

Note that the Bitcoin Reference , Developer Guide, and Wiki can be wrong, outdated, or not apply to Zcash.

</details>

**Comment by mpguerra** [comment]
Removing epic from the Sprint, individual issues under this epic should be scheduled instead

**Comment by teor2345** [comment]
This is either complete, or we decided not to do it.
