### ISSUE TITLE
Move the coinbase decryption check to the transaction verifier

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3290]
## Motivation

This slow check should be done in parallel with the other transaction checks:
https://github.com/ZcashFoundation/zebra/blob/1cbc06aa64673e070c791e0205ae07d38514be9d/zebra-consensus/src/block.rs#L193

This change might make Zebra a bit faster, and it improves DoS-resistance.

**Comment by ftm1000** [comment]
redistributing issues that can be separately worked from Epic #2311

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3290?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This cleanup isn't needed, unless it shows up in performance profiles.
