### ISSUE TITLE
Add a new v5 transaction script verification API to zcash_script and Zebra

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3291]
## Motivation

We want to [modify ZIP-244 to include all UTXO values and scripts in each input's sighash](https://github.com/zcash/zips/issues/574).

This requires updates to `zcashd`'s script module, `zcash_script`, `zebra-script`, and `zebra-consensus`.

### Specifications

[ZIP 244 - Changes to transparent component of signature digest](https://github.com/zcash/zips/pull/577)

TODO: quote consensus rules after the ZIP PR merges

### Designs

Zebra changes:
- Propose a API update to `zcashd`'s script module with a v5 script verification precompute function, which takes the the concatenated serialized bytes of all the spent outputs for a transaction
- Update `zebra-consensus` to wait for all the UTXOs, then pass them to where the new `zebra-script` v5 function will be called

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3291?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
Split the remaining part into https://github.com/ZcashFoundation/zebra/issues/3520.
