### ISSUE TITLE
Document remaining consensus rules from Zcash spec: 7.6 Block Header Encoding and Consensus

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3297]
We divided https://github.com/ZcashFoundation/zebra/issues/3227 in two tickets to make it a bit easier as there are some rules that might be undocumented in the spec, see comment https://github.com/ZcashFoundation/zebra/issues/3227#issuecomment-997484371.

For each consensus rule:

- check that the rule is implemented in Zebra
- make sure the latest version of the rule is quoted in the docs for the code that implements it
- make sure the code implements the latest version of the rule

## Consensus rule

https://zips.z.cash/protocol/protocol.pdf#blockheader
![headerrules2](https://user-images.githubusercontent.com/21685097/147360551-fdae4ba7-b53b-40bc-bd2c-e7d1278ce99b.png)

## Implementation
 

Implemented in:

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3297?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
