### ISSUE TITLE
Upgrade to the ripemd160 0.10 API

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3307]
## Motivation

ripemd160 0.10 has incompatible API changes, so we need to change Zebra's code when we upgrade.

We should only make these changes after `librustzcash` upgrades this dependency.

## Related Work

Dependabot PR:
- #3305

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3307?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We can do this when our other dependencies upgrade.
