### ISSUE TITLE
Abstract out h_Sig hash function for sprout joinsplit verification

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#331]
![image](https://user-images.githubusercontent.com/552961/78058969-1c28b400-7357-11ea-85b4-a008ce1468cf.png)

https://zips.z.cash/protocol/protocol.pdf#hsigcrh

We have pulled in blake2 for Sapling key derivation already. 👍

**Comment by teor2345** [comment]
@dconnolly does this belong in the "Transaction Validation" milestone?

**Comment by dconnolly** [comment]
This is only for sending money to Sprout, and as of  [ZIP-211](https://zips.z.cash/zip-0211), we shouldn't be doing that anymore. 🎉
