### ISSUE TITLE
Consider adding codespell to the CI

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#3318]
## Motivation

It seems @rex4539 is a regular contributor who fixes our typos by running [codespell](https://github.com/codespell-project/codespell) over the codebase. As @oxarbitrage  mentioned, it might be possible to integrate a spell-checker like [codespell](https://github.com/codespell-project/codespell) into our CI.

### Specifications

Here's a previous discussion about spell-checking with @teor2345:

> The tricky part of this change is adding a dictionary with Zcash-specific words, Rust-specific words, and engineering-specific words. Otherwise the spelling CI might fail every time we add a new feature or design.

> > Codespell looks for common (and a lot of) misspellings instead of checking dictionary membership. Here's the relevant description: It does not check for word membership in a complete dictionary, but instead looks for a set of common misspellings. Therefore it should catch errors like "adn", but it will not catch "adnasdfasdf". This also means it shouldn't generate false-positives when you use a niche term it doesn't know about.

> > Here are the misspellings https://github.com/codespell-project/codespell/tree/master/codespell_lib/data.
We could even add ours if we find a common one.

**Comment by teor2345** [comment]
Do we want to fail CI if someone misspells a word?

We need to fix misspellings that make documentation incorrect or unclear. (Which hasn't happened much in the recent spelling fix PRs.)

But if it's clear what the word should be, then it doesn't matter exactly how it is spelt.

Since we can't do an automated check for meaning, we might just want to fix all the misspellings anyway. But I agree it's a low priority.

**Comment by upbqdn** [comment]
Sure, anyone can feel free to close this if it's not a good idea.

**Comment by gustavovalverde** [comment]
Maybe failing the whole CI won't be a good idea. But I plan to have a configuration file specifically for linting/styling/spell-checking. If there's something that's not high-priority but relevant anyways, we can fail the step while keeping the check green, so it allows merging.

I'll keep this issue in my queue, let's keep it open in the meanwhile.

**Comment by teor2345** [comment]
> But I plan to have a configuration file specifically for linting/styling/spell-checking. If there's something that's not high-priority but relevant anyways, we can fail the step while keeping the check green, so it allows merging.

Zebra requires some lints and consistent code formatting, so we can reliably review security-critical code. (Inconsistent formatting or linting can hide security issues.)

Our required lints also allow every developer to check those lints locally, and they help us keep our reviews focused.

But spelling isn't security critical, and we want to add new lints as experiments before we require them. So there's still a need for some optional checks.

**Comment by upbqdn** [comment]
The CI wasn't the right proposal. What I meant was having the spell-checking process somehow automated. I thought of renaming the issue, but the comments wouldn't make sense anymore. 

Failing CI might also require adjusting the spell-checker for false positives, which would be a bigger burden than no spell-checking. Having automated PRs with spell-checking suggestions might be better?

**Comment by teor2345** [comment]
I'm still not quite sure what the goals of this ticket are.

We don't want to block merges for misspellings, and we don't want red check marks if a single word is spelt wrong.

Can we get warnings like Clippy?
Will they actually be useful?
