### ISSUE TITLE
Stop logging IP addresses and mempool transaction IDs by default, to protect user privacy

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3320]
## Motivation

Zebra collects, logs, and has metrics on two kinds of private information:
* IP addresses of Zcash nodes, which can be linked to organisations or individuals, and
* transaction IDs of mempool transactions, because they can reveal the origin of a transaction.

Zebra's logs also attach detailed timestamps to this information.

Zebra should avoid logging and metrics containing this private information by default.

### Suggested Solution

Stop logging and including in metrics by default:
- `SocketAddr`s
- `UnminedTxId`s

## Suggested Design

Modify the `Debug` and `Display` impls of `SocketAddr` and  `UnminedTxId` to just log the type name by default. This would need a `PrivateSocketAddr` wrapper with a `Deref` impl.

This should work for logging and metrics.

## Follow Up Work

Add an IP address logging mode. If we add this config, then users can be compelled to collect this information. So we might want to put it behind a feature that's off by default. Or we might not want to expose this information at all.

**Comment by ftm1000** [comment]
redistributing issues that can be separately worked from Epic #2311

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3320?planning-poker) with ZenHub @gustavovalverde @dconnolly @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This isn't somethign we need to fix any time soon.

**Comment by teor2345** [comment]
@mpguerra Dodger suggested that we consider this privacy risk for the `zebra-network` part of the DNS seeder. We might also want to consider it for the Zebra stable release.
