### ISSUE TITLE
Fix frequent Zebra hangs during syncing

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3322]
## Motivation

Zebra is currently hanging during about 5% - 90% of syncs, depending on the machine and network. But Zebra doesn't seem to hang after the initial sync.

This Epic contains bugs that might be causing these hangs.

But it's also possible that:
- bugs we're currently working on will fix the hangs, or
- other undiscovered bugs are causing the hangs.

So we don't want to add these bugs to #3096 yet.

## Tasks

First, fix the bugs we are currently working on, and see if Zebra stops hanging all the time:
- [x] #3168 
- [x] #3234 
- [x] #3254
- [x] #3379 

If Zebra keeps on hanging frequently, implement these diagnostics:
- [ ] #2112

Then use the diagnostics to:
- prioritise the bugs in this epic, or
- open new bugs for any issues reported by tokio-console.

### Likely Causes

This code has caused hangs before:
- [x] #3288
- [x] #3263
- [x] #862
- [x] #2188
- [x] #2201
- [x] #2202
- [x] #3042
- [x] #1351

**Comment by mpguerra** [comment]
Do we need to review this issue and its associated potential fixes given that it seems we've fixed some hangs for now...

**Comment by conradoplg** [comment]
I think we can close this after https://github.com/ZcashFoundation/zebra/issues/3234 is completed

**Comment by teor2345** [comment]
I'm not seeing any hangs after testing the latest `main` on 4 different mainnet and testnet instances, so I'm happy to just close this now.
