### ISSUE TITLE
Update `bitvec` to version 1.0.0

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3340]
## Motivation

A new release of `bitvec` came out with a stable API. It is a breaking change, and we'll have to update parts of our code.

### Designs

See [bitvec's changelog](https://github.com/bitvecto-rs/bitvec/blob/main/CHANGELOG.md#version-1) for information about the breaking changes and suggestions on how to update the code.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3340?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
bellman, orchard, bls12_381, jubjub all depend on it so we're probably stuck on using whatever they're using; I'm closing this for now

**Comment by str4d** [comment]
I am attempting to get this addressed for `zcashd 5.0.0` via an `ff 0.12` release, which requires a bunch of coordination.

**Comment by teor2345** [comment]
@dependabot ignore this minor version
