### ISSUE TITLE
Bump color-eyre from 0.5.11 to 0.6.0

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3343]
## Motivation

https://github.com/ZcashFoundation/zebra/pull/3342 fails because it creates a duplicate dependency on `tracing-subscriber`.

Bump `color-eyre` and update `tracing-subscriber` too or add an exception for it

**Comment by teor2345** [comment]
@conradoplg can we close this ticket and do the upgrade with the rest of tracing in #2953?

**Comment by conradoplg** [comment]
> @conradoplg can we close this ticket and do the upgrade with the rest of tracing in #2953?

Sure!
