### ISSUE TITLE
Use a single Dockerfile for testing and deploying

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3344]
## Motivation

- Github Actions is using VMs for pre-merge CI
- GCP is using Dockerfile.test for post-merge CI
- GCP is using Dockerfile.build for pre-prod build

The ideal scenario would be to have the same Dockerfile to test, build and deploy; this ensures the same behavior across platforms and that post-merge errors are captured before merging into main.

### Designs

- Refactor the actual Dockerfile
- Update CI and CD to use the resulting artifact (Docker image) for building, testing, and deploying
- Allow executing different tests from a single Docker image by passing arguments at runtime
- Speed up CI by caching previous layers

**Comment by conradoplg** [comment]
@gustavovalverde I lost track of the recent changes, is this ticket done or is there something left to do?

**Comment by gustavovalverde** [comment]
@conradoplg added the PR to close this
