### ISSUE TITLE
Fix intermittent syncing

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3352]
## Motivation

Currently, the sync stops for a couple minutes every ~5 minutes, which makes syncing very slow.

Identify the cause and fix it. We're currently discussing it in https://discord.com/channels/676527656170160146/920784737872773122

The issue seems to have appeared in https://github.com/ZcashFoundation/zebra/pull/3120

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3352?planning-poker) with ZenHub @conradoplg @gustavovalverde @jvff @oxarbitrage @upbqdn @teor2345 @dconnolly
