### ISSUE TITLE
Documenting Mergify and other automations being done in the repository

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3360]
## Motivation

- Automating helps the team with faster delivery, but it also makes onboarding harder if there's no documentation available

### Designs

- Improve actual documentation in the pipelines.
- Explain queues and some options from Mergify.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3360?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @teor2345

**Comment by gustavovalverde** [comment]
Closed via https://github.com/ZcashFoundation/zebra/pull/4540
