### ISSUE TITLE
Restore coverage to use latest rust nightly

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3367]
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/3366, in `coverage.yml` we pinned rust nightly in to a specific version to workaround a [rust bug](https://github.com/rust-lang/rust/issues/79645#issuecomment-1013982804).

[Since it was fixed in 2022-01-26](https://github.com/taiki-e/cargo-llvm-cov/issues/128#issuecomment-1021809795), we should restore it back to `nightly` to always get the latest version.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3367?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
