### ISSUE TITLE
Bump tracing-journald from 0.1.0 to 0.2.2

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3371]
## Motivation

We should keep dependencies up to date.

We must fix breaking changes, see logs in https://github.com/ZcashFoundation/zebra/pull/3358

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3371?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Duplicate of #2953
