### ISSUE TITLE
Calc Block Subsidy and Funding Streams

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#338]
## Motivation

When validating blocks and transactions, we need to calculate the block subsidy.

### Specifications

> Consensus rule: [Canopy onward] The coinbase transaction at block height height MUST contain at least one output per funding stream fs active at height, that pays fs.Value(height) zatoshi in the prescribed way to the stream’s recipient address represented by fs.AddressListfs.AddressIndex(height).
> 
> The “prescribed way” to pay a transparent P2SH address is to use a standard P2SH script of the form OP_HASH160 fs.RedeemScriptHash(height) OP_EQUAL as the scriptPubKey. Here fs.RedeemScriptHash(height) is the standard redeem script hash for the recipient address given by fs.AddressList fs.AddressIndex(height) in Base58Check form. The standard redeem script hash is specified in [Bitcoin-Multisig] for P2SH multisig addresses, or [Bitcoin-P2SH] for other P2SH addresses.
> 
> The “prescribed way "to pay a Sapling address is as defined in [ZIP-213], using the post-Heartwood consensus rules specified for Sapling outputs of coinbase transactions in § 7.1 ‘Transaction Encoding and Consensus’ on p. 116.

https://zips.z.cash/protocol/protocol.pdf#fundingstreams

## Existing Work

Block Subsidy and Funding Streams Design RFC PR: #1129

Founders Reward Implementation PR: #1170

## Remaining Work

Semantic Validation RFC
- [ ] Since Zebra has a mandatory checkpoint at Canopy, we can ignore the founders reward
  - [ ] Delete the founders reward parts of the RFC and implementation
- [ ] Review the funding streams parts of the RFC

Semantic Validation Implementation
- [ ] Implement funding streams
- [ ] Implement other semantic validation from the RFC

Contextual Validation
- [ ] transaction fees: needs UTXOs
- [ ] coinbase source: needs UTXOs tagged with coinbase provenance #1342 
    - this is a database version change

## Requirements

![image](https://user-images.githubusercontent.com/552961/76341799-ea7e7900-62d3-11ea-8528-f8dd5afac025.png)

https://zips.z.cash/protocol/protocol.pdf#subsidyconcepts
https://zips.z.cash/protocol/protocol.pdf#blockchain
https://zips.z.cash/protocol/protocol.pdf#subsidies
https://zips.z.cash/protocol/protocol.pdf#foundersreward

![image](https://user-images.githubusercontent.com/552961/78065439-4bdcb980-7361-11ea-9c75-1831b7a9941b.png)

![image](https://user-images.githubusercontent.com/552961/78065544-70389600-7361-11ea-848a-9cb3defef89a.png)

**Comment by teor2345** [comment]
We've chosen to delay work on miner rewards and block subsidy until later, so I'm removing this from the sprint.
