### ISSUE TITLE
Document `zebrad download` command

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3383]
Zebra has a command to pre download the parameters. Zebra also download parameters at `zebra start` if they are not present.

There is no documentation about this, i think we should add:

- Briefly describe what are this parameters and why they are needed.
- Document the `zebrad download` existence.
- Explain `zebrad start` will automatically start downloading parameters at startup.

https://zebra.zfnd.org/user/run.html

We may need to wait on https://github.com/ZcashFoundation/zebra/issues/3133 as some of the current behaviour will maybe change.

**Comment by teor2345** [comment]
This isn't a breaking change, does it need to happen before the stable release?

**Comment by conradoplg** [comment]
> This isn't a breaking change, does it need to happen before the stable release?

@teor2345 I moved some to that Epic thinking about making it just a "Stable Release" epic, but there weren't enough issues to justify that. I'll move them to the Tech Debt Epic

**Comment by mpguerra** [comment]
@oxarbitrage can you please add an estimate to this issue since you worked on it?

**Comment by mpguerra** [comment]
I'm not going to move this one to Sprint 2 as it was just supposed to be work for the end of year. We should try to get its PR reviewed and merged soon enough though.
