### ISSUE TITLE
Enforce a commit message convention project-wide

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3410]
## Motivation
To automate some tools based on commits, we'd need a commit convention. In the long run, this also helps to hastily identify which commits are fixes, improvements, reactors, documentation, styling, and even **breaking changes**. And, as a result, it helps us understand which commit might have made a behavioral change, just by seeing the commit title.

### Specifications
https://www.conventionalcommits.org/en/v1.0.0/#specification

### Designs
- Implement conventional commits
- Found a way to enforce it project-wide
- The best way to enforce this kind of rules is locally (on each developer's terminal)
- Using pre-commit (for this and other things) might be helpful https://pre-commit.com/

## Related Work

N/A

**Comment by teor2345** [comment]
Can you add this discussion to an engineering sync agenda?
