### ISSUE TITLE
Upgrade to NU5 mainnet version of orchard and librustzcash

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3414]
## Motivation

`orchard` and `librustzcash` won't have a tagged version until after the `zcashd` 4.7.0 release. So we need to split its version upgrade out of the NU5 testnet 2 work in #2982.

After #2982, Zebra and `zcash_script` will depend on a git version of the following shared Zcash crates:
- orchard
- zcash_history
- zcash_primitives
- zcash_note_encryption
- zcash_script

We need to update to the NU5 mainnet versions of these crates.

We should also upgrade to the newest released versions of these crates:
- incrementalmerkletree
- equihash
- halo2

Crypto dependencies:
- #4335

## Tasks

1. Wait until the `zcashd` team publishes updated versions of orchard and librustzcash
2. Make sure https://github.com/zcash/librustzcash/pull/459 is in that release (if not, upgrade our fork, as in #2982)

### zcash_script

3. Upgrade `zcash_script` to the latest orchard and its dependencies (published crate), removing the git versions in Cargo.toml
4. Upgrade `zcash_script` to the latest librustzcash and its dependencies (published crate), removing the git versions in Cargo.toml
5. Tag a `zcash_script` beta release

### Zebra

6. Upgrade Zebra to the latest versions of orchard and its dependencies (published crate), removing the git versions in Cargo.toml, including #4335
7. Upgrade Zebra to the latest version of librustzcash and its dependencies (published crate), removing the git versions in Cargo.toml
8. Upgrade Zebra to the latest version of`zcash_script` (git tag)
9. Remove the exceptions for orchard, librustzcash, and their dependencies in `deny.toml`
10. Merge the Zebra upgrade PR along with the PR for ticket #1841

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3414?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
