### ISSUE TITLE
Zcash parameter downloads take 20+ minutes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3416]
## Motivation

Zebra downloads the Zcash parameters in every Google Cloud Build run. Recently, these downloads started taking 20+ minutes.

But in the GitHub runners, the same downloads seem to work fine. But the GitHub runners don't do the download every time. They cache the parameters, and only do the download when the cache expires or gets too big.

## Tasks

1. Work out if we've made changes that caused `zebrad download` to be slow
2. Check if the `download-params` example is also slow
3. Check if the `zcashd` script is also slow: https://github.com/zcash/zcash/blob/master/zcutil/fetch-params.sh

**Comment by conradoplg** [comment]
Happened [again](https://github.com/ZcashFoundation/zebra/pull/3433/checks?check_run_id=4983058667) even with 60min timeout

```
Jan 28 16:07:57.557  INFO {zebrad="15ba75b" net="Main"}: zebrad::commands::download: checking if Zcash Sapling and Sprout parameters have been downloaded
Jan 28 16:07:57.557  INFO {zebrad="15ba75b" net="Main"}: zebra_consensus::primitives::groth16::params: downloading Zcash Sapling parameters
Jan 28 16:09:59.097  INFO {zebrad="15ba75b" net="Main"}: zebra_consensus::primitives::groth16::params: downloading Zcash Sprout parameters
Jan 28 16:26:12.177  INFO {zebrad="15ba75b" net="Main"}: zebra_consensus::primitives::groth16::params: error downloading Zcash Sprout parameters, retrying error=IoError(Custom { kind: InvalidData, error: "sprout-groth16.params failed validation: expected: e9b238411bd6c0ec4791e9d04245ec350c9c5744f5610dfcce4365d5ca49dfefd5054e371842b3f88fa1b9d7e8e075249b3ebabd167fa8b0f3161292d36c180a hashing 725523612 bytes, actual: 6a3ed3097058de47619e45832db71fe88f3b3b6c3794b5c793febfafc424809e125dd1ebaed034ec26367b80cc00bbde15cceaf0af6ab26a5e0431caf539e8fd hashing 412948144 bytes from \"https://download.z.cash/downloads/sprout-groth16.params.part.1 + https://download.z.cash/downloads/sprout-groth16.params.part.2\"" })
Jan 28 16:53:50.819  INFO {zebrad="15ba75b" net="Main"}: zebra_consensus::primitives::groth16::params: error downloading Zcash Sprout parameters, retrying error=IoError(Custom { kind: InvalidData, error: "sprout-groth16.params failed validation: expected: e9b238411bd6c0ec4791e9d04245ec350c9c5744f5610dfcce4365d5ca49dfefd5054e371842b3f88fa1b9d7e8e075249b3ebabd167fa8b0f3161292d36c180a hashing 725523612 bytes, actual: ec5d69444b295b47c19c5917bac215bd3754d032cfed4a8a3cd8d2921608aab0a3848e75628866c9d3395627252ab4d1338bf8c91006114813b792bba555acbc hashing 724342447 bytes from \"https://download.z.cash/downloads/sprout-groth16.params.part.1 + https://download.z.cash/downloads/sprout-groth16.params.part.2\"" })
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 2
```

**Comment by mdr0id** [comment]
Based on some historical events from the past, it is strongly discouraged to download params in a given CI pipeline per runner. The increase in time needed to download above is likely due to underlying security features. It is likely best to cache the params and reuse these for your builders. Github and Gitlab offer larger file caches for runners, but we often times will use tools such as IPFS depending on the size of the files needed, requesting geo location, and cost. For now in zcash we build in the params files to our docker zcash-worker* images just for convenience and usability. Later NUs will allow us to remove ceremony params layer in each docker image without much update time.

**Comment by teor2345** [comment]
> Based on some historical events from the past, it is strongly discouraged to download params in a given CI pipeline per runner. The increase in time needed to download above is likely due to underlying security features. It is likely best to cache the params and reuse these for your builders. Github and Gitlab offer larger file caches for runners, but we often times will use tools such as IPFS depending on the size of the files needed, requesting geo location, and cost. For now in zcash we build in the params files to our docker zcash-worker* images just for convenience and usability. Later NUs will allow us to remove ceremony params layer in each docker image without much update time.

I'd be happy to make this change. But how do you make sure your code changes don't break the downloads?

**Comment by mdr0id** [comment]
> > Based on some historical events from the past, it is strongly discouraged to download params in a given CI pipeline per runner. The increase in time needed to download above is likely due to underlying security features. It is likely best to cache the params and reuse these for your builders. Github and Gitlab offer larger file caches for runners, but we often times will use tools such as IPFS depending on the size of the files needed, requesting geo location, and cost. For now in zcash we build in the params files to our docker zcash-worker* images just for convenience and usability. Later NUs will allow us to remove ceremony params layer in each docker image without much update time.
> 
> I'd be happy to make this change. But how do you make sure your code changes don't break the downloads?

I'm confused by your question. Do you mean changes made to fetch-params.sh or some client requesting params repeatedly ?

**Comment by teor2345** [comment]
> > > Based on some historical events from the past, it is strongly discouraged to download params in a given CI pipeline per runner. The increase in time needed to download above is likely due to underlying security features. It is likely best to cache the params and reuse these for your builders. Github and Gitlab offer larger file caches for runners, but we often times will use tools such as IPFS depending on the size of the files needed, requesting geo location, and cost. For now in zcash we build in the params files to our docker zcash-worker* images just for convenience and usability. Later NUs will allow us to remove ceremony params layer in each docker image without much update time.
> > 
> > 
> > I'd be happy to make this change. But how do you make sure your code changes don't break the downloads?
> 
> I'm confused by your question. Do you mean changes made to fetch-params.sh or some client requesting params repeatedly ?

Zebra automatically downloads the parameters when it starts up, if they are not already in `.zcash-params`.

So if we cache the parameters, we won't know if a PR breaks the parameter download code.

Do you do anything to check that the parameter script still works? Or do you just accept the risk of breakage?

**Comment by mdr0id** [comment]
There are other pipelines that monitor that script diff more or less and deploy nodes. Ideally we want to update the fetch-params.sh to a python/rust flavor to support multiple platforms and provide ipfs or other fallback by default. This design/work went into a bit of a holding pattern for other priority node infra updates. Does this address the question regarding breakage or is there other risks you are referring to?

**Comment by str4d** [comment]
> So if we cache the parameters, we won't know if a PR breaks the parameter download code.

There are several things currently being tested simultaneously here (by always downloading the parameters):
1. That the parameter download code can successfully generate the necessary parameter-fetching requests, and successfully process the received response data.
1. That the generated requests get a response from the remote server that will likely satisfy us once we download it.
1. That the response from the server, once downloaded, actually gives us the correct parameters.

1 is testing the actual code, what I think @teor2345 mostly cares about. 2 is testing that the parameter host is responding in a way we expect to the requests that the code generates, and would be nice to have regular checks of, but doesn't necessarily need to happen on every PR. Meanwhile 3 is where the bandwidth cost arises from, where the security controls are being triggered, and what we actually want to avoid (and not rely on it for the side-effect of making the parameters available for _other_ tests).

So I would argue that we should find a way to either test 1 in a unit tests (mocking out the server request, maybe having it actually return the already-cached parameters), or test 1+2 as a functional test (by having some configurable flag or environment variable that influences the parameter download code to e.g. request the length of the parameter files, but not their actual content). 3 then gets tested occasionally (whenever the CI caches need refreshing).

**Comment by teor2345** [comment]
> So I would argue that we should find a way to either test 1 in a unit tests (mocking out the server request, maybe having it actually return the already-cached parameters), or test 1+2 as a functional test (by having some configurable flag or environment variable that influences the parameter download code to e.g. request the length of the parameter files, but not their actual content). 3 then gets tested occasionally (whenever the CI caches need refreshing).

This seems like a good longer-term fix.

But for now, in Zebra we can just test this code:
- when any code changes in the modules that implement it, and
- whenever the caches expire

That should avoid the server security measures, and catch most PRs that break the parameter downloads.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3416?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
I think this was split between #3447 and #3448, so this can be closed. @teor2345 what do you think?

**Comment by teor2345** [comment]
I think this is covered by those other tickets.
