### ISSUE TITLE
ZG-CONFORMANCE-003-006: ignore non-Version/Verack messages during the handshake

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3429]
## Motivation

The Ziggurat team picked up some handshake bugs we should fix:
https://github.com/eqlabs/ziggurat#conformance
https://github.com/eqlabs/ziggurat/blob/master/SPEC.md#zg-conformance-003

## Tasks

In the handshake:
- ignore unexpected messages while waiting for `Version`
- ignore unexpected messages while waiting for `Verack`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3429?planning-poker) with ZenHub @dconnolly @conradoplg @gustavovalverde @oxarbitrage @teor2345 @upbqdn @jvff
