### ISSUE TITLE
Use the Filesystem Hierarchy Standard (FHS) for deployments and artifacts

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3432]
## Motivation

Linux has its own filesystem convention, which is standard and considered by most sysadmins when creating products, OS-level restrictions, and even when taking security measures.

We should respect this convention for compatibility with different deployment mechanisms, and when high-security standards are being in placed (most directories are being restricted)

A good example is the Container-Optimized OS used by Google: https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem#working_with_the_file_system

### Specifications

Filesystem Hierarchy Standard - v3.0: https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html
Linux man for `hier`: https://man7.org/linux/man-pages/man7/hier.7.html

## Related Work
#3344

**Comment by teor2345** [comment]
We'll need to make the zebra changes in #1894 to fully support the file system hierarchy standard. But that's a breaking change.

Did you want to schedule both changes for an upcoming sprint?
(They are not required for the stable release candidate, but we should do them before the stable release.)

**Comment by teor2345** [comment]
We want to check this all got done, then close it.
