### ISSUE TITLE
Create wrapper for `precomputed` in `CachedFfiTransaction`

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3436]
## Motivation

`CachedFfiTransaction` has a `unsafe impl Send/Sync` since it has a FFI pointer (`precomputed`) which is neither, and we need both in order to be stored in a `Box` and sent across threads. This is fine as long as we take the proper precautions, as already extensively documented in its source code.

However, we could easily add another field which is not Send/Sync, which would be a problem since the whole struct is being forced into implementing Send/Sync and it would compile without errors while still being unsafe.

The solution is to create a wrapper for the `precomputed` and only make it `unsafe impl Send/Sync`. Since a struct is `Send/Sync` as long as all its fields are too, if we add a field that is not `Send/Sync` then the compiler would detected that.

### Specifications

[This is the approach suggested by the Rustonomicon](https://doc.rust-lang.org/nomicon/send-and-sync.html):

> Most uses of raw pointers should be encapsulated behind a sufficient abstraction that Send and Sync can be derived. For instance all of Rust's standard collections are Send and Sync (when they contain Send and Sync types) in spite of their pervasive use of raw pointers to manage allocations and complex ownership.

### Designs

- [ ] Create a wrapper for `precomputed` that has  `unsafe impl Send/Sync`
- [ ] Remove  `unsafe impl Send/Sync` from `CachedFfiTransaction`
- [ ] Update comments to reflect the changes

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3436?planning-poker) with ZenHub @gustavovalverde @dconnolly @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn
