### ISSUE TITLE
Keep track of partial block downloads

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3440]
## Motivation

When downloading a block, the current `Codec` will only return an item (a `Message`) once the block is fully downloaded. However, that means that the download can time out when the block is almost ready. It would be nice to return intermediary items saying that the block is still being downloaded and how much remains, so that this information can be used to improve the synchronizer's performance.

One idea is to increase the remaining time of the timeout when there's progress, so that the block has a lower chance of timing out when it's almost finished.

### Open Security Problems

Increasing the remaining time out each time a byte is received will leave zebra open to a [slow loris attack](https://en.wikipedia.org/wiki/Slowloris_(computer_security)), unless this change is implemented very carefully.

It might be safer to keep the current fixed timeout.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3440?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @upbqdn @teor2345

**Comment by teor2345** [comment]
I'd like to resolve the security risks in this design before we schedule this ticket.

**Comment by jvff** [comment]
I think the slow loris attack would already be mitigated by the hedge layer, and we can prevent it by still having a larger timeout besides the internal dynamic timeout and/or calculating the dynamic timeout in a way that ensures a given bound.

We can revisit this in the future if needed.
