### ISSUE TITLE
Keep a peer service busy until a cancelled request has finished being received

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3441]
## Motivation

There is no way in the Zcash protocol to request a remote peer to cancel a previous request and stop sending a response. Therefore, when Zebra currently cancels a request, it simply ignores the received response. However, once a request is cancelled, the peer service becomes available to send a new request, which will very likely take a while because it will only receive a response for it once the cancelled request's message is finished being received.

This has led to problems in the past (#3352), and may still be causing issues (#3438).

One idea to solve this problem is not mark the service as ready until the cancelled request's response is fully received.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3441?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This bug doesn't seem to be causing us any issues right now, do we want to remove it from the sprints?

**Comment by teor2345** [comment]
The current behaviour is that we receive the cancelled response, and possibly have a parsing or response handling error. Then the connection recovers.

This seems ok for now.
