### ISSUE TITLE
Move debug stop at height to the `zebrad start` main loop

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3442]
## Motivation

Currently, the debug stop at height config is implemented in the state service. But this makes shutdown difficult.

It would be better if we checked the stop conditions as part of the start command run loop in zebrad.

## Related Work

This change will be easier after we add a task that stops the full sync in:
- #1592

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3442?planning-poker) with ZenHub @gustavovalverde @dconnolly @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@jvff do you mind if I close this ticket?

The current code seems to work, and it's totally unrelated to the light wallet epic.

**Comment by jvff** [comment]
Yeah, I think we will probably not need this any time soon.
