### ISSUE TITLE
Revisit some network timeout values

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3444]
## Motivation

Parts of the network code have heavy use of timeouts. Some timeouts might be redundant or unnecessary, so we should take a look to see if there are any improvements that could be made.

Some specific timeout situations that might warrant a closer attention:
- `GetAddr` timeouts
- fanout timeouts
- timeouts that wrap large network requests or responses, because the peer still has to send the data, even if we drop the future

There is a tradeoff here: if we timeout too early, we can discard partial requests that are almost ready.

But if we timeout too late, or use the default timeout, we can wait a long time for peer responses, or for the peer set to be ready.

The peer set readiness timeout is particularly important on testnet, or networks with a small number of peers. (If we don't have it, Zebra can be really slow or deadlock.)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3444?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
