### ISSUE TITLE
Cache Zcash parameters in Docker files

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3447]
## Motivation

Zebra's CI is currently triggering rate-limits on the Zcash parameters server.

We should cache the Zcash parameters in a docker build that runs once, then occasionally expires. (Or refreshes when the parameter download code modules change.)

### Background

This is a 2 part change, to achieve this outcome:

Zebra should just test the parameter download code:
- when any code changes in the modules that implement it, and
- whenever the caches expire

That should avoid the server security measures, and catch most PRs that break the parameter downloads.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/3416#issuecomment-1026192060_

**Comment by conradoplg** [comment]
@gustavovalverde did https://github.com/ZcashFoundation/zebra/pull/3431 solve this issue?

**Comment by gustavovalverde** [comment]
@conradoplg yes, and I was expecting the "Fixes" keyword on the PR to close the related issues, but it didn't
