### ISSUE TITLE
Run Zcash parameter downloads when the download code changes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3448]
## Motivation

Zebra's CI is currently triggering rate-limits on the Zcash parameters server.

We should run a `zebrad download` test in CI whenever these modules change:
```
zebra-consensus/src/primitives/groth16/params.rs
zebra-consensus/src/chain.rs
zebrad/src/commands/start.rs
```

This will make sure we catch any code changes that break parameter downloads.

### Background

This is a 2 part change, to achieve this outcome:

Zebra should just test the parameter download code:
- when any code changes in the modules that implement it, and
- whenever the caches expire

That should avoid the server security measures, and catch most PRs that break the parameter downloads.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/3416#issuecomment-1026192060_

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3448?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @teor2345 @upbqdn @jvff @oxarbitrage

**Comment by teor2345** [comment]
@gustavovalverde is this already done in https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/zcash-params.yml ?

**Comment by gustavovalverde** [comment]
@teor2345 that's correct. But I haven't closed this because I suppose this is also needed for the `ci.yml` as I've seen that Windows and Mac are not hitting the zcash parameters cache from time to time.

**Comment by gustavovalverde** [comment]
Caching for MacOS and Ubuntu was fixed by https://github.com/ZcashFoundation/zebra/pull/4298
