### ISSUE TITLE
Run `cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag <new-tag> zebrad` from our README before/on release tagging

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3449]
## Motivation

We want to make sure that our install instructions are currently 'green' when we update them for a new release.

### Open Questions

- This might depend on the latest release tag, should this test only run when a tag is pushed?
- Should this run every time the `README.md` file is changed?

**Comment by ftm1000** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3449?planning-poker) with ZenHub @dconnolly
