### ISSUE TITLE
fix(transparent): check coinbase data is at least 2 bytes long

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3457]
## Motivation

`zcashd` requires coinbase data that's 2-100 bytes long:
https://github.com/zcash/zcash/blob/d8c818bfa507adb845e527f5beb38345c490b330/src/main.cpp#L1697-L1698

But Zebra accepts coinbase data that's 1-100 bytes long:
https://github.com/ZcashFoundation/zebra/blob/fa071562fd0b891f29143e4cc8d17b34b4b1cf10/zebra-chain/src/transparent/serialize.rs#L250

https://github.com/ZcashFoundation/zebra/blob/fa071562fd0b891f29143e4cc8d17b34b4b1cf10/zebra-chain/src/transparent/serialize.rs#L74

### Specifications

There is an upcoming change to the Zcash specifications:
https://github.com/zcash/zips/issues/589

## Related Work

We might want to merge these height changes first, they could cause a merge conflict:
- #3401

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3457?planning-poker) with ZenHub @dconnolly @conradoplg @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
