### ISSUE TITLE
Update DNS seeder for NU5 testnet 2 and mainnet activation

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3458]
## Motivation

The Zcash network protocol versioning scheme is going to change, so the DNS seeder's network protocol version will become outdated.

### Scheduling

This task can be done as soon as the spec is updated.
It should be completed a few days before the NU5 testnet rollback, so the new seeder can get a list of updated nodes.

### Specifications

Upcoming change to: https://zips.z.cash/zip-0252

### Tasks

DNS Seeder:
- update the seeder's current and maximum network protocol version to the ***NU5 mainnet*** version
    - we don't need to do separate testnet and mainnet updates, because the network protocol isn't changing
- re-deploy the DNS seeder
- test that the DNS seeder works

(There is no minimum protocol version for the DNS seeders.)

## Related Work

- #3018

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3458?planning-poker) with ZenHub @dconnolly @conradoplg @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
