### ISSUE TITLE
Impl Display for all Sapling keys and addresses 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#346]
This is the human-readable version of serialization.

**Comment by hdevalence** [comment]
Since there's a blanket impl of `ToString` for `Display` types, the `Display` impls should be paired with `FromStr` impls and have property tests that check `ToString/FromStr` round trips.

**Comment by hdevalence** [comment]
(as an aside: writing that makes it really clear that `String` should have been called `StrBuf` :cry: )
