### ISSUE TITLE
Make clippy job work for dependabot PRs

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3477]
## Motivation

When a dependabot PR is opened, the Clippy job always fails with `Resource not accessible by integration`. Re-running the job manually makes it pass.

### Tasks

As Clippy posts annotations, it seems it has permission issues when done by Dependabot https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807852653

In the meanwhile, it seems this is the only (tested) workaround https://github.com/actions-rs/clippy-check/issues/2#issuecomment-807878478

1. Apply the workaround
2. Change the GitHub settings to require clippy to pass before merging

**Comment by teor2345** [comment]
I added Gustavo's analysis from https://github.com/ZcashFoundation/zebra/pull/3471#issuecomment-1031902698 to this ticket

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3477?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @upbqdn
