### ISSUE TITLE
Validate valueBalance consensus rule in deserialization.

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3478]
We have this consensus rule:

> [Sapling onward] If effectiveVersion = 4 and there are no Spend
> descriptions or Output descriptions, then valueBalanceSapling MUST be 0.

However we are not enforcing it in the deserialization. Check https://github.com/ZcashFoundation/zebra/pull/3461#discussion_r800772595 for more information. 

- [ ] Add code to check this rule
- [ ] Cite the rule next to the code

**Comment by teor2345** [comment]
The transaction v4 check for a zero value balance in empty sapling shielded data is here:
https://github.com/ZcashFoundation/zebra/blob/1a14baf8e7c6c82dba7a64e9b43d076b8f856f2a/zebra-chain/src/transaction/serialize.rs#L658-L663
