### ISSUE TITLE
Do not allow any kind of unwanted text when doing a manual `workflow_dispatch` 

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3494]
## Motivation

Some workflows expect a strict input (including case-sensitivity) like `Mainnet` or `Testnet`. We should not allow any other input for this scenarios,
### Designs

Use specific input types like `type: choice` and `type: boolean` for strict choices. Other inputs might need to be `required:true`

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3494?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @teor2345

**Comment by teor2345** [comment]
This seems to be fine for now, it's not causing any bugs.
