### ISSUE TITLE
Detect warnings, errors and panics in full sync test

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3500]
## Motivation

After we have the [full sync test ready](https://github.com/zcashfoundation/zebra/issues/1592#issuecomment-1032006501), we should expand the information it generates (and not just a pass/fail), by reacting to warnings, errors and panics.

### Specifications

The end goal here is not 100% defined and can be discussed with the team. A preliminary suggestion:

- If any errors or panics occur, fail the test
- Otherwise even if any warnings occur, the test passes (not sure about this one)
- In any of these cases, make the warnings/errors/panics easily available (in CI logs? Notify the team somehow?)

We already have `sentry` in place, which notifies some team members about panics. Check if that should be enhanced and/or replaced.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3500?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@gustavovalverde did you want to turn this into a discussion, then open specific tickets for any missing monitoring?

**Comment by gustavovalverde** [comment]
Fixed by: https://github.com/ZcashFoundation/zebra/pull/3968
