### ISSUE TITLE
Add lightwalletd full sync integration test

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3511]
## Motivation

Most `lightwalletd` RPC methods need a cached state to operate on.

We can construct these integration tests (modulo sending txs) with pre-synced/indexed state, so we don’t have to worry about mainnet/testnet weather.

## Tasks

- Attach a cached state disk to the lightwalletd integration tests
- Add a test harness that opens the cached state, but doesn't haven't have any configured seed peers
- Add a lightwalletd integration test for starts lightwalletd and waits for it to fully sync

**Comment by teor2345** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3511?planning-poker) with ZenHub @conradoplg @dconnolly @oxarbitrage @jvff @upbqdn

**Comment by teor2345** [comment]
We re-assigned this task to Conrado in yesterday's meeting.

**Comment by conradoplg** [comment]
This ended up mutating into a different ticket, I changed the description and copied some of the old description into https://github.com/ZcashFoundation/zebra/issues/4160
