### ISSUE TITLE
Check if anchorSapling is in the correct range

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3528]
## Motivation

We seem to have missed a consensus rule:

> Consensus rule: LEOS2IP 256 ( anchorSapling ), if present, MUST be less than 𝑞 J .

![image](https://user-images.githubusercontent.com/35766/153880884-7355489e-3bdc-490d-83d6-93710cc17957.png)

### Specifications

https://zips.z.cash/protocol/protocol.pdf#spendencodingandconsensus

### Designs

- Add the check, preferrably by changing the type of the `Root` to be a field element, thus forcing the validation. Check the Orchard code for reference.
- Can probably do https://github.com/zcashfoundation/zebra/issues/3224 at the same time

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3528?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
