### ISSUE TITLE
Coverage changes are inaccurate, because the job doesn't run on `main`

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3533]
## Motivation

> By the way, why does this PR change test coverage when it only edits comments? The bot says there will be 854 new hits.

## Suggested Solution

Our `main` branch coverage seems to be out of date, maybe we need to start running our coverage job on `main` again.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/3521#issuecomment-1039479864_

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3533?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
