### ISSUE TITLE
Published docs are outdated, because the job needs to run whenever we update code

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3534]
## Motivation

> The rustdoc-generated docs also change any time the Rust code changes, can we loosen this trigger restriction? This job doesn't take long

https://github.com/ZcashFoundation/zebra/pull/3516#discussion_r804731537

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3534?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn
