### ISSUE TITLE
Turn on full backtraces using COLORBT_SHOW_HIDDEN=1

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3536]
## Motivation

In #3489, the test failure was hard to diagnose, because `COLORBT_SHOW_HIDDEN=1` hid some of the function calls we needed to see.

### Specifications

> `COLORBT_SHOW_HIDDEN` env variable, disabling frame filtering

https://github.com/athre0z/color-backtrace/blob/master/CHANGELOG.md#v042-2020-05-19

## Related Issues

I wanted to fix this as part of #3489, but those CI configs are getting refactored in PR #3459

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3536?planning-poker) with ZenHub @conradoplg @gustavovalverde @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
