### ISSUE TITLE
Validate hashFinalSaplingRoot

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3565]
## Motivation

We missed a consensus rule, which is to validate `hashFinalSaplingRoot`. (Which entails two things: check if it's well-formed; e.g. if it's the encoding of an integer in the correct range; and if it actually matches the tree root for the treestate at the end of the block where it's contained. The second usually implies the first, but it may be useful to separate the checks)

### Specifications

![image](https://user-images.githubusercontent.com/35766/154374104-80737e64-4431-4c4f-bf70-3dee28f6dadc.png)

https://zips.z.cash/protocol/protocol.pdf#blockheader

### Designs

- [ ] Add the check. I believe it should be in `block_commitment_is_valid_for_chain_history`. This will require passing the Sapling root to it, but that can be done in `validate_and_commit`, but _after_ the block is pushed. You'll need to handle this somehow, since the history tree that is also passed to `block_commitment_is_valid_for_chain_history`  is the history tree _before_ the block is pushed. Also be aware that this is called by the finalized state too, but it should be similar.
- [ ] The best test is to simply sync the chain. I'm not sure if there is an easy way to test this.

Note that the "well-formed" check will already be done in `block.commitment()` in `block_commitment_is_valid_for_chain_history` after #3544 is merged

**Comment by teor2345** [comment]
@conradoplg do we need to validate this consensus rule?

We checkpoint on Canopy, so our checkpointer already validates all the `hashFinalSaplingRoot`s.

If we decide to skip this rule, we should document why we're skipping it.
(In whatever place made it look like it wasn't being validated.)

**Comment by conradoplg** [comment]
> @conradoplg do we need to validate this consensus rule?
> 
> We checkpoint on Canopy, so our checkpointer already validates all the `hashFinalSaplingRoot`s.
> 
> If we decide to skip this rule, we should document why we're skipping it. (In whatever place made it look like it wasn't being validated.)

Ah great point, I keep forgetting about that. Yes agreed, I'll change #3566 to cover what you mentioned and I'll close this issue.
