### ISSUE TITLE
Design Sprout note commitment trees.

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#36]
We may need a sprout note commitment tree, even if we checkpoint on sapling activation, in order to do sprout-on-groth16 proofs to move old sprout value.

**Comment by dconnolly** [comment]
Look at the one in `librustzcash`.

**Comment by hdevalence** [comment]
Changed the title so that this can correspond to items in the list for #123.

**Comment by dconnolly** [comment]
We may want to bring in the impl from librustzcash

https://github.com/zcash/librustzcash/blob/37270776beb10acd34bdd96dc6a4bb44117cb00a/zcash_primitives/src/merkle_tree.rs

**Comment by hdevalence** [comment]
depends on #273 #274

**Comment by dconnolly** [comment]
The 'design' part of this is basically contained in #983
