### ISSUE TITLE
Upgrade to halo2 -> halo2_proofs 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3600]
## Scheduling

This task must be done as part of:
- #2982

## Motivation

The `halo2` crate is being refactored, we may need to adjust how we use it.

### Designs

Try: 

```
halo2 = { package = "halo2_proofs", version = "=0.1.0-beta.2" }
```

"and then you only need to focus on the API changes, not renaming the imports everywhere."

Make sure that the `orchard` crate is updated and working accordingly, if needed.

**Comment by str4d** [comment]
See also [the changelog for `halo2_proofs 0.1.0-beta.2](https://github.com/zcash/halo2/blob/main/halo2_proofs/CHANGELOG.md#010-beta2---2022-02-14) for all of the API changes relevant to this upgrade.

**Comment by ftm1000** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3600?planning-poker) with ZenHub @dconnolly

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3600?planning-poker) with ZenHub @gustavovalverde @conradoplg @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
# Schedule note

This task must be done as part of:
- #2982

**Comment by teor2345** [comment]
#2982 moved sprints, but this linked task didn't.

Should we close this ticket, and move its details into #2982?

**Comment by conradoplg** [comment]
> #2982 moved sprints, but this linked task didn't.
> 
> Should we close this ticket, and move its details into #2982?

I missed this comment, sorry. Yep that makes sense, I copied the contents there and I'm closing this.
