### ISSUE TITLE
Fix "synced block height too far ahead of the tip: dropped downloaded block"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3603]
## Motivation

Sometimes Zebra downloads a block that is a long way ahead of the state tip. Currently, we're dropping those blocks, which can waste a lot of network bandwidth.

There are two cases we need to handle here:
1. the block is near the estimated tip, but the state tip is a long way from the estimated tip
2. the block is close to the state tip

Here is how we currently handle them:
1. drop the block, because verification would timeout anyway, and download it again in an hour or two
2. drop the block, and download it again a few minutes later

For the second case, we could pause extending tips instead.

### Designs

Syncer:
- add a state pipeline limit to the syncer, and wait for it after waiting for the download & verify lookahead limit
    - await the current state tip height changing in a loop, until we are under the limit
- only return a "too far ahead" error when the block is a very long way ahead of the tip

If we also get these errors from the inbound downloads, we could increase its limit, or just turn down the log level. (We can't pause the inbound downloads, because they are gossiped.)

## Related Work

- #3438 
- #3375 
- #3042

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3603?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This isn't causing us any issues right now.
