### ISSUE TITLE
GitHub Actions cache fails, causing "Build images" job to fail

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3665]
## Motivation

I keep seeing CI failures in "Build images" when running full sync tests, but they don't happen on every run.

> Error: buildx failed with: error: failed to solve: Get "https://artifactcache.actions.githubusercontent.com/iLo8c1TT59QRZKeUa4bO5aBdMPTRIlKlqwBwOSus1iy4D4L9OS/_apis/artifactcache/cache?keys=buildkit-blob-1-sha256%3A0c6b8ff8c37e92eb1ca65ed8917e818927d5bf318b6f18896049b5d9afc28343&version=693bb7016429d80366022f036f84856888c9f13e00145f5f6f4dce303a38d6f2": dial tcp 13.107.42.16:443: i/o timeout

https://github.com/ZcashFoundation/zebra/runs/5353953645?check_suite_focus=true#step:7:2528

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3665?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Also happened in PR #3668:
> Error: buildx failed with: error: failed to solve: error writing layer blob: Patch "https://artifactcache.actions.githubusercontent.com/iLo8c1TT59QRZKeUa4bO5aBdMPTRIlKlqwBwOSus1iy4D4L9OS/_apis/artifactcache/caches/19616": read tcp 10.1.0.82:52776->13.107.43.16:443: read: connection reset by peer


https://github.com/ZcashFoundation/zebra/runs/5364814787?check_suite_focus=true#step:7:1797

**Comment by teor2345** [comment]
Also happened in PR #3641, the error is slightly different:
> Error: buildx failed with: error: failed to solve: failed commit on ref "manifest-sha256:446e770f6ae99a4d1cd9de5e5916e8057ecca7d11ad6f4bc69499a0f4963bda9": cannot reuse body, request must be retried

**Comment by teor2345** [comment]
Probably also failed on #3647:
https://github.com/ZcashFoundation/zebra/runs/5383367400?check_suite_focus=true

**Comment by teor2345** [comment]
Failed in PR #3691:
https://github.com/ZcashFoundation/zebra/runs/5414784546?check_suite_focus=true#step:7:274
