### ISSUE TITLE
Investigate windows failure in rpc_conflict test

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#3666]
## Motivation

In https://github.com/ZcashFoundation/zebra/pull/3641 we added an `rpc_conflict` test to check an already in use port for the rpc server.

This test is failing on windows: https://github.com/ZcashFoundation/zebra/pull/3641#issuecomment-1053791732

## Scheduling

We are disabling the test for windows family but we will want to know what is going on exactly with it and potentially fix and enable the test for this platform. 

We only need to schedule this ticket if we decide to support Windows as a primary platform.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3666?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We only need to schedule this ticket if we decide to support Windows as a primary platform.

(We seemed to only want to promise primary support for Linux last time we talked.)

**Comment by gustavovalverde** [comment]
That's correct. And we even have to workaround some issues with Docker and Rust while using Windows https://github.com/rust-lang/docker-rust/issues/30

**Comment by oxarbitrage** [comment]
We are not supporting windows anymore by now, we can reopen if we decide to do so.
