### ISSUE TITLE
Fake activation heights test is not running in CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3673]
## Motivation

The fake activation heights job doesn't run any tests:
>  running 0 tests

https://github.com/ZcashFoundation/zebra/runs/5362650951?check_suite_focus=true

## Tasks

Maybe the test name, package, or `--lib` are wrong in the test command:
https://github.com/ZcashFoundation/zebra/blob/f8a4021c077d4f0b3204dd7cb8dc729522209244/.github/workflows/test.yml#L128

**Comment by gustavovalverde** [comment]
Based on this discussion https://github.com/ZcashFoundation/zebra/discussions/3683#discussioncomment-2276565, I'd prefer to use `runtime` environment variables to run this test. Otherwise we'd have to build a docker image specifically to fix this issue. 

I don't know the difficulty of doing it with environment variables, as it would require changes in Rust. Please let me know how to proceed with this one @teor2345

**Comment by teor2345** [comment]
> Based on this discussion [#3683 (reply in thread)](https://github.com/ZcashFoundation/zebra/discussions/3683#discussioncomment-2276565), I'd prefer to use `runtime` environment variables to run this test. Otherwise we'd have to build a docker image specifically to fix this issue.

I agree, runtime environmental variables would be easier and more efficient.

> I don't know the difficulty of doing it with environment variables, as it would require changes in Rust. Please let me know how to proceed with this one @teor2345

This is a complicated Rust change, because we need to change Zebra's hard-coded consensus parameters. (In particular, the network upgrade activation heights.) You can see the details in ticket #3238.

**Comment by teor2345** [comment]
We're focused on the lightwalletd work right now, so we need to keep Rust and DevOps scope small. But getting all our tests working is also important.

I can see these alternatives:
- run the tests in docker (extra DevOps work, and extra CI run time)
- run the tests on ubuntu or macOS runners, like we used to do before the CI refactor (extra CI run time)
- do the Rust fixes, and adjust scope elsewhere (extra risk?)
    - for example, we could add #3238 to this sprint, and remove #3375

Can we pay the extra compile-time cost for now, until we have time for #3238?
Or if we're happy with Zebra's sync speed, we could remove or delay #3375?

@conradoplg @jvff what do you think?

**Comment by teor2345** [comment]
Thinking about this a bit more...

Can we focus on these urgent bugs that are causing regular CI failures every day:
- #3665
- #3712 
- #3705

Once they are fixed, we'll be in a better position to make other changes.

**Comment by gustavovalverde** [comment]
I'll focus on the issues that are actually stopping PRs from getting merged, and then we'll retake this subject.

**Comment by jvff** [comment]
> @conradoplg @jvff what do you think?

I'm up for the Rust changes to allow the test to have the activation heights set through environment variables. I think the risk isn't too big, and it will also avoid increasing CI times. That said, there is the effort/scope to factor in, so I understand if we don't want to do this (yet?).

**Comment by conradoplg** [comment]
> @conradoplg @jvff what do you think?

I think it's possible that implementing https://github.com/ZcashFoundation/zebra/issues/3238 may be faster than discussing if it's worth doing it :rofl: Let me try to quickly implement it tomorrow and if it turns out it's complicated we can rethink this (I was going to do that today but ended up focusing on other stuff)

**Comment by conradoplg** [comment]
Created https://github.com/ZcashFoundation/zebra/pull/3749

**Comment by gustavovalverde** [comment]
Fixed by https://github.com/ZcashFoundation/zebra/pull/3749
