### ISSUE TITLE
CI fails on Ubuntu runners because all network connections fail

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3675]
## Motivation

Sometimes our Ubuntu CI fails because all network connections fail.

We get logs like this:
> INFO {zebrad="fd81e81" net="Main"}:add_initial_peers: zebra_network::peer_set::initialize: finished connecting to initial seed peers handshake_success_total=0 handshake_error_total=11 outbound_connections=0

https://github.com/ZcashFoundation/zebra/runs/5367124304?check_suite_focus=true#step:13:2022

This has been happening for a while, but all of the tests that depend on the network are disabled on Ubuntu.

### Scheduling

We can disable the affected tests for now, but it would be good to have test runners with reliable network connections.

**Comment by teor2345** [comment]
I'm marking this task as optional, because skipping the affected tests seems to work for now.

**Comment by gustavovalverde** [comment]
Closing until this is relevant.
