### ISSUE TITLE
Clean module layouts and imports.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#37]
As we flesh out the code, we're placing things in various parts of the module tree and importing various items from various paths, but as things take a clearer form we will have a better idea of the ideal logical structure of the module tree.   Before we do any release, we should do a reorganization pass to ensure that the module tree is conceptually coherent, and probably use re-exports to simplify presentation of the external module components to external crates.  However, it may not make sense to do this right now, while things are still in flux.

**Comment by hdevalence** [comment]
Tagged with `later` because we cannot have encapsulation until more of the parts are in place, and it's useful to be able to drive stuff with the `connect` stub.

**Comment by hdevalence** [comment]
`Poll::Pending` -> `Poll::Ready`

**Comment by hdevalence** [comment]
Potential refactorings/cleanups/simplifications:

- remove the `Peer` prefix on the contents of the `peer` module (i.e., `peer::Client` not `peer::PeerClient`);

- move the initialization functions in `peer_set.rs` into a submodule and just re-export the `init` function

**Comment by hdevalence** [comment]
Going to start working on this, hoping to slip it in before #118...

**Comment by hdevalence** [comment]
The remaining work for this ticket is to rename structs in the `peer_set` module.

**Comment by dconnolly** [comment]
Closed as done (I think???)
