### ISSUE TITLE
CI: build crates independently on Windows MSVC and MinGW

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3800]
## Motivation

We disabled Windows build in #3799 due to `zcash_script` requiring MinGW, and `rocksdb` requiring `rocksdb`.

But we could build and test crates independently, with different targets. With that, we at least would have some testing on Windows

### Designs

- [ ] Re-enable Windows build
- [ ] Change CI to build and test (on Windows):

- `zebra_script` with MinGW
- `zebra_state` with MSVC
- Any crates that import only one of these two with the matching compiler
- Any crates that import neither with both
- Skip any crates that import both

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3800?planning-poker) with ZenHub @gustavovalverde @conradoplg @dconnolly @teor2345

**Comment by teor2345** [comment]
We'll probably just fix the Windows build.
