### ISSUE TITLE
When "Test with fake activation heights" is skipped, Mergify hangs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#3827]
## Motivation

When the "Test with fake activation heights" job is skipped, Mergify hangs on the PR, because it is a required job in GitHub settings.

### Temporary Workaround

I removed the job from the required jobs in GitHub settings.

## Long-Term Fix

1. Do we need a patch workflow for "Test with fake activation heights"?
2. Restore this job as a required job in GitHub settings or Mergify

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3827?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
