### ISSUE TITLE
Remove duplicated zcash_proofs

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#3831]
## Motivation

We forked `zcash_proofs` because we need Sprout downloading support https://github.com/zcash/librustzcash/pull/459, which causes it to be duplicated as a dependency since other crates we use also import the upstream version.

### Designs

After the PR is merged upstream:

- Remove reference to the fork
- Remove the exceptions from `deny.toml`

**Comment by mpguerra** [comment]
removing from sprint as it seems like doing #5445 will fix this
