### ISSUE TITLE
Print lightwalletd output during integration test

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#3856]
## Motivation

Zebra currently consumes all of lightwalletd's output during the integration test. It would be useful to have that output also sent to the standard output so that debugging any issues is easier.

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/3856?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn
