### ISSUE TITLE
Orchard: ensure that ivk = 0 is rejected if that negligible case occurs 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#3869]
## Motivation

"In a pairing today, @Daira (ze/hir) and I discovered a bug in the orchard crate, that arose from the interaction of the fixes for the two circuit bugs that were found and fixed in zcashd 4.5.1. If we'd recognised this current bug at the time of those fixes, we'd probably have altered how we changed the circuit (but making that change now would be too noisy and require further analysis). As it is, we have a simple fix that just requires changing the outside-circuit code in orchard (to ensure that ivk = 0 is rejected if that negligible case occurs) and clarifying some type definitions in the protocol spec. https://github.com/zcash/orchard/issues/294 "

### Specifications

https://github.com/zcash/orchard/issues/294

So we need to map the identity to an error, not just the ⊥, in 
https://github.com/ZcashFoundation/zebra/blob/5e1fd4b2d6dd663b0c67968c20f8e420f14d9d9b/zebra-chain/src/orchard/keys.rs#L655

## Related Work

https://github.com/zcash/orchard/issues/294

**Comment by conradoplg** [comment]
The spec changes affects two places:

- Orchard key generation
- Incoming viewing key parsing

Which are either not supported, or not used in regular node usage in Zebra. (The closest I could think of is the consensus rule that shielded coinbase txs must be decryptable with an all-zero outgoing viewing key, but that's not affected by the spec change)

Therefore we don't need to do this now, and can schedule this maybe for the wallet epic. @dconnolly can you please check if this reasoning is correct?
