### ISSUE TITLE
actions: some checks are failing as the github-slug-action is returning variable results 

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3921]
## Description

The action used to get a shortened SHA in most workflows has been recently changed as it's not using a fixed version, and the action is sometimes returning a SHA with a length of 7 and sometimes with a length of 8, which crashes some actions.

### Steps to Reproduce

```yaml
- name: Inject slug/short variables
  uses: rlespinasse/github-slug-action@v4
```

### Expected Behaviour

Always use the same length on all the available steps in an action

### Actual Behaviour

See this examples:

Correct len(7) for GITHUB_SHA_SHORT: https://github.com/ZcashFoundation/zebra/runs/5618372155?check_suite_focus=true#step:3:977

Wrong len(8) for GITHUB_SHA_SHORT: https://github.com/ZcashFoundation/zebra/runs/5618372108?check_suite_focus=true#step:3:1017

**Comment by teor2345** [comment]
This seems to be blocking all PR merges, so I'd like it to be critical priority.

**Comment by gustavovalverde** [comment]
I'll get this one done today.
