### ISSUE TITLE
ci: run a full lightwalletd sync from a close-to-tip zebrad

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#3926]
## Motivation
On every PR push, if the zebrad state format hasn’t changed, we want to run a full lightwalletd sync from a close-to-tip zebrad, as a test. This test should take 30 minutes

### Designs

- Lightwalletd updates from zebrad in less than half an hour, so that part of the test can be  run on every PR change
- This approach would use already generated disks from previous stateful disk generations job https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/test.yml#L213
- A `lightwalletd-test.yml` might be appropriate from this point on and move specific lightwalletd tests here.

## Related Work
https://github.com/ZcashFoundation/zebra/issues/3922

**Comment by teor2345** [comment]
Is this the same as #3511?

**Comment by gustavovalverde** [comment]
@teor2345 I added #3511 as a dependency. Considering the test must be created (#3511) and then added to the CI (#3926)

**Comment by teor2345** [comment]
This is a high priority, because it is on the critical path, and blocking other lightwalletd integration tests.
