### ISSUE TITLE
restructure `zebra_network::init` to propogate all errors back to the caller

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#408]
The current design of `zebra_network::init` spawns multiple background tasks via tokio. When spawning background tasks you have two options for handling errors, either handle them in the task or propogate them via the JoinHandle. The background handling is the current option we employ, where if the task ends in an error we print it to the terminal immediately and exit the task.

The downside of this is that the errors can be overlooked, especially if there's any large amount of output to the terminal from other tasks before the process finally exits.

I believe we should instead support both options by returning a wrapper around all the join handles back to the user. This way they can choose to drop the join handles, thus getting the background logging they want, or they can await them when their application is ready to shutdown gathering up all of the results for each task. Once they have the set of results they can propogate them back up the stack in an orderly shutdown letting them get nice error reports at the end of their terminal output (or whatever io channel they use).

Likewise, once this propogation support is in place I think we should choose to propogate instead of background log errors from zebra_network in zebrad.

**Comment by hdevalence** [comment]
:tada: nice work on this!
