### ISSUE TITLE
ci: improve mergify's merge queue throughput

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4092]
## Motivation

A single PR can take up to 6 hours merging (if a Full Sync is triggered)/

Having multiple PRs waiting for review and not having those getting into a queue at the same time, would commonly mean a serialized merge (6 hours per PR). Even if the reviews happen on the same day, based on the priority label, we could have 4+ PRs taking ~2 days just merging.

### Designs
- Reduce the amount of queues. Maybe 2 queues are enough (hotfixand changes and improvements)
- Increase the time mergify waits before queueing PRs together
- Increase the amount of speculative_checks and batch_size to 3 and 5 respectively for all queues in mergify
- Set allow_checks_interruption to true in mergify, as this would allow for hotfixes to be merged faster

**Comment by teor2345** [comment]
> * Set allow_checks_interruption to true in mergify, as this would allow for hotfixes to be merged faster

If we do this, I'd like to only interrupt other PRs for critical fixes.
That means all other priorities go in the changes queue.
