### ISSUE TITLE
Improve API to spawn processes for tests

### ISSUE THREAD

**Issue by jvff** [ZcashFoundation/zebra#4093]
## Motivation

Currently tests use an extension trait to spawn sub-processes. The extension trait is implemented for directory paths (including `tempfile::TempDir`). This might be a bit confusing, and it would perhaps be clearer to use the `TestChild` type directly.

### Designs

This is still an open question, but one idea is to have a `TestChild` constructor that receives the directory to spawn the process in.

**Comment by teor2345** [comment]
We don't need to do this yet, and we can re-open it if we need to later.

**Comment by ftm1000** [comment]
Issue to be revisited at a later time. Closing ticket
