### ISSUE TITLE
ci: refactor most pipelines to make use of reusable workflows

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4106]
## Motivation

We're not following the DRY principle with the pipelines, as most workflows have at least a 20% of repeated steps, and we're moving into a stage were we need to have more workflow segregation, for example moving all the disk rebuild steps to their own workflow, but by doing this we would also create even more repetition and code harder to maintain.

### Specifications

https://docs.github.com/cn/actions/using-workflows/reusing-workflows

### Designs
- Create a workflow for building docker images (`docker-build.yml`)
- Make other workflows that require a docker image to run tests or for deployment depend on `docker-build.yml`
- Move disk rebuild steps/jobs to their own workflow, allowing to run this workflow without triggering other tests
- Merge the Full sync workflow with the Integration Tests as the paths used to run this workflows is basically the same

## Related Work
[refactor(actions): rename workflow files](https://github.com/ZcashFoundation/zebra/pull/3941#) #3941
[Skip duplicate GitHub actions](https://github.com/ZcashFoundation/zebra/issues/1786#) #1786

**Comment by teor2345** [comment]
> Merge the Full sync workflow with the Integration Tests as the paths used to run this workflows is basically the same

If we're going to remove a bunch of paths from the full sync workflow, we might not want to do this step.

**Comment by teor2345** [comment]
Would it be helpful to move some of the google cloud and docker scripts into shell script files?

It seems like some of those scripts are getting really complex, so it might help to be able to run them separately.
