### ISSUE TITLE
ci: GCP workflows fail with missing container names, due to mounting cached disk partition

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4114]
## Motivation

Some Zebra workflows repeatedly fail due to a missing container error:
> Error: No such container: klt-regenerate-disk-4038-merge-9969dc2-bfnh

https://github.com/ZcashFoundation/zebra/runs/6007481272?check_suite_focus=true#step:10:115

But the container actually exists - it's the partitions on the image that trigger a bug in Google Cloud.

### Underlying Infrastructure Bug

TODO: @gustavovalverde knows the details here.

**Comment by teor2345** [comment]
I turned full validation sync off in GitHub branch protection due to this bug.

**Comment by teor2345** [comment]
This bug is not actually fixed in some workflows, see PR #4190:
> Error: No such container: klt-sync-checkpoint-4190-merge-472f067-wbuf

https://github.com/ZcashFoundation/zebra/runs/6160856472?check_suite_focus=true#step:9:116

**Comment by gustavovalverde** [comment]
This has been a bit difficult to track, so far this is related to the `cached disk`, the container complains with this error just when a disk with a cached state is mounted.

**Comment by gustavovalverde** [comment]
Related piece of code with the issue https://github.com/GoogleCloudPlatform/konlet/blob/9cb9106daf07123c2641159cb8bcc9d6f4960ec2/gce-containers-startup/volumes/volumes.go#L549
