### ISSUE TITLE
Set the minimum network protocol version to `170_050` for NU5 testnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4116]
## Motivation

On testnet, Zebra should always reject pre-NU5 nodes.

### Scheduling

We need to wait for:
- NU5 testnet activation - around April 22
- Enough NU5 nodes to be deployed on testnet

## Tasks

- Update the `INITIAL_MIN_NETWORK_PROTOCOL_VERSION` to `Testnet, Nu5`

**Comment by conradoplg** [comment]
The minimum version should be 170_040, right?

Closed by https://github.com/ZcashFoundation/zebra/pull/3976

**Comment by teor2345** [comment]
`170_040` is a fake version that rejects all pre-NU5 nodes. (The previous released version was `170_017`.)

So technically this ticket is closed, because there are no nodes between `170_040` and `170_050`.
But the specific code change in the ticket hasn't been done yet.

We can fix this up when we do the NU5 mainnet version fix in #4117.
