### ISSUE TITLE
Merge Freeze causes all Mergify PRs to fail

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4137]
## Motivation

When we do a release, we want to:
- stop most PRs from merging
- allow the release PR in GitHub
- allow the release PR in Mergify

Currently:
- we can un-freeze the release PR, but we can't un-freeze the Mergify PR in advance
- if we set Merge Freeze as a branch protection rule, all Mergify PRs fail, before we can un-freeze them
- if we don't set Merge Freeze as a branch protection rule, any PR can merge (but they show as failed)

(We can change the Merge Freeze config so it automatically adds a pending branch protection rule, but then we can't make exceptions for any PRs. So all PRs would be blocked.)

### Designs

We could choose one of these options:
- always manually merge un-frozen PRs, and skip the Mergify checks (or run them manually),
- remove the Merge Freeze branch protection rule, so it is advisory,
- ask Merge Freeze to add an API to un-freeze matching PRs in advance, or
- try another freeze tool that works differently.

**Comment by gustavovalverde** [comment]
A possible fix is changing this to true:
https://github.com/ZcashFoundation/zebra/blob/5054e048d4c8ef0b310f06bb9c1ee469c6145754/.github/mergify.yml#L3

As this would allow mergify to use the already opened PR to make the merge. The whole team would have to log in at least once into https://dashboard.mergify.com/ so the merges get authored by us and not by Mergify's bot (which was the main reason to set this to false)

**Comment by teor2345** [comment]
> A possible fix is changing this to true:
> 
> https://github.com/ZcashFoundation/zebra/blob/5054e048d4c8ef0b310f06bb9c1ee469c6145754/.github/mergify.yml#L3
> 
> As this would allow mergify to use the already opened PR to make the merge. The whole team would have to log in at least once into https://dashboard.mergify.com/ so the merges get authored by us and not by Mergify's bot (which was the main reason to set this to false)

This seems like it's worth a try!
