### ISSUE TITLE
Re-use cached state with the same version from any branch

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4153]
## Motivation

In PR #4074, we check for unexpected state versions before running Google Cloud tests.

But we want tests to re-use the previous cached state with the same version.

### Designs

We want to re-use the cached state from any branch, as long as:
- the state version is the same, and
- the state kind (checkpoint or tip) is the same.

If there is a state with that version on `main`, and on another branch, use the one from `main`.

If a cached state with that version can't be found, the state should be rebuilt.
(We currently check for changes to the state version `constants.rs` Rust file, but we should check for a matching cached state version instead.)

And then the tests should be run with that new state.

### Out of Scope

Old cached state versions should be cleaned up:
- when the `main` branch has a higher state version.

I'm not sure what we should do if a previous cached state version has a bug. But we can make this decision later, because we only have one state version change planned, and it is a low priority.

As a workaround, we can change the state version in the code, which will regenerate a new cached state.

## Related Work

- #3881 
- #4074

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/4153?planning-poker) with ZenHub @conradoplg @dconnolly @gustavovalverde @teor2345
