### ISSUE TITLE
ci: call lightwalletd wallet queries

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4168]
## Motivation

We need to call the `lightwalletd_wallet_grpc_tests` tests from #3655 in CI, using the lightwalletd cached state from #4165.

(PR #4267 already added the tests from #3512.)

**Comment by teor2345** [comment]
@gustavovalverde I re-opened this ticket, because we still need to call the `lightwalletd_wallet_grpc_tests` in CI.
