### ISSUE TITLE
ci: refactor test workflows to use a DRY/matrix approach

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4239]
## Motivation

We have a bunch of workflow code repeating to execute almost the same tasks, for example the following jobs have over a 100 line of codes, and both are almost a **replica**:
- `test-full-sync`
- `test-stateful-sync`

This also happens with:
- `test-all`
- `test-fake-activation-heights`
- `test-empty-sync`
- `test-lightwalletd-integration`
- `regenerate-stateful-disks`

This same behavior is repeating with:
https://github.com/ZcashFoundation/zebra/pull/4223

### Designs

- As most test doesn't share a standard cli execution, this makes pipeline standardization a bit harder
- Using `entrypoint.sh` can workaround most of this issues. And might be the ideal solution until a more standardize way of executing the test is created within zebra/rust/cargo.
- All tests can have an execution variable with an specific nomenclature

## Related Work

https://github.com/ZcashFoundation/zebra/pull/4237

**Comment by teor2345** [comment]
Can this wait until after we've finished the next few lightwalletd integration tests?
* fully synced RPC
* generate lightwalletd cached state
* use lightwalletd cached state

Then we'll know the parameters the matrix or sub-workflow needs.

If we try to do this refactor now, we could end up adjusting parameters a lot, in multiple places.
