### ISSUE TITLE
Add missing wallet grpc tests

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#4278]
In https://github.com/ZcashFoundation/zebra/pull/4253 we added tests for grpc wallet methods, however we left a few `TODO`s in the main file (`zebrad/tests/common/lightwalletd/wallet_grpc_test.rs`)for missing tests.

This ticket is for add them:

- [ ] #4362
- [x] #4350
- [x] #4351
    - #3990
    - ECC implementing parsing and gRPC in https://github.com/zcash/lightwalletd
    - Aditya merging those changes to https://github.com/adityapk00/lightwalletd

The stream ones should be easy, the tree state should also be easy after #3990 is in place. Mempool ones are harder as we will have to add some transaction to the mempool from the test (idea: need to use code from `zebrad/tests/common/lightwalletd/send_transaction_test.rs`)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/4278?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
There's just one sub-ticket left here, so I'm going to close this tracking issue.
