### ISSUE TITLE
Truncate branch name when used in Google Cloud names

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4295]
## Motivation

Zebra's DevOps workflows fail on long branch names:
> ERROR: (gcloud.compute.images.create) Could not fetch resource:
> - Invalid value for field 'resource.name': 'zebrad-cache-increase-block-validation-timeouts-0eb6a83-v23-mainnet-tip'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

https://github.com/ZcashFoundation/zebra/runs/6283701351?check_suite_focus=true#step:10:69

It would be good to fix this eventually, but it's not urgent.

### Designs

- truncate branch names before using them in length-limited contexts (in this case, we can only use 24 characters)

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/4295?planning-poker) with ZenHub @conradoplg @dconnolly @jvff @oxarbitrage @teor2345 @upbqdn

**Comment by dconnolly** [comment]
> ## Motivation
> Zebra's DevOps workflows fail on long branch names:
> 
> > ERROR: (gcloud.compute.images.create) Could not fetch resource:
> > 
> > * Invalid value for field 'resource.name': 'zebrad-cache-increase-block-validation-timeouts-0eb6a83-v23-mainnet-tip'. Must be a match of regex '(?:a-z?)'
> 
> https://github.com/ZcashFoundation/zebra/runs/6283701351?check_suite_focus=true#step:10:69
> 
> It would be good to fix this eventually, but it's not urgent.
> 
> ### Designs
> * truncate branch names before using them in length-limited contexts (in this case, we can only use 24 characters)

Yep I'm good with 'just' truncating the branch names, that is still helpful to a human to distinguish branches

**Comment by teor2345** [comment]
This made a full/checkpoint sync test fail:
https://github.com/ZcashFoundation/zebra/runs/7535292198?check_suite_focus=true#step:8:70

So I'm marking it as medium priority.

**Comment by teor2345** [comment]
We fixed long branch names in image names in PR #4962.

We also use these long branch names in instance and disk names, but the other text is much shorter, so they can be 30+ character. If that limit becomes a problem, we can open another ticket to fix the failing usage.
