### ISSUE TITLE
Set RUST_LOG environmental variable in gcp-test-deploy.yml

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4305]
## Motivation

We can't see when GCP tests are being skipped, because the test logs aren't active in gcp-test-deploy.yml

### Designs

Use the same logging environmental variables as the build workflows:
```
RUST_BACKTRACE="full"
RUST_LIB_BACKTRACE="full"
COLORBT_SHOW_HIDDEN="1"
ZEBRA_SKIP_IPV6_TESTS="1"
RUST_LOG="info"
```

We should hard-code these values for now.

**Comment by gustavovalverde** [comment]
Most of this variables are being set at build time, and available in the containers:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/16890942/166858947-54004d0c-f913-4519-95b6-a438d0b4b360.png">

Those are being set here: https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/docker-image-build.yml#L116

**Comment by teor2345** [comment]
We need `RUST_LOG="info"` to see which tests have been skipped
