### ISSUE TITLE
ci: Require successful lightwalletd integration tests for PRs to merge

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4340]
## Motivation

We're running a lot of lightwalletd integration tests in CI, but most of them are not required to merge.

While we are actively working on lightwalletd, we should require all the tests to pass before merging.

## Designs

- We'll need a patch job for each test
- Then we need to add the tests to the `main` branch protection rule

### List of Remaining Tests

Zebra:
- [x] Zebra checkpoint / Run sync-to-checkpoint test
- [x] Zebra checkpoint / Run sync-past-checkpoint test
- [x] Zebra tip / Run full-sync-to-tip test

Lightwalletd:
- [x] lightwalletd tip / Run lwd-full-sync test
- [x] lightwalletd tip / Run send-transactions test (sp?)
- [x] lightwalletd tip / Run lwd-update-tip test (sp?)
- [x] lightwalletd tip / Run lwd-grpc test (sp?)

### Non-Lightwalletd Tests

- [x] Coverage on stable

**Comment by ftm1000** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/4340?planning-poker) with ZenHub @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@gustavovalverde I can do this ticket if you'd like. Are there any blockers?

I can start on the tests that are already in CI, and do new ones as they are added.

**Comment by gustavovalverde** [comment]
You can go ahead if you'd like. This one has to be merged first, as it's causing the tests not to run:
- https://github.com/ZcashFoundation/zebra/pull/4364

**Comment by teor2345** [comment]
This is now done in the GitHub settings for Zebra.
