### ISSUE TITLE
Summarise the environmental variables used to activate `zebrad` acceptance tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4363]
## Motivation

Some `zebrad` acceptance tests need special state to run, they get skipped when it is not available.

We want to document:
- the state requirements for each group of tests (lightwalletd binaries, zebra or lightwalletd cached state)
- the environmental variables (or Rust features) used to run each test
- the environmental variables and command line flags used to see test messages (`RUST_LOG=info cargo test -- --nocapture`)
- the required lightwalletd binary - https://github.com/adityapk00/lightwalletd

We can add these docs to the top of `acceptance.rs`.

### Designs

If the environmental variables aren't set, most tests skips themselves, and logs a message.

Some tests use a Rust feature instead, but we're trying to move away from that.

**Comment by oxarbitrage** [comment]
I think this issue will be a lot more clear if you just had said that you want to document what the CI do.
