### ISSUE TITLE
Automate pinning CI dependencies to specific commit hashes

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#4412]
## Motivation

It'd be nice to be able to manage our CI actions and other dependencies like we do with our cargo etc deps. 

The newish https://github.com/sethvargo/ratchet may help us do that.

**Comment by gustavovalverde** [comment]
I know this is a security measure, but it worries me how readable this would be to know in which version we are from a specific GitHub action. This has been opened for a almost a year, but feel free to reopen it @dconnolly if you feel we should do this in the short term. I'll close it as not planned to have it in a long term scope

**Comment by teor2345** [comment]
> I know this is a security measure, but it worries me how readable this would be to know in which version we are from a specific GitHub action. This has been opened for a almost a year, but feel free to reopen it @dconnolly if you feel we should do this in the short term. I'll close it as not planned to have it in a long term scope

This was my concern as well, part of security is being clear about what we depend on, and being able to review changes.

We could wait until GitHub or another project creates better tooling?
