### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ruzcash** [ZcashFoundation/zebra#4433]
## Description

Hello! I'm trying to install Zebra and I'm getting the error at the very end of compilation:

Compiling zebra-consensus v1.0.0-beta.9 (/home/ak/.cargo/git/checkouts/zebra-d0d93d7ded255019/c190e30/zebra-consensus)
Compiling zebra-rpc v1.0.0-beta.9 (/home/ak/.cargo/git/checkouts/zebra-d0d93d7ded255019/c190e30/zebra-rpc)
error: there is no argument named `address`
   --> zebra-rpc/src/methods.rs:829:69
    |
829 |                     Error::invalid_params(&format!("invalid address {address:?}: {error}"))
    |                                                                     ^^^^^^^^^^^

error: there is no argument named `error`
   --> zebra-rpc/src/methods.rs:829:82
    |
829 |                     Error::invalid_params(&format!("invalid address {address:?}: {error}"))
    |                                                                                  ^^^^^^^

error: there is no argument named `method`
  --> zebra-rpc/src/server/tracing_middleware.rs:44:37
   |
44 |                 format!(r#"method = {method:?}, params = {params:?}"#)
   |                                     ^^^^^^^^^^

error: there is no argument named `params`
  --> zebra-rpc/src/server/tracing_middleware.rs:44:58
   |
44 |                 format!(r#"method = {method:?}, params = {params:?}"#)
   |                                                          ^^^^^^^^^^

error: there is no argument named `method`
  --> zebra-rpc/src/server/tracing_middleware.rs:47:43
   |
47 |                 format!(r#"notification = {method:?}, params = {params:?}"#)
   |                                           ^^^^^^^^^^

error: there is no argument named `params`
  --> zebra-rpc/src/server/tracing_middleware.rs:47:64
   |
47 |                 format!(r#"notification = {method:?}, params = {params:?}"#)
   |                                                                ^^^^^^^^^^

error: there is no argument named `call_description`
  --> zebra-rpc/src/server/tracing_middleware.rs:66:64
   |
66 |             tracing::warn!("Received unrecognized RPC request: {call_description}");
   |                                                                ^^^^^^^^^^^^^^^^^^

error: could not compile `zebra-rpc` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `zebrad v1.0.0-beta.9 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-beta.9#c190e302)`, intermediate artifacts can be found at `/tmp/cargo-install6Pk0SQ`

Caused by:
  build failed

### Zebra Version

Zebra 1.0.0-beta.9

### Operating System

Ubuntu 20.04.4 LTS 64-bit GNOME 3.36.8

**Comment by conradoplg** [comment]
Thanks for reporting this!

Ubuntu 20.04 ships Rust 1.57, and Zebra now requires 1.58, but we didn't specify that in the build and documentation. We'll address that in the next release.

You will need to uninstall the packaged Rust (`apt remove cargo rustc`) and install a newer version by following https://www.rust-lang.org/tools/install

**Comment by ruzcash** [comment]
Thank You, I will write about results.

**Comment by ruzcash** [comment]
Problem solved, thanks again!
Zebra is already syncing!
