### ISSUE TITLE
failed to find tag v1.0.0-beta.10

### ISSUE THREAD

**Issue by yawnbox** [ZcashFoundation/zebra#4441]
## Description

Attempting to update from beta 9 to beta 10.
This link 404's: `https://github.com/ZcashFoundation/zebra/releases/tag/v1.0.0-beta.10`

### Steps to Reproduce

I tried this:

`$ cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-beta.10 zebrad`

### Actual Behaviour

```$ cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-beta.10 zebrad
    Updating git repository `https://github.com/ZcashFoundation/zebra`
error: failed to find tag `v1.0.0-beta.10`

Caused by:
  reference 'refs/remotes/origin/tags/v1.0.0-beta.10' not found; class=Reference (4); code=NotFound (-3)```

**Comment by oxarbitrage** [comment]
Please retry, i just published the release tag: https://github.com/ZcashFoundation/zebra/releases/tag/v1.0.0-beta.10

**Comment by yawnbox** [comment]
Confirmed working. Thank you!
