### ISSUE TITLE
Decide on supported platforms and test in CI

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4448]
## Motivation

We should decide which platforms we will officially support, and test it in CI.

### Designs

- [ ] Decide which platforms (OS distribution, CPU, Rust version, C/C++ compiler, packaging system) we want to support
- [ ] Add tests in CI for those that we don't test already

**Comment by teor2345** [comment]
I added the following parts to the platform:
* OS distribution
* C/C++ compiler
* packaging system
