### ISSUE TITLE
ci: create documentation on how to run tests locally for development purposes

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4464]
## Motivation

Developers might want to run CI tests locally on their machine, so they don't have to wait for the CI if they have faster machines or available cached states locally.

We should create documentation on how to this with Docker and/or a script to automate the whole process when passing environment variables.

### Designs

- A Docker documentation or a docker-compose file with the needed steps to run certain tests and rebuild accordingly
- A script to run locally and ensure all the needed dependencies are set and allow to pass arguments to run different tests

**Comment by teor2345** [comment]
This doesn't seem to be a priority for the Zebra project right now, but we can re-open it if it becomes one.

**Comment by mpguerra** [comment]
reopening for #5430

**Comment by teor2345** [comment]
This seems almost the same as #7534?
