### ISSUE TITLE
Support getblock with verbosity=1

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4480]
## Motivation

To workaround a lightwalletd issue related to V5 TXIDs, it was [recently changed](https://github.com/zcash/lightwalletd/pull/393/files) to get the transactions IDs using a `getblock` call with `verbose=1`.

That was the cause of one of the issues found during ZecWallet Lite + lightwalletd + Zebra tests on Testnet, so we might want to support that so we can test it further.

### Designs

Add support for `verbose=1`. Note that we just need the `tx` field (the list of TXIDs) for now.

Testing:
- Add a snapshot test for `verbose=1`.
- Manually run `zcash-rpc-diff` with `verbose=1`

**Comment by teor2345** [comment]
I added:

Testing:
- Add a snapshot test for `verbose=1`.
- Manually run `zcash-rpc-diff` with `verbose=1`
