### ISSUE TITLE
Project/assign automation fails with "Parameter token or opts.auth is required"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#449]
It looks like the Project/assign automation in PR #441 doesn't work for me, I see:
```
##[error]Parameter token or opts.auth is required
```
in https://github.com/ZcashFoundation/zebra/pull/448/checks?check_run_id=748611278

**Comment by dconnolly** [comment]
I think I'm going to tear this out, it doesn't work on external prs because of permissions and should never 'fail a build' if it breaks.

**Comment by dconnolly** [comment]
Try this instead
https://github.com/apps/project-bot
