### ISSUE TITLE
NU5: Monitor estimated activation time based on current and activation block height

### ISSUE THREAD

**Issue by ftm1000** [ZcashFoundation/zebra#4507]
Motive:
Monitor the network activation to determine when it will actually happen, as follows:

Monitor the network upgrade activation

To do that, periodically subtract the current block height (get it from a block explorer or a synced node) from the activation height, and multiply by 75 seconds. (The target block interval.) Divide by (`60*60*24`) to get the number of days before activation.

**Comment by conradoplg** [comment]
We can use this command (substitute the current height from e.g. https://zcashblockexplorer.com/)

```
python -c 'import datetime; print((datetime.datetime.utcnow() + datetime.timedelta(seconds=((1687104 - CURRENT_HEIGHT) * 75))).isoformat())'
```

Current estimate is 2022-05-31T16:58:51 UTC

**Comment by conradoplg** [comment]
Current estimate is 2022-05-31T17:43:43 UTC

**Comment by conradoplg** [comment]
2022-05-31T17:45:50 UTC

**Comment by conradoplg** [comment]
Activated!
