### ISSUE TITLE
NU5: Check the Foundation’s DNS seeder has enough updated nodes

### ISSUE THREAD

**Issue by ftm1000** [ZcashFoundation/zebra#4508]
Motive:
Load Zebra’s DNS seeder network protocol version dashboard.

Check that the Foundation’s DNS seeders have enough peers on the new network protocol version on mainnet/testnet.

**Comment by teor2345** [comment]
I just did this, there aren't as many NU5 nodes as we'd like, due to this known DNS seeder bug:
- [Enforce the minimum protocol version](https://github.com/ZcashFoundation/dnsseeder/issues/10)

But it is ok for now.
