### ISSUE TITLE
NU5: Test the activation by keeping Zebra running

### ISSUE THREAD

**Issue by ftm1000** [ZcashFoundation/zebra#4509]
- [ ] Keep your local Zebra rode nunning through activation (anyone interested can do this)
- [ ] [Deploy](https://github.com/ZcashFoundation/zebra/actions/workflows/continous-delivery.yml) a Zebra beta.10 node before the activation with enough time for it to sync (monday? or maybe earlier to be sure)
- [ ] Check the logs for errors and to verify it keeps syncing

**Comment by conradoplg** [comment]
[Deploying a beta.10 mainnet node](https://github.com/ZcashFoundation/zebra/actions/runs/2410623015)

**Comment by conradoplg** [comment]
It seems deploying from a tag is not working right now, [deploying from main](https://github.com/ZcashFoundation/zebra/actions/runs/2411825703)

**Comment by conradoplg** [comment]
It's  `zebrad-main-bfa319d` on GCP

**Comment by conradoplg** [comment]
We ended up not being able to deploy on GCP due to #4546 but me, @upbqdn and @dconnolly kept Zebras running and everything went smoothly :tada:
