### ISSUE TITLE
Document how to use Zebra as a lightwalletd backend

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4513]
## Motivation

Some people were interested in the Zebra/lightwalletd integration but I realized there is no documentation to point them to.

### Designs

Describe how to use Zebra as a lightwalletd backend (probably somewhere in https://zebra.zfnd.org/user.html, and we could point to it in the README)

Here is a similar `zcashd` RPC config guide:
https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html#json-rpc-options

And the existing lightwalletd guide, which we could link to:
https://zcash.readthedocs.io/en/latest/rtd_pages/lightclient_support.html

**Comment by teor2345** [comment]
Nice catch!

Here is a similar `zcashd` RPC config guide:
https://zcash.readthedocs.io/en/latest/rtd_pages/zcash_conf_guide.html#json-rpc-options

And the existing lightwalletd guide, which we could link to:
https://zcash.readthedocs.io/en/latest/rtd_pages/lightclient_support.html
