### ISSUE TITLE
Handle chain reorganisations

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#452]
Edit:

See PR #763 for the latest design, which avoids chain reorganisations by storing all the tips in memory.

-----

Depends on block validation #428 and maybe block checkpointing #429.

Here's a draft API for chain reorganisation:

Most ZebraState users will want the following current chain API:
* GetTip() -> hash
  * returns the tip for the current chain
* GetHashAtHeight(height) -> hash
  * returns the hash for the current chain

This API can be shared between zebra-consensus and other users:
* GetBlock(hash) -> block
* GetHeight(hash) -> u32
  * derived from the block, but it requires a transaction search, so it could be expensive
* GetParent(hash) -> hash
  * derived from the block header, but the header is 1.5 kB, so it could be expensive
* we could write wrapper service for non-consensus users, which returns an error if the hash isn't on the current chain. That way, futures the depend on side-chains are automatically cancelled.

zebra-consensus will also want:
* GetCumulativeWork(hash) -> (cumulative_work)
* AddBlock(block, hash, cumulative_work)
* SetTip(hash)
  * replaces the current chain with the chain that ends in hash
  * when we have transaction state:
    * undo all the blocks that are in the old chain
    * apply all the blocks that are in the new chain
* PruneSideChain(hash)
  * delete the block that ends in hash, and all of its ancestors that aren't on any other chains
  * typically happens 100 blocks after a fork
  * may also happen under memory pressure?
* GetSideChainTipList() -> [hash]
  * if we support the get_tips() RPC call, then it will be `[GetTip()] + GetSideChainTipList()`.

See https://github.com/ZcashFoundation/zebra/issues/452#issuecomment-644493202 for example API usage and pseudocode.

Here are the state invariants we'll maintain:
* the state only contains valid blocks
* each block must chain back to the genesis block (or a checkpoint hash)
* there is one chosen block at each height in the state
* if there are multiple competing chains, zebra-consensus chooses the chain with the largest cumulative proof of work, breaking ties with the earliest block received

To work out when we need to do a chain reorganisation, we'll need to keep a list of side-chain tips. (We'll prune side-chains once they get too old.)

It might also help to store the cumulative proof of work for each tip. (Or store the tips in order of work.)

During a reorganisation, we'll need to revert all the state changes in a set of blocks, and then redo the changes from a different set of blocks. If we design the state well, this should be a reasonably inexpensive operation. (Because we won't need to re-fetch or re-validate blocks.)

To handle chain reorganisations, we need to answer these kinds of questions:
- [x] What if there are two blocks with the same parent? Or two chains with the same length?
  - [x] Which block is the tip?
    - zcashd has a get_tips() API, which returns a set of tips
  - [x] Is there a preferred tip?
      - The tip with the greatest cumulative work is the best. Ties are broken by choosing the block that the node received first. (Not the miner-supplied timestamp in the block header.)
  - [ ] In Zebra, should we choose the block that validates first? Or should we attach a timestamp to each block?
- [x] What's the threshold for discarding the blocks in orphaned chains?
  - after >=100 blocks, the zcashd block chain reorg limit
- [x] How do we clean up non-chain blocks (and expired transactions)?
  - after they are orphaned, drop them from the state and mempool

Here is some background info:

**Largest permitted reorgs**

The bitcoin and zcash coinbase maturity rule is 100 blocks:
https://github.com/zcash/zcash/blob/63c3d1ec9435b445a883028b9111595ffa9292d4/src/consensus/consensus.h#L30

zcashd will only accept 99 block chain reorgs:
https://github.com/zcash/zcash/blob/b5dda4ecc56a1f65da46828b249bdf1705f1aac3/src/main.h#L58

zcashd prunes orphaned side-chain blocks when they are 288 blocks behind the tip:
https://github.com/zcash/zcash/blob/b5dda4ecc56a1f65da46828b249bdf1705f1aac3/src/main.h#L187

**Chain forks in practice**

There are approximately 3 reorganisations per day, as of April 2020. Almost all reorganisations are 1 block. See the April 2020 update in:
https://grants.zfnd.org/proposals/21786689-zcash-observatory

There's some analysis of chain forks here, including a 7 block orphaned fork:
https://github.com/zcash/zcash/issues/2004

Nathan recommends 10 blocks before transaction confirmation:
https://github.com/zcash/zcash/issues/952

Transactions that depend on JoinSplits anchored to discarded blocks become invalid after a reorganisation:
https://zcash.readthedocs.io/en/latest/rtd_pages/security_warnings.html#block-chain-reorganization-major-differences

**Comment by teor2345** [comment]
> In order to choose the best valid block chain in its view of the overall block tree, a node sums the work, as defined in § 7.6.5 ‘Definition of Work’ on p. 91, of all blocks in each valid block chain, and considers the valid block chain with greatest total work to be best. To break ties between leaf blocks, a node will prefer the block that it received first.

Section 3.3, Zcash Protocol Specification, https://github.com/zcash/zips/raw/master/protocol/protocol.pdf

**Comment by yaahc** [comment]
* GetTipList() -> [(hash, cumulative_work)]
* SetTip(hash)
* PruneTip(hash)

How are these APIs going to be used? My expectation is that you'd only ever care about the current best tip, and I feel like the `SetTip` and `PruneTip` might not be necessary depending on how we structure the state. Right now its already trivial to grab the tip with the greatest cumulative work, though thats because we don't have forks. But if we can still easily ask what the block with the greatest height is then wouldn't the tip list almost always be just this one tip block, unless there are multiple blocks with the exact same height which are both the maximum height.

For example, if we have a `height -> [hash]` map we can pretty trivially iterate up the tree of chains and infer where chains fork and end based on increments and decrements to the length of the list of same height hashes and the parent hashes of those blocks. It seems like we could just never prune this information and be fine.

**Comment by teor2345** [comment]
I think you're right about some of the APIs, I'll edit them and describe their usage in another comment.

The consensus rule is not "the longest chain", but "the largest cumulative proof of work". They are sometimes the same block, but that's not guaranteed:
> * if there are multiple competing chains, zebra-consensus chooses the chain with the largest cumulative proof of work, breaking ties with the earliest block received

One of the consensus rules is a minimum proof of work for each block. Let's call that minimum value `N`. Here is a fork where the longest chain is not the consensus chain tip:
* `A(N) <- B(N) <- C(N)` = 3*N cumulative work
* `A(N) <- D(4*N)` = 5*N cumulative work, the consensus chain

I think it's helpful to have our internal data structures support these APIs as closely as possible, because it's less error-prone. It's also worth noting that the block header is 1.5 kB, so it might be expensive to iterate through block headers.

Here's an example of an ambiguous `height -> [hash]` map:
* 2 -> [U, V, W]
* 1 -> [X, Y]
* 0 -> [Z]

Are there two side chains? Three side chains? How long are they?

**Comment by yaahc** [comment]
the ambiguous chains can be resolved by looking at their parent blocks right?

as for the cumulative proof of work, that's good to know. and I agree on the data structures needing be optimized to support the APIs they're intended for, I'm just still figuring out the APIs is all, I'll chew on how to factor cumulative work into the state for now.

also good to know about how expensive it is to iterate over hashes, I think for a height to hash map it should be possible to iterate just by keys and restrict the memory usage for the most part but I'll definitely keep it in mind. Assuming the height map is even useful if proof of work is the key factor...

**Comment by yaahc** [comment]
given this info I feel like the best data structure for iteration would be one that just represents the tree of the fork points, where each chain has a set of blocks and info about those blocks, like cumulative work, and additional an entry for the continuation of the chain... suddenly I just understood all the chain reorg stuff you've been talking about

**Comment by teor2345** [comment]
Here's how we use the (redesigned) APIs:

Adding a block:
```
ValidateBlock(block):
check_block(block)?
work = GetCumulativeWork(block.parent_header_hash)?
work = work + block.work
hash = block.header_hash()
AddBlock(block, hash, work)?
SetBestChain(hash, work)
PruneOldSideChains()
```
Validation should be as efficient as possible, and it should be scheduled at normal priority.

Reorganising the chain:
```
SetBestChain(new_block_header_hash, new_block_cumulative_work):
current_best_work = GetCumulativeWork(GetTip())
// If the work is equal, prefer the current block.
// The consensus rule is "first received at node", but we use
// "first applied to the state". This should
if new_block_cumulative_work > current_best_work:
  SetTip(new_block_header_hash)
```
Reorganising needs to be reasonably efficient, and it can be scheduled at higher priority.

Pruning old chains:
```
PruneOldSideChains():
tips = GetSideChainTipList()

main_height = GetHeight(GetTip())
for tip in tips:
  for side_hash in iter::successors(tip, GetParent):
    side_height = GetHeight(side_hash)
    // Stop iterating when we get back to the main chain
    if GetHashAtHeight(side_height) == side_hash:
      continue;
    // Side chains can be longer than the main chain
    if (main_height > side_height) && (main_height - side_height > MIN_BLOCKS_TO_KEEP):
      PruneSideChain(side_hash)
```

There might be a better data structure or algorithm here. But even if there is not, the quadratic iteration is limited by:
* the length of the side chain (typically 1-7 blocks)
* the number of side chains (typically 1 in 300 blocks)
* the pruning limit (side chains are pruned 288 blocks after their fork in zcashd)

Pruning needs to be reasonably efficient, to avoid some kinds of DoS. But it can be scheduled at low priority.

**Comment by yaahc** [comment]
> Adding a block:

I think from the standpoint of `zebra-concensus` the API can be reduced to

```
ValidateBlock(block):
check_block(block)?
AddBlock(block)?
```

Because none of the cumulative work checking or chain management is dependent on verification, which would make all of the pruning, work tracking, and organizing of chains implementation details of `zebra-state`.

_I will comment on the rest of the APIs later tonight or tomorrow, gotta afk rn_

**Comment by teor2345** [comment]
Yeah, you're right, we could push all the chain management into zebra-state. Or we could keep all the consensus rules in zebra-consensus, and keep zebra-state's implementation reasonably simple.

I'm not sure what the best design is here.

*Feel free to take the time you need, I'm going to focus on verification for the next day or two.*

**Comment by yaahc** [comment]
Here's the plan going forward:

* Add an `in_memory` representation of chains that tracks the potentially valid chains that are still within the reorg limit, tentatively called `VolatileChains`
* use this new data structure in both the `in_memory` and `on_disk` state services to track blocks that have been validated and added but may still be reorganized
  * do not persist these blocks to disk, may be changed later
* This data structure will use `im` to deduplicate state shared between multiple chains
* when adding a new block to the volatile chains, persist any ancestors that go beyond the reorg limit
  * For now implement as little pruning logic as is feasible

The various APIs provided by the state services will then check the in memory chain prior then the on disk chain, so any information that has been added to the state service is available to outside observers, regardless of whether it has been persisted.

As far as I can tell the design here is relatively simple, the complexity seems to mostly live in how the volatile chains are reoganized, how data is persisted, and how its pruned whenever we add a new block.

**Comment by teor2345** [comment]
We're doing this through the RFC process and #680 now.
