### ISSUE TITLE
Add `cargo doc` warnings/errors to CI

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4524]
## Motivation

After #2892 is done, we'll want to make sure we don't introduce new errors. To do that, we should test it in CI.

### Designs

- [ ] Add `cargo doc` to CI to make sure no errors/warnings are thrown
- [ ] Check for warnings and publish docs with
  ```bash
  cargo doc --no-deps --document-private-items --all-features
  ```

**Comment by teor2345** [comment]
I added the new "Rust doc" job to the `main` branch requirements.
