### ISSUE TITLE
Fix automatic Zebra deployments to Google Cloud

### ISSUE THREAD

**Issue by conradoplg** [ZcashFoundation/zebra#4546]
## Motivation

All node deployments seem to be failing in GCP with messages like:

```
2022/05/31 22:15:00 Error: Failed to start container: Error response from daemon: {"message":"manifest for us-docker.pkg.dev/zealous-zebra/zebra/main:bfa319d not found: manifest unknown: Failed to fetch \"bfa319d\""}
```

### Designs

- [ ] Fix the issue
- [ ] Think about a way to get notified somehow if a deployment fails and implement it if possible, or create a new ticket for it if it's complex

**Comment by gustavovalverde** [comment]
We'll be notifying this instead of "fixing" it, as we have to change the way we deploy, and Google Instance Groups are not flexible enough to accomplish this. I'll be tracking this as a general implementation for infrastructure.
