### ISSUE TITLE
ci: lightwalletd tests fail with "could not read ScriptSig"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4551]
## Motivation

Zebra's lightwalletd tests are currently failing with:
> {"app":"lightwalletd","error":"error parsing block: parsing transaction 0: while parsing transparent input: could not read ScriptSig","height":1687104,"level":"warning","msg":"error zcashd getblock rpc","time":"2022-06-01T02:00:00Z"}
> {"app":"lightwalletd","level":"fatal","msg":"unable to issue RPC call to zcashd node","time":"2022-06-01T02:00:00Z","timeouts":11}
https://github.com/ZcashFoundation/zebra/runs/6681266038?check_suite_focus=true#step:9:1437

It looks like https://github.com/adityapk00/lightwalletd has not been updated for NU5, so we need to switch our tests to another `lightwalletd`.

### Designs

We could switch to the most up-to-date `lightwalletd` fork:
https://github.com/zcash/lightwalletd

Or we could temporarily disable these error messages.

**Comment by teor2345** [comment]
It seems like `main` is still using adityapk00/lightwalletd, despite PR https://github.com/ZcashFoundation/zebra/pull/4553 :
> {"app":"lightwalletd","error":"error parsing block: parsing transaction 0: while parsing transparent input: could not read ScriptSig","height":1687104,"level":"warning","msg":"error zcashd getblock rpc","time":"2022-06-04T08:33:12Z"}

https://github.com/ZcashFoundation/zebra/runs/6736917351?check_suite_focus=true#step:9:1154

**Comment by conradoplg** [comment]
This seems to be caused by:

- When building the image, it fetches the `lightwalletd` docker image with the `latest` tag
- The image with the `latest` tag is very old

So the issue can be:
- We are not tagging the image with `latest`
- Or we should be pointing to something other than `latest`

I manually retagged `latest` and I'm currently retrying some jobs to check if they work.

**Comment by conradoplg** [comment]
I created https://github.com/ZcashFoundation/zebra/issues/4590 to better track the issue
