### ISSUE TITLE
ci: re-enable zebra & lightwalletd status checks

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4600]
## Motivation

We've recently disabled most lighwalletd CI tests for as required status checks, with recent changes on CI we should periodically check if this checks can be re-enabled, so we don't merge faulty code

### Designs

Re-enable the following checks:
- [x] `Zebra checkpoint / Run sync-to-checkpoint test`
- [x] `Zebra tip / Run full-sync-to-tip test`
- [x] `lightwalletd tip / Run lwd-full-sync test`
  - [x] `lightwalletd tip / Run lwd-grpc-wallet test`
  - [x] `lightwalletd tip / Run lwd-send-transactions test`
  - [x] `lightwalletd tip / Run lwd-update-sync test`

These depend on PRs:
- #4669
- #4663
- maybe #4670

Enable new checks:
- [x] `Rust doc` #4635
- [x] Build all crates individually (13 crate jobs + check matrix job) #4640 
- [x] Beta Rust #4637
- [x] `cargo deny` with `--no-default-features` and `--all-features` #4640

**Comment by teor2345** [comment]
I just re-enabled all these branch protection rules.
