### ISSUE TITLE
ci: Wait for lightwalletd image rebuild if it has changed

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4612]
## Motivation

If we change the `lightwalletd` Docker image in a PR, we want to see those changes in the PR's tests. Otherwise we won't know if our fixes work.

If we don't change the image, the latest `main` branch image is fine.

## Design

Before starting this PR, we want to add the job to the branch protection rules, so we don't merge broken code:
- #4882

We might want to use the same dependency algorithm we use for the state cache:
- wait for the image from the current PR and commit, if it is being rebuilt, then use it, or
- use the image from `main`

## Original Conversation

> I'm not sure if this completely solves the problem. What happens if we need to update the image? The PR that changes it will use the `latest` image which will not be the updated one and it will fail CI.

I had the same thought, it makes testing a bit tricky.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/4599#issuecomment-1155790695_

**Comment by teor2345** [comment]
This caused a build failure on the main branch:
- buggy PR: #4786 
- fix PR: #4886 

So I've set it as a medium priority.
(It's already scheduled for a sprint.)

**Comment by teor2345** [comment]
This isn't actually causing us any problems at the moment

**Comment by gustavovalverde** [comment]
Work was started in https://github.com/ZcashFoundation/zebra/pull/4980#issuecomment-1260475097 but a refactor is needed to make builds interdependent
