### ISSUE TITLE
Test that old zebrad.toml files still work

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4625]
## Motivation

We want to make sure that we don't accidentally break the config format.

### Designs

- [ ] Commit a copy of the `zebrad generate` output to a test folder in the Zebra git repository
- [ ] Add an acceptance test that makes sure the config is up to date in the Zebra git repository
- [ ] Add an acceptance test that launches `zebrad start` using the config from the Zebra git repository

We already have a test that launches using a freshly generated config.

**Comment by oxarbitrage** [comment]
I am unsure if we should use cargo insta, snapshots and how.

1- If you make a snapshot of the config, you have to remove the header meta data to convert it to a real config file that zebra can use to start.
2- If the config changes, the snapshot of the config will need to be updated. Then when zebra is started it will use a new config and not an old one. 

Here is what i think we should do:

- Create a file with the current config and store it in a test folder.
- Create a test that start zebra with that config.

If there are breaking changes to the config in the future the old config will fail to start zebra, we will then have to update the stored old config file to make the test pass. That way we will know before merging and can notify users (I think is the only thing we can do if the new config has breaking changes and we still want to go ahead with them).

Let me know how do you see it, or if we want to use snapshots please explain the workflow a bit more. Thanks.

**Comment by teor2345** [comment]
> Here is what i think we should do:
> * Create a file with the current config and store it in a test folder.
> * Create a test that start zebra with that config.

This seems better to me, I'll edit the ticket.

**Comment by teor2345** [comment]
We also need to make sure that new config fields are added to the test config.
If we don't, we could make a breaking change to a config that was added recently, and the test wouldn't pick it up.

**Comment by oxarbitrage** [comment]
>  Store a copy of the zebrad generate output in a test folder in git

Can you clarify the git part please ? Thanks!

**Comment by teor2345** [comment]
> > Store a copy of the zebrad generate output in a test folder in git
> 
> Can you clarify the git part please ? Thanks!

I meant "in the Zebra git repository", I've added that to the ticket.
