### ISSUE TITLE
Limit the size of reject network message strings

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4632]
## Motivation

We want to avoid sending large error messages on the network.

`zcashd` does this with a limit of `111`, we might want ours to be slightly smaller:
https://github.com/zcash/zcash/blob/1b5ab4a06e52c23aca48afb1ebb72a25ef5dd3ca/src/main.cpp#L7334-L7335

### Specifications

Bitcoin doesn't say much about limits:
https://en.bitcoin.it/wiki/Protocol_documentation#reject

**Comment by daira** [comment]
> zcashd does this with a limit of 111, we might want ours to be slightly smaller

Why so? I don't know why the limit is 111, and of course Bitcoin Core doesn't document it, but if I had to guess it would be either:
* just an arbitrary magic number, or
* some calculated limit on actual message size.

**Comment by teor2345** [comment]
> > zcashd does this with a limit of 111, we might want ours to be slightly smaller
> 
> Why so? I don't know why the limit is 111, and of course Bitcoin Core doesn't document it, but if I had to guess it would be either:
>     * just an arbitrary magic number, or
>     * some calculated limit on actual message size.

Is the `zcashd` limit in bytes or UTF-8 characters?

Zebra's is in UTF-8 characters right now, because that's how Rust counts things.

**Comment by oxarbitrage** [comment]
I just removed the entire from code:

```
impl<E> From<E> for Message
where
    E: Error,
{
    fn from(e: E) -> Self {
...
    }
}
```

And zebra compiles. This means this code is not used at all at the moment. May lower the priority of this PR and some testings we wanted to do.

**Comment by teor2345** [comment]
Thanks, I made ticket #4633 optional priority.
