### ISSUE TITLE
Upgrade ripemd160 usage to support version 0.9 API

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#467]
s/input/update/g : https://github.com/RustCrypto/hashes/compare/ripemd160-v0.8.0...ripemd160-v0.9.0#diff-5c71a510a1a91775bbb0fa17b1678012R13

s/result/finalize/g: https://github.com/RustCrypto/hashes/compare/ripemd160-v0.8.0...ripemd160-v0.9.0#diff-5c71a510a1a91775bbb0fa17b1678012R17

**Comment by teor2345** [comment]
@dconnolly does this belong in the "Transaction Validation" milestone?

**Comment by dconnolly** [comment]
eeeeh it was a dependency bump, but not strictly required for the milestone
