### ISSUE TITLE
Check cargo dev-dependency feature interactions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#468]
```
[dev-dependencies]
...
tokio = { version = "0.2.21", features = ["full"] }
```
I think this _might_ have negative interactions with the features that are enabled when not using dev-dependencies. AFAIK this bug in cargo was fixed in nightly recently so its probably fine but we might want to open an issue to verify that we're not pulling in more of tokio than wanted when compiling just `zebra-concensus` without tests

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/448_

Edit: add the relevant Cargo.toml line

**Comment by hdevalence** [comment]
I think we use `features = ["full"]` in zebrad anyways, so i'm not sure we end up saving anything regardless of the dev-dependency interactions.

**Comment by yaahc** [comment]
I'm not worried about the `zebrad` case or even this as an issue short term, just that eventually someone could write an application that uses `zebra-concensus` as a library which also wants to limit what features they enable from tokio. In all likelyhood the fixes to the feature resolver will merge before this happens so we should definitely not focus on this issue.

**Comment by hdevalence** [comment]
Closing this issue for now per @yaahc's comment just to keep the amount of open tasks down; happy to reopen this later.
