### ISSUE TITLE
Add a `WeakCache` to `zebra_state`.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#471]
#416 and related issues moved to `Arc<Block>` and `Arc<Transaction>` everywhere.  The motivation for this change is that because this data doesn't change much, using `Arc`s gets us part of the way to a fancy interning implementation that only ever stores one copy of an immutable object (most commonly seen with string interning).  The other part is a way to ensure that we don't needlessly create multiple copies of the same `Block` or `Transaction` while serializing or deserializing.  Ideally, we would detect at a deserialization boundary whether there was an extant copy of the object in memory, and then return that copy rather than creating a new one.

There are two main places where blockchain object deserialization happens.

1. In the network system, when receiving new data over the network.
2. In the state system, when retrieving data from storage.

I think the first case is relatively less important to address, because due to the design of the Zcash network protocol, we never get data we didn't explicitly ask for (or, slightly more precisely, we discard messages with unsolicited data, so it's immediately dropped). When we are explicitly asking for data, it's probably data we don't already have, so I'm not sure there's much benefit to adding a complex tracking system. 

In the second case, because the state system is the single source of truth for blockchain state, it's likely that we'll get repeated requests for the same data. Indeed, other parts of the application should ideally not be storing data themselves, but asking the state system for the data they need when they need it.  So it seems relatively more useful to deduplicate references there.

To do this, we need a way to look up objects based on a key (e.g., the block or transaction hash) and return an `Arc` of the full object if it exists.  The cache itself shouldn't hold `Arc`s, because that would prevent unused objects from being dropped.  A relatively simple solution is to build a `WeakCache` struct backed by a `HashMap` that holds [`Weak`](https://doc.rust-lang.org/std/sync/struct.Weak.html) references.  Here is a strawman API proposal:

```
struct WeakCache<K, V> {
    inner: HashMap<K, Weak<V>>,
}

impl<K: Eq + Hash, V> WeakCache<K, V> {
    pub fn insert(&mut self, k: K, v: &Arc<V>) {
        self.inner.insert(k, Arc::downgrade(v));
    }

    pub fn get(&self, k: &K) -> Option<Arc<V>> {
        self.inner.get(k).and_then(|weak| weak.upgrade())
    }

    pub fn prune(&mut self) {
        self.inner.retain(|_, v| v.strong_count() > 0)
    }
}
```

**Comment by hdevalence** [comment]
@yaahc WDYT of this? One thing I'm not sure about is whether `get` should prune known-dead entries, which would require either `get` to take `&mut self` or to use interior mutability.

**Comment by yaahc** [comment]
Does this mean that we don't expect to store all blocks in memory if we've requested them? I had expected that the storage would just read the state from disk on startup and commit snapshots of the in memory copy in the background. I'm guessing that this means that the actual plan is to minimize how much memory we use by storing all blocks that aren't actively in use exclusively on the disk.

One thing I'm worried about is making our Caching behavior tightly coupled to `Arc` and `Weak`. I want to check the database backends that we're considering using and how they handle write back and caching, if they're already handling a lot of this for us automatically I think the `Arc`/`Weak` splits might be redundant.

As for pruning I would handle this at the same time as the commit to disk, whenever that happens. I was planning on making that a background task that gets `tokio::spawned` by the `Service` or something.

**Comment by hdevalence** [comment]
Yeah, I think there are currently 20-40GB of blocks already, so we definitely won't be able to store them all in memory.  

I agree in general about not wanting to duplicate caching layers that already exist in a better way in the database layer, but I think that for this specific application (blocks and transactions), there's not much downside and a bunch of upside.  In terms of the upside, we would save on serialization overhead and memory use.  In terms of the downsides, because block and transaction data is immutable, I think that writebacks and cache invalidation aren't a concern, and this eliminates a bunch of cache management complexity. And there's no duplication between this system and the database's cache, because this cache wouldn't hold on to any data itself, only keep track of what data is already in memory.

**Comment by yaahc** [comment]
From the sled README:

![Screenshot from 2020-06-12 14-38-19](https://user-images.githubusercontent.com/1993852/84548402-61a02080-acba-11ea-9ec4-9510ac8b4c40.png)

I think if sled had this feature we could have it just deserialize directly into `Arcs` and presumably it would drop its own copies based on it's own cache policies which seems to be exactly what we'd want.

It might be worth asking spacejam when that feature will be ready or if it would be easy to implement.

**Comment by yaahc** [comment]
@spacejam :point_up:

**Comment by hdevalence** [comment]
Yeah that sounds like exactly the kind of thing we'd want.  I don't see any related tracking issues on the repo, though, so this might be a useful small thing to do in the meantime.

**Comment by yaahc** [comment]
Yea, it should be pretty easy I think so I don't see any reason to not implement this.

Where should this go though, relative to the `in_memory` stuff and `sled` backend. Sled looks like it just provides an interface to bytes on the disk, essentially, so it's API is pretty different from the stuff exposed by `in_memory::BlockIndex`

My first inclination is to put the `sled` db behind the `in_memory` service, then tweak the hash_maps in `BlockIndex` to only work with Weak pointers and do all the serialization amortization. We'd probably also want to configure `sled` to have little or no cache so long as we have the weak ptr api infront of it. The problem with this approach though is it doesn't give us the two parallel backends that we want. I guess the answer is to just copy everything in `in_memory` and make an `on_disk` backend that makes these changes.

**Comment by yaahc** [comment]
theres also this, so it looks like it might already be possible to do this already, maybe?

https://github.com/spacejam/sled/blob/master/examples/structured.rs

edit: maybe not, this looks like a bunch of zero copy interfacing with the cache which doesn't seem useful to us

**Comment by hdevalence** [comment]
@yaahc I wasn't thinking of the `in_memory` backend at all here, since it's already an in-memory store and it's just for testing so performance or resource use doesn't matter.  With regard to the `sled` caching, I don't think that this layer should affect those parameters at all, since this cache doesn't actually store any data, it just keeps track of data that's already in use in some other part of the program. So there's no duplication between this system and the database cache.

**Comment by yaahc** [comment]
> With regard to the `sled` caching, I don't think that this layer should affect those parameters at all, since this cache doesn't actually store any data, it just keeps track of data that's already in use in some other part of the program. So there's no duplication between this system and the database cache.

What I meant was that the memory usage would still be duplicated for blocks that are being cached by both sled and active `Arc`s
