### ISSUE TITLE
Projects that rely on BOSL exceptions should say that they do

### ISSUE THREAD

**Issue by daira** [ZcashFoundation/zebra#4716]
This is important licensing information since it affects how those projects can be forked.

* `zcash_script` depends on `orchard` via `zcash_primitives`:
  * https://github.com/ZcashFoundation/zcash_script/blob/c9fbc441efd78593ba6a9828be45baf2d6469757/Cargo.toml#L57-L58
  * https://github.com/ZcashFoundation/zcash_script/issues/36
* `zcash_chain` depends on `orchard` directly and via `zcash_primitives` and `zcash_note_encryption`:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-chain/Cargo.toml#L52-L56
* `zcash_consensus` directly and via `zcash_proofs` and other Zebra crates:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-consensus/Cargo.toml#L37-L48
* `zebra_network` via `zebra_chain`:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-network/Cargo.toml#L50
* `zebra_node_services` via `zebra_chain`:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-node-services/Cargo.toml#L10
* `zebra_rpc` via `zebra_chain` and `zebra_state`:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-rpc/Cargo.toml#L54-L55
* `zebra_state` via `zebra_chain`:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebra-state/Cargo.toml#L35
* `zebrad` via all of the above:
  * https://github.com/ZcashFoundation/zebra/blob/97fb85dca9d00a717661ea0cbab7ce66b8d23977/zebrad/Cargo.toml#L71-L76

A copy of the notice is needed for each potentially reusable crate or component.

Suggested wording is:
> Downstream code forks should note that the code in this repository depends on
> the 'orchard' crate, which is licensed under the Bootstrap Open Source License.
> A license exception is provided allowing some derived works that are linked or
> combined with the 'orchard' crate to be copied or distributed under the original
> licenses (in this case MIT / Apache 2.0), provided that the included portions of
> the 'orchard' code remain subject to BOSL.
> See https://github.com/zcash/orchard/blob/main/COPYING for details of which
> derived works can make use of this exception.

See also:
* https://forum.zcashcommunity.com/t/bosl-or-mit-orchard/41439/118
* https://github.com/zcash/zcash/issues/5931 (similar issue for zcashd)
* https://github.com/zcash/librustzcash/pull/577 (PR for librustzcash)

**Comment by daira** [comment]
The `orchard` crate has now been relicensed to MIT OR Apache 2.0: https://github.com/zcash/orchard/pull/405. Strictly speaking, this issue is still valid until Zebra depends on an `orchard` release that includes the relicensing, i.e. 0.7.0: https://github.com/zcash/orchard/issues/407

**Comment by mpguerra** [comment]
this would have been resolved by #8201 but we're waiting for `zcash_primitives` to be upgraded to `orchard 0.7.0`

**Comment by mpguerra** [comment]
depends-on: #8541 and #8540

**Comment by mpguerra** [comment]
I think we can close this now as zebra no longer depends on BOSL licensed versions of any crates.
