### ISSUE TITLE
ci: Split deploy-gcp-tests workflow into multiple categories

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4753]
## Motivation

We might get into scenarios were we'd like to disable specific CI tests categories, for example:
- lightwalletd syncs
- zebra syncs
OR
- syncs with cached state
- syncs without cached state

As of know, a single workflow is also harder to understand as it has multiple dependencies and relations
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/16890942/177447304-a722bf8c-a038-4eca-a1bc-e9ef9444f096.png">

### Designs

This would require to have at least 2 reusable workflows, which would also simplify the actual dependency tree and allow us to disable specific pieces of the whole `Deploy GCP tests` :
- `deploy-gcp-tests-lwd.yml`
- `deploy-gcp-tests-zebra.yml`

**Comment by teor2345** [comment]
This is not currently a priority for Zebra.

**Comment by teor2345** [comment]
We can re-open this ticket when we actually need this change.
