### ISSUE TITLE
Add an NU5 block test vector that contains many shielded Sapling transactions

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#4775]
## Motivation

When blocks started showing up on mainnet after NU5 with many shielded Sapling transactions, we observed aberrant zebrad verification behavior. For similar blocks with many Orchard transactions, we identified some [bugs](https://github.com/ZcashFoundation/zebra/pull/4752) already. We should include these blocks (at least one) as test vectors.

## Related Work

https://github.com/ZcashFoundation/zebra/issues/4774

**Comment by teor2345** [comment]
Zebra's performance is good enough for now, so this is a low priority.
