### ISSUE TITLE
Avoid calling `find_group_hash` with every new `ValueCommitment`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#4783]
`verify_sapling_shielded_data` is a hot task in Zebra when we have too many sapling transactions. Any improvements we can make there can help the sync performance.

There is one potential improvement we can make here:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/src/sapling/commitment.rs#L283-L286

There are two things we need to discuss first:

1 - If we don't generate these points with each new commitment then where do we do it. 

One possible option is to add them as fields of the transaction verifier struct: https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/transaction.rs#L64 

2- `find_group_hash` calls `jubjub_group_hash` which produces a random, always different, point in the curve. If we do this change we will start using the same generated point for all created note commitments. I think this will be ok but i want to make sure.

**Comment by conradoplg** [comment]
1 - They could be globals created with `lazy_static`. Not sure if adding to the transaction verifier would require passing them too much around, if not then that's good too

2 - They are deterministic, the documentation is a bit misleading (the points generated follow a random distribution, but the same input generates the same output)

**Comment by dconnolly** [comment]
> 1 - They could be globals created with `lazy_static`. Not sure if adding to the transaction verifier would require passing them too much around, if not then that's good too
> 
> 2 - They are deterministic, the documentation is a bit misleading (the points generated follow a random distribution, but the same input generates the same output)

Agreed, I would start with a `lazy_static` in that module and then re-profile

**Comment by dconnolly** [comment]
> > 1 - They could be globals created with `lazy_static`. Not sure if adding to the transaction verifier would require passing them too much around, if not then that's good too
> > 
> > 2 - They are deterministic, the documentation is a bit misleading (the points generated follow a random distribution, but the same input generates the same output)
> 
> Agreed, I would start with a `lazy_static` in that module and then re-profile 

Also we can tweak the rustdoc

**Comment by oxarbitrage** [comment]
`lazy_static` seems easier at least to get started. Thank you both. I can work on this however i will like @teor2345  or @ftm1000 to let us know if it is ok to work on this now or later.
