### ISSUE TITLE
Move note commitment tree updates to a dedicated blocking and CPU-heavy thread

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4790]
## Motivation

Zebra's sync can be slow or fail, because note commitment tree updates involve some CPU-heavy cryptography.

So we want to move note commitment tree updates into a `rayon` CPU thread pool `scope`.

### API Reference

Blocking threads:
https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html

CPU-heavy threads:
https://docs.rs/rayon/latest/rayon/fn.scope_fifo.html

### Detailed Analysis

See https://github.com/ZcashFoundation/zebra/issues/4583#issuecomment-1186662862

### Designs

- [ ] Wrap the entire function that calls `append()`/`root()` in `rayon`, to minimise the cost of scheduling `tokio` and `rayon` threads
- [ ] We'd like to update sprout, sapling, and orchard note commitment trees in parallel, using Rayon's `join()`
- [ ] If there isn't a `tokio::spawn_blocking()` wrapping the update future, add it (see ticket #4779 and its PR)

Example code for `rayon` in `tokio` blocking threads:
https://github.com/ZcashFoundation/zebra/blob/81727d7df0ee57e6d4f2172c287e52e414c4e6a0/zebra-consensus/src/primitives/ed25519.rs#L121-L134

## Related Work

We'll move state updates to blocking tokio threads as part of #4779

**Comment by dconnolly** [comment]
Calls to `append()` may be wrapped up into `rayon` threads

https://github.com/ZcashFoundation/zebra/blob/81727d7df0ee57e6d4f2172c287e52e414c4e6a0/zebra-chain/src/orchard/tree.rs#L305

**Comment by teor2345** [comment]
It might be more efficient to wrap the entire function that calls `append()`/`root()` in `rayon`, to minimise the cost of scheduling `tokio` and `rayon` threads.

**Comment by teor2345** [comment]
I assigned this to myself, because I need to do it to test PR #4199.
