### ISSUE TITLE
docs(release): Tier policies summary in the Supported platforms docs might be confusing

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4818]
## Motivation

The summary text for Tiers in [Supported Platforms](https://github.com/ZcashFoundation/zebra/blob/main/book/src/user/supported-platforms.md) might be confusing, taking into consideration an actual summary from [Target Tier Policies](https://github.com/ZcashFoundation/zebra/blob/main/book/src/user/target-tier-policies.md)

**Comment by teor2345** [comment]
I don't know how to schedule this ticket, because I'm not sure what the exact problem is.

Feel free to re-open it with a specific description of what we need to change.
