### ISSUE TITLE
Create large block and transaction test cases

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#482]
As part of block and transaction validation (#428), we'd like to test large blocks and transactions. 

Since Sapling, the maximum block and transaction size is 2,000,000 bytes (MAX).

Note that the maximum size of a transaction is actually slightly lower, because the block also contains a block header, and a transaction count `compact size` field. This effective limit isn't documented in the spec.

The same restriction doesn't apply to mempool transactions, because protocol messages can be up to 2 MB (2 * 1024 * 1024). This inconsistency between mempool and block transactions isn't documented in the spec.

We would like the following test cases:

Block parsing:
* a MAX size block
* a (MAX+1) size block

Mempool transaction parsing:
* ~a MAX size transaction~ (moved to #571)
* ~a (MAX+1) size transaction~ (moved to #571)
* a transaction that's the largest size that will fit in a MAX size block (moved mempool testing to #571)
* a transaction that's 1 byte larger than the largest size that will fit in a MAX size block (moved mempool testing to #571)

These blocks and transactions should use the latest block and transaction formats (Blossom or Heartwood).

Our property tests may already cover these cases, but they are edge cases, so we'd like to be sure.

This issue is open to external contributors. But the Zebra team might also create some of these test cases ourselves.

**Comment by dconnolly** [comment]
Resolved by #558
