### ISSUE TITLE
Send note commitment and history trees from the non-finalized state to the finalized state

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#4824]
## Motivation

When Zebra commits a finalized block, it re-calculates all the note commitment and history trees. This uses a lot of extra CPU. Zebra also fetches these structures from the database for each block coming from the non-finalized state.

## Related Work

This issue is tracked in #3757.

**Comment by teor2345** [comment]
Zebra's performance is good enough for now, so this is a low priority.

If we can finish it off quickly, that's ok, but we should move on to other tasks soon.

**Comment by upbqdn** [comment]
I'll finish it this week.
