### ISSUE TITLE
Cache the treestate in the checkpointer and send it to the finalized state

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#4836]
## Motivation

When the checkpointer commits a block, the finalized state fetches the history tree and note commitment trees from the database, recomputes the trees, and stores them back in the database. This cycle repeats for every block that the checkpointer sends to the finalized state.

A more efficient way would be to cache the trees and stop fetching them each time a block is committed. One approach would be to cache and recompute the trees in the finalized state, but since the non-finalized state already recomputes the treestate for each block for its own needs, it wouldn't be efficient to do it in the finalized state again. Instead, the checkpointer could cache the treestate and send it to the finalized state with each new block.

### Specifications

Here's the relevant call stack that shows how Zebra currently fetches the note commitment trees when committing a block from the checkpointer:
 
1. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-consensus/src/checkpoint.rs#L988

3. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service.rs#L681
5. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service.rs#L244
6. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state.rs#L155
7. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state.rs#L191
8. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state.rs#L296
9. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state/zebra_db/block.rs#L332
10. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state/zebra_db/shielded.rs#L162-L164
11. https://github.com/zcashfoundation/zebra/blob/404f682af659cd9f49782cf5bb4ba8fc8d83eb75/zebra-state/src/service/finalized_state/zebra_db/shielded.rs#L82

## Related Work

#4824

**Comment by teor2345** [comment]
> One approach would be to cache and recompute the trees in the finalized state, but since the non-finalized state already recomputes the treestate for each block for its own needs, it wouldn't be efficient to do it in the finalized state again.

As a quick fix, we could conditionally cache and compute the trees in the finalized state:
- when we're using checkpoints, we cache and compute in the finalized state
- when we stop using checkpoints, we drop the cache and avoid recomputing, because the non-finalized state is doing that work

That way, we only do the work once.

**Comment by teor2345** [comment]
Obsoleted by #4909, which makes Zebra read the note commitment roots and trees from a checkpoint file.
