### ISSUE TITLE
Limit transaction size in the mempool

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#484]
## Motivation

When Zebra starts parsing mempool transactions, we should limit them to the maximum consensus block size (2,000,000 bytes).

Block transactions are already limited by the block size limit in #477.

## Existing Design

These limits should be checked in  the `zcash_deserialize()` implementation for `Transaction`.

Here's the implementation for `Block`:
https://github.com/ZcashFoundation/zebra/blob/b600e82d6e6f54656f05e36ce586dec679214348/zebra-chain/src/block/serialize.rs#L118-L120

See #482 for test cases for this code.

### Background Info

`zcashd` has a 2,000,000 byte transaction limit in its consensus rules:
https://github.com/zcash/zcash/blob/63c3d1ec9435b445a883028b9111595ffa9292d4/src/consensus/consensus.h#L29

### Rejected Designs

In practice, the maximum size of a transaction is around 1.5kB smaller than the maximum block size, because blocks also contain a block header and a transaction count. Zebra might want to use this smaller limit for transactions.

But we have no good reason to be different from `zcashd` here.

**Comment by mpguerra** [comment]
@teor2345 did we do this already as part of the mempool work? Should this be added back to the mempool epic to track future mempool improvements?

**Comment by teor2345** [comment]
> @teor2345 did we do this already as part of the mempool work? Should this be added back to the mempool epic to track future mempool improvements?

This is a consensus rule that we should implement as part of the mempool epic.

I've put it in sprint 20, it's trivially simple to implement.

**Comment by teor2345** [comment]
Thanks for finding this!
