### ISSUE TITLE
Coverage check fails with "Cannot read property 'find' of undefined"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#486]
The coverage check for #485 failed with:
```
Run cargo-tarpaulin
Run actions-rs/tarpaulin@v0.1
  with:
    version: 0.12.3
    timeout: 300
    out-type: Xml
##[error]Cannot read property 'find' of undefined
```

A few hours ago, the coverage checks worked for my previous PR #478.

**Comment by dconnolly** [comment]
Tarpaulin has occasionally been flakey, a subsequent coverage run succeeded so I think it's independent of your changes.

**Comment by yaahc** [comment]
I'm hesitant to ignore flakeyness in our automation, even from the coverage testing stuff. I don't think we should necessarily prioritize this but I don't think we should close this bug on the basis that it passed in a subsequent run.

**Comment by teor2345** [comment]
When I've worked with unreliable CI, it's been helpful to keep a tracking issue open, so we can see how often it fails. That helps us prioritise further investigation.

(We could also leave this issue closed until we see the next failure. Not sure if GitHub is good at recommending similar closed tickets though.)

**Comment by yaahc** [comment]
I've seen repos where github recommends similar closed/open issues but it doesn't happen all the time, I wonder if thats a setting...

For now I've gone ahead and reopened this, I don't think it will be in the way to keep it open given we garden regularly, so I'd prefer to keep it on the radar.

**Comment by dconnolly** [comment]
Let's see if we can reproduce and/or find an upstream tarpaulin issue to link to and see if we can ever resolve this with the upstream dep or at the very least try to remove non-deterministic fails.

**Comment by dconnolly** [comment]
This has been resolved now I think.
