### ISSUE TITLE
Independently verify each crate in zebra during CI

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#487]
This was noticed in `zebra-chain` during the change to add serde bounds everywhere. `zebra-chain` got into a state where it could not build successfully on its own, but when compiled with other crates in the `zebra` workspace the missing features that it needed to compile successfully would get enabled. This means that despite the fact that the build on `zebra-chain` is broken PRs for changes to `zebra-chain` would pass successfully.

To fix this we should add steps to individually build each crate in the workspace, and then build the entire workspace. They should in theory share artifacts, so with any luck this will not slow down CI overall.

For reference, the original comment that triggered this:

---

I want to see what automation does but when I run the build locally from `zebra-chain` it fails but when I run it from the root directory of the entire project `zebra-chain` compiles successfully along with the rest of the project. I don't necessarily think this is a problem, its probably just different features being enabled by default vs by zebrad, but if this compile error isn't caught by automation then we will want to fix that as well.

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/231#issuecomment-644247068_

**Comment by dconnolly** [comment]
What about `cargo build` at the workspace level, then `cargo check` in each crate within the workspace. EDIT: the subsequent sub-crate `cargo check` was doing a lot of work.

@teor2345 : "once I set up sccache locally, everything was fine."

**Comment by dconnolly** [comment]
Let's do a parallel per-crate job when we merge to main.
