### ISSUE TITLE
Add zcash-lightwalletd / Build images to required jobs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4882]
## Motivation

If this job fails because we broke it in a PR, we shouldn't merge the PR.

### Tasks

- [ ] add a patch job that runs when the real job is skipped
- [ ] enable the job in branch protection rules (needs Zebra admin permissions)

**Comment by teor2345** [comment]
This is a task that anyone can do (and then any GitHub admin can add the branch protection rule).

**Comment by mpguerra** [comment]
Can we prioritise this one for this sprint to finally finish off the release candidate epic?

**Comment by teor2345** [comment]
> Can we prioritise this one for this sprint to finally finish off the release candidate epic?

This isn't causing us any problems right now, and we aren't planning on changing this Dockerfile, so we can do it in the next sprint.

**Comment by mpguerra** [comment]
In that case I will remove from the release candidate Epic also
