### ISSUE TITLE
Make tests wait until lightwalletd full sync goes all the way to the tip

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4894]
## Motivation

lightwalletd doesn't reliably log when it reaches the chain tip.

In PR #4828, we added a workaround to the lightwalletd full sync test, which stops at a fixed height near the chain tip. But for tests like #4350, we need to wait until it has actually reached the tip.

### Designs

Make the lightwalletd full sync, update sync, grpc, and send transaction tests wait until lightwalletd has reached the chain tip.

We could do this by checking that the Zebra JSON-RPC and lightwalletd gRPC heights match. (We can't do it using the logs, because `lightwalletd` doesn't reliably log block heights.)

The `lightwalletd_integration_test()` already does most of this work, we might want to call it from the grpc and send transaction tests.

**Comment by teor2345** [comment]
If you want to run this test locally, I'm using:

```sh
export TMPDIR=/home/dev/.cache/zebra-tmp
export ZEBRA_CACHED_STATE_DIR=/home/dev/.cache/zebra-custom
export LIGHTWALLETD_DATA_DIR=/home/dev/.cache/lightwalletd-custom
export RUST_LOG=info

cargo test --release \
      --test acceptance \
      --features lightwalletd-grpc-tests \
      -- \
      --nocapture --include-ignored \
      sending_transactions_using_lightwalletd
```

**Comment by teor2345** [comment]
The `lightwalletd_integration_test()` already does most of this work, we might want to call it from the grpc and send transaction tests.

**Comment by mpguerra** [comment]
removing from sprint as it's blocked by #5253 which is not even scheduled for this sprint
