### ISSUE TITLE
Outgoing `Ping` messages

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#49]
In #17 we handle incoming ping messages at the edge, but we also need to generate outgoing ping messages in case the remote peer does not send them to us.  This involves using a timer to generate a stream of events (presumably [an `Interval`](https://docs.rs/tokio/0.2.0-alpha.6/tokio/timer/struct.Interval.html)), sending a `ping` message on every time interval event, and checking that the server receives a `pong` before some timeout.

Currently the `PeerServer` state machine is already somewhat complicated, but I think a relatively clean way to do this functionality would be to take advantage of the fact that the `PeerClient` uses an mpsc channel to communicate with the `PeerServer`, so there is no limitation that the `PeerServer` must have only one client.  So when we spawn the server task, we could also spawn a second client task that waits on a timer interval and sends a new `Request::Ping(Nonce)` to the server task.

The downside of this approach is that we would have to add a `Ping` variant to the `Request` enum, which feels like a slight layering violation (these are really messages about transport maintenance, not messages sent over that transport) but I think it would otherwise integrate cleanly with the code we have.

**Comment by hdevalence** [comment]
With #51 / #65 this could be done as above; adding a `Pong` to the `Response` type isn't necessary because the `PeerServer` can special-case handling of `Ping` requests and fail itself if they timeout or the nonce doesn't match.  Special-casing is a little ugly but means that we don't have to add extra causation paths for failure propagation in the `PeerClient`/`PeerServer` pair.

**Comment by dconnolly** [comment]
Resolved by #77
