### ISSUE TITLE
Managed instance groups deployed with continuous deployment can't scale beyond 1 instance per Zone

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#4946]
## Motivation

This warning is raised when deploying instance groups

```
WARNING: Some requests generated warnings:
 - Instance template specifies a disk with a custom name. This will cause instance group not to scale beyond 1 instance per zone.
```

### Designs

- Remove the instance disk name, and allow google to create the disk name
- Delete old instance disks using the name that google creates

## Related Work

None

**Comment by teor2345** [comment]
Do we have any plans for instance groups larger than 1 instance?

**Comment by gustavovalverde** [comment]
We once talked about doing global deployments with multiple nodes (cc: @dconnolly) but I'm not sure how we'd like to prioritize this.

**Comment by teor2345** [comment]
> We once talked about doing global deployments with multiple nodes (cc: @dconnolly) but I'm not sure how we'd like to prioritize this.

It's not a blocker for the release candidate, and it's not part of any of our current priorities, so I think it's optional.

**Comment by teor2345** [comment]
This isn't something we're planning to use any time soon, so I might just close this ticket.

**Comment by mpguerra** [comment]
@gustavovalverde can I please get an estimate on this issue?
