### ISSUE TITLE
Make file locations appear in zebrad error messages

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4956]
## Motivation

When Zebra's Rust test harness fails in CI, I can't see the file and line in the panic backtrace:
```
12: zebra_test::command::TestChild<T>::expect_stdout_line_matches::h471f18611d79fb45
    at <unknown source file>:<unknown line>
13: acceptance::lightwalletd_integration_test::h1e497ff748a26c03
    at <unknown source file>:<unknown line>
```

https://github.com/ZcashFoundation/zebra/runs/7992118921?check_suite_focus=true#step:6:246

This happens in both Docker, and in release builds on my local machine.
```
The application panicked (crashed).
Message:  Opening database "/home/.../.cache/zebra/state/v25/mainnet" failed: Error { message: "IO error: While lock file: /home/.../.cache/zebra/state/v25/mainnet/LOCK: Resource temporarily unavailable" }. Hint: Check if another zebrad process is running. Try changing the state cache_dir in the Zebra config.
Location: zebra-state/src/service/finalized_state/disk_db.rs:460
...
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 7 frames hidden ⋮                               
   8: zebra_state::service::finalized_state::disk_db::DiskDb::new::h0adc7941d0b09e1e
      at <unknown source file>:<unknown line>
   9: zebra_state::service::finalized_state::FinalizedState::new::hd85ae10e187a7755
      at <unknown source file>:<unknown line>
...
```

But debug builds on my local machine show the file locations:
```
9: zebra_state::service::finalized_state::disk_db::DiskDb::new::hfc24129cd47798c6
      at /home/dev/zebra/zebra-state/src/service/finalized_state/disk_db.rs:<unknown line>
  10: zebra_state::service::finalized_state::zebra_db::ZebraDb::new::hcc01b459aaf10f3f
      at /home/dev/zebra/zebra-state/src/service/finalized_state/zebra_db.rs:50
  11: zebra_state::service::finalized_state::FinalizedState::new::hbcbdd50bfd733126
      at /home/dev/zebra/zebra-state/src/service/finalized_state.rs:84
```

## Tasks

Try adding debugging info to the Rust release profile:
https://github.com/ZcashFoundation/zebra/blob/5866fc339a1a4bf85b954961bcde3dfbd45b5f01/Cargo.toml#L67

**Comment by teor2345** [comment]
This makes diagnosing errors in the docker tests tricky, but it can wait until next sprint.

**Comment by teor2345** [comment]
This important, but it's not causing any particular issues right now.

**Comment by mpguerra** [comment]
@gustavovalverde does it make sense to look at this issue opportunistically since we're making other changes to the Dockerfile? Especifically this part:

> Try changing the build working directory to the `zebrad` source directory:
> https://github.com/ZcashFoundation/zebra/blob/5866fc339a1a4bf85b954961bcde3dfbd45b5f01/docker/Dockerfile#L12

**Comment by gustavovalverde** [comment]
After I'm done with #5933 I might add this one, as #5933 is pilling up with untagged images in the Registry.

**Comment by teor2345** [comment]
@gustavovalverde @mpguerra I just re-checked this on my local machine, and it happens in all release builds, even outside Docker.

So I don't think we can fix it by changing the Docker config.

**Comment by teor2345** [comment]
I had a look at this, we can fix this issue using the `debug` setting in `.cargo/config.toml`:
https://doc.rust-lang.org/cargo/reference/profiles.html#debug

But the debug info adds 300 MB to the `zebrad` binary, making it 11 times its usual 29 MB size. I'm not sure if that's worth it. (For comparison, `zcashd` is 18 MB.)

Since this hasn't been a blocker for diagnosing any bugs, I made it into a branch which developers can use if we need it:
https://github.com/ZcashFoundation/zebra/tree/detailed-backtraces
