### ISSUE TITLE
Create a zebrad healthcheck

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#496]
Something we can hit (perhaps with an HTTP request) to ensure that the node is up and healthy when trying to scale out a fleet of nodes.

**Comment by teor2345** [comment]
Could we modify the DNS seeder to do a health check?

It already does some checks to make sure that nodes are up and valid.

**Comment by hdevalence** [comment]
Is the health check supposed to be public to anyone or private to the node operator? If it's the latter we can just add an extra RPC call or something, or use the tracing filter endpoint in the meantime until we add RPC support.

**Comment by dconnolly** [comment]
> Is the health check supposed to be public to anyone or private to the node operator? If it's the latter we can just add an extra RPC call or something, or use the tracing filter endpoint in the meantime until we add RPC support.

I don't think it has to be private, it should return a very bare response (or even just an empty http 200 perhaps) so I think that can be public/hittable by anyone who can ping the host.

Yeah in the meantime the tracing filter endpoint will probably do, and then later have a dedicated one as an RPC method.

**Comment by hdevalence** [comment]
Hmm, if it's supposed to be public, I don't think the tracing filter endpoint or the main RPC port will work, since that's not supposed to be public.

**Comment by dconnolly** [comment]
> Hmm, if it's supposed to be public, I don't think the tracing filter endpoint or the main RPC port will work, since that's not supposed to be public.

It needs to be public enough to hit from gcloud infrastructure. It can be visible 'publicly' but i bet we could config something that checks a key, configurable per-deployment.

**Comment by hdevalence** [comment]
can the gcloud infrastructure just set certain ports as being only accessible "internally"?

**Comment by dconnolly** [comment]
> can the gcloud infrastructure just set certain ports as being only accessible "internally"?

Yes we can scope it to just be available to Google 'spotter' IPs, I haven't gotten this to work _yet_ but if I do then we can probably just use :3000/filter, if not I can make another thing.

**Comment by dconnolly** [comment]
Closed in #479
