### ISSUE TITLE
[NCC-E005955-M2F] `zebra-chain`: Check that header block version field is valid when serializing blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#497]
## Impact

Zebra assumes all serialization/deserialization functions cannot produce invalid data. Unenforced constraints violate this assumption and may affect consensus or interoperability.

## Description

Zebra implements the `ZCashSerialize` trait for consensus-critical data.

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/serialization/zcash_serialize.rs#L19-L30

Note the highlighted requirement that illegal states must be unrepresentable.

The function `zcash_deserialize()` for `Header` contains historical information regarding the version field of the header. In particular, it specifies that the only valid version number is 4, but that incorrect implementations in the past resulted in several blocks with an incorrect value. The function has some special case handling for this, as well as an explicit check that the parsed version is greater than or equal to 4:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/block/serialize.rs#L75-L82

This is similarly captured in other annotations for the version field, where it is specified that:

> The only constraint is that it must be at least `4` when interpreted as an `i32` .

In comparison, the corresponding `zcash_deserialize()` function does not perform validation on the version field:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/block/serialize.rs#L28-L43

No instances within the codebase will currently set this value incorrectly, but it appears to be a violation of the specified constraint. It is possible to construct a `Header` such that the output of `zcash_serialize` will not correctly deserialize within Zebra.

## Recommendation

Align the constraint checks for the version field such that any serialized Header will correctly deserialize without an error.

## Location

[zebra-chain/src/block/serialize.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-chain/src/block/serialize.rs)

## Original issue description

Once Zebra starts generating its own blocks, we'll need to do the version check in a few more places:
- [ ] make sure serialized blocks contain a version that's 4 or greater, based on the consensus rules
- [x] impose a stricter version check on generated blocks, to ensure the version is always 4

This task is open to contributors, but some parts of it depend on future Zebra features.

**Comment by yaahc** [comment]
Removing open-to-contributors on this one based on [henry's comment](https://discordapp.com/channels/676527656170160146/716086297210650634/725765190137937950) pending further discussion in today's gardening session

**Comment by oxarbitrage** [comment]
Comment from Henry says "not sure about that one" but nothing more. I think we should detail further.

**Comment by yaahc** [comment]
I think the issue is that this depends on generating blocks which is something we don't have implemented yet, but I'm not sure, @hdevalence?

**Comment by oxarbitrage** [comment]
I am asking because if that is the case i think we could still check the version in the receiving side just as we did with header_solution and coinbase.

**Comment by teor2345** [comment]
The BlockVerifier checks the version on blocks as of PR #748.

**Comment by teor2345** [comment]
Oops, that's not correct, I misread the code.

Note: generated blocks aren't part of the "sync and validate" milestone. They only happen if we implement mining.

**Comment by teor2345** [comment]
We don't plan on generating blocks any time soon.

**Comment by teor2345** [comment]
This came up in the audit: there is a missing check in the block header version serialize function.
