### ISSUE TITLE
Only run one full sync on main at a time

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#4977]
## Motivation

There isn't much point in running multiple Mainnet full syncs on the `main` branch at the same time.

It slows down the Zcash network, costs the Foundation more money, and it doesn't provide much more diagnostic information.

### Designs

We could skip or cancel full syncs if there is already one running on `main`.
(But still run all the dependent jobs, if possible.)

We don't want to just limit the concurrency of jobs running on `main`, because that could queue up days worth of jobs on `main`.

**Comment by gustavovalverde** [comment]
What should be an expected scenario with 10 PRs waiting to be merged?
- Running the sync with the first merge and cancelling the following ones
- Waiting for a "merge-cycle" and run the sync with the last merge (every X PRs)
- Allow to trigger it with specific merges (not all PRs/merges need a full sync)

**Comment by teor2345** [comment]
The goals are:
- automatically do a full sync when the `main` branch has changed,
- only have one full sync running on `main` at the same time, and
- don't have a large queue of syncs waiting to run: the latest code is the most important to test.

It is ok to occasionally have two syncs running, if it turns out that is hard to avoid.

Also remember that the GitHub trigger is per-push, not per-PR. Mergify might have batched some of the PRs, there's no need to test every PR/commit in a batch push.

> What should be an expected scenario with 10 PRs waiting to be merged?
>     * Running the sync with the first merge and cancelling the following ones 
>     * Waiting for a "merge-cycle" and run the sync with the last merge (every X PRs)

The exact implementation doesn't really matter - either of those implementations would be ok.

But it seems like GitHub has exactly the implementation we want:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idconcurrency

If a concurrent job is running:
- when a new job arrives, make it pending, and cancel any jobs that were previously pending
- run the latest pending job when the original job finishes

> * Allow to trigger it with specific merges (not all PRs/merges need a full sync)

The check must be automated. When we've made checks manual in the past, people forget to do them.
