### ISSUE TITLE
Get transactions from the non-finalized state in the send transactions test

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5015]
## Motivation

Currently, the send transactions test is very slow, because it:
- copies the entire Zebra finalized state directory
- syncs to the tip
- gets transactions from the copied finalized state
- runs the test on the old finalized state

This is ok for now, but it might become a problem if the state gets much bigger, or we need to modify that test a lot.

### Designs

Instead, the test could:
- use the original Zebra cached state directory
- sync to the tip
- get transactions from at least 3 blocks in the non-finalized state via JSON-RPC
- run the test on the updated finalized state (which won't have all those non-finalized transactions)

**Comment by teor2345** [comment]
@arya2 here's an example of an RPC call from the tests:
https://github.com/ZcashFoundation/zebra/blob/7b47aac3703afe2e5efb45cdeb537a238ef45d4e/zebrad/tests/acceptance.rs#L2016-L2029

There's no need to use `zebra-rpc` or anything complicated to get the transaction data, because we're not really testing that RPC here.

**Comment by arya2** [comment]
@teor2345 Is there an easy way to use the original Zebra cached state directory?

Update: disregard, I was thinking only temp files could be accessed from the spawned process, but I found `spawn_zebrad_for_rpc` and realized we're already using the original cached state in some tests.
