### ISSUE TITLE
DevOps Ticket Tracker

### ISSUE THREAD

**Issue by ftm1000** [ZcashFoundation/zebra#5023]
DevOps tracker for open issues/tasks tagged with DevOps tag

**Comment by teor2345** [comment]
Is this epic just for DevOps issues we actually want to work on, or for scheduled issues, or for all issues?

(If we want to find all issues, we can also use the DevOps tag, and if we want to find scheduled issues, we can search by sprint.)

**Comment by mpguerra** [comment]
Yes, I think we need to find a better way to organise Devops work into longer term projects (which would be epics) versus tactical fixes which would just be standalone issues which could be scheduled in a sprint.

**Comment by teor2345** [comment]
> Yes, I think we need to find a better way to organise Devops work into longer term projects (which would be epics) versus tactical fixes which would just be standalone issues which could be scheduled in a sprint.

I think that would be really helpful!

I wonder if we have any longer-term DevOps work we want to do for Zebra right now. But even if we don't, it would be good to know that. (And check with the team to be sure.)

**Comment by mpguerra** [comment]
going to remove epic label and  close this one for now.
