### ISSUE TITLE
Implement pipelineable block lookup

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#504]
This issue summarizes a discussion from discord with @yaahc and @teor2345.

To sync the chain, we need to find out which blocks to download and then download them.  Downloaded blocks can then be fed into the verification system and (assuming they verify correctly) into the state system.  In `zcashd`, blocks are processed one at a time.  In Zebra, however, we want to be able to pipeline block download and verification operations, using futures to explicitly specify logical dependencies between sub-tasks, which we execute concurrently and potentially out-of-order on a threadpool. This means that the procedure we use to determine which blocks to download must look somewhat different than `zcashd`.

## Block fetching in Bitcoin

Zcash inherits its network protocol from Bitcoin. Bitcoin block fetching works roughly as follows.  A node can request block information from peers using either a `getblocks` or `getheaders` message.  Both of these messages contain a *block locator object* consisting of a sequence of block hashes.  The block hashes are ordered from highest to lowest, and represent checkpoints along the path from the node's current tip back to genesis.  The remote peer computes the intersection between its chain and the node's chain by scanning through the block locator for the first hash in its chain.  Then, it sends (up to) 500 subsequent block hashes in an `inv` message (in the case of `getblocks`) or (up to) 2000 block headers in a `headers` message (in the case of `getheaders`).  Note: `zcashd` reduces the `getheaders` count to 160, because Zcash headers are much larger than Bitcoin headers, as noted below.

The `headers` message sent after `getheaders` contains the actual block headers, while the `inv` message sent after `getblocks` contains only hashes, which have to be fetched with a `getdata` message.  In Bitcoin, the block headers are small relative to the size of the full block, but this is not always the case for Zcash, where the block headers are much larger due to the use of Equihash and many blocks have only a few transactions.  Also, `getblocks` allows parallelizing block downloads, while `getheaders` doesn't. For these reasons and because we know we need full blocks anyways, we should probably use `getblocks`.

The `getblocks` Bitcoin message corresponds to our `zebra_network::Request::FindBlocksByHash`, and the `getdata` message is generated by `zebra_network::Request::Blocks`.

## Pipelining block verification

As mentioned above, our goal is to be able to pipeline block download and verification.  This means that the process for block lookup should ideally attempt to fetch and begin verification of future blocks without blocking on complete verification of all earlier blocks.  To do this, we split the chain state into the *verified* block chain (held by the state component) and the *prospective* block chain (held only by the syncer), and use the following algorithm to pursue prospective chain tips.  

#### ObtainTips

1. Query the current state to construct the sequence of hashes
```
[tip, tip-1, tip-2, ..., tip-9, tip-20, tip-40, tip-80, tip-160 ]
```
The precise construction is unimportant, but this should have a Bitcoin-style dense-first, then-sparse hash structure.

The initial state should contain the genesis block for the relevant network. So the sequence of hashes will only contain the genesis block
```
[genesis ]
```
The network will respond with a list of hashes, starting at the child of the genesis block.

2. Make a `FindBlocksByHash` request to the network `F` times, where `F` is a fanout parameter, to get `resp1, ..., respF`.

3. For each response, starting from the beginning of the list, prune any block hashes already included in the state, stopping at the first unknown hash to get `resp1', ..., respF'`.  (These lists may be empty).

4. Combine the last elements of each list into a set; this is the set of prospective tips.

5. Combine all elements of each list into a set, and queue download and verification of those blocks.

6. If there are any prospective tips, call ExtendTips, which returns a new set of prospective tips. Continue calling ExtendTips with this new set, until there are no more prospective tips.

7. Restart after some delay, say 15 seconds.

#### ExtendTips

1. Remove all prospective tips from the set of prospective tips, then iterate through them.  For each removed tip:

2. Create a `FindBlocksByHash` request consisting of just the prospective tip.  Send this request to the network `F` times.

3. For each response, check whether the first hash in the response is a genesis block (for either the main or test network). If so, discard the response. It indicates that the remote peer does not have any blocks following the prospective tip. (Or that the remote peer is on the wrong network.)

4. Combine the last elements of the remaining responses into a set, and add this set to the set of prospective tips.

5. Combine all elements of the remaining responses into a set, and queue download and verification of those blocks.

### DoS resistance

Because this strategy aggressively downloads any available blocks, it could be vulnerable to a DoS attack, where a malicious peer feeds us bogus chain tips, causing us to waste network and CPU on blocks that will never be valid.  However, because we separate block finding from block downloading, and because of the design of our network stack, this attack is probably not feasible.  The primary reason is that `zebra_network` randomly loadbalances outbound requests over all available peers.

Consider a malicious peer who responds to block discovery with a bogus list of hashes.  We will eagerly attempt to download all of those bogus blocks, but our requests to do so will be randomly load-balanced to other peers, who are unlikely to know about the bogus blocks. When we try to extend a bogus tip, the extension request will also be randomly load-balanced, so it will likely be routed to a peer that doesn't know about it and can't extend it. And because we perform multiple block discovery queries, which will also be randomly load balanced, we're unlikely to get stuck on a false chain tip. 

### Fork-finding

When starting from a verified chain tip, the choice of block locator can find forks at least up to the reorg limit (99 blocks). When extending a prospective tip, forks are ignored, but this is fine, since unless we are prefetching the longest chain, we won't be able to keep extending the tip prospectively.

### Retries and Fanout

We should consider the fanout parameter `F` and the retry policy for the different requests.  I'm not sure whether we need to retry requests to discover new block hashes, since the fanout may already provide redundancy.  For the block requests themselves, we should have a retry policy with a limited number of attempts, enough to insulate against network failures but not so many that we would retry a bogus block indefinitely. Maybe fanout 4 and 3 retries?

**Comment by teor2345** [comment]
Thanks, this looks like a great design. Let's commit it to the design/ folder as part of the implementation PR?

I wonder what happens when we get near the tip of the main chain, particularly during the initial sync. We're likely to get a set prospective tips that represent [tip, tip-1, tip-2, ...] on the main chain.

But that's ok, because if the network is in a state where not all nodes have the same tip, then miners could be mining off any of those tips.

We'll also want to avoid downloading a block multiple times, regardless of whether that block is in the queue, a download Future, or a verification Future. But we can do a best-effort implementation here.

**Comment by teor2345** [comment]
I edited the ticket to document the initial ObtainTips, where we have no state:

    When the current state is empty, the sequence of hashes should also be empty
    [ ]
    The network responds with a list of hashes starting at the genesis block.

**Comment by hdevalence** [comment]
@teor2345 Do we know what the zcashd/bitcoin behavior for `getblocks` messages is? At least https://en.bitcoin.it/wiki/Protocol_documentation#getblocks has a note that there is a minimum of one hash.  If we consider the state to always include the genesis block, then we'd never have an empty state, so we could always include the hash of the genesis block and avoid an empty message.

**Comment by hdevalence** [comment]
> We'll also want to avoid downloading a block multiple times, regardless of whether that block is in the queue, a download Future, or a verification Future. But we can do a best-effort implementation here.

I don't think we'll need to do anything extra, even on a best-effort basis, provided we implement the algorithm as described above, because it's already constructed to not ever download the same block twice, assuming our peers are honest.

**Comment by hdevalence** [comment]
Edited the description to clarify the iteration in `ExtendTips`.

**Comment by teor2345** [comment]
> @teor2345 Do we know what the zcashd/bitcoin behavior for `getblocks` messages is? At least https://en.bitcoin.it/wiki/Protocol_documentation#getblocks has a note that there is a minimum of one hash. If we consider the state to always include the genesis block, then we'd never have an empty state, so we could always include the hash of the genesis block and avoid an empty message.

I don't see a one hash minimum implemented anywhere obvious:
https://github.com/zcash/zcash/blob/6d9573c66e33b5b742c49ab35e816d74d4ab55b1/src/main.cpp#L5838
https://github.com/zcash/zcash/blob/6d9573c66e33b5b742c49ab35e816d74d4ab55b1/src/main.cpp#L569

But I wouldn't want to rely on unspecified behaviour. And we want to use responses starting with the genesis block hash as an error sentinel.

So let's hard-code the main net and test net genesis blocks, and initialise the state with the relevant block.

**Comment by teor2345** [comment]
> > We'll also want to avoid downloading a block multiple times, regardless of whether that block is in the queue, a download Future, or a verification Future. But we can do a best-effort implementation here.
> 
> I don't think we'll need to do anything extra, even on a best-effort basis, provided we implement the algorithm as described above, because it's already constructed to not ever download the same block twice, assuming our peers are honest.

I don't think that's necessarily true. As far as I can see, there is a race between the block downloader, block verifier, state updates, and ObtainTips/ExtendTips.

Let's say we query a peer that only has part of the main chain. (Perhaps it is new, or has unreliable connectivity.) Or we query an implementation that provides fewer than 500 hashes in response to getblocks.

So the prospective tip from that peer lags behind the tips from other peers. And all other tips derived from that tip will also lag.

When a tip lags behind, we'll re-queue the earliest blocks in each lagged response, even though they overlap with the last set of queued blocks.

So I think we need to make the following parts of the design explicit:
1. If a prospective tip is an ancestor of another prospective tip, it is ignored.
2. The download queue is a set of hashes. Duplicate hashes are ignored.
3. Do we also ignore hashes that have been downloaded, and are being verified?
4. Does ExtendTips also ignore blocks that are in the state?

The precise sequence of operations is also unclear:
* Is each ExtendTips followed by another ExtendTips? What is the delay?
* What happens to the set of prospective tips generated by ExtendTips? Is it re-used by the next ExtendTips or ObtainTips?

Also, what's the best case sync time?

If we do an ObtainTips, then do an ExtendTips, then wait 15 seconds, and restart with ObtainTips, it will take about 4 hours to sync. (900,000 blocks / 1000 blocks per iteration * 15 seconds = 3.75 hours.)

**Comment by teor2345** [comment]
> So I think we need to make the following parts of the design explicit:
> 
> 1. If a prospective tip is an ancestor of another prospective tip, it is ignored.
> 2. The download queue is a set of hashes. Duplicate hashes are ignored.
> 3. Do we also ignore hashes that have been downloaded, and are being verified?
> 4. Does ExtendTips also ignore blocks that are in the state?

Actually, I think it's better for the downloader to keep a set of all the hashes in the state, and all the hashes it has ever queued. Then we won't download any duplicate blocks:
https://github.com/ZcashFoundation/zebra/pull/506#discussion_r443739068

I'm not sure what happens if a block is temporarily unavailable, or temporarily unverifiable. We'd need to retry downloads in that case.

**Comment by yaahc** [comment]
> When a tip lags behind, we'll re-queue the earliest blocks in each lagged response, even though they overlap with the last set of queued blocks.

This seems legit. At least in the lagged request case we should be able to fix it by adding a prune step that prunes any prospective tips that were present in other responses but not as the tip of that response.

edit: i see this is 1.) on your list

**Comment by yaahc** [comment]
> Do we also ignore hashes that have been downloaded, and are being verified?

I think so long as all the prospective tips are entirely new blocks via the fix in step 1) this is impossible by construction as Henry said.

> Does ExtendTips also ignore blocks that are in the state?

I think it avoids them.

> Is each ExtendTips followed by another ExtendTips? What is the delay?

Yes. None.

> What happens to the set of prospective tips generated by ExtendTips? Is it re-used by the next ExtendTips or ObtainTips?

Reused by the next ExtendTips

**Comment by hdevalence** [comment]
> Let's say we query a peer that only has part of the main chain. (Perhaps it is new, or has unreliable connectivity.) Or we query an implementation that provides fewer than 500 hashes in response to getblocks.
> 
> So the prospective tip from that peer lags behind the tips from other peers. And all other tips derived from that tip will also lag.
> 
> When a tip lags behind, we'll re-queue the earliest blocks in each lagged response, even though they overlap with the last set of queued blocks.

Yes, but there is an easier way to solve this problem: drop any responses that are shorter than the longest response.

> So I think we need to make the following parts of the design explicit:
> 
> 1. If a prospective tip is an ancestor of another prospective tip, it is ignored.
> 
> 2. The download queue is a set of hashes. Duplicate hashes are ignored.

Yes, this is step 5: "combine all elements of the remaining responses into a set".

> 3. Do we also ignore hashes that have been downloaded, and are being verified?

No, because we ask for hashes following the blocks we've already started feeding into the pipeline.

> 4. Does ExtendTips also ignore blocks that are in the state?

No, because it extends tips that are already not in the state.

> The precise sequence of operations is also unclear:
>
> * Is each ExtendTips followed by another ExtendTips? What is the delay?

Yes, as specified in Step 6 of ObtainTips:  "Continue this step until there are no more prospective tips."

> * What happens to the set of prospective tips generated by ExtendTips? Is it re-used by the next ExtendTips or ObtainTips?

Yes, in step 4: "and add this set to the set of prospective tips".


> Also, what's the best case sync time?
> 
> If we do an ObtainTips, then do an ExtendTips, then wait 15 seconds, and restart with ObtainTips, it will take about 4 hours to sync. (900,000 blocks / 1000 blocks per iteration * 15 seconds = 3.75 hours.)

No, we use ObtainTips only when we're not already chasing a chain.  So we download at full speed until we get to the end of the chain, and then only poll occasionally.

**Comment by teor2345** [comment]
> > Let's say we query a peer that only has part of the main chain. (Perhaps it is new, or has unreliable connectivity.) Or we query an implementation that provides fewer than 500 hashes in response to getblocks.
> > So the prospective tip from that peer lags behind the tips from other peers. And all other tips derived from that tip will also lag.
> > When a tip lags behind, we'll re-queue the earliest blocks in each lagged response, even though they overlap with the last set of queued blocks.
> 
> Yes, but there is an easier way to solve this problem: drop any responses that are shorter than the longest response.

This change would break fork handling and main chain selection, if shorter chain has the greatest proof of work.

The consensus rule is:
> In order to choose the best valid block chain in its view of the overall block tree, a node sums the work, as defined in § 7.6.5 ‘Definition of Work’ on p. 91, of all blocks in each valid block chain, and considers the valid block chain with greatest total work to be best. To break ties between leaf blocks, a node will prefer the block that it received first.

Section 3.3, Zcash Specification.

So I think we can only do common prefix elimination. Once we make this change, the design works as specified.

I agree with the sequence of operations. I have tweaked the issue description to make them clearer.

**Comment by hdevalence** [comment]
I don't think it does break fork handling, because the ExtendTips procedure already doesn't (and isn't intended) to handle forks; that's done by `ObtainTips`.

**Comment by teor2345** [comment]
I think you're right. In the worst-case scenario, a malicious peer can cause us to waste an entire `ObtainTips` cycle.

Here's the attack:
1. We are within 500 blocks of the end of the chain.
2. A malicious peer responds with 500 arbitrary hashes.
3. We discard the shorter main chain (and any genuine forks), and follow the malicious hashes.

Here's one possible defence:
* Each `ObtainTips` and `ExtendTips` request should randomly select a new set of peers.

If we re-use a malicious peer, it can force us to follow an arbitrarily long chain.

Here's a possible optimisation:
* We queue shorter chains for downloading, but don't use their tips.

With this optimisation, we will download and validate the main chain, even if it is shorter than other chains.

**Comment by teor2345** [comment]
I've updated the description so we reject either genesis block. That way, we reject peers on the wrong network:
https://github.com/ZcashFoundation/zebra/pull/506#discussion_r443912828

**Comment by yaahc** [comment]
I'm still not clear if I should be pruning tips that are ancestors of other tips or dropping chains that are not the max length, so I went with the former because it makes more sense to me atm. Implemented the fix for this here https://github.com/ZcashFoundation/zebra/pull/531/files, also fixed a bug (I think?) where I forgot to include the tips in the set of blocks to download.

**Comment by teor2345** [comment]
As we talked about earlier today, either solution is fine in the alpha release.

**Comment by hdevalence** [comment]
I think this will be closed by #540.

**Comment by teor2345** [comment]
We still need to commit the design doc to the repository. Is there an issue or PR for that?

**Comment by yaahc** [comment]
@teor2345 I've started the process for creating the design doc for this in https://github.com/ZcashFoundation/zebra/pull/583. I went ahead and just started by copying over rust's RFC template which should hopefully be a good design doc template

**Comment by teor2345** [comment]
Great, if there's another ticket, then we can close this one.
