### ISSUE TITLE
Fix "Connection closed by remote host" error on Google Cloud ssh

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5069]
## Motivation

A few different PRs seem to be failing with this error:
> kex_exchange_identification: Connection closed by remote host
https://github.com/ZcashFoundation/zebra/runs/8161163434?check_suite_focus=true#step:7:86

**Comment by teor2345** [comment]
I haven't seen these errors recently, I wonder if they are caused by rate-limiting?

We could add the `ConnectionAttempts` option to the SSH command-line to fix this.

**Comment by teor2345** [comment]
This happened again today:
https://github.com/ZcashFoundation/zebra/actions/runs/3033472434/jobs/4881881486#step:8:106

**Comment by teor2345** [comment]
Failed on `main`:
https://github.com/ZcashFoundation/zebra/actions/runs/3053855581/jobs/4926083103#step:6:105

**Comment by teor2345** [comment]
It looks like this is now more frequent than the other Google Cloud errors.

**Comment by teor2345** [comment]
Failed 3 times on `main` in the same workflow:
https://github.com/ZcashFoundation/zebra/actions/runs/3150972503/jobs/5131855566
https://github.com/ZcashFoundation/zebra/actions/runs/3150972503/jobs/5131861932
https://github.com/ZcashFoundation/zebra/actions/runs/3150972503/jobs/5131846881

**Comment by gustavovalverde** [comment]
The `main` branch has been failing recently with this errors. So I'm reopening this one

**Comment by gustavovalverde** [comment]
I've been able to find this error log in GCP

```
Supplied fingerprint does not match current metadata fingerprint.
```

I've also found the root cause: some `ssh-keys` in the project metadata that might have been added when testing OS Login.

This might not solve the problem, but will at least reduce the noise when searching for the actual error.

**Comment by teor2345** [comment]
> I've also found the root cause: some `ssh-keys` in the project metadata that might have been added when testing OS Login.

Thanks for tracking this down!
