### ISSUE TITLE
Can we filter out notifications from [bots]?

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#508]
They leave a lot of spam via discord/slack/github notifications.

**Comment by hdevalence** [comment]
There should be some filter in the webhook setting in this repo.

**Comment by dconnolly** [comment]
I think @yaahc was specifically citing GitHub notifications and I don't know if webhook filters affect that but

**Comment by dconnolly** [comment]
I think this has been cleaned up by some config changes made by @hdevalence
