### ISSUE TITLE
Make sure Zebra can sync from a local zcashd node

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#509]
During testing, we'll want to sync Zebra from a local zcashd node.

This feature will be useful for:
* network integration tests (#466), so tests are reproducible, and
* developers or testers on slow networks, or networks with high bandwidth charges.

For integration tests, the restrictions should be strict: all communication should go to the specified nodes.

For developers or testers, the restrictions can be flexible:
* best effort, or
* only apply when syncing a large amount of blocks up to the current tip.

**Comment by hdevalence** [comment]
I've done this before in a one-off way. There are two steps:

1. Telling Zebra to connect to the local Zcashd instance.  This can be done already using the config file.

2. Telling Zebra not to connect to any other nodes.  I did this by commenting out the part of the network init that spun up the crawler task, so the peer set never discovered any other nodes to connect to.  This is obviously not an ideal solution.  A potential alternative I haven't thought through could be to use a limit of 1 on the peer set size.

**Comment by teor2345** [comment]
It works enough for now :-)

**Comment by dconnolly** [comment]
> It works enough for now :-)
