### ISSUE TITLE
Prepare issue and response templates for user issues

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#5120]
## Motivation

Zebra is going to have its first release candidates and active users. We should prepare issue templates to make bug reporting unified and easy for people outside the ZF team.

We might also want to have some suggested responses to tell users when they report issues.

Related issue: #5121.

**Comment by mpguerra** [comment]
Aside from the response template, what is the difference between this a our existing bug report template? Have we decided how we are going to ask users to report issues? e.g is it just going to be by creating a new issue in github?

**Comment by upbqdn** [comment]
> what is the difference between this a our existing bug report template?

The way I see it is that bug reports are related to the source code, and issue reports are related to usability. I think we could just edit the existing bug report if such a distinction is unnecessary.

> Have we decided how we are going to ask users to report issues? e.g is it just going to be by creating a new issue in github?

This should be addressed in #5121.

**Comment by teor2345** [comment]
> > what is the difference between this a our existing bug report template?
> 
> The way I see it is that bug reports are related to the source code, and issue reports are related to usability. I think we could just edit the existing bug report if such a distinction is unnecessary.

I think it would be ok to make the bug report template into a "user bug report" template.

We're not using it as developers, because we have usually:
- already diagnosed the bug, or
- we've seen it on our supported infrastructure in CI.
