### ISSUE TITLE
Document where users can get support

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#5121]
## Motivation

Zebra is going to have its first release candidates and active users. We should document, ideally in the README, where users can get support for Zebra.

**Comment by mpguerra** [comment]
Is this already decided or should we open up a discussion about it?

**Comment by upbqdn** [comment]
I think the only two official places will be the `zebra-support` channel on Discord and GitHub Issues. We agreed that this should be mentioned in the README.

**Comment by teor2345** [comment]
We aren't doing user support yet.
