### ISSUE TITLE
Tag Google Cloud instances with the name of the test or workflow for cost management

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5153]
## Motivation

When we look at Google Cloud costs, we want to know which test or continuous deployment is causing them.

This is essential for reducing Google Cloud costs, which we significantly larger than our budget in September.

## Priority

The priority of this ticket depends on Google Cloud costs from 24-30 September.

**Comment by teor2345** [comment]
I added this ticket to the sprint, because it helps us work out how to limit Google Cloud costs.

**Comment by mpguerra** [comment]
I'm going to move this to the next sprint. Although this is important it's not high priority for this sprint.

**Comment by teor2345** [comment]
> I'm going to move this to the next sprint. Although this is important it's not high priority for this sprint.

This is essential for reducing Google Cloud costs, which are currently significantly larger than our budget.

So if we run out of DevOps work in this sprint, let's do this next.

**Comment by teor2345** [comment]
> > I'm going to move this to the next sprint. Although this is important it's not high priority for this sprint.
> 
> This is essential for reducing Google Cloud costs, which are currently significantly larger than our budget.
> 
> So if we run out of DevOps work in this sprint, let's do this next.

I just looked at costs, and they have decreased significantly over the past week.

So let's check costs during sprint planning, and set the priority of this ticket then.

**Comment by teor2345** [comment]
Tagging it as low for now, in the hope that costs continue to be low.

**Comment by teor2345** [comment]
We only need to do this if cost is a concern.

**Comment by teor2345** [comment]
@mpguerra it looks like cost might be a problem, so let's re-check next week, and schedule this in the next sprint if needed?

We can get the CI failure rate down first, move jobs to the main branch, and make the send transaction test faster (#5015).
But then we need this ticket to find out which other jobs we need to speed up.

**Comment by teor2345** [comment]
Costs were reasonable for October, so we don't need to do this unless we need to do detailed cost monitoring again.
