### ISSUE TITLE
docs: Create a user documentation explaining how to use Zebra with Docker

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5167]
## Motivation

We don't have user documentation regarding how to use Zebra with Docker

### Designs

We might want to include:
- TLDR to run
- How to build
- How to pull it
- How to run CI locally
- How to develop with Docker locally (?)

## Related Work

Originated from: https://github.com/ZcashFoundation/zebra/pull/5163#discussion_r971284355

**Comment by teor2345** [comment]
I'd like to split out the developer parts of this ticket:
- How to build
- How to run CI locally
- How to develop with Docker locally (?)

The user docs seem like a medium priority, but the developer docs seem like a low priority.

**Comment by teor2345** [comment]
> I'd like to split out the developer parts of this ticket:
>     * How to build
>     * How to run CI locally
>     * How to develop with Docker locally (?)
> 
> The user docs seem like a medium priority, but the developer docs seem like a low priority.

@mpguerra @gustavovalverde did you want to split the developer parts of this ticket into a separate ticket?

**Comment by teor2345** [comment]
This was closed by PR #5504, the developer parts are in ticket #4464 already.
