### ISSUE TITLE
Add Docker tests for default config and $ZEBRA_CONF_PATH

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5168]
## Motivation

We want to test that our Docker build scripts configure Zebra correctly:
- check that $ZEBRA_CONF_PATH works
- make sure the default Docker config works with the latest Zebra version

## Suggested Solution

- move the default Docker config into a file 
- add that file to the Zebra config test directory, all configs in this directory are automatically tested with Zebra:
    - https://github.com/ZcashFoundation/zebra/tree/main/zebrad/tests/common/configs
- add a Docker test for the default config
- add a Docker test for $ZEBRA_CONF_PATH

Here's one possible test script:
```sh
# make sure Zebra runs with the default docker config
docker run ... | grep --max-count=1 'estimated progress to chain tip.*BeforeOverwinter'
docker stop ...

# make sure Zebra runs with a custom docker config
TODO: copy the file into docker?
export ZEBRA_CONF_PATH=`zebra/zebrad/tests/common/configs/v1.0.0-rc.2.toml`
docker run ... | grep --max-count=1 'v1.0.0-rc.2.toml'
docker stop ...
```

## Related Work

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/5163#discussion_r971283944_

The test script depends on PR #5733 merging.

**Comment by mpguerra** [comment]
removing this one from the release candidate epic

**Comment by teor2345** [comment]
This isn't causing any problems for us right now, but we should test this new docker feature soon. (In the next sprint is ok.)

**Comment by teor2345** [comment]
I added some more details to this ticket, and a possible test script.

**Comment by teor2345** [comment]
@mpguerra I moved this ticket out of this sprint, because some devops tasks were still open from last sprint.

But feel free to move it back in!
