### ISSUE TITLE
ci: Add a workflow to build Dockerfile layers independently

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5178]
## Motivation

We should have a workflow to test that Zebra builds with Docker with different targets (`test` and `release`). As `release` is just tested on the `main` branch, but we should asure this works in a PR before merging.

> In the long-rung a single build workflow should exists to test Zebra builds in all platforms (including Docker), without pushing the binaries.

### Designs
- Create a build workflow similar to `build-crates-individually.yml`

## Related Work

Originated by: https://github.com/ZcashFoundation/zebra/actions/runs/3059162353/jobs/4936544609#step:8:317

**Comment by teor2345** [comment]
I think this might be a low priority, because it doesn't cause failures very often.

When it does cause a failure, let's track them on this ticket, so we know how important it is.

**Comment by gustavovalverde** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5178?planning-poker) with Zenhub @arya2 @dconnolly @teor2345

**Comment by gustavovalverde** [comment]
As the release process is **after** merging to `main`, this is not required unless it causes issues in the future. It would only add extra complicity to PRs workflows.

We recently added https://github.com/ZcashFoundation/zebra/pull/5968 which also reduces this risk
