### ISSUE TITLE
Better version negotiation in the peer connection handshake

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#52]
We should check zcashd to ensure we are constructing version handshake messages with fields that have the same meaning as `zcashd`.

**Comment by hdevalence** [comment]
Reference: zcashd handles incoming version messages here: https://github.com/zcash/zcash/blob/master/src/main.cpp#L5416-L5569

**Comment by dconnolly** [comment]
We never actually check and agree on a version so uh, we should do that.

**Comment by hdevalence** [comment]
Added the `research` label since there's some looking into how zcashd behaves involved.

**Comment by dconnolly** [comment]
![image](https://user-images.githubusercontent.com/552961/72561887-2a972180-3878-11ea-80b0-134c4ffb042f.png)

**Comment by dconnolly** [comment]
This is 'done' by #295 , there may be an edge case if version changes happen in the future.

https://github.com/ZcashFoundation/zebra/pull/295#discussion_r388549034
