### ISSUE TITLE
Actions workflow displays duplicate warnings

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#525]
It seems like every platform we test on is adding its own duplicate warnings:

![image](https://user-images.githubusercontent.com/44879/85319925-24385180-b477-11ea-8f52-943f99438187.png)

**Comment by hdevalence** [comment]
I haven't seen this reoccur, so I think it's been fixed.

**Comment by teor2345** [comment]
Here's a recent example, but I'm not sure if there is anything we can do to actually fix the issue:
https://github.com/ZcashFoundation/zebra/pull/833/files#diff-0f952e6068cc909f968e4d2115f78032R47
