### ISSUE TITLE
Disable code timers unless a specific `zebrad` feature is activated

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5253]
## Motivation

We're running a lot of code timers that never actually log anything. But calling those time functions can be really expensive on some operating systems.

### Designs

Add a new `zebrad` feature that activates a `zebra-chain` feature with the same name.
This feature should be off by default.

When the feature is off, disable all the code and fields in the `CodeTimer` struct.
Just have a stub, so that code can still call the methods even when the feature is off.

**Comment by teor2345** [comment]
If CI passes on PR #5164, we can mark this ticket as optional and close it.
If it fails with a timeout, it is a medium priority for this sprint.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5253?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @teor2345 @upbqdn

**Comment by teor2345** [comment]
We fixed the speed issues another way, so we don't need to do this ticket any time soon.

**Comment by teor2345** [comment]
We're not making changes like this while the audit is pending
