### ISSUE TITLE
Write up how we want to do tags and feature branches

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5259]
## Motivation

We want to document the process we decided for new features. We also want to write down the goals we're trying to satisfy.

The draft notes are in the Retrospective pad.
We've also had some conversations in Slack about how this could work.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5259?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @gustavovalverde @teor2345 @upbqdn

**Comment by teor2345** [comment]
The audit tag and branch part got split into ticket #5431 and PR #5395.
