### ISSUE TITLE
Increase the timeout for db_init_outside_future_executor

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5295]
## Motivation

The db_init_outside_future_executor test failed with:
> Message:  futures executor was blocked longer than expected (5.487612ms)

https://github.com/ZcashFoundation/zebra/actions/runs/3141191750/jobs/5103357118#step:10:2995

On a busy test virtual machine, we can't guarantee that the Zebra tests will get CPU time every few milliseconds. Similar timeouts elsewhere in the tests are hundreds of milliseconds or a few seconds.

## Related Work

This test bug was introduced by PR #5228

**Comment by teor2345** [comment]
This happened again, so I'm moving it to the current sprint.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5295?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @teor2345 @upbqdn
