### ISSUE TITLE
Rename zebra-test-vectors to zebra-test

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#530]
> As for where to put the shared utility code, I was thinking we should take `zebra-test-vectors` and rename it to `zebra-test` and make that the crate where we store all of our shared test utilities and artifacts. Take the existing vectors and shove them in a `mod vectors;` and then put `install_tracing()` in the root. We will probably want to rename it to just `install` or `init` because I'm also gonna shove some `eyre` stuff in there.

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/issues/515#issuecomment-647809038_

**Comment by teor2345** [comment]
While we're moving things around, we could also move the genesis blocks to zebrad or zebra-chain. That way, we can initialise the state with the relevant genesis block:
https://github.com/ZcashFoundation/zebra/pull/506#discussion_r443917501

**Comment by hdevalence** [comment]
@teor2345 Sounds good! There could be a separate PR for that, I wanted to do the renaming alone just because other changes block on it.

**Comment by teor2345** [comment]
I understand, this PR makes a *lot* of little changes across the codebase.
