### ISSUE TITLE
Add support for `getblockcount` RPC call

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5303]
## Motivation

Mining pools use the `getblockcount` RPC call.

### Mining Pool Usage

`s-nomp` calls `getblockcount` from this code:
- https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L595

## Requirements

https://zcash.github.io/rpc/getblockcount.html

## Testing

- [x] Snapshot the output of the RPC
- [ ] Test calling the RPC from the mining pool software
- [x] Manually compare the `zcashd` and `zebrad` RPC output using https://github.com/ZcashFoundation/zebra/blob/main/zebra-utils/zcash-rpc-diff

**Comment by oxarbitrage** [comment]
This seems to be just the current tip of the blockchain but the [rpc method description](https://zcash-rpc.github.io/getblockcount.html) of the docs is not up to date: https://github.com/zcash/zcash/issues/2735#issuecomment-458252350

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5303?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn
