### ISSUE TITLE
Only run the `lightwalletd` full sync on the `main` branch

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5316]
## Motivation

In PR #5164, we made `lightwalletd` sync all the way to the tip in its full sync test.

This increases that test's time from 1 hour to 4 hours, which makes the CI we run on each PR change increase from 3 hours to 6 hours.

This increases Google Cloud costs, and makes PR testing and merges slower for engineers.

### Designs

We're already running the full `zebrad` sync only on the `main` branch.
We can copy and paste the workflow code to the full `lightwalletd` sync, so this should be an easy change.

We might also need to update the patch workflows or the branch protection rules.

**Comment by teor2345** [comment]
@mpguerra PR #5164 will double the time it takes to run CI on every PR change (from 3 hours to 6 hours).

So we might want to schedule this work early in the next sprint, or right after PR #5164 merges.

**Comment by mpguerra** [comment]
> ## Motivation
> 
> In PR #5164, we made `lightwalletd` sync all the way to the tip in its full sync test.

What was it doing before and why did we change it?

**Comment by teor2345** [comment]
> > ## Motivation
> > In PR #5164, we made `lightwalletd` sync all the way to the tip in its full sync test.
> 
> What was it doing before and why did we change it?

We were skipping all the blocks after 1.7 million, because we needed to add some extra test code to test those blocks. But this meant that we weren't testing those blocks at all. So we didn't find issues like #5307 until now.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5316?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn
