### ISSUE TITLE
ERROR: (gcloud.compute.ssh) User [None] does not have permission to access users instance [None] (or it may not exist) on main branch

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5332]
## Motivation

2 of the last few main branch commits have failed with:
> ERROR: (gcloud.compute.ssh) User [None] does not have permission to access users instance [None] (or it may not exist): End user credentials must match the user specified in the request. Request for user [ None] does not match the credential for [github-service-account@zealous-zebra.iam.gserviceaccount.com].

https://github.com/ZcashFoundation/zebra/actions/runs/3180237524/jobs/5184393771#step:7:97
https://github.com/ZcashFoundation/zebra/actions/runs/3179050813/jobs/5192664093#step:6:103

Sometimes this happens during instance creation, sometimes during the test run.

### Possible Fixes

@gustavovalverde will this be fixed by the SSH action?

**Comment by gustavovalverde** [comment]
Yes https://github.com/ZcashFoundation/zebra/pull/5330 should fix this

**Comment by teor2345** [comment]
A manual full sync on PR #5257 also failed multiple times due to this bug:
https://github.com/ZcashFoundation/zebra/actions/runs/3184782188

**Comment by teor2345** [comment]
It looks like all Rust PRs are failing in the Google Cloud tests due to this bug.
