### ISSUE TITLE
Restrict zebrad commands that are actually available on release build

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#535]
We can:
* delete some commands, or
* move some commands to the utils crate

![image](https://user-images.githubusercontent.com/552961/85475749-9480c900-b584-11ea-84e7-e27cadf7ba59.png)

**Comment by dconnolly** [comment]
Probably:
- generate
- help
- start
- version

Do we need `seed` ? @gtank

**Comment by hdevalence** [comment]
Potentially related: https://github.com/ZcashFoundation/zebra/issues/536#issuecomment-648578315

**Comment by oxarbitrage** [comment]
By doing some research online it seems a way(maybe the only one) to do something like this will be with `debug_assertions` (https://doc.rust-lang.org/reference/conditional-compilation.html#debug_assertions) used as a conditional above the commands we want to remove from release, for example we could do:

```
    #[cfg(debug_assertions)]
    #[options(help = "testing stub for dumping network messages")]
    Connect(ConnectCmd),
```

This will disable the connect command from the release build(we should probably also make some other conditional in the imports).

ITOH by @hdevalence comment in #536 i am not sure if this should be implemented.

**Comment by yaahc** [comment]
@oxarbitrage I think theres been a bit of a mixup, I don't think we want to have the commands that are available be based on if optimizations are enabled. We wanted to have a minimal subset of the commands exposed when we eventually make an official tagged release. Also, if I remember correctly, the plan isn't to use conditional compliation but to just remove the unwanted commands completely as one of the tasks before the next release. cc @ZcashFoundation/zebra-team

**Comment by oxarbitrage** [comment]
Ok, that is clear now, thanks.

**Comment by hdevalence** [comment]
The only one of these that doesn't serve a purpose was connect, which was removed.
