### ISSUE TITLE
Google Cloud ssh-compute action: "destination read failed"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5362]
## Motivation

> ERROR: (gcloud.compute.start-iap-tunnel) Error while connecting [4010: 'destination read failed'].
kex_exchange_identification: Connection closed by remote host

https://github.com/ZcashFoundation/zebra/actions/runs/3203311358/jobs/5234000346#step:6:106

## Alternatives

We could ask for a retry option on https://github.com/google-github-actions/ssh-compute

We could manually retry the ssh step ourselves.

If we can't fix these errors, we might want to revert all of PRs #5330 and #5358.

**Comment by teor2345** [comment]
We don't know the priority here until we know how frequent this error is.

**Comment by gustavovalverde** [comment]
Research info: https://issuetracker.google.com/issues/228091306#comment5
