### ISSUE TITLE
Fix "the resource was not found" instance errors in CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5366]
## Motivation

I'm seeing errors like this in CI:
>  - The resource 'projects/zealous-zebra/zones/us-central1-a/instances/update-to-tip-5360-merge-818a593' was not found

https://github.com/ZcashFoundation/zebra/actions/runs/3203311358/jobs/5239744583#step:6:101

### Command Reference

https://cloud.google.com/sdk/gcloud/reference/topic/filters

### Designs

I'm not sure what is causing these bugs, we only delete instances after 3 days:
https://github.com/ZcashFoundation/zebra/blob/ee0edef8571d3ed82848303b142c7ae72e7135fc/.github/workflows/delete-gcp-resources.yml#L56

And after the job fails:
https://github.com/ZcashFoundation/zebra/blob/ee0edef8571d3ed82848303b142c7ae72e7135fc/.github/workflows/deploy-gcp-tests.yml#L1329

Maybe we got a failed instance or outdated instance delete script wrong somewhere?
We could try using `name={{key}}` for failed job deletes, but it might not be causing this problem.

Let's check the Google Cloud logs to work out what is deleting these instances.

**Comment by teor2345** [comment]
Failed in PR #5541, halfway through the test run:
https://github.com/ZcashFoundation/zebra/actions/runs/3390759314/jobs/5636067584#step:6:106

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5366?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345

**Comment by teor2345** [comment]
@gustavovalverde did this get fixed by the recent changes?

**Comment by teor2345** [comment]
We haven't seen this bug for a while.

**Comment by teor2345** [comment]
I haven't seen these in ages?
