### ISSUE TITLE
Do contextual validation on mempool transactions using the state best tip

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5376]
## Motivation

The `getblocktemplate` RPC collects the transactions in the mempool into a block.
That block must be contextually valid based on the best tip in the state.

Edit: This means that each transaction in the mempool must be valid based on the best tip, not any tip.

We'll want a new state request for this.

### Design

Contextual validation:
https://github.com/ZcashFoundation/zebra/blob/afb8b3d4775d89b3f9223447341bf6ce152f5c3a/book/src/dev/rfcs/0002-parallel-verification.md

State design details:
https://github.com/ZcashFoundation/zebra/blob/afb8b3d4775d89b3f9223447341bf6ce152f5c3a/book/src/dev/rfcs/0005-state-updates.md

**Comment by teor2345** [comment]
@mpguerra this is part of the getblocktemplate work I was talking about on Slack.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5376?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Here is some of the code we will need to change:

In the mempool, this code is already using the best chain, but that isn't documented anywhere.

Needs a comment update:
https://github.com/ZcashFoundation/zebra/blob/6446e0ec1bd42d46c115a1dc41fa78955f4aed30/zebrad/src/components/mempool/downloads.rs#L445-L450

https://github.com/ZcashFoundation/zebra/blob/6446e0ec1bd42d46c115a1dc41fa78955f4aed30/zebrad/src/components/mempool/downloads.rs#L279

**Comment by teor2345** [comment]
In PR #5616, we made the transaction verifier use the best chain for UTXOs. This is the only place that the transaction verifier uses the state.

No changes needed here:
https://github.com/ZcashFoundation/zebra/blob/6446e0ec1bd42d46c115a1dc41fa78955f4aed30/zebra-consensus/src/transaction.rs#L488-L497

**Comment by teor2345** [comment]
The mempool transaction verifier doesn't check:
- sprout, sapling, and orchard anchors are valid in the best chain
    - https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/check/anchors.rs
- sprout, sapling, and orchard nullifiers are not revealed in the best chain
    - https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/check/nullifier.rs
    - we'll need to create a `check_*` method for non-finalized nullifiers, currently we try to add them to the non-finalized state, and return an error if that fails

These missing checks are a bug in Zebra's mempool implementation, so we can do them all the time, even if the `getblocktemplate-rpcs` feature is off.

**Comment by teor2345** [comment]
If a transaction is already in the mempool, Zebra currently:
- removes committed transaction IDs, spent outputs, and revealed nullifiers from the best chain
- removes expired transactions at the new height

Anchors remain valid when the chain is extended, so that check doesn't need to be done for each new block.

So we don't need to change anything that happens when a transaction is already in the mempool.

**Comment by arya2** [comment]
We might need to add a check for spend conflicts in the mempool too. 

There are checks for:
- spend conflicts within the transaction
- a transaction with the same hash in the mempool (in `storage.should_download_or_verify`)
- a transaction with the same hash in the state (in `download_if_needed_and_verify`)

but I don't see it checking for spend conflicts against verified transactions in the mempool storage.

**Comment by teor2345** [comment]
> but I don't see it checking for spend conflicts against verified transactions in the mempool storage.

That happens just before the transaction is inserted into the mempool:
https://github.com/ZcashFoundation/zebra/blob/c7745415b6da487db0c081f01a0183975c6de406/zebrad/src/components/mempool/storage/verified_set.rs#L116-L118
