### ISSUE TITLE
Refactor QueuedBlocks and SentHashes fields on StateService to avoid unnecessary utxo removals and re-additions

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5385]
## Motivation

In PR https://github.com/ZcashFoundation/zebra/pull/5257 `known_utxos` of queued blocks were added to the sent hashes when blocks are dequeued and sent to the block write task. Removing the UTXOs from `QueuedBlocks` and re-adding them to `SentHashes` can be easily avoided by coupling QueuedBlocks and SentHashes together.

See https://github.com/ZcashFoundation/zebra/pull/5339

**Comment by teor2345** [comment]
Thanks for opening this ticket!

I'm going to mark it as "not scheduled", because we're not doing changes this large while the audit is pending.

Feel free to re-open it if it's needed for other work, or after the audit fixes are complete.
