### ISSUE TITLE
Use BestChainUtxo rather than AwaitUtxo in the mempool transaction validator

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5386]
## Motivation

The `getblocktemplate` RPC collects the transactions in the mempool into a block.
That block must be contextually valid based on the best tip in the state.

We can't use `AwaitUtxo` for validating mempool transactions, because it gets UTXOs from any chain or any queue.

### Design

Use `BestChainUtxo` rather than `AwaitUtxo` to verify mempool transactions.
(Block transactions should still use `AwaitUtxo`.)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5386?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn
