### ISSUE TITLE
Add an Abscissa command for DNS seeder information.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#54]
Our MVP to test our new networking design is a daemon that can power a DNS seeder; this is a trivial application but it is measurable and concrete and tests that the networking design does actually work in a visible way, before we complete the rest of the work of the node implementation.

Currently the only command we have is the `connect` command, which exists solely for debugging during development and is intended to be thrown away.

To run the daemon we need to have a different command.  This could either be called `run` (the future command to start a full node should certainly be `run`), or something else to indicate that the command only does address spidering and that the rest of the node functionality is not yet implemented.  Thoughts?

**Comment by hdevalence** [comment]
(Tagged `later` because this depends on at least #53 #52 #51 #50 #49 #48 #47 #46 #45 #26 #18 and probably others)

**Comment by dconnolly** [comment]
Call network.init(), handle `GetPeers` requests, and keep updating our `AddressBook` of our crawled data.

**Comment by hdevalence** [comment]
As part of this, we can probably remove the `connect` stub, since it won't be needed any more.

**Comment by dconnolly** [comment]
> As part of this, we can probably remove the `connect` stub, since it won't be needed any more.

I've been modifying the `connect` command frequently in local testing so not removing as part of completion of this issue yet.

**Comment by dconnolly** [comment]
Resolved by #54
