### ISSUE TITLE
Add a CI workflow for `getblocktemplate-rpcs` feature

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5405]
After https://github.com/ZcashFoundation/zebra/pull/5357 gets merged we want to add a workflow into the CI so we can:

- [ ] Build the code inside that feature
- [ ] Run the test code behind this feature

To do this, we'll need to:
- [ ] Add a `getblocktemplate-rpcs` feature to `zebrad` that activates the `zebra-rpc` feature

**Comment by teor2345** [comment]
@mpguerra this ticket was split out of #5305, can we schedule it in this sprint?

**Comment by mpguerra** [comment]
> @mpguerra this ticket was split out of #5305, can we schedule it in this sprint?

Sure, it will need an estimate though :)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5405?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn
