### ISSUE TITLE
Add the Rust compiler version to the bug report metadata

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5422]
## Motivation

Bugs like #5091 only happen on some Rust compiler versions, so it would be useful to have the compiler version in the startup and bug report metadata.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5422?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn
