### ISSUE TITLE
Move the send transactions test to the main branch

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5426]
## Motivation

The send transactions test is very slow and copies a lot of data.

We want to fix this test in #5015. But until then, we want to move it to the `main` branch.

If we move it to the `main` branch, we'll have a better chance of catching any changes that break this RPC.

### Designs

Move the workflow to `main` like we did in PR #5393.

## Rejected Alternatives

If we turn this test off, we need to either:
- test it manually before every release, or
- accept the risk that it might be broken in a release.

We're not planning on making any changes to this RPC, but we are working on some related RPC and mempool code that it calls.

Move the job definition into a separate workflow file, and turn off that workflow in GitHub Actions.

**Comment by teor2345** [comment]
@mpguerra this is the slow test we talked about this morning

**Comment by mpguerra** [comment]
Let's move to main for now and see how it goes

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5426?planning-poker) with Zenhub @arya2 @conradoplg @oxarbitrage @teor2345 @upbqdn
