### ISSUE TITLE
Audit: remove zebra-chain cryptographic implementations that are unused

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5446]
## Motivation

We want to remove unused full-node or full-wallet cryptographic code in zebra-chain, because it has known bugs. We don't want to spend audit time reviewing it or fixing it at the moment.

We can add it back in later if we need to.

Split out of #5214.

**Comment by teor2345** [comment]
@mpguerra this is an extra part of the audit work that we decided at the foundation sync this week.

It would probably block the next release.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5446?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
