### ISSUE TITLE
Introduce `getblocktemplate` RPC method

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5451]
Tasks:

- [ ] Add a `getblocktemplate` RPC method behind the `getblocktemplate-rpcs` rust feature.
- [ ] The method should have no arguments.
- [ ] Create the response structure `GetBlockTemplate` with fields: https://github.com/ZcashFoundation/zebra/issues/5235#issuecomment-1285174731
- [ ] Always return an empty `GetBlockTemplate`
- [ ] Test the rpc method is callable and returns a `GetBlockTemplate` type.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5451?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
