### ISSUE TITLE
Populate `Blocktemplate` responses with fixed values data

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5452]
## Motivation

Several `BlockTemplate`  fields introduced in https://github.com/ZcashFoundation/zebra/issues/5451 are fixed values. 

## Tasks

- [ ] Add fixed values to the response of the `getblocktemplate` RPC call. These values should use the relevant Zebra constants, or create a new constant.
  - `version`: `4` - existing block version number constant from block parser
  - `mutable`: `["time", "transactions", "prevblock"]` - new constant list of strings
  - `noncerange`: `00000000ffffffff` - new min and max nonce constants, set to `u32::MIN` and `u32::MAX`
  - `sigoplimit`: `20000` - existing sigops limit constant from consensus rule check
  - `sizelimit`: `2000000` - existing block byte limit constant from block parser
- [ ] Update the test created at 1- so it can also test for fixed values in the responses.

Depends on https://github.com/ZcashFoundation/zebra/issues/5451

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5452?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
