### ISSUE TITLE
Populate transactions of `BlockTemplate`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5454]
## Motivation

The `transactions` field of the `BlockTemplate`  response is an array of `BlockTemplateTx` structure with the transaction data and other fields.

## Tasks

- Create `BlockTemplateTx`
- bring transactions from the mempool and populate the `transactions.data` fields. https://github.com/ZcashFoundation/zebra/issues/5235#issuecomment-1285189453
  - the `depends` field is always an empty list, Zebra's mempool doesn't support dependent transactions
- Populate the additional fields of `BlockTemplateTx`

Depends on https://github.com/ZcashFoundation/zebra/issues/5451

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5454?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I split ZIP-317 transaction selection out of this ticket into #5473.

It seems like separate work, and it depends on some details that the `zcashd` developers haven't decided yet.
