### ISSUE TITLE
Populate `BlockTemplate` fields using a new state request

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5455]
## Motivation

Whatever is not fixed values(https://github.com/ZcashFoundation/zebra/issues/5452), coinbase transaction(https://github.com/ZcashFoundation/zebra/issues/5453) or mempool transaction(https://github.com/ZcashFoundation/zebra/issues/5454) will be state or Rust API values.

## Tasks

Return state values in the `getblocktemplate` RPC method response:
* `previousblockhash`
* `height`
* `defaultroots`
  * `chainhistoryroot`
* `target` (same as `bits`, but in a different format)
* `mintime`

These values should come from a new state request based on recent best blocks. We want to use a single state request for performance.

Return local node clock value in the `getblocktemplate` RPC method response:
* `curtime` - using the same standard library time function as the `time` field consensus rule check

## Related Tickets

Depend on https://github.com/ZcashFoundation/zebra/issues/5451
Can depend on https://github.com/ZcashFoundation/zebra/issues/5452 for identification

**Comment by teor2345** [comment]
@oxarbitrage I think the fields we need here are:

New state request based on recent best blocks:
* `previousblockhash`
* `height`
* `defaultroots`
  * `chainhistoryroot`
* `target` (same as `bits`, but in a different format)
* `mintime`

Standard library time function:
* `curtime`

Can I edit the ticket, or did you want to?

**Comment by oxarbitrage** [comment]
Please feel free to edit any of the getblocktemplate tickets. I did some some work already in the [first one](https://github.com/ZcashFoundation/zebra/issues/5451) but none in the rest of them.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5455?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
PR #5659 populates all of these fields except `defaultroots.chainhistoryroot` (and the 5 fields that are copies of it).

@mpguerra @oxarbitrage did you want to split that out into a separate ticket?

**Comment by mpguerra** [comment]
I think @oxarbitrage is working on them in a separate PR so I think it's ok to just keep it in this ticket.
