### ISSUE TITLE
Add a miner transparent address config option

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5456]
## Tasks

Shielded coinbase is out of scope, most miners don't use it.
 
- [ ] Add a config containing the miner transparent address to `zebrad.toml`, probably in a new `[mining]` section.
- [ ] Hide the whole mining section in the `getblocktemplate-rpcs` feature if this is possible?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5456?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
