### ISSUE TITLE
Return an error from getblocktemplate if Zebra isn't synced to the tip

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5466]
## Motivation

`s-nomp` uses `getblocktemplate` to check if the node is synced to the tip:
https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L140

### Designs

- Use a `SyncStatus` to check that Zebra has finished syncing
- Allow the same clock skew as the Zcash network, which is 100 blocks, based on the standard rule:

> a full validator MUST NOT accept blocks with nTime more than two hours in the future according to its clock. This is not strictly a consensus rule because it is nondeterministic, and clock time varies between nodes.

https://zips.z.cash/protocol/protocol.pdf#blockheader

Completed work:
<details>

Get the chain tip and the estimated height, and see if they are close enough.
Here is some existing RPC code that gets those fields:
https://github.com/ZcashFoundation/zebra/blob/a2dba8cc5dd482531883ea982398cf0e36c6fcdd/zebra-rpc/src/methods.rs#L370-L397

</details>

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5466?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
PR #5263 was only a partial fix, we still need to:
- check if Zebra has finished syncing blocks
- allow the same clock skew as the Zcash network, which is 100 blocks, based on the standard rule:

> a full validator MUST NOT accept blocks with nTime more than two hours in the future according to its clock. This is not strictly a consensus rule because it is nondeterministic, and clock time varies between nodes.

https://zips.z.cash/protocol/protocol.pdf#blockheader

**Comment by teor2345** [comment]
@mpguerra @arya2 feel free to split out the extra work into a new ticket, if that's easier for you to track!

**Comment by mpguerra** [comment]
I've created #5675 and added it to next sprint (sprint 24) instead
