### ISSUE TITLE
Add basic support for `getmininginfo` RPC call

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5468]
## Motivation

We want to support the RPCs used by mining pools.

https://zcash.github.io/rpc/getmininginfo.html

## Tasks

`s-nomp` uses the `networkhashps` field for statistics:
- https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L452

This might need a new state request to calculate the network hash rate from recent blocks.

Other mining pools have told us they use the `chain` field to detect mainnet or testnet.

We can skip the other fields for now.

## Related Work

We should probably do this at the same time as:
- #5721

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5468?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345

**Comment by teor2345** [comment]
I'd like to know what fields we're implementing first, before I estimate this RPC.

**Comment by mpguerra** [comment]
> I'd like to know what fields we're implementing first, before I estimate this RPC.

Looking at this again I've decided to remove from the sprint until I can do some more research on it. FWIW I think we'd start with just the fields that we know are used by mining pools, e.g the network hash rate

**Comment by teor2345** [comment]
@mpguerra I've updated the ticket with the two fields we know are currently used by mining pools

**Comment by mpguerra** [comment]
> @mpguerra I've updated the ticket with the two fields we know are currently used by mining pools

Are you able to estimate this now based on the above 2 fields?
