### ISSUE TITLE
Select `getblocktemplate` transactions according to ZIP-317

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5473]
## Motivation

We want to select transactions based on ZIP-317.

### Specifications

The block production parts of:
- https://zips.z.cash/zip-0317#block-production
- https://hackmd.io/rgb38M_wSxa9kotyaON1fA (or any actual ZIP updates)

The outdated ZIP-313 might also have some relevant information:
https://zips.z.cash/zip-0313

### Design

When selecting transactions, we should do something similar to `zcashd`, based on ZIPs 317 and 313.

The ZIP editors have recommended including low-fee transactions in blocks with probability `fee / conventional_fee`. Zebra could implement this in the mempool, but that changes relaying as well, which we don't want to do yet. So using the RPC is best for now. The details are in https://hackmd.io/rgb38M_wSxa9kotyaON1fA

We should also check the `sigop_limit` before adding each new transaction to the block.

## Related Tickets

Other parts of transaction selection will be handled by the mempool changes in #5335.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5473?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345
