### ISSUE TITLE
Return detailed errors from the `submitblock` RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5487]
## Motivation

If we find a mining pool that relies on detailed `submitblock` RPC errors, we should implement them.

Otherwise this ticket is optional.

This depends on #2908, because it changes the errors in the state.

### Mining Pool Usage

`s-nomp` calls `submitblock` from this code:
- https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L245

## Requirements

https://zcash.github.io/rpc/submitblock.html

https://en.bitcoin.it/wiki/BIP_0023

The goals of the `submitblock` RPC are to:
- get valid blocks onto the local and network chains as quickly as possible, so miners have the best chance of profiting from their work, and
- reject invalid blocks as quickly as possible, so miners can start on an updated block template.

## Possible Design

Return null if the block is accepted onto the best chain in the non-finalized state. Otherwise, return a detailed error containing the specified text.

See the TODO comments in the `submit_block()` RPC function for details.

#### Error handling

We need to check if miners rely on any specific error values.

Return
 - "duplicate": if Zebra has already committed the block to the non-finalized or finalized state
 - "duplicate-invalid": if Zebra already has the block, but it is invalid
    - Zebra will never return this status, because it does not store invalid blocks
 - "duplicate-inconclusive": if Zebra already has the block in the state queue or channel, but has not committed it to the non-finalized state yet. Checking this might not be supported by Zebra's current architecture.
 - "inconclusive": if Zebra has committed the block to the non-finalized state, but it is not on the best chain
 - "rejected": if Zebra rejected the block as invalid
 - Other possible errors listed here, if needed by mining pools: https://github.com/bitcoin/bips/blob/master/bip-0022.mediawiki#appendix-example-rejection-reasons

`zcashd` implementation:

https://github.com/zcash/zcash/blob/6c392dbb0b43d6988283e40ce423242833df2d30/src/rpc/mining.cpp#L869-L905

## Testing

- [ ] Snapshot the output of the RPC
- [ ] Test calling the RPC from the mining pool software
- [ ] Manually compare the `zcashd` and `zebrad` RPC output using https://github.com/ZcashFoundation/zebra/blob/main/zebra-utils/zcash-rpc-diff

We might also want to implement #5015 to make writing tests for this issue quicker.

**Comment by arya2** [comment]
This might optionally include the check from issue #5466 to be added under `#[cfg(not(test))]`

**Comment by teor2345** [comment]
One mining pool has told us that they don't need detailed errors.

**Comment by teor2345** [comment]
We haven't had any user requests for this, and our own tests work fine without it.

We also partially implemented detailed logging it in a much earlier PR.
