### ISSUE TITLE
Enable `arti-client` when it upgrades its dependency `x25519-dalek`

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#5492]
## Motivation

Zebra's dependency `arti-client v0.0.2` depends on `x25519-dalek v2`, which depends on an old version of `zeroize` that conflicts with other crates' dependencies. For this reason, we've temporarily disabled `arti-client` in #5481.

### Solution

Enable and upgrade `arti-client` when it uses a new version of `x25519-dalek`, which doesn't depend on an old version of `zeroize`.

**Comment by mpguerra** [comment]
I think we can do this one soon

**Comment by oxarbitrage** [comment]
I am closing this in favor of https://github.com/ZcashFoundation/zebra/issues/5492 because the issue with dalek is fixed in arti since a while. But there are other issues as described in https://github.com/ZcashFoundation/zebra/issues/8328#issuecomment-1969989648
