### ISSUE TITLE
gcloud ssh: Connection reset by peer

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5494]
## Motivation

This error happens occasionally:
>  ERROR: (gcloud.compute.ssh) There was a problem refreshing your current auth tokens: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

https://github.com/ZcashFoundation/zebra/actions/runs/3341437225/jobs/5533308842#step:6:84

>  kex_exchange_identification: read: Connection reset by peer

https://github.com/ZcashFoundation/zebra/actions/runs/3352929291/jobs/5555664923#step:6:108

**Comment by gustavovalverde** [comment]
I reopened https://github.com/ZcashFoundation/zebra/pull/5069, I'll let you decide which ticket to use.

> I'm not sure if reopening tickets is a thing in our workflow

**Comment by teor2345** [comment]
> I reopened #5069, I'll let you decide which ticket to use.

I think the errors are different?
(They might have the same cause, I guess we'll find out when we fix one of them.)

> > I'm not sure if reopening tickets is a thing in our workflow

It works for me, but that's really a question for Pili.

**Comment by teor2345** [comment]
> kex_exchange_identification: read: Connection reset by peer

On a launch step in PR #5521:
https://github.com/ZcashFoundation/zebra/actions/runs/3373347892/jobs/5597848235#step:7:108

**Comment by teor2345** [comment]
From PR #5508:
> Writing 3 keys to /home/runner/.ssh/google_compute_known_hosts
> Updating project ssh metadata...
> ..................................................................Updated [https://www.googleapis.com/compute/v1/projects/zealous-zebra].
> .done.
> Waiting for SSH key to propagate.
> kex_exchange_identification: read: Connection reset by peer

https://github.com/ZcashFoundation/zebra/actions/runs/3381967679/jobs/5617006676

But this was an interim logging step that didn't run too long, so the test still passed.

**Comment by teor2345** [comment]
> kex_exchange_identification: read: Connection reset by peer

On PR #5550 halfway through a test run:
https://github.com/ZcashFoundation/zebra/actions/runs/3391346405/jobs/5665340226#step:6:110

**Comment by teor2345** [comment]
Same error on the main branch:
https://github.com/ZcashFoundation/zebra/actions/runs/3412654251/jobs/5679413392#step:6:106

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5494?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345
