### ISSUE TITLE
Ignore the `jsonrequestobject` argument to the `getblocktemplate` RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5495]
## Motivation

Our stub `getblocktemplate` RPC will fail if it gets any arguments.

But we want to ignore the optional `jsonrequestobject` argument instead, because we're not going to support any optional features requested by clients.

### Specifications

https://zcash.github.io/rpc/getblocktemplate.html

### Designs

Accept an Option<String> argument and ignore it.

## Related Work

If we discover that clients need optional features, we can parse the argument and implement them later.

**Comment by arya2** [comment]
> Accept an `Option<String>` argument and ignore it? Does that work?

~It seemed to cause `ParseError`s for the JsonParameterObject in submitblock when that was called with only one parameter.~

Update: I was wrong, `jsonrpc` handles `Option<T>` params as expected, so the design in this ticket would work.

**Comment by teor2345** [comment]
> > Accept an `Option<String>` argument and ignore it? Does that work?
> 
> It seemed to cause `ParseError`s for the JsonParameterObject in submitblock when that was called with only one parameter.

I'm not exactly sure how the `jsonrpc` library argument processing works, but unlike `submitblock`, `getblocktemplate` doesn't need any arguments at all.

**Comment by arya2** [comment]
It's the same problem in `submitblock` where it needs to accept and ignore an optional argument. 

This works:

```
/// Routes request to `get_block_template` method
#[rpc(name = "getblocktemplate")]
fn get_block_template_with_ignored_json_params(
    &self,
    _json_params: String,
) -> BoxFuture<Result<GetBlockTemplate>> {
    self.get_block_template()
}
```
