### ISSUE TITLE
Migrate to the latest version of Abscissa (0.7 or later)

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5502]
## Motivation

We need to update our command-line argument parsing to bump abscissa_core from 0.5.2 to 0.7.0 or later.

This is also needed to make the output of the `--help` flag and `help` command consistent with that of invalid options or commands, by replacing `gumdrop` with `clap`.

It is also needed to avoid a compilation error that is likely to be added to the Rust 2024 edition:
https://github.com/rust-lang/rust/issues/79813

This error is currently a warning on `nightly`.

### Security

This will fix a low-severity security issue - we don't actually call the vulnerable abscissa 0.5.2 or tracing-subscriber 0.1.6 code, so it's only an issue at startup.

It will also make our dependency tree smaller, which improves compile speed, binary size, and security.

Vulnerability:
https://github.com/advisories/GHSA-wcg3-cvx6-7396
https://github.com/time-rs/time/issues/293

Fix:
https://github.com/chronotope/chrono/issues/602#issuecomment-1242149249

## Steps

[Migration guide](https://github.com/iqlusioninc/abscissa/blob/main/CHANGELOG.md#migration-guide)

1. Upgrade command-line argument parsing
2. Upgrade abscissa
    a. Consider replacing Zebra's custom `tokio` and `metrics` components with the current Abscissa implementations
3. Turn future incompatibility warnings back on, by reverting https://github.com/ZcashFoundation/zebra/pull/6024

## Related Work

- #3372

**Comment by teor2345** [comment]
Thanks!

We're unlikely to do this any time soon, because we've replaced abscissa components with our own custom versions instead.

**Comment by teor2345** [comment]
Abscissa 0.5 is likely to cause Rust compiler errors in the Rust 2024 edition:
https://github.com/rust-lang/rust/issues/79813

So we might want to migrate some time in the next year.

**Comment by teor2345** [comment]
I bumped this up to medium because we can't disable the warning just for abscissa, we have to disable all warnings about any future incompatibility:
https://github.com/ZcashFoundation/zebra/pull/6024

**Comment by teor2345** [comment]
@mpguerra we might want to schedule this work after the audit, because we needed to turn off warnings about all upcoming Rust changes until we fix this issue. (We couldn't just turn off this specific warning.)

**Comment by teor2345** [comment]
@mpguerra we might want to schedule this work before the first stable release, because it will change how command-line arguments work.

We might be able to emulate the old arguments, or we might not. Even if we could emulate the same argument processing, we might want to do a breaking change and make them more consistent.

**Comment by teor2345** [comment]
It will also help us get rid of some insecure outdated dependencies. (Which we never call, but still appear in our dependency tree.)

Some of those dependencies are listed in #6391

**Comment by mpguerra** [comment]
> @mpguerra we might want to schedule this work after the audit, because we needed to turn off warnings about all upcoming Rust changes until we fix this issue. (We couldn't just turn off this specific warning.)

This is already in the [Zebra Stable Release Epic](https://github.com/zcashfoundation/zebra/issues/6390) which is intended for anything that needs to be completed before we tag a stable release

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5502?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
Since this is quite a large one, let's move it until after the audit
