### ISSUE TITLE
ci: recently created GCP instances sometimes are not found by workflow jobs

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5517]
## Description

From time to time a workflow job fails with the following error message:

`ERROR: (gcloud.compute.ssh) Could not fetch resource:  The resource 'projects/zealous-zebra/zones/us-central1-a/instances/sync-past-checkpoint-5464-merge-dee1b9c' was not found`

## Expected Behavior

We should wait for the instances to be ready before trying any action. Some jobs might need to wait a few seconds/minutes before executing ssh or any other action after an instance has been udpated

**Comment by gustavovalverde** [comment]
Original comment: https://github.com/ZcashFoundation/zebra/pull/5464#issuecomment-1288356582

**Comment by teor2345** [comment]
This seems like it could be a duplicate of #5366, which has some more analysis.

Sometimes the resource is not found halfway through a job, so I'm not sure if waiting will fix this issue.

**Comment by gustavovalverde** [comment]
Closing as duplicate of #5366
