### ISSUE TITLE
ci: logs longer than GitHub's limit do not allow to see the actual error in the console

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5518]
## Motivation

Some error logs might be "hidden" if the logs are too long, needing extra steps for developer to find the actual error. And making it harder to _link_ the errors in issues/PRs

Example: https://github.com/ZcashFoundation/zebra/actions/runs/3332682537/jobs/5548148889

### Designs

We can approach this in two different ways:
- Confirm the actual limits on GitHub Actions, and just show the _end_ of the logs or the amount supported by GHA
- Make Zebra logs on certain tests less verbose

**Comment by teor2345** [comment]
> * Make Zebra logs on certain tests less verbose

I did this in PR #5521 for the "test all" jobs, but it doesn't fix the full sync logs.

I think maybe we could make the Zebra sync logs less verbose to fix things like:
https://github.com/ZcashFoundation/zebra/actions/runs/3332682537/jobs/5548148889
