### ISSUE TITLE
Add submitblock test to CI

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5527]
## Motivation

The acceptance test for submit block in #5526 uses the cached zebra state and is ignored in the regular coverage CI.

Add a CI job like the one for the send transaction test for the submit block RPC method.

**Comment by arya2** [comment]
I'll try updating the acceptance test first and re-open this if it's still needed.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5527?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345
