### ISSUE TITLE
RPC test crashes: signal: 10, SIGBUS: access to undefined memory

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5532]
## Motivation

Sometimes, the `getblocktemplate-rpcs` tests fail on macOS with:

> Error: test failed, to rerun pass '-p zebra-rpc --lib'
> Caused by:
>   process didn't exit successfully: `/Users/runner/work/zebra/zebra/target/debug/deps/zebra_rpc-26172f8bc86700d4` (signal: 10, SIGBUS: access to undefined memory)
> Error: The process '/Users/runner/.cargo/bin/cargo' failed with exit code 101

https://github.com/ZcashFoundation/zebra/actions/runs/3373347872/jobs/5597821936#step:15:3496

Or on Linux with:
> process didn't exit successfully: `/home/dev/zebra/target/debug/deps/zebra_rpc-b9c86c8bb96626fd --quiet` (signal: 11, SIGSEGV: invalid memory reference)

(On my local machine.)

This could be a security issue.

### Diagnosis

Since this only happens using `getblocktemplate-rpcs`, it could be:
- an issue with the new code added by `--feature getblocktemplate-rpcs`

We could try implementing RPC server shutdown correctly:
https://github.com/ZcashFoundation/zebra/blob/c5e6adc87af53852d733e815cf2750cdf7743f64/zebra-rpc/src/server.rs#L114-L117

Or multiple RPC delegate support could be buggy:
https://github.com/ZcashFoundation/zebra/blob/c5e6adc87af53852d733e815cf2750cdf7743f64/zebra-rpc/src/server.rs#L83

**Comment by teor2345** [comment]
@mpguerra I've just seen this issue on Linux, which makes it a high-priority security issue. So I'm going to push a PR that shuts down the RPC server correctly.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate to this issue? Since you've already done the PR I don't think we need this to go through planning poker
