### ISSUE TITLE
Add a workflow to push our main README.md to Docker Hub

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5542]
## Motivation

Our Docker Hub is missing the actual documentation used in the Zebra repository. We should automate this so we don't have to manually sync both versions

https://hub.docker.com/r/zfnd/zebra

### Designs

- Docker Hub has 2 versions of the README.md, an overview and a detailed one. We should verify if we're going to need both versions.

## Related Work

#5504

**Comment by teor2345** [comment]
The workflow we added failed with an error.

**Comment by teor2345** [comment]
Adding the password as a secret worked:
https://github.com/ZcashFoundation/zebra/actions/runs/3633668844
