### ISSUE TITLE
Tag Google Cloud instances with the name of the test or workflow for debugging

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5543]
## Motivation

We once thought on doing this for costs, but it's also a good idea for filtering logs, as GCP logs are not too friendly when using the instance name or container name, and tags are part of the filtering rules

### Designs

- Tag the instances generated by tests with the following information:
 - Test being run
 - Branch Name
 - short-SHA

## Related Work

#5153

**Comment by teor2345** [comment]
Feel free to re-open old tickets if you'd like 🙂

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5543?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345
