### ISSUE TITLE
Fix test compilation and lint failures with Rust 1.65.0

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5547]
## Motivation

Zebra tests are failing with the Rust 1.65.0 release due to compilation errors:

https://github.com/ZcashFoundation/zebra/actions/runs/3387720824/jobs/5628827965#step:15:17284
<details>

> error: linking with `cc` failed: exit status: 1
> Error:   |
>   = note: "cc" "-m64" "/tmp/rustcBSeDle/symbols.o" "/tmp/rustdoctest3oeRg5/rust_out.rust_out.0b343d98-cgu.0.rcgu.o" "/tmp/rustdoctest3oeRg5/rust_out.471l5hwfdd61rvgf.rcgu.o" "-Wl,--as-needed" "-L" "/home/runner/work/zebra/zebra/target/debug/deps" "-L" "/home/runner/work/zebra/zebra/target/debug/deps" "-L" "/home/runner/work/zebra/zebra/target/debug/build/cxx-79a04422bdc932ed/out" "-L" "/home/runner/work/zebra/zebra/target/debug/build/libgit2-sys-dc2d8e534aa10880/out/build" "-L" "/home/runner/work/zebra/zebra/target/debug/build/librocksdb-sys-bc30ccf58b88f489/out" "-L" "/home/runner/work/zebra/zebra/target/debug/build/link-cplusplus-11343166a431a999/out" "-L" "/home/runner/work/zebra/zebra/target/debug/build/ring-1efd227b1ba0ef85/out" "-L" "/home/runner/work/zebra/zebra/target/debug/build/secp256k1-sys-fbf0283a6d94ce6a/out" "-L" "/home/runner/work/zebra/zebra/target/debug/build/zcash_script-7ffafdef64afbb09/out" "-L" 
> ....
> "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-01209bdfe9867748.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-5dba08c0e996feed.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-fcd555fdecc4f69e.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-63179a22dd24cae2.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1ced5827449ff915.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-430d8655a2cd2488.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-e60518d2760eb01e.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1ad943f92a4b1081.rlib" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-cce2c773caa14f2f.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lstdc++" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/runner/.rustup/toolchains/beta-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/rustdoctest3oeRg5/rust_out" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs"
>   = note: collect2: error: ld returned 1 exit status

</details>

There also seem to be issues related to changes in the Clippy lint:

```
error: the Err-variant returned from this function is very large
--> zebrad/src/components/sync.rs:1027:10
|
1027 | ) -> Result<(), BlockDownloadVerifyError> {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the Err-variant is at least 144 bytes
```

https://github.com/ZcashFoundation/zebra/actions/runs/3387578258/jobs/5628508335#step:8:501

**Comment by teor2345** [comment]
I can fix this now, shouldn't be too hard.
