### ISSUE TITLE
Use larger runners for coverage tests

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5551]
## Motivation

Larger runners for Github actions are currently in public beta for team plans. (https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners)

This may allow us to merge some additional tests for zebra-state (https://github.com/ZcashFoundation/zebra/pull/5377) and make our coverage tests run more quickly.

**Comment by teor2345** [comment]
Duplicate of #7180, which was closed as "not planned".
