### ISSUE TITLE
Make error handling in syncer consistent

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#557]
Right now in `sync.rs` we have some error handling logic for handling invalid responses or propagating back errors from spawned tasks but overall the logic is inconsistent / incomplete. The things left to do still are:

- [x] save `JoinHandle`s for outer spawned futures from `request_blocks` in a `FuturesUnordered` owned by `Syncer` and check background futures for errors periodically in `run`
- [x] turn incorrect responses from block requests into a hard error rather than a log msg
- [x] pass downloaded by spawned tasks back to the syncer to reissue and track the verifications directly

---

I think this should be an error on par with a failure of the request. If we're erroring out on request failures, we should also error out on wrong answers.  Either way we can't advance.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/540_

**Comment by hdevalence** [comment]
One thing I'm wondering about is whether we should use the current approach of spawning tasks for block download, then spawning subtasks for verification (nested spawning) versus spawning tasks for download, handing blocks back to the syncer, and then having the syncer spawn tasks for verification.  In the latter case we wouldn't need to propagate errors out of two levels of tasks or handle the fanout, and if we kept the running tasks in FuturesUnordereds, we could use the number of running tasks to exert backpressure on the downloader.

**Comment by yaahc** [comment]
Partially resolved by https://github.com/ZcashFoundation/zebra/pull/707

**Comment by yaahc** [comment]
I think this issue has effectively been resolved or is otherwise tracked by other issues.
