### ISSUE TITLE
GitHub runners fail with linker error: "collect2: error: ld returned 1 exit status"

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5570]
## Motivation

Sometimes our GitHub actions tests fail with:

> Running `rustdoc --edition=2021 --crate-type lib --crate-name zebrad
> ...
>   = note: collect2: error: ld returned 1 exit status
> ...
> src/components/mempool/crawler.rs - components::mempool::crawler (line 16)

https://github.com/ZcashFoundation/zebra/actions/runs/3411951675/jobs/5676818960

This happened in the `Test beta on ubuntu-latest --features getblocktemplate-rpcs` job in PR #5565.

### Diagnostics

This usually seems to happen on beta Rust with `--features getblocktemplate-rpcs`, and only on GitHub Actions runners.

It could be a full disk, or a Rust build bug caused by rebuilding with extra features. It might also be a bug in Zebra's feature settings in `Cargo.toml`s.

The linker failure does not have a specific error message, we need to collect more logs to diagnose it.

## Related Work

This might be fixed by #5551.

**Comment by teor2345** [comment]
When I re-ran the job, PR #5565 failed with exactly the same error in the same place:
https://github.com/ZcashFoundation/zebra/actions/runs/3411951675/jobs/5680965534#step:14:9034

I'll try cherry-picking PR #5575 to see if that fixes it.

**Comment by teor2345** [comment]
> I'll try cherry-picking PR #5575 to see if that fixes it.

It makes it worse!

We might want to split the GitHub Actions caches with and without the feature.

**Comment by teor2345** [comment]
Still happening with PR #5565 after upgrading to regex 1.7.0 and Unicode 15, but possibly only with beta Rust.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5570?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345

**Comment by teor2345** [comment]
This was fixed by PR #5565.
