### ISSUE TITLE
ci: use self-hosted runners for CI pipelines

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5572]
## Motivation

Some of our tests, mainly our full sync test, are way above [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) limits, being the 6 hours timeout the main limitation. 

We might want to start testing GitHub [self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) to raise the limits.

### Designs

- Deploy a Self-hosted runner to GCP using terraform
- Confirm how the cached state is handled with a self-hosted runner (SHR) 
- Validate how SSH connections will be handled in a SHR
- Move the full-sync job to this runner
- Validate time, reliability and cost of hosting the runner

## Related Work

Another approach would be using #5551, if we get through their beta waitlist. But this might won't get rid from the 6 hours limit.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5572?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345

**Comment by teor2345** [comment]
@gustavovalverde @mpguerra can we be more specific with the scope here? What specific changes are we going to try?

It's hard to estimate this ticket without a list of tasks or a list of requirements.

**Comment by arya2** [comment]
Larger runners are still limited to 6 hours, but this may bypass ssh issues if done the hard way.

https://github.com/actions-runner-controller/actions-runner-controller
https://github.com/jonico/awesome-runners

**Comment by dconnolly** [comment]
> @gustavovalverde @mpguerra can we be more specific with the scope here? What specific changes are we going to try?
> 
> It's hard to estimate this ticket without a list of tasks or a list of requirements.

Yeah we might want to scope this first issue as 'try setting up  /a/ self-hosted runner for one simple workflow/action'

**Comment by gustavovalverde** [comment]
I added some steps

**Comment by teor2345** [comment]
Thanks, that looks good!

> * Add other sync jobs to the runner

I think moving all the sync jobs might be out of scope for an initial ticket. There's no particular urgency, they seem to be working ok.

Or did you want this to become a tracking issue?

**Comment by gustavovalverde** [comment]
I removed that one.

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by mpguerra** [comment]
unscheduling for now
