### ISSUE TITLE
Try using rust-log-analyzer bot to post failure logs on PRs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5573]
## Motivation

We spend a bit of time locating errors in our CI logs, and posting them to PRs.

We could use the `rust-log-analyzer` bot to post a comment on a PR when CI fails, like this comment:
https://github.com/rust-lang/rust/pull/104118#issuecomment-1306119356

https://github.com/rust-lang/rust-log-analyzer

### Design Questions

Will this work with GitHub Actions, Google Cloud Docker instances, or both?

## Related Work

We might also want to post `main` branch failures to a developer channel, maybe on Discord?

**Comment by teor2345** [comment]
This is what the bot's posts look like:
<img width="936" alt="Screen Shot 2022-11-08 at 07 59 42" src="https://user-images.githubusercontent.com/8951843/200424497-c9431dc8-cacf-44ea-9976-274eda20bec0.png">

**Comment by dconnolly** [comment]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/552961/200433119-a12f6e2a-b61f-4d93-b084-2793c6a426d1.png">

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5573?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345

**Comment by mpguerra** [comment]
unscheduling for now

**Comment by gustavovalverde** [comment]
We want this, and it would be great to have it, but this require to migrate the actual source code and it won't be scheduled for a while. I'll close as not planned so we can reopen-it after the pipeline overhaul.
