### ISSUE TITLE
ci: notify team members in our chat system if the main branch fails a job

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5574]
## Motivation

When CI is stable we'd like to notify the team if a CI job fails in the `main` branch, so we're notified in a timely manner to fix it as soon as possible

### Designs
- Create a separate workflow for notifications
- We might want to have a global solution which connects to multiple chat systems (Discord, Slack, etc.)

**Comment by teor2345** [comment]
I implemented this for the CI Docker workflow in Slack using the Slack+GitHub integration command:
```
/github subscribe ZcashFoundation/zebra +label:"S-ci-fail-auto-issue"
```

I added the integration for the rest of the workflows to ticket #6864.
