### ISSUE TITLE
Document P2SH multisig address handling for funding stream receivers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5577]
## Motivation

Zebra's consensus rule documentation does not specifically mention P2SH multisig addresses, even though we handle them correctly.

### Specifications

> The standard redeem script hash is specified in [Bitcoin-Multisig] for P2SH multisig addresses...

https://zips.z.cash/protocol/protocol.pdf#fundingstreams
https://developer.bitcoin.org/devguide/transactions.html#multisig

### Designs

- Document multisig handling in `check_script_form()`
- We might want to assert we're getting a P2SH `Address` in `check_script_form()` and the mining config, because `Address` also has other variants

## Related Work

The `Address` variant bug was introduced as part of #5453

**Comment by teor2345** [comment]
I documented why we can skip this consensus rule in PR #5580.

**Comment by str4d** [comment]
> However, the current funding streams do not use multisig addresses

This is false. All of the current and past funding stream addresses are multisig P2SH addresses (the ones I spot-checked are 2-of-3 multisig).

**Comment by teor2345** [comment]
> > However, the current funding streams do not use multisig addresses
> 
> This is false. All of the current and past funding stream addresses are multisig P2SH addresses (the ones I spot-checked are 2-of-3 multisig).

Thanks, I think I misunderstood what was happning here. Zebra's code is correct, but the consensus rule docs are incomplete.
