### ISSUE TITLE
Populate `BlockTemplate.blockcommitmentshash` from the transactions and state request

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5579]
## Motivation

The `blockcommitmentshash` field is calculated from the transactions in #5453 and #5454, and the state request in #5455.

This field's value is repeated in:
    * `lightclientroothash`
    * `finalsaplingroothash`
    * `blockcommitmentshash`
    * `defaultroots.blockcommitmentshash`

### Specifications

https://zips.z.cash/zip-0244#block-header-changes

### Designs

We have code to calculate the block commitments hash in `zebra-chain` already, because we validate it in `zebra-state`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5579?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345
