### ISSUE TITLE
Make the transaction database ignore the genesis coinbase UTXO

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#559]
There is a bug in the main bitcoin client, where the coinbase transactions in the genesis block are not included in the unspent transaction (UTXO) list:
https://bitcointalk.org/index.php?topic=119645.msg1288552#msg1288552

zcashd inherits this bug, with the following differences:
* the coinbase transaction in the genesis block has zero value, so no money was lost

Note that zero-valued UTXOs can still be used as transaction inputs, so this is a consensus-critical issue.

The coinbase transaction is the only transaction in the genesis blocks.

**Comment by daira** [comment]
The only transaction in each of those blocks is the coinbase transaction.

**Comment by teor2345** [comment]
Thanks, I've updated the ticket description.

**Comment by teor2345** [comment]
This bug was recently fixed in the Zcash specification, the correct behavior is specified in the Zebra State RFC, and implemented in Zebra.
