### ISSUE TITLE
ci: snapshot a VM when a workflow job fails

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5592]
## Motivation

Sometimes is hard to diagnose the behavior of a specific VM if we don't have information from the internal VM logs (not exported in GitHub Actions nor GCP logs explorer)

### Designs

This could be a _snapshot_ but we could take other approaches:
- Exporting the logs to GitHub Actions as artifacts (to download and further investigate)
- Have a step to show (cat) the logs of sshd, syslog, etc in the GitHub console

**Comment by teor2345** [comment]
> * Have a step to show (cat) the logs of sshd, syslog, etc in the GitHub console

I think this would be more helpful, but it might rely on getting `ssh` working.

**Comment by gustavovalverde** [comment]
> but it might rely on getting `ssh` working.

Considering multiple steps have failed one after the other. Yes.

**Comment by gustavovalverde** [comment]
I won't be doing this until we refactor deployments, as we might end up not using VMs at all.
