### ISSUE TITLE
Run the send transactions test on each PR update

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5600]
## Motivation

The send transactions test was moved to the main branch in https://github.com/ZcashFoundation/zebra/pull/5480 because it was very slow.

It's much faster (~30m) with https://github.com/ZcashFoundation/zebra/issues/5015 and can be run for every PR update again.

### Designs

Revert the changes in https://github.com/ZcashFoundation/zebra/pull/5480 and remove the `github.event.inputs.run-lwd-send-tx != 'true'` anywhere else it may have been added.

**Comment by teor2345** [comment]
We're not updating this RPC code right now, so this is a low priority.
