### ISSUE TITLE
ci: Use machine images instead of custom images to snapshot cached states

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5615]
## Motivation

We've dealt with multiple issues, from snapshot multiple disks to restore a custom image (not being available). This can also increase in complexity, making custom images a less reliable option in the future

We can also benefit from the use of differential backups and the crash-consistent feature made now available with machine images

### Specifications

https://cloud.google.com/compute/docs/machine-images

### Designs

- Change our cached state backups from custom images to machine images
- Validate if it's better to use differential backups for the `main` branch (if this is a feature flag)

## Related Work

This might fix #5044

**Comment by teor2345** [comment]
Looks good!

This will lock us into always combining the Zebra and lightwalletd caches in the lightwalletd cached stafe. So we should check if that's what we want. (Using custom disks, we could keep the Zebra and lightwalletd states from the same run on separate disks. But we don't do that right now, and it's not really needed.) Either way, we let's document our choice?

There is also a risk that we'll accidentally re-use old test code on the machine image. Let's document how we avoid that happening.

> This might fix #5044

Switching to machine images is unlikely to fix images being un-READY while they are being created. For that, we need to change our image search filters to exclude images that are un-READY.

**Comment by gustavovalverde** [comment]
We're closing it for now, until it is a priority
