### ISSUE TITLE
Test the checkpoint verifier with a longer checkpoint gap

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#563]
In #524, I added an initial implementation of the checkpoint verifier. But it doesn't have many tests yet.

In particular, we should add a test with a sequence of blocks, where the ends of the sequence are checkpoints.

At the moment, the longest checkpoint test is:
* `[0, 1]`.

Ideally, we should have:
* `[0, 2]` verifying blocks `0..=2`
* `[0, 5, 10]` verifying blocks `0..=10`

**Comment by oxarbitrage** [comment]
Why only continuous checkpoints verify ? I think this issue might be blocked.

**Comment by yaahc** [comment]
@oxarbitrage what do you mean?

**Comment by oxarbitrage** [comment]
That the verifier is failing if the checkpoints are not continuous. The code is pretty complex for me so i am maybe not understanding correctly but on my view the checkpoints do not need to be continuous but the blockchain should.

I have some dirty code that you maybe want to check:

https://github.com/ZcashFoundation/zebra/compare/main...oxarbitrage%3Aissue563?expand=1

In the test i have a continuous blockchain and a non continuous range of checkpoints. When you feed the verifier with the blockchain the test fails by timeout.
There are some comments in the code mentioning this is something that need to be fixed: https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs#L830

**Comment by yaahc** [comment]
@oxarbitrage I think you might need to use `tokio::spawn` to spawn the verification futures. Its a batched interface, so each future wont resolve until the checkpoint is satisified, so they should all be pending until you add the 3rd block.

relevant resources:

* https://docs.rs/tokio/0.2.21/tokio/fn.spawn.html
* https://docs.rs/futures/0.3.5/futures/stream/struct.FuturesUnordered.html

You'll want to spawn the futures and then store the handles in a `FuturesUnordered` and once they've all been pushed you'll want do `while let Some(res) = handles.next().await {res??}` or something.

**Comment by teor2345** [comment]
> That the verifier is failing if the checkpoints are not continuous. The code is pretty complex for me so i am maybe not understanding correctly but on my view the checkpoints do not need to be continuous but the blockchain should.

The CheckpointVerifier only verifies continuous chains of blocks in the chain. There must be a checkpoint at height 0. There are no other restrictions on the checkpoint heights.

In `multi_item_checkpoint_list`, we use the same block list for the chain and the checkpoints:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs#L869
So we can't verify block 415000, because we don't have all the lower blocks in the test.

In some tests, we drop the verifier to cancel all the unverified futures:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs#L1185

**Comment by teor2345** [comment]
I'm happy to review a PR, please submit your code when you think it's ready.

**Comment by teor2345** [comment]
(Or when you need help.)

**Comment by oxarbitrage** [comment]
Thanks @teor2345 that is actually my understanding and what i was trying to do at https://github.com/ZcashFoundation/zebra/compare/main...oxarbitrage%3Aissue563?expand=1 (I am not pushing as i dont think that is even close to be ready however if it is better for you to see it i can just submit it).

In the test i am trying i have a vector `allblocks_data` with block0, block1 and block2. Then in `checkpoint_data` i only have block0 and block2. When i try to verify the blockchain by looping i am getting the timeout failure. 

I am unsure if this is related to the `spawn` needed @yaahc suggested. I will check this tomorrow and update, in the meantime any suggestion is welcome.

**Comment by teor2345** [comment]
@yaahc's suggestion is correct: the futures won't resolve until all the blocks are in the verifier queue.

So you can't await the futures until you have created all of them. (Creating the futures queues the blocks.)

Then you should be able to await them in any order.

**Comment by teor2345** [comment]
You might also find `tokio::time::timeout` useful during testing, so that your tests fail when futures don't resolve, rather than hanging:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs#L1104

**Comment by oxarbitrage** [comment]
Nice, thank you both, will try tomorrow and let you know how it goes :)

**Comment by teor2345** [comment]
Closed by #643.
