### ISSUE TITLE
Add an acceptance test for the getblocktemplate method

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5652]
## Motivation

The vector and snapshot tests for the `getblocktemplate` RPC method won't be able to use the non-finalized state to test the contextual validity checks for https://github.com/ZcashFoundation/zebra/pull/5630.

## Designs

- Use `from_script_hash(Mainnet, [0x7e; 20])` as the `miner_address` in the config
- Sync Zebra to the network tip
- Call the getblocktemplate RPC method
- Assert that the call was successful

**Comment by teor2345** [comment]
Re-opening this ticket, because the test PR was reverted due to intermittent CI failures.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5652?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345

**Comment by teor2345** [comment]
So I think this just needs a quick fix to remove an assertion, or fix a bug.

Did you want an estimate for the whole ticket, or just that fix?

**Comment by teor2345** [comment]
Hey @arya2 I think the errors in your PR were from code I wrote, so I'm going to try to fix them.
