### ISSUE TITLE
Check Bitcoin handling of non-negativity in `TransparentOutput`

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#566]
Is there some canonical description of how Bitcoin does this kind of checking? If we do this, we reject negative values during parsing.  Is that fine, if we need exact compatibility with Zcashd? I think it is probably fine but I'm not sure.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/554/files_

**Comment by hdevalence** [comment]
> You'll have to reverse-engineer zcashd to get that information, I'm afraid. Please document it when you do!
— @daira

**Comment by teor2345** [comment]
We looked at this when we looked at the consensus rules - transparent values must be non-negative.
