### ISSUE TITLE
Fix get_block_template test failure in CI

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5669]
## Motivation

The get_block_template test seems to work locally but is failing in CI with:

> Message: negating a NonNegative amount always results in a valid NegativeOrZero: Constraint { value: 43740, range: -2100000000000000..=0 }
> Location: zebra-rpc/src/methods/get_block_template_rpcs/types/transaction.rs:105

https://github.com/ZcashFoundation/zebra/actions/runs/3498079512/jobs/5859110894#step:6:264

<details>

#### Other examples:

>    Message:  negating a NonNegative amount always results in a valid NegativeOrZero: Constraint { value: 15774, range: -2100000000000000..=0 }
>    Location: zebra-rpc/src/methods/get_block_template_rpcs/types/transaction.rs:105

https://github.com/ZcashFoundation/zebra/actions/runs/3496645952/jobs/5857867959#step:6:269

>    Message:  negating a NonNegative amount always results in a valid NegativeOrZero: Constraint { value: 3000, range: -2100000000000000..=0 }
>    Location: zebra-rpc/src/methods/get_block_template_rpcs/types/transaction.rs:105

https://github.com/ZcashFoundation/zebra/actions/runs/3495782850/jobs/5853499468#step:6:267

</details>

This is needed for a branch protection rule.

**Comment by teor2345** [comment]
If the test isn't working, and it is blocking all other PRs from merging, this is a critical-priority ticket.

I suggest we revert the test PR. Then we can change the priority of this ticket to "medium", and submit a new PR with a working test.

**Comment by teor2345** [comment]
Actually, I think it might be easier to re-open the test ticket #5652 instead, and close this ticket when the revert PR merges.
