### ISSUE TITLE
Pin Swatinem/rust-cache to a patch version

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#5676]
## Motivation

We want to pin Swatinem/rust-cache to a specific version, rather than just the current major version it's pinned to.

## Related Work

 See  #5647

**Comment by mpguerra** [comment]
How urgent is this? I'm un-scheduling for now.

**Comment by mpguerra** [comment]
Is this still relevant? I see from #7373 that swatinem/rust-cache is already on v2

**Comment by teor2345** [comment]
Yes it looks like this was fixed a while ago.
