### ISSUE TITLE
Test the getblocktemplate RPC's response as a block template proposal in CI

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5685]
## Motivation

The acceptance test could confirm that the `getblocktemplate` response in 'template' mode will be accepted if it has a valid solution by submitting the same data to the `getblocktemplate` method in 'proposal' mode.

### Design

In the acceptance test that syncs until the tip and calls the `getblocktemplate` RPC method:
- Deserialize the response
- Convert the template into a block with empty `solution` and `nonce` fields
- Hex-encode the resulting block
- Call `getblocktemplate` in 'proposal' mode
- Assert a "null" response indicating successful validation (similar to the `submitblock` test)

**Comment by teor2345** [comment]
> The acceptance test could confirm that the getblocktemplate response in 'template' mode will be accepted if it has a valid solution by submitting the same data to the getblocktemplate method in 'proposal' mode.

I'm not quite sure how this would work, do we need to mine a valid solution for the proposal to be valid?
Could we use `submitblock` in the test, rather than adding an extra unused `proposal` mode to `getblocktemplate`?

**Comment by arya2** [comment]
> I'm not quite sure how this would work, do we need to mine a valid solution for the proposal to be valid? Could we use `submitblock` in the test, rather than adding an extra unused `proposal` mode to `getblocktemplate`?

It doesn't need a valid solution (it doesn't commit the block, just checks that it would be accepted if submitted with a valid solution), so a new block verifier request would skip the `check::equihash_solution_is_valid(&block.header)` [here](https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/block.rs#L166) and use a `CheckContextualValidity` request instead of `CommitBlock`. Then if miners want to modify the template and then check that their modifications are still valid before mining, they could propose the new template.

> The block data MUST be validated and checked against the server's usual acceptance rules (excluding the check for a valid proof-of-work) - https://en.bitcoin.it/wiki/BIP_0023#Block_Proposal

**Comment by teor2345** [comment]
Sounds good, can you update the ticket description with the spec details and your suggested design?

Sometimes they get lost in the comments!

**Comment by mpguerra** [comment]
I don't think we should do this in CI until we can confirm it manually

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5685?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
