### ISSUE TITLE
document our design process 

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#569]
Based on recent meetings we've decided to create a more formal design process for complex designs.

## Issues we hope to solve

* unclear which issues are formal designs and which issues are informal recommendations
* starting to write the code before doing the design, then having to do re-work after learning more.
* knowing the goals of the design- some team members might be working towards different design goals.

**Comment by teor2345** [comment]
I think we solved this issue with the RFC process?

**Comment by yaahc** [comment]
we should probably add a section on how the RFC process works to the book but we've definitely finished figuring out our design process.

**Comment by teor2345** [comment]
> we should probably add a section on how the RFC process works to the book

Would you like to edit this issue, or open a new one?

**Comment by teor2345** [comment]
See #922 for the follow up.
