### ISSUE TITLE
ci: Tests failing with `request should match added_transaction_ids`

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#5706]
## Motivation

This error has happened a few times in PRs and on the main branch, and rerunning fixes it:

```
failures:

---- components::inbound::tests::fake_peer_set::mempool_requests_for_transactions stdout ----

The application panicked (crashed).
Message:  response to `MempoolTransactionIds` request should match added_transaction_ids [Legacy(transaction::Hash("c4eaa58879081de3c24a7b117ed2b28300e7ec4c4c1dff1d3f1268b7857a4ddb"))]
Location: zebrad/src/components/inbound/tests/fake_peer_set.rs:81
```

Full backtrace here: https://github.com/ZcashFoundation/zebra/actions/runs/3531498052/jobs/5924747694#step:3:9534

**Comment by gustavovalverde** [comment]
This also happened in `main` in another test https://github.com/ZcashFoundation/zebra/actions/runs/3524141968/jobs/5909163893#step:14:8717

Maybe this ticket title is not accurate

**Comment by mpguerra** [comment]
This is #5384, let's track there
