### ISSUE TITLE
Improve consistency of usage information printed by zebrad `help` command

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5707]
## Motivation

Print the long-form usage information for the help to match that which is printed with the --help flag

### Designs

- Copy Abscissa's `Help` Cmd into a new command module
- Move the code used to print out usage information for the `--help` flag into a fn of the new module (https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/application/entry_point.rs#L46)
- Call that fn instead of `print_usage_and_exit` from `HelpCmd::run` if no subcommand is provided

**Comment by teor2345** [comment]
This is likely to be obsoleted by the upgrades to `abscissa` 0.7 and `clap` 0.4.
