### ISSUE TITLE
relay (fRelayTxes) field when parse Message::Version from the remote node should be optional

### ISSUE THREAD

**Issue by DeckerSU** [ZcashFoundation/zebra#5713]
## Required Changes

If the `Version` message bytes end at the `start_height` field, Zebra currently returns an `ErrorKind::UnexpectedEof`.
Instead of returning that error for that field, set the `relay` field to `true`.

If the message doesn't include enough bytes for any of the other fields, Zebra should continue to return `ErrorKind::UnexpectedEof`.

## Bug Report

The `relay` field read from the `Message::Version` should be optional as it implemented in `zcashd`:

https://github.com/zcash/zcash/blob/6284f3f8b08aa1f5fcaa27a8a4088fb204364401/src/main.cpp#L6505-L6510

As we are see here:
```cpp
        {
            LOCK(pfrom->cs_filter);
            if (!vRecv.empty())
                vRecv >> pfrom->fRelayTxes; // set to true after we get the first filter* message
            else
                pfrom->fRelayTxes = true;
        }
```
If `fRelayTxes` is not passed in version message we assume it `true`, but in the `zebrad` reading relay from the `Message::Version` is mandatory:

https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/protocol/external/codec.rs#L483

```rust
fn read_version<R: Read>(&self, mut reader: R) -> Result<Message, Error> {
        // Clippy 1.64 is wrong here, this lazy evaluation is necessary, constructors are functions. This is fixed in 1.66.
        #[allow(clippy::unnecessary_lazy_evaluations)]
        Ok(VersionMessage {
            version: Version(reader.read_u32::<LittleEndian>()?),
            // Use from_bits_truncate to discard unknown service bits.
            services: PeerServices::from_bits_truncate(reader.read_u64::<LittleEndian>()?),
            timestamp: Utc
                .timestamp_opt(reader.read_i64::<LittleEndian>()?, 0)
                .single()
                .ok_or_else(|| Error::Parse("version timestamp is out of range for DateTime"))?,
            address_recv: AddrInVersion::zcash_deserialize(&mut reader)?,
            address_from: AddrInVersion::zcash_deserialize(&mut reader)?,
            nonce: Nonce(reader.read_u64::<LittleEndian>()?),
            user_agent: String::zcash_deserialize(&mut reader)?,
            start_height: block::Height(reader.read_u32::<LittleEndian>()?),
            relay: match reader.read_u8()? {
                0 => false,
                1 => true,
                _ => return Err(Error::Parse("non-bool value supplied in relay field")),
            },
        }
        .into())
    }
```
If `relay` was unable to read here bcz it's not passed `read_version` will return with:
```
Err(error::const_io_error!(ErrorKind::UnexpectedEof, "failed to fill whole buffer"))
```
But `zcashd` default behavior is set it to `true`. 

To reproduce all of these we can start instance of `zebrad` and try to connect to it from `zcashd` qa `test_framework`. As the `class msg_version` haven't `relay` (`fRelayTxes`) it doesn't serialize it:

https://github.com/zcash/zcash/blob/master/qa/rpc-tests/test_framework/mininode.py#L1464

So, connection from the Python framework to `zebrad` will looks like this:
```
DEBUG:NodeConn(127.0.0.1:17770):Recv msg_version(nVersion=170011 nServices=1 nTime=Thu Nov 24 02:05:00 2022 addrTo=CAddress(nServices=1 ip=127.0.0.1 port=44424) addrFrom=CAddress(nServices=1 ip=0.0.0.0 port=17770) nNonce=0x3ACF450EA438557A strSubVer=b'/Zebra:1.0.0-beta.13/' nStartingHeight=0)
DEBUG:NodeConn(127.0.0.1:17770):Send msg_verack()
DEBUG:NodeConn(127.0.0.1:17770):MiniNode: Closing Connection to 127.0.0.1:17770...
```
I.e. closed with `HandshakeError::ConnectionClosed` on `zebrad` side. But the `zcashd` behaviour on the same connection with absent `relay` (`fRelayTxes`) in `version` p2p message will be different, connection will remains active, bcz in `zcashd` this param is `optional`.

**Comment by teor2345** [comment]
@mpguerra this bug can stop Zebra connecting to other nodes, it might be the cause of some of our DNS seeder or block explorer issues.

Can we fix it in the next sprint?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5713?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
