### ISSUE TITLE
Implement transparent P2PKH mining address support

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5719]
## Motivation

Some mining pools have told us they use P2PKH transparent addresses for coinbase transactions, but Zebra only currently supports P2SH transparent addresses.

### Specification

```
In a P2PKH output, the pubkey script is:
OP_DUP OP_HASH160 <PubkeyHash> OP_EQUALVERIFY OP_CHECKSIG
```

https://developer.bitcoin.org/devguide/transactions.html#p2pkh-script-validation

In Zebra, `<PubkeyHash>` is implemented as:
```rust
bytes.push(OpCode::Push20Bytes);
bytes.extend(address.hash_bytes());
```

### Designs

- If the configured miner address is a P2PKH address, create the miner payout script using that P2PKH address (the funding streams must stay as P2SH scripts, this is a consensus rule)
    - Also support unified addresses that contain P2SH or P2PKH addresses (this can be a separate PR)
- Remove assertions that miner addresses are P2SH

#### Optional Changes

We might want to move the existing script opcodes to a new module, and add the others we need.
It will be easier to write code with the opcodes if they are `#[repr(u8)]`.

### Existing Code

We already define some of the required script opcodes here:
https://github.com/ZcashFoundation/zebra/blob/ce07f4d7af9eae3fd80c38ff3ecf5adb71b7b1b7/zebra-consensus/src/block/subsidy/funding_streams.rs#L175-L180

**Comment by teor2345** [comment]
@mpguerra can we schedule this in the next sprint?

It's not urgent, but some miners won't be able to use Zebra for mining until we do it.

**Comment by mpguerra** [comment]
Where is this support implemented? is it a value in one of the mining rpc fields?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5719?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> Where is this support implemented? is it a value in one of the mining rpc fields?

It is the address we use to send the miner reward in the coinbase transaction, and the script required to use that address type.

**Comment by mpguerra** [comment]
@oxarbitrage  can you please set an estimate/size here?
