### ISSUE TITLE
Support long polling in the getblocktemplate RPC (excluding mempool changes)

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5720]
## Motivation

Some mining pools need long polling support, where the RPC response is delayed until the block template changes.

### Specifications

https://en.bitcoin.it/wiki/BIP_0022#Optional:_Long_Polling

### Designs

RPC fields:
- [x] Declare `longpoll` support in the `getblocktemplate` RPC `capabilities`
- [x] Provide a `longpollid` field in the RPC response, which represents the contents of the tip and mempool used to create the response.
- [x] Accept a `longpollid` parameter to the RPC request,
    - [x] which activates long polling until the ID changes.

When long polling is requested by the client using a `longpollid` parameter, delay the RPC response until:
- [x] the tip block changes:
    - [x] add a `submitold: false` field, because the old template is invalid, and
    - [x] use a `ChainTipChange` watch channel that is updated by the state;
- [x] any transactions in the mempool change:
    - [x] add a `submitold: true` field, because the old template can still be a valid block, and
    - [ ] use a watch channel that is updated by the mempool, like `ChainTipChange`;
- [x] or the `max_time` is reached (or close?):
    - [x] add a `submitold: false` field, because the old template is invalid.

RPC server:
- [x] Increase the default number of RPC threads when the `getblocktemplate-rpcs` feature is on, because every long polling client could use one thread.
    - [ ] Test the `jsonrpc_core` implementation to see what happens when a RPC request future is held open. (We assume it will do whatever the underlying `tokio` executor does.)

## Testing

I have tested long polling with `zcashd`, and it works with this command:
```sh
 zcash-cli getblocktemplate '{ "longpollid": "0000000000ab159b36911c7860f637a8e5c2d99d17c2a922029ff0905655a30080497" }'
```

**Comment by mpguerra** [comment]
We probably want to do this, however, this seems like a nice and should wait until we have the basic MVP functionality done (Scope section in https://github.com/zcashfoundation/zebra/issues/5234)

**Comment by teor2345** [comment]
> We probably want to do this, however, this seems like a nice and should wait until we have the basic MVP functionality done (Scope section in #5234)

How will we know our MVP implementation actually works, if we don't implement enough functionality for a mining pool to run it?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5720?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is potentially a very large ticket, and it's in this sprint, so I'm going to split the mempool part into another ticket.

**Comment by teor2345** [comment]
> This is potentially a very large ticket, and it's in this sprint, so I'm going to split the mempool part into another ticket.

The specific split I planned didn't end up working out, so I closed that ticket, and I did it in multiple PRs instead.
