### ISSUE TITLE
Implement getnetworksolps and getnetworkhashps RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5721]
## Motivation

Some mining pools use the getnetworkhashps RPC.

### Specifications

These RPCs are identical, just with a different name:
https://zcash.github.io/rpc/getnetworksolps.html
https://zcash.github.io/rpc/getnetworkhashps.html

### Designs

Miners just use the current network hash rate, so we can ignore the arguments and just use the default values.

We should return an error if the arguments aren't the default values.

This will probably need a new state request.

We can implement both RPCs using the same function:
```rust
#[rpc(name = "getnetworksolps", alias("getnetworkhashps"))]
fn get_network_sol_ps(&self, ...) -> Result<...>;
```

**Comment by mpguerra** [comment]
It seems like this RPC call is actually deprecated in favour of `getnetworksolps`. 

Do we still want to do this or do `getnetworksolps` instead? Or should we do both?

**Comment by teor2345** [comment]
> It seems like this RPC call is actually deprecated in favour of `getnetworksolps`.
> 
> Do we still want to do this or do `getnetworksolps` instead? Or should we do both?

Some mining pools still use this RPC. I don't think that mining pools will change the RPCs they use, just so they can use Zebra.

The arguments and returned value are exactly the same for both RPCs. So we can implement both RPCs at the same time using an alias. (I added some details to the ticket.)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5721?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@arya2 can you please set an estimate/size here?
