### ISSUE TITLE
Implement validateaddress RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5722]
## Motivation

Some mining pools use this RPC to check addresses.

### Specifications

https://zcash.github.io/rpc/validateaddress.html

### Designs

We can call the [`zcash_address`](https://docs.rs/zcash_address/latest/zcash_address/) crate to validate shielded and unified addresses. (Zebra also has its own transparent address parsing, but we'd be better to just be consistent and use `zcash_address` for everything.)

We just need to implement these fields:

Transparent:
- p2pkh
- p2sh
- scriptPubKey (optional, only do it if it's easy)
- pubkey (optional, only do it if it's easy)
- isscript

## Related Work

- #5719

**Comment by mpguerra** [comment]
We should implement these, however since they are not strictly mining RPCs they don't fall within the scope of the MVP.

**Comment by teor2345** [comment]
> We should implement these, however since they are not strictly mining RPCs they don't fall within the scope of the MVP.

Some mining pools won't be able to use Zebra until we implement these RPCs.

**Comment by teor2345** [comment]
I added `validateaddress` to this ticket, because some mining pool software needs it. The fields are almost exactly the same as `z_validateaddress`, just with different names.

**Comment by str4d** [comment]
Note that the `type` field is deprecated and will be disabled by default in zcashd 5.4.0. It is being renamed to `address_type`.

**Comment by teor2345** [comment]
> Note that the `type` field is deprecated and will be disabled by default in zcashd 5.4.0. It is being renamed to `address_type`.

Since that change hasn't been released yet, we might use both names until miners update.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5722?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@arya can you please update the estimate here, if necessary, after splitting off the original issue
