### ISSUE TITLE
Implement the getpeerinfo RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5723]
## Motivation

Some mining pools use the getpeerinfo RPC to make sure the mining pool is still connected to peers.

### Specifications

https://zcash.github.io/rpc/getpeerinfo.html

### Designs

- Pass the shared `zebra-network` address book to the RPC server
- Call `address_book.recently_live_peers()` to get the peers that were recently connected
    - The shared address book is protected by a mutex, so we want to clone it to drop the mutex as soon as possible.
    - Doing the mutex lock and clone in a separate function will make sure this happens.
- Turn the list of `MetaAddr`s into a list of peerinfo records

We just need to provide the `addr` field for now, we can add more fields if mining pools ask for them.

**Comment by mpguerra** [comment]
We should implement these, however since they are not strictly mining RPCs they don't fall within the scope of the MVP.

**Comment by teor2345** [comment]
> We should implement these, however since they are not strictly mining RPCs they don't fall within the scope of the MVP.

Some mining pools won't be able to use Zebra until we implement these RPCs.

**Comment by mpguerra** [comment]
@arya2 can we get an estimate here please?
