### ISSUE TITLE
change(ci): Change set-output to environment files by May 2023

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5736]
## Motivation

This message is logged by a lot of our workflows:
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Specifications

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5736?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@gustavovalverde do we want to split this ticket into multiple PRs? Maybe one for each big workflow, and one for the rest?

**Comment by gustavovalverde** [comment]
I think I'd prefer to handle it all-in-one, if it gets tricky (or even 1 workflow fails in the PR after the changes) I might start splitting it.

**Comment by teor2345** [comment]
No worries, just wanted to check, because it seemed like the estimate was variable :-)
