### ISSUE TITLE
Use lazier alternatives to `count()` in `Transaction` methods where possible

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5744]
## Motivation

Some functions like `check::has_inputs_and_outputs` in the transaction verifier or `check::anchors::sprout_anchors_refer_to_treestates` in the state service are accessing more data than is required to compute their result. 

It would be faster to use `next().is_some()` or `joinsplit_data.rest.len() + 1` in those cases, `map(Vec::len).sum()` for getting the nullifier counts for metrics, etc.

**Comment by teor2345** [comment]
Rust is pretty good at optimising iterators. Have you checked that these extra data accesses actually happen in production? Is the performance of this code actually impacting Zebra's performance?

**Comment by arya2** [comment]
> Is the performance of this code actually impacting Zebra's performance?

Not a chance, there are far too few transactions for it to matter.
