### ISSUE TITLE
deduplicate test vectors and move what can be moved to zebra-test

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#575]
Based on @teor2345's comment here https://github.com/ZcashFoundation/zebra/pull/558#pullrequestreview-440465177, we should move large vector construction to `zebra-test` as much as possible.

**Comment by teor2345** [comment]
I think #558 and #585 make a lot of progress here.

But we should do a final check for hex-encoded test vectors in modules other than zebra-test.

**Comment by teor2345** [comment]
Let's just move test vectors as we find them.
