### ISSUE TITLE
Automatically delete old GCP Artifact Registry Storage test images

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5750]
## Motivation

They are costing us a bit, and it's increasing every month.

We want to keep them around long enough so that PRs that are still on the same commit can be re-run with the same image.

### Designs

Delete test images from GCP Artifact Registry Storage after 3 weeks.
(Most PRs get updated every few days, and merge within 1-2 weeks.)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5750?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn

**Comment by gustavovalverde** [comment]
@mpguerra as I'm finishing this one. I'd prefer to have it in this sprint.
