### ISSUE TITLE
Update block production algorithm once ZIP-317 updates

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5752]
## Motivation

We're expecting a minor update to the ZIP-317 block production algorithm.

### Specifications

https://zips.z.cash/zip-0317

With the changes from the PR:
https://github.com/zcash/zips/pull/650

### Designs

1. Replace the dynamic size limit with a fixed action limit. This makes the design simpler.
    - Don't make the limit configurable for now, we'll see if we need to do that later.

2. Update comments to link to ZIP-313:
    - `[ZIP-313]: https://zips.z.cash/zip-0313#specification`
    - https://github.com/ZcashFoundation/zebra/pull/5724#discussion_r1036518490

3. Replace "transparent P2SH single signature address" with "transparent P2SH address", the single signature part is wrong

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate to this issue?
