### ISSUE TITLE
Mark test-only code with `#[cfg(test)]`

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5775]
## Motivation

We should mark test-only code such as `MockSyncStatus`, `MockService`, `MockChainTip`, or the `impl Mempool` block [in the tests module here](https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/mempool/tests.rs) under `#[cfg(test)]` to more clearly distinguish it.

**Comment by teor2345** [comment]
Most of this code is already in test-only modules or crates.

I looked for test-only code that isn't under `#[cfg(test)]`, and the only code I could find was:
- `NoChainTip`, or
- newly added in PR #5769

**Comment by arya2** [comment]
> Most of this code is already in test-only modules or crates.

Oh, I missed that, my bad.
