### ISSUE TITLE
Make EquihashSolution.is_valid() take a BlockHeader

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#578]
The signature `pub fn is_valid(&self, input: &[u8], nonce: &[u8]) -> bool` is a bit worrisome compared to one that takes a `BlockHeader` because it forces the caller to perform extra parsing logic.  Since we perform structural validation during parsing, we should try to work only on parsed representations as much as possible (even if it meant that we need to occasionally re-serialize for hashing, etc.). 

As a concrete example, the `equihash_solution_test_vector_is_valid` test has two checks that aren't really checks of the method itself, but of the parsing logic its interface pushes to the caller, and as soon as we take a `BlockHeader`, we can guarantee those properties statically so we have nothing to test.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/549#issuecomment-651336023_

**Comment by yaahc** [comment]
Fixed by https://github.com/ZcashFoundation/zebra/pull/550
