### ISSUE TITLE
Release Zebra 1.0.0-rc.3

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5785]
## Motivation

We do regular Zebra releases.

**Comment by mpguerra** [comment]
We're probably not going to have a Sprint 26 so I will move this to the first sprint of next year when it's generated by Zenhub

**Comment by teor2345** [comment]
~~I think this is arya's release, but I'm happy to help out!~~

**Comment by teor2345** [comment]
Oops, sorry, I misread the roster, it's mine!
