### ISSUE TITLE
Make `zebra-checkpoints` work with Zebra RPCs, as well as `zcashd` RPCs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5852]
## Motivation

Currently, the `zebra-checkpoints` utility uses the `getblockcount` RPC, which Zebra doesn't have. But we do have other RPCs that provide the current block height.

If we use those RPCs, then `zebra-checkpoints` will work with both `zcashd` and Zebra.

It might also be useful to be able to compare checkpoints generated by `zcashd` and `zebrad`.

## Proposed Changes

Switch `zebra-checkpoints` from `getblockcount` to the `blocks` field of `getblockchaininfo`.

## Related Work

Another larger alternative change is:
- #795

**Comment by teor2345** [comment]
@mpguerra this is one of the alternative `zebra-checkpoints` changes we discussed in the engineering sync.

**Comment by mpguerra** [comment]
@oxarbitrage can you please add an estimate to this issue since you worked on it?
