### ISSUE TITLE
CI failed to authenticate to google cloud: Failed to get ID Token.

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#5872]
Commit https://github.com/ZcashFoundation/zebra/commit/f7011a903e1a0370c0b2ee23f9dc294a2ac47c4f (the merge of https://github.com/ZcashFoundation/zebra/pull/5843 into main) failed with:

Failed to get ID Token. 

https://github.com/ZcashFoundation/zebra/actions/runs/3699930152/jobs/6286014095#step:6:62

Low priority if other merges on top of this one pass.

**Comment by gustavovalverde** [comment]
This seems like a race condition. We might track it later if this gets too often https://github.com/aws-actions/configure-aws-credentials/issues/469 

Feel free to reopen it or ping me if you see this error again.
