### ISSUE TITLE
If we upgrade the sled major version, delete and re-sync the chain

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#588]
If sled releases a major version update which changes its database structure, new zebrad versions won't be able to load previous state.

Since all our state is public, the easiest way to handle upgrades is to delete state, and re-sync.

This change is only required after we do a sled major version update.

**Comment by hdevalence** [comment]
Note: a database structure change is a semver breaking change, so this will only be an issue when we upgrade the sled version past `0.32.x`.

**Comment by teor2345** [comment]
Thanks, I tweaked the description and title.

**Comment by hdevalence** [comment]
Closing this because there's nothing actionable, it's just a reminder.
