### ISSUE TITLE
Do manual stateful Zebra sync tests before release

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#589]
For the first alpha release, we want to manually test that new zebrad versions can load previous block chain state.

Here's what a manual test looks like:
1. Keep a zebrad running locally, and check that it's syncing
2. When a new version arrives, install the new version, and restart zebrad
3. Check that zebrad is still syncing

These tests needs to happen in every release, until we automate stateful upgrade tests in #587.

**Comment by mpguerra** [comment]
This seems like something that should live in a pre-release or go/no-go checklist. e.g "new release version should be able to load previous block chain state"  - regardless of whether they are done automatically or manually

**Comment by teor2345** [comment]
We automatically do the tests in #587 for every commit, so we don't need to do them manually before a release.
