### ISSUE TITLE
Verify that the Equihash Solution is valid for the Block Header

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#591]
As part of #477, we need to verify that the equihash solution covers the previous fields in the block header.

Once #578 / #550 are completed, we should be able to call `is_valid_equihash_solution()` on a `BlockHeader` here:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/verify/block.rs#L97

**Comment by teor2345** [comment]
@oxarbitrage you might like to do this ticket, but you'll need to wait until @yaahc has finished ticket #578 / PR #550.

**Comment by oxarbitrage** [comment]
Sure, will take it, thanks @teor2345 . You guys can assign me if you want.

**Comment by teor2345** [comment]
Fixed by #607.
