### ISSUE TITLE
Remove duplicate `read::hash()` and `read::hash_by_height()` consensus-critical code

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5910]
## Motivation

Zebra has two duplicate state functions for reading a block hash: `read::hash()` and `read::hash_by_height()`. We don't want to have duplicate code in Zebra, because it risks breaking consensus. It's also hard to maintain and audit.

This is a simple search-and-replace fix.

https://github.com/ZcashFoundation/zebra/blob/53e836efdcb6f25319403d8e43daaff92408b009/zebra-state/src/service/read/find.rs#L111-L112

https://github.com/ZcashFoundation/zebra/blob/53e836efdcb6f25319403d8e43daaff92408b009/zebra-state/src/service/read/block.rs#L187-L190

### Testing

This change will improve testing, because the existing tests will all check the same function, rather than some tests checking one function, and some checking the other function.

## Related Work

Discovered as part of PR #5894.

**Comment by teor2345** [comment]
@mpguerra can we schedule this fix soon?

It's very small, and it's a consensus compatibility risk.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate to this issue?
