### ISSUE TITLE
Store the serialized block size in the database

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5911]
## Motivation

RPCs like `getblock` return the serialized block size, but we haven't found any specific clients that need it yet.

If we find clients that need it, we want to get this size efficiently, without reading the whole block. This substantially improves the performance of clients like `lightwalletd` and `zebra-checkpoints`, which use other fields in this RPC.

### Complex Code or Requirements

We could add a block size to the `hash_by_height` index. It only needs to be 4 bytes:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0005-state-updates.md#rocksdb-data-structures

This ticket updates the database format on disk. If we increment the state version, we'll run some rarely-used CI jobs, and make all our users rebuild their entire databases from scratch.

But we could implement the size lookup in a backwards-compatible way instead. If we check the length of the `hash_by_height` value, and return `None` if the block size is not present in the database, then old databases will still work. We could remove this compatibility code the next time we increment the state version.

### Testing

We'll need tests for reading block sizes from the database.
Writing block sizes is covered by our existing sync and cached state tests.

If we use the backwards-compatible design, we'll also need specific tests for legacy state data (without the size) and new state data (with the size).

Our existing cached state tests will check both these modes. But coverage won't be guaranteed, because the blocks that have sizes will change depending on how other tests and PRs use the cached state.

## Related Work

This is a performance fix for PR #5894, we're using a workaround for now. The workaround has acceptable performance for `zebra-checkpoints`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5911?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@mpguerra I think this might be optional, since we solved #5894 another way. And the performance is acceptable.
