### ISSUE TITLE
On startup, check that the finalized state blocks match the checkpoint hashes

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5912]
## Motivation

Currently, Zebra doesn't check if its checkpoints match the blocks in its cached state. This means that Zebra can follow a chain fork for a very long time, even after restarts.

This has become more of an issue recently, because Zebra will soon be able to:
- mine its own blocks, and
- generate its own checkpoints.

### Specifications

`zcashd` checks for a few well-known block hashes on startup, which are typically network upgrade activations.

### Complex Code or Requirements

To avoid startup delays, Zebra can do these checks concurrently with the rest of its startup and sync tasks. This can happen in a similar way to the Zcash parameter downloads. (But it can be async, because the state service is async.)

https://github.com/ZcashFoundation/zebra/blob/bc783a7745251b7ab0e23d58c26080191c6306ca/zebra-consensus/src/chain.rs#L242-L251

### Testing

We could manually insert a bad block hash into the database, then run this check and make sure it fails.

The success case will be covered by existing tests.

## Related Work

This is part of a larger issue for the Zcash network - we don't have good monitoring for chain forks or other serious network events.

We also want to track the recent chain forks that an individual Zebra node has discovered in our metrics:
- #5297

**Comment by mpguerra** [comment]
tentatively scheduling this for after the GBT work

**Comment by teor2345** [comment]
I had a bit of trouble deciding the priority for this ticket. I think it might be medium priority, because it is an easy fix for a consensus rule check we should be doing.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5912?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
