### ISSUE TITLE
Unclear implementation of block "timestamp against prev" (time-too-old) consensus rule

### ISSUE THREAD

**Issue by DeckerSU** [ZcashFoundation/zebra#5914]
It appears that the consensus rule of "checking the timestamp against the median time past" (`time-too-old`) which is present in ZCash (ZEC) is not implemented in Zebra:

https://github.com/zcash/zcash/blob/master/src/main.cpp#L4829-L4835
```cpp
    // Check timestamp against prev
    auto medianTimePast = pindexPrev->GetMedianTimePast();
    if (block.GetBlockTime() <= medianTimePast) {
        return state.Invalid(error("%s: block at height %d, timestamp %d is not later than median-time-past %d",
                                   __func__, nHeight, block.GetBlockTime(), medianTimePast),
                             REJECT_INVALID, "time-too-old");
    }
```

In Zebra sources I see only `time-too-new` rule implementation:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/block.rs#L193-L195
```rust
            let now = Utc::now();
            check::time_is_valid_at(&block.header, now, &height, &hash)
                .map_err(VerifyBlockError::Time)?;
```

It appears that there is no check for a `time-too-old` at all. I understand that Zebra uses "parallel block validation", which allows for blocks to come in an "unpredictable order" and could potentially not provide enough data to calculate the median time past at that moment. However, it looks like this check is not present in the contextual validation (nor in `initial_contextual_validity`, nor in `block_is_valid_for_recent_chain`) either. If I am mistaken, I apologize.

**Comment by teor2345** [comment]
Thanks for looking into Zebra's consensus rule implementation - it's great to have people checking our code!

I think this rule is implemented here, as part of the difficulty threshold check (because they use the same set of blocks):
https://github.com/ZcashFoundation/zebra/blob/e9d6e975b48b5c54ace39fa58b7f6749926c3ef3/zebra-state/src/service/check.rs#L248-L263

We could rename that function to make it clearer, what do you think?

Also, just letting you know for next time that you can report security issues to security@zfnd.org. We don't have PGP keys yet, but I'll remind the team that we need to get them soon.
https://github.com/ZcashFoundation/zebra/blob/main/SECURITY.md

**Comment by DeckerSU** [comment]
I apologize for not paying attention to this check. However, now I can see that it exists. What about function name, may be It is better to call it `is_difficulty_threshold_and_block_time_valid` (or `difficulty_threshold_and_block_time_is_valid`), as it not only deals with difficulty, but also with two consensus rules that check the candidate time?

**Comment by teor2345** [comment]
> I apologize for not paying attention to this check.

No worries! We really do appreciate it when people check our code 🙂 

> However, now I can see that it exists. What about function name, may be It is better to call it `is_difficulty_threshold_and_block_time_valid` (or `difficulty_threshold_and_block_time_is_valid`), as it not only deals with difficulty, but also with two consensus rules that check the candidate time?

What do you think of `check::difficulty_threshold_and_time_are_valid(...)` ?

You can see these changes and another consensus rule cleanup in PR #5915.

**Comment by DeckerSU** [comment]
Looks good to me. The only thing, there will be good to change `difficulty_threshold_is_valid` -> `difficulty_threshold_and_time_are_valid` in [0006-contextual-difficulty.md](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0006-contextual-difficulty.md) also.

**p.s.** Also not related to this PR, but jfyi - seems there is also need to update ``StateService::check_contextual_validity`` related documentation, as it no longer exists since https://github.com/ZcashFoundation/zebra/pull/5257 .

**Comment by teor2345** [comment]
Thanks for the reminder, but we usually don't update RFCs after they've been approved. We use code comments and rustdoc instead.

Otherwise we'd be changing a lot of code in two different places.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate here?
