### ISSUE TITLE
Manually test that Zcash mining pools can use Zebra to mine blocks on testnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5934]
## Motivation

We should run Zebra with mining pool software before asking other mining pools to test it.

### Complex Code or Requirements

A bunch of us have done some work on this, it's tricky to get the right dependencies to deploy most mining pools.

## Related Work

- #5686
- #5803
- #5935

Here is our previous [discussion](https://github.com/ZcashFoundation/zebra/discussions/5804) about mining pool testing.

**Comment by teor2345** [comment]
I think we should put a time limit of one day on this ticket. If we can't get it working quickly, we can contact an actual mining pool later to help with testing, when we've done more RPCs.

**Comment by mpguerra** [comment]
> I think we should put a time limit of one day on this ticket. If we can't get it working quickly, we can contact an actual mining pool later to help with testing, when we've done more RPCs.

Agreed

@ZcashFoundation/zebra-team can whoever has done some research and/or testing add their notes to this issue.

Scheduling for Sprint 2 as I'd like to get all of the testing resolved in the next sprint

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5934?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
moving to Sprint 3 for now

**Comment by teor2345** [comment]
I did some testing on this back in December, it was tricky because I couldn't get the node dependencies right. And some of the C libraries wouldn't compile on my machine.

But maybe using the node dependency lock files will help.

**Comment by upbqdn** [comment]
I made it work by modifying the source code and installation configs. I could pack it all into some container.

**Comment by teor2345** [comment]
Even just a diff from the original source would help!

**Comment by mpguerra** [comment]
Let's document any successes we've had with this here and what we have done. This will help with #6028

**Comment by teor2345** [comment]
> Let's document any successes we've had with this here and what we have done. This will help with #6028

These instructions are now at:
https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md

Anyone can open PRs to improve them.

**Comment by arya2** [comment]
🎉 The 6 Sols/s is a little sad but the instructions worked well for me. I had some trouble with installing dependencies for `s-nomp`, I think `export CXXFLAGS="-std=gnu++17"` is important there.

![image](https://user-images.githubusercontent.com/5491350/217302672-e1e34776-ad3d-44d2-bc6d-1ea0c665f6d6.png)

![image](https://user-images.githubusercontent.com/5491350/217309273-53f1c7ae-7058-4ce3-8052-d7e707783bb7.png)

**Comment by teor2345** [comment]
> The 6 Sols/s is a little sad but the instructions worked well for me.

This is normal for 1-3 cores, so it might help to document it in the instructions.

> I had some trouble with installing dependencies for `s-nomp`, I think `export CXXFLAGS="-std=gnu++17"` is important there.

Can you please open an PR to update the instructions? I think those flags are marked as optional, but if they are required we should remove the "optional".

https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md

**Comment by oxarbitrage** [comment]
I was able to mine as well:

![mined](https://user-images.githubusercontent.com/21685097/217551473-bb0fbd99-63f3-478f-bb48-da73633fc099.png)

**Comment by mpguerra** [comment]
I think everyone has managed to mine a block now. 👏
