### ISSUE TITLE
Remove some crates.io patches from zebra/Cargo.toml

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#594]
Some of the crates.io patches refer to commit hashes that aren't in @yaahc's GitHub repositories any more, causing build failures like:
https://github.com/ZcashFoundation/zebra/pull/524/checks?check_run_id=841330606

Removing the color-eyre and spandoc patches works on my machine, and hopefully CI:
https://github.com/ZcashFoundation/zebra/pull/524/commits/b05e6b55f7c0c52ee446fa7b3c0d76ffc0632d70
https://github.com/ZcashFoundation/zebra/pull/524/checks?check_run_id=841458489

But I'm not sure if that's the right thing to do.

**Comment by yaahc** [comment]
spandoc patches shouldn't need to be removed, but we should remove the color-eyre ones. I was afraid they would break but i was hoping with the `rev` stuff henry did it would survive deleting the branch... guess not. Sorry about that :sweat_smile:
