### ISSUE TITLE
Fix spurious test_rpc_response_data test failure

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#5940]
An `expect_request` in the RPC snapshot tests timed out:

> ---- methods::tests::snapshot::test_rpc_response_data stdout ----
> 
> The application panicked (crashed).
> Message:  timeout while waiting for a request
>  in zebra_test::mock_service::MockService<zebra_node_services::mempool::Request, zebra_node_services::mempool::Response, zebra_test::mock_service::PanicAssertion, alloc::boxed::Box<dyn core::error::Error+core::marker::Sync+core::marker::Send>>

https://github.com/ZcashFoundation/zebra/actions/runs/3886245054/jobs/6631117711#step:14:3001

_Originally posted by @arya2 in https://github.com/ZcashFoundation/zebra/issues/5870#issuecomment-1377802583_

### Possible Solution

Drive mock service request handling futures on main thread (see https://github.com/ZcashFoundation/zebra/pull/5909)

**Comment by mpguerra** [comment]
it's not happening as much anymore

**Comment by teor2345** [comment]
Failed in PR #6124 in the merge queue:
https://github.com/ZcashFoundation/zebra/pull/6124#issuecomment-1432096183

**Comment by teor2345** [comment]
Also in PR #6161 in the merge queue:
https://github.com/ZcashFoundation/zebra/actions/runs/4179532386/jobs/7240319881#step:3:1374

**Comment by teor2345** [comment]
This ticket is hard to diagnose correctly, because we need to check timeouts to see which tests are still running. (If there's a `test_rpc_response_data has run for more than 60 seconds` in the logs, but no success message, it's the one that hasn't finished.)

So we might not know how much it is happening until we've fixed all the other CI bugs on `main`.

**Comment by teor2345** [comment]
Failed in PR #6163:
https://github.com/ZcashFoundation/zebra/actions/runs/4192197829/jobs/7268094975#step:3:1403

@mpguerra I think this is actually an important issue to fix soon, it seems to be failing multiple times a day.
