### ISSUE TITLE
Check that upcoming librustzcash changes to primitives and proofs still compile with Zebra

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5947]
## Motivation

The `zcashd` developers have asked us to report any breaking API changes in this `librustzcash` PR:
https://github.com/zcash/librustzcash/pull/755

### Testing

The compiler should identify any breaking API changes for us, and our CI should identify any bugs introduced by the refactor.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5947?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is done in PR #5966, we just need to turn that PR into a ticket I guess.

(It could be a while before the changes get released by ECC.)

**Comment by teor2345** [comment]
The tests passed, the new upgrade ticket is #5978.

**Comment by mpguerra** [comment]
The issue was closed before the planning poker round was completed and so we don't have an estimate from that. @teor2345 can you please add an estimate for this issue since you worked on it?
