### ISSUE TITLE
Upgrade to the zcash_primitives 0.10 API

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5978]
## Motivation

When the next version of zcash_primitives is released after 0.9.1, we need to apply these changes to update to the new API:
- PR #5966

### Testing

This code already has test coverage, and the tests on the original PR passed.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5978?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
