### ISSUE TITLE
Fix clippy warnings in zebra-test and zebra-chain/tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#598]
It looks like we merged some code with clippy warnings as part of PR #558:
https://github.com/ZcashFoundation/zebra/runs/832764571#step:4:926

@oxarbitrage, would you mind fixing them up?

You can also run `cargo clippy` on your own machine to see the warnings.

I didn't see the clippy warnings when I did the review, because GitHub doesn't show check annotations in PRs from forked repositories:
https://github.com/actions-rs/clippy-check/issues/2

**Comment by oxarbitrage** [comment]
Sorry about that, i applied the suggestions in https://github.com/ZcashFoundation/zebra/pull/602 and now the output is empty: https://github.com/ZcashFoundation/zebra/pull/602/checks?check_run_id=845754570#step:4:921
