### ISSUE TITLE
Use the same format as `zcashd` for `getblocktemplate` proposal mode errors 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5981]
## Motivation

When I use `zebra-utils/zcash-rpc-block-template-to-proposal` from PR #5944 to send a block proposal from Zebra to both `zcashd` and Zebra, I see these differences in the response format:
```
Proposal response diffs between ports  8232 6666 and time sources CurTime MinTime MaxTime ClampedNow:
--- /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 15:15:37.881314992 -0300
+++ /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.MaxTime.6666.json	2023-01-26 15:15:38.329290891 -0300
@@ -0,0 +1,5 @@
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
```

Zebra should return a string to match the `zcashd` response format, but it is currently returning JSON. For example zcashd returns errors like `bad-txns-inputs-missingorspent`

### Specifications

We were following the specifications in the bitcoin improvement proposals here, but being compatible with the `zcashd` implementation is a higher priority.

It is enough to return any error string in `kebab-case` format - we don't need to match the exact error wording.

For the example above about best tip error zebra should return something like:

`invalid-proposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash–must–be-the–best-chain-tip`

### Complex Code or Requirements

This should be a simple format change.

### Testing

We can use the `zebra-utils/zcash-rpc-block-template-to-proposal` script to manually re-test to make sure this bug is gone. We'll need to wait for an error.

(The previous block error happens if a new block has just arrived, or there is a chain fork.)

**Comment by teor2345** [comment]
@mpguerra we might want to schedule this fix in this sprint, the different outputs could make testing harder for everyone, because we have to check the differences every time we run the script. But this is not a consensus rule bug, so it's not as important as #5982.

@arya2 what do you think?

**Comment by arya2** [comment]
> @mpguerra we might want to schedule this fix in this sprint, the different outputs could make testing harder for everyone, because we have to check the differences every time we run the script. But this is not a consensus rule bug, so it's not as important as #5982.
> 
> @arya2 what do you think?

I think it's low-priority since it only happens for rejections where the response is going to be different anyways because Zebra doesn't provide any specific reject-reasons. The intent in this case is to test the template response rather than getblocktemplate in proposal mode so I think should prioritize fixing the causes of rejections over this.

**Comment by teor2345** [comment]
> > @mpguerra we might want to schedule this fix in this sprint, the different outputs could make testing harder for everyone, because we have to check the differences every time we run the script. But this is not a consensus rule bug, so it's not as important as #5982.
> > @arya2 what do you think?
> 
> I think it's low-priority since it only happens for rejections where the response is going to be different anyways because Zebra doesn't provide any specific reject-reasons. The intent in this case is to test the template response rather than getblocktemplate in proposal mode so I think should prioritize fixing the causes of rejections over this.

It could be a blocker for running with nodes if they exit or permanently fail when they get an error response they are not expecting.

So I think we might want to fix it before we ask mining pools to test Zebra.

(We expect to return a "wrong tip block" to about 1% of proposals, due to changing chain forks, and new blocks being committed while the proposal is being created.)

**Comment by teor2345** [comment]
And I agree that the consensus bug is a higher priority!

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5981?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We could try replacing all the punctuation and newlines in those messages with `-` ?

Then the message would stay detailed and readable, but it would match the format that `zcashd` uses.

**Comment by teor2345** [comment]
@mpguerra I don't think this is a blocker for anything, except maybe for some mining pool software using Zebra.

**Comment by oxarbitrage** [comment]
I was not able to reproduce this issue yet. Had been using this to test: https://github.com/ZcashFoundation/zebra/issues/5803#issuecomment-1386250961

There are failures but not the one posted here, i am unsure if this is still happening.

Other fails i was able to see were:

Zcash responding  with `-inconclusive-not-best-prevblk` and zebra with nothing. I got this one 3 times.

```
Proposal response diffs between ports  8232 6666 and time sources CurTime MinTime MaxTime ClampedNow:
--- /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 14:26:53.409248928 -0300
+++ /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.6666.json	2023-01-26 14:26:53.409248928 -0300
@@ -1 +0,0 @@
-inconclusive-not-best-prevblk
--- /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 14:26:53.409248928 -0300
+++ /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.MinTime.6666.json	2023-01-26 14:26:53.425247940 -0300
@@ -1 +0,0 @@
-inconclusive-not-best-prevblk
--- /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 14:26:53.409248928 -0300
+++ /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.MaxTime.6666.json	2023-01-26 14:26:53.449246461 -0300
@@ -1 +0,0 @@
-inconclusive-not-best-prevblk
--- /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 14:26:53.409248928 -0300
+++ /tmp/tmp.xPEFRgWMHJ.block-template-proposal/proposal-check-getblocktemplate-proposal.ClampedNow.6666.json	2023-01-26 14:26:53.469245227 -0300
@@ -1 +0,0 @@
-inconclusive-not-best-prevblk
```

Invalid proposal in zebra but valid in zcashd. I got this one one time.

```
Proposal response diffs between ports  8232 6666 and time sources CurTime MinTime MaxTime ClampedNow:
--- /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 15:15:37.881314992 -0300
+++ /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.MaxTime.6666.json	2023-01-26 15:15:38.329290891 -0300
@@ -0,0 +1,5 @@
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
--- /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 15:15:37.881314992 -0300
+++ /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.ClampedNow.6666.json	2023-01-26 15:15:38.461283790 -0300
@@ -0,0 +1,5 @@
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
```

I am not totally sure from where the error in the original post is built, seems to be at https://github.com/ZcashFoundation/zebra/blob/main/zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs#L49 ?

I can try to change that `kebab-case`, however not sure if we need to change `kind`, `error` or both and i am not sure if that will fix the problem either.

@teor2345 can you point me to where do you think the format needs to be changed ?

**Comment by teor2345** [comment]
The exact error doesn't matter, this ticket is about the error format.

`zcashd` produces this format:
```
inconclusive-not-best-prevblk
```

But `zebrad` produces this format:
```
invalid proposal: Block {
    source: ValidateProposal(
        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
    ),
}
```

We don't know how strict mining pools are about the response format. And if they get an error, they might just give up on using Zebra, rather than telling us.

Here is the code that needs to change:
https://github.com/ZcashFoundation/zebra/blob/b3a480757a6378fa8d031468092420e624479d3f/zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs#L44-L56

Currently, `zebra-rpc` formats the string with punctuation, newlines, and spaces. But we want a string that looks like `zcashd` instead:
> invalid-proposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash–must–be-the–best-chain-tip

It is ok to delete or replace punctuation. It doesn't matter if the Block, source, or ValidateProposal are included or not.

**Comment by oxarbitrage** [comment]
I was never referring to the exact error, i already know that is not the problem. All the explication about what the miners will do (according to what you think) are not needed either.

Here what i am asking.

Your error:

```
-bad-txns-inputs-missingorspent
+{
+  "reject_reason": "rejected",
+  "capabilities": [
+    "proposal"
+  ]
+}
```

My error (zcashd produces and error but zebra does not):

```
-inconclusive-not-best-prevblk
```

In my other error (zebra produces an error and zcashd is not):

```
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
```

Making a regex or whatever to convert from 

```
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
```

into `invalid-proposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash–must–be-the–best-chain-tip` seems a bit different than doing it for

```
+{
+  "reject_reason": "rejected",
+  "capabilities": [
+    "proposal"
+  ]
+}
```

into `rejected` or `reject-reason-rejected`. I have no idea on why capabilities is there. I think we should try to remove it.

**Comment by teor2345** [comment]
> I was never referring to the exact error, i already know that is not the problem. All the explication about what the miners will do (according to what you think) are not needed either.

Thanks for letting me know. I explained the errors because you said you couldn't reproduce the issue.

**Comment by teor2345** [comment]
> I have no idea on why capabilities is there. I think we should try to remove it.

The format was already changed in PR #5993, so the error message in the ticket is out of date. Would you like to update the ticket, or did you want me to?

**Comment by oxarbitrage** [comment]
> The format was already changed in PR #5993, so the error message in the ticket is out of date. Would you like to update the ticket, or did you want me to?

Ok, that is what i had missing. Got it now, thanks. Ill make the changes in the OP with my error.

**Comment by teor2345** [comment]
> Making a regex or whatever to convert

I'd suggest using `str::replace()`:
https://doc.rust-lang.org/std/primitive.str.html#method.replace

If we do something like this:
```rust
format!("{error:?}").replace(|c| !c.is_alphanumeric(), "-").make_ascii_lowercase()
```

Then it doesn't matter what the debug format is, and we can change that format without breaking the RPC.

**Comment by oxarbitrage** [comment]
> > Making a regex or whatever to convert
> 
> I'd suggest using `str::replace()`: https://doc.rust-lang.org/std/primitive.str.html#method.replace
> 
> If we do something like this:
> 
> ```rust
> format!("{error:?}").replace(|c| !c.is_alphanumeric(), "-").make_ascii_lowercase()
> ```
> 
> Then it doesn't matter what the debug format is, and we can change that format without breaking the RPC.

Yes, that is what i was thinking about, not a regex really.
