### ISSUE TITLE
Transaction nLockTIme check (CheckFinalTx) against MTP when adding to mempool possible missed

### ISSUE THREAD

**Issue by DeckerSU** [ZcashFoundation/zebra#5984]
In `zcashd` implementation when we accepting transaction in memory pool (`AcceptToMemoryPool`) we checking is this transaction final or not - https://github.com/zcash/zcash/blob/master/src/main.cpp#L1816-L1820 :+1: 
```cpp

    // Only accept nLockTime-using transactions that can be mined in the next
    // block; we don't want our mempool filled up with transactions that can't
    // be mined yet.
    if (!CheckFinalTx(tx, STANDARD_LOCKTIME_VERIFY_FLAGS))
        return state.DoS(0, false, REJECT_NONSTANDARD, "non-final");
```
Here we called `CheckFinalTx` with `flags == 2` and inside it calls [`IsFinalTx(tx, nBlockHeight, nBlockTime)`](https://github.com/zcash/zcash/blob/master/src/main.cpp#L784) with `nBlockTime == chainActive.Tip()->GetMedianTimePast()`.

But in `zebrad` this check seems omitted. We have one [verifier](https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/transaction.rs#L297) for block and mempool requests, and inside we have only one locktime related [check](https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/transaction.rs#L309-L312):
```rust
            // Do basic checks first
            if let Some(block_time) = req.block_time() {
                check::lock_time_has_passed(&tx, req.height(), block_time)?;
            }
```
But this check only performed on `req` is `Request::Block` with block time, which corresponds to call `isFinalTx` in `ContextualCheckBlock` of `zcashd`, but on `Request::Mempool` - seems there is no check tx `nLockTIme` against MTP is implemented in `zebrad`. I apologize profusely if I am incorrect and once more overlooked something.

**Comment by teor2345** [comment]
@mpguerra we might want to schedule this bug in this sprint as well, because it can make generated blocks invalid.

**Comment by teor2345** [comment]
Thanks for reporting this, we think it is a bug in the mempool  which might allow some invalid transactions. Some light wallets might see these transactions in the mempool in production. But that seems like a low impact bug.

It also impacts block production - it could make some produced blocks invalid. So we need to fix it before we stabilise the `getblocktemplate` RPC.

We need to make two fixes here:
- do the check in the mempool transaction verifier based on the median-time-past of the best tip in the state
- document that mempool transactions remain valid as the tip grows, because the median-time-past can only increase, and the lock time is a "less than" check (and quote the relevant consensus rules)

**Comment by DeckerSU** [comment]
One possible way to pass the `mtp` (median-time-past) in the mempool transaction verifier could be to calculate the `mtp` on the best chain tip before calling `set_best_non_finalized_tip` and then pass it within the `ChainTipBlock` structure in `update_latest_chain_channels` to the mempool. This way, the `mtp` will always be known on the current best chain tip (mean, we can always get it from receiver in `LatestChainTip`), and can be passed to the verifier directly in `Request::Mempool`, alongside with other data (transaction and height). However, you may have a better solution. I apologize if I did not explain my version of the solution very clearly.

**Comment by teor2345** [comment]
> One possible way to pass the `mtp` (median-time-past) in the mempool transaction verifier could be to calculate the `mtp` on the best chain tip before calling `set_best_non_finalized_tip` and then pass it within the `ChainTipBlock` structure in `update_latest_chain_channels` to the mempool. This way, the `mtp` will always be known on the current best chain tip (mean, we can always get it from receiver in `LatestChainTip`), and can be passed to the verifier directly in `Request::Mempool`, alongside with other data. However, you may have a better solution. I apologize if I did not explain my version of the solution very clearly.

Thanks, that is one of the solutions we are considering. Another alternative is to add the median-time-past to the `ChainInfo` state response, or add another state request and response for the median-time-past:
https://github.com/ZcashFoundation/zebra/blob/2018d49907f489f684cfa6248fd78273e5157f6c/zebra-state/src/response.rs#L139

Whichever solution we choose, we might be able to re-use the same state code to calculate the median-time-past, if it's easy to split it out of these functions:
https://github.com/ZcashFoundation/zebra/blob/2018d49907f489f684cfa6248fd78273e5157f6c/zebra-state/src/service/read/difficulty.rs#L200-L210

And you have nothing to apologise for, we welcome suggestions 🙂

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5984?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
