### ISSUE TITLE
Zebra returns a confusing error for block proposals when it isn't fully synced yet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#5991]
## Motivation

Sometimes Zebra knows that it isn't fully synced, but it accepts block proposals anyway.

This is a temporary issue that gets resolved when Zebra syncs to the tip. And it's just in proposal mode. So this seems like a low priority.

The proposals fail with an error like:
(The error format was changed in PRs #5993 and #6044.)
```
invalid proposal: Block {
    source: ValidateProposal(
        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
    ),
}
```

But it would be more helpful to return the same error as the template mode:
```
Zebra has not synced to the chain tip, estimated distance: 67, local tip: Height(1952293). Hint: check your network connection, clock, and time zone settings.
```

### Specifications

We might want to follow whatever `zcashd` does here.
This might impact compatibility with some mining pools.

### Testing

Manually run `zcash-rpc-block-template-to-proposal`. To reproduce this error, get the template from a synced `zcashd` instance, and send it to a Zebra instance you just started.

## Related Work

These tickets change how errors are displayed:
- #5981

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/5991?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
