### ISSUE TITLE
Document how to mine on testnet using Zebra and `s-nomp`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6028]
## Motivation

We want people to try to use zebra to mine blocks, in order to help them to do this, we should share how we have attempted to do this ourselves. We might also want to consider publishing this "How to" as a blog post (#6159).

### Testing

The reviewer should follow the instructions outlined in the document to configure the mining pool software and zebra to attempt (and ideally succeed) mining a block on testnet.

## Related Work

We will do the actual manual test in #5934. This ticket is for documenting the steps to set up and run the  manual test.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6028?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We've started this documentation here, please feel free to open PRs as you do testing and find missing steps:
https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md

**Comment by teor2345** [comment]
This ticket isn't finished yet, there are still TODOs about changing the pool name in that document.

**Comment by teor2345** [comment]
@mpguerra can you link the documentation PRs in a way that doesn't close this ticket?

**Comment by teor2345** [comment]
When we've finished changing the documentation, do we want to move it into the Zebra repository with the other user docs?
https://github.com/ZcashFoundation/zebra/tree/main/book/src/user

It's a bit hard to find right now, because it's in a completely separate repository:
https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md

**Comment by arya2** [comment]
> When we've finished changing the documentation, do we want to move it into the Zebra repository with the other user docs? 

I think so, it would be good for it to be accessible from the Zebra repository. We could also add a more general doc for mining with Zebra and include a link to it as an example.

**Comment by teor2345** [comment]
I have tested the latest code changes and opened another minor doc PR:
[change(doc): Add note about quitting nheqminer](https://github.com/ZcashFoundation/s-nomp/pull/8)

**Comment by teor2345** [comment]
> We could also add a more general doc for mining with Zebra

This will be really helpful when we ask mining pools to test Zebra.

**Comment by mpguerra** [comment]
> When we've finished changing the documentation, do we want to move it into the Zebra repository with the other user docs? https://github.com/ZcashFoundation/zebra/tree/main/book/src/user

Yes let's move it into the zebra repo

> I think so, it would be good for it to be accessible from the Zebra repository. We could also add a more general doc for mining with Zebra and include a link to it as an example.

Yes, either a link or just the instructions directly. We would only keep the docs in the zebra repo updated

**Comment by mpguerra** [comment]
I would also like to publish the instructions as a blog post. 

I've updated the issue description to add a couple of check boxes to outline what we need to do before we can close off this issue.

For the blog post... do we want to just post the instructions "as is"  or do we want to add some more details, e.g an intro paragraph? Any volunteers to turn the instructions into a blogpost?

**Comment by teor2345** [comment]
> For the blog post... do we want to just post the instructions "as is" or do we want to add some more details, e.g an intro paragraph?

I think an intro paragraph would be great for the instructions and the blog post.

I think we'll want to simplify the instructions by choosing the most common or most reliable alternative:
- nvm (rather than nodenv)
- node 8.11
- Debian/Ubuntu
- remove optional steps
- assume Zebra is running on the default testnet port

**Comment by teor2345** [comment]
This ticket is currently waiting on this documentation PR, then we can move the docs to the Zebra repository:
https://github.com/ZcashFoundation/s-nomp/pull/9

**Comment by mpguerra** [comment]
Splitting this issue up. This can be closed once we're happy with the instructions in https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md
