### ISSUE TITLE
Implement z_listunifiedreceivers RPC

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6030]
## Motivation

Some mining pools use this RPC to check addresses.

### Specifications

https://zcash.github.io/rpc/z_listunifiedreceivers.html

### Designs

We can call the [`zcash_address`](https://docs.rs/zcash_address/latest/zcash_address/) crate to validate unified addresses. (Zebra also has its own transparent address parsing, but we'd be better to just be consistent and use `zcash_address` for everything.)

#### Required Fields

The required fields are:
- orchard
- sapling
- p2pkh

**Comment by teor2345** [comment]
@arya2 it looks like this ticket and #5722 will both call `ZcashAddress::try_from_encoded()`:
https://docs.rs/zcash_address/latest/zcash_address/struct.ZcashAddress.html#method.try_from_encoded

How did you want to avoid conflicts in that part of the code?
Can you push a small PR that adds the dependencies and sets up the module for the address RPC return types?
(And anything else you think might conflict.)

**Comment by arya2** [comment]
> How did you want to avoid conflicts in that part of the code? Can you push a small PR that adds the dependencies and sets up the module for the address RPC return types? (And anything else you think might conflict.)

I was hoping one of these would be closed before work started on the other, but a small PR for the parts they both have sounds good too.

**Comment by teor2345** [comment]
> > How did you want to avoid conflicts in that part of the code? Can you push a small PR that adds the dependencies and sets up the module for the address RPC return types? (And anything else you think might conflict.)
> 
> I was hoping one of these would be closed before work started on the other, but a small PR for the parts they both have sounds good too.

I'm happy to wait for this ticket, I think most pools use the other RPCs.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6030?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@mpguerra this RPC isn't used by s-nomp:
https://github.com/s-nomp/s-nomp/search?q=z_listunifiedreceivers
https://github.com/s-nomp/node-stratum-pool/search?q=z_listunifiedreceivers

But it is used by another mining pool we're in contact with.

**Comment by teor2345** [comment]
This is on the critical path for mining pool testing.

**Comment by teor2345** [comment]
@oxarbitrage I think you said you wanted to do this ticket, and maybe you've already started?

(Just checking because it's one of the tickets I could do if you don't want to.)
