### ISSUE TITLE
Don't return from long polling if the block template is an invalid block proposal

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6037]
## Motivation

`zcashd` returns an error when the block template is not a valid block (ignoring proof of work):
https://github.com/zcash/zcash/blob/9e1efad2d13dca5ee094a38e6aa25b0f2464da94/src/miner.cpp#L674-L676

Mining pools would like to start working on new blocks as soon as possible, but they are ok with some delays before seeing updated transactions.

### Design

1. If we are not long polling, return the template immediately.
2. If we are long polling, and the tip height or hash has changed, or the maximum time has elapsed, return the template immediately.
3. If we are long polling, and only the transactions in the mempool have changed, check the template as a proposal before returning, and continue long polling (don't return) if the new template is invalid.

### Specifications

This checks all the block consensus rules:
https://zips.z.cash/protocol/protocol.pdf#blockheader
https://zips.z.cash/protocol/protocol.pdf#txnencoding

### Complex Code or Requirements

We already have a function to create a block proposal and submit it to the state in our tests, so this should be simple to implement.

We should check performance long polling on large blocks before and after this change.

### Testing

This change would add a runtime test for some block proposals in production code. We already do these tests in CI.

**Comment by teor2345** [comment]
We don't know if miners prefer performance or checking correctness here.

**Comment by teor2345** [comment]
I split the complicated parts of this ticket into #6047.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6037?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
