### ISSUE TITLE
Remove librustzcash git dependency.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#604]
Currently we have a git dependency on our fork of `librustzcash`, used for the `equihash` crate. We should try to replace this with a dependency on a published crate, preferably sooner rather than later:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-chain/Cargo.toml#L32

**Comment by str4d** [comment]
Once https://github.com/zcash/librustzcash/pull/248 is reviewed and merged, I'll publish `equihash 0.1.0`.

**Comment by yaahc** [comment]
do you need us to review that PR @str4d ?

**Comment by str4d** [comment]
@yaahc yes, that would be helpful (in particular, making sure I've correctly migrated the parameter constraints over from [here](https://github.com/zcash/zcash/blob/1192116598253276e920ee164fe32547ef68dc25/src/rust/src/rustzcash.rs#L579)).

**Comment by str4d** [comment]
`equihash 0.1.0` is now published.
