### ISSUE TITLE
Verify proposals are valid after sending them to miners

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6047]
## Motivation

`zcashd` returns an error when the block template is not a valid block (ignoring proof of work):
https://github.com/zcash/zcash/blob/9e1efad2d13dca5ee094a38e6aa25b0f2464da94/src/miner.cpp#L674-L676

Mining pools would like to start working on new blocks as soon as possible, but if it turns out to be invalid, they would like it replaced with a valid template as soon as possible.

### Design

1. If we haven't checked the template's long poll id, return the template to the client immediately, then spawn a task to check it as a proposal. If the proposal is invalid, mark the long poll id of the template as invalid.
2. If a long poll id in a client request is invalid, check the next template for validity before returning it. If it is valid, return it immediately, even if there haven't been any changes. If it is not valid, continue long polling until a valid template is found.
3. Return a RPC error if we don't find a valid template within a target block interval or two.

Optional
4. Try to recover from an invalid template by dropping transactions at random.

### Specifications

This checks all the block consensus rules:
https://zips.z.cash/protocol/protocol.pdf#blockheader
https://zips.z.cash/protocol/protocol.pdf#txnencoding

### Complex Code or Requirements

We already have a function to create a block proposal and submit it to the state in our tests, so this should be simple to implement.

We should check performance on large blocks before and after this change.

### Testing

This change would add a runtime test for every block proposal in production code. We already do these tests in CI.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6047?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I was just looking at what we need to fix to officially support Zebra's mining RPCs.

If it turns out this ticket is tricky to implement, we could just assume that block templates will always be valid, and close this ticket. Then if we ever generate an invalid template, we can open a specific ticket for the bug that produced the invalid template.

**Comment by teor2345** [comment]
@mpguerra I think this ticket has accidentally been scheduled without its dependent ticket #6037. Maybe we actually want to do #6037, and not do this ticket?
