### ISSUE TITLE
Use error code -1 for incorrect RPC parameters

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6054]
## Motivation

`node-stratum-pool` expects a `-1` error code when the RPC parameters are incorrect, but `jsonrpc_core` provides code `-32602` by default:
https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L459-L461

equihash-solomining logs:
```
[PoolWorker][Thread 0][2023/01/31 16:23:19] Could not detect block submission RPC method, [{"result":{"isvalid":true,"address":"tmRGc4CD1UyUdbSJmTUzcB6oDqk4qUaHnnh"},"id":1675146199404},{"result":1,"id":1675146199399},{"result":{"build":"v1.0.0-rc.3+60.g3ab518e.modified","subversion":"/Zebra:1.0.0-rc.3/"},"id":1675146199403},{"result":{"networksolps":4,"networkhashps":4,"chain":"test","testnet":true},"id":1675146199402},{"error":{"code":-32602,"message":"`params` should have at least 1 argument(s)"},"id":1675146199405}]
```

### Complex Code or Requirements

I think we can fix this by changing the error code in an `IoHandler`, after doing the RPC call:
https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/struct.IoHandler.html#method.handle_call

This is very similar to our existing `TracingMiddleware`, we just need to change the error code in the "incorrect parameters" case:
https://github.com/ZcashFoundation/zebra/blob/9b1d26538a02ed65f7a7b87b429da995db283d4e/zebra-rpc/src/server/tracing_middleware.rs#L57-L67

### Testing

We can manually test this with `equihash-solomining` or `s-nomp`.

We might be able to do a snapshot test for `submitblock` with no arguments, but we'd have to run the whole RPC server to do it. (Calling the RPC function directly doesn't work, because Rust requires valid arguments to compile.)

## Related Work

This blocks #5934 with both `equihash-solomining` and `s-nomp`.

The only other error codes I could find are in the payment code, which Zebra doesn't support because it doesn't have a wallet:
https://github.com/s-nomp/s-nomp/blob/8567a4c649ab6f5ea37ac3c3901f2d9c2597199a/libs/paymentProcessor.js#L750

**Comment by teor2345** [comment]
@mpguerra I'd like to fix this in this sprint, because it's blocking my progress on testing mining.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate for this issue?
