### ISSUE TITLE
Ignore expected "proposal is not based on the current chain tip" error in getblocktemplate acceptance test

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6079]
## Motivation

We've seen the `getblocktemplate` test fail in CI with:

> "proposal is not based on the current best chain tip"

(see https://github.com/ZcashFoundation/zebra/pull/6013#issuecomment-1412381467)

## Possible Design

- Use getblocktemplate with long-polling in acceptance test
- Ignore/retry the getblocktemplate request in proposal mode if a new template is received from the long-polling request
- Wait a second for the long-polling to return after the block proposal result if it fails because it's not based on the current best chain tip?

## Alternative Design

- We already try the test multiple times. Make the test pass if there is at least one success, and all of the errors are "proposal is not based on the current best chain tip".

## Another Alternative

> We might also want to think about how we handle "previous block is not the tip block" errors in CI, which are expected when a new block arrives. We might need to check the tip is the same before and after the proposal before we fail the test.
https://github.com/ZcashFoundation/zebra/pull/5963#issuecomment-1396154807

**Comment by teor2345** [comment]
I just added an alternative fix here:
- We already try the test multiple times. Make the test pass if there is at least one success, and all of the errors are "proposal is not based on the current best chain tip".

**Comment by teor2345** [comment]
This seems like a high priority because it is causing CI failures in unrelated PRs.

**Comment by mpguerra** [comment]
@arya2  can you please add an estimate here?
