### ISSUE TITLE
Implement missing mining status RPCs or fields

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6081]
## Motivation

`s-nomp` shows the following status log when starting, which seems to be missing some important information (noted next to each field):
```
Network Connected:      Mainnet - missing or incorrect RPC, or config issue?
Detected Reward Type:   POW
Current Block Height:   2212372
Current Block Diff:     0.050878195
Current Connect Peers:  undefined - missing getpeers RPC field?
Network Difficulty:     NaN - missing getdifficulty? RPC
Network Hash Rate:      0.00 KH
Stratum Port(s):        1234
Pool Fee Percent:       0.2%
Block polling every:    500 ms
```

This is based on these instructions:
https://github.com/teor2345/s-nomp/blob/zebra-mining/zebra-instructions.md

We might want to create a separate ticket for each missing RPC or set of fields.

### Specifications

We'll need to find which RPCs or fields are missing by looking at the `s-nomp` code.

### Complex Code or Requirements

Depends on exactly what is missing.

### Testing

RPC snapshots and manual testing with `s-nomp`.

## Related Issues

Some of these fields might be fixed by:
- #6055

The difficulty scaling is incorrect on testnet due to a hard-coded minimum difficulty in `node-stratum-pool`:
https://github.com/s-nomp/node-stratum-pool/blob/master/lib/algoProperties.js#L28

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6081?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I think we should make specific changes in response to miner feedback, rather than having a generic ticket with no actionable tasks.
