### ISSUE TITLE
Implement `getnetworkinfo` RPC so the default `s-nomp` config works

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6082]
## Motivation

To use `s-nomp` with Zebra, users need to change the default `zec.json` coin configs:
https://github.com/s-nomp/node-stratum-pool/blob/d86ae73f8ff968d9355bb61aac05e0ebef36ccb5/lib/pool.js#L394-L398

Here is the config change:
https://github.com/teor2345/s-nomp/blob/38613124cf00cce2d5505bb1880f96088ccff93e/coins/zec.json#L74-L75

This is because we don't implement `getnetworkinfo`.

### Priority

I think this ticket is optional priority, because `s-nomp` doesn't have support for generating valid NU5 coinbase transactions with user-specified mining addresses, and we haven't found any other mining software that uses this RPC.

### Specifications

https://zcash.github.io/rpc/getnetworkinfo.html

`s-nomp` requires these fields:
- protocolversion
- connections

We can re-use the same code as `getpeers` and `getinfo`.

### Complex Code or Requirements

Depends on the fields needed by `s-nomp`.

### Testing

Snapshots and manual testing with `s-nomp`.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6082?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by jackgavigan** [comment]
> But I think this is optional, because s-nomp doesn't support NU5 anyway.

What's optional?

**Comment by teor2345** [comment]
> > But I think this is optional, because s-nomp doesn't support NU5 anyway.
> 
> What's optional?

I think this ticket is optional priority, because `s-nomp` doesn't have support for generating valid NU5 coinbase transactions with user-specified mining addresses, and we haven't found any other mining software that uses this RPC.

I'll edit the ticket to clarify.
