### ISSUE TITLE
Implement z_validateaddress RPC

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6083]
## Motivation

Some mining pools use this RPC to check addresses.

### Specifications

https://zcash.github.io/rpc/z_validateaddress.html

### Designs

We can call the [`zcash_address`](https://docs.rs/zcash_address/latest/zcash_address/) crate to validate shielded and unified addresses. (Zebra also has its own transparent address parsing, but we'd be better to just be consistent and use `zcash_address` for everything.)

We just need to implement these fields:
- isvalid
- address
- type
- address_type (same as type)
- ismine - always false, because Zebra doesn't have a wallet

The `Address` enum added in [#6086](https://github.com/ZcashFoundation/zebra/pull/6086/files#diff-7f5d342981d90d652271da72fb36b58d1af35b1f92431d3dcc79a1113d0ad957) can be extended to convert shielded addresses as well for implementing this RPC.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6083?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is on the critical path for mining pool testing.

**Comment by upbqdn** [comment]
How do we know we don't have to implement the `diversifier` and `diversifiedtransmissionkey` fields described in the spec https://zcash.github.io/rpc/z_validateaddress.html?

**Comment by teor2345** [comment]
> How do we know we don't have to implement the `diversifier` and `diversifiedtransmissionkey` fields described in the spec https://zcash.github.io/rpc/z_validateaddress.html?

We don't support Sapling shielded coinbase yet (#5472), and those fields are only used for Sapling. So we could add those fields to the Sapling ticket, if they aren't already there?

**Comment by upbqdn** [comment]
Even though it's not stated in the spec, Zcashd checks unified addresses. Should we also support those?

**Comment by teor2345** [comment]
> Even though it's not stated in the spec, Zcashd checks unified addresses. Should we also support those?

Maybe as a separate ticket once the unified address PR #6171 merges?

**Comment by teor2345** [comment]
@upbqdn did you want to open that ticket so we don't forget? It doesn't need to be long, we can fill it in later.

**Comment by mpguerra** [comment]
yes, I'd rather not block testing and the release on unified addresses. We can add them in after.
