### ISSUE TITLE
CI getblocktemplate test is failing in `main` branch.

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6101]
I am not sure yet if it is always or sometimes. I also don't know if we already have a ticket to track this issue. Feel free to close it if so:

https://github.com/ZcashFoundation/zebra/actions/runs/4070984079/jobs/7033598748#step:8:226

**Comment by arya2** [comment]
This should be fixed by https://github.com/ZcashFoundation/zebra/pull/6091.

**Comment by oxarbitrage** [comment]
> This should be fixed by #6091.

Got it, thanks.
