### ISSUE TITLE
Upgrade zebra-script for the `zcashd` 5.4.0 release

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6107]
## Motivation

When `zcashd` 5.4.0 is released, we can upgrade the following dependency tree:
- zebra-script
    - zcash_script:
        - C++ code from zcashd
        - zcash_primitives 0.9 or 0.10
        - cxx 1.0.83

We might want to check that it compiles earlier, so we can remove any unnecessary `zcashd` dependencies or fix C++ compilation issues.

### Testing

We have existing CI tests for all this code.

## Related Work

We are upgrading Zebra's direct dependency on zcash_primitives to 0.10 in PR #6087.

**Comment by teor2345** [comment]
@mpguerra we might want to check that this upgrade works before ECC does their release, so we don't have to use forked versions of their crates or the `zcashd` code.

We don't have to do a full `zcash_script` release, just update the C++ code and dependencies and check it works. What do you think @conradoplg, is it worth it?

**Comment by conradoplg** [comment]
> @mpguerra we might want to check that this upgrade works before ECC does their release, so we don't have to use forked versions of their crates or the `zcashd` code.
> 
> We don't have to do a full `zcash_script` release, just update the C++ code and dependencies and check it works. What do you think @conradoplg, is it worth it?

I think it's worth it, yes. Usually it's simple until it's not :stuck_out_tongue:

**Comment by teor2345** [comment]
> Usually it's simple until it's not 😛

And I'd like to know that now while we can still ask them to fix things!

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6107?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
We missed doing this before the release, so there might be some bugs we can't fix until their next release.

It would be good to have 3 people in the team who can work with zcash_script.
Conrado and I understand this code, maybe we could help someone else work on it?
