### ISSUE TITLE
Add tracing to CheckpointVerifier

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#611]
> As a follow-on, it might be helpful (after this is merged) for us to go through and add tracing calls so that we can inspect it running.

@hdevalence  in https://github.com/ZcashFoundation/zebra/pull/524#pullrequestreview-444242349

In particular, we should instrument the target and progress functions, because they are the most complex.

**Comment by teor2345** [comment]
Blocked by #582.

**Comment by dconnolly** [comment]
@teor2345 put a lot of tracing into the checkpoint verifier service so this particular issue is closed.
