### ISSUE TITLE
Create a Docker images and docker-compose for mining with Zebra on Testnet

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6118]
## Motivation

We could make it easier for people to try mining with Zebra on Testnet by publishing a Docker image.

This would also make it easier to add a manually dispatched workflow to our CI for testing mining pool support.

## Design

Collect all of the steps for starting s-nomp and nheqminer [zebra-instructions](https://github.com/ZcashFoundation/s-nomp/blob/zebra-mining/zebra-instructions.md) into Dockerfile(s).

Add a docker-compose file for starting zebra-mining-rpcs-testnet, redis, s-nomp, and nheqminer. (Exclude zebra-mining-rpcs-testnet from docker-compose so the rest of the instances can be spun up after the testnet sync?)

## Timing

We're going to limit this ticket to 2 days of work, because it won't be usable in production. (We had to disable parts of `s-nomp` because it doesn't support NU5.)

**Comment by teor2345** [comment]
This might have a lot of overlap with ticket #6025, can you update its ticket description to mention this ticket?

**Comment by teor2345** [comment]
Is this a low priority or optional ticket?

**Comment by mpguerra** [comment]
If we do a "How to mine using s-nomp and Zebra on testnet"  blogpost we would ideally provide the docker image already so I feel like this is potentially a blocker for finishing off #6028. However, we may decide that the instructions on there are good enough.

**Comment by arya2** [comment]
> Is this a low priority or optional ticket?

I think it's a should-have and medium priority so it can be included in the Zebra book.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6118?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This has a lot of overlap with #6200, we might want to make that Docker image first. I'll try to do that today.

**Comment by teor2345** [comment]
@arya2 @mpguerra do we need to implement this ticket? Have any users asked for it?

`s-nomp` doesn't support generating its own NU5 coinbase transactions, so I'm not sure if we would want to create a Docker image that uses `s-nomp`. And I'm not sure if testnet images are useful to our users.

**Comment by arya2** [comment]
> @arya2 @mpguerra do we need to implement this ticket? Have any users asked for it?


I don't think it's worthwhile anymore.
