### ISSUE TITLE
Fix "duplicate transparent spend" caused by mempool validation race condition

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6132]
## Motivation

In an unrelated PR, block proposal validation failed with:
> Message:  block proposal validation failed: 
> 0: unsuccessful block proposal validation, reason: "block-source-validateproposal-commitblockerror-duplicatetransparentspend-outpoint-outpoint-hash-transaction-hash-20d2422d07a5b168e9a6d7d60f8d7eadc89f270ccce6ca984081d1f4c4258e07-index-111-location-the-non-finalized-chain"

https://github.com/ZcashFoundation/zebra/actions/runs/4131129255/jobs/7138887361#step:8:210

### Specifications

The consensus rules say that each transparent output must only be spent once in each chain. This should already be implemented in the mempool.

### Complex Code or Requirements

This bug needs further investigation: we won't know how complex it is until we know why.

### Testing

We might want to add a unit test for this rare scenario, because the existing unit and integration tests aren't catching it.

## Related Work

This likely blocks the next Zebra release, because we can't have miners test on `mainnet` with this bug.

**Comment by teor2345** [comment]
@mpguerra I think this mining bug might block mining pool testing.

**Comment by arya2** [comment]
That's strange .. I would think the transaction verifier should reject it here: 
https://github.com/ZcashFoundation/zebra/blob/remove-duplicate-chain-fields/zebra-consensus/src/transaction.rs#L546

That state request checks `spent_utxos` here: 
https://github.com/ZcashFoundation/zebra/blob/remove-duplicate-chain-fields/zebra-state/src/service/read/block.rs#L155

That error seems to be from that same check failing here: 
https://github.com/ZcashFoundation/zebra/blob/remove-duplicate-chain-fields/zebra-state/src/service/check/utxo.rs#L146

And it can't be that the best chain tip changed because it would've failed when checking that the previous block hash is the best chain tip hash before checking for duplicate spends.

Perhaps it verified the transaction right before a chain tip change and inserted it into the mempool right after the call to `reject_and_remove_same_effects()`?

**Comment by teor2345** [comment]
> Perhaps it verified the transaction right before a chain tip change and inserted it into the mempool right after the call to `reject_and_remove_same_effects()`?

Oh yeah, that seems like a concurrency bug in the mempool.

Here's one possible fix:
- store chain tip hash at the start of each mempool transaction verification
- return it to the mempool in the response
- when inserting, if the chain tip hash from the verification is different to the chain tip hash now, re-verify the transaction

This is a rare edge-case, so it's ok to do the extra work of re-verifying the transaction.

**Comment by teor2345** [comment]
This doesn't happen for block transactions, because we re-check spends based on the previous transaction in each chain in the state.

**Comment by arya2** [comment]
> Here's one possible fix:
> 
> * store chain tip hash at the start of each mempool transaction verification
> * return it to the mempool in the response
> * when inserting, if the chain tip hash from the verification is different to the chain tip hash now, re-verify the transaction

It could also return and check the height since transactions are re-verified when there's a `TipAction::Reset`.

**Comment by teor2345** [comment]
> > Here's one possible fix:
> > 
> > * store chain tip hash at the start of each mempool transaction verification
> > * return it to the mempool in the response
> > * when inserting, if the chain tip hash from the verification is different to the chain tip hash now, re-verify the transaction
> 
> It could also return and check the height since transactions are re-verified when there's a `TipAction::Reset`.

I'm not sure heights will work, here's an example of an incorrect verification and insert:
1. A transaction gets verified against tip hash A, then is waiting to be put into the insert queue
2. A Reset from tip hash A to B is processed by the mempool, where A and B are at the same height
3. The transaction is put in the insert queue and inserted into the mempool

A "verified against hash" check will correctly re-verify the transaction, but a height check wouldn't.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6132?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by arya2** [comment]
> A "verified against hash" check will correctly re-verify the transaction, but a height check wouldn't.

It shouldn't need to if the whole state with pending verifications are dropped for the reset (I'll make sure to test this and leave a note on correctness, it should be easy to switch to using the hash if I've misunderstood):

https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/mempool.rs#L335

Though I think it needs to call `last_tip_change` again after checking for verified transactions in `pending` in case a reset happens during `poll_ready` execution after the first call to `last_tip_change`.

**Comment by teor2345** [comment]
> It shouldn't need to if the whole state with pending verifications are dropped for the reset (I'll make sure to test this and leave a note on correctness, it should be easy to switch to using the hash if I've misunderstood):

I think you're right, we'd re-verify all the transactions in that case.

I have a preference for using the obviously correct identifier, so it's harder for future refactors or changes to break it. But the tests should ensure it doesn't get broken accidentally.

**Comment by teor2345** [comment]
> Though I think it needs to call `last_tip_change` again after checking for verified transactions in `pending` in case a reset happens during `poll_ready` execution after the first call to `last_tip_change`.

Hmm, this seems like the kind of scenario that needs a loom test, but that's not something we have right now.

Would a hash solve this particular edge case, or does it have the same issue as a height?

**Comment by arya2** [comment]
> Would a hash solve this particular edge case, or does it have the same issue as a height?

It would have the same issue as height, it would work when the hash changes after the call to `last_tip_change()` but before getting the best tip hash to check against the verified transactions, but not if the tip changes while verified transactions are being inserted.

**Comment by teor2345** [comment]
> > Would a hash solve this particular edge case, or does it have the same issue as a height?
> 
> It would have the same issue as height, it would work when the hash changes after the call to `last_tip_change()` but before getting the best tip hash to check against the verified transactions, but not if the tip changes while verified transactions are being inserted.

Ah right so we have to check before and after? Let me check how that looks in the PRs.
