### ISSUE TITLE
Publish zebra crates to crates.io

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6149]
## Motivation

Once the code is audited and we do our first stable release, we will want to publish zebra to crates.io.

## Instructions

https://doc.rust-lang.org/cargo/reference/publishing.html#before-publishing-a-new-crate

In particular, we'll want to include the Zcash Foundation in the crate description and homepage, and "Zcash" in the crate keywords.

## Crates that need to be published

- [x] [`tower-batch-control`](https://crates.io/crates/tower-batch-control) (was renamed in #6202)
- [x] [`tower-fallback`](https://crates.io/crates/tower-fallback)
- [x] [`zebra-chain`](https://crates.io/crates/zebra-chain)
- [x] [`zebra-consensus`](https://crates.io/crates/zebra-consensus)
- [x] [`zebra-network`](https://crates.io/crates/zebra-network)
- [x] [`zebra-node-services`](https://crates.io/crates/zebra-node-services)
- [x] [`zebra-rpc`](https://crates.io/crates/zebra-rpc)
- [x] [`zebra-script`](https://crates.io/crates/zebra-script)
- [x] [`zebra-state`](https://crates.io/crates/zebra-state)
- [x] [`zebrad`](https://crates.io/crates/zebrad)

Testing and developer tools:
- [x] [`zebra-utils`](https://crates.io/crates/zebra-utils)
- [x] [`zebra-test`](https://crates.io/crates/zebra-test)

## Reserved Crate Names

We have already reserved these crate names on crates.io.

<details>

We can, to just get the crate names, do local renames of `zebra-cli` to each one, publish, and so forth, for now.

These placeholders are now co-owned by @ZcashFoundation/owners (https://crates.io/teams/github:zcashfoundation:owners?sort=new): 

- [x] `tower-batch-cpu` (https://crates.io/crates/tower-batch-cpu)
- [x] [`tower-fallback`](https://crates.io/crates/tower-fallback)
- [x] [`zebra-chain`](https://crates.io/crates/zebra-chain)
- [x] [`zebra-cli`](https://crates.io/crates/zebra-cli) 
- [x] [`zebra-consensus`](https://crates.io/crates/zebra-consensus)
- [x] [`zebra-network`](https://crates.io/crates/zebra-network)
- [x] [`zebra-node-services`](https://crates.io/crates/zebra-node-services)
- [x] [`zebra-rpc`](https://crates.io/crates/zebra-rpc)
- [x] [`zebra-script`](https://crates.io/crates/zebra-script)
- [x] [`zebra-state`](https://crates.io/crates/zebra-state)
- [x] [`zebra-test`](https://crates.io/crates/zebra-test)
- [x] [`zebra-utils`](https://crates.io/crates/zebra-utils)
- [x] [`zebrad`](https://crates.io/crates/zebrad) (and https://crates.io/crates/zebra)

</details>

**Comment by mpguerra** [comment]
Do we want to squat and publish the other crates, e.g zebra-network, etc... to crates.io?

**Comment by teor2345** [comment]
> Do we want to squat and publish the other crates, e.g zebra-network, etc... to crates.io?

We have to publish all our production crates to crates.io, because it won't accept a crate unless its dependencies are also published:
- We will need to rename `tower-batch`, because it [already exists](https://crates.io/crates/tower-batch), and does something different (file writing batches, not cryptography batches)

I don't mind if we squat or publish our test crates, it's probably easier just to publish them.

`zebra-client` is currently a placeholder, but we should add a README saying that.

**Comment by teor2345** [comment]
Do we also want to publish a placeholder for `zebra-cli`? Or are we going to use `zebrad` as the `zebra-cli` instead?

(It seems simpler, but if we publish a placeholder, we can leave that decision for later.)

**Comment by teor2345** [comment]
We might not be able to publish `zebra-test` due to the 10 MB crates.io size limit (our test data is close to that size):
https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate

If we can't, we should still publish a placeholder.

**Comment by mpguerra** [comment]
@dconnolly has been working on this. I'm hoping we can finish this off during next sprint (2023 Sprint 8)

**Comment by teor2345** [comment]
@mpguerra should this be blocked by renaming `tower-batch` in #6202?

**Comment by mpguerra** [comment]
Now that we have the placeholders we can wait to publish the actual crates until we tag the stable release

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6149?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@dconnolly I split up the list of crates into crates that need to be published for the `zebrad` release, and everything else.

I think for our first step we might just want to publish the `zebrad` crates.

**Comment by teor2345** [comment]
I removed the empty crates from the list because PR #6726 deletes them.
