### ISSUE TITLE
actions: use a name convention for workflow files/names

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#6166]
## Motivation

We'd like to standardize the way the workflows are named, and align their names with what's actually being executed inside the workflow.

### Specifications

When we do the redesign of Zebra CI, can we use a naming standard for workflow files?
For example, we could name them something like: `(purpose)-(when they run)-(where they run)-(what they do)-(patch?).yml`

So we'd end up with names like:
- `sub-build-docker-image.yml`
- `ci-pr-gcp-continuous-integration-test-docker.yml`
- `ci-pr-gh-continuous-integration-test-os.yml`
- `cd-release-gcp-continuous-delivery-deploy-docker.yml`

**Comment by teor2345** [comment]
hmm, we might want the first one to be `ci-sub`, I'll tweak that.
