### ISSUE TITLE
actions: segregate workflows based on their purpose

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#6167]
## Motivation

Some workflows have different requirements like resources, time and dependencies, and even have jobs with different objectives (in some cases, not related to other workflow jobs).

### Specifications

If multiple workflows require the same setup, this should be split into a dependable workflow which sets all the information of the following workflows. And if this workflows are not dependable on each other or have different objectives, those should also live in their own workflow files.

Sometimes we require to restart a specific workflow, which also triggers a whole dependency tree which makes re-running time consuming and almost as similar as depending on all previous workflows if there's a false/positive.

### Complex Code or Requirements

- We can't make a dependable workflow depend on another dependable workflow
- Reduce workflow nesting as much as possible
- Be able to cancel specific time consuming jobs without affecting other jobs which ran successfully
- Resource intensive workflows/jobs should be split apart if other workflows don't have this resource heavy requirements

**Comment by teor2345** [comment]
> * Be able to cancel specific time consuming jobs without affecting other jobs which ran successfully
> 
> * Resource intensive workflows/jobs should be split apart if other workflows don't have this resource heavy requirements

Yep, this is the main thing that's annoying for us as developers.

Another thing that might be helpful is disabling failing jobs until we can do a proper fix, which we can only do in the Actions web interface on a workflow level. Jobs with similar requirements that test similar areas usually fail together.
