### ISSUE TITLE
docker: move the default configuration file outside the Dockerfile

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#6170]
## Motivation

We don't want to hardcode how Zebra is configured by default (differently than what's expected in the source code). We should handle this in a separate layer as the `entrypoint`, and build the file on the fly for those who require to change the configuration on each run, without having to rebuild

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6170?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn @gustavovalverde

**Comment by teor2345** [comment]
@gustavovalverde I think this was already completed in PR #6842, the current config generation script is:
https://github.com/ZcashFoundation/zebra/blob/main/docker/runtime-entrypoint.sh

Is there anything left to do in this ticket?

This is an estimation blocker.

**Comment by mpguerra** [comment]
this is done
