### ISSUE TITLE
Simplify `z_listunifiedreceivers` RPC implementation

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6190]
After https://github.com/ZcashFoundation/zebra/pull/6185 the `z_listunifiedreceivers` rpc method can be simplified by the use of  `try_from_unified`  function that properly parses UAs into individual addresses, and checks their validity as well.

**Comment by teor2345** [comment]
Here are some other optional changes we could make after PR #6185 merges:
* unified payment address encoding implementation: https://github.com/ZcashFoundation/zebra/pull/6171#discussion_r1109176473
* move the unified to specific address conversions into the `Address` type: https://github.com/ZcashFoundation/zebra/pull/6171#discussion_r1109176983

**Comment by teor2345** [comment]
Also we might want to update is_transparent and is_script_hash

**Comment by teor2345** [comment]
Here are some follow-ups from z_validateaddress:
https://github.com/ZcashFoundation/zebra/pull/6185#pullrequestreview-1306247303

The future compatibility bug has a separate ticket #6193.
