### ISSUE TITLE
Fix future compatibility of address RPCs with unknown unified receivers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6193]
## Motivation

Unknown unified receivers are valid according to the spec, but Zebra's RPCs reject them.

Unified addresses are designed to be forwards-compatible, so new or experimental receiver types can be added at any time. In this case, we can ignore them because the RPC doesn't have fields for them.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/6185#discussion_r1112266164_

### Specifications

> Every Wallet must properly parse a Unified Address or Unified Viewing Key containing unrecognized Items.
> A Wallet may process unrecognized Items by indicating to the user their presence or similar information for usability or diagnostic purposes.
> ...
> When executing a Transfer the Sender selects a Receiver via a Selection process.
> Given a valid UA, Selection must treat any unrecognized Item as though it were absent.
> This property is crucial for forward compatibility to ensure users who upgrade to newer protocols / UAs don't lose the ability to smoothly interact with older wallets.

https://zips.z.cash/zip-0316#receivers

### Complex Code or Requirements

ZIP-316 is reasonably complex, but this particular bug is not consensus-critical. (It causes an error, not a consensus split.)

### Testing

We don't have test vectors for this yet, and it might not be worth the effort of creating them.

## Related Work

Follow up to:
- #6185

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6193?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
unscheduling for now
