### ISSUE TITLE
Publish Docker image with mining enabled

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6200]
## Motivation

We'd like to provide an easy way for miners to test their own mining software with Zebra.

The required changes in the Dockerfile are:
- Compile with `--features getblocktemplate-rpcs`
- Enable the testnet RPC port in the default config, and change the network to testnet
- Expose the port in the Docker image

And in the workflows:
- Publish this Docker image to DockerHub with every release, named something like `zebra-mining-rpcs-testnet-v1.0.0-rc.5.experimental`

### Testing

We can run this image using the Docker commands in the readme, and connect to its RPC port using `zcash-cli`.

We'll be asking mining pools to test this.

## Related Work

This is a much smaller task than:
- #6118

**Comment by teor2345** [comment]
This is how to use a docker `ARG` to change commands:
https://stackoverflow.com/questions/37057468/conditional-env-in-dockerfile

We can add new command arguments or config file lines using shell parameter expansion:
https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html

**Comment by mpguerra** [comment]
Let's timebox this to 1 day and not carry it over to Sprint 5. If we have a lot of demand for it we can pick this up again in Sprint 6.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate here also?

**Comment by teor2345** [comment]
I don't know if any mining pools that want this yet, but we're still waiting for some to get back to us.

**Comment by teor2345** [comment]
I didn't end up having time to do this today.
