### ISSUE TITLE
Implement custom Debug trait for CommitBlockError

### ISSUE THREAD

**Issue by dimxy** [ZcashFoundation/zebra#6218]
## Motivation
For CommitBlockError tuple the default implementation for Debug is used now so with statements like `println!("{:?}, err);` there is no formatted error description is printed for the base ValidateContextError but only the error parameters.
Suggestion is to implement the std::fmt::Debug trait for CommitBlockError which would also print expanded ValidateContextError, like:
```
impl std::fmt::Debug for CommitBlockError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "CommitBlockError(\"{}\": ValidateContextError(\"{}\"))", self.to_string(), self.0.to_string())
    }
}
``` 
Or maybe we could use debug_tuple with the formatted ValidateContextError field as well.

**Comment by teor2345** [comment]
Can you give an example of how the log looks now, and how you'd like it to look?
Or would you like to submit a PR?

**Comment by dimxy** [comment]
Here is how I have it printed with println!("commit_result={}", commit_result):
```
commit_result=block is not contextually valid
```
I believe users would expect the nested ValidateContextError error description printed here:
```
commit_result="block height 12 is lower than the current finalized height 127"
```
I studied more rust docs and I think I found a standard way to improve this:
it's either just a forward CommitBlockError error message to the underlying error with `#[error(transparent)]` attribute or extend CommitBlockError with the underlying error Display results: `#error("block is not contextually valid: {}", .0)`.
Yes I'll suggest a PR for that.
