### ISSUE TITLE
reimplement `zcash_script` in rust

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#623]
Our short term plan for getting a consensus compatible zcash-script implementation is to depend on the implementation currently used in `zcash` (https://github.com/ZcashFoundation/zebra/issues/622). However, long term we would like to avoid depending on c++ code as much as possible. Additionally, the c++ build system may impose new restrictions on what platforms we can support.

To defend against these issues we should also create a rust reimplementation of `zcashconsensus`. We will still prefer to use the same zcash-script implementation that is used by `zcash` to avoid bugs causing issues with consensus, but long term we may wish to eventually switch both `zebrad` and `zcashd` from the `zcashconsensus` c++ implementation over to our rust reimplementation.

**Comment by conradoplg** [comment]
Closing since decided to keep using `zcash_script` for now
