### ISSUE TITLE
Upgrade to Orchard and zcash_primitives versions with the nightly Rust (1.69) fix before 20 April

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6232]
## Motivation

To fix Orchard verification errors in Rust 1.69 (currently nightly), we need to upgrade to a fixed Orchard version:
https://github.com/zcash/halo2/issues/737

We also need to upgrade every other ECC dependency that depends on `orchard` and `halo2`, including:
- `zcash_primitives`
- see the PR

## Deadline

Rust 1.69 will be released as stable on Thursday 20 April, so we need to merge and release this fix before then:
https://releases.rs/

### Complex Code or Requirements

We need to upgrade Zebra's `orchard` dependency, and make sure none of these dependencies use the older Orchard version:
- `librustzcash`

We also need to update the rest of the ECC dependencies at the same time, to avoid duplicate dependencies.

### Testing

- [x] Re-enable the disabled `verify_generated_halo2_proofs` test to make sure the upgrade worked.

## Follow Up Work

Update `zcash_script` to remove duplicate dependencies:
- #6535

**Comment by mpguerra** [comment]
We should also remember to turn the related test that is failing on nightly back on (assuming that we have turned it off)

**Comment by mpguerra** [comment]
The 5.5.0 release which should include this fix is tentatively planned for 3 - 4 weeks from now

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6232?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Orchard 0.4 has not been released yet, check this page for updates: https://crates.io/crates/orchard

**Comment by teor2345** [comment]
This is now unblocked, `orchard` 0.4.0 has just been released:
https://github.com/ZcashFoundation/zebra/pull/6479

**Comment by teor2345** [comment]
Oh, we also need to wait for the next `zcash_primitives` release, it should be 0.11.0:
https://github.com/zcash/librustzcash/tags

**Comment by teor2345** [comment]
I split #6535 out of this ticket as discussed, because we don't need to upgrade `zcash_script` in the same release.
