### ISSUE TITLE
Spec check: Zcash protocol messages 2 MB limit

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#624]
`zcashd` limits encoded and decoded bitcoin protocol messages to 2 MB (2 * 1024 * 1024 bytes):
https://github.com/zcash/zcash/blob/caea54013e8df02a9d9424d6496eb1ac6af069e2/src/net.h#L50

## TODO

Check if the `zcashd` limit is an implementation detail, or a missing consensus rule in the spec.

## Completed Work

Currently, Zebra uses a ~4 million~ 2 MB limit for inbound messages~, and doesn't limit outgoing messages~:
* max_len setting: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/protocol/external/codec.rs#L53
* inbound check: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/protocol/external/codec.rs#L314
* no outbound check: https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/protocol/external/codec.rs#L104

We currently match zcashd, and we added some tests.

**Comment by teor2345** [comment]
@oxarbitrage you might be interested in this ticket?

**Comment by hdevalence** [comment]
Is this a consensus rule, or just network behavior?

**Comment by teor2345** [comment]
It's a zcashd limit, which isn't in the spec.

So either it's an unwritten consensus rule which needs a spec update, or an implementation detail. We won't know which until we try to add it to the spec :-)

**Comment by teor2345** [comment]
Closed by #645.

**Comment by teor2345** [comment]
We might actually want to add this to the spec, or get confirmation that it's an implementation detail of zcashd

**Comment by teor2345** [comment]
We got this sorted a while ago.
