### ISSUE TITLE
Create a Zebra package in the Arch User Repository (AUR)

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#6243]
## Motivation

Arch is a common distro and having a package in the AUR makes it trivial to install Zebra. `zcashd` has a package in the _community_ repository, and Zebra will hopefully follow. Note that the _community_ repository has a higher level of trust than the AUR and the Zebra package will have to earn this trust in order to be promoted. More info can be found here https://wiki.archlinux.org/title/Arch_User_Repository.

**Comment by upbqdn** [comment]
Note that the estimate of this issue might be exaggerated.

**Comment by mpguerra** [comment]
I think once we write a blog post about it we can close this one off. Can start off the blogpost with reasons for working on this, why an Arch linux package, how to create one and then finally all the details for the specific zebra one with a call to action to try it out and upvote.

**Comment by mpguerra** [comment]
this was done
