### ISSUE TITLE
Add Rkyv deserialization/serialization for RPC method requests/responses

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6246]
### Motivation

Providing a rkyv RPC interface should offer better performance than JSON-serialization and some additional type-safety.

> [[rkyv](http://github.com/rkyv/rkyv)](http://github.com/rkyv/rkyv) (*archive*) is a zero-copy deserialization framework for rust.

Request and response types can be exported from `zebra-rpc` so that the validity of RPC requests can be checked by rustc.

### Possible Design

- Add a `rkyv_serialization` feature to `zebrad`, `zebra-rpc` and `zebra-chain`

When the feature is enabled:

- Add a `rkyv_listen_addr` field to the config
- Listen for requests with `hyper` or `axum`
- Map deserialized requests to `RpcImpl` or `GetBlockTemplateRpcImpl` methods
- Serialize responses with `rkyv`
- Export request/response types from `zebra-rpc`

Optional: 

- Add a `subscribe-getblocktemplate` method that opens a WebSocket for sending new block templates

### Testing

- Add  `rkyv_serialization` feature to CI coverage matrix
- Add the new config to test configs
- Snapshot tests

### Benchmarks

- Add benchmarks to measure performance differences for key RPC methods

**Comment by mpguerra** [comment]
@arya2 is this for Sprint 5? :) just so I can add it in if so
