### ISSUE TITLE
Make checkpoint list re-use clearer in multi_item_checkpoint_list test

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#626]
I want to fix these comments so they're clearer:
https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/checkpoint.rs#L838

**Comment by yaahc** [comment]
fwiw I feel like that comment is pretty clear as is, but maybe that's only because I have context...

**Comment by teor2345** [comment]
It's already confused at least one person, so I'll improve it.
