### ISSUE TITLE
Write script to find TODOs mentioning closed github issues

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6278]
##  Motivation

There are a number of `TODO` comments in the code which refer to issues which have already been closed. 

In order to get a full list of all of these comments and issues, we are going to try to write some scripting that finds `TODO`s that mention github issues that have been closed and update the list in #6281.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6278?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by conradoplg** [comment]
A reference: https://github.com/ZcashFoundation/developers/blob/main/zcash-issue-dag.py has code to check if an issue has been closed or not
