### ISSUE TITLE
[NCC-E005955-XVE] `zebra-chain`: Inconsistent error management in `Add` and `Sub` for `Height`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6279]
## Motivation

We want to track all of the findings from the zebra audit.

## Details

Some arithmetic operations for `Height` are implemented in [zebra-chain/src/block/height.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-chain/src/block/height.rs#L68-L100) for both `Height` and `i32`

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-chain/src/block/height.rs#L68-L100

The `Add` function handles overflow with an `Option` , but `Sub` will panic. The `Sub` function later in the file for `i32` subtraction returns an `Option` as well, making the panic behavior an outlier. Panics should be used as a last resort, when there is no possibility of recovery. Otherwise, an attacker may attempt to intentionally trigger a panic as part of a denial-of-service attack. Additionally, the `Sub` function **does not** enforce the same constraint checks shown on Line 73 above, unlike the other functions in the same file.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6279?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> The `Add` function handles overflow with an `Option` , but `Sub` will panic. The `Sub` function later in the file for `i32` subtraction returns an `Option` as well, making the panic behavior an outlier.

We don't think this panic is possible with valid `Height`s, due to the range of the data types involved:
https://github.com/ZcashFoundation/zebra/pull/6330#issuecomment-1475550868

 However, since some code (particularly RPC code) might construct invalid heights, we're going to do some fixes anyway.

> Additionally, the `Sub` function **does not** enforce the same constraint checks shown on Line 73 above, unlike the other functions in the same file.

The output type is not a `Height`, it's the difference between two heights. So the height range limits do not apply. But we'll make some fixes to make this clearer.

**Comment by mpguerra** [comment]
Do we need to review the estimate on this one? Seems like it ended up being bigger than a "size 2" issue. I don't necessarily want us to actually change the estimate retroactively but it might be interesting to discuss during the retro :)

**Comment by teor2345** [comment]
This refactor has already helped me discover a potential bug in my progress bar code.
