### ISSUE TITLE
Add 'confirmations' field to `getrawtransaction` RPC

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6286]
## Motivation

Mining pools may need a way to see the confirmation progress for a particular transaction.

## Specifications

https://zcash.github.io/rpc/getrawtransaction.html

Zebra needs to return the `confirmations` field.

## Design

- Return `confirmations: 1 + latest_chain_tip_height - transaction_block_height` if the transaction is in the state

**Comment by mpguerra** [comment]
@arya2 can you please add an estimate here?
