### ISSUE TITLE
Enable disabled `verify_generated_halo2_proofs` test

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6288]
## Motivation

This test was disabled as it was failing. See #6232 for more details.

### Specifications

 Once #6232 is closed we should re-enable the `verify_generated_halo2_proofs` test

**Comment by teor2345** [comment]
I don't think it makes sense to track this issue separately from #6232, because we need to re-enable this test to make sure the dependency update actually worked.

I've added this step to the testing part of that ticket.
