### ISSUE TITLE
Bump bitflags from 1.3.2 to 2.0.0

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6326]
## Motivation

This is a breaking dependency upgrade. See: https://github.com/ZcashFoundation/zebra/pull/6305#pullrequestreview-1341242949

**Comment by oxarbitrage** [comment]
This upgrade has a bunch of problems: https://github.com/bitflags/bitflags/issues/310

I tried to fix it in our end with some experiences other people are having but i was not able to make it work yet. 

I am unsure if they will make a new minor update to fix some. Ill know more soon as i will investigate it further.

**Comment by oxarbitrage** [comment]
I crated an issue in the `bitflags` repo. Lets see how it goes.

https://github.com/bitflags/bitflags/issues/314

**Comment by oxarbitrage** [comment]
`bitflags` bumped a new version 2.0.1 where they explain better what changes are needed. 

I made the needed changes to support the upgrade in https://github.com/ZcashFoundation/zebra/pull/6346

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6326?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
Fixed by PR #6346.
