### ISSUE TITLE
[NCC-E005955-NQ6] `zcash_proofs`: Theoretical possibility of overflow leading to panic (Copy of zcash/librustzcash#786)

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6327]
This issue mirrors zcash/librustzcash#786 in order to allow us to track it in Zenhub

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6327?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This seems like a low priority because it can't happen with the current parameter sizes, and we don't plan on adding new downloadable parameters ever again.

**Comment by mpguerra** [comment]
Done in zcash/librustzcash#805
