### ISSUE TITLE
GCloud Builds fail via GitHub App Integration

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#634]
Since we merged #614, every merge to main shows a "failed" (red x) status on GitHub:
https://github.com/ZcashFoundation/zebra/commits/main

Here is the error message:
```
invalid argument "gcr.io/zealous-zebra/zcashfoundation//:e0a71c2" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 125
--------------------------------------------------------------------------------

##[error]Process completed with exit code 1.
```
https://github.com/ZcashFoundation/zebra/runs/855181580

**Comment by dconnolly** [comment]
This has been fixed in https://github.com/ZcashFoundation/zebra/pull/637
