### ISSUE TITLE
[NCC-E005955-WVM] `zebra-consensus`: Off-by-One Errors and Inconsistent Usage of `PARAMETER_DOWNLOAD_MAX_RETRIES`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6340]
## Impact

The `PARAMETER_DOWNLOAD_MAX_RETRIES` may not behave as expected due to a potential off-by-one error.

## Description

The parameter `PARAMETER_DOWNLOAD_MAX_RETRIES` is defined in [zebra-consensus/src/
primitives/groth16/params.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-consensus/src/primitives/groth16/params.rs):

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L18-L22

As noted, this parameter represents the number of times to retry the download of groth16 parameters. However, later in the same file the following description is given:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L63-L70

Here, the parameter is claimed to specify the number of download attempts, not the number of _retry_ attempts. The implementation matches the described behavior and uses this parameter to cap the total number of download attempts; see `retry_download_sapling_parameters()` :

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L132-L144

The same behavior is implemented for `retry_download_sprout_parameters()` . Documentation for both of these functions is inconsistent:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L120-L125

For example, consider a case where `PARAMETER_DOWNLOAD_MAX_RETRIES` = 1 . Then this
comment specifies the following: 

1. “Download Sapling parameters and retry 1 if it fails.” – This should likely read “1 time(s)” if it fails (currently missing the word “time”). This description matches the implied behavior based on the parameter name.
2. Panics “After 1 failed download attempts” – In other words, it will not retry 1 time. This description matches the implemented behavior.

For consistency, the parameter should be uniformly treated as the maximum number of download attempts, or the maximum number of retry attempts, and treated appropriately in all documentation and code.

## Recommendation

Revise documentation, parameter names, and implemented behavior to correctly capture the behavior of `PARAMETER_DOWNLOAD_MAX_RETRIES`.

## Location

[zebra-consensus/src/primitives/groth16/params.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-consensus/src/primitives/groth16/params.rs)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6340?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This seems like a low priority, given the impact of the issue.
