### ISSUE TITLE
Code duplication between `reddsa` and `redjubjub`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6341]
## Details

The [`redjubjub` crate](https://github.com/ZcashFoundation/redjubjub/tree/0.5.0) implements the RedDSA signature scheme over the Jubjub curve.
The [`reddsa` crate](https://github.com/ZcashFoundation/reddsa/tree/0.4.0) mostly subsumes that task and provides RedDSA support for both the Jubjub and Pallas curves; the migration of the code from `redjubjub` to `reddsa`, and its
generalization to unify support over distinct elliptic curves, are currently in an incomplete state, resulting in some code duplication. Thus, there are currently (at least) three mostly identical implementations of the multiplication of a curve point by a scalar with the w-NAF method, in [redjubjub/src/scalar_mul.rs](https://github.com/ZcashFoundation/redjubjub/blob/e19279f70f3999627b4076386848d1956b18560e/src/scalar_mul.rs#L62), [reddsa/src/scalar_mul.rs](https://github.com/ZcashFoundation/reddsa/blob/507dcdf695bbc7eccd5d6b8e3c0d62625a45e4e9/src/scalar_mul.rs#L67), and [reddsa/src/orchard.rs](https://github.com/ZcashFoundation/reddsa/blob/507dcdf695bbc7eccd5d6b8e3c0d62625a45e4e9/src/orchard.rs#L86). In all three cases, the input scalar is converted to a w-NAF representation over exactly 256 digits:

<img width="859" alt="Screenshot 2023-03-16 at 15 04 06" src="https://user-images.githubusercontent.com/1311133/225641980-83b96394-159a-437c-b58d-30a7108a35fa.png">

https://github.com/ZcashFoundation/redjubjub/blob/e19279f70f3999627b4076386848d1956b18560e/src/scalar_mul.rs#L66-L70

<img width="859" alt="Screenshot 2023-03-16 at 15 05 53" src="https://user-images.githubusercontent.com/1311133/225642479-86cb17b4-2fb3-4a40-866b-c08fb26755d2.png">

https://github.com/ZcashFoundation/reddsa/blob/507dcdf695bbc7eccd5d6b8e3c0d62625a45e4e9/src/scalar_mul.rs#L73-L77

<img width="859" alt="Screenshot 2023-03-16 at 15 06 17" src="https://user-images.githubusercontent.com/1311133/225642576-aa58f753-a8df-469d-93e3-89cec26091a9.png">

https://github.com/ZcashFoundation/reddsa/blob/507dcdf695bbc7eccd5d6b8e3c0d62625a45e4e9/src/orchard.rs#L90-L94

The w-NAF representation converts an input value `x` into signed digits, using a window width `w` (expressed in bits), with the following characteristics:

- Each digit is either zero, or an odd signed integer between -2<sup>w-1</sup> and +2<sup>w-1</sup>.
- Between any two non-zero digits, there are at least `w` digits of value zero.
- n+1 output digits are sufficient to represent all possible `x` such that 0 ≤ x < 2<sup>n</sup> + 2<sup>n-w</sup>.

The `non_adjacent_form()` function requires that the window width `w` lies between 2 and 8.
The use of 256 digits is then slightly wasteful for the Jubjub and Pallas curves, where scalars are lower than the prime (sub)group order of interest:

- Jubjub order is about 2<sup>251.85</sup>, and thus needs only 253 digits at most for w-NAF.
- Pallas order is slightly below 2<sup>254</sup> + 2<sup>125.1</sup>, leading to a maximum w-NAF scalar size of 255 digits.

Since the number of iterations in the multiplication loop is exactly [equal to the number of digits](https://github.com/ZcashFoundation/reddsa/blob/507dcdf695bbc7eccd5d6b8e3c0d62625a45e4e9/src/orchard.rs#L185), and each iteration includes at least a curve point doubling, then some of these doublings are wasted (they will repeatedly double the initial value of the accumulator point, i.e. the curve identity point). On the other hand, if the `non_adjacent_form()` and `optional_multiscalar_mul()` functions are turned into generic functions that handle arbitrary curves whose scalars fit on 32 bytes, then 256 digits are not enough: a curve whose order is greater than 2<sup>255</sup> +2<sup>247</sup> (e.g. secp256k1, or NIST’s P-256) may need up to 257 digits for its scalars in w-NAF representation.

**Comment by teor2345** [comment]
Is this resolved by the latest versions of each of these crates?

**Comment by teor2345** [comment]
> Thus, there are currently (at least) three mostly identical implementations of the multiplication of a curve point by a scalar with the w-NAF method, in [redjubjub/src/scalar_mul.rs](https://github.com/ZcashFoundation/redjubjub/blob/e19279f70f3999627b4076386848d1956b18560e/src/scalar_mul.rs#L62),

As of `redjubjub` 0.7, the first duplicate implementation has been removed. The duplicates within `reddsa` still remain.

**Comment by upbqdn** [comment]
> As of redjubjub 0.7, the first duplicate implementation has been removed.

Nitpick: the duplicate implementation was removed in 0.6.

**Comment by upbqdn** [comment]
The description of the issue says:
> Between any two non-zero digits, there are at least `w` digits of value zero.

I think this statement contains an off-by-one error. The correct number of zero digits should be `w-1` since in a w-NAF, at most one of any `w` consecutive digits is nonzero.

**Comment by conradoplg** [comment]
> The description of the issue says:
> 
> > Between any two non-zero digits, there are at least `w` digits of value zero.
> 
> I think this statement contains an off-by-one error. The correct number of zero digits should be `w-1` since in a w-NAF, at most one of any `w` consecutive digits is nonzero.

_digs out Guide to ECC_

![image](https://user-images.githubusercontent.com/35766/233735554-96d84faf-80ae-4cdd-a959-48ab76d2e1da.png)


You're correct!

**Comment by upbqdn** [comment]
Sorry, I should have added the full definition right away so others don't have to search for it. I only realized that now.

**Comment by mpguerra** [comment]
@upbqdn  can you please add a size for this issue?

**Comment by upbqdn** [comment]
Done.
