### ISSUE TITLE
Accept text/plain RPC encodings automatically

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6363]
## Motivation

A user describes a Zebra incompatibility with `zcashd` RPC examples in this blog post:

> The curl command originally came from [the RPC docs](https://zcash.github.io/rpc/getblockchaininfo.html) as a sample, but it didn’t work out of the box. I had to change the Content-Type header from text/plain to application/json.

https://blog.nerdbank.net/2022/12/hosting-zcash-litewalletd-via-zebra

### Specifications

The `curl` example in:
https://zcash.github.io/rpc/getblockchaininfo.html

### Complex Code or Requirements

This should be a trivial change, we already adjust missing `Content-Type` headers here:
https://github.com/ZcashFoundation/zebra/blob/a97a9752d74c8505652de666cca3c67fa4ea7c81/zebra-rpc/src/server/http_request_compatibility.rs#L106-112

### Testing

- Make sure the `curl` example works after this change
    - Add a test in CI, like the existing raw RPC tests
- Make sure `zcash-cli` still works

**Comment by teor2345** [comment]
I'm not sure if this ticket should be medium or low priority, feel free to change it!

**Comment by droark** [comment]
@teor2345 - I'll start with this one. Seems like it should be low-hanging fruit.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6363?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
