### ISSUE TITLE
Add NU5 block test vectors for mainnet and testnet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6366]
## Motivation

We don't have any block test vectors for NU5 on:
* mainnet: https://github.com/ZcashFoundation/zebra/blob/main/zebra-test/src/vectors/block.rs#L542
* testnet: https://github.com/ZcashFoundation/zebra/blob/main/zebra-test/src/vectors/block.rs#L855

This means we're not testing the NU5 consensus rules in some unit tests, which seems like a significant gap in our test coverage.

This should be a quick fix, the scripts to generate the test vectors are in that file already.

### Testing

A lot of Zebra's unit tests already use these test vectors, but some tests might need to be updated for NU5.

**Comment by mpguerra** [comment]
@ZcashFoundation/zebra-team Is this still relevant?

**Comment by upbqdn** [comment]
Yes, however, the scope in the description seems loose.
