### ISSUE TITLE
Generate checkpoints in CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6367]
## Motivation

We want to generate checkpoints from the cached states in Zebra's CI, so that developers can do releases easily.

### Complex Code or Requirements

- [x] We currently call `zcash-cli` in the checkpoint binary, we'll need to switch to making RPC requests directly.
- [x] Set up a test harness that launches `zebrad` with RPCs, and connects `zebra-checkpoints` to it. This should be simple, we have existing test code that launches `zebrad` with RPCs.
  - [x] The mainnet version needs to use the cached state for efficiency, this slightly reduces our security, because we also test the checkpoints against the same cached state.
  - [x] The testnet version can also use a new testnet cached state, failures should be ignored because testnet can be unstable.

Originally I said that testnet can do a full sync from an empty state, but it turns out that's complicated to configure in our test harness.

### Testing

- [x] Compare manually generated checkpoints from `zcashd` and the checkpoints in CI.
- [x] Add a unit test that verifies that the generated checkpoints obey maximum checkpoint height gap, and that the minimum gap is at least 17 (the maximum checkpoint bytes divided by the maximum block size). This helps detect copy-paste mistakes.

## DevOps

- [x] After PR #6582 merges, re-enable https://github.com/ZcashFoundation/zebra/actions/workflows/delete-gcp-resources.yml
- [x] Admin: Require the new mainnet checkpoints job in the `main` branch protection rules

Testnet failures are expected occasionally, so we don't want to require that job.

**Comment by mpguerra** [comment]
Let's wait until @gustavovalverde is back before starting this one

**Comment by teor2345** [comment]
> Let's wait until @gustavovalverde is back before starting this one

This ticket also needs some changes to the Rust code of the checkpoint generation command, is that also blocked by Gustavo being away?

**Comment by mpguerra** [comment]
> > Let's wait until @gustavovalverde is back before starting this one
> 
> This ticket also needs some changes to the Rust code of the checkpoint generation command, is that also blocked by Gustavo being away?

No, but we should be prioritising audit fixes, shouldn't be doing a release for a while and we're going to be short-staffed so we might as well wait until Sprint 8 :)
