### ISSUE TITLE
Use default testnet port on testnet when Zcash listener address is not supplied

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6386]
## Motivation

I think there might be a bug in the deserializer code:
https://github.com/ZcashFoundation/zebra/blob/f1bedafbbb1bab97b2536fee50062db47bc4bbea/zebra-network/src/config.rs#L312-L324

What happens is that if the user configures `Testnet` but no listener address, we get the default mainnet port, as specified in the defaults here.

This usability bug only impacts testnet.

## Solution

I think the default deserialized listen address needs to be "0.0.0.0", so that we get the correct default port when the address is not configured on testnet.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/6228#discussion_r1144151036_

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6386?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
