### ISSUE TITLE
[NCC-E005955-GCR] Cargo Audit and RustSec Advisories

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6391]
## Impact
Failure to address RustSec advisories may leave publicly disclosed vulnerabilities in the project and may damage the reputation of the project.

## Description

The `cargo audit` tool can be used to check a project’s dependency tree against published RustSec advisories. Running `cargo audit` on the `audit-v1.0.0-rc.0` branch results in 6 known vulnerable crates and 6 warnings:

- Vulnerabilties:
    - `time 0.1.44` - Potential `segfault` in the time crate
    - `owning_ref 0.4.1` - Multiple soundness issues in `owning_ref`
    - `git2 0.14.4` - `git2` Rust package suppresses ssh host key checking
    - `libgit2-sys 0.13.4+1.4.2` - `git2` does not verify SSH keys by default
    - `remove_dir_all 0.5.3` - Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
    - `tokio 1.21.2` - `reject_remote_clients` Configuration corruption
- Warnings:
    - `ansi_term 0.11.0` - `ansi_term` is Unmaintained
    - `ansi_term 0.12.` - `ansi_term` is Unmaintained
    - `directories 4.0.1 - `directories` is unmaintained, use `directories-next` instead
    - `dirs 4.0.0` - `dirs` is unmaintained, use `dirs-next` instead
    - `mach 0.3.2` - `mach` is unmaintained
    - `net2 0.2.37` - `net2` crate has been deprecated; use `socket2` instead

The `audit-v1.0.0-rc.0` branch was frozen approximately two months prior to the writing of this finding. On the main branch of the project (commit 45a96b5 at the time of writing), only the two most recently reported vulnerabilities are present:

- Vulnerabilties ( main / 45a96b5):
    - `time 0.1.44` - Potential `segfault` in the `time` crate
    - `owning_ref 0.4.1` - Multiple soundness issues in `owning_ref`

The 6 warnings are also present.

In general, it is recommended to keep all crates up-to-date, particularly when known advisories are relevant. Even if the identified vulnerabilities do not affect Zebra directly, failure to respond to advisories and update dependencies may affect the reputation of the project.

## Recommendation

Ensure dependencies are regularly audited for RustSec advisories using a tool such as `cargo audit` or `cargo deny` , and automate the detection and response to future advisories to the greatest extent possible, such as the automatic filing of a security issue for review.

**Comment by teor2345** [comment]
These do not impact Zebra's security in release builds:

> Vulnerabilities:
> * `time 0.1.44` - Potential `segfault` in the time crate

Zebra is not vulnerable to this specific bug.

> * `owning_ref 0.4.1` - Multiple soundness issues in `owning_ref`

This dependency is not used in release builds, we have our own upgraded tracing component.
Upgrading `abscissa` #5502 will likely remove this dependency.

> * `git2 0.14.4` - `git2` Rust package suppresses ssh host key checking
> * `libgit2-sys 0.13.4+1.4.2` - `git2` does not verify SSH keys by default
> * `remove_dir_all 0.5.3` - Race Condition Enabling Link Following and Time-of-check Time-of-use (TOCTOU)
> * `tokio 1.21.2` - `reject_remote_clients` Configuration corruption

Fixed or removed in PR #6217 or an earlier dependency update.

> * Warnings:
>   
>   * `ansi_term 0.11.0` - `ansi_term` is Unmaintained
>   * `ansi_term 0.12.1` - `ansi_term` is Unmaintained

These crates do not need maintenance to continue to be secure. They are not used in security-critical code.
Upgrading `abscissa` #5502 might replace these dependencies.

>   * `directories 4.0.1 - `directories`is unmaintained, use`directories-next` instead
>   * `dirs 4.0.0` - `dirs` is unmaintained, use `dirs-next` instead

These warnings are incorrect, Zebra has updated to a recently released maintained version.

>   * `mach 0.3.2` - `mach` is unmaintained

Removed in PR #6217 or an earlier dependency update.

>   * `net2 0.2.37` - `net2` crate has been deprecated; use `socket2` instead

Waiting on our `jsonrpc-http-server` dependency to upgrade.

**Comment by teor2345** [comment]
> Ensure dependencies are regularly audited for RustSec advisories using a tool such as `cargo audit` or `cargo deny` , and automate the detection and response to future advisories to the greatest extent possible, such as the automatic filing of a security issue for review.

The Zebra team is automatically notified of RustSec advisories via GitHub Dependabot security notifications.
