### ISSUE TITLE
[NCC-E005955-MU2] `zebra-consensus`: Redundant Computation in Sapling and Orchard Note Validation

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6392]
## Impact

During Sapling and Orchard output validation, one redundant elliptic curve scalar multiplication is performed. It may be considered for removal for efficiency purposes.

This is an issue in `librustzcash`:
https://github.com/zcash/librustzcash/issues/802

## Description

In order to verify that Sapling and Orchard outputs are decryptable and consistent with ZIP 212 rules, Zebra uses the `zcash_primitives` crate’s `try_sapling_output_recovery` [function](https://github.com/zcash/librustzcash/blob/277d07c7/zcash_primitives/src/sapling/note_encryption.rs#L553). This function is called, for example, when coinbase transaction outputs are [validated](https://github.com/ZcashFoundation/zebra/blob/5a88fe78/zebra-consensus/src/transaction/check.rs#L320) to adhere to the rules specified in ZIP 212.

Once decrypted, an output’s note is [parsed](https://github.com/zcash/librustzcash/blob/277d07c7/components/zcash_note_encryption/src/lib.rs#L681). An ephemeral key validation function is passed as a lambda:

<img width="867" alt="Screenshot 2023-03-24 at 15 59 39" src="https://user-images.githubusercontent.com/1311133/227561862-3e9759af-6696-42cb-b5cc-b2b3718dfd86.png">

The check implemented by the highlighted lambda function is mandated by ZIP 212. A few lines below, the `check_note_validity` function is [called](https://github.com/zcash/librustzcash/blob/277d07c7/components/zcash_note_encryption/src/lib.rs#L693):

<img width="867" alt="Screenshot 2023-03-24 at 16 01 19" src="https://user-images.githubusercontent.com/1311133/227562274-b72c3704-c16e-480e-82d1-c848345447b7.png">

The validation highlighted in the first code snippet happens regardless of whether ZIP 212 is activated or not. This is also what the original Zcash client does; see [`zcash/Note.cpp`](https://github.com/zcash/zcash/blob/219b9c68/src/zcash/Note.cpp#L400).
The validation highlighted in the second code snippet aims to only validate the public key post-ZIP 212 and is likely meant to be a blanket end-of-function validation helper. This helper includes an ECC point multiplication and as such is not inexpensive.

## Recommendation

It appears that the highlighted check inside the `check_note_validity` function overlaps with the previous validation, and, as such, may be removed.

**Comment by teor2345** [comment]
@mpguerra this isn't a bug in Zebra, it's in an ECC dependency that is out of scope for the audit.

**Comment by mpguerra** [comment]
> @mpguerra this isn't a bug in Zebra, it's in an ECC dependency that is out of scope for the audit.

That's right. We want to track everything raised by the auditors and try to fix it if it makes sense.

**Comment by teor2345** [comment]
> > @mpguerra this isn't a bug in Zebra, it's in an ECC dependency that is out of scope for the audit.
> 
> That's right. We want to track everything raised by the auditors and try to fix it if it makes sense.

@mpguerra is there an equivalent librustzcash issue?

**Comment by mpguerra** [comment]
> @mpguerra is there an equivalent librustzcash issue?

There is now! https://github.com/zcash/librustzcash/issues/802

**Comment by upbqdn** [comment]
The function [check_note_validity](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/components/zcash_note_encryption/src/lib.rs#L514), where the redundancy occurs, is also called in

- [parse_note_plaintext_without_memo_ivk](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/components/zcash_note_encryption/src/lib.rs#L507), which is called in
- [try_note_decryption_inner](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/components/zcash_note_encryption/src/lib.rs#L486), which is called in
- [try_note_decryption](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/components/zcash_note_encryption/src/lib.rs#L462), which is a public function for trial decryption.

The call stack above doesn't contain the [epk check](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/zcash_primitives/src/sapling/note_encryption.rs#L261-L267) from [parse_note_plaintext_without_memo_ovk](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/zcash_primitives/src/sapling/note_encryption.rs#L254) mentioned in the finding; thus, removing the check from [check_note_validity](https://github.com/zcash/librustzcash/blob/fb49cd412f02b65def53a096f536c2d4aeda68f4/components/zcash_note_encryption/src/lib.rs#L514) might cause unexpected errors.

It would be beneficial to separate the two call stacks and remove the redundancy from the affected one, but my estimate is that the effort required for the refactoring doesn't match the benefits. I, therefore, propose we close this issue without addressing it.

**Comment by mpguerra** [comment]
@upbqdn  can you please add a size for this issue based on how much effort it took to investigate and analyze this?

**Comment by upbqdn** [comment]
Done.
