### ISSUE TITLE
Improve error handling in syncer

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6400]
## Motivation

We should downcast errors in the syncer's `BlockDownloadVerifyError` to concrete types and add them to the match statement in `should_restart_sync()`:

https://github.com/ZcashFoundation/zebra/blob/0152c8641bc41767a5ef7a67a8e01e84a26eb0a7/zebrad/src/components/sync.rs#L1088

https://github.com/ZcashFoundation/zebra/blob/0152c8641bc41767a5ef7a67a8e01e84a26eb0a7/zebrad/src/components/sync.rs#L1155-L1163

**Comment by teor2345** [comment]
Could we re-open and update #2908 rather than starting a new ticket?
Or is there any useful info in #2908 that we can add here?

**Comment by arya2** [comment]
Updating and re-opening #2908 instead.
