### ISSUE TITLE
Add documentation on how to manipulate log levels in `zebrad`

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#652]
In particular we need to document that we:
- [ ] use a non-standard env variable for manipulating our log level, `ZEBRAD_LOG`, and
- [ ] process the log options in this order: verbose flag, command uses stdout, env var, config file.

We should probably follow `chalk`'s example on how to structure the section on how to manipulate the log level. https://rust-lang.github.io/chalk/book/contribution_guide.html?highlight=log#running-and-debugging

I already had plans for creating a mdbook for the various zebra design documents we create, we might want to also have a dev guide in that same book as a different section where this gets placed.

---

We should probably document this.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/648_

**Comment by hdevalence** [comment]
Sounds good.  Should we keep a tracking issue for all of the facts we need to document, or should it be a milestone?

**Comment by yaahc** [comment]
I think its fine to just leave them as individual issues. If we need a way to organize them I'd start with adding a `docs` tag or something.

**Comment by hdevalence** [comment]
This is now in the Config docs.
