### ISSUE TITLE
Document the process of updating zcashd dependencies

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6532]
Zcash dependencies of zebra (zcash_primitives, zcash_script, zcash_address, etc) are generally needed to be updated at the same time. This means depdendabot has to be closed and a bump pull request should be created with all the bumps at once.

This ticket is to document this process.

**Comment by oxarbitrage** [comment]
### Updating ECC dependencies

We use a bunch of ECC dependencies, and when there is a big change (e.g. NU5) we need to update them all at once because they may only work with specific versions of one another.

The main dependency that influences that is zcash itself. This is because zebra_script links to specific files from it (zcash_script.cpp and all on which it depends). Due to the architecture of zcash, this requires linking to a lot of seemingly unrelated dependencies like orchard, halo2, etc (which are all Rust crates). So the first thing to determine is which zcash version to use, and that will dictate which versions of the other crates to use.

The overall steps to update them are:

- Determine the zcashd version to use. Usually this should be a tag, but could be a reference to a branch (e.g. nu5-consensus) if there is some development going on that hasn't been tagged but you want to test it ASAP.
- In zcash_script:
  - Point to the updated zcash code (see the project README.md for more info)
  - Update Cargo.toml to match the same package version and patches that are in zcash/Cargo.toml (in the desired version).
  - Run cargo clean && cargo test to check if everything still works. (clean is needed because it doesn’t always correctly detect that the C++ code has changed).
  - Ideally, commit and tag a release, but if you're just testing it, commit to a branch and write down the commit hash.
- In zebra:
  - Update zebra-script/Cargo.toml to point zcash_script to the version you wrote down (tag or commit hash).
  - Update Cargo.toml to point zcash_proofs to the version you wrote down.
  - Update other dependencies and patches in Cargo.toml to match the ones in zcash/Cargo.toml.
  - Do the usual testing to check if it works


## Outdated

This step is outdated, it doesn't need to be done any more (we forgot to update the instructions, if they are in the repository, they are more likely to get updated)

- In our fork of librustzcash (if our Sprout download code is not yet merged upstream):
  - Rebase our fork on top of the desired version of librustzcash (the previous branch/commit should be listed in zebra/Cargo.toml) and push to a new branch, e.g. download-sprout-params-5761bb4b (use the hash of the librustzcash commit). Write down the commit hash of that branch.

**Comment by teor2345** [comment]
We might want to `@dependabot ignore this dependency` for everything except the highest-level dependencies.

But it's tricky, because sometimes we only need to update a single dependency for a bug fix release.

**Comment by teor2345** [comment]
Here's how I upgraded to the latest shared dependencies:
1. Get a list of all open `zcash_*` dependabot PRs
2. Run `cargo upgrade --workspace (those dependencies)`
3. Check the compiler errors, and add each crate they mention to the upgrade list
4. Check `cargo deny` duplicate dependency errors, and add each crate they mention to the upgrade list
5. Repeat from step 2 until all dependencies are upgraded
6. Make any required changes to the code that can't be fixed with a dependency update
7. Remove unused `deny.toml` entries

And the final command was:
```sh
cargo upgrade --workspace bellman bls12_381 group halo2 halo2_proofs jubjub orchard redjubjub zcash_address zcash_note_encryption zcash_primitives zcash_proofs
```

**Comment by teor2345** [comment]
Here are the `zcash_script` upgrade instructions:
https://github.com/ZcashFoundation/zcash_script#updating-this-crate

They get updated as needed when `zcashd` changes things.

**Comment by mpguerra** [comment]
Is this going to go in the Zebra book?

**Comment by teor2345** [comment]
> Is this going to go in the Zebra book?

I think the overall process can go in the dev book, and we can link from there to the detailed `zcash_script` instructions.

**Comment by teor2345** [comment]
We should document whether we base `zcash_script` on `zcashd` release candidates, or we wait until the production release.

I think we might want to open a draft PR for the `master` branch and any release candidates, so we can pick up any bugs. But we should only do the final release once the production release is tagged, to save us upgrading Zebra twice.

**Comment by conradoplg** [comment]
> We should document whether we base `zcash_script` on `zcashd` release candidates, or we wait until the production release.
> 
> I think we might want to open a draft PR for the `master` branch and any release candidates, so we can pick up any bugs. But we should only do the final release once the production release is tagged, to save us upgrading Zebra twice.

Agreed!

**Comment by mpguerra** [comment]
We should take advantage of the fact that we're doing #6859 in the same sprint to finalise and publish this documentation

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6532?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
It would also help to have a list of cryptographic dependencies we upgrade along with the ECC dependencies. For example:
https://github.com/ZcashFoundation/zebra/blob/f1ee502ddf2bf8ffcdb60dbabdc91885f3d723c9/zebra-chain/Cargo.toml#L67-L68

**Comment by teor2345** [comment]
Here's another overview I just wrote, for testing the release candidate:
- [ ] wait for the zcashd release candidate
- [ ] upgrade `zcash_script`
- [ ] wait for the zcashd release
- [ ] release zcash_script
- [ ] upgrade Zebra's ECC and `zcash_script` dependencies in the same PR

**Comment by daira** [comment]
We don't have capacity to do this ourselves, but if you wanted to try to extricate `zcash_script.cpp` so that it depends on less of zcashd, those changes would be welcome I think. (In the longer term they'd help us safely transition to using Zebra.)

**Comment by teor2345** [comment]
> We don't have capacity to do this ourselves, but if you wanted to try to extricate `zcash_script.cpp` so that it depends on less of zcashd, those changes would be welcome I think. (In the longer term they'd help us safely transition to using Zebra.)

It might be easier to make `zcash_script` call lower-level `zcashd` functions, rather than removing dependencies from the high-level transaction object to other parts of `zcashd`.

In general it's tricky because the `zcash_script` crate isn't tested in `zcashd`'s CI, so dependencies just creep in over time. If we call lower level functions this is less likely.
