### ISSUE TITLE
Upgrade `zcash_script` after the `zcashd` 5.5.0 release

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6535]
## Motivation

After `zcashd` 5.5.0 is released:
https://github.com/zcash/zcash/tags

We want to update our script engine to match its implementation. There haven't been any significant changes to script behaviour, but the surrounding code has been refactored.

## Scheduling

This doesn't need to be in the same release as #6232, but builds will be slower until we update our entire set of dependencies. There's also a small but acceptable risk of consensus divergence.

### Specifications

Zcash transparent scripts are mostly unspecified, so we must match `zcashd`'s behaviour.

### Complex Code or Requirements

This is consensus-critical code.

### Testing

Our existing unit and integration tests have good coverage of this code.

Manually use `cargo tree` to check that we don't depend on any vulnerable `orchard` versions: we must only depend on orchard 0.4 or later.

## Related Work

Follow up to:
- #6232

**Comment by teor2345** [comment]
The zcash_script crate upgrades are in https://github.com/ZcashFoundation/zcash_script/pull/84

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6535?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@teor2345 are you working on this one in https://github.com/ZcashFoundation/zcash_script/pull/84 ? Is there anything else that needs to be done to close this issue?

**Comment by teor2345** [comment]
> @teor2345 are you working on this one in [ZcashFoundation/zcash_script#84](https://github.com/ZcashFoundation/zcash_script/pull/84) ?

Yes, please see my updates on that PR and in Slack.

I am waiting for the ECC developers to push the zcashd v5.5.0 tag, but we can proceed based on the second release candidate if we need to. Is there any reason we need to do this soon?

> Is there anything else that needs to be done to close this issue?

We need to:
- [x] wait for the zcashd tag
- [x] finish the zcash_script changes
- [x] get the PR reviewed
- [ ] merge and publish the crate
- [ ] open a PR in Zebra to update the crate dependency (or wait for dependabot)
- [ ] get that PR reviewed and approved

**Comment by teor2345** [comment]
You can see the detailed instructions here:
https://github.com/ZcashFoundation/zebra/issues/6532#issuecomment-1512155820

**Comment by mpguerra** [comment]
> > @teor2345 are you working on this one in [ZcashFoundation/zcash_script#84](https://github.com/ZcashFoundation/zcash_script/pull/84) ?
> 
> Yes, please see my updates on that PR and in Slack.
> 
> I am waiting for the ECC developers to push the zcashd v5.5.0 tag, but we can proceed based on the second release candidate if we need to. Is there any reason we need to do this soon?

No no :) I was just trying to figure out if this was in progress and who was working on it

**Comment by mpguerra** [comment]
I think we still need to:

- [x] merge and publish the crate
- [x] open a PR in Zebra to update the crate dependency (or wait for dependabot)
- [ ] get that PR reviewed and approved
