### ISSUE TITLE
Should `zebrad seed` use the zebrad config file?

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#655]
In `process_config`, we use the config file for the start command:
https://github.com/ZcashFoundation/zebra/blob/67718898c53d6603bcbdcdfbadb02dfc970a999b/zebrad/src/commands.rs#L79

Should we also use it for the `seed` command?

In any case, we should document which commands use the config.

@gtank @dconnolly what do you think?

**Comment by hdevalence** [comment]
Yes, I think all commands should use the same config file, except for the commands that don't use any config at all (help, version, etc.)

**Comment by yaahc** [comment]
as far as I can tell everything is already using the same config file, the `override_config` fn is for overriding the config's settings with settings from the command line

```rust
impl config::Override<ZebradConfig> for StartCmd {
    // Process the given command line options, overriding settings from
    // a configuration file using explicit flags taken from command-line
    // arguments.
    fn override_config(&self, mut config: ZebradConfig) -> Result<ZebradConfig, FrameworkError> {
        if !self.filters.is_empty() {
            config.tracing.filter = Some(self.filters.join(","));
        }

        Ok(config)
    }
}
```

I think everything is already setup the way we want

**Comment by hdevalence** [comment]
Per @yaahc's analysis, I'm to close this to keep the open issue count down, but we can reopen it if it turns out we missed something.
