### ISSUE TITLE
Make the latest production release sort first on DockerHub

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6553]
## Motivation

Currently, the docker image for the latest production release is the 5th entry on DockerHub:
https://hub.docker.com/r/zfnd/zebra/tags

But we want people to use that image, so it should be listed first to avoid confusion. This is a usability issue.

## Potential Solution

This might be fixed by adding a `latest` tag, which should sort first in alphabetical order.

### Testing

Do a release, and check what appears here:
https://hub.docker.com/r/zfnd/zebra/tags

**Comment by teor2345** [comment]
@mpguerra this is something we probably want to start doing in a release candidate at least two releases before the stable release.

**Comment by gustavovalverde** [comment]
This should be done automatically when we release v1.0.0 without `-rc.0`. For Docker, `latest` is only the last `stable` release. https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/build-docker-image.yml#L99

This can be closed, or we can wait until we release to confirm.

**Comment by teor2345** [comment]
It would be nice to check this happens how we expect after the stable release.

**Comment by gustavovalverde** [comment]
Confirmed https://hub.docker.com/r/zfnd/zebra/tags
