### ISSUE TITLE
Automate Zebra updates (behind a feature)

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6564]
## Motivation

We want to keep Zebra nodes on the network up-to-date with minimal obtrusion.

Outdated Zebra releases should refuse to run (without code changes) once https://github.com/ZcashFoundation/zebra/pull/6351 has merged to prevent stable releases of Zebra from inadvertently being left running after a certain block height. 

Zebra *could* still be left running indefinitely if there were a feature for self-updating when there's a new release.

### Possible Design

- Poll for new Zebra releases when Zebra is compiled and run with a feature flag.
  - Add a config field for specifying how long Zebra should wait after a version is released before switching to it.
  - Add a config field for the source, so users can set up and use private registries for updating their nodes

https://github.com/jaemk/self_update

**Comment by arya2** [comment]
This could help more Zebra nodes stay on the latest release.

**Comment by teor2345** [comment]
This is a good idea, but it has some severe security and decentralisation impacts.

Auto-updates would allow the Zebra team or anyone who gains access to our deployment keys to deploy malicious code.

It also increases the centralisation of the ecosystem, which goes against the Foundation's goals:
> The Zcash Foundation aims to encourage decentralization of the protocols and networks that we support, avoiding the placement of trust or granting of capabilities to any single party (assigned or emergent). The Foundation will not seek to place itself in a position of control over the Zcash community. Whenever current technology does not achieve perfect decentralization, we will seek to minimize, monitor, and mitigate centralization.

> To help protect that freedom of choice, the Foundation will not seek or hold privileged information beyond what is observable by anyone from public blockchains or equivalent outside disclosures. We will never knowingly facilitate or assist in surveillance, through a cryptographic “backdoor” or any other method.

https://zfnd.org/about/

**Comment by arya2** [comment]
> This is a good idea, but it has some severe security and decentralisation impacts.
> 
> Auto-updates would allow the Zebra team or anyone who gains access to our deployment keys to deploy malicious code.
> 
> It also increases the centralisation of the ecosystem, which goes against the Foundation's goals

That's an excellent point, I added:
>  ..when Zebra is compiled and run with a feature flag
> - a config field for specifying how long Zebra should wait after a version is released before switching to it.
> - a config field for the source, so users can set up and use private registries for updating their nodes

Ideally implementing this would make it easier for users to configure what they would otherwise be doing manually (so that they can safely forget about their own policy.)

**Comment by teor2345** [comment]
As another alternative, we could notify users when there is a new `zebrad` release available:
https://github.com/tarikeshaq/update-notifier

This would need to happen in the tracing logs and the progress-bar info line.

**Comment by teor2345** [comment]
> As another alternative, we could notify users when there is a new `zebrad` release available: [tarikeshaq/update-notifier](https://github.com/tarikeshaq/update-notifier)
> 
> This would need to happen in the tracing logs and the progress-bar info line.

Actually, I'm not sure even this is a good idea, for privacy reasons. There's a good summary of the privacy impacts of any kind of "phone-home" network activity in this blog post: 
https://estebank.github.io/rustc-metrics.html

It's about metrics, but the privacy impact of auto-update checks is similar.

So I think we'd be better to delegate updates to existing software like Docker or debian package managers, which privacy-conscious users have already set up to respect their privacy goals. (And even if they haven't, doing updates in the same way as a lot of other software creates a larger anonymity set for all users.)

Here's a summary of the main arguments about privacy:

> Trust is easily lost, and difficult to recover. The Rust community trusts us, its maintainers, to ship reliable tooling. Users also trust us to respect their privacy.
> ...
> I believe that no compiler needs to call home.
> ...
> In other spaces, particularly for Free/Libre and Open Source Software and developer tools in general, the idea of any kind of communication between an application running on a user’s machine and a remote server is viewed with suspicion, if not out-right disdain.
> ...
> Consumer software is different. Users have an expectation that software will do only what it “says on the tin”, not mess with their data in unwanted ways, including sending it to a third party. The relationship between developers and users is then in tension. Developers want to know as much as possible in order to service their users, and users don’t want to be worried about their applications working against their interests. A consequence of this dynamic is that when telemetry is proposed, it is immediately perceived by users as the software they trusted starting to spy on them.
