### ISSUE TITLE
Codify process for tracking newly-uncovered security vulnerabilities

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6574]
## Motivation

We want to codify our policies for triaging and fixing uncovered security vulnerabilities.

**Comment by teor2345** [comment]
See also:
- #2001 
- #5996

**Comment by teor2345** [comment]
I think our next step here is to do a retrospective on the security issues we fixed recently?

**Comment by mpguerra** [comment]
We already did a retrospective in the past, closing this for now
