### ISSUE TITLE
Avoid conflicting default ports for listeners

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#660]
We should disable the metrics and tracing services by default, because they represent a low-severity security issue:
* metrics exposes information some users may want to keep private
* tracing allows unauthenticated third parties to modify some parts of the config, which may be a denial of service risk

Using "localhost" as the default isn't the perfect solution, because:
* "localhost" doesn't convert to SocketAddr, even though the SocketAddr docs say it should, and
* there are multiple localhost addresses: 127.0.0.0/8 and ::1

Using "None" means that the user can decide between IPv4 or IPv6 as needed, and we don't risk picking the wrong address. And we can encourage users to specify 127.0.0.1 by providing that as an example in the generated config's comments.

Similarly, the Zcash protocol listener defaults to 0.0.0.0:8233, which is the wrong port for the testnet, and doesn't include IPv6 on some operating systems.

We should fix all these issues at the same time, so we only have to do one docker config update.

TODO:
- Change the default for these listeners:
  - [x] Metrics: no listener
  - [x] Tracing: no listener
  - [x] Zcash: all interfaces, default port for ~the configured network~ Mainnet
- [ ] Update the generated config's comments to recommend `127.0.0.1` or `::1`
- [ ] Update the Zebra deployment docker configs (#885)

See #649 for an earlier version of this change, which modified the bind addresses to 127.0.0.1.

**Comment by hdevalence** [comment]
Rather than updating the generated config's comments to recommend 127.0.0.1, I think we should do it in the documentation for the config field -- we currently don't document any config fields in the generated config's comments, and instead just direct users to the generated rustdoc, so that there's a single source of truth on the meaning of the config options.

**Comment by teor2345** [comment]
Blocked on the initial alpha release.

We don't want to change the zebrad docker configs until after the initial alpha release.

**Comment by hdevalence** [comment]
I think it's fine to do this now. Zebra doesn't actually work yet, so preserving a stable deployment mechanism is not important compared to implementing necessary functionality, since we have no software to meaningfully deploy.

**Comment by hdevalence** [comment]
In particular, we can't wait until after we do a release to fix the config format that we expect the software to use.

**Comment by teor2345** [comment]
I'm ok with this change, but I'd like to check with @dconnolly, because she was the one who raised concerns about the docker configs.

Do we have monitoring on docker which uses the metrics ports?
Would it be ok to break it for a while, until we have time to fix it?

This change only disables the metrics and tracing ports by default, so we'll still need #807 for the Zcash protocol listener port.
