### ISSUE TITLE
Document how to switch from Testnet to Mainnet in Docker images

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#6611]
## Motivation

We recently published a Docker image with mining enabled on Testnet. We would like to invite miners to try mining with Zebra on Mainnet as well. We should document how they can do the switch so we can point them to the documentation.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6611?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
The answer to this should be:
```sh
docker run --env "NETWORK=Mainnet" zfnd/zebra:1.0.0-rc.8
```

As in our new tests in:
https://github.com/ZcashFoundation/zebra/pull/6842/files#diff-cf50b78d878d5d82cd3d3a646a8f4ad1a3e289b85701a30f0b4f2cc0fac49fecR103

**Comment by upbqdn** [comment]
This is not enough because miners also need to set a Mainnet `mining.miner_address`; otherwise, Zebra won't start. We don't set any address even for Testnet, so the image doesn't currently work.

We could set a default one, but if a miner accidentally forgets to set their own, and they happen to mine a block on Mainnet, they might be upset. I would therefore lean towards forcing users to set their `mining.miner_address` before starting the Docker container. This is also consistent with non-containerized Zebra. I'd do the same for Testnet so that there's no difference.

**Comment by teor2345** [comment]
> This is not enough because miners also need to set a Mainnet `mining.miner_address`; otherwise, Zebra won't start. We don't set any address even for Testnet, so the image doesn't currently work.

Do we need to update ticket #6752 so we implement the mining config this way?

**Comment by upbqdn** [comment]
That ticket already mentions that we need to add `mining.miner_address` to the config. I also added the clarification as to why we shouldn't set a default one to the PR description.
