### ISSUE TITLE
[NCC-E005955-GHX] Incorrectly Disabled Consistency Check

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6617]
## Impact

Disabling checks to pass incorrect tests rather than fixing the tests themselves may prevent the detection of bugs or other incorrect behavior.

## Description

The function `fetch_sprout_final_treestates()` in [zebra-state/src/service/check/anchors.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-state/src/service/check/anchors.rs#L158-L172) contains a block of commented code that performs an assertion that “that roots match the fetched tree during tests”. The annotations suggest that this check was disabled due to bad test data:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-state/src/service/check/anchors.rs#L158-L172

As is, the code suggests that a required safety check has been disabled to prevent tests from failing, which prevents the test from being run in production as well. The preferred solution would be one of:

1. Fix the tests such that the check can remain enabled.
2. Disable this code only when tests are running.

Initial discussions with the Zebra team suggested that the latter approach would be preferable. Furthermore, the comment suggests that this check should be refactored and located elsewhere in the code. A task to track this change should be documented.

## Recommendation

1. Re-enable the check and either add a flag to disable it during tests, or update tests to correctly pass when the check is in place.
2. Refactor the code as recommended in the comment, or add a link to a tracked issue detailing this work item.

**Comment by teor2345** [comment]
This check was verified as redundant and the comment was deleted in PR #6450.
