### ISSUE TITLE
Google Cloud CI machine setup fails due to an internal error

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6667]
## Motivation

CI is failing on some PRs due to:
> ERROR: (gcloud.compute.images.list) Some requests did not succeed:
> - Internal error. Please try again or contact Google Support. (Code: '5FB73FD7D035B.A2586D1.C40B6F7F')

https://github.com/ZcashFoundation/zebra/actions/runs/4953409934/jobs/8861561210?pr=6662#step:9:129

### Testing

TODO: @gustavovalverde can you fill this in?

**Comment by gustavovalverde** [comment]
I have a long time without seeing this one. Please reopen it otherwise
