### ISSUE TITLE
Create a ticket template for devops or CI failures

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6668]
## Motivation

We don't have a ticket template for devops bugs or CI failures, and they need different information from Zebra change requests or Zebra bugs.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6668?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
