### ISSUE TITLE
[NCC-E005955-7DU] `zebra-network`: Fragile State Transition During Address Book Update

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6672]
## Impact

Failure to reject out of order address change requests corrupts the Address Book’s state and opens the Zebra node to state manipulation attacks.

## Description
The `zebra_network`’s `AddressBook` update implementation uses `MetaAddrChange`’s `apply_to_meta_addr()` to update the entry’s previous state to the received updated state.
The `apply_to_meta_addr()` function validates the change against the previous state and optionally returns the new `MetaAddr`. If the received state is not the never-attempted state (the else condition on line 831) the current state is one of { `AttemptPending`, `Responded`, `Failed`}. In order to tolerate an address change request that is received out of order, the implementation picks the maximum of { `last_response`, `last_attempt`, `last_failure`} timestamps. Thus these timestamps will never revert to their previous values. However, independent of what the previous state was, on line 853, the new address state is returned. The `last_connection_state` records the outcome of local node’s most recent
communication attempt with this peer:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-network/src/meta_addr.rs#L785-L860

## Recommendation

Update `apply_to_meta_addr()` to return `None` when the state transition is invalid, e.g., the request is received out-of-order.

## Location

[zebra-network/src/meta_addr.rs, line 853](https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-network/src/meta_addr.rs#L853)

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6672?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This suggested solution won't quite work, because incoming network messages from the same peer can be processed in parallel by different tasks. So we need to:
- add times to each message
- compare the times within some tolerance
- prioritise the "worst/latest" peer state if the times are close (Failed, Responded, AttemptPending)

**Comment by teor2345** [comment]
There's also a separate fix needed to avoid one peer overwhelming the shared address book update channel.
