### ISSUE TITLE
Outdated Documentation in `zebra-state`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6673]
The `Chain::update_chain_state_with` that is mentioned in the documentation for the `with_block_and_spent_utxos()` function does not exist (see snippet below). It should probably be replaced with [`update_chain_tip_with()`](https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/non_finalized_state/chain.rs). The same error exists in the [`book/src/dev/rfcs/0012-value-pools.md`](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0012-value-pools.md) document.

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-state/src/request.rs#L264-L274

**Comment by teor2345** [comment]
> The same error exists in the [`book/src/dev/rfcs/0012-value-pools.md`](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0012-value-pools.md) document.

We don't usually update RFCs, they are a point-in-time "request for comments" from developers.

**Comment by mpguerra** [comment]
> > The same error exists in the [`book/src/dev/rfcs/0012-value-pools.md`](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0012-value-pools.md) document.
> 
> We don't usually update RFCs, they are a point-in-time "request for comments" from developers.

We can add this as a client comment in the relevant section

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6673?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> > > The same error exists in the [`book/src/dev/rfcs/0012-value-pools.md`](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0012-value-pools.md) document.
> > 
> > 
> > We don't usually update RFCs, they are a point-in-time "request for comments" from developers.
> 
> We can add this as a client comment in the relevant section

I added it to the client comments document.
