### ISSUE TITLE
Renames to address confusion in zebra's handling of finalized state

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6680]
Here's a list of the renames we could do, feel free to edit it:

Add to docs:
- [x] The difference between a `CheckpointVerifiedBlock` and a `ContextuallyVerifiedBlock` is that the `CheckpointVerifier` doesn't bind the transaction authorizing data to the `ChainHistoryBlockTxAuthCommitmentHash`, but the `NonFinalizedState` and `FinalizedState` do.

zebra-consensus:
- [x] BlockVerifier -> SemanticBlockVerifier
- [x] ChainVerifier -> BlockVerifierRouter
- [x] Rename file `zebra-consensus/src/chain.rs` to `zebra-consensus/src/router.rs`  

The `CheckpointVerifier` doesn't need to be renamed.

zebra-state:

SemanticBlockVerifier `Request`:
- [x] CommitBlock(PreparedBlock) -> CommitSemanticallyVerifiedBlock(SemanticallyVerifiedBlock)
- [x] PreparedBlock -> SemanticallyVerifiedBlock
- [ ] any variables, functions, methods, and documentation that mentions `non_finalized` where it should say `semantically_verified` (mainly in `service.rs`, `queued_blocks.rs`, `request.rs`, and `response.rs`)

CheckpointBlockVerifier `Request`:
- [x] CommitFinalizedBlock(FinalizedBlock) -> CommitCheckpointVerifiedBlock(CheckpointVerifiedBlock)
- [x] FinalizedBlock -> CheckpointVerifiedBlock
- [ ] any variables, functions, methods, and documentation that mentions `finalized` where it should say `checkpoint_verified` (mainly in `service.rs`, `queued_blocks.rs`, `request.rs`, and `response.rs`)

Used inside the NonFinalizedState:
- [x] ContextuallyValidBlock -> ContextuallyVerifiedBlock
- [x] FinalizedWithTrees -> ContextuallyVerifiedBlockWithTrees
- [x] any variables, functions, methods, and documentation that mentions `finalized` where it should say `contextually_verified` (mainly `FinalizedState::commit_finalized_direct()` and callers)

I usually use `fastmod` then `cargo fmt --all` to do renames, but any search and replace tool should make it pretty easy.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/discussions/6620#discussioncomment-5898725_

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6680?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
I made all the task list in https://github.com/ZcashFoundation/zebra/pull/6762/

but i didnt made the changes that say:

```
 any variables, functions, methods, and documentation that mentions non_finalized where it should say semantically_verified (mainly in service.rs, queued_blocks.rs, request.rs, and response.rs)
```

and 

```
 any variables, functions, methods, and documentation that mentions finalized where it should say checkpoint_verified (mainly in service.rs, queued_blocks.rs, request.rs, and response.rs)
```

This is because this variables do not shown up in `queued_blocks.rs, request.rs, and response.rs` , they appear partially in `service.rs` as for example `non_finalized_state_receiver`, `last_sent_finalized_block_hash`, etc.

I was unsure if we should change those.

**Comment by teor2345** [comment]
@mpguerra I don't think this task is actually finished yet. There are still a lot of variables and comments that incorrectly say "finalized" when they should say "checkpoint verified", and "non_finalized" when they should say "semantically_verified".

**Comment by teor2345** [comment]
I think we need to finish #6793 and #6681 to actually fix this confusion in the state names and documentation.

But first we need to add all the missed renames from this ticket and PR #6762 to the list in #6793.
