### ISSUE TITLE
Build failure when elasticsearch feature is enabled

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6695]
Reported by John in slack. When i execute this command to install zebra:

```
cargo install --features="elasticsearch" --locked --git https://github.com/ZcashFoundation/zebra --tag v1.0.0-rc.8 zebrad
```

I get the following build error:
```
...
   Compiling zebra-state v1.0.0-beta.24 (/home/oxarbitrage/.cargo/git/checkouts/zebra-d0d93d7ded255019/0190882/zebra-state)
error[E0277]: the trait bound `zebra_chain::block::Block: Serialize` is not satisfied
   --> zebra-state/src/service/finalized_state.rs:388:23
    |
388 |                 .push(serde_json::json!(block).to_string());
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^
    |                       |
    |                       the trait `Serialize` is not implemented for `zebra_chain::block::Block`
    |                       required by a bound introduced by this call
    |
    = help: the following other types implement trait `Serialize`:
              &'a T
              &'a mut T
              ()
              (T0, T1)
              (T0, T1, T2)
              (T0, T1, T2, T3)
              (T0, T1, T2, T3, T4)
              (T0, T1, T2, T3, T4, T5)
            and 276 others
    = note: required for `Arc<zebra_chain::block::Block>` to implement `Serialize`
    = note: 2 redundant requirements hidden
    = note: required for `&&Arc<zebra_chain::block::Block>` to implement `Serialize`
note: required by a bound in `to_value`
   --> /home/oxarbitrage/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.96/src/value/mod.rs:942:8
    |
942 |     T: Serialize,
    |        ^^^^^^^^^ required by this bound in `to_value`
    = note: this error originates in the macro `json_internal` which comes from the expansion of the macro `serde_json::json` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `zebra-state` due to previous error
error: failed to compile `zebrad v1.0.0-rc.8 (https://github.com/ZcashFoundation/zebra?tag=v1.0.0-rc.8#01908822)`, intermediate artifacts can be found at `/tmp/cargo-install27LFAQ`
$
```

This is also happening without `--locked` argument.

**Comment by oxarbitrage** [comment]
Also happening with the last `main`:

```
cargo install --features="elasticsearch" --git https://github.com/ZcashFoundation/zebra zebrad
```

**Comment by oxarbitrage** [comment]
This builds fine:

```
$ cargo build --release --features="elasticsearch"
```

**Comment by teor2345** [comment]
The elasticsearch feature needs to be added to the list of features that activate Serialize on Block and every type that it contains:
https://github.com/ZcashFoundation/zebra/blob/185d1384fbf4e7a31c794b17d7fc69dd4aeb5aa7/zebra-chain/src/block.rs#L46-L47

This build issue happens because some build commands activate the proptest-impl feature, and some don't.

**Comment by oxarbitrage** [comment]
I tried the above fix and i am now getting the same error as https://github.com/ZcashFoundation/zebra/actions/runs/5005342607/jobs/8969163581?pr=6706 which is a bump of bitflags. It is possible that a fix in that PR (https://github.com/ZcashFoundation/zebra/pull/6706) might help here too.

**Comment by teor2345** [comment]
> I tried the above fix and i am now getting the same error as [ZcashFoundation/zebra/actions/runs/5005342607/jobs/8969163581?pr=6706](https://github.com/ZcashFoundation/zebra/actions/runs/5005342607/jobs/8969163581?pr=6706) which is a bump of bitflags. It is possible that a fix in that PR (#6706) might help here too.

This is a bug in the `bitflags` release version, see https://github.com/ZcashFoundation/zebra/issues/6711#issuecomment-1552060384

Use `--locked` to work around this issue, it will stop `cargo` finding the latest version. (Which is wrongly marked as compatible.)

**Comment by oxarbitrage** [comment]
You are right, `--locked` will do it. https://github.com/ZcashFoundation/zebra/pull/6709#issuecomment-1552156168

**Comment by KodrAus** [comment]
Sorry for the confusion all. This should be all sorted by `bitflags-serde-legacy` `0.1.1` now.

**Comment by teor2345** [comment]
> The elasticsearch feature needs to be added to the list of features that activate Serialize on Block and every type that it contains

@oxarbitrage I'm happy to help you through setting up these feature dependencies, but I'm focused on other work right now. 

So let's wait until this ticket gets scheduled?

**Comment by oxarbitrage** [comment]
> So let's wait until this ticket gets scheduled?

Yes, agree with that, I thought it was going to be easier.
