### ISSUE TITLE
Update to the latest versions of bitflags-serde-legacy and bitflags

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6711]
## Motivation

The `bitflags` version bump from 2.2.1 to 2.3.1 renames the `BitFlags` trait.

This caused some build failures until `bitflags-serde-legacy` was also updated.

We can either depend on `bitflags` < 2.3.0 and `bitflags-serde-legacy` < 0.1.0, or `bitflags` >= 2.3.0 and `bitflags-serde-legacy` >= 0.1.0. Other combinations won't compile.

### Update dependent packages

Update `bitflags` to 2.3.1 or later, and `bitflags-serde-legacy` to 0.1.1 or later, in the same PR. This will happen anyway the next time we run `cargo update` for a release.

### Bring dependent packages inside Zebra

We should consider replacing `bitflags-serde-legacy` with our own implementation in Zebra.

## Background

> #[deprecated(note = "use the `Flags` trait instead")]
> 
> https://github.com/bitflags/bitflags/compare/2.2.1...2.3.1#diff-172747fc43e38d33de743b2d5f564ad6440570670af7aa912235399448a55c7cR323

_Originally posted by @arya2 in https://github.com/ZcashFoundation/zebra/issues/6706#issuecomment-1551977386_

**Comment by teor2345** [comment]
This is a bug in the versioning of `bitflags`, which made a breaking change in a minor version bump.
(It was obviously a breaking change, because it broke compilation of `bitflags-serde-legacy`.)

I've opened a ticket to get the author to fix it and release a new version:
https://github.com/bitflags/bitflags/issues/359

**Comment by teor2345** [comment]
This seems like it's a medium priority, because it's causing build failures.

**Comment by teor2345** [comment]
Other packages have been updated, and the build failures have been resolved.

**Comment by mpguerra** [comment]
Do we need to do anything here before the stable release and/or the next few sprints or can this wait?

**Comment by mpguerra** [comment]
will happen automagically
