### ISSUE TITLE
Pass mining config to the mining Docker container at runtime

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#6752]
## Motivation

In order to use Zebra for mining, a user needs to set their Zcash address in Zebra's config. Zebra uses this address in coinbase transactions to pay the mining reward.

We have a Docker image that packages Zebra with support for mining. However, since Zebra lives inside this image, the user needs to be able to pass the address to the container at runtime.

Users of the image will also need to be able to choose if they want to mine on Testnet or Mainnet. They will need to pass this information to the container at runtime as well.

## Solution

We need to enable passing of `network.network` and `mining.miner_address` to Zebra's config at the runtime of the Docker container that has mining enabled.

We could set a default `mining.miner_address`, but if a miner accidentally forgets to set their own, and they happen to mine a block on Mainnet, they might be upset. I would therefore lean towards forcing users to set their `mining.miner_address` before starting the Docker container. This is also consistent with non-containerized Zebra. I'd do the same for Testnet so that there's no difference.

**Comment by upbqdn** [comment]
In order to do this, we need to use the `ENTRYPOINT` instruction for the `runtime` target in the Dockerfile. We're using this instruction already for the testing target, and there can be only one `ENTRYPOINT` instruction per Dockerfile. I didn't find a way to solve this issue without splitting up the current Dockerfile.

**Comment by teor2345** [comment]
Note from the engineering sync: This seems risky to do between the last release candidate and the first stable release. We don't have automated tests that check this functionality.

**Comment by teor2345** [comment]
> We need to enable the passing of `network.network`
> In order to do this, we need to use the ENTRYPOINT instruction for the runtime target in the Dockerfile

These parts are done in PR #6842, but the mining config still needs to be added to the new entrypoint script.

**Comment by upbqdn** [comment]
> We're using this instruction already for the testing target, and there can be only one ENTRYPOINT instruction per Dockerfile. I didn't find a way to solve this issue without splitting up the current Dockerfile.

I had this wrong. There can be multiple `ENTRYPOINT` instructions that will have effect, despite the official docs saying:

> Only the last `ENTRYPOINT` instruction in the Dockerfile will have an effect.

The docs apparently don't consider multistage builds, which I hadn't realized.
