### ISSUE TITLE
Inconsistent management of ports in the Dockerfile

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#6759]
## Motivation

- I noticed we set the ports for `metrics` and `tracing` for Zebra in the Dockerfile (https://github.com/zcashfoundation/zebra/blob/3706ff6e67e3214a7acc8beb98dacd878771f0ab/docker/Dockerfile#L191-L194), but we don't expose them (https://github.com/zcashfoundation/zebra/blob/3706ff6e67e3214a7acc8beb98dacd878771f0ab/docker/Dockerfile#L198). Note that neither `metrics` nor `tracing` are enabled in our published images, but users could enable them when building the image manually.
- We allow setting an arbitrary RPC port (https://github.com/zcashfoundation/zebra/blob/3706ff6e67e3214a7acc8beb98dacd878771f0ab/docker/Dockerfile#L189), which seems like a redundant overhead because users can pick any port when they are publishing the ports at runtime.

**Comment by teor2345** [comment]
> * We allow setting an arbitrary RPC port ([zcashfoundation/zebra@`3706ff6`/docker/Dockerfile#L189](https://github.com/zcashfoundation/zebra/blob/3706ff6e67e3214a7acc8beb98dacd878771f0ab/docker/Dockerfile#L189)), which seems like a redundant overhead because users can pick any port when they are publishing the ports at runtime.

Could this be useful if someone is using our Dockerfile as a base for a RPC client Dockerfile?

**Comment by upbqdn** [comment]
I've never needed that, but I've never used Docker in any advanced scenarios.

However, I noticed that now we expose a user-set RPC port at build time here https://github.com/zcashfoundation/zebra/blob/c058f77a342d5513420f50542593c11e76731a87/docker/Dockerfile#L177, and then we use a user-set RPC port at runtime here https://github.com/zcashfoundation/zebra/blob/c058f77a342d5513420f50542593c11e76731a87/docker/runtime-entrypoint.sh#L52. These two ports can differ since the user can set a port at runtime that will differ from the one used at build time.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6759?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn
