### ISSUE TITLE
Model errors in service transcripts.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#676]
Right now the service `Transcript` can't check that requests fail, only that they succeed, because the transcript is a list of request/response pairs, not a list of request/result pairs. This could probably be fixed by changing
```rust
pub struct Transcript<R, S, I>
where
    I: Iterator<Item = (R, S)>,
```
to
```rust
pub struct Transcript<R, S, E, I>
where
    I: Iterator<Item = (R, Result<S, E>)>,
```
so that the transcript is of responses or errors, but I'm not sure what the right way to change the check function is.

Currently it's
```rust
impl<R, S, I> Transcript<R, S, I>
where
    I: Iterator<Item = (R, S)>,
    R: Debug,
    S: Debug + Eq,
{
    pub async fn check<C>(mut self, mut to_check: C) -> Result<(), Report>
    where
        C: Service<R, Response = S>,
        C::Error: Debug,
    { /* ... */ }
}
```
but the obvious change to
```rust
impl<R, S, E, I> Transcript<R, S, E, I>
where
    I: Iterator<Item = (R, S)>,
    R: Debug,
    S: Debug + Eq,
    E: Debug + Eq,
{
    pub async fn check<C>(mut self, mut to_check: C) -> Result<(), Report>
    where
        C: Service<R, Response = S, Error = E>,
    { /* ... */ }
}
```
isn't right because most errors aren't `Eq`, it's not clear what that would mean anyways, and many errors are extremely inconvenient to construct outside of their normal context.

If we don't care about testing **specific** facts about an error, but just that an error occurred, then rather than adding an extra error type `E`, we could instead change the `Transcript` definition to
```rust
pub struct Transcript<R, S, I>
where
    I: Iterator<Item = (R, Option<S>)>,
```
and use `Result::ok` on the result of the service call to check for the *presence* of an error rather than the details of the error.

**Comment by yaahc** [comment]
I'd like to get something more specific than the presence of an error. I'm thinking we might be able to use closures to handle the check `fn(Box<dyn Error + 'static>) -> bool`, that plus the `Result` on the inputs you end up with this:

```rust
    vec![
        // Insert higher block first, lower block second
        (
            Request::AddBlock { block: block1 },
            Ok(Response::Added { hash: hash1 }),
        ),
        (
            Request::AddBlock { block: block0 },
            Ok(Response::Added { hash: hash0 }),
        ),
        (
            Request::GetTip,
            Err(|e| {
                e.downcast_ref::<zebra_state::Error>()
                    .map(|e| matches!(...))
                    .unwrap_or(false)
            }),
        ),
    ]
```

**Comment by yaahc** [comment]
Also, I assigned this one to myself because I'm interested in working on it :3

**Comment by hdevalence** [comment]
@yaahc great, go nuts! I think the priority should be making it really ergonomic to specify errors in transcripts so that it's easy to write tests. The example you wrote looks nice.
