### ISSUE TITLE
Test every command as part of our CI

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#677]
We should test every command as part of our CI:
- [ ] ~Connect~ (will be removed)
- [ ] Generate
- [ ] Help
- [ ] Revhex modes:
  - [ ] command-line option
  - [ ] stdin
- [ ] Seed (might be combined with Start)
- [ ] Start
- [ ] Version
- [ ] No Command Line Arguments - shows Help

This is not an urgent task, but we should do it for our second release.

**Comment by hdevalence** [comment]
Abscissa has tooling for running tests of commands that we can probably use for some of this (we stripped out the example tests because we weren't using them).

**Comment by teor2345** [comment]
I think it's also useful to test each command from the command-line, to make sure we haven't broken the interface or startup behaviour.

**Comment by hdevalence** [comment]
Yep, sorry, that's what I meant — the Abscissa test runners actually run the commands and you can enforce behavior about their outputs, etc. in the test code.

**Comment by oxarbitrage** [comment]
I know this is not priority but i started some work here and will need some comments in the PR https://github.com/ZcashFoundation/zebra/pull/690 . No rush at all but please take a look when you can. Thanks!

**Comment by oxarbitrage** [comment]
Closed by https://github.com/ZcashFoundation/zebra/pull/690
