### ISSUE TITLE
Restore 'version' subcommand

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#6823]
## Motivation

The `version` subcommand was replaced with a `--version` flag in https://github.com/ZcashFoundation/zebra/pull/6801.

We want to support both so that `zebrad version` will have the same output as `zebrad --version`.

**Comment by teor2345** [comment]
This didn't make the release cut-off, so did you want to close it and just call it a breaking change in a pre-release?

**Comment by teor2345** [comment]
I think we've missed our release cutoff for this one. Users can use `zebrad --version` instead.
