### ISSUE TITLE
Restore macOS tests

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6824]
We have an issue with macOS tests and the last rust version upgrade (1.70). We don't know exactly what test is failing nor why so we [disabled all macOS tests](https://github.com/ZcashFoundation/zebra/pull/6825) for now as we are not supporting it in the first stable release.

This ticket is for researching whats going on and potentially restore the tests if possible.

**Comment by teor2345** [comment]
> We don't know exactly what test is failing nor why

One of the state tests is failing, likely because the RocksDB database shutdown code is not running at the correct time during `zebra-state` shutdown. (We've seen this issue before in the state.)

**Comment by teor2345** [comment]
I added this to the list of tasks in the original bug #6812
