### ISSUE TITLE
Use testnet blocks in the unit tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#683]
At the moment, zebra-test only has mainnet test vectors.

Let's add some testnet blocks to zebra-test, and use them in the tests:
- [x] Add testnet blocks to zebra-test
- [ ] Update zebra-chain tests
- [ ] Update zebra-state tests
- [ ] Update zebra-consensus tests

Let's use a different PR for each crate where we update the tests.

It might be helpful to have utility functions that:
* return the genesis block data, based on the network,
* return all the test vector block data for a network
* return all the test vector block data, regardless of the network

It might also be helpful to re-write some of our tests to take a Network enum parameter.

**Comment by teor2345** [comment]
@oxarbitrage you might be interested in doing this ticket.

**Comment by oxarbitrage** [comment]
Will take it, thanks @teor2345

**Comment by teor2345** [comment]
We've added the testnet blocks, but we still need to use them in more tests.

**Comment by teor2345** [comment]
No-one is working on this ticket at the moment

**Comment by teor2345** [comment]
These tests either got fixed, or they are obsolete.
