### ISSUE TITLE
Re-write the checkpoint list generation scripts in Rust

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#684]
In PR #674, I wrote some bash scripts that get block info using `zcash-cli`, then generate a list of checkpoints.

We should re-write these scripts in Rust, as a bin target in zebra-utils. We'll still have to call `zcash-cli`, but we can parse the output using a Rust json library.

We should be able to re-use some of the CheckpointList and `zebrad revhex` code. We might want to move the revhex code to `zebra-consensus`, and then `zebrad` and `zebra-utils` can use it from there.

**Comment by teor2345** [comment]
@oxarbitrage you might enjoy this ticket.

**Comment by oxarbitrage** [comment]
Nice one, will take it. Thanks.
