### ISSUE TITLE
Support incremental updates to the hard-coded checkpoint lists

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#685]
In PR #674, I wrote some bash scripts that get block info using `zcash-cli`, then generate a list of checkpoints. But getting all that block info can be slow.

We should modify the scripts so that we can give them the most recent checkpoint height, and get back any extra checkpoints.

We might want to re-implement the scripts in Rust (see #684) before doing this ticket. But if we decide to update the checkpoint lists before the alpha release, an incremental update will be a lot faster.

Edit: I split off zebra-based checkpoint generation into #795.

**Comment by hdevalence** [comment]
Just to clarify, by incremental updates to the hard-coded lists, you mean a change to the process that we use to generate the checkpoint lists in our source tree (as opposed to updating the lists in released binaries), correct?  You mentioned before that the script can take quite a while to run.  Do you know how slow the generation process has to be for this to be a problem worth solving, vs the simpler / current method of just generating them from scratch each time?

**Comment by teor2345** [comment]
I mean "generate just the extra checkpoints, add them to the end of the current hard-coded list, and put the new list in the next release".

If we're updating the list every month or so, I think it's ok for 2 people to let the checkpoint scripts run overnight for testnet and mainnet, and then we could cross-check the results. (Long-term, it might be nice to automate the list generation, so it just runs as a build every week or so.)

If there's a testnet rollback, we'll need to regenerate that list pretty fast. But we can always just truncate the list to the rollback height.

**Comment by teor2345** [comment]
I think the slow part is zcash-cli, but it might also be all the shell processes or jq.

As a much faster alternative, we could make a synced Zebra generate a list from its current set of blocks.

So I'd rather implement that feature, because it could share a lot of Rust code with the Zcash-based tool.

**Comment by yaahc** [comment]
I think this might be something we can include in the automated release process https://github.com/ZcashFoundation/zebra/issues/755

**Comment by teor2345** [comment]
Generating checkpoints using the Rust checkpoint tool takes less than an hour, so this ticket is a very low priority.

It might also be useful to be able to compare checkpoints generated by zcashd and zebrad. Or generate checkpoints only using zebrad. So this feature will have other benefits.
