### ISSUE TITLE
Enable logging on Google Cloud continuous delivery instances

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6861]
## Motivation

Currently logging doesn't work on these instances: they just show a few instance security logs at startup.

This is urgent because it impacts final release candidate testing.

### Reference

The service account might not have enough permissions:
https://stackoverflow.com/questions/59188515/gcloud-compute-instances-create-with-container-not-logging-to-stackdriver/66466152#66466152

Or the rest of this checklist:
https://cloud.google.com/logging/docs/agent/logging/troubleshooting

This requires Google Cloud admin permissions.

### Testing

1. Change the CD_LOG_FILE repository variable to an empty string
2. Manually run this workflow: https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-delivery.yml
3. Check that the instance logs some `zebrad` logs

## Related Work

Discovered as part of:
- #6842

**Comment by gustavovalverde** [comment]
I've added the following permissions to our instance deployer SA:
-  roles/errorreporting.user
- roles/logging.logWriter
- roles/monitoring.metricWriter

Even though the lack of permissions was an actual issue to solve, the instances are not logging `zebrad` logs as the container in the instances are not being started at all:

```
Jun 08 15:16:01 zebrad-main-testnet-2270 konlet-startup[605]: 2023/06/08 15:15:59 No containers created by previous runs of Konlet found.
Jun 08 15:16:01 zebrad-main-testnet-2270 konlet-startup[605]: 2023/06/08 15:15:59 Found 1 volume mounts in container zebrad-main-0ffa47c-testnet declaration.
Jun 08 15:16:01 zebrad-main-testnet-2270 konlet-startup[605]: 2023/06/08 15:15:59 Error: Failed to start container: Volume pd-0: Could not determine if the GCE Persistent Disk zebrad-cache-0ff>
Jun 08 15:16:01 zebrad-main-testnet-2270 konlet-startup[605]: 2023/06/08 15:15:59 Saving welcome script to profile.d
Jun 08 15:16:03 zebrad-main-testnet-2270 systemd[1]: konlet-startup.service: Main process exited, code=exited, status=1/FAILURE
Jun 08 15:16:03 zebrad-main-testnet-2270 systemd[1]: konlet-startup.service: Failed with result 'exit-code'.
```

I'm troubleshooting this one

**Comment by gustavovalverde** [comment]
The disk issue is not new, I reopened that ticket: https://github.com/ZcashFoundation/zebra/issues/5644

**Comment by teor2345** [comment]
> the instances are not logging `zebrad` logs as the container in the instances are not being started at all:

Sometimes they are, I checked by logging into the container:
https://github.com/ZcashFoundation/zebra/pull/6842#issuecomment-1581666225

**Comment by teor2345** [comment]
This got fixed.
