### ISSUE TITLE
Zcash listener ports of CD instances are not open to the internet 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6862]
## Motivation

I launched an instance using https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-delivery.yml and then tried to connect to its Zcash listener port using:
```sh
nc -v -z 34.73.3.145 8233
```

`nc` did not give any response and did not finish, indicating that packets to that address are being dropped.

### Priority

This is required for final release candidate testing.

### Specifications

The default Zcash listener ports are 8233 for mainnet and 18233 for testnet.

### Testing

Repeat the same tests given in the description.

**Comment by mpguerra** [comment]
@gustavovalverde did we fix this one yet and are we waiting for the zebra stable release to test that the fix worked?

**Comment by gustavovalverde** [comment]
@mpguerra not fixed yet, I'm tracking this

**Comment by gustavovalverde** [comment]
Tested with our latest deployed instance:

```shell
nc -zvw100 34.148.121.77 8233 
Connection to 34.148.121.77 port 8233 [tcp/*] succeeded!
```

**Comment by gustavovalverde** [comment]
Adding testnet as reference:

```shell
nc -zvw100 34.75.179.82 18233
Connection to 34.75.179.82 port 18233 [tcp/*] succeeded!
```

**Comment by teor2345** [comment]
I also tested my custom instance that I deployed for other teams to do testnet testing:
```sh
nc -G 5 -z 34.73.237.65 18233
Connection to 34.73.237.65 port 18233 [tcp/*] succeeded!
```
