### ISSUE TITLE
Enable iap.tunnelInstances.accessViaIAP for Zebra dev instances

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6863]
## Motivation

When I use in-browser SSH to a CD VM instance, I get this message:

> Please consider adding the IAP-secured Tunnel User IAM role (iap.tunnelInstances.accessViaIAP) to start using Cloud IAP for TCP forwarding for better performance. 

SSH performance is also very slow, a few characters per second.

This should be changed for all Zebra developer instances: CI and CD.

### Testing

Click "SSH" next to a Zebra dev instance, and check for this message.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6863?planning-poker) with Zenhub @arya2 @gustavovalverde @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I don't think we use web-based cloud SSH that often, is this really worth fixing?

Let's check with the team to see if anyone is using it frequently, and if the performance matters to them. (I am most likely to be impacted because where I live has high latency to our GCP zones.)

**Comment by teor2345** [comment]
Here's the answers from the engineers:
https://zfnd.slack.com/archives/CNAP6K8V9/p1696884437137429

**Comment by gustavovalverde** [comment]
Connecting from the machine using GCP's CLI should be the prefered way to do this, and we should instead document how to connect to the instances from our local machines
