### ISSUE TITLE
Tracking: Automatically open an issue when a scheduled or triggered job fails

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6864]
## Motivation

We have to manually check for failures in CI jobs. But we could save ourselves a lot of work by automatically opening or updating a ticket instead:
https://github.com/marketplace/actions/failed-build-issue

### Slack Integration

For each new label, run this command in the `#zebra-dev` channel:
```
/github subscribe ZcashFoundation/zebra +label:"(new label name)"
```

https://github.com/integrations/slack#subscribe-to-an-organization-or-a-repository

### List of Jobs

CI Docker:
- [x] scheduled jobs
- [x] main branch merges (`push: - main` in GitHub workflows)
- [x] manual workflow dispatch

Other workflows (in rough priority order):
- [x] #7678
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-delivery.yml
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/release-binaries.yml
- [x] #7679
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/release-crates-io.yml
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-integration-os.yml
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/build-crates-individually.yml

These workflows rarely fail (lower priority):
- [x] #7680
- [x] #7681
- [x] #7798

Manual workflow dispatch can be automatically handled by using the "not a PR" condition.

### Out of Scope

<details>

<summary>these workflows are out of scope</summary>

 project management workflows are unlikely to fail:
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/project-management.yml

unused/untested manual dispatch workflows:
    - https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/zcashd-manual-deploy.yml

Patch workflows are also unlikely to fail.
Callable workflows fail the calling workflow, so the calling workflow can open a ticket if needed.

</details>

### Complex Code or Requirements

We should not open a ticket on PR failures, the PR author should check and deal with those.
For manual dispatch we might only want to open a ticket for `main` branch workflows.

### Testing

Deliberately cause a failure in a job, and make sure a ticket gets opened or updated.

## Related Work

This will help simplify our release checklist.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6864?planning-poker) with Zenhub @arya2 @dconnolly @gustavovalverde @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
Is this an issue for @gustavovalverde or should anyone else in the zebra team be able to do this?

**Comment by teor2345** [comment]
> Is this an issue for @gustavovalverde or should anyone else in the zebra team be able to do this?

I didn't know the answer to this question, so I spent 15 minutes trying it out for one workflow in PR #7565.

If that works, then anyone can copy it. If it doesn't, we might need Gustavo to help work out why. But let's merge it and see!

**Comment by teor2345** [comment]
I also made a list of the remaining workflows, and made some of them lower priority. Is it worth splitting them into a separate ticket?

**Comment by teor2345** [comment]
> > Is this an issue for @gustavovalverde or should anyone else in the zebra team be able to do this?
> 
> I didn't know the answer to this question, so I spent 15 minutes trying it out for one workflow in PR #7565.

It seems to work:
https://github.com/ZcashFoundation/zebra/pull/7565#issuecomment-1722610567

So anyone can copy the changes in that PR into the 5 other workflows that run on `main`.

**Comment by teor2345** [comment]
I moved this from ticket #5574 because it depends on the label name:

### Slack Integration

For each new label, run this command in the `#zebra-dev` channel:
```
/github subscribe ZcashFoundation/zebra +label:"(new label name)"
```

**Comment by teor2345** [comment]
After the recent workflow splits and name changes, I updated the open tickets in this tracking issue.

**Comment by mpguerra** [comment]
We've done all we're going to do for now
