### ISSUE TITLE
RPC connection closed by Zebra during sending_transactions_using_lightwalletd test

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6867]
## Motivation

The `sending_transactions_using_lightwalletd` test occasionally fails with a "connection closed" or "connection refused" error:
> {"app":"lightwalletd","error":"Post \"[http://127.0.0.1:39183\](http://127.0.0.1:39183/)": read tcp 127.0.0.1:37352-\u003e127.0.0.1:39183: read: connection reset by peer","level":"fatal","msg":"error zcashd getbestblockhash rpc","time":"2023-06-08T01:52:28Z"}

https://github.com/ZcashFoundation/zebra/actions/runs/5205948564/jobs/9392912256?pr=6842#step:8:384

Zebra just seems to keep on running, without logging any errors.

We could try adding extra logs or extra waits when the `zebrad` or `lightwalletd` processes in these tests fail?
This might be tricky because we're seeing a test panic, rather than a test error.

We could also remove this error from the lightwalletd error list, and see if the test passes. (It probably won't, because `lightwalletd` says it's a fatal error. But it might give us more time to see Zebra's logs.)

### Complex Code or Requirements

This is probably a `zebrad` RPC concurrency bug or a test harness concurrency bug.

### Testing

This is going to be very tricky to reproduce and test.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6867?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
@mpguerra we've only seen this happen once every few weeks, maybe it should be a low priority? (Feel free to switch it back.)

**Comment by mpguerra** [comment]
that's fine, we should use the opportunity that we'll be working on lightwalletd RPC methods to try to fix this if it comes up. Otherwise I will un-schedule if it's not finished by the time we're done with our RPC changes.

**Comment by teor2345** [comment]
This failed again in the merge queue in PR #6992:
https://github.com/ZcashFoundation/zebra/actions/runs/5305905415/jobs/9603454438?pr=6992#step:8:547

**Comment by teor2345** [comment]
We haven't seen this happen since PR #7103 was merged, so I'm going to assume it was fixed by that PR.

**Comment by teor2345** [comment]
PR #7229 might also have had this happen in the `getblocktemplate` RPC test

**Comment by mpguerra** [comment]
un-scheduling and closing for now
