### ISSUE TITLE
Rewrite future work section of the README before stable release

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#6872]
https://github.com/ZcashFoundation/zebra#future-work

> The Zebra team is currently working towards an audited stable release.
> 
> We will continue to add new features as part of future network upgrades, and in response to community feedback.

The first sentence need to be removed and the second one maybe adjusted for new goals ?

**Comment by teor2345** [comment]
Let's replace the first part with a link to the audit report when it has been published?
We might want to put it in the section that links to the specifications.

For the second part I know our next goal is #6642, but we haven't decided what comes after that. Do we want to keep an up to date list of goals in the readme, or is there a better place for it? Like blog posts?

**Comment by mpguerra** [comment]
> Let's replace the first part with a link to the audit report when it has been published? We might want to put it in the section that links to the specifications.
> 
> For the second part I know our next goal is #6642, but we haven't decided what comes after that. Do we want to keep an up to date list of goals in the readme, or is there a better place for it? Like blog posts?

I would remove the first sentence and leave the second sentence as is. It's ok to keep it vague and not keep updating our goals as they change. If we want to be more transparent I think there are better ways to do so than updating a sentence at the end of our README :)

**Comment by teor2345** [comment]
This was done in PR #6877.
