### ISSUE TITLE
Release blocker: zebrad v1.0.0-rc.9 panics at start

### ISSUE THREAD

**Issue by autotunafish** [ZcashFoundation/zebra#6879]
### What happened?

I expected to see this happen:
Upgrading to v1.0.0-rc.9 with the normal command 
'cargo install --locked --git `https://github.com/ZcashFoundation/zebra` --tag v1.0.0-rc.9 zebrad'
and running
'zebrad',
the node should start and run normally as before.

Instead, this happened:

The program successfully upgrades but panics at launch before the node starts with 
'thread 'main' panicked at 'VERGEN_GIT_DESCRIBE without a hash "9959a6c" must be valid semver 2.0', zebrad/src/application.rs:56:21'

### What were you doing when the issue happened?

upgrading
'cargo install --locked --git `https://github.com/ZcashFoundation/zebra` --tag v1.0.0-rc.9 zebrad'
run
'zebrad'

### Zebra logs

The node does not start but this is the BACKTRACE of the output

john@john-Latitude-5490:~$ RUST_BACKTRACE=full zebrad
thread 'main' panicked at 'VERGEN_GIT_DESCRIBE without a hash "9959a6c" must be valid semver 2.0', zebrad/src/application.rs:56:21
stack backtrace:
   0:     0x564ab05a6a1d - std::backtrace_rs::backtrace::libunwind::trace::h9a6b80bbf328ba5d
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564ab05a6a1d - std::backtrace_rs::backtrace::trace_unsynchronized::hd162ec543a11886b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564ab05a6a1d - std::sys_common::backtrace::_print_fmt::h78a5099be12f51a6
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564ab05a6a1d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha1c5390454d74f71
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x564ab02b273f - core::fmt::write::h9ffde816c577717b
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/fmt/mod.rs:1254:17
   5:     0x564ab05a3215 - std::io::Write::write_fmt::h88186074961638e4
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/io/mod.rs:1698:15
   6:     0x564ab05a67f5 - std::sys_common::backtrace::_print::h184198273ed08d59
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x564ab05a67f5 - std::sys_common::backtrace::print::h1b4d8e7add699453
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x564ab05a7f0e - std::panicking::default_hook::{{closure}}::h393bcea75423915a
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:269:22
   9:     0x564ab05a7cee - std::panicking::default_hook::h48c64f31d8b3fd03
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:288:9
  10:     0x564ab05a83db - std::panicking::rust_panic_with_hook::hafdc493a79370062
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:691:13
  11:     0x564ab05a82e6 - std::panicking::begin_panic_handler::{{closure}}::h0a64bc82e36bedc7
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
  12:     0x564ab05a6f26 - std::sys_common::backtrace::__rust_end_short_backtrace::hc203444fb7416a16
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x564ab05a8082 - rust_begin_unwind
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
  14:     0x564ab011b3b3 - core::panicking::panic_fmt::h0f6ef0178afce4f2
                               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  15:     0x564ab0ad4278 - zebrad::application::app_version::h315e56eee4eeeb97
  16:     0x564ab0ad4b78 - <zebrad::application::ZebradApp as abscissa_core::application::Application>::register_components::he125a07f9a7696ca
  17:     0x564ab0aaf1e7 - abscissa_core::application::Application::run::h2fd709597dc91d40
  18:     0x564ab0ad8522 - zebrad::application::boot::h97eaa0f94349fb59
  19:     0x564ab0b77a6e - zebrad::main::hbdea60afcf3654ce
Aborted (core dumped)

### Zebra Version

zebrad v1.0.0-rc-9

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Linux john-Latitude-5490 5.4.0-150-lowlatency #167-Ubuntu SMP PREEMPT Mon May 15 18:08:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Additional information

Unsure, maybe related to the abcsissa version (is mentioned in the panic BACKTRACE)? or lack thereof? All three devices tested worked with previous versions of zebrad, rc8 was reinstalled on these devices and do work so the issue appears isolated to the new rc9 version. 

Talking with Marek who was unable to reproduce the issue, explains the error originates here  https://github.com/ZcashFoundation/zebra/blob/0ffa47cc1e81695e5e79a052dd79885e5283f90d/zebrad/src/application.rs#LL57C1-L57C1 and seems because of a lack of a version but it contains a hash.
 
"I can't reproduce the issue. Can you pull the Zebra repo on the machine where it happens, and run
git describe --tags
in the repo?"
"cloning the repo and running that gets 'v1.0.0-rc.9-5-g0ffa47cc but I'm not sur if thats what you meant' "
"The vergen_git_describe variable should contain a string like the one from the git describe you sent, but for some reason it contains only the hash."

Attempt was made at quickly getting more info about the error but was I unsuccessful at applying the test changes
"suggestion that I thought of. If you want, try adding
    panic!("VERGEN_GIT_DESCRIBE {vergen_git_describe:?}");
to this line https://github.com/zcashfoundation/zebra/blob/0ffa47cc1e81695e5e79a052dd79885e5283f90d/zebrad/src/application.rs#L41, compile, and run."
and
"Or try
    let vergen_git_describe: &str = env!("VERGEN_GIT_DESCRIBE");
here https://github.com/zcashfoundation/zebra/blob/0ffa47cc1e81695e5e79a052dd79885e5283f90d/zebrad/src/application.rs#L40 and
    match vergen_git_describe {
here https://github.com/zcashfoundation/zebra/blob/0ffa47cc1e81695e5e79a052dd79885e5283f90d/zebrad/src/application.rs#L42 and see if that resolves the issue."

"Well I just rebuilt rc8 and it starts up no problem so whatever it is is isolated to the new version. My config errors I think had to do with how I was trying to build zebra after I had added those lines to my own fork and was just being weird so idk if I can test that."

**Comment by teor2345** [comment]
This is a release blocker.

**Comment by teor2345** [comment]
I think we'd be better to rewrite this code so any parsing failures fall back to the cargo version, rather than panicking. I'll go do that now.
