### ISSUE TITLE
Change `ContextuallyVerifiedBlockWithTrees` into an enum to correctly represent verification statuses

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6912]
## Motivation

`ContextuallyVerifiedBlockWithTrees` actually represents two different types with two different verification statuses. This is a maintainability issue.

### Design Background

Blocks from the checkpoint verifier are checkpoint-verified: they are semantically verified, but their transaction authorizing data isn't bound to their header.

Blocks from the non-finalized state are contextually verified: their transaction authorizing data is bound to their header. (And their trees have been calculated.)

### Complex Code or Requirements

The consensus code is correct, but the names and types we're using could cause bugs during future changes.

### Design

The current code is:
https://github.com/ZcashFoundation/zebra/blob/c058f77a342d5513420f50542593c11e76731a87/zebra-state/src/request.rs#L277-L282

The different verification statuses can be represented using an enum:
```rust
pub enum FinalizableBlock {
    Checkpoint {
        checkpoint_verified: CheckpointVerifiedBlock
    },
    Contextual {
        contextually_verified: ContextuallyVerifiedBlock,
        treestate: Treestate,
    }
}
```

Here are some example code changes that we could do:

In the match statement in `commit_finalized_direct()`:
- `FinalizableBlock::Checkpoint { checkpoint_verified }` replaces `ContextuallyVerifiedBlockWithTrees { checkpoint_verified, treestate: None }`
- `FinalizableBlock::Contextual { contextually_verified,  treestate }` replaces `ContextuallyVerifiedBlockWithTrees { checkpoint_verified, treestate: Some(treestate) }`

The `Checkpoint` case can construct a `ContextuallyVerifiedBlockWithTrees` from the checkpoint block and the trees in `commit_finalized_direct()`. Then the rest of the finalized state can use `ContextuallyVerifiedBlockWithTrees` instead of passing separate `finalized, history_tree, note_commitment_trees` arguments.

### Testing

Our existing tests should cover this change.

## Related Work

This is part of:
- #6680

**Comment by mpguerra** [comment]
@upbqdn can you please add an estimate here?
