### ISSUE TITLE
Rename tower-batch to tower-batch-control in .github

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6914]
## Motivation

In PR #6907, these files got skipped:
- [ ] .github/PULL_REQUEST_TEMPLATE/release-checklist.md
- [ ] .github/CODEOWNERS

This impacts review auto-assignments and the next release after 1.0.0. They are not a release blocker for 1.0.0, so I approved the PR and opened a follow-up ticket.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/6907#pullrequestreview-1473895294_

**Comment by teor2345** [comment]
I did this part so I removed it from the ticket description:

We also need to update the branch protection rules:
- [x] Admin: Add `Build tower-batch-control crate` to the `main` branch protection rules

This might be a testing blocker for 1.0.0.

It's only a blocker if:
- the `tower-batch-control` job starts failing, or
- this crate is modified in another release-blocker PR.

**Comment by dconnolly** [comment]
Has this been resolved now?
