### ISSUE TITLE
Add Zebra crate versions to dev-dependencies, to enable crater tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6924]
## Motivation

If we add versions to all of Zebra's dev-dependencies, our crates will get tested by Rust compiler team `crater` runs.

This helps prevent build and test failures caused by future Rust compiler versions.

### Specifications

https://rustc-dev-guide.rust-lang.org/tests/crater.html

Also possibly the restrictions here, if they are still current:
https://www.reddit.com/r/rust/comments/f5xpib/psa_denywarnings_is_actively_harmful/

And we might need optional feature dependencies:
```toml
feature_name = ["optional_dep?/feature_if_dep_activated_by_another_feature"]
```

### Changes

- [ ] Add crate versions to all dev-dependencies on Zebra crates
    - [ ] Remove the tower-batch-control -> zebra-consensus circular dependency by copying those verifiers into tower-batch-control (and copying the tests into zebra-consensus so we're also testing the latest verifier code)
- [ ] Make sure the tests that are on by default:
    - run reasonably fast
    - don't use too much network
    - (check crater docs for any other requirements)

### Testing

This needs testing using `cargo release`, to make sure there aren't any other circular dependencies.

## Related Work

Split off PR #6908 and ticket #6149.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6924?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by bishopcheckmate** [comment]
Hey, I would like to take on that.
I started checking and I think we could at this point just specify `version = "1"` for most relevant crates in `dev-dependencies`. Can you see any downside of this approach? I think it would a bit lower the maintenance burden

**Comment by arya2** [comment]
> Hey, I would like to take on that. I started checking and I think we could at this point just specify `version = "1"` for most relevant crates in `dev-dependencies`. Can you see any downside of this approach? I think it would a bit lower the maintenance burden

Thank you!

It gave me a build error when I tried this, `prerelease package needs to be specified explicitly`, but I don't see any downside here if it works. The maintenance burden should be trivial if it needs to be a specific version.

**Comment by bishopcheckmate** [comment]
indeed it doesn't work for pre-release packages, tho it should work after 1.0.0. Anyway, I'll go with setting specific versions for now

**Comment by bishopcheckmate** [comment]
can you assign this to me please for easier searching?

**Comment by bishopcheckmate** [comment]
Also fyi since #8136 publishing will be blocked by https://github.com/zcash/librustzcash/pull/1083 https://github.com/zcash/librustzcash/pull/1088
