### ISSUE TITLE
Change named zebra version instances to `latest` where possible

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#6939]
## Motivation

When we tag the stable release, we may be able to replace a number of named versions with the `latest` tag instead. This will save us a number of renames and possibly steps in the release checklist. 

e.g in the `README`'s "Getting started" section (https://github.com/ZcashFoundation/zebra#getting-started) we could update the commands to 

`docker run zfnd/zebra:latest`

for Docker and

`cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag latest zebrad`

for installing from source.

### Specifications

We need to investigate and test which of these commands will work with a `latest` tag and which need an actual version number tag.

### Testing

Not all of the commands will work with a `latest` tag, we will need to test each of the commands out after the stable release.

**Comment by teor2345** [comment]
> cargo install --locked --git https://github.com/ZcashFoundation/zebra --tag latest zebrad

There is no git tag `latest`, and we can't make one, because lots of tools assume that git tags never change.

**Comment by teor2345** [comment]
I think the rest of this ticket is closed in PR #6877.
