### ISSUE TITLE
Add note tree size fields to the `getblock` RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6952]
## Motivation

Be compatible with the new `zcashd` RPC fields used by `lightwalletd`.

### Specifications

- New fields are in https://github.com/zcash/zcash/pull/6677/files#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR781-R787

```
"trees": {                 (object) information about the note commitment trees
      "sapling": {             (object, optional)
          "size": n,             (numeric) the total number of Sapling note commitments as of the end of this block
      },
      "orchard": {             (object, optional)
          "size": n,             (numeric) the total number of Orchard note commitments as of the end of this block
      },
},
```

### Complex Code or Requirements

State lookups are concurrent, so we'll need to deal with concurrent database updates where the database overlaps the cloned non-finalized state.

Zebra's RPCs must remain compatible with the latest version of `lightwalletd`. If fields or methods are provided by `zcashd` but not used by `lightwalletd`, Zebra doesn't need to add them.

### Implementation Notes

I think we can implement this using our existing trees, [bridgetree::NonEmptyFrontier::position()](https://docs.rs/bridgetree/latest/bridgetree/struct.NonEmptyFrontier.html#method.position), and `u64 from Position` or `serde::Serialize`

`zcashd` implemented these RPC changes in https://github.com/zcash/zcash/pull/6677

### Testing

New state fields will need:
- [ ] the same tests as the RPCs, if they use a populated state

New fields in existing RPC methods will need:
- [ ] extra checks in existing unit tests
- [ ] snapshot updates (automated, see the snapshot test module for details)
- [ ] extra checks in existing integration tests
- [ ] manual `zcash-rpc-diff` test results in a comment on the PR, to make sure we match `zcashd`

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6952?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I added this missing test to this ticket:
- manual `zcash-rpc-diff` test results in a comment on the PR, to make sure we match `zcashd`
