### ISSUE TITLE
Implement `z_getsubtreesbyindex` RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6954]
### Motivation

We want to implement this new RPC to remain compatible with `lightwalletd`.

### Specifications

Add new state requests for reading subtrees using `read::tree::{sapling, orchard}_subtree_by_index` fns.

```
Returns roots of subtrees of the the given pool's note commitment tree. Each value returned
in the `subtrees` field is the Merkle root of a subtree containing 2^16 leaves.
```

`zcashd` implemented `z_getsubtreesbyindex` in https://github.com/zcash/zcash/pull/6677

New fields are listed in https://github.com/zcash/zcash/pull/6677/files#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR1458-R1475

#### Arguments

```
z_getsubtreesbyindex "pool" start_index ( limit )
Arguments:
1. "pool"        (string, required) The pool from which subtrees should be returned. Either "sapling" or "orchard".
2. start_index   (numeric, required) The index of the first 2^16-leaf subtree to return.
2. limit         (numeric, optional) The maximum number of subtree values to return.
```

#### Fields

```
Result:
{
    "pool" : "sapling|orchard", (string) The shielded pool to which the subtrees belong
    "start_index": n,      (numeric) The index of the first subtree
    "subtrees": [          (array) A sequential list of complete subtrees
        {
            "root": "hash",    (string) Merkle root of the 2^16-leaf subtree
            "end_height": n,   (numeric) height of the block containing the note that completed this subtree
        }, ...
    ]
}
```

### Complex Code or Requirements

State lookups are concurrent, so we'll need to deal with concurrent database updates where the database overlaps the cloned non-finalized state.

Zebra's RPCs must remain compatible with the latest version of `lightwalletd`. If fields or methods are provided by `zcashd` but not used by `lightwalletd`, Zebra doesn't need to add them.

### Testing

Tests are in separate tickets.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6954?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
Can this issue be split up so that multiple people can work on it?

**Comment by teor2345** [comment]
> Can this issue be split up so that multiple people can work on it?

Yes, we can split this ticket. If we merge the RPC implementation in PR #7436, then we can get 2-3 different people to work on the tests.
