### ISSUE TITLE
Create an empty database format update task and format update tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6955]
## Motivation

We want to do in-place format upgrades to the Zebra on-disk database.

### Design

We can make state database format changes by:
- [x] add a "minor" version to the state
- [x] launch a format update task when we open the database
- [x] regularly check if the format upgrade task has finished, and check for panics after it exits
- [x] mark the update as finished when the task finishes
- [x] restart the task if the previous zebrad instance didn't finish updating the format (or if it downgraded the format)

After initial PR review:
- [x] increment the database format patch version
- [x] log the database version as part of the startup/panic logs
- [x] add full disk and running state versions to cached state images in CI

### Tests

- [x] newly created database is not updated / version is not updated on restart
- [x] standard update / state version is incremented
- [x] repeated update only runs once / current version is not updated on restart
- [x] downgrade (best effort compatibility/testing)
- [ ] partial update and restart (TODO in another PR)
- [x] CI workflow changes

## Documentation Follow-Up

In ticket #7215.

## Refactor Follow-Ups

- refactor the `block_write_task` and `format_change_handle` into a generic `std::thread` wrapper.
- move config code to the new format upgrade module

## Debugging Follow-Ups

- add a small log file for debugging database format changes in the state directory, and limit its length

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6955?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@teor2345 should the estimate for this issue be updated?

**Comment by teor2345** [comment]
I split documentation out of this ticket into #7215

**Comment by teor2345** [comment]
> @teor2345 should the estimate for this issue be updated?

Good question!

I think the estimate is correct, it had just taken me a while due to the showcase and getting pulled on to other more urgent audit, network testing, and other bugs. I've also split out the documentation task into ticket #7215, so the overall size of the task will be a few points higher.

(I don't want to do the docs until we've done one or two format changes and made any fixes we need to the implementation.)
