### ISSUE TITLE
Lint warning: missing documentation for zebrad/build.rs main

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#6956]
### What happened?

When building with `-W missing docs`, `zebrad/build.rs` `main()` is lacking docs:

### Zebra logs

```
#21 643.9    Compiling zebrad v0.0.1 (/opt/zebrad/zebrad)
#21 644.0 warning: missing documentation for the crate
#21 644.0  --> zebrad/build.rs:1:1
#21 644.0   |
#21 644.0 1 | fn main() {}
#21 644.0   | ^^^^^^^^^^^^
#21 644.0   |
#21 644.0   = note: requested on the command line with `-W missing-docs`
#21 644.0 
#21 644.2 warning: `zebrad` (build script) generated 1 warning
```

### Zebra Version

1.0.0

**Comment by teor2345** [comment]
This is not a bug, these warnings are caused by `cargo-chef` overwriting some source files so only Zebra's dependencies are built:
https://github.com/LukeMathWalker/cargo-chef#how-to-use

If this was a bug in Zebra, the OS builds would fail, because they deny all warnings, including doc warnings.
