### ISSUE TITLE
zebrad's sync service logs are a bit too verbose

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#698]
`sync:obtain_tips` logs client request timeouts at error level.

I can submit a PR to reduce them to warn or info, but I don't know how to disable the backtraces. (I tried RUST_BACKTRACE, but it doesn't remove the span trace.)

**Comment by yaahc** [comment]
the solution I think is not to prevent the SpanTrace from being captured and instead move the spans to higher log levels so they're disabled by default. also I want to make some changes to the display format to let us print log messages for errors as one line.

**Comment by teor2345** [comment]
I opened PR #703 for the log level downgrade.

I'd like to reduce the network errors to info, but keep the block verify errors at warn. Is there an easy way to do that, when the errors come from the same future result?

**Comment by hdevalence** [comment]
per https://github.com/ZcashFoundation/zebra/pull/703#issuecomment-661989549 , I think we should warn on network errors that we can't handle (i.e., any network errors that propagate upwards into the syncer), but handle all transient network errors.  The problem with the current syncer code is that it doesn't use retry policies to handle network errors, but I'm working on fixing that this morning (bundled with #617 fixes).
