### ISSUE TITLE
Ignore repeated inbound connections from the same IP

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6981]
## Motivation

This prevents some kinds of attacks, by making Zebra skip the handshake for these inbound connections.

Edit: some possible attacks are:
* A single IP can have multiple inbound connections in flight between the inbound connection task and the peer set. (About 3-4 if it uses both timeouts fully.) These connections must be successful to be sent to the peer set.
* A single IP can also deny service to other inbound peers by continually making connections, and hitting the 1 second rate-limit. These connections can be successful, failed, or time out. (So there's no guarantee they will reach the peer set.)

### Complex Code or Requirements

To avoid complex code, we could keep a list in a vector and reset every N seconds.

We could re-use the outbound reconnection interval.

### Testing

Try to make a lot of inbound connections:
- existing tests do this, their asserts can be changed
- we can copy the failing tests and adjust their test data to use different IPs to test this new code

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6981?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn
