### ISSUE TITLE
Don't initiate handshakes to outbound IPs that were recently connected

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#6982]
## Motivation

This prevents some kinds of attacks, by making Zebra skip the handshake for these outbound connections.

Edit: some possible attacks are:
- rapidly repeated outbound reconnections and handshakes to the same IP

### Complex Code or Requirements

Skip addresses in `CandidateSet::next()` if their IPs are recently connected, according to the AddressBook.

The iteration order should be carefully written so this new check is O(n) rather than O(n^2):
> In [computer science](https://en.wikipedia.org/wiki/Computer_science), big O notation is used to [classify algorithms](https://en.wikipedia.org/wiki/Computational_complexity_theory) according to how their run time or space requirements grow as the input size grows.

https://en.wikipedia.org/wiki/Computational_complexity_theory

### Testing

Try to make a lot of outbound connections:
- existing tests do this, their asserts can be changed
- we can copy the failing tests and adjust their test data to use different IPs to test this new code

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/6982?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn
