### ISSUE TITLE
Document Docker build-time & run-time config params

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7008]
## Motivation

We have recently refactored the Dockerfile so that it allows users to specify various parameters when launching their Docker containers. There are also a bunch of parameters that can be specified when building images.

These aren't documented anywhere.

## Suggested Solution

Document the parameters users can set both at build-time and when starting the container.

## Related Work

Issue #6759 might change how we handle Zebra's ports in Docker.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7008?planning-poker) with Zenhub @arya2 @gustavovalverde @oxarbitrage @teor2345 @upbqdn
