### ISSUE TITLE
GitHub Actions error: There was a problem refreshing your current auth token. GitHub Actions is temporarily unavailable

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7015]
## Motivation

I've seen this error on a few PRs recently:
> ERROR: (gcloud.compute.ssh) There was a problem refreshing your current auth tokens: ('Unable to retrieve Identity Pool subject token', '{ "message": "GitHub Actions is temporarily unavailable. Please visit https://www.githubstatus.com/ for the status of our services.", "ref": "Ref A: 28C40F7FA2C5465FB3AD96C4A3038863 Ref B: BN3EDGE0617 Ref C: 2023-06-19T19:58:02Z" }')

https://github.com/ZcashFoundation/zebra/actions/runs/5315173045/jobs/9624283153?pr=6934#step:8:83

### Testing

This might be a tricky one to test.

**Comment by mpguerra** [comment]
Have we seen this again recently? We might want to consider closing if not

**Comment by teor2345** [comment]
Seems like it might have gone away by itself?
