### ISSUE TITLE
Publish next Zebra release v1.0.1

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7021]
# Prepare for the Release

 These release steps can be done a week before the release, in separate PRs.
 They can be skipped for urgent releases.

 ## Checkpoints

 For performance and security, we want to update the Zebra checkpoints in every release.
 - [x] You can copy the latest checkpoints from CI by following [the zebra-checkpoints README](https://github.com/ZcashFoundation/zebra/blob/main/zebra-utils/README.md#zebra-checkpoints).

 ## Missed Dependency Updates

<details>

<summary>This step will be skipped because we have an open ECC crate update PR.</summary>

 Sometimes `dependabot` misses some dependency updates, or we accidentally turned them off.

 This step can be skipped if there is a large pending dependency upgrade. (For example, shared ECC crates.)

 Here's how we make sure we got everything:
 - [ ] Run `cargo update` on the latest `main` branch, and keep the output
 - [ ] If needed, [add duplicate dependency exceptions to deny.toml](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md#fixing-duplicate-dependencies-in-check-denytoml-bans)
 - [ ] If needed, remove resolved duplicate dependencies from `deny.toml`
 - [ ] Open a separate PR with the changes
 - [ ] Add the output of `cargo update` to that PR as a comment

</details>

 # Prepare and Publish the Release

 Follow the steps in the [release checklist](https://github.com/ZcashFoundation/zebra/blob/main/.github/PULL_REQUEST_TEMPLATE/release-checklist.md) to prepare the release:

 Release PR:
 - [x] Update Changelog
 - [x] Update README
 - [x] We need to decide whether this will be a 1.1.0 or 1.0.1 release
 - [x] Update Zebra Versions
 - [x] Update End of Support Height

 Publish Release:
 - [x] Create & Test GitHub Pre-Release
 - [x] Publish GitHub Release
 - [x] Publish Rust Crates
 - [x] Publish Docker Images

**Comment by teor2345** [comment]
I think this will be a 1.0.1 release, I've asked everyone to delay config changes until the next release.

There will be a lot of bug fixes, and some logging changes (the logo and welcome message). But they aren't really features.

The Docker image will have more options, but they aren't documented yet, so I'm happy to call them "experimental" for now.
