### ISSUE TITLE
Broken link to zebra_network and zebra_state Config in docs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7048]
## Motivation

`network: Config` on https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html should link to `zebra_network::Config`. But instead there's an extra `zebra_network` directory in the URL.

`zebra_state::Config` also has the same issue.

### Testing

Look at the generated docs manually.

**Comment by mpguerra** [comment]
This issue seems familiar to me... @oxarbitrage did you try to fix this at some point also?

**Comment by teor2345** [comment]
My guess is that it's caused by how we're importing the Config, and using fewer aliases or importing it directly will fix it.

**Comment by mpguerra** [comment]
Scheduling for next sprint as it seems that this might be needed for external contributors

**Comment by teor2345** [comment]
This bug does not happen on docs.rs, so I think we should direct external contributors to that page:
https://docs.rs/zebrad/latest/zebrad/config/struct.ZebradConfig.html

We might want to stop publishing our external docs entirely, and just use docs.rs. (Our internal docs are still useful because they show private items and experimental features.)

**Comment by mpguerra** [comment]
> We might want to stop publishing our external docs entirely, and just use docs.rs. (Our internal docs are still useful because they show private items and experimental features.)

I'd be happy with not publishing the same external docs in 2 places. Do you want to just change the title of this issue to reflect what we're actually doing or would you rather create a new issue for it?

**Comment by mpguerra** [comment]
Ah, I see #7837 now :D Let's close this as a `wont-fix` then

**Comment by mpguerra** [comment]
Re-opening as we have a PR to fix it for now
