### ISSUE TITLE
Upgrade zcash_script to the latest ECC code & dependencies, and release the crate

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7071]
## Motivation

ECC have updated `zcashd` and its Rust dependencies, so we need to update `zcash_script`'s C++ code and Rust dependencies.

### Instructions

https://github.com/ZcashFoundation/zcash_script/#updating-this-crate

**Comment by mpguerra** [comment]
How's this one different from #6859 ? Is this one of the tasks in order to complete it?

**Comment by teor2345** [comment]
> How's this one different from #6859 ? Is this one of the tasks in order to complete it?

Yes, this ticket is the upgrade and release of the `zcash_script` crate itself, which was completed in https://github.com/ZcashFoundation/zcash_script/pull/91

#6859 is the upgrade to that release in Zebra, along with a lot of other upgrades.
