### ISSUE TITLE
Log a warning when the loaded config includes fields used by elasticsearch feature

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7118]
## Motivation

Zebra currently warns about unused config fields for the flamegraph and metrics features, but panics when compiled without the elasticsearch feature and trying to a load a configuration file with a elasticsearch fields

The existing warnings are logged once Zebra instantiates the components that would use them, they may be more noticeable if logged immediately after it has loaded the config file.

## Possible Design

- Remove feature flags on elasticsearch config fields
- Log warnings about unused config fields after loading the config, either:
    - while loading the config
    - in [`Component::after_config()`](https://docs.rs/abscissa_core/0.7.0/abscissa_core/component/trait.Component.html#method.after_config) on each component
    - in `register_components()` after `load_config()` (maybe in methods on Config structs)
    - in any other code that's shortly after config loading

### Optional Changes

  - Move warnings about unused config fields for flamegraph or prometheus after loading the config

## Drawbacks

Warning and ignoring the unused config fields would be better for some users.

But other users who expect Zebra to fail if the Zebra build doesn't support the config, or the config fields are wrong, will be surprised.

**Comment by teor2345** [comment]
What about the filter-reload feature?

I'd like to split this ticket into separate tickets for mining and elasticsearch, because they are likely to stabilise at different times.

**Comment by arya2** [comment]
> What about the filter-reload feature?

It looks like it would log a warning and skip the filter-reload feature: 

https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/tracing/endpoint.rs#L40
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/tracing/endpoint.rs#L60

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7118?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
> What about the filter-reload feature?
> 
> I'd like to split this ticket into separate tickets for mining and elasticsearch, because they are likely to stabilise at different times.

@mpguerra since we're about to stabilise `getblocktemplate-rpcs`, I'd like to remove it from this ticket.

**Comment by mpguerra** [comment]
un-scheduling for now
