### ISSUE TITLE
Fix CI failures in checkpoint generation log regex

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7123]
## Motivation

CI panicked in `wait_for_zebra_checkpoints_generation()`: https://github.com/ZcashFoundation/zebra/actions/runs/5418491535/jobs/9851372930?pr=7090#step:8:219

_Originally posted by @arya2 in https://github.com/ZcashFoundation/zebra/pull/7090#pullrequestreview-1509652219_

### Diagnosis

It looks like this regex might be too strict, Zebra logged a block height in the *9000 range before it was terminated.

**Comment by mpguerra** [comment]
Does this one still need a fix?

**Comment by teor2345** [comment]
Yes, we need to relax the check in the test code so it accepts some range of blocks around the current height. Using a 1000 block range is too short and fails the test, but only rarely.

A 10,000 block range would probably work fine, so would parsing the height and comparing it. There can't be too much of a gap between the current height and the start and end of the check range, otherwise the test will timeout and fail, skip too many checkpoints, or take too long.

**Comment by teor2345** [comment]
This happened again today in PR #7611:
https://github.com/ZcashFoundation/zebra/actions/runs/6280142048/job/17057947498?pr=7611#step:9:269

**Comment by teor2345** [comment]
Just to be clear, I'm not working on this ticket, because we're trying to spread CI work around the team.

**Comment by mpguerra** [comment]
Un-scheduling for now, doesn't seem to be high priority

**Comment by teor2345** [comment]
Just noting that this check will fail CI 40% of the time as soon as blocks get smaller, and we don't control block size. (That's based on the number of transactions.)
