### ISSUE TITLE
warning: package `x25519-dalek v2.0.0-rc.2` in Cargo.lock is yanked

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7133]
## Motivation

We need to upgrade `x25519-dalek` from a yanked version to the latest version. This needs some API changes to avoid calling deprecated methods.

### Related Changes

This was done in PR #7188.

To avoid duplicate dependencies, we might also need:
- https://github.com/ZcashFoundation/ed25519-zebra/pull/76
- an `ed25519-zebra` release
- upgrading to that release in Zebra

### Complex Code or Requirements

This looks like a straightforward change.

### Testing

We have existing tests for this code.

**Comment by mpguerra** [comment]
How urgent is this? I guess it will block the next release?

**Comment by teor2345** [comment]
> How urgent is this? I guess it will block the next release?

Yes, I think it should block the next release. This might mean we need to get started on a ed25519-zebra release too. I'm not sure if its related dependencies are outdated as well.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7133?planning-poker) with Zenhub @arya2 @dconnolly @oxarbitrage @teor2345 @upbqdn @conradoplg

**Comment by mpguerra** [comment]
I seem to remember we did an ed25519-zebra release recently... Was it related to this or do we need to do another one?

**Comment by conradoplg** [comment]
> I seem to remember we did an ed25519-zebra release recently... Was it related to this or do we need to do another one?

I think we're good, the last release updated the `curve25519-dalek` crate which is what was needed IIRC

**Comment by teor2345** [comment]
We upgraded to that ed25519-zebra release in PR #7188.

**Comment by teor2345** [comment]
This has already been fixed in PR #7188, it's the only instance of that dependency:
https://github.com/ZcashFoundation/zebra/blob/9ebd56092bcdfc1a09062e15a0574c94af37f389/Cargo.lock#L5462-L5463
