### ISSUE TITLE
Zebra sometimes panics in the state and network tasks on shutdown

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7170]
### What happened?

I expected to see this happen:

A shutdown with no panics.

Instead, this happened:

> 2023-07-06T02:30:10.476975Z  INFO {net="Test"}: zebrad::components::tokio: waiting for async tokio tasks to shut down TOKIO_SHUTDOWN_TIMEOUT=20s
> The application panicked (crashed).
> Message:  panic in ReadRequest::Tip: JoinError::Cancelled(Id(23437))
> Location: zebra-state/src/service.rs:1208

https://github.com/ZcashFoundation/zebra/actions/runs/5470776835/jobs/9961459769#step:5:347

> 2023-07-10T04:02:08.269874Z  INFO {net="Test"}: zebrad::components::tokio: waiting for async tokio tasks to shut down TOKIO_SHUTDOWN_TIMEOUT=20s
> The application panicked (crashed).
> Message:  panic in next peer address book task: JoinError::Cancelled(Id(9554))
> Location: /opt/zebrad/zebra-network/src/peer_set/candidate_set.rs:407

https://github.com/ZcashFoundation/zebra/actions/runs/5503766375/jobs/10029501421#step:5:326

### What were you doing when the issue happened?

Running Zebra in CI and terminating the process.

### Zebra logs

You can see the full logs at:
https://github.com/ZcashFoundation/zebra/actions/runs/5470776835/jobs/9961459769#step:5:347
https://github.com/ZcashFoundation/zebra/actions/runs/5503766375/jobs/10029501421#step:5:326

### Zebra Version

1.0.1 with PR #7029
1.0.1 with PRs #7177 + #7183 in merge queue PR #7190

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Ubuntu 4   22.04.2 5   LTS GitHub Runner

### Additional information

This is a low priority because the cache is not corrupted, and the user was shutting down anyway. It also causes rare CI failures. (Any tokio update could make them more common.)

Every JoinError::Cancelled in every state and network request will need to be ignored, something like this:
https://github.com/ZcashFoundation/zebra/blob/1014e3c7855df1c53d0bf0ef571d2cecd9b795f8/zebra-network/src/peer_set/initialize.rs#L633-L640

It might be easier to do this using a `CheckForPanic::check_for_panic()` trait method, implemented on `JoinError` (async and thread).

State Metadata:
version: 1.0.1
Zcash network: Testnet
state version: 25
features: default,default_release_binaries,release_max_level_info,sentry
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.70.0
rust release date: 2023-05-31
optimization level: 3
debug checks: false

Network Metadata:
version: 1.0.1
Zcash network: Testnet
state version: 25
features: default,default_release_binaries,release_max_level_info,sentry
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.70.0
rust release date: 2023-05-31
optimization level: 3
debug checks: false

**Comment by teor2345** [comment]
@mpguerra this seems to be happening multiple times a week in CI, can we fix it soon?

If there are other more important tasks, it doesn't need to be scheduled, because it only happens on shutdown and doesn't corrupt data.

**Comment by mpguerra** [comment]
@teor2345 can I please get your estimate on this issue?

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7170?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn
