### ISSUE TITLE
Re-enable coverage jobs on larger runners

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7180]
## Motivation

Coverage jobs are failing during compilation with "no space left on device" errors. They need larger runners (or a change to the compilation arguments) to work.

So we turned coverage off on 10 July 2023. This ticket is about turning it back on.

Larger runners also have a cost. (The default runners are free for open-source projects.) So we'd need to ask ops to set a cost cap for GitHub actions before we use them. Or @gustavovalverde might want to wait to switch to self-hosted runners.

### Steps

- [x] Fix coverage disk space issues
- [ ] Re-enable the coverage job: https://github.com/ZcashFoundation/zebra/actions/workflows/coverage.yml
- [x] Re-enable the coverage patch job: https://github.com/ZcashFoundation/zebra/actions/workflows/coverage.patch.yml
- [ ] Admin: re-enable the coverage job `main` branch protection rule

## Reference

Standard runners have 14 GB of disk space:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

But the smallest "larger runner" has 150 GB:
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners#machine-sizes-for-larger-runners

## Attempted Fixes

> Coverage is a GitHub actions job, it doesn't have any GCP steps: [ZcashFoundation/zebra/actions/runs/5488261146/jobs/10013394589?pr=7174#step:3:1](https://github.com/ZcashFoundation/zebra/actions/runs/5488261146/jobs/10013394589?pr=7174#step:3:1)
> 
> So I think we might need to clear the compiler caches instead: [`main`/book/src/dev/continuous-integration.md#fixing-disk-full-errors-and-zcash-parameter-errors](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md?rgh-link-date=2023-07-09T19%3A22%3A15Z#fixing-disk-full-errors-and-zcash-parameter-errors)

That job also doesn't have any explicit Rust cache steps, but it might have implicit caching, I'm not sure.

I tried clearing all the test caches using `gh api` to access GitHub Actions, and I restarted one of the jobs:
https://github.com/ZcashFoundation/zebra/actions/runs/5488261146

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/7176#issuecomment-1627808845_

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7180?planning-poker) with Zenhub @arya2 @gustavovalverde @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I'm not sure if we're using test coverage metrics in Zebra, so I don't know if this ticket is a priority.

What do other people think? Are we using code coverage for anything?

**Comment by teor2345** [comment]
I don't know how to estimate this ticket accurately, because I don't know how much time or money it will cost to enable larger GitHub runners.

**Comment by arya2** [comment]
> What do other people think? Are we using code coverage for anything?

I don't think it's particularly useful except to build confidence in Zebra's test coverage.

**Comment by gustavovalverde** [comment]
Not planned for now

**Comment by teor2345** [comment]
This ticket wasn't completed: the fixes are in the workflow, but the coverage job isn't running, and the branch protection rule wasn't added.

The coverage job can be re-enabled here:
https://github.com/ZcashFoundation/zebra/actions/workflows/ci-coverage.yml

The dev docs have instructions for branch protection rules.

**Comment by teor2345** [comment]
@mpguerra should I have opened a new ticket instead? I just realised this one was already estimated and closed.

**Comment by mpguerra** [comment]
> @mpguerra should I have opened a new ticket instead? I just realised this one was already estimated and closed.

No, this is great, thank you!

**Comment by gustavovalverde** [comment]
Done enabling the workflow, and adding the rules.

**Comment by gustavovalverde** [comment]
This issue has resurfaced. The same 'no space left on device' error is now affecting Docker builds due to a GitHub Actions runner image update (from `20251102` to `20251112`).

See #10126 for the current tracking and proposed solution using configurable larger runners via repository variables.
