### ISSUE TITLE
Check that the note commitment tree RPC serialization format hasn't changed in zcashd 5.6.0

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7201]
## Motivation

This is a double-check of the scope of the `lightwalletd` RPC upgrade. We can use `zcash-rpc-diff` to do this test.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7201?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by oxarbitrage** [comment]
I am checking the differences between zcashd and zebra in regards to note commitment serialization in rpc methods, specifically after zcashd 5.6.0 where serde was disabled.

In https://github.com/ZcashFoundation/zebra/pull/7053 we were able to remain compatible with previous zebrad and zcashd versions by not changing the internal serialization. This serialization is then also used in rpc methods(`z_gettreestate`). We are unsure if zcashd did the same or other similar process to keep in line with this, we want to double check this.

We are using the `zcash-rpc-diff` zebra utility to query some blocks and check if some fields match.

First, we need to consider that the `z_gettreestate` in zebra do not have all the same fields than zcashd, specifically:


- zebra do not display sprout commitments at all.
- zebra do not display `finalRoot` field in sapling and orchard commitments.

So, we are after the `finalState` fields of the sapling and orchard commitments differences.

Here is a difference, but i think is unrelated:


    ./zcash-rpc-diff 6666 z_gettreestate 2

`zcashd` displays data when `finalState` is 0 while zebrad avoid them altogether.


![](https://paper-attachments.dropboxusercontent.com/s_357D23258F1E669FD762ED385EF67E8591F2B08AED5554E2CF1883CD982D68E9_1691676489918_diff1.png)


Another block with spout only commitments:


    ./zcash-rpc-diff 6666 z_gettreestate 12345


![](https://paper-attachments.dropboxusercontent.com/s_357D23258F1E669FD762ED385EF67E8591F2B08AED5554E2CF1883CD982D68E9_1691683831513_diff2.png)


Lets check a block with sapling commitments:


    ./zcash-rpc-diff 6666 z_gettreestate 1500002


![](https://paper-attachments.dropboxusercontent.com/s_357D23258F1E669FD762ED385EF67E8591F2B08AED5554E2CF1883CD982D68E9_1691683907162_diff3.png)


The above looks good, sprout is omitted altogeher as we know, also `finalRoot` field is not supported in zebra, orchard commitments are ignored when the `finalState`  field is zero in zebra. The most important for us seems to be to check that `finalState` field is the same in both implementations when it is not zero.

A block with orchard commietsments also looks good for us, such as:


    ./zcash-rpc-diff 6666 z_gettreestate 2000002


![](https://paper-attachments.dropboxusercontent.com/s_357D23258F1E669FD762ED385EF67E8591F2B08AED5554E2CF1883CD982D68E9_1691684075152_diff4.png)


Where orchard and sapling `finalState` are the same in both implementations.

I checked several other blocks and they all match in the `finalState` field, for example:


    ./zcash-rpc-diff 6666 z_gettreestate 210000
    ./zcash-rpc-diff 6666 z_gettreestate 210001
    ./zcash-rpc-diff 6666 z_gettreestate 210031
    ./zcash-rpc-diff 6666 z_gettreestate 999999
    ./zcash-rpc-diff 6666 z_gettreestate 0
    ./zcash-rpc-diff 6666 z_gettreestate 1046400
    ./zcash-rpc-diff 6666 z_gettreestate 1046401
    ./zcash-rpc-diff 6666 z_gettreestate 1046407
    ...

I am not sure if we should be looking for something else, if not, then this issue can be closed.

**Comment by mpguerra** [comment]
@upbqdn can you please double check this and then we can close if you're satisfied?

**Comment by teor2345** [comment]
@oxarbitrage I just wanted to double-check what versions of Zebra and `zcashd` you used to do this comparison?

(The versions are in the output of `zcash-rpc-diff`, but they are above the parts you captured in your screenshots.)

**Comment by oxarbitrage** [comment]
I don't think the versions are in the output of `zcash-rpc-diff` but this is maybe something we will want to add?

Here is a full output:

```
oxarbitrage@oxarbitrage:/media/oxarbitrage/4eb53770-4e4f-4d80-a830-0914f3f5b89a/chain/zcash$ ./zcash-rpc-diff 6666 z_gettreestate 2
Checking first node release info...
Checking second node release info...
Connected to zebrad (port 6666) and zcashd (./zcash-cli zcash.conf port).

Checking zebrad network and tip height...
Checking zcashd network and tip height...

Request:
z_gettreestate 2

Querying zebrad main chain at height >=2197222...

real	0m0,003s
user	0m0,000s
sys	0m0,002s

Querying zcashd main chain at height >=2197222...

real	0m0,002s
user	0m0,000s
sys	0m0,002s


Response diff between zcashd and zebrad:
--- /tmp/tmp.FjZABfO7Ma.rpc-diff/zebrad-main-2197222-z_gettreestate.json	2023-08-19 15:45:51.639870382 -0300
+++ /tmp/tmp.FjZABfO7Ma.rpc-diff/zcashd-main-2197222-z_gettreestate.json	2023-08-19 15:45:51.639870382 -0300
@@ -1,5 +1,21 @@
 {
   "hash": "0002a26c902619fc964443264feb16f1e3e2d71322fc53dcb81cc5d797e273ed",
   "height": 2,
-  "time": 1477671626
+  "time": 1477671626,
+  "sprout": {
+    "commitments": {
+      "finalRoot": "59d2cde5e65c1414c32ba54f0fe4bdb3d67618125286e6a191317917c812c6d7",
+      "finalState": "000000"
+    }
+  },
+  "sapling": {
+    "commitments": {
+      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
+    }
+  },
+  "orchard": {
+    "commitments": {
+      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
+    }
+  }
 }
oxarbitrage@oxarbitrage:/media/oxarbitrage/4eb53770-4e4f-4d80-a830-0914f3f5b89a/chain/zcash$ 
```

I can't remember what version i used for `zebrad` when i made those tests, probably the last `main` but i don't know what was that exactly as i deleted the folder, so i am running the same tests again with the last main now, the versions used are:

Zcashd:

```
Thank you for running a mainnet zcashd v5.6.1 node!
```

Zebrad:

```
2023-08-19T18:25:14.945013Z  INFO zebrad::application: Diagnostic Metadata:
version: 1.1.0+36.g92dd528
Zcash network: Mainnet
running state version: 25.1.0
initial disk state version: 25.0.2
features: default,release_max_level_info
branch: main
git commit: 92dd528
commit timestamp: 2023-08-18T02:04:56.000000000Z
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.70.0
rust release date: 2023-05-31
optimization level: 3
debug checks: false
```

All tests provided the same results as the screenshots provided in https://github.com/ZcashFoundation/zebra/issues/7201#issuecomment-1673540705

**Comment by teor2345** [comment]
> I don't think the versions are in the output of `zcash-rpc-diff` but this is maybe something we will want to add?

I made a new ticket #7351 for this.

**Comment by mpguerra** [comment]
are we good here or are there any more checks that we want to do?

**Comment by teor2345** [comment]
> @upbqdn can you please double check this and then we can close if you're satisfied?

I was waiting for @upbqdn, I just wanted to double-check the node versions.

**Comment by upbqdn** [comment]
I'm currently syncing zcashd. I'm at 90%.

**Comment by upbqdn** [comment]
I got the same results as Alfredo for:

```bash
./zcash-rpc-diff 6666 z_gettreestate 2
./zcash-rpc-diff 6666 z_gettreestate 12345
./zcash-rpc-diff 6666 z_gettreestate 1500002
./zcash-rpc-diff 6666 z_gettreestate 2000002
```

I used the current `main` and `master` branches.

**Comment by teor2345** [comment]
Great, let's call this done!
