### ISSUE TITLE
Document how to do in-place upgrades of the state database format

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7215]
## Motivation

In ticket #6955 I implemented a task for in-place state upgrades, but we didn't actually do any upgrades yet. Once we've had some experience with upgrades, I want to write down how to do them.

### Tasks

Add a new dev doc for upgrading the state in-place:
- [x] move the current format out of the state RFC so it's easier to find
- [x] goals
  - avoid a full download and rebuild of the state
  - the previous state format must be able to be loaded by the new state, this is checked by PR tests once, after that the cached state is marked as upgraded
  - the previous zebra version should be able to load the new format, this is checked by other PRs running using the upgraded cached state, if there are any Rust PRs run after the new PR's CI finishes
  - best-effort loading of older supported states by newer Zebra versions
  - best-effort compatibility between newer states and older supported Zebra versions
- [x] design constraints
  - make sure the state can read the old and new formats, it can't panic if the data is missing
  - if Zebra is restarted, the format upgrade will run multiple times, and it must produce the correct format
    - changes should be made in database transactions, or by creating a new column family then enabling it, unless each change is valid by itself
- [x] implementation steps
  - increment the state minor version
  - write the new format in the block write task
  - add format update code in the format update task
  - upgrade failures should be handled by panicking with a message that tells the user to delete their cached state and re-launch Zebra
- [x] add the implementation checklist to each state upgrade ticket

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7215?planning-poker) with Zenhub @arya2 @conradoplg @dconnolly @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
trying something out
