### ISSUE TITLE
Download the genesis block

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#725]
Currently we're not downloading the genesis block. Oops!

**Comment by hdevalence** [comment]
We already have the bytes of the mainnet genesis block, so instead of downloading it we could hardcode the bytes in the binary.  But I'm not sure this is better than just downloading it.

**Comment by hdevalence** [comment]
Oops, for some reason I thought the "close and comment" button was "close comment" and I decided the one above might not be worth writing. So I accidentally closed the issue instead :sweat_smile:
