### ISSUE TITLE
Document useful tracing filters

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#726]
We'd like to be able to trace every nth block, maybe a filter like this would work?

`set -x ZEBRAD_LOG "[block_verify{height=Some(BlockHeight(.*000))}]=trace"`

**Comment by hdevalence** [comment]
I tested that in the hope of tracing every nth block but it doesn't actually work.  I think I'm getting the syntax wrong, or something.  `[block_verify{height=Some(BlockHeight(.*))}]=trace` does select every span, but adding numbers breaks it. I'm not sure exactly how the `tracing-subscriber` regex support works.

**Comment by hdevalence** [comment]
There's a worked example here: https://tokio.rs/blog/2019-08-tracing

**Comment by hawkw** [comment]
the regex support _should_, in theory, support everything the `regex` crate supports... but it’s possible the filtering code is buggy.

**Comment by teor2345** [comment]
@hdevalence have you tried `[block_verify{height=Some(BlockHeight(.*?000))}]=trace`?

`regex` is greedy by default, but think we need the lazy match, so the `000`s after the pattern will match.
https://docs.rs/regex/1.3.9/regex/#repetitions

@hawkw what are the exact text and regex strings that are passed to the `regex` crate?
I'm wondering if the brackets count as capture groups:
https://docs.rs/regex/1.3.9/regex/#grouping-and-flags

**Comment by oxarbitrage** [comment]
It looks pretty ugly but the only way i was able to make the needed filter work was with `[block_verify{height=Some(.*000.*)}]=trace` . I documented this at https://github.com/ZcashFoundation/zebra/pull/780

**Comment by hdevalence** [comment]
Hmm, I'm surprised by that. I think that pattern isn't quite what we want, since it will match, e.g., `700071` etc. Maybe the problem is that the `()` are treated as capture groups, as @teor2345 suggested, so the extra `.*` at the end is needed to match a `)` that isn't part of the pattern. But then, why are the `(` in `Some(BlockHeight` not capture groups?

**Comment by oxarbitrage** [comment]
You are right, but i realized we can escape all `(` and `)`. So this will do what we need i think:

`[block_verify{height=Some\(BlockHeight\(.*000\)\)}]=trace`
