### ISSUE TITLE
Return errors instead of panicking in methods for  `Height`s

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7263]
### Motivation

Resolve the issues raised in https://github.com/ZcashFoundation/zebra/pull/7239#discussion_r1266136500.

**Comment by teor2345** [comment]
@mpguerra I think these fixes might cause some merge conflicts with the open RPC PRs.

Do you mind if we bump this issue to the next sprint?

**Comment by mpguerra** [comment]
> @mpguerra I think these fixes might cause some merge conflicts with the open RPC PRs.
> 
> Do you mind if we bump this issue to the next sprint?

Depends on whether @upbqdn has started working on it yet or not

**Comment by upbqdn** [comment]
I have not.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7263?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
