### ISSUE TITLE
Upgrade lightwalletd used by Zebra

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7292]
Currently Zebra uses https://github.com/adityapk00/lightwalletd for all the CI ligthwalletd tasks as can be seen in https://github.com/ZcashFoundation/zebra/blob/v1.1.0/.github/workflows/zcash-lightwalletd.yml#L61

This version does not include new code added by the ECC to support new functionality: https://github.com/zcash/lightwalletd

For example `ChainMetadata` was added to https://github.com/zcash/lightwalletd/blob/master/walletrpc/compact_formats.proto#L31 which is needed by https://github.com/ZcashFoundation/zebra/pull/7278 

I am not sure yet if we can just switch to the ECC version or if we need to request the new changes to be done to the adityapk00 version.

**Comment by arya2** [comment]
> I am not sure yet if we can just switch to the ECC version or if we need to request the new changes to be done to the adityapk00 version.

I think we should switch to the ECC version now.
