### ISSUE TITLE
Readd blank template to issues

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7318]
https://github.com/ZcashFoundation/zebra/issues/new/choose

I generally use and prefer an empty template when adding new short issues instead of the ones prepopulated that are more used by external users or special cases. Currently i have to select one of the templates and remove stuff from the url to get to it. 

This is a minor thing but i think we should have the empty issue creation option back to the list.

**Comment by mpguerra** [comment]
@oxarbitrage can you bring this up during the sprint retrospective next week?

**Comment by mpguerra** [comment]
After trying to create a tracking issue and finding it too hard I want to bump this one up.

**Comment by teor2345** [comment]
It might be good to mark the empty template as "developer only", or put it at the bottom of the template list.

**Comment by oxarbitrage** [comment]
I agree this should be the last option at the bottom. Maybe changing this to `true` will do it for us instead ?

https://github.com/ZcashFoundation/zebra/blob/main/.github/ISSUE_TEMPLATE/config.yml#L1
