### ISSUE TITLE
Update lightwalletd fork in zebra book and code docs

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7319]
https://zebra.zfnd.org/user/lightwalletd.html

We switched from [adityapk00](https://github.com/adityapk00/lightwalletd) lightwalletd to [ecc](https://github.com/zcash/lightwalletd) in [here](https://github.com/ZcashFoundation/zebra/pull/7307).

We may need to change the documentation to point to that repo instead, i suppose we can keep using the [zecwallet-light-cli](https://github.com/adityapk00/zecwallet-light-cli)  but we might want to try the documentation steps and see if the whole process remains working with the different lightwalletd version.

I am not doing this change yet as we are unsure that the switched version is currently working for us as we are having CI issues that could be related to the switch.

**Comment by oxarbitrage** [comment]
Also https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/acceptance.rs#L58-L61

A full search for `adityapk00` in Zebra should be done and decide what to change on each case if needed.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7319?planning-poker) with Zenhub @upbqdn @teor2345 @oxarbitrage @arya2
