### ISSUE TITLE
Fix lightwalletd sync finish detection code in tests

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7335]
### Motivation

zcash/lightwalletd's get_latest_block RPC returns the tip height of the full node.

Zebra's lightwalletd sync test expects for this RPC to return the height of the latest block in the lightwalletd cache to check that the full sync works.

### Suggested Design

- Check lightwalletd logs instead of get_latest_block for cache height
OR
- Check zebrad logs for lightwalletd requests (might need changes to the log level of the request log)

Then revert #7332.

### Other Designs

<details>

<summary>adding new RPCs significantly increases the scope of this ticket</summary>

- Add an RPC method or field to zcash/lightwalletd that returns the sync status

</details>

**Comment by teor2345** [comment]
> * Check lightwalletd logs instead of get_latest_block for cache height

I think there are already some regexes in the tests that check the lightwalletd logs, so we could copy those.

One tricky part of this is that we might need to check the Zebra and lightwalletd logs in concurrently running threads.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7335?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
