### ISSUE TITLE
Make getblocktemplate-rpcs a default feature

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7361]
### Post-Merge TODOs

- [x] Describe this newly stabilised feature in the CHANGELOG
- [x] Arborist announcement
- [ ] Forum update

### Motivation

Once we're happy to support the getblocktemplate RPCs, we can turn them on in all Zebra builds, by adding that feature to the default feature list:
https://github.com/ZcashFoundation/zebra/blob/31426f3b0e38bb681df3b82a38dad07405a876a5/zebrad/Cargo.toml#L53-L55

### Specifications

https://doc.rust-lang.org/cargo/reference/features.html#the-default-feature

### Complex Code or Requirements

This is a well-supported Cargo configuration.

### Testing

Some tests might need updates if they assume `getblocktemplate-rpcs` will always be disabled during the test. We should probably delete or disable those tests (ticket #7362).

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7361?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
