### ISSUE TITLE
Remove extra tests for getblocktemplate-rpcs feature

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7362]
### Motivation

Currently we have duplicate tests with and without `getblocktemplate-rpcs`. We can delete some of these tests after ticket #7361 merges.

### Complex Code or Requirements

We should delete Rust tests we aren't using any more.

Some tests might fail and need to be fixed as part of ticket #7361.

### Testing

We can manually check there's still one instance of every test when we review the PR.

### Related Work

- #7361

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7362?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This is currently blocked by an open refactor that changes workflow names and structures. Once that merges, we can delete some of the workflow jobs in the PR for this ticket.

(I can open a PR on top of the workflow structure PR at any time, but merging any changes can get complicated.)
