### ISSUE TITLE
Make a config for progress bars, rather than having the feature activate them by default

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7363]
### Motivation

Currently the `progress-bars` feature turns on progress bars and file logging immediately.

But if we want users to test them, we should make the progress bars configurable with `zebrad.toml`. This allows us to compile the `progress-bar` feature by default, but not activate it for every user by default.

(Activating progress bars by default could be a breaking change for some users that expect Zebra to write logs to standard output.)

### Specifications

We probably want to have this in the tracing config, and then use it to activate the progress bar display loop.

If the display loop isn't active, progress bar operations are ignored, so it's ok for the progress bar update code to always be on. 

### Complex Code or Requirements

We might want to make the config flexible, so that we can have expert and default progress bar configs, once we know which progress bars are a priority for users.

### Testing

We can manually test that progress bars are off by default, off when the feature is active, but on when the feature is active and they are configured on.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate for this one?
