### ISSUE TITLE
Tracking: Official support for mining RPCs in Zebra

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7366]
## Motivation

We want to officially support mining functionality in zebra by making it available on the stable Zebra docker image. 

Before we are comfortable doing this we _might_ want to do _some_ of the following:

### Making `getblocktemplate-rpcs` a default feature

- [x] #7362 
- [x] #7361

### Potential security issues

- [x] #6688 

### Related work

- [x] #7415 

### Performance improvements

- [x] #5674 
- [x] #5604 
- [ ] #5891 
- [x] #7403 
- ~~#6037~~
- ~~#6047~~ 

### Usability 

- [x] #5449 
- [ ] #5472 
- [x] #5718
- [x] #5911
- [x] #6193 
- [x] #6082 
- [x] #6068 
- [ ] #5929 
- ~~#7118~~ no longer related 

### Tech debt

- [x] #6190 

This is an exhaustive list that will need to be triaged and prioritised further.

**Comment by teor2345** [comment]
- https://github.com/ZcashFoundation/zebra/issues/6037
- https://github.com/ZcashFoundation/zebra/issues/6047

These aren't related to performance, they are for detecting bugs in our proposal construction.

But since we haven't seen any invalid proposals for a long time, I think we should close these tickets, and open tickets for any specific proposal bugs that actually happen.

**Comment by teor2345** [comment]
- https://github.com/ZcashFoundation/zebra/issues/6190

I think these cleanups can be turned into TODOs in the code instead, and we can fix them if we modify that code in future.

**Comment by teor2345** [comment]
- https://github.com/ZcashFoundation/zebra/issues/7118

This is a usability issue, not really technical debt. Currently Zebra panics, which is ok, but warning and ignoring the unused config fields would (possibly) be better for some users.

The drawback is that users who expect Zebra to fail if the Zebra version or config is wrong will be surprised.

**Comment by mpguerra** [comment]
> * [Simplify `z_listunifiedreceivers` RPC implementation #6190](https://github.com/ZcashFoundation/zebra/issues/6190)
> 
> 
> I think these cleanups can be turned into TODOs in the code instead, and we can fix them if we modify that code in future.

I'm thinking this will require a PR and review cycle anyway (albeit a shorter one than actually fixing it) and will therefore languish in our backlog as a result

**Comment by teor2345** [comment]
> > * [Simplify `z_listunifiedreceivers` RPC implementation #6190](https://github.com/ZcashFoundation/zebra/issues/6190)
> > 
> > I think these cleanups can be turned into TODOs in the code instead, and we can fix them if we modify that code in future.
> 
> I'm thinking this will require a PR and review cycle anyway (albeit a shorter one than actually fixing it) and will therefore languish in our backlog as a result

I honestly don't think it matters either way. We might be more likely to do the change if there's a TODO near the code we're modifying anyway. But since it's not an important change, it doesn't really matter how likely we are to do it.

**Comment by mpguerra** [comment]
We are done here for now 🎉
