### ISSUE TITLE
Make the BlockVerifier check for the previous block before verifying

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#737]
Some high blocks occasionally slip through our fix in #727, and then the BlockVerifier approves them, because it doesn't check any chain state.

When that happens, the state layer panics on the next ExtendTips, because there is a gap in the chain.

Until we have a chain state implementation, we should make the BlockVerifier check the parent hash and height.

**Comment by yaahc** [comment]
> Until we have a chain state implementation, we should make the BlockVerifier check the parent hash and height.

The race is on
