### ISSUE TITLE
(De)Serialize `NoteCommitmentTree`s using supported serialization format instead of `bincode`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7383]
## Scheduling

This ticket is blocked by the #7392 state bug fix.

## Motivation

Apparently (@teor2345  mentioned me this, came up in conversations with @upbqdn), if we replace `bincode` with the supported serialization format in for example [sprout](https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/finalized_state/disk_format/shielded.rs#L91), sapling and orchard implementations the resulting database might be smaller. And it will be easier to maintain the code.

We might need to add `as_bytes()` and `from_bytes()` methods to `sprout::NoteCommitmentTree`, `sapling::NoteCommitmentTree` and `orchard::NoteCommitmentTree` to do this, using:
- [`write_frontier_v1()`](https://docs.rs/zcash_primitives/0.12.0/zcash_primitives/merkle_tree/fn.write_frontier_v1.html), and
- [`read_frontier_v1()`](https://docs.rs/zcash_primitives/0.12.0/zcash_primitives/merkle_tree/fn.read_frontier_v1.html#)

### Suggested Solution

- [ ] Make the needed changes [to the database format](https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#upgrading-the-state-database)
- [ ] Update database version
- [ ] Check the serialization/deserialization produces the same tree structures, by synchronizing the chain up to tip, then comparing the tree roots using the RPCs (or any other way). The comparison can be done with an older Zebra version, or with `zcashd`.

#### Optional

- [ ] Compare the database size with a previous version without the changes (may need extra space in your computer to hold the 2 versions).

**Comment by teor2345** [comment]
This is also a technical debt issue. Currently we're maintaining code for a legacy `incrementalmerkletree` bincode-compatible serialization format, conversion code, and code to use the current version of `incrementalmerkletree`.

If we used the supported serialization formats, we could delete the duplicate code and data structures, and remove `zebra-state`'s dependency on `bincode` and `serde`.

**Comment by arya2** [comment]
This looks like a good option too: 

https://crates.io/crates/parity-scale-codec
