### ISSUE TITLE
fix(state): Don't expose arbitrary batches for database writes

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7418]
Address the issue raised in https://github.com/ZcashFoundation/zebra/pull/7312#discussion_r1294514456.

**Comment by teor2345** [comment]
I wonder if this is ok as long as it just happens inside the state crate?

**Comment by upbqdn** [comment]
Sure, let's close this issue if the current design is fine.

**Comment by teor2345** [comment]
We could also make it so the batch type is only available within the finalised state, if it isn't that way already. (A type can't be accessed if its module is not publicly exported by parent module, and the type itself isn't publicly exported by that parent module.)
