### ISSUE TITLE
feature: Use the `CODEOWNERS` file to define reviewers for specific dependencies and dependency groups

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7421]
### Motivation

As a team, we discussed how it might be advantageous to always have the same people review the same dependency upgrades as they would have the most background and knowledge to effectively review the same.

**Comment by mpguerra** [comment]
@ZcashFoundation/zebra-team Do we still want to do this?

**Comment by teor2345** [comment]
This is not technically possible in most cases.

Instead, our plan is to limit dependency upgrades tp 4 PRs per week: ECC dependencies, production Rust dependencies, test/developer tool Rust dependencies, and DevOps dependencies.

The DevOps changes will be auto-assigned to DevOps reviewers by our current CODEOWNERS file.

If there are only a few Rust updates, the PR will be auto-assigned to the people who usually review the crates that depend on those dependencies. That's the best we can do for now.

**Comment by mpguerra** [comment]
Closing in favour of #7809
