### ISSUE TITLE
Exercise the mining pipeline on Mainnet

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7423]
We have produced a block on Testnet via S-nomp and a CPU Equihash solver.

We could do the same on Mainnet with some volunteer-provided ASIC solvers.

For example, we should be able to produce a block within a week with six Z15 machines given the current difficulty on Mainnet.

## Solution

- Run Zebra with mining enabled.
- Connect s-nomp to Zebra.
- Connect s-nomp to `zcashd` for payment processing. This step might not be necessary. Part of this ticket is to figure out if we need it.
- Connect some volunteer-provided ASICs to s-nomp. This requires making s-nomp's inbound RPC port and IP available to the ASICs since they won't be on the same local network. I think we could go without TLS here and use dynamic port forwarding via SSH, for example. The ASICs have only a "home WiFi router-like" user interface for configuration. The only required config is the URL of the pool, which will be our s-nomp.
- Start mining and wait for a correct solution.
- Check if the block got into the chain on Mainnet.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7423?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
This seems like the kind of ticket we could time-box to 1-2 days of work. (And 6 days of waiting.)

Optional: we could turn on the code that puts "zebra" in the mined block. I think there's a config or a feature for it.

**Comment by mpguerra** [comment]
let's close this for now, just waiting for a zebra generated block to get mined
