### ISSUE TITLE
Investigate rewriting `checkpoint/tests.rs` tests in `zebra-consensus` to use `zebra_test::Transcript`

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#744]
Wondering if this could be expressed as a `zebra_test::Transcript`

It seems like the only thing that's missing is some sort of customizable callback to do additional assertions after each request. I think we might be able to bring in the assertions as an additional service wrapping the transcript.

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/736#discussion_r459642633_

**Comment by teor2345** [comment]
We're unlikely to update these tests any time soon.
