### ISSUE TITLE
Fix proptest coverage of note commitment subtree serialization

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7443]
## Motivation

Almost all the subtree proptest cases are checking an `end` of `MAX_ON_DISK_HEIGHT`.

### Specifications

This issue is documented here, but for a string regex, rather than a clamp:
> In general, the ideal solution is to find a way to take a seed value and then use prop_map to transform it into the desired, irregular domain.
> This kind of works, but it has problems ... [it] also results in a pretty odd distribution of values. 

https://proptest-rs.github.io/proptest/proptest/tutorial/filtering.html
https://proptest-rs.github.io/proptest/proptest/tutorial/transforming-strategies.html

## Suggested Solution

Instead, transform the input range so its distribution is roughly uniform:
```suggestion
        val.end.0 %= (MAX_ON_DISK_HEIGHT.0 + 1);
```

This fix is required for both Sapling and Orchard proptests.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/7350#discussion_r1309512808_

**Comment by mpguerra** [comment]
@oxarbitrage can you please add an estimate to this one?

**Comment by oxarbitrage** [comment]
Estimate added.
