### ISSUE TITLE
Correctly populate subtree values in ZebraDb::note_commitment_trees()

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7444]
## Motivation

The subtrees returned by `ZebraDb::note_commitment_trees()` are currently `None`.

### Suggested Solution

Populate the subtree fields with the tip subtrees, or document that they are always `None` in the function documentation.

This change might need `*_subtree_for_tip()` methods.

You can get the tip trees with `zs_last_key_value()`, PR #7408 has the required `impl FromDisk for NoteCommitmentSubtreeIndex`.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/7350#discussion_r1309528107_

**Comment by arya2** [comment]
These are currently only used to add subtrees to the state, it shouldn't cause a bug in Zebra's current form.

These should be populated here as well if Zebra needs to read these fields later: https://github.com/ZcashFoundation/zebra/blob/subtree-upgrade-data-only/zebra-state/src/service/non_finalized_state/chain.rs#L1367

**Comment by teor2345** [comment]
Thanks, that seems like a low priority technical debt issue. It could cause confusing bugs later if we don't fix it.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7444?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
