### ISSUE TITLE
Test the `z_getsubtreesbyindex` RPC

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7449]
## Motivation

To make sure the `z_getsubtreesbyindex` RPC method works, do these tests:

- [x] #7450
- [x] #7451
- [x] #7513
- [x] #7446

For this RPC we will need to test Sapling and Orchard, because they use different state requests.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7449?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
this seems like a tracking issue now so I'm removing this from the sprint and adding the individual issues to sprints instead

**Comment by teor2345** [comment]
All these tasks are done now.
