### ISSUE TITLE
Test `z_getsubtreesbyindex` using a `lightwalletd` gRPC request

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7451]
## Scheduling

This might be blocked by #7349.

## Motivation

We want to make sure `lightwalletd` can use our new `z_getsubtreesbyindex` JSON-RPC method successfully.

This test makes sure we continue working with `lightwalletd`, even if they make changes without telling us.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7451?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
