### ISSUE TITLE
Write acceptance tests for sync, verify, and state

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#746]
We want to write acceptance tests for sync testing.

These tests should be off by default, but run during CI.

See the integration test RFC #1004 for the latest test plan.

Test Types:
- [x] Fresh Sync:
  - Start with an empty state
  - Launch with a longer timelimit
- [x] Restart Sync:
  - Start with an empty state
  - Launch with a short timelimit, enough to store some state
  - Restart with a longer timelimit

Test Features:
- [x] Support Mainnet
- [x] Support Testnet

**Comment by teor2345** [comment]
Closed by #1188

**Comment by dconnolly** [comment]
Closed by #1188
