### ISSUE TITLE
Checking if transactions get into the mempool fails in lightwalletd tests

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7529]
In `send_transaction_tests` we send transactions using grpc and then attempt to check if they are inside the mempool using grpc calls as well. This should be more or less what a wallet using lightwalletd may want to do.

However, the check of the mempool works in some local environments (i was able to make that work reliable locally) but fails in the CI for unknown reasons.

In the past, when we were using `adityapk00` lightwalletd fork the mempool calls were commented out so an empty response was expected.  When we changed to the `zcash` lightwalletd we were expecting this test to start working so they were enabled in https://github.com/ZcashFoundation/zebra/pull/7349, however this is not the case so we disabled them back again in the same PR.

We don't know the reason of the failure. More details can be found in https://github.com/ZcashFoundation/zebra/pull/7349

**Comment by teor2345** [comment]
This could be a bug in the tests, a timing bug, or a specific issue with our CI test setup.

There have also been fixes and changes to those gRPC calls recently, including disabling and re-enabling them. So it's also possible there is a bug in the gRPC code itself, and our tests trigger it sometimes.

**Comment by teor2345** [comment]
It's also possible that we need to replace our gRPC protocol definitions with the definitions from the ECC fork. Protocol changes could cause messages to be dropped.

Here's our definitions:
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/common/lightwalletd/proto/service.proto
https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/common/lightwalletd/proto/compact_formats.proto

**Comment by oxarbitrage** [comment]
We saw an instance of this rpc methods working in the CI https://github.com/ZcashFoundation/zebra/actions/runs/6241861800/job/16946300444#step:9:572 but we had to disable it as it seems to be intermittent: https://github.com/ZcashFoundation/zebra/issues/7598

**Comment by mpguerra** [comment]
@arya2 can you please add an estimate to this issue?
