### ISSUE TITLE
Provide metrics for bytes written, bytes read

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#753]
It would be nice to hook into the `Codec` implementation to provide metrics for bytes written and bytes read.  This seems like it would be a useful metric in tandem with our metrics on message counts and request counts.

**Comment by hdevalence** [comment]
The structure of the codecs is described in this blog post: https://www.zfnd.org/blog/decoding-bitcoin-messages-with-tokio-codecs/

For bytes read, I think we can do this very simply by incrementing a counter with the length as soon as we have a complete message.  For bytes written, I guess we would record the size of every message we write and add that to a counter, but it's possible (?) that this will require slightly more work to remember how much data we wrote.

**Comment by oxarbitrage** [comment]
I am unsure if this should be by address like `peer_outbound_messages` and `inbound_messages` or if just the total bytes written and total bytes read in current session is enough.

If what is required is just total values i dont see how the written ones can be more work than the read. (an incremental counter can be added in `encode` and `decode` functions of `codec.rs` after we have the full message)

It can help if you post the output format you will like to see. Thanks.

**Comment by hdevalence** [comment]
Doing it per-address like the inbound and outbound message counts seems like a good idea, because then in Prometheus/Grafana we can do aggregate statistics or zoom in on individual peers.  We construct a different codec object for every connection (since the codec is an adapter that transforms the byte stream to a message stream) so it should be possible for each codec to record metrics by address.  I'm not sure whether the codec currently knows anything about the address, but if it doesn't, we can add whatever data is needed to do debugging to the codec's builder as extra configuration data.
