### ISSUE TITLE
Upgrade dependencies for zcashd 5.7.0

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7535]
## Motivation

`zcashd` crate dependency upgrades need to be done together, along with an upgrade to `zcash_script`.

We don't have upgrade instructions yet, but there's a draft in #6532.

The steps are:
- [ ] wait for the zcashd release candidate
- [ ] upgrade `zcash_script`
- [ ] wait for the zcashd release
- [ ] release zcash_script
- [ ] upgrade Zebra's ECC and `zcash_script` dependencies in the same PR

What versions of `zcashd` and the ECC crates do we need to upgrade to?
(This list might be out of date.)

| Package | From | To |
| --- | --- | --- |
| [bridgetree](https://github.com/zcash/incrementalmerkletree) | `0.3.0` | `0.4.0` |
| [incrementalmerkletree](https://github.com/zcash/incrementalmerkletree) | `0.4.0` | `0.5.0` |
| [orchard](https://github.com/zcash/orchard) | `0.5.0` | `0.6.0` |
| [zcash_primitives](https://github.com/zcash/librustzcash) | `0.12.0` | `0.13.0` |
| [zcash_proofs](https://github.com/zcash/librustzcash) | `0.12.1` | `0.13.0` |

**Comment by mpguerra** [comment]
Do we have a date for the next zcashd release? I did a quick search and couldn't find this information

**Comment by str4d** [comment]
It will be in the next week or two. `zcashd 5.6.*` reaches EoS in 3-4 weeks, so before then.

**Comment by teor2345** [comment]
> It will be in the next week or two. `zcashd 5.6.*` reaches EoS in 3-4 weeks, so before then.

Let's wait to schedule this work until the `zcashd` release is out. As far as I know, there's no upgrade deadline on our side.

**Comment by teor2345** [comment]
@mpguerra this ticket is ready to go because their release happened on Friday:
https://github.com/zcash/zcash/releases/tag/v5.7.0

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7535?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@oxarbitrage can you work on this one and #6532 next?

**Comment by mpguerra** [comment]
Can this be closed now that #7784 has merged?

**Comment by oxarbitrage** [comment]
Yes this can be closed.
