### ISSUE TITLE
devops: Long branch names fail CI because GCP resource name is too long 

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7559]
### Describe the issue or request

When I open a PR with a long branch name, CI fails with "Invalid value for field 'resource.name'".

### Expected Behavior

CI passes on long branch names.

### Current Behavior

> ERROR: (gcloud.compute.instances.create-with-container) Could not fetch resource:
>  - Invalid value for field 'resource.name': 'generate-checkpoints-testnet-label-cached-state-from-disk-32f315b'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'

https://github.com/ZcashFoundation/zebra/actions/runs/6179715964/job/16776349421#step:11:78

### Possible Solutions

Reduce the length of newer test IDs. (See the list below.)

### Rejected Solution

Truncate the branch name to fit within the length limit. ~~(I'm pretty sure this used to happen?)~~

### Is this happening on PRs?

Yes

### Is this happening on the main branch?

No, it has a short name

**Comment by gustavovalverde** [comment]
I can't find the specific message, but we onced talked about this issue and did not take further action on it, just informing that we had to keep the branch name short and without special characters to avoid this kind of issues (which also happens on other places, like docker build tags)

We could truncate the name, for certain, but we'd have to consider all places where this might happen.

**Comment by teor2345** [comment]
> I can't find the specific message, but we onced talked about this issue and did not take further action on it, just informing that we had to keep the branch name short and without special characters to avoid this kind of issues (which also happens on other places, like docker build tags)
> 
> We could truncate the name, for certain, but we'd have to consider all places where this might happen.

I think this is more of a problem now because the `generate-checkpoints-testnet` test ID is very long. So maybe we could fix this bug by making that name shorter instead?

The newer longest IDs are:
- `generate-checkpoints-testnet`
- `generate-checkpoints-mainnet`
- `full-sync-to-tip-testnet`

Before they were added, the longest ID was:
- `sync-past-checkpoint`

Here are some alternatives:
- `checkpoints-testnet`
- `checkpoints-mainnet`
- `full-sync-testnet`

**Comment by teor2345** [comment]
@gustavovalverde is this fixed in PR #7616, or does it need to wait until after that PR merges?
