### ISSUE TITLE
Set Canopy testnet activation height

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#756]
zcashd has set a Canopy testnet activation height, but it's changed in the past week:
* current: https://github.com/zcash/zcash/commit/62c3613816f82603a4529403454fcb2a16e69b12
* earlier: https://github.com/zcash/zcash/commit/8a4c51508acfa1765f168ebc6233fd68edff49bb

We should work out how we want to track the activation height, and then update zebra-consensus.

For example, we could wait until ZIP 251 is updated:
https://zips.z.cash/zip-0251

Edit:
* the current testnet Canopy activation height is `1028500`
* there is an explanation for the change in https://github.com/zcash/zips/pull/385

**Comment by daira** [comment]
Review needed for https://github.com/zcash/zips/pull/385

> This also sets the Canopy Testnet activation height in ZIP 251.
