### ISSUE TITLE
Test that "sync from empty" and "upgrade from existing" state code produces the same data

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7570]
### Motivation

We want to prevent bugs like #7532 happening again. Expecting developers to run manual tests on all the different ways of creating a state isn't reliable.

#### Run subtree tests on both kinds of states

One option is to run the subtree tests in tickets #7450, #7451, and #7446 on both a "sync from new" state and an "upgrade from existing" state. But to do that, we'd need to:
1. change the state selection script so it accepts a parameter for new/upgraded state kinds
2. change the state deletion script so it always keeps both state kinds
3. Run all those tests twice
4. Remember to do this for every future state upgrade

#### Re-run state validity checks while Zebra is running

Another option is to repeat the state validity check in PR #7566:
- [x] periodically while Zebra is running
- [x] before Zebra shuts down (or any time after the full sync finishes)
- [ ] fail CI if the format is wrong

Then that check will run:
- on upgraded states: PRs and main branch merges (this already happens once),
- on "sync from empty" states: the weekly full sync (this is the missing check),
- before we write the cached state in CI.

Then as soon as we merge PR #7565 we'll automatically get a ticket when these checks fail on `main` merges or scheduled full syncs.

This seems like the more reliable option, because it will automatically test all state upgrade code, not just subtrees. 

### Complex Code or Requirements

Now we have two different code paths for creating state data, we need to check that they create exactly the same data.

But unfortunately, we can't run a full and an upgrade sync on each PR, because that would take 3 days. So this ticket is about finding another way to reduce the risk.

### Testing

This is a testing ticket.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate to this one?
