### ISSUE TITLE
bug: Zebra panics with "Sprout note commitment tree must exist if there is a finalized tip" shortly after launch

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7581]
### What happened?

I expected to see this happen:

Zebra always launches successfully.

Instead, this happened: 

Zebra panics with "Sprout note commitment tree must exist if there is a finalized tip" shortly after launch.

### What were you doing when the issue happened?

Testing the subtree code in PR #7566 on my local machine
Testing unrelated code on my local machine
Running unrelated PRs in CI

### Zebra logs

Exit Status:
command terminated unsuccessfully by signal 6
Stdout:
Stderr:
The application panicked (crashed).
Message:  Sprout note commitment tree must exist if there is a finalized tip
Location: zebra-state/src/service/finalized_state/zebra_db/shielded.rs:97
Metadata:
failures:
config_tests

### Zebra Version

zebrad 1.2.0, multiple commits on different PRs

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

various machines: CI, local machine

### Additional information

The panic is from the `expect()` in:
https://github.com/ZcashFoundation/zebra/blob/4f6d28f9b115648f990a7c471ebc5e0b8a4048e6/zebra-state/src/service/finalized_state/zebra_db/shielded.rs#L84-L98

This issue should be fixed by PR #7392.

It might be possible for remote nodes to trigger this bug, or make it more likely, because it happens when a block is downloaded during launch. (Or maybe while writing another block.)

**Comment by teor2345** [comment]
This just happened again on my local machine.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate here?
