### ISSUE TITLE
Add short descriptions at the top of the workflow files

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7607]
Zebra has quite a few workflow files: https://github.com/ZcashFoundation/zebra/tree/main/.github/workflows

As you browse that directory is pretty hard to know what each file do. Some of them have a short description at the top like https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/release-binaries.yml but the majority of them just don't:

- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-integration-docker.patch-always.yml
- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/zcash-lightwalletd.yml
- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/continous-delivery.yml
- ...

I think it will be nice to create a header doc that we can add to each of this files at the top with a short description on what can be expected in the code below.

I will be happy to do this myself but i unfortunately don't know what each file do.

**Comment by teor2345** [comment]
You might find parts of these documents helpful, they explain what some workflows do:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-integration.md
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/continuous-delivery.md

**Comment by oxarbitrage** [comment]
Thank you, i think this as not only for me but for anyone to have a brief idea on what is the file about when browsing it.

It is not very important, it is ok to close it if you think is it not a good idea.

**Comment by teor2345** [comment]
I think it's a good idea, it's what we do with Rust code files, and it's helpful.

**Comment by mpguerra** [comment]
@gustavovalverde I think you're already working on this? I've added it to this sprint but feel free to remove if you're not working on it

**Comment by gustavovalverde** [comment]
@mpguerra that's correct

**Comment by teor2345** [comment]
This was merged in PRs #8009 and #8005.
