### ISSUE TITLE
Allow logging to terminal when progress bars are enabled

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7648]
## Motivation

Zebra's terminal output is weird when progress bars are enabled without logging to a file.

It would be nice for users to be able to see warning logs adjacent to the progress bars.

### Possible Designs

One of: 

- Pass the non-blocking logger a struct that implements `Writer` with [`howudoin::Tx::{add_warn, add_info, ..}`](https://docs.rs/howudoin/latest/howudoin/struct.Tx.html#method.add_warn)
- Call `tracing::{info, warn, trace, debug}` through functions defined in Zebra that call `howudoin`'s log methods instead of the tracing methods when progress bars are enabled and writing logs to the terminal
- Use indicatif directly instead of howudoin and implement `Writer` to write to stdout from `suspend()`
- Add `suspend()` to `howudoin` and implement `Writer` to write to stdout from `suspend()`

**Comment by teor2345** [comment]
This is currently handled by always sending logs to a file when progress bars are configured.

Showing both logs and progress bars at the same time is something to consider after we implement separate `summary` and `detailed` modes.
