### ISSUE TITLE
Automatically open an issue when main branch release-related merges fail

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7680]
Releases:
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/docs-deploy-firebase.yml
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/docs-dockerhub-description.yml
https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/release-drafter.yml

**Comment by teor2345** [comment]
I removed https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/cd-build-zcash-params.yml because we deleted it when we put parameters in the Zebra binary,

**Comment by mpguerra** [comment]
Not a priority
