### ISSUE TITLE
devops: `docker logs` hangs and docker config workflow job times out

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7702]
### Describe the issue or request

`docker logs` should finish after it shows the available logs, but in this workflow it hung:
https://github.com/ZcashFoundation/zebra/actions/runs/6451909524/job/17513328674#step:4:158

### Expected Behavior

`docker logs` should finish after it shows the currently available logs.

### Current Behavior

`docker logs` showed Zebra's shutdown logs then kept running for 15 minutes:
https://github.com/ZcashFoundation/zebra/actions/runs/6451909524/job/17513328674#step:4:158

### Possible Solution

This is a really unusual bug, there don't seem to be any arguments to `docker logs` that would cause this behaviour. This could be a hardware, OS, or runner issue.

Maybe a command like `timelimit` could help if it happens again.

### Additional Information/Context

The workflow logs are confusing to read because Zebra's logs come after the `docker logs` command.

### Is this happening on PRs?

I haven't seen it happen on a PR yet

### Is this happening on the main branch?

I've only seen it happen once

**Comment by gustavovalverde** [comment]
This hasn't been happening for a while. If this repeats we can reopen.
