### ISSUE TITLE
Fix documentation links in zebrad::config::ZebradConfig

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7769]
## Motivation

The link to the `zebra_network` (and other) field type `Config` goes to the wrong page.

https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

**Comment by teor2345** [comment]
Do we already have a ticket for this?

**Comment by mpguerra** [comment]
closed as duplicate of #7048
