### ISSUE TITLE
change: Support hiding specific progress bars in summary mode

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7785]
We could support hiding the progress bars that users don't find interesting. For example, as a user, I feel like the "Checkpoint Queue Height" doesn't bring much new info compared to other progress bars.

**Comment by teor2345** [comment]
Here's one possible design:
- the progress bars config gets passed to every service/task that has progress bars
- based on that config, some progress bars decide to hide themselves in summary mode
