### ISSUE TITLE
Tracking Issue: Progress Bar Improvements and Fixes

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#7786]
This is a tracking issue for tweaking the progress bars. These are the changes we would like to make:

Data and label fixes:
- [x] #7981
- Rename the "Blocks" bar to "Verified Blocks"
- [ ] Optional: #7110 (this needs extra state format changes)
- [ ] Optional: #7648

Extra progress bars or information:
- Show how much is in each shielded pool (and transparent)
  - from https://forum.zcashcommunity.com/t/zebra-progress-bars/44485/5
- Show unique IP address counts for peers, as well as address/port counts, this can be added using [`desc()`](https://docs.rs/howudoin/latest/howudoin/struct.Tx.html#method.desc)

Configurable "summary" progress bars:
- [x] #7785

**Comment by mpguerra** [comment]
This is not a priority right now
