### ISSUE TITLE
Add new branch protection rules for Docker config tests

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7793]
We need 4 new branch protection rules now that #7616 has merged:

- [x] Test CD default Docker config file / Test default-conf in Docker
- [x] Test CD custom Docker config file / Test custom-conf in Docker
- [x] Test CI default Docker config file / Test default-conf in Docker
- [x] Test CI custom Docker config file / Test custom-conf in Docker

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/7616#issuecomment-1767594197_

**Comment by mpguerra** [comment]
Can we have someone other than @gustavovalverde or @teor2345 take this one so we spread knowledge on this around the team?
There's documentation on this in #7773

**Comment by upbqdn** [comment]
I tried adding the rules, but I can't see the "Branches" section in the settings. I guess I don't have the permissions.

**Comment by gustavovalverde** [comment]
As I was reassigned to this, I've recently added these rules.
