### ISSUE TITLE
Change `rpc_endpoint_parallel_threads` job to use the logs instead of a fixed time

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7808]
`rpc_endpoint_parallel_threads` failed with a timing issue, we might want to fix that test to use the logs rather than a fixed time.

https://github.com/ZcashFoundation/zebra/actions/runs/6607410396/job/17944979809?pr=7800#step:4:6196

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/7800#issuecomment-1775978108_

**Comment by teor2345** [comment]
Thanks for opening this ticket! I think it is optional unless we see the bug more than once every few weeks.

**Comment by teor2345** [comment]
Failed in PR #7873:
https://github.com/ZcashFoundation/zebra/actions/runs/6694816802/job/18189520312?pr=7873

**Comment by gustavovalverde** [comment]
This hasn't happened for a while.
