### ISSUE TITLE
Remove sprout and sapling parameter downloads and preload config

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7810]
## Motivation 

This is cleanup for https://github.com/ZcashFoundation/zebra/pull/7800.

See https://github.com/ZcashFoundation/zebra/issues/7613#issuecomment-1776168530.

**Comment by teor2345** [comment]
This cleanup specifically?
- Remove the download task, ignore the `debug_skip_parameter_preload` config, remove any production code for downloads, and any test code that tests downloads or sets the config

**Comment by teor2345** [comment]
Just to be clear, this is about everything except the `zebrad download` command and Dockerfiles, which is in #7811.
