### ISSUE TITLE
devops: Build CI Docker runs twice for every PR

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7816]
### Describe the issue or request

On every PR, we run the same Docker build twice, with exactly the same settings:

https://github.com/ZcashFoundation/zebra/blob/aad883b68ae1fb7a98aa2868bc1bd4a34954bd13/.github/workflows/ci-unit-tests-docker.yml#L84-L86

https://github.com/ZcashFoundation/zebra/blob/aad883b68ae1fb7a98aa2868bc1bd4a34954bd13/.github/workflows/ci-integration-tests-gcp.yml#L126-L128

### Expected Behavior

This seems redundant, we only need to build one image.

### Current Behavior

The same image is built twice.

### Possible Solution

Make the jobs in one workflow wait on the build job in the other workflow, or re-combine the workflows into a single workflow.

### Additional Information/Context

This costs us extra build machine time, and extra storage costs.

### Is this happening on PRs?

Yes

### Is this happening on the main branch?

Not really, de-duplicating the `main` merge and release builds is more complicated, and there is only one duplicate every few weeks

**Comment by teor2345** [comment]
Cross-workflow dependencies can be created in GitHub actions:
https://stackoverflow.com/questions/63148639/create-dependencies-between-jobs-in-github-actions#63148947

**Comment by teor2345** [comment]
Seems like these duplicate jobs might be causing CI failures:
> #1 ERROR: Error response from daemon: error parsing HTTP 429 response body: invalid character 'T' looking for beginning of value: "Too Many Requests (HAP429).\n"

https://github.com/ZcashFoundation/zebra/actions/runs/6646940836/job/18061386992?pr=7831#step:10:209

**Comment by teor2345** [comment]
Seems like this can also allow PRs to merge even if one of the duplicate jobs fails. That's definitely a bug.

This happened on PR #7831 but it still seems to be merging?
<img width="913" alt="Screenshot 2023-10-26 at 09 21 37" src="https://github.com/ZcashFoundation/zebra/assets/8951843/b5055b03-c36f-4f83-8cbc-d1b421951748">

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7816?planning-poker) with Zenhub @arya2 @gustavovalverde @oxarbitrage @teor2345 @upbqdn
