### ISSUE TITLE
Design: Work out how to suppress similar messages in zebrad's logs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#782]
In zebrad, we see a lot of repeated log messages, such as network errors or repeated block verification warnings. These repeated messages can hide other important messages.

Some of these errors are bugs, and we should fix them (repeated verifications).

But some errors aren't under our control (network). So it would be nice to summarise those messages in zebrad's text-based log output.

We could use a `tracing_subscriber::Layer` to:
* log and remember recent log messages
* suppress duplicates up to a fixed limit (1000) or fixed frequency (1 every 60 seconds)
* log the next message with an extra "summary" field, that says how many similar messages were received recently

See https://tracing.rs/tracing_subscriber/layer/trait.layer

As an example, tor's log message summaries look like:
> May 13 18:50:37.600 [warn] extrainfo_insert(): Bug: No entry found in extrainfo map. [1 similar message(s) suppressed in last 1800 seconds] (on Tor 0.2.7.1-alpha-dev 95a9920461dd3322)

**Comment by hdevalence** [comment]
@hawkw mentioned that there may already be an implementation of something similar to this, but I don't recall the details.

Personally I would prefer that we don't suppress any log messages, on the principle that the log represents a particular execution trace, and if some event is important enough to display under a particular tracing filter, it's important enough to be displayed on its own.

I definitely agree that currently zebrad often dumps way too many warnings into the log, but I suspect that we can do a lot better than we currently do, even for errors not under our control.

**Comment by teor2345** [comment]
While I agree with the principle, the output that we display for human consumption may need some filtering.

Sometimes, an error is more interesting if it's the first error of a particular kind (for example, an unexpected high block escaping our filter).

Sometimes, an error is more interesting if there are multiple errors of the same kind (for example, a network failure).

I also agree that we shouldn't be making those decisions for all our users. And perhaps the best place for these filters is in software that is designed to analyse logs.

**Comment by teor2345** [comment]
I don't think we need to resolve this issue: we've tended to just adjust log levels.
