### ISSUE TITLE
bug: Fix unreliable tests in coverage builds, and re-enable coverage reports

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7828]
### Scheduling

We haven't had coverage for a year and none of our developers think it is an important priority, so this ticket is optional.

### What happened?

I expected to see this happen:

Tests consistently pass in the coverage workflow.

Instead, this happened:

Some tests fail in unrelated PRs, including:
    primitives::redjubjub::tests::batch_flushes_on_max_items_test
    primitives::redjubjub::tests::batch_flushes_on_max_latency_test
    primitives::redpallas::tests::batch_flushes_on_max_items
    primitives::redpallas::tests::batch_flushes_on_max_latency
    transaction::tests::v4_with_modified_joinsplit_is_rejected

### What were you doing when the issue happened?

Making an unrelated change in PR #7819.

### Zebra logs

failures:
    primitives::redjubjub::tests::batch_flushes_on_max_items_test
    primitives::redjubjub::tests::batch_flushes_on_max_latency_test
    primitives::redpallas::tests::batch_flushes_on_max_items
    primitives::redpallas::tests::batch_flushes_on_max_latency
    transaction::tests::v4_with_modified_joinsplit_is_rejected

test result: FAILED. 111 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out; finished in 72.27s

https://github.com/ZcashFoundation/zebra/actions/runs/6645922313/job/18058933174#step:7:2868

### Zebra Version

zebrad 1.3.0 PR #7819

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

CI

### Additional information

I have turned off the coverage workflow and the coverage branch protection rule.

After this PR merges, coverage needs to be restored:
- [ ] Re-enable https://github.com/ZcashFoundation/zebra/actions/workflows/ci-coverage.yml
- [ ] Admin: add a branch protection rule for the coverage job

**Comment by mpguerra** [comment]
We need to figure out what kind of code quality metrics we want to provide and ensure that they are accurate.

Un-scheduling again for now.

**Comment by mpguerra** [comment]
This doesn't seem to be a priority
