### ISSUE TITLE
devops: Stop publishing doc.zebra.zfnd.org and change links to docs.rs/zebrad/latest

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7837]
### Describe the issue or request

As long as we do regular releases, https://doc.zebra.zfnd.org will be a duplicate of https://docs.rs/zebrad/latest (there are also docs.rs for the other Zebra crates). So there's no point in having it.

There are some bugs like #7048 that only happen in our docs.

The internal docs are still useful, because they show private items and all features for the `main` branch.

### Possible Solution

- [x] Change all the Zebra repository links for doc.zebra.zfnd.org to docs.rs/zebrad/latest
- [x] Remove the external docs job
- [x] Admin: remove the branch protection rule

**Comment by mpguerra** [comment]
@teor2345 do you still want to do this one during this sprint?

**Comment by teor2345** [comment]
There doesn't seem to be much else for me to do, and it's a quick change.

**Comment by teor2345** [comment]
> * Admin: remove the branch protection rule

I removed the branch protection rule because it won't be needed once the PR merges.
