### ISSUE TITLE
Add a `regtest()` constructor method to `Network`

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#7839]
## Motivation

This has been requested, and could be useful for testing.

### Possible Design

Add a method that returns a `Network::Testnet` with `Regtest` parameters.

**Comment by teor2345** [comment]
I don't think we should ~~make this change~~ add a Regtest variant to Network, I think we should add fields to the existing Testnet enum variant instead, like @arya2 and I talked about.

**Comment by arya2** [comment]
This is blocked on adding some of the hard-coded parameters that need to be changed for `RegTest` to the `Network::Testnet` variant in https://github.com/ZcashFoundation/zebra/issues/7845

**Comment by mpguerra** [comment]
Does the issue title accurately reflect what we are going to do here?
