### ISSUE TITLE
Implement ZIP 212: Allow Recipient to Derive Sapling Ephemeral Secret from Note Plaintext

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#785]
Changes Sapling note plaintexts, the sending of notes, the receiving of notes, and the first byte to the new version of (0x02) of the note plaintext. After activation of the [ZIP](https://zips.z.cash/zip-0212) as part of Canopy activation, these changes are MUSTs.

![image](https://user-images.githubusercontent.com/552961/88764630-46428500-d143-11ea-89d0-86489f3cb069.png)

![image](https://user-images.githubusercontent.com/552961/88764641-4f335680-d143-11ea-8d88-34c6bac60639.png)

![image](https://user-images.githubusercontent.com/552961/88764746-7f7af500-d143-11ea-8ca0-3659f8ad1a5d.png)

The consensus rule about shielded coinbases will be done as https://github.com/ZcashFoundation/zebra/issues/2362: 
![image](https://user-images.githubusercontent.com/552961/88764818-9c172d00-d143-11ea-8a7e-a89de3e9bb00.png)

https://zips.z.cash/zip-0212

**Comment by mpguerra** [comment]
Do we need this one for our Beta release or will this be part of the wallet support work?

**Comment by dconnolly** [comment]
We did part of this but we need to do the rest to encrypt shielded notes with a wallet.

**Comment by teor2345** [comment]
> We did part of this but we need to do the rest to encrypt shielded notes with a wallet.

@dconnolly can we open a separate ticket, so it's clear which parts we still need to do?

**Comment by conradoplg** [comment]
ZIP-212 was incorporated into the spec, so this should be part of https://github.com/ZcashFoundation/zebra/issues/269. I'll add a note there and close this
