### ISSUE TITLE
security: avoid hangs in the peer set and related code

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7858]
### Motivation

There are still some potential hangs in the peer set and related code.

### Specifications

Rust futures need to give a copy of their task waker to any code that could potentially wake the task.

### Complex Code or Requirements

Method calls shouldn't be skipped based on the outcomes of previous methods, unless the connection is shutting down.

### Testing

This is fairly straightforward, we need to check that each method that could wake the service or future is called.

We have existing tests that cover this code.

### Related Work

Follow up to #7772.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7858?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
@teor2345 Do you remember why we decided to move this to next Sprint (Sprint 24)? I see that we have PR #7859 open for this issue already which is why I've moved it back to this sprint (Sprint 23).

**Comment by teor2345** [comment]
> @teor2345 Do you remember why we decided to move this to next Sprint (Sprint 24)? I see that we have PR #7859 open for this issue already which is why I've moved it back to this sprint (Sprint 23).

It was a lower priority, and we thought other tickets would be ready earlier. (But it turned out they weren't.)

So it's fine to do this now, it's unlikely to extend into next sprint unless the review is both late and large.
