### ISSUE TITLE
feat(zebra-scan): Make the scanner send data to the results channel

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7907]
This task involves making the [previously created scanner task](https://github.com/ZcashFoundation/zebra/issues/7905) to send data to the [previously created results channel](https://github.com/ZcashFoundation/zebra/issues/7906). 

- [ ] Modify the scanner task to send its output data to the results channel
- [ ] Develop tests to verify that the scanner successfully sends data to the channel, and that the channel can correctly receive and handle this data.

**Comment by teor2345** [comment]
This ticket might not be needed, writing results directly to the database seems to work just fine for now.
