### ISSUE TITLE
feat(zebra-scan): Connect scanner with zebrad for block processing

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7908]
This task involves connecting the scanner task with `zebrad`, ensuring that it is initiated from within `zebrad` and that all incoming blocks are correctly routed to the scanner for processing.

To complete this task, we need to:

- [ ] Integrate the scanner task into `zebrad` start command, ensuring it is triggered and operates in coordination with the `zebrad` node.
- [ ] Verify that all incoming blocks within `zebrad` are sent to the scanner for further processing.
- [ ] Do local testing to confirm the functionality of this integration.

**Comment by teor2345** [comment]
> * Verify that all incoming blocks within `zebrad` are sent to the scanner for further processing.

What about verified blocks that are already in Zebra's cached state? We also need to scan them with every key (and re-scan with each new key we get).

Can we open tickets to decide on a scanning strategy for cached blocks, and add that implementation in another scanner task?

(We want the incoming task to wait on new blocks, so it's tricky to have it handle cached blocks as well.)

**Comment by teor2345** [comment]
@mpguerra I think that running the scanner in `zebrad` needs to be part of the MVP.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7908?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by mpguerra** [comment]
It's not clear that this needs to be in the MVP, unscheduling

**Comment by teor2345** [comment]
Are we going to run the scanner as a separate binary? That seems more complicated than running it from inside `zebrad`.

**Comment by teor2345** [comment]
As an alternative, we could remove "incoming blocks" from the scope of this ticket?

**Comment by upbqdn** [comment]
> As an alternative, we could remove "incoming blocks" from the scope of this ticket?

We excluded #7905 from the MVP, so we should remove that item from the scope of this ticket.

**Comment by teor2345** [comment]
This was done in PR #8040, except for some of the tests.

I moved the tests to #8022.
