### ISSUE TITLE
zebrad broadcasts an invalid User Agent in version messages

### ISSUE THREAD

**Issue by str4d** [ZcashFoundation/zebra#791]
Running `zcash-cli getpeerinfo` on one of my nodes, I found the following three peers:
```
  {
    "id": 101,
    "version": 170011,
    "subver": " Zebra 3.0.0-alpha.0 ",
    ...
  },
  {
    "id": 116,
    "version": 170011,
    "subver": "/btcwire:0.5.0/zfnd-seeder:0.1.2/",
    ...
  },
  {
    "id": 171,
    "version": 170011,
    "subver": "/MagicBean:3.0.0/",
    ...
  }
```
The `subver` field of the `version` message is meant to contain a [BIP 14 User Agent](https://github.com/bitcoin/bips/blob/master/bip-0014.mediawiki). `zebrad` is incorrectly setting it to what appears to be intended as a human-readable string.

(`MagicBean` is the User Agent for ECC's `zcashd` builds, to distinguish it from other `zcashd` builds. The ZF seeders similarly advertise themselves correctly, due to btcwire implementing full User Agent capabilities).

**Comment by str4d** [comment]
It looks like the user agent is intentionally set here:
https://github.com/ZcashFoundation/zebra/blob/4aa00ad21650d0b600da91a5330eeb1957dce481/zebra-network/src/constants.rs#L36-L37

I would suggest the following BIP 14-compatible replacement:
```rust
pub const USER_AGENT: &str = "/Zebra:3.0.0-alpha.0(🦓)/";
```

**Comment by str4d** [comment]
The unicode zebra does not show up in the output of `getpeerinfo` because `zcashd` tightly whitelists allowable characters in subversions further than BIP 14, to prevent XSS attacks. See https://github.com/zcash/zcash/blob/caea54013e8df02a9d9424d6496eb1ac6af069e2/src/net.h#L277-L281 and https://github.com/zcash/zcash/blob/68fd808e0ff7bf5d5e56dbb24d137f66737baca5/src/utilstrencodings.cpp#L24

**Comment by teor2345** [comment]
I added a follow-up ticket #794 to check that configured user-agent strings are correct.
