### ISSUE TITLE
Create a tutorial for forking the testnet blockchain

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7921]
Zebra lacks the same testing capabilities zcashd has; for example regtests or some sort of private network.
This kind of testing framework is relevant when testing features to be added in a future network upgrade.

We want to create a tutorial and add it to the zebra book, for now we have the following information wrote by @teor2345 in the user-defined-assets channel of the R&D discord: https://discord.com/channels/809218587167293450/809250978859319326/1169787608591765504

--------------------

At the Arborist meeting, we had a discussion about testing ZSAs, and what changes would be needed in Zebra. One way to test is forking the current testnet chain.

It would be the fastest way for QEDIT to start testing in Zebra, because the changes it needs are:
- Add a `Nu6` NetworkUpgrade enum variant
- add a testnet NU6 activation height
- add a new consensus branch ID for NU6
- increase the network protocol version

That's how we testnet NU5 on testnet, so the ZF and ECC developers on the call were confident it would work. It's also simpler, because there are no changes to the Network enum or its variants.

The drawback is that the testnet chain needs to be synced the first time the node runs. That takes around 3-8 hours for Zebra, but it takes a longer time for `zcashd`.

You'll also need at least one zcashd or external miner on the forked testnet. zcashd 's built-in miner is the easiest to configre. But both nodes support external mining via JSON-RPC calls.
💻 

Here are the steps to make these changes in Zebra, with example PRs from NU5:

Add a NU6 network upgrade variant and a random consensus branch ID:
https://github.com/ZcashFoundation/zebra/pull/1823/files
Set the activation height to a future height (or a past height), and the current network protocol version to 170110 for testnet (this PR does mainnet):
https://github.com/ZcashFoundation/zebra/pull/4390/files

If you'd like to merge that change into Zebra, please submit a PR, and we can add an `nu6` Rust feature before we merge. Or I can ask Pili if we can do the entire PR.

**Comment by oxarbitrage** [comment]
Another use case here is the following:

Consider i want to fork zcash to my own blockchain with the following simple properties: 

- Change the base coin name from `ZEC` to `ZZZ`. 
- Start my blockchain at block 1. 

The question will be if we should include and encourage this kind of forking in addition to fork to test new features for a future network upgrade.

**Comment by teor2345** [comment]
> Another use case here is the following:
> 
> Consider i want to fork zcash to my own blockchain with the following simple properties:
> 
> * Change the base coin name from `ZEC` to `ZZZ`.
> * Start my blockchain at block 1.
> 
> The question will be if we should include and encourage this kind of forking in addition to fork to test new features for a future network upgrade.

Forking the entire Zcash cryptocurrency (before genesis) is a much more complex use case, because it involves forking node software and wallets.

So it would help to just explain how to fork testnet to start with. If we need more complex instructions, we can open another ticket.
