### ISSUE TITLE
feat(zebra-state): Send a reference to latest non-finalized state in TipAction::Reset

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7927]
## Motivation

This is needed for the scanner task in zebra-scan (https://github.com/ZcashFoundation/zebra/issues/7905) to get any blocks in the non-finalized portion of the best chain when there is a `Reset` action without repeated calls to the state service.

### Possible Design

- Add the `latest_non_finalized_state` watch channel receiver
- Add a method on `LatestTipChange` that returns all the blocks in the latest non-finalized chain

This is acceptable because the worst-case scanning performance is 3 blocks per second, which means we can re-scan an entire non-finalized chain before the next block arrives. (Forks usually only happen every 300+ blocks.)

### Alternative Solution

This solution is more complex than we need.

<details>
<summary>Too complicated</summary>

Add a method on `LatestTipChange`:
  - accepting a previous block hash
  - check if it matches any previous_block_hash in the non-finalized best chain (follow the old chain from the tip until reaching a common ancestor block)
  - return all blocks after and including the block with a matching previous_block_hash, or 
  - return all blocks in the non-finalized best chain if it doesn't find the provided hash

</details>

## Related Work

This ticket is required for:
- #7934

**Comment by teor2345** [comment]
I think we're missing the ticket that this ticket enables:
- #7934

**Comment by arya2** [comment]
> I think we're missing the ticket that this ticket enables:

I was thinking this ticket could involve adding a method to be used instead of `wait_for_tip_change()` returning any new blocks on the chain that the receiver hasn't seen yet, so the task that scans new blocks as they come in would work for best chain changes too.

**Comment by teor2345** [comment]
@mpguerra did we decide to move this issue to a later sprint?

**Comment by teor2345** [comment]
I updated this ticket based on the current scanning speed. We don't need a complicated solution because it is fast enough:
https://github.com/ZcashFoundation/zebra/issues/7813#issuecomment-1837756994

**Comment by arya2** [comment]
@upbqdn @oxarbitrage I was wondering about adding a state request for getting the latest non-finalized state instead of adding it here, which makes more sense?

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
