### ISSUE TITLE
Workflow icons are broken in the README

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7931]
![1](https://github.com/ZcashFoundation/zebra/assets/21685097/85fd7c7e-e390-42fd-ae67-aa7c604ebab8)

This cause several other places to be broken too like the book https://zebra.zfnd.org/index.html, the dockerhub page https://hub.docker.com/r/zfnd/zebra and probably more.

We should fix or remove some/all of them.

**Comment by teor2345** [comment]
Oh yeah I noticed that recently.

This seems to have happened because we changed the workflow names, but we didn't do a search and replace in the docs for them. So maybe we could do that search and replace now.
