### ISSUE TITLE
change(zebra-state): When the best chain changes, scan all the blocks in the best chain fork

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7934]
## Motivation

When the best chain fork changes, we need to scan the blocks in that fork.

More precisely, we need to scan any blocks in that fork we haven't already scanned. (The difference matters when we've only partially scanned the old chain.)

Since our worst-case scanning is 3 blocks per second, we can scan the 100 blocks in the new fork in 33 seconds. This is less than the 75 second target block time. So we can just re-scan the entire non-finalized chain.

### Deleting Old Results

If we store the results by height, then the re-scanning will overwrite the existing entries for those blocks. But since we're storing by height and transaction index, we'll need to delete any transaction indexes that aren't present in the new chain.

The easiest way to do this is to delete all the indexes in the height range that has changed, for each key. Then clients will either get no results during re-scanning, or the latest fork's results.

**Comment by teor2345** [comment]
I updated this ticket based on the scanning speed in:
https://github.com/ZcashFoundation/zebra/issues/7813#issuecomment-1837756994

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
