### ISSUE TITLE
Add a state request to get the block hash, height, and transaction index from the transaction ID

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7943]
## Motivation

I don't think we need to store the block height or hash in the scanner storage. Using the transaction hash, we can get the block height and hash from the state, so there's no need to store it in the scanner as well.

### Suggested Design

Here's how we could do that state request:

We can use the transaction hash to look up `tx_loc_by_hash`, which gives us a `TransactionLocation` containing the block height (and transaction index). And we can get the block hash from the height. We have `read::find` methods for some of this already.

There are similar methods in the non-finalized state. This method should be for any chain, but prefer the best chain.

https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/state-db-upgrades.md#current-state-database-format

https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/service/read/find.rs#L129

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/7942#discussion_r1393416374_

**Comment by oxarbitrage** [comment]
I think this is optional initially but feel free to remove the label.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
