### ISSUE TITLE
Store decrypted scanning results in the scanner storage

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7944]
## Motivation

We want to store the decrypted results of scanning in the scanner storage.

### Complex Code

These types look pretty complicated, so it might help to use [`HashMap`'s entry API](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry).

It would be helpful to add type aliases for `SaplingSpend` and `SaplingOutput`, so we can change them later.

### Suggested Design

In `sapling_spend_results`, when `Nf` is `()` it should become `None`. 

```suggestion
    /// The new outputs created in each transaction, for each scanning key. 
    sapling_spend_results: HashMap<String, HashMap<Hash, WalletSaplingSpend>>,

    /// The spent outputs by each transaction, for each scanning key.
    /// If the scanning key is an individual viewing key (without a nullifier deriving key), there are no nullifiers in those results.
    sapling_spend_results: HashMap<String, HashMap<Hash, WalletSaplingOutput<Option<Nullifier>>>>,
```

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/7942#discussion_r1393420286_

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
