### ISSUE TITLE
feat(scanner): Read and store keys from config at zebra startup

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7946]
After we have a key storage and the keys in the config file we need to read them and add them to the database at zebra startup.

Tasks:

- [ ] Create a `Storage` instance and add the config keys to it.

Blocked on https://github.com/ZcashFoundation/zebra/issues/7941 and https://github.com/ZcashFoundation/zebra/issues/7904

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7946?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
