### ISSUE TITLE
Generate checkpoints from zebrad's block database

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#795]
## Motivation

Zebra currently generates checkpoints using a synced `zcashd` instance.

But it would be useful (and faster) for Zebra to generate its own checkpoints from `zebrad`'s cached state.

It might also be useful to be able to compare checkpoints generated by `zcashd` and `zebrad`.

## Suggested Design

Add a new `zebrad checkpoints` command that generates checkpoints from Zebra's cached state, using the existing state requests:
- `zebra_state::ReadRequest::Tip`
- `zebra_state::ReadRequest::BestChainBlockHash`
- `zebra_state::Request::Block` (or a new state request that just returns the serialized block size)

## Related Work

Another smaller alternative change is:
- #5852

**Comment by hdevalence** [comment]
> But it would be useful (and faster) for Zebra to generate its own checkpoints.

Just to clarify, do we need to interact with the zcashd data in order for Zebra to generate its own checkpoints? Could we ask a running zebrad instance instead?

Also, in order to know what blocks are at what height, wouldn't we need to maintain support not just for the raw block storage used by zcashd, but also for its internal leveldb indexes?

**Comment by teor2345** [comment]
> > But it would be useful (and faster) for Zebra to generate its own checkpoints.
> 
> Just to clarify, do we need to interact with the zcashd data in order for Zebra to generate its own checkpoints? Could we ask a running zebrad instance instead?

I was expecting either:
* a Zebra tool that read the cached blocks, or
* some kind of interface to a running zebrad instance.

We already have a lot of the code we'd need to do this in the CheckpointList class and zebra-checkpoints tool.

I didn't expect to use zcashd data, because that would make it hard to generate checkpoints only using zebrad.

**Comment by hdevalence** [comment]
I think we shouldn't do this, because it's a bunch of work to parse zcashd structures that we can avoid by making RPC calls to zcashd (as we currently do) and we only need to update the checkpoint list infrequently, so it's relatively unimportant.

**Comment by teor2345** [comment]
I think there's been a bit of confusion here, I was never talking about parsing `zcashd`'s cached blocks directly.

But you're right, this change is only worth doing if we want to:
* remove our dependency on `zcashd` and `zcash-cli`, or
* generate checkpoints using `zebrad`'s sled cache.

Since we don't generate checkpoints very often, this task isn't important, unless we want to be independent from `zcashd`.

**Comment by teor2345** [comment]
We might do this eventually, but it isn't needed any time soon. We can continue using `zcashd`.

**Comment by teor2345** [comment]
This is one of the alternatives we discussed for end of year work.

**Comment by teor2345** [comment]
@mpguerra this is one of the alternative `zebra-checkpoints` changes we discussed in the engineering sync.

This one is a bit more complicated than the other one, but it will perform better. (Performance probably doesn't matter, because we only generate the most recent ~100 checkpoints each release.)

**Comment by teor2345** [comment]
I think using Zebra's RPCs is good enough for now.
