### ISSUE TITLE
Put addresses from the peer's version message and remote IP in the connection cache, don't send them directly to the address book

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7951]
## Motivation

This prevents an attack where peers can repeatedly connect, supply an address in the version message, and fill the address book.

### Complex Requirements or Code

Potential drawbacks:

We might lose these addresses when the peer sends an addr message (but addr messages should always contain that peer's address, so in some cases we might lose the remote address of inbound connections). This is fixed in #7952 by adding all new addresses to the cache, taking any that are needed, then truncating the rest if needed.

These addresses are treated like gossiped addresses, so they have slightly higher priority. This is unlikely to have a significant impact, because their times will quickly become outdated by new addresses from this peer or other peers.

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7951?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn
