### ISSUE TITLE
Scan verified blocks from sapling activation to the tip

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#7953]
## Motivation

We want to scan all the blocks in the state, this is the ticket for scanning verified blocks from sapling activation to the tip.

### Suggested Design

Count from sapling activation height to `LatestChainTip.best_tip_height()`, ask the state for each block, then scan it. If there is no block for a height, wait 10 seconds, then try that height again in a loop.

Outside the state there is no distinction between finalised and non-finalised blocks, so this design will scan all of them.

## Out of Scope

- #7905

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/7953?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by arya2** [comment]
I blocked closing this on #7947, but most of the changes can be made without it.
