### ISSUE TITLE
Add a field for the network upgrade activation heights to `TestnetParameters`

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#7970]
## Motivation

This field is needed for configuring custom testnet activation heights without hard-coded changes or compilation features.

Depends-On: #7968

It addresses part of item 2 in https://github.com/ZcashFoundation/zebra/issues/8280:

> First of all TESTNET_ACTIVATION_HEIGHTS[Nu5] constant is modified in network_upgrade.rs#L113 from 1_842_420 to 1_060_755. If there are plans to make this list a config rather than const or somehow use FAKE_TESTNET_ACTIVATION_HEIGHTS

## Possible Design

- Add an `activation_heights` field to the `TestnetParameters` from #7968
- Add a configuration field in the `consensus` section for defining custom testnet activation heights or for enabling the [`ZFuture` network upgrade](https://docs.rs/zcash_primitives/latest/zcash_primitives/consensus/enum.NetworkUpgrade.html#variant.ZFuture) 
  - This could also be done separately as #7840

## Testing

Check that the parameters have not changed for Network::Mainnet or the default Testnet

**Comment by teor2345** [comment]
I thought we were going to have a discussion about these tickets first?

**Comment by arya2** [comment]
> I thought we were going to have a discussion about these tickets first?

Yes, I forgot to link the discussion (#7967) in the tracking issue. There was an older comment asking for just this issue.

**Comment by teor2345** [comment]
I don't think this is required for NU6 specifically?
