### ISSUE TITLE
Update the Zcash spec for fractional ToTarget() values

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#798]
## Motivation

In #572, we created a wrapper for the `nBits` field in the block header, and associated conversion functions.

## Edge Cases

The spec handles overflow for `ToTarget()` by producing a very large number, which does not fit in the size of a block header hash:
https://zips.z.cash/protocol/protocol.pdf#nbits

But zcashd's `CheckProofOfWork()` treats overflow the same as negative values and zero, by failing the threshold check:
https://github.com/zcash/zcash/blob/b4ec903ac4e27943b667291c34271b2275653bb1/src/pow.cpp#L122

We think the consensus rules cover this case, because the hash can never be higher than the PoWLimit. But some implementations might wrap or fail, which could cause consensus failures. (This is an implementation issue, not a spec issue.)

We also think that rejecting zero and negative compact values is required by the other consensus rules. (As long as zero is never a valid value for the proof of work threshold in a block header, which should be true in practice, because that would represent an impossible amount of work.)

## Spec Issues

It's also unclear what happens to fractional values of `ToTarget()`. It looks like zcashd truncates them to the next lowest integer.

So for spec correctness, we might want to:
- [ ] explicitly truncate fractional values towards zero

**Comment by teor2345** [comment]
Not blocked by any other tasks.

**Comment by daira** [comment]
Note that ToCompact is never called on a value greater than PoWLimit. Since the consensus rules require that only possible outputs of ToCompact can appear as `nBits` fields, that means that we'll only call ToTarget on such outputs. Does that help?

Yes ToTarget should call floor in the "otherwise" case.

I'm not sure I understand the rest of the issue.

**Comment by teor2345** [comment]
This got fixed in the spec a while ago.
