### ISSUE TITLE
Upgrade `hyper` to version 1.x.y in `zebra-rpc` and `zebrad` crate

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#7997]
## Motivation

The `hyper` team did a major release from 0.14.27 to 1.0.0 where significant changes were introduced, including some breaking changes, notably replacing the `Body` enum with a trait.

The proposed dependabot bumps [here](https://github.com/ZcashFoundation/zebra/pull/7966) have building issues with `hyper`.

What we did by now is to separate the rest of the upgrades in https://github.com/ZcashFoundation/zebra/pull/7996 so we can decide what to do here isolated from the rest of the bumps that had no issues. 

### Possible Solution

Upgrade guide: https://hyper.rs/guides/1/upgrading/

- Wait for jsonrpc-http-server to upgrade
- Replace jsonrpc crates with tonic and a [`Codec`](https://docs.rs/tonic/latest/tonic/codec/trait.Codec.html) impl for JSON

**Comment by mpguerra** [comment]
Blocked on https://github.com/paritytech/jsonrpsee/issues/1257

**Comment by mpguerra** [comment]
> Blocked on [paritytech/jsonrpsee#1257](https://github.com/paritytech/jsonrpsee/issues/1257)

This is now complete, should we work on this one soon?

**Comment by mpguerra** [comment]
This seems to have been done already
