### ISSUE TITLE
Re-use existing raw database code for the scanner, without splitting the state yet

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8001]
## Motivation

For a new database, we can re-use the existing state database code, and pass it a different state path and column family names.

We can use the existing binary serialization formats. Database lookups are fast. Concurrent writing just works.

### Rough Design

Here's a rough sketch of the minimum necessary code changes:
- Add `db_path`, `db_version`, and `column_family_list` arguments to `ZebraDb::new()`
- For example, `db_path` is `state` for `zebra-state`, and could be `private-scan` for `zebra-scan`. The other arguments are existing constants.
- Export `ZebraDb` from `zebra-state`

### Rejected Alternatives

If we re-used the existing state database, we could add a new column family name, and we don't need to change the state path. But the results are harder to delete, because they are mixed with publicly available cached data. This is a security issue.

## Related Work

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/discussions/7975#discussioncomment-7636554_

**Comment by mpguerra** [comment]
@teor2345 can you please add the estimate for this issue?
