### ISSUE TITLE
Bump version of `hyper` to v1

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8008]
## Motivation

Hyper has released it's v1 with some breaking changes, notably replacing the `Body` enum with a trait.

### Possible Solution

Upgrade guide: https://hyper.rs/guides/1/upgrading/

- Wait for jsonrpc-http-server to upgrade
- Replace jsonrpc crates with tonic and a [`Codec`](https://docs.rs/tonic/latest/tonic/codec/trait.Codec.html) impl for JSON

**Comment by oxarbitrage** [comment]
Duplicated of https://github.com/ZcashFoundation/zebra/issues/7997 
 
We might want to put the information here into there or vice versa but closing one of them.
