### ISSUE TITLE
Write scanning results to database

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8021]
After we have a database created in https://github.com/ZcashFoundation/zebra/issues/8019 and we have results from https://github.com/ZcashFoundation/zebra/issues/8018, we need to insert them to the database. 

This will be the issue that makes the connection between the scanning results and the persistent storage. Results can be written using the `Storage::add_sapling_result()` method.

Writing results to database files can block, so it should be wrapped in a `spawn_blocking()` function.

**Comment by teor2345** [comment]
I updated this ticket with the functions from PR #8036.

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate here?
