### ISSUE TITLE
feat(scanner): Start scanning where it left off last time

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8022]
## Motivation

We discussed in the Zebra team for the need of restarting a scan that was interrupted, left behind or if new keys are added to the config after a restart. Ideally the scan for a key should start around where it was left when applicable. 

### Suggested Design

A possible design might be:

- [x] Insert new keys into the database with the height before their birthday height (done in PR #8036)
- [x] Add a database method to get the last scanned height for each key in the database, by getting the last value in each key's range (based on the existing code for getting the first value in each key's range)
- [x] When scanning blocks:
  - Start from the lowest height for any key.
  - Only scan with the keys that haven't scanned that height already.

#### Testing

- [ ] Make sure cached blocks at or below the last scanned height aren't scanned
- [ ] Make sure cached blocks above the last scanned height are scanned
- [ ] Verify that all incoming blocks within `zebrad` are scanned
- [ ] Test with different heights for different keys

**Comment by teor2345** [comment]
I updated this design after the changes in PR #8036

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/8022?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I updated the tests based on what we skipped for other tickets. Feel free to open more tickets for those tests.
