### ISSUE TITLE
doc: Explain how to use a persistent state disk with Docker

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8023]
### Motivation

A user was surprised when their Docker run stopped and they couldn't find Zebra's state:
> Hi guys, do you know how can I resume Zebrad's sync? I've installed it trough docker and stopped at block 550000. But now I can't find Zebra's files/folders.

https://discord.com/channels/809218587167293450/809251029673312267/1179106203868090378

It would be helpful to tell users how to set up a persistent state disk in the Docker guide:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/user/docker.md

If we're going to change any configured paths inside the Docker image, we might want to do that first.

### Specifications

https://docs.docker.com/storage/volumes/

### Testing

Manually run the commands and check that the state is persistent.

**Comment by gustavovalverde** [comment]
@mpguerra this is what we talked about recently. So it might seem as we'll have to schedule it for next sprint, alongside:
- #4464
- #7534
- #7541

As all these will require a similar work.

_* It seems #4464 and #7534 are basically the same._

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/8023?planning-poker) with Zenhub @arya2 @gustavovalverde @oxarbitrage @teor2345 @upbqdn
