### ISSUE TITLE
slow test cleanup

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#803]
Right now a few of our tests, particularly our proptests it seems, take a while to run. For CI this isn't as big of a deal but Ideally I'd like to be able to run tests super quickly locally before push. We should investigate fixing up particularly long running tests if possible or setting them to `#[ignored]` by default so we only run the particularly slow tests in CI.

**Comment by teor2345** [comment]
I am very much a fan of this.

We could drop the iteration count for the slow proptests, it won't make much practical difference:
https://docs.rs/proptest/0.10.0/proptest/macro.proptest.html#example
