### ISSUE TITLE
security: Run the scanner it is own tokio executor, and use low-priority threads to avoid timing attacks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8043]
## Motivation

If we're using private keys during scanning, and running other public tasks in the same executor, that enables timing attacks. A timing attack guesses secret data by running secret and public tasks, and seeing how the timing is different when they run together.

## Suggested Solution

Run the scanner task and everything it accesses in their own tokio executors:
- [ ] Launch a separate tokio executor for the scanner task in `spawn_init()`, and make `init()` a private function
- [ ] Launch another tokio executor for the state buffer
- [ ] Launch a separate executor for any other services shared by the scanner task and the rest of `zebrad`

Run the scanning in a low-priority thread, so that a CPU-bound machine prioritises verification:
- [ ] Use `thread_priority::ThreadBuilder` to create a named minimum-priority thread
- [ ] Check that the scanner library uses low-priority threads internally

For example:
https://github.com/ZcashFoundation/zebra/blob/37ca967b6a4ba0a769b43abd4c2f6601306e4e5d/zebrad/src/components/miner.rs#L259-L273

Check that every blocking task in the scanner uses `spawn_blocking()`:
- [ ] Reading the storage
- [ ] Writing the storage
- [ ] TODO: check for other kinds of blocking tasks

These tasks don't need to use low-priority threads because they are disk-bound, not CPU-bound.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
