### ISSUE TITLE
Store scanner viewing keys in a separate file, and give them more restrictive file permissions

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8048]
## Motivation

Storing secret keys in the same file as non-sensitive configs makes it harder to secure those keys.

Since we are scanning using viewing keys, this is a transaction privacy issue, not a funds loss issue. 

### Suggested Solution

Best practice is to store the key or keys in separate files, and put the file paths in the config. Then the key files can have restrictive filesystem permissions, or be excluded from backups.

We could support multiple keys per file if we want, one per line.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
