### ISSUE TITLE
Change scanner database format so it is easier for users to query for transaction IDs

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8050]
## Motivation

We want technical users to be able to query the scanner database more easily.

This means:
- [x] each transaction ID should be in its own database row/entry
- [x] #8056

**Comment by mpguerra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Team-5fb24d9264a3e8000e666a9e/issues/ZcashFoundation/zebra/8050?planning-poker) with Zenhub @arya2 @oxarbitrage @teor2345 @upbqdn

**Comment by teor2345** [comment]
I manually checked this format using `ldb` and it appears to work:
https://github.com/ZcashFoundation/zebra/issues/8046#issuecomment-1844772654

**Comment by mpguerra** [comment]
@teor2345 can you please add an estimate to this issue?
