### ISSUE TITLE
test: Add database snapshot tests for the scanner database

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8069]
### Motivation

Add these snapshot tests to the scanner:
- [x] snapshot tests for the raw database format
- [x] snapshot tests for the typed database format
  - [x] after PR #8080 merges, add scanning progress markers to both snapshot tests

These tests already exist for the state, we just need to copy and paste and change the config to the scanner.

### Testing

These are new tests.

### Related Work

Split off #8037

**Comment by teor2345** [comment]
I'm doing the snapshot tests in this ticket.

**Comment by teor2345** [comment]
Only part of this is done.

**Comment by mpguerra** [comment]
@teor2345 can I get an estimate here also?

**Comment by teor2345** [comment]
This issue still isn't complete, I'm not sure why it keeps closing

**Comment by teor2345** [comment]
I split out #8102 because the snapshot tests are required and almost done, but the other database tests are a low priority.
