### ISSUE TITLE
Codespell is failing in all new PRs

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8081]
https://github.com/ZcashFoundation/zebra/actions/runs/7152640433

https://github.com/ZcashFoundation/zebra/actions/runs/7144702104/job/19458900909?pr=8079

**Comment by teor2345** [comment]
There is an open PR to fix this, but it often takes the maintainer 2-3 weeks to do a fix.
https://github.com/plettich/action-codespell/pull/3
https://github.com/plettich/action-codespell/pull/2

So I would just turn it off temporarily, and open a ticket to re-enable it later.

**Comment by gustavovalverde** [comment]
I was actually thinking on using the official action instead: https://github.com/codespell-project/actions-codespell 

I'll open this PR to test it out.
