### ISSUE TITLE
Compare config file and database after restart, act accordingly

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8101]
Currently we can have differences between the config and the database in regards to keys. This was part of https://github.com/ZcashFoundation/zebra/issues/8022 but it is moved to its own ticket.

- [ ] After the new keys are inserted, compare the keys in the database and in the config:
  - If keys are deleted from the config, don't start any scan for them, keep results if any.
  - If key is in both places, check the last scanned height from the database and scan up to tip from that height only.
  - (It is impossible for keys to only be in the config, because we waited for their birthdays to be inserted.)

Move was done because deleting things from the database can be complicated.

**Comment by mpguerra** [comment]
Just confirming that this issue is out of scope for the MVP?

**Comment by oxarbitrage** [comment]
> Just confirming that this issue is out of scope for the MVP?

Correct.

**Comment by mpguerra** [comment]
@oxarbitrage do we still need to do this now that we're separating the scanner out?

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
