### ISSUE TITLE
test: Add standard database tests to the blockchain scanner

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#8102]
### Motivation

Add these standard tests to the scanner:
- [ ] init blocking test: `db_init_outside_future_executor()` with the scanner init
- [ ] the scanner directory is created, add to the `ephemeral ()` test that checks `state` and `network` directories, but only when the `shielded-scan` feature is enabled 
- [ ] scanner database conflict test: `check_config_conflict()` with the same scanner database path 

#### Examples

Some of these tests might be useful.

The blocking tests are at the start, and the conflict tests are at the end of:
https://github.com/ZcashFoundation/zebra/blob/9acdf0e512fedd0a1bf939ec37a389d9bc68997b/zebrad/tests/acceptance.rs#L371-L2297

### Related Work

Split off #8069

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
