### ISSUE TITLE
feature:  Create new zebra-grpc crate

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8161]
### Motivation

We want to provide a modern RPC interface for the zebra-scan crate.

### Complex Code or Requirements

After some discussion in #8154 we have decide to use the `tonic` crate for this f

### Related Work

This is part of the next #7728 milestone to provide an RPC interface

**Comment by oxarbitrage** [comment]
Created placeholder in crates.io: https://crates.io/crates/zebra-grpc
