### ISSUE TITLE
feature: Implement `getinfo` method for new gRPC interface

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8162]
### Motivation

In order to get to grips with the new grpc library we want to implement a grpc server and a `getinfo` method.

### Related Work

This is part of #7728

**Comment by oxarbitrage** [comment]
Blocked on https://github.com/ZcashFoundation/zebra/issues/8161

**Comment by mpguerra** [comment]
@oxarbitrage are we all done here with #8178 or is there follow up work?
