### ISSUE TITLE
Stop the sync service downloading duplicate blocks

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#818]
At the moment, Zebra's sync service downloads and verifies duplicate blocks. These duplicate verifies cause the following errors in the verification services:

CheckpointVerifier:
* "block height has already been verified"  
* "no checkpoints left to verify"

But the BlockVerifier, ChainVerifier, and StateService silently re-verify duplicate blocks, replacing the existing state content.

Ideally, we should avoid downloading duplicate blocks. If that's not possible, we should stop verifying them.

TODO:
- [x] make BlockVerifier reject duplicate blocks, for consistency
- [x] track the list of pending hashes, add on download, use to filter, remove on success
- [x] remove from pending hashes on failure

See #819 for remaining TODOs.

**Comment by hdevalence** [comment]
Closing this since the checklist is completed.
