### ISSUE TITLE
feat(grpc): Implement a `registerkeys` grpc method

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8211]
For the service added at https://github.com/ZcashFoundation/zebra/issues/8203

**Comment by mpguerra** [comment]
@oxarbitrage how does this relate to #8176 ?

**Comment by upbqdn** [comment]
Yes, this issue seems like a copy of #8176 to me.

**Comment by oxarbitrage** [comment]
Apologies, i was not able to see it in the epic (https://github.com/ZcashFoundation/zebra/issues/7728). Corrected now, closing this one.
