### ISSUE TITLE
feat(scan): Support batched scanning

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#8221]
## Motivation

We currently don't perform batched scanning: https://github.com/zcashfoundation/zebra/blob/80827f5294603cca3d5e010bb2047617c2913991/zebra-scan/src/scan.rs#L233.

Depends on #8229.

## Suggested solution

Scan blocks using batches of keys https://discord.com/channels/809218587167293450/809251029673312267/1194795872681201714

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
