### ISSUE TITLE
Implement `Status` scan service to get information related to a key

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8226]
We want to do a `getstatus(keys)` grpc method to get information about the scanner task and database. For example, we want to know up to what height the scan was done, how many transactions were found and so on.

To implement the grpc we want to first do a `Status` scan service.

It will be good to present a draft of what are we planning to return before implementing.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
