### ISSUE TITLE
Extend `getresults` grpc

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8233]
In https://github.com/ZcashFoundation/zebra/issues/8163 we implemented the `getresults` api where we can get all the transactions we have for given viewing keys.

We want to extent that so we can query transactions from the given height to the tip or all transactions in a range of heights.

**Comment by oxarbitrage** [comment]
Blocked until https://github.com/ZcashFoundation/zebra/issues/8163 is done.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
