### ISSUE TITLE
Improve `scans_for_new_key` test

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8236]
## Motivation

This test doesn't currently check specific transactions in the results at specific heights. It also doesn't test if Zebra starts scanning for blocks from the start height when it's restarted after a key is registered but before the `scan_range()` task is finished.

This issue depends on correctly handling `ScanTask` restarts before a `scan_range()` task for a newly registered key is finished. See https://github.com/ZcashFoundation/zebra/issues/8238.

## Possible Design

- Use `ScanService` requests to register key and get results instead of `ScanTask`
- Check for known transaction ids and heights in the test
- Check that it returns scans all of the blocks in the required range when ScanTask restarts before the `scan_range()` task is finished

**Comment by arya2** [comment]
Split out adding the test to CI to #8274. The rest of this issue is blocked on handling restarts correctly (See #8238).

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
