### ISSUE TITLE
fix(scan): Canceled scanning tasks leave unscanned intervals

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#8238]
## Description

PR #8222 spawns a separate scanning task for each set of newly registered kyes. This task will scan the chain up to the height at which the keys were registered, while the main scanning task will scan the heights that come after the registration height. However, suppose the separate scanning task is canceled before it reaches the registration height. In that case, Zebra won't scan the interval between the height at which the task was canceled and the registration height unless the key is deleted and re-registered.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
