### ISSUE TITLE
Add tests for gRPC methods

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8244]
## Motivation

We want to have tests in CI to check that gRPC methods are working as expected. 

Note: There's already test coverage for most of the logic in methods that have been implemented, and the gRPC methods have been manually tested, this issue is for filling the remaining gaps.

## Possible Design

- Snapshot tests like those in `zebra-rpc`
- Acceptance tests (See [the changes in zebrad/tests/acceptance.rs here](https://github.com/ZcashFoundation/zebra/pull/8241/files#diff-b33295e5bb25fffe92ba36f21922285a10a387c43838477a2b1bcee48e9b3a4c) for calling these methods from acceptance tests)

**Comment by oxarbitrage** [comment]
Snapshots tests for the methods we had written were done at https://github.com/ZcashFoundation/zebra/pull/8277
Other snapshots tests will be added in the PR of the method itself (For example https://github.com/ZcashFoundation/zebra/pull/8268)

Unit tests foer the grpc methods will be done in a separated PR that will close this ticket.
