### ISSUE TITLE
Fix ZEBRAD_CACHE_DIR description

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#825]
The `ZEBRAD_CACHE_DIR` description gives an incorrect example of cached data.

We can't store the wallet in the cache directory, because caches can be deleted at any time.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/436_

**Comment by teor2345** [comment]
Blocked by #436, due to a potential merge conflict.

**Comment by teor2345** [comment]
Unblocked by removing the env vars entirely.

**Comment by oxarbitrage** [comment]
This is actually closed by https://github.com/ZcashFoundation/zebra/pull/827 as `enviroment-variables.md` file was removed. A new doc comment corrected the issue at https://github.com/ZcashFoundation/zebra/blob/main/zebra-state/src/lib.rs#L40-L43
