### ISSUE TITLE
Implement `Status` scan service

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8257]
We want to have scanning status for a set of keys, this is basically at what block the scanner task for the given key is at. 

We can get an approximate results for this with the scanner markers that are periodically inserted into the database to keep track of where we are when zebra restarts.

If we want something more exact we might need to send a command to the scanner task.

- [ ] Design
- [ ] Implement

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
