### ISSUE TITLE
Eliminate all of the zebrad environment variables

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#826]
I think we should eliminate all of these environment variables and use config settings.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/436_

**Comment by teor2345** [comment]
If we eliminate these environmental variables soon, then we'll stop building tests and scripts which depend on them.

**Comment by hdevalence** [comment]
Duplicate of #822
