### ISSUE TITLE
Use an alternative to optional fields in protocol buffer files

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8278]
In https://github.com/ZcashFoundation/zebra/pull/8266 we added an `optional` field to the spec, this is not supported in older versions of protoc. Several linux distributions are shipped with older versions of this software (for example Linux Mint 21.2 Cinnamon use the `libprotoc 3.12.4` version), which do not support the new feature. Upgrading the library is not that straightforward and if we decide to keep the optionals as it is, we should mention the change in the README as some users will have the following build error:

```
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: proto/scanner.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.\n" }

```

## Possible Design

One alternative is to use https://github.com/ZcashFoundation/zebra/pull/8266#issuecomment-1942973687 or remove the optional from the spec.

## Related Work

- #8272

**Comment by arya2** [comment]
The `optional` fields could be replaced with `oneof`, like:

```proto

message KeyWithHeight {
    // Scanning key
    string key = 1;
    // Birth height of the key
    oneof start_at {
        uint32 start_height = 2;
    }
}

```

Update: Just noticed the link in the issue.
