### ISSUE TITLE
Add snapshot tests for ClearResults, DeleteKeys, and RegisterKeys gRPC methods

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8285]
## Motivation

We want snapshot tests for all of the zebra-scan gRPC methods.

**Comment by oxarbitrage** [comment]
I dont think we need snapshot tests for the grpc calls that return empty responses. I do think we should add these to unit tests (i am working on it in another PR as part of  https://github.com/ZcashFoundation/zebra/issues/8244)

**Comment by oxarbitrage** [comment]
https://github.com/ZcashFoundation/zebra/pull/8293
