### ISSUE TITLE
Set up a Tauri app for Zebra

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8292]
Using [Tauri](https://tauri.app/) will allow us to provide a simple GUI with a webview and an installer for Zebra.

The initial implementation will cover:

#### Devops:
- [x] Setup CI for preview deployments of front-end
- [ ] Add a release workflow for building external binaries that should be included in the Tauri installer?
  - [ ] Build zebrad binary
  - [ ] Build prometheus and grafana external binaries
  - [ ] Build lightwalletd binary

#### Webview
- [x] #8331
- [x] #8332
- [x] Add tabs or navigation between pages
- [x] Add a form for the configuration that displays available options
- [ ] Display Grafana in an iframe (embed)

#### Tauri Backend
- [x] #8333
- [x] Bundle external binaries into Tauri installer
- [x] Add a command for updating Zebra's config and restarting Zebrad
- [ ] Add an app tray menu so the window can be closed without stopping Zebra
- [ ] Add Tauri updater for self-updating

**Comment by arya2** [comment]
Not everything has been completed but we'll open issues for the remainder in the zebra-app repository.
