### ISSUE TITLE
devops: Check GCP's CLI version as some VMs are not being created because of invalid arguments

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#8299]
### Describe the issue or request

We have the following error for a few weeks now: `argument --create-disk: Invalid flag value []` while creating the VM for the full sync, as in https://github.com/ZcashFoundation/zebra/actions/runs/7843642597/job/21404455889#step:11:76

### Expected Behavior

Create the VM with the required disks

### Current Behavior

GCPs CLI was updated, and now the VM creation has failing arguments

### Possible Solution

- Update the command to adapt to the new GCP CLI
- Downgrade and use an specific CLI version (if possible)

### Is this happening on PRs?

yes

### Is this happening on the main branch?

Not sure

**Comment by mpguerra** [comment]
how does this relate to #8302 ?

**Comment by gustavovalverde** [comment]
@mpguerra I'm closing this as #8302 is the actual real cause of this error.
