### ISSUE TITLE
add(rpc): Create documentation resource for all RPCs

### ISSUE THREAD

**Issue by upbqdn** [ZcashFoundation/zebra#8324]
## Motivation

Zebra now contains RPCs that are only documented in the API docs rendered at https://docs.rs/zebra-grpc/0.1.0-alpha.2/zebra_grpc/server/struct.ScannerRPC.html. These docs are Rust-specific and not suitable as general documentation for an RPC endpoint.

Zebra also implements JSON RPCs for lightwalletd: https://docs.rs/zebra-rpc/1.0.0-beta.35/zebra_rpc/methods/index.html; and JSON RPCs for mining, which are currently not rendered in the public API due to #8169. Note that the JSON RPCs are in a different crate than the gRPCs, which complicates discoverability.

`zcashd` renders its RPCs here: https://zcash.github.io/rpc/. Ideally, we should create a similar resource that would:

- be language-agnostic,
- contain the docs for all RPCs under one roof,
- render the docs directly from the source code.

It would be great if we found a tool that would fulfill the requirements above, and we could integrate it into CD.

**Comment by oxarbitrage** [comment]
I think we can close this and do the grpc in https://github.com/ZcashFoundation/zebra/issues/8407
