### ISSUE TITLE
research: Explore using zebra on disk database as a source of data for `zcash_client_backend`

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8359]
An alternative to https://github.com/ZcashFoundation/zebra/issues/8358 will be to make the `zcash_client_backend` to read and use the data in the Zebra on disk database. A replacement of this kind will make all functionality of the crate to remain working as it is but pulling the data from that source instead.

**Comment by mpguerra** [comment]
@upbqdn do you want to do anything else here?

**Comment by upbqdn** [comment]
Yes, I would like to look into this.

**Comment by upbqdn** [comment]
The conclusion is that we can read the state similarly to how we're going to do it in the scanner.
