### ISSUE TITLE
ci(fix): Warnings building in rust beta toolchain

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8379]
After the last rust upgrade we have a few warnings when building the internal docs. They are visible in all pull requests open after the upgrade for example in https://github.com/ZcashFoundation/zebra/pull/8376/files

![Screenshot from 2024-03-26 07-38-57](https://github.com/ZcashFoundation/zebra/assets/21685097/a3d31754-6df1-40f7-89cc-33bed05b1270)

This warnings do not block the merge of pull requests but we should fix anyways.

**Comment by mpguerra** [comment]
Let's work on this during Sprint 8

**Comment by oxarbitrage** [comment]
This is an issue in the rust beta toolchain. To reproduce:

```
rustup toolchain install beta
cargo +beta doc --no-deps --workspace --all-features --document-private-items
```

Also note this is not an internal error specific but also happens when we run the tests in ubuntu beta:

```
cargo +beta test
```

I added that to the ticket title.
