### ISSUE TITLE
Update dependabot groups to open PRs for ECC dependency updates separately

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8431]
## Motivation

Zebra's ECC dependencies usually have some breaking changes, or in some cases (for `zcash_proofs`/`zcash_primitives`) the updates need to be coordinated with `zcash_script` updates, so we usually need to split them out of prod dependency update PRs.

It would be easier to define them as their own dependency update group so they won't need to be split out manually.

**Comment by mpguerra** [comment]
done in #8433 and #8494
