### ISSUE TITLE
Update `getrawtransaction` RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8451]

**Comment by mpguerra** [comment]
closing in favour of #8945

**Comment by conradoplg** [comment]
We're not finished with `getrawtransaction`, we need to support additional fields in `verbose` mode. Should we reopen this, #8945, or create a new issue? @mpguerra

**Comment by mpguerra** [comment]
> We're not finished with `getrawtransaction`, we need to support additional fields in `verbose` mode. Should we reopen this, [#8945](https://github.com/ZcashFoundation/zebra/issues/8945), or create a new issue? [@mpguerra](https://github.com/mpguerra)

Let's reopen #8945 and create a new sub-issue for the additional fields
