### ISSUE TITLE
Fix warning when building zebra

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8455]
When executing `cargo build`, `cargo test` or similar i am getting since a while the following warning:

```
warning: /home/alfredo/zebra/bump_prod_whatwecan/zebra/zebra-utils/Cargo.toml: version requirement `0.9.34+deprecated` for dependency `serde_yaml` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion
```

This ticket is to research and fix it.

**Comment by gustavovalverde** [comment]
`serde_yaml` has been deprecated, thus we'll require a replacement for this one https://github.com/dtolnay/serde-yaml
