### ISSUE TITLE
Fix occasional `rejection_restores_internal_state_genesis` test failure on Windows

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8461]
## Motivation

This test occasionally fails on Windows:

https://github.com/ZcashFoundation/zebra/actions/runs/8820297906/job/24213599401#step:12:4731
https://github.com/ZcashFoundation/zebra/actions/runs/8808071916/job/24176434273?pr=8411#step:12:4695

This may be due to a bug in production code, or a bug in the test code.

**Comment by mpguerra** [comment]
Closing this for now, can reopen if it starts happening regularly again
