### ISSUE TITLE
Windows tests get stuck on pull requests updating github action files

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8496]
The windows tests are getting stuck in PRs that modify github action files.

https://github.com/ZcashFoundation/zebra/pull/8494
https://github.com/ZcashFoundation/zebra/pull/8433

We might want to disable the Windows tests from modifying this files or just run them, but it seems they don't even get started as theyare waiting for a status report that is never coming.

**Comment by gustavovalverde** [comment]
Solved with #8578
