### ISSUE TITLE
Review Zebra EOS halt in light of upcoming network upgrade

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8514]
We should revert and possibly decrease this value to ensure that there are no zebra versions running with old consensus rules after the end of the current protocol version which includes the devfund.

_Originally posted by @mpguerra in https://github.com/ZcashFoundation/zebra/pull/8429#discussion_r1594197341_

**Comment by mpguerra** [comment]
I'm not sure if we still need to do this now that we match zcashd again. 

The only outstanding question is whether zcashd reduces the EOS halt as a network upgrade approaches or it just relies on the network upgrade activation height to ensure there are no nodes running with old consensus rules and whether we should follow that approach.

So, if my understanding is correct, this means that we need to ensure that if the EOS halt for a zebra release falls beyond the date when we estimate the next network upgrade height will hit we should either:

a. include the next network upgrade activation height and consensus rules within this release
b. reduce the EOS halt period to happen before the estimated date for the next network upgrade activation height. 

As of today, there are ~26 weeks until the halving and potentially next network upgrade activation.

**Comment by upbqdn** [comment]
NU6 on Mainnet should come into effect at height 2,726,400, which falls on 2024-11-22. If we release Zebra 1.8 this week, there will be 20 whole weeks until NU6 activates on Mainnet, so we can go with the usual 16-week EOS period, and Zebra 1.8 will have halted four whole weeks before NU6.

If we will be releasing another Zebra version without support for NU6 in more than three weeks, we should lower the EOS then.

**Comment by mpguerra** [comment]
I'm going to move this issue to the next release sprint (Sprint 16) as a reminder

**Comment by mpguerra** [comment]
we've got this one covered with #8709
