### ISSUE TITLE
Move or remove the possibility of keys in the config file for scanning

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8584]
Option 1: The interaction between the user and the scanner will be only by the grpc server, we want to remove the config keys and related code.

Option 2: An alternative can be to leave the keys from the config file support but move it to the new `zebra-scanner` binary configuration file(https://github.com/ZcashFoundation/zebra/issues/8581).

**Comment by mpguerra** [comment]
we're not going to do this for now
