### ISSUE TITLE
Testing the new `zebra-scanner` binary

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8585]
We have some good test coverage for our blockchain scanner and most of them will keep working after we introduce a new binary (https://github.com/ZcashFoundation/zebra/issues/8581) however tests that relies on the scanner being started by zebrad will fail. We need to replace these by specific tests in the new binary scope. We may also want to add more tests and add the build of this binary into the CI.

More details to be added.

Note: https://github.com/ZcashFoundation/zebra/pull/8631 should be reverted if/when the `scan-start-where-left-test` test is restored.

**Comment by mpguerra** [comment]
@oxarbitrage what else do we need to do in order to close off this issue?

**Comment by oxarbitrage** [comment]
I think what we wanted to do here is actually done. 

What i will like to do at some point (and we can mark it as optional for now) is to add a test that checks the scanner behavior when we are synced up to the tip. This can be complicated to do so we will probably not do now. Do you want me to close this issue and open another one just for that ?

**Comment by mpguerra** [comment]
yes please!

**Comment by oxarbitrage** [comment]
Closing and opening https://github.com/ZcashFoundation/zebra/issues/8697 for the optional remaining test.
