### ISSUE TITLE
Delete in-memory state backend?

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#864]
The original motivation for the in-memory backend was to be able to use it to mock the real state backend in tests and to test against the real backend.  But to the extent that we need small-scale, deterministic mocking, we now have the transcript utility; for larger tests, there's no problem with using sled with a temporary directory; the complexity of maintaining a second backend we don't intend to use is large, etc.  So it seems like it would be better to remove it now rather than continuing to put more work into it.

TODO:
- [x] Move from tempdirs to temporary sled databases: #896 
- [ ] Replace each in-memory state with a temporary sled state
  - Use `zebra_state::Config { ephemeral: true, ..Default::default() }` to create a temporary state.
- [ ] Remove the in-memory state backend

**Comment by dconnolly** [comment]
Yiss, if we do this we can cut down on the RAM specs we currently have on the VMs running our containers on merge to #main

**Comment by hdevalence** [comment]
@dconnolly RAM usage should decrease since #887 now that we cap sled caching at 512MB by default.

**Comment by teor2345** [comment]
Each test will need an on-disk state in a different temporary directory.

I added a TODO for this change.

**Comment by hdevalence** [comment]
While looking up details for #888 I noticed that Sled has a config option that allows us to create an in-memory database on a ramdisk. Maybe we could use that?

**Comment by teor2345** [comment]
> While looking up details for #888 I noticed that Sled has a config option that allows us to create an in-memory database on a ramdisk. Maybe we could use that?

Sounds good, I've added that decision to the TODO list.

**Comment by hdevalence** [comment]
I think the right fix is to remove all the tempdir stuff and use a temporary Sled database. Created #896 .

**Comment by hdevalence** [comment]
This is clear to go now that #896 is closed.  Removing this sooner rather than later will cut down on the amount of code we have to touch as we fill in the state implementation.
