### ISSUE TITLE
Stop checking for duplicate blocks in sync and verifiers

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#865]
In #852 and #853, we made the `Sync` service and `BlockVerifier` check for known block hashes in the state.

But that's a costly check, because it might access the disk.

So once the sync service stops downloading so many duplicate blocks, we want to:
- [ ] Make the state service itself check for duplicate blocks, log an info-level message, and return success
- [ ] Delete any other duplicate block checks
- [ ] Turn any remaining duplicate block errors into successes (for example, `CheckpointVerifier`)
- [ ] Replace any remaining state checks with the cheapest possible request (see #862)

These changes should be made in the:
- [x] `Sync` service
- [ ] `ChainVerifier`
- [ ] `CheckpointVerifier`
- [ ] `BlockVerifier`

**Comment by hdevalence** [comment]
These changes were made in #887 for the sync service, but not for the checkpoint, chain, or block verifiers.

**Comment by teor2345** [comment]
We don't actually want to make these changes, because:
- on network-constrained nodes, it's cheaper to check the state, than to re-download a block
- on all nodes, it's cheaper to check the state, than to re-download a duplicate block, get a sync error, and then restart the entire sync

I have an upcoming sync PR that achieves the purpose of this ticket, without overloading the network so much.
