### ISSUE TITLE
docs: Update Zebra documentation for NU6

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8678]
### Motivation

There are likely a number of places in the documentation, including the README, that refer to NU5 as the latest network upgrade. We will need to update these once NU6 activates.

### Related Work

See #2372 for NU5 tasks

**Comment by oxarbitrage** [comment]
I don't see any reference to Nu5 in the readme. Do you know where do we need to make changes ?

**Comment by mpguerra** [comment]
> I don't see any reference to Nu5 in the readme. Do you know where do we need to make changes ?

I guess we removed references to the current network upgrade in the README a while back. I just did a quick search for "NU5" on our repo markdown files and we may not have to do any updates. Maybe just search everywhere in the code as a sanity check?

**Comment by mpguerra** [comment]
It seems like we don't have to update any documentation
