### ISSUE TITLE
Implement ZIP-253: Deployment of the NU6 Network Upgrade

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8695]
Implement final version of zcash/zips#878:

- [x] #8689 
- [x] #8681

**Comment by oxarbitrage** [comment]
It seems https://github.com/ZcashFoundation/zebra/issues/8689 and https://github.com/ZcashFoundation/zebra/issues/8681 are part of this major issue that could include more stuff as the ZIP is currently a draft PR: https://github.com/zcash/zips/pull/878

**Comment by mpguerra** [comment]
All tasks are now done. Closing
