### ISSUE TITLE
Create a test for when the scanner is at the tip

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8697]
We have a pretty good coverage of the scanner activity in the new binary, done in the context of https://github.com/ZcashFoundation/zebra/issues/8585, however we don't have any test that checks the behavior of the scanner at heights close to the tip. 

This is an optional test that might be a bit complex to set up so it is an optional task to do in the future.

**Comment by mpguerra** [comment]
We won't be doing any more work on the scanner
