### ISSUE TITLE
Add additional crate owners

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8707]
Currently we only have one named crate owner for zebra crates. We should add in @conradoplg also

**Comment by oxarbitrage** [comment]
Sent invites to be owner to @conradoplg of the 20 zebra crates:


- https://crates.io/crates/tower-batch-control
- https://crates.io/crates/tower-batch-cpu
- https://crates.io/crates/tower-fallback
- https://crates.io/crates/zcash_script
- https://crates.io/crates/zebra
- https://crates.io/crates/zebra-chain
- https://crates.io/crates/zebra-cli
- https://crates.io/crates/zebra-client
- https://crates.io/crates/zebra-consensus
- https://crates.io/crates/zebra-grpc


- https://crates.io/crates/zebra-network
- https://crates.io/crates/zebra-node-services
- https://crates.io/crates/zebra-rpc
- https://crates.io/crates/zebra-scan
- https://crates.io/crates/zebra-scanner
- https://crates.io/crates/zebra-script
- https://crates.io/crates/zebra-state
- https://crates.io/crates/zebra-test
- https://crates.io/crates/zebra-utils
- https://crates.io/crates/zebrad
