### ISSUE TITLE
Upgrade `zcash_protocol`/`zcash_primitives` to a version that includes the NU6 NetworkUpgrade variant without `zcash_unstable = "nu6"`

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8713]

**Comment by oxarbitrage** [comment]
I sent a PR for this: https://github.com/zcash/librustzcash/pull/1454 Let's see how it goes ...

**Comment by mpguerra** [comment]
Waiting on a release of librustzcash containing zcash/librustzcash#1454 and an upgrade of the same in zebra in order to close this one

**Comment by oxarbitrage** [comment]
I think we can upgrade zebra to the main librustzcash now. This change will block the release for us but it is what we agreed to do IIRC.
