### ISSUE TITLE
Add lockbox information to `getblock` RPC method

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8730]
We need to add a lockbox value pool field to the `getblock` RPC method.

https://github.com/zcash/zcash/pull/6912/files#diff-decae4be02fb8a47ab4557fe74a9cb853bdfa3ec0fa1b515c0a1e5de91f4ad0bR276

This is the value going to the lockbox in the requested block.

Update: Zebra do not keep track of the needed value balabce amounts for each block but only for the tip. This tracking is needed to create the `valuePools` object efficiently, doing this is a lot more work than expected. More info in https://github.com/ZcashFoundation/zebra/pull/8765. In discussions with the zcashd team we concluded this will be nice to have but is not critical. I changed the labels and the milestone to reflect this decisions and closed the corresponding PR attempt.

**Comment by mpguerra** [comment]
not a priority
