### ISSUE TITLE
Create and run manual NU6 Tests

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8736]
We have some coverage in the different NU6 pull requests, but we want to expand our testing.

The following list are manual and private tests, the result could be a report and not necesary any pull request: 
 - [ ] Private testnet/regtests: `zcashd` will be conducting these tests, so we will want to compare results with their findings.
 - [x] Manual diff tests of updated RPC methods: Use the `zcash-rpc-diff` tool available at [Zebra utils](https://github.com/ZcashFoundation/zebra/tree/main/zebra-utils#zcash-rpc-diff).

Snapshot tests are not included here, as they should be done in the same PR that modifies the related RPC methods.

Reports should be added as comments of this ticket.

**Comment by mpguerra** [comment]
I believe this was done. Please re-open if not!
