### ISSUE TITLE
devops: Migrate from Mergify to GitHub Merge Queues

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#8757]
### Describe the issue or request

We've moved out from [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#about-branch-protection-rules) to [Rulesets](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-rulesets) and Mergify does not support the latter.

### Expected Behavior

Mergify should work as expected

### Current Behavior

Mergify does not support rulestes, causing some odd behaviors while merging, and requiring us to keep using some protection rules just for the sake of keeping Mergify working.

### Possible Solution

As GitHub Merge Queues are already included in our subscription, we should test it and if the same behavior is kept, we should migrate as this would also free some of our budget.

### Is this happening on PRs?

Yes

**Comment by mpguerra** [comment]
@gustavovalverde should we close this one as a `wont-fix`?
