### ISSUE TITLE
Copy zcashd RPC tests and document how to run them

### ISSUE THREAD

**Issue by arya2** [ZcashFoundation/zebra#8779]
## Motivation

We want to improve Zebra's test coverage by running the zcashd RPC test framework with Zebra.

The first step is to move the tests into this repository, run them locally, document how to run them, and implement any basic infrastructure required to run them.

See: https://discord.com/channels/809218587167293450/1275444207368011778.

**Comment by oxarbitrage** [comment]
The following is a list with all the tests existing in the zcashd repository. The details of what RPC methods they call and what features are needed are detailed for each case (incomplete).
https://docs.google.com/spreadsheets/d/1F-KZuhGHvecpjzQ9PFeMLh8cJHaP8BxI3Kg0IWdBBuU

**Comment by oxarbitrage** [comment]
I think https://github.com/ZcashFoundation/zebra/pull/8866 may have closed this even if we didn't moved all the tests but just some of them.

Closing in favor of https://github.com/ZcashFoundation/zebra/issues/8781 where CI and further work could be done.
