### ISSUE TITLE
Tracking: RPC support for ZavaX Bridge

### ISSUE THREAD

**Issue by pacu** [ZcashFoundation/zebra#8859]
### Motivation

According to what Red.Dev engineers have responded, the bridge is currently using these four endpoints:

- [x] getblock
- [x] getblockhash
- [x] getblockcount
- [x] getinfo

I couldn't find a 1:1 replacement for get block count

According to documentation: https://zcash.github.io/rpc/getblockcount.html

```
getblockcount - Zcash 5.5.0 RPC
getblockcount

Returns the number of blocks in the best valid block chain.

Result:
n    (numeric) The current block count

Examples:
> zcash-cli getblockcount 
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblockcount", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:8232/
```

A reasonable implementation would be for them to use [et_best_block_height_and_hash](https://docs.rs/zebra-rpc/latest/zebra_rpc/methods/trait.Rpc.html#tymethod.get_best_block_height_and_hash). Would this be appropriate @arya2 ?

**Comment by oxarbitrage** [comment]
All RPC methods mentioned here are currently supported by zebra including `getblockcount`.

You can paste the [openapi spec](https://github.com/ZcashFoundation/zebra/blob/main/openapi.yaml) into a [swagger editor](https://editor.swagger.io/) to see what we currently support, which should be easier than reading the zebra source code or developer documentation.

**Comment by mpguerra** [comment]
@pacu can you please confirm whether our implementation of `getblockcount` satisfies the needs of the Red.Dev team? Happy to help out further and/or implement any missing functionality.

**Comment by pacu** [comment]
yes it does!

thanks @oxarbitrage for the open api link.
