### ISSUE TITLE
devops: re-integrate Sentry to our CD and Release nodes 

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#8862]
### Describe the issue or request

For multiple previous issues we've not been using Sentry for a while, but there are no longer any more roadblocks

### Expected Behavior

We should be notified about panics, race conditions or other non-expected behaviors in Zebra after we deploy our `main` branch nodes, and our releases nodes.

This will allow us to get notified on hard to identify errors happening on an ongoing basis in those "unattended" instances.

### Current Behavior

We don't have, nor plan to do, further integrations with Google Cloud Logging to classify errors in the application, making it hard to classify error information/logs.

### Possible Solution

As most the error handling and classification is easier to do with existing Sentry integrations, and considering Sentry is agnostic to cloud providers; this is a more feasible and general solution we should keep using and maintaining.

This might require:
- Updating existing code
- Enabling sentry in our nodes
- Configuring our Sentry account correctly

### Is this happening on PRs?

No

### Is this happening on the main branch?

Yes

**Comment by mpguerra** [comment]
this is now done
