### ISSUE TITLE
Make the state Config load unspecified fields from defaults

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#890]
I think the state Config should have whatever attribute makes serde load unspecified fields from defaults

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/859#issuecomment-673169825_

**Comment by teor2345** [comment]
@hdevalence should we have this attribute on all our configs, or just on state?

It seems wise to be consistent, and to reduce breaking config changes.

(If we ever need a deliberate break, we can delete an existing field, or rename it.)

**Comment by hdevalence** [comment]
I think we already do this for all of the other config structs.
