### ISSUE TITLE
Fix links in the release-checklist template

### ISSUE THREAD

**Issue by oxarbitrage** [ZcashFoundation/zebra#8934]
https://github.com/ZcashFoundation/zebra/blob/main/.github/PULL_REQUEST_TEMPLATE/release-checklist.md

Almost all links are broken, for example explorer link does not work anymore, several github action links that were moved or deleted, etc.

Will be good to fix this before the next release.

**Comment by mpguerra** [comment]
Let's do this as part of the next release. @upbqdn can you please take care of it as you'll be tagging the next release?
