### ISSUE TITLE
Implement `createrawtransaction` RPC method

### ISSUE THREAD

**Issue by mpguerra** [ZcashFoundation/zebra#8952]
## Motivation

This is required for zcashd deprecation. 

More details about this method can be found here: https://zcash.github.io/rpc/createrawtransaction.html

**Comment by elijahhampton** [comment]
I created a draft PR for this issue here: https://github.com/ZcashFoundation/zebra/pull/9017. Test will be submitted in the next commit.

**Comment by mpguerra** [comment]
it seems like this is not required to be implemented in zebra and should be implemented in the cli-wallet instead
