### ISSUE TITLE
Add support for temporary sled databases.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#896]
Sled has support for in-memory temporary databases.  We should use this instead of our current tempdir-based solution.

- [ ] Add a new option to `zebra-state::Config`:
```
/// Whether to use an ephemeral, in-memory store instead of writing to disk.
///
/// Set to `false` by default. If this is set to `true`, [`cache_dir`] is ignored and no state
/// is written to disk.  This is useful for testing but is otherwise probably not what you
/// want, unless you intend to load the entire blockchain into memory.
ephemeral: bool,
```

- [ ] Use the `ephemeral` variable to set https://docs.rs/sled/0.34.2/sled/struct.Config.html#method.temporary

- [ ] In `zebra-test`, replace the state `TempDir` configs with a config that sets `ephemeral = true`.
  - We'll need to keep the `TempDir`s for the tests that generate configs

**Comment by teor2345** [comment]
We also use TempDir for the generated configs in `zebra-test`, so I think we'll have to keep it as a test dependency.

I'll adjust the issue checklist.

**Comment by teor2345** [comment]
Sled's ephemeral feature doesn't actually guarantee an in-memory database. See #939 for details.
