### ISSUE TITLE
Dynamic tracing filters and extra tracing integrations

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#897]
This isn't a priority right now, but here are some notes for future improvements we should make to our tracing support. After https://github.com/tokio-rs/tracing/issues/894 merges, we'll be able to create a stack of reloadable, optional tracing layers. 

This means that we can:
- [ ] dynamically enable/disable flamegraph collection
- [ ] dynamically enable/disable formatted output
- [x] optionally support journald integration #561 
- [ ] optionally support opentelemetry for google cloud trace (https://cloud.google.com/trace/docs)

The ability to disable formatted output is useful when collecting flamegraphs, because both flamegraphs and formatted output use the same filter, so a more detailed filter for flamegraphs may result in too much output.

**Comment by teor2345** [comment]
@dconnolly just a reminder to split this issue into tickets so we can estimate it.

**Comment by mpguerra** [comment]
@gustavovalverde not one for now, but I'm just cleaning up the backlog and noticed this one for you in future

**Comment by teor2345** [comment]
We haven't needed any of these things for 2 years, and if we need them we'll open specific tickets.
