### ISSUE TITLE
Retcon new sync logic into RFC1

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#899]
The sync logic was fixed up in #887 and now RFC1 doesn't match the implementation.  Let's wait a bit to be sure we don't want to make even more changes, then retcon the design into the RFC.

Let's also remove the RFC template text from the RFC. We can:
- rewrite the RFC content to fit the template, or
- delete the template text

**Comment by teor2345** [comment]
@hdevalence should this task be in the first alpha release?

It seems like something we could leave for later. But it would be nice to do as soon as sync stabilises.

**Comment by dconnolly** [comment]
Defunct
