### ISSUE TITLE
bug: possible regression in the `test_sync_to_mandatory_checkpoint_mainnet` test

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#9001]
### What happened?

**I expected to see this happen:**
The test passing without hitting the 3 hours limit.

**Instead, this happened:**
By the 3 hours limit, the test is under 35% completion, which is a considerable regression.

### What were you doing when the issue happened?

Merging a PR

### Zebra logs

When I found the issue: https://github.com/ZcashFoundation/zebra/actions/runs/11660022609/job/32461809526
The earliest error found in the Workflow runs: https://github.com/ZcashFoundation/zebra/actions/runs/11589847031/job/32266635323
A previous commit where this was working: https://github.com/ZcashFoundation/zebra/actions/runs/11584155837/job/32473981901

### Zebra Version

2.0.1

### Which operating systems does the issue happen on?

- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### Additional information

We should look into this, and confirm if it's happening locally, and validate when this might have started.

**Comment by mpguerra** [comment]
we've not seen anything significant here
