### ISSUE TITLE
bug: some Zebra and Lightwalletd logs have changed, causing some tests to fail

### ISSUE THREAD

**Issue by gustavovalverde** [ZcashFoundation/zebra#9012]
### What happened?

 I expected to see this happen:
Tests passing

Instead, this happened:
Cached states are not being created as we're failing the disk creation if the expected logs are not found: 
- #8987

We have multiple regexes in Zebra for disk versioning, that are not being found:
- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-deploy-integration-tests-gcp.yml#L493
- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-deploy-integration-tests-gcp.yml#L493
- https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-deploy-integration-tests-gcp.yml#L493

And the [height of the disk](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-deploy-integration-tests-gcp.yml#L493), which varies by test:
- For [test_sync_to_mandatory_checkpoint_${NETWORK}](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L87) is `flushing database to disk .*height.*=.*Height.*\(`
- For [full_sync_mainnet](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L147), [zebrad_update_sync](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L186), [generate_checkpoints_mainnet](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L216) and [full_sync_testnet](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L252) is `current_height.*=.*Height.*\(`
- For [generate_checkpoints_testnet](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L295) is `zebra_tip_height.*=.*Height.*\(`
- For [lightwalletd_full_sync](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L327) and [lightwalletd_update_sync](https://github.com/ZcashFoundation/zebra/blob/main/.github/workflows/sub-ci-integration-tests-gcp.yml#L360) is `Waiting for block: `

### What were you doing when the issue happened?

CI was running

### Zebra logs

This is an example: https://github.com/ZcashFoundation/zebra/actions/runs/11725652272/job/32664982469#step:12:170 

### Which operating systems does the issue happen on?

- [x] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

**Comment by conradoplg** [comment]
The database version and height issues seems to be independent.

The database version issue [cause was pinpointed by @arya2](https://github.com/ZcashFoundation/zebra/pull/8987#issuecomment-2455438148), needs updating the test
