### ISSUE TITLE
Add documentation to `zebra_chain::amount`.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#908]
The module-level documentation for `zebra_chain::amount` should motivate and describe the API, paraphrasing https://github.com/ZcashFoundation/zebra/issues/126#issuecomment-582635560 and providing a worked example in the form of a doctest.  The doctest can replace existing tests.

This is low-priority, since it's just motivating the API we already have.

**Comment by dconnolly** [comment]
Done-ish
