### ISSUE TITLE
Remove `secp256k1` dependency from zebra-chain until we implement related functionality.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#910]
Currently `zebra-chain` depends on `secp256k1` in order to define `From<secp256k1::PublicKey> for TransparentAddress`, but we don't make any other use of the crate.

We should check this (@ZcashFoundation/zebra-team), but I think that because (a) signature verification is performed as part of script execution (b) we outsource script execution to C++ via `zcash_script` and (c) we don't implement any other transparent-related functionality, we won't make any other use of secp256k1 until (c) changes as part of wallet support.

Until then, we can cut down on code size and save a dependency by dropping the From impl and the dependency.

This is an easy change, but only *after* we determine that it's the correct one.

**Comment by teor2345** [comment]
Seems like a good idea, and it seems correct to me. (But I'm not as familiar with this area of the spec and code.)
