### ISSUE TITLE
Rewrite `block::tests::generate` as proptest strategies.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#919]
As noted in 64d9d5599298d63a03f47d4ca038a4645ca265fc, the existing `generate` functionality would be better expressed as a collection of proptest strategies, so that it's composable with other test code.

These strategies should be exposed as part of the crate API in test mode, so that they can be used by other crates (particularly `zebra_consensus`.

**Comment by teor2345** [comment]
This is not required, and there is a TODO in the code.
