### ISSUE TITLE
Tidy `zebra_chain::sapling` module structure.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#921]
Changes discussed on discord:

- [x] Rename `sapling::address::SaplingShieldedAddress` to `Address` and re-export it from the `sapling` module;
- [x] Make the `address` module private;
- [x] Make the `commitment` module private;
- [x] Re-export `CommitmentRandomness`, `NoteCommitment`, `ValueCommitment` from the `sapling` module;
- [x] Move `Diversifier` out of `key`s and into the module root (either by re-exporting or by moving the code;
- [x] Make the `keys::find_group_hash` and `keys::RANDOMNESS_BEACON_URS` items `pub(super)`;
- [x] Rename `EncryptedCiphertext` to `EncryptedNote`;
- [x] Rename `OutCiphertext` to `WrappedNoteKey`;
- [x] Add a `memo: Memo` field to `Note` and remove the `NotePlaintext` type;
- [x] Re-export `{Note, EncryptedNote, WrappedNoteKey, Nullifier}` from the `sapling` module;
- [x] Make the `note` module private;
- [x] Rename `tree::SaplingNoteTreeRootHash` to `tree::Root`;
- [x] Make `SaplingNoteCommitmentTree` private until we decide what shape the API should take (this can be `#[allow(dead_code)]` for now, there's no risk we'll forget to implement it);

**Comment by dconnolly** [comment]
#331
