### ISSUE TITLE
Keep cache_dir conversion errors in the zebrad acceptance tests

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#928]
don't think we should discard this error
```suggestion
                .wrap_err("tmp dir path cannot be encoded as UTF8")?
```

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/920#discussion_r472531767_

Note that the suggestion doesn't compile, but it might with a few tweaks.

**Comment by oxarbitrage** [comment]
The part of the code involved was removed at https://github.com/ZcashFoundation/zebra/pull/940 so this is not needed anymore.
