### ISSUE TITLE
Design: mempool transaction handling

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#936]
This is not strictly needed for 'Sync and Validate Mainnet' but is needed for 'behaving like a friendly node on the network', so probably before our first major release.

### Specification

This design should include the [ZIP-200](https://zips.z.cash/zip-0200) network upgrade mechanism for the mempool (#2374):
- [x] Reject transactions that are invalid for the current network upgrade
- [x] Clear mempool each time the network upgrade changes
- [x] Allow rollback and multiple activations of the same network upgrade
    - resolved by clearing the mempool every time the best chain changes

### Security

This design should resist the following attack:
1. A malicious peer sends lots of small "dust" transactions to Zebra
    - unlike fake valid blocks, fake transactions are cheap to generate and send
    - resolved using ZIP-401
2. Zebra broadcasts all those transactions to its ~50 peers, making them unready, and causing Zebra to open more peer connections
    - resolved by only broadcasting transaction IDs after validation
    - resolved by broadcasting transaction IDs (Zebra never broadcasts transactions)
3. Zebra's mempool becomes full, using excessive memory, or crowding out non-dust transactions
    - resolved using ZIP-401

**Comment by daira** [comment]
To be more precise, what's needed in order to behave like a friendly node on the network is to relay valid transactions. Keeping them around in memory is entirely optional.

**Comment by mpguerra** [comment]
Since we have now almost finished with our first implementation of the mempool, should this issue be turned into a documentation issue?

**Comment by teor2345** [comment]
> Since we have now almost finished with our first implementation of the mempool, should this issue be turned into a documentation issue?

Yes, we need to document how we deal with each of these security issues.

**Comment by teor2345** [comment]
I've updated the ticket with some notes.

**Comment by conradoplg** [comment]
I'm closing this since the mempool is finished. If there is any documentation required for the release candidate or stable release, please open a separate ticket
