### ISSUE TITLE
Turn errors from inbound requests into reject messages.

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#94]
Split out from https://github.com/ZcashFoundation/zebra/pull/83#discussion_r345503475

When a `Request` made by a peer server resolves to an error, the peer server should inspect the error and turn it into an appropriate `reject` message.  I believe it may already do some error inspection to test whether the inbound service is overloaded.

**Comment by dconnolly** [comment]
Related to #106

**Comment by hdevalence** [comment]
I think this is already done in https://github.com/ZcashFoundation/zebra/pull/106/files#diff-a1699d205a2a0cec572fa943cd26f32dR377
