### ISSUE TITLE
Demo: compare zcashd vs zebrad ludicrous speed on syncing 

### ISSUE THREAD

**Issue by dconnolly** [ZcashFoundation/zebra#950]
Demonstrate the wins from our novel async multithreaded architecture that has taken a little more time on our calendar to do well.

We need to refine the scope of how we want to do this, how complex we want to get. A straightforward, 'write some scripts, collect same-same data' might be good enough, and then recording the demo, and making sure this is reproducible. So maybe a workflow? Or VM? 

We should use `zcashd`'s Prometheus metrics support, see: https://github.com/zcash/zcash/pull/4947

**Comment by daira** [comment]
Looking forward to seeing this! :-)

**Comment by teor2345** [comment]
We'll do this outside the issue tracker.
