### ISSUE TITLE
Missing a LICENSE file

### ISSUE THREAD

**Issue by bobsummerwill** [ZcashFoundation/zebra#96]
Is this codebase a continuation of https://github.com/bobsummerwill/parity-zcash or a fresh codebase?

What is the LICENSE, please?  Thank you!

**Comment by hdevalence** [comment]
Hi there, this is a fresh codebase rather than a continuation of parity-zcash.  The code is dual-licensed as Apache2 or MIT, and the license metadata is in the [individual `Cargo.toml` files](https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/Cargo.toml#L5) but as you note we are missing a LICENSE file.  I will leave this issue open until we add it.

**Comment by bobsummerwill** [comment]
Thanks, @dconnolly.

Aside - what is the rationale for dual MIT/Apache licensing?

The MIT license is weaker than Apache 2.0, with no patent protection.

Is there a specific reason why you did not use ONLY Apache 2.0?  Thanks.

**Comment by hdevalence** [comment]
Apache2 or MIT is a standard licensing choice in the Rust ecosystem (e.g., it is the license for Rust itself), and in particular it means that the code is GPLv2-compatible. See https://doc.rust-lang.org/1.5.0/complement-project-faq.html#why-dual-mitasl2-license or https://github.com/sfackler/rust-postgres-macros/issues/19 for some more details.

**Comment by bobsummerwill** [comment]
Right - thanks.

And so because you have the Apache 2.0 licence, that is giving you the patent protection?

And the MIT license option is giving you compatibility with GPLv2, as well as the GPLv3 compatibility you get from Apache 2.0?

**Comment by bobsummerwill** [comment]
https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/5

graydon says:  Yeah, just to echo josh here: the MIT is almost a subset of ASL2 but not quite: GPLv2 compatibility is the one weird case that we needed to retain the nearly-redundant MIT for. Otherwise we’d just have gone ASL2.

SO NOW I KNOW :-)

**Comment by hdevalence** [comment]
Yep :)
