### ISSUE TITLE
Remove remaining references to BlockHeaderHash and BlockHeight

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#968]
In #905, we renamed `BlockHeaderHash` to `block::Hash` and `BlockHeight` to `block::Height`.

But there are still a few instances of the old names in comments, debug formatters, and tests. We should replace them with the new names.

**Comment by hdevalence** [comment]
Oops, my bad, I did this using the `rust-analyzer` rename feature and touched up references in comments that I saw while fixing up import paths, but I should have done `rg BlockHeight` or `rg BlockHeaderHash` to check for completeness that all of the references were gone.
