### ISSUE TITLE
Remove the zebra-consensus AddBlock order workarounds

### ISSUE THREAD

**Issue by teor2345** [ZcashFoundation/zebra#969]
I'm seeing a bunch of "there should be no holes in the current chain" panics during syncing.

I think these errors happen because the `CheckpointVerifier` verifies blocks in order, but the blocks are asynchronously committed by the `ChainVerifier`. So the actual commits can get out of order.

There are a few ways to resolve this issue:
* the block and checkpoint verifiers add blocks to the state
* the `ChainVerifier` can wait for the previous block to be committed to the state, ideally via a future from the state service, or
* the state service can queue blocks until the previous block arrives.

In the state design RFC #902, we decided that:
* the state service can queue blocks until the previous block arrives.

TODO:
- [x] Stop committing blocks in the chain verifier
- [x] Commit blocks in the checkpoint verifier
  - [x] Pass the state to the checkpoint verifier
  - [x] Commit any verified blocks in the returned future
- [x] Commit blocks in the block verifier

Optional:
- [x] Commit blocks in the state's call, not in the returned future
- [x] Panic in the state as soon as the chain gets out of order, rather than waiting to panic in the next block locator request
  - [x] Temporarily panic if there is a duplicate block at a particular height - *implied by the chain order check*

**Comment by teor2345** [comment]
@yaahc and @hdevalence: is there anything I can do to help move the state RFC forward?

Is the block order part of the RFC settled enough to implement now?

**Comment by hdevalence** [comment]
Yes, I think the only unsettled part is nailing down exactly what information the state should store to represent the treestate. @yaahc and I were planning to work through that tomorrow.

**Comment by teor2345** [comment]
I'm not sure if you've seen my questions on #902:
* [How can callers of `Request::CommitBlock` commit finalized blocks in order?](https://github.com/ZcashFoundation/zebra/pull/902/files#r479949736)
* [Where do the contextual validation checks happen, and how are they related to the other verification checks?](https://github.com/ZcashFoundation/zebra/pull/902/files#r479950334)

I re-read the RFC, tried to summarise the core design issues involved, and revised the possible design options.

Can we try to catch up tomorrow to talk through the design?

**Comment by hdevalence** [comment]
@teor2345 Nope, I hadn't seen those questions yet, sorry for missing them!

**Comment by teor2345** [comment]
Updated based on the design in #902.
