### ISSUE TITLE
Check that transaction::Hash logic is correct and then remove the TODO comment

### ISSUE THREAD

**Issue by hdevalence** [ZcashFoundation/zebra#972]
The `transaction::Hash` docs have a TODO comment about how transaction hashes are computed. We should check that the transaction hash computations are correct (I think we already have tests for this @zebra-team ?) and then remove the comment.

_Originally posted by @hdevalence in https://github.com/ZcashFoundation/zebra/pull/963#r480302848_

**Comment by teor2345** [comment]
The merkle tree implementation tests transaction hashes, and the comment has been deleted.
