### ISSUE TITLE
remove option to read config from current directory

### ISSUE THREAD

**Issue by yaahc** [ZcashFoundation/zebra#976]
This feature seems to be more trouble than it's worth

---

Here's a similar conversation from the last PR:
https://github.com/ZcashFoundation/zebra/pull/714#discussion_r458529306
https://github.com/ZcashFoundation/zebra/pull/714#discussion_r458529306

Using the current directory for the config is non-standard. And it seems to be more confusing than I expected.

I think it will be simpler for users to put a config in the one default location, or `-c config.toml`.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/974#discussion_r480717880_

**Comment by teor2345** [comment]
For more context, @yaahc and I both struggled to remember why we chose the original priority order - and we expect users will struggle to remember which order the configs are read in.

So let's just have one default config, and `-c explicit-config.toml`
